Update kubevirtCloudSpec to inject infraStorageClass info
kubermatic/kubermatic pull request #10006
Opened 2022-06-07 12:17 UTC by sankalp-r

**What does this PR do / Why do we need it**:
This PR introduces a new field `InfraStorageClasses` in `KubevirtCloudSpec` which holds the names of all the Kubevirt Infra-StorageClasses. Later this info is passed to `csi-driver-opeartor.yaml` for `kubevirt-csi-driver-operartor` ADDON creation.

**Does this PR close any issues?**:
Fixes #8546 

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Added support for storage classes initialization on KubeVirt user clusters that customers can use hot-pluggable disks.
```

Signed-off-by: Sankalp Rangare <sankalprangare786@gmail.com>

2022-06-07 16:25 UTC, sankalp-r commented
/retest

2022-06-07 20:25 UTC, sankalp-r commented
/retest

2022-06-07 21:18 UTC, sankalp-r commented
/retest

2022-06-08 08:35 UTC, mfranczy requested changes
overall looks good, just a small nit

2022-06-08 08:35 UTC, mfranczy commented on pkg/provider/cloud/kubevirt/storage.go
> +	InfraStorageClassAnnotation = "kubevirt-initialization.k8c.io/initialize-sc"
please make this a constant

2022-06-08 08:38 UTC, mfranczy commented
@sankalp-r please add unit tests as well, we have to finally start writing tests :)

2022-06-08 08:54 UTC, mfranczy approved these changes
/lgtm

2022-06-08 08:59 UTC, zreigz commented
/lgtm
/approve

2022-06-08 11:27 UTC, sankalp-r commented
/retest

2022-06-08 12:46 UTC, sankalp-r commented
/retest

2022-06-08 14:28 UTC, sankalp-r commented
/retest

2022-06-10 07:50 UTC, mfranczy commented
/lgtm

2022-06-10 08:08 UTC, ahmedwaleedmalik approved these changes
/approve ⚡

2022-06-10 09:19 UTC, ahmedwaleedmalik commented
/retest
Flake

2022-06-10 13:00 UTC, merged