WIP: Update kubevirt ccm config
kubermatic/kubermatic pull request #10215
Opened 2022-06-30 09:42 UTC by sankalp-r

**What does this PR do / Why do we need it**:
This PR updates kubevirt CCM config to remove infra-kubeconfig from ConfigMap and mount it as Secert on kubevirt-cloud-controller-manager.

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
```

2022-07-24 15:29 UTC, xrstf commented
What's the status of this PR?

2022-07-25 06:43 UTC, sankalp-r commented
> What's the status of this PR?

Waiting for this issue to finish: #9531

2022-07-25 10:48 UTC, mfranczy commented
@sankalp-r a new image has been published quay.io/kubermatic/kubevirt-cloud-controller-manager:v0.2.0

2022-07-25 13:46 UTC, mfranczy commented
/test pre-kubermatic-e2e-kubevirt-centos-1.24
/test pre-kubermatic-e2e-kubevirt-ubuntu-1.24

2022-07-25 14:10 UTC, sankalp-r commented
/retest

2022-07-25 16:25 UTC, mfranczy commented
I pulled your changes into a local cluster and it fails on
> Warning  ReconcilingError       37s (x33 over 3m27s)  kkp-kubernetes-controller                 failed to reconcile cluster: failed to ensure Deployment cluster-gxfgw9lbbd/kubevirt-cloud-controller-manager: failed waiting for the cache to contain our latest changes: timed out waiting for the condition

Looks like this is a very similar error to this what you had with network policy.

2022-07-25 16:46 UTC, mfranczy requested changes

2022-07-25 16:46 UTC, mfranczy commented on pkg/resources/cloudcontroller/kubevirt.go
> +	CloudControllerManagerInfraKubeconfigSecretName = "cloud-controller-manager-infra-kubeconfig"
Could you change this name? It's very long. 
Please change
`CloudControllerManagerInfraKubeconfigSecretName` to `KubeVirtInfraSecretName`
`InfraKubeConfigSecretKey` to `KubeVirtInfraSecretKey`

2022-07-25 17:04 UTC, mfranczy commented
/hold 

This PR doesn't have to land in KKP 2.21 (if it does then it's ok but it's not a must - fyi @xrstf)
I have to sync with upstream folks of KubeVirt CCM to discuss again credentials exposure.

2022-07-25 17:16 UTC, mfranczy commented
Overall speaking the direction is good IMO. However, I would change the way how you create a secret, but this brings one topic for sig-cluster-management discussion and the thing that all cloud configs with sensitive data are exposed as config maps instead of secrets.

2022-07-27 22:48 UTC, sankalp-r commented
/retest

2022-07-27 22:52 UTC, sankalp-r commented
/test pre-kubermatic-e2e-kubevirt-centos-1.24
/test pre-kubermatic-e2e-kubevirt-ubuntu-1.24

2022-07-28 06:52 UTC, mfranczy commented
/test pre-kubermatic-e2e-kubevirt-centos-1.24
/test pre-kubermatic-e2e-kubevirt-ubuntu-1.24

2022-07-28 08:51 UTC, mfranczy commented
@sankalp-r please add a release note that we move to new KubeVirt CCM.

@xrstf could your review as well? KubeVirt CCM needs two volumes, a cloud config that is a config map and a secret that is a kubeconfig to KubeVirt infrastructure cluster (where all vms are running). We agreed with @sankalp-r that we should create a new file secrets.go with tests for this purpose. So after all in configmap.go there is a creation of cloud config which has a path to the kubeconfig and in secrets.go there is a creation of kubevirt infra kubeconfig which is later add to the deployment of CCM.

2022-07-28 08:52 UTC, mfranczy commented
/lgtm
/approve

2022-07-28 10:27 UTC, ahmedwaleedmalik approved these changes
/approve ⚡

2022-07-28 11:30 UTC, mfranczy commented
/retest

2022-07-28 12:22 UTC, mfranczy approved these changes

2022-07-28 12:29 UTC, merged