updates the list of users for slack notification
kubermatic/kubermatic pull request #1023
Opened 2018-05-09 13:13 UTC by p0lyn0mial

**What this PR does / why we need it**: updates the list of users for slack notification

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

2018-05-09 13:14 UTC, p0lyn0mial commented on .drone.yml
> +      - thz=thz
If the names are the same not sure if we need mapping.

2018-05-09 13:15 UTC, mrIncompetent submitted a review, later dismissed

2018-05-09 13:47 UTC, kdomanski commented on .drone.yml
> +      - thz=thz
explicit > implicit

2018-05-09 15:12 UTC, metalmatze requested changes
Can we remove luk please?

2018-05-10 06:54 UTC, p0lyn0mial commented on .drone.yml
> +      - thz=thz
@kdomanski not sure if I understand your comment, these are the mappings that maps github users to slack users.

2018-05-10 06:56 UTC, p0lyn0mial commented
> Can we remove luk please?

goodbye luk :(

2018-05-10 07:07 UTC, mrIncompetent approved these changes

2018-05-10 08:42 UTC, metalmatze approved these changes

2018-05-10 08:42 UTC, metalmatze commented
Thanks!

2018-05-10 08:42 UTC, merged

2018-05-10 15:51 UTC, kdomanski commented on .drone.yml
> +      - thz=thz
I meant that it's better to map explicitly even when they're the same, rather than omit the entry from the list.