WIP - Add projectId suffix to binding subjects
kubermatic/kubermatic pull request #10625
Opened 2022-08-01 12:18 UTC by pkprzekwas

**What does this PR do / Why do we need it**:
Add project id suffix to role binding subjects to avoid unwanted role leaks.

**Does this PR close any issues?**:
Fixes #10602 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

2022-08-01 12:43 UTC, pkprzekwas commented
/retest

2022-08-01 13:40 UTC, pkprzekwas commented
/retest

2022-08-02 06:17 UTC, embik requested changes
Looks good, I think this should fix our issue. Just a very minor nit.

2022-08-02 06:17 UTC, embik commented on pkg/provider/userinfo.go
> +					groupName += "-" + projectID
Very minor and personal nit, but can we make this

```suggestion
					groupName += fmt.Sprintf("-%s", projectID)
```
?

2022-08-08 06:28 UTC, pkprzekwas commented
> Looks good, I think this should fix our issue. Just a very minor nit.

Corrected, as suggested.

2022-08-08 06:36 UTC, embik approved these changes
@pkprzekwas feel free to remove WIP status and add the 2.21 milestone if you think this is good to go, from my perspective it should fix our issue (although we should verify afterwards anyway).

2022-08-08 08:14 UTC, embik approved these changes

2022-08-08 09:01 UTC, pkprzekwas commented
/retest

2022-08-08 09:33 UTC, merged