improve event handling in external cluster controller, use reconciling framework for kubeconfig secrets
kubermatic/kubermatic pull request #10702
Opened 2022-08-09 11:05 UTC by xrstf

**What this PR does / why we need it**:
This PR

* ensures that we use our existing reconciling code to deal with the kubeconfig secrets
* ensures that all errors result in events on the ExternalCluster object
* improves logging slightly
* makes the filtering a bit easier to understand and re-use existing upstream filters

/kind cleanup

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

2022-08-12 12:00 UTC, xrstf commented
@imharshita ping

2022-08-12 12:18 UTC, imharshita commented
> @imharshita ping

will check today positiviely

2022-08-15 08:59 UTC, imharshita commented
/lgtm
/approve
@xrstf thanks for making the code better

2022-08-15 08:59 UTC, imharshita commented
/retest

2022-08-15 10:05 UTC, ahmedwaleedmalik approved these changes
/approve

2022-08-15 12:14 UTC, imharshita requested changes

2022-08-15 12:14 UTC, imharshita commented on pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
> +		return ok && externalCluster.Spec.CloudSpec.KubeOne == nil
```suggestion
		return ok && externalCluster.Spec.CloudSpec != nil && externalCluster.Spec.CloudSpec.KubeOne == nil
```

2022-08-15 14:59 UTC, xmudrii approved these changes

2022-08-15 15:30 UTC, imharshita commented
/lgtm

2022-08-15 16:33 UTC, merged