remove old code
kubermatic/kubermatic pull request #1088
Opened 2018-05-18 16:47 UTC by mrIncompetent

**What this PR does / why we need it**:
Removes old&dead code

**Release note**:
```release-note
NONE
```

2018-05-18 22:09 UTC, alvaroaleman requested changes

2018-05-18 22:09 UTC, alvaroaleman commented on api/pkg/resources/resources.go
> +const (
I prefer having one `const` block only

2018-05-22 11:04 UTC, mrIncompetent commented on api/pkg/resources/resources.go
> +const (
Its common practice to group constants by usage/meaning.
So i would prefer to have those 2 blocks

2018-05-22 11:19 UTC, p0lyn0mial approved these changes

2018-05-22 11:47 UTC, merged