Image loader tool
kubermatic/kubermatic pull request #1089
Opened 2018-05-18 21:06 UTC by alvaroaleman

**What this PR does / why we need it**:

Downloads, retags and uploads all docker images we currently deploy via the clusterController

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Partially resolves #1045

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

2018-05-22 10:32 UTC, mrIncompetent requested changes

2018-05-22 10:32 UTC, mrIncompetent commented on api/cmd/image-loader/main.go
> +	corev1 "k8s.io/api/core/v1"
We normally group imports:
- go-sdk
- others
- kubermatic
- k8s

2018-05-22 10:32 UTC, mrIncompetent commented on api/cmd/image-loader/main.go
> +	var printOnly bool
Should be moved out of the function and into a `var` block

2018-05-22 10:32 UTC, mrIncompetent commented on api/cmd/image-loader/main.go
> +	flag.StringVar(&masterResources, "master-resources", "../config/kubermatic/static/master/versions.yaml", "")
Why is this flag called `master-resources` when the default points to the `versions.yaml` ?

2018-05-22 10:32 UTC, mrIncompetent commented on api/cmd/image-loader/main.go
> +	flag.StringVar(&registryName, "registry-name", "", "Name of the registry to push to")
Please add an example which shows the format. Like `docker.io|quay.io`

2018-05-22 10:32 UTC, mrIncompetent commented on api/cmd/image-loader/main.go
> +		glog.Fatalf("Registry name must not be empty!")
Rather write `registry-name must not be empty` So there's no confusion about what `Registry` is

2018-05-22 10:32 UTC, mrIncompetent commented on api/cmd/image-loader/main.go
> +		glog.Fatalf("Error loading versions: %v", err)
include the path to the file in the error message. Unless that's already in `err`

2018-05-22 10:32 UTC, mrIncompetent commented on api/cmd/image-loader/main.go
> +			returnedImages, err := getImagesForVersion(versions, version)
We should log what versions we're processing

2018-05-22 10:32 UTC, mrIncompetent commented on api/cmd/image-loader/main.go
> +		if out, err := exec.Command("docker", "push", image).CombinedOutput(); err != nil {
Log the command you're going to execute

Other thing:
Should we add a retry logic?

2018-05-22 10:32 UTC, mrIncompetent commented on api/cmd/image-loader/main.go
> +		if out, err := exec.Command("docker", "tag", image, retaggedImageName).CombinedOutput(); err != nil {
Log the command you're going to execute

2018-05-22 10:32 UTC, mrIncompetent commented on api/cmd/image-loader/main.go
> +		if out, err := exec.Command("docker", "pull", image).CombinedOutput(); err != nil {
Log the command you're going to execute

Other thing:
Should we add a retry logic?

2018-05-22 10:32 UTC, mrIncompetent commented on api/cmd/image-loader/main.go
> +	cache.WaitForCacheSync(wait.NeverStop, serviceInformer.Informer().HasSynced)
You can replace the above 6 lines with the kubeInformerFactory functions.
```go
kubeInformerFactory.Start()
kubeInformerFactory.WaitForCacheSync()
```

2018-05-22 10:32 UTC, mrIncompetent commented
Do you want to add a Readme here or are you going to open a separate PR for it?

2018-05-22 10:45 UTC, metalmatze commented on api/cmd/image-loader/main.go
> +		if out, err := exec.Command("docker", "pull", image).CombinedOutput(); err != nil {
If you want to do retry logic I can highly recommend:
https://github.com/cenkalti/backoff

2018-05-28 10:54 UTC, alvaroaleman commented on api/cmd/image-loader/main.go
> +	flag.StringVar(&masterResources, "master-resources", "../config/kubermatic/static/master/versions.yaml", "")
The flagname is taken over from the cluster-controller cmd

2018-05-28 10:56 UTC, alvaroaleman commented on api/cmd/image-loader/main.go
> +		if out, err := exec.Command("docker", "push", image).CombinedOutput(); err != nil {
No, I'd argue the retry logic will be the user executing this tool again

2018-05-28 10:58 UTC, alvaroaleman commented
Regarding the readme I thought this would be a good candidate for our new hugo doc system, allhought it obviously makes sense to version it together with the code - We could probably keep it in both places for the time being and at some future point write some exporting logic that exports docs that are versioned here into the docs repo?

2018-05-28 11:03 UTC, mrIncompetent commented
Regarding the docs:
sgtm

@cbrgm where do we have to write our documentation so it gets published via Hugo?
Also where is the documentation available?

2018-05-28 11:04 UTC, mrIncompetent commented on api/cmd/image-loader/main.go
> +	flag.StringVar(&masterResources, "master-resources", "../config/kubermatic/static/master/versions.yaml", "")
Right, i think by now we could actually replace that flag by dedicated version&update flags.
Though something for another PR

2018-05-28 11:05 UTC, mrIncompetent commented on api/cmd/image-loader/main.go
> +		if out, err := exec.Command("docker", "push", image).CombinedOutput(); err != nil {
sgtm

2018-05-28 11:28 UTC, cbrgm commented
Documentation is available here https://github.com/kubermatic/docs/tree/kubermatic-docs.
You simply have to drop markdown files with some annotated meta data on top of the file into the `/content` folder. After that you can run the `hugo` command and it will generate all static website files into a folder called `/public`.

2018-05-29 14:23 UTC, p0lyn0mial commented on api/cmd/image-loader/main.go
> +	return &resources.TemplateData{Version: version,
how do we make use of `Version` ?
I think that `resources.TemplateData` doesn't have `Version` member.

2018-05-29 14:23 UTC, p0lyn0mial commented on api/cmd/image-loader/main.go
> +		imageSplitted := strings.Split(image, "/")
why not to check the length of `imageSplitted` ?

2018-05-29 14:24 UTC, p0lyn0mial commented on api/cmd/image-loader/main.go
> +	client := kubefake.NewSimpleClientset(objects...)
nice :)

2018-05-30 07:46 UTC, mrIncompetent commented on api/cmd/image-loader/main.go
> +	return &resources.TemplateData{Version: version,
Not anymore. The controller exclusively takes the version from the Cluster object.
The version/update handling got some polishing in https://github.com/kubermatic/kubermatic/pull/1095

2018-05-30 14:10 UTC, alvaroaleman commented on api/cmd/image-loader/main.go
> +		imageSplitted := strings.Split(image, "/")
Good point, added it

2018-05-30 14:11 UTC, alvaroaleman commented
@mrIncompetent @p0lyn0mial I think I addressed all comments, PTAL. Had to update some of the version loading logic because it got significantly changed in #1095

2018-05-30 14:14 UTC, mrIncompetent approved these changes

2018-05-30 14:50 UTC, merged