Enhance AKS external cluster status information
kubermatic/kubermatic pull request #10913
Opened 2022-09-01 19:23 UTC by hbernardo

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note

```

**Documentation**:

```documentation

```

2022-09-01 20:25 UTC, hbernardo commented
/retest

2022-09-06 09:10 UTC, imharshita commented on pkg/provider/cloud/aks/provider.go
>  	case provisioningState == string(resources.FailedAKSState):
lets remove this condition for error and replace it with warning:
`case provisioningState == string(resources.FailedAKSState) && string(powerState) == string(resources.RunningAKSMDState)`

2022-09-06 09:19 UTC, imharshita commented on pkg/handler/v2/external_cluster/aks.go
> +		case string(*nodePool.PowerState.Code) == string(resources.StoppedAKSMDState) && *nodePool.ProvisioningState == string(resources.SucceededAKSMDState):
message could be something like this:
`The cluster and node pools are in stopped.
You can only start or delete a stopped AKS cluster. To perform any operation like scale or upgrade, start your cluster first.`

2022-09-06 09:25 UTC, imharshita commented on pkg/handler/v2/external_cluster/aks.go
>  	}
```suggestion
                state := aks.ConvertMDStatus(*nodePool.ProvisioningState, *nodePool.PowerState.Code)
		md.Phase = apiv2.ExternalClusterMDPhase{
			State: state,
			AKS: &apiv2.AKSMDPhase{
				ProvisioningState: apiv2.AKSProvisioningState(*nodePool.ProvisioningState),
				PowerState:        apiv2.AKSPowerState(*nodePool.PowerState.Code),
			},
		}
		switch {
		case string(*nodePool.PowerState.Code) == string(resources.StoppedAKSMDState) && *nodePool.ProvisioningState == string(resources.SucceededAKSMDState):
			md.Phase.StatusMessage = "Power state is marked as 'Stopped' by Azure."
		case string(*nodePool.PowerState.Code) == string(resources.StoppedAKSMDState) && *nodePool.ProvisioningState == string(resources.FailedAKSMDState):
			md.Phase.StatusMessage = "Power state is marked as 'Stopped' and provisioning state is marked as 'Failed'. Please check on Azure side for previous operations on the node pool to resolve any failures."
		case state == WarningExternalClusterState:
			md.Phase.StatusMessage = "Despite the power state is 'Running', provisioning state is marked as 'Failed'. Please check on Azure side for previous operations on the node pool to resolve any failures."
		}
	}
```

2022-09-06 09:33 UTC, imharshita commented on pkg/handler/v2/external_cluster/aks.go
>  	}
plz make same changes to md

2022-09-06 09:37 UTC, imharshita commented
added a few comments, still reviewing..

2022-09-06 14:11 UTC, hbernardo commented
/retest

2022-09-06 14:48 UTC, imharshita requested changes

2022-09-06 14:48 UTC, imharshita commented on pkg/provider/cloud/aks/provider.go
> +		return apiv2.ErrorExternalClusterState // TODO: think about changing this to "Warning" and add other variables to decide if actual error, because there are cases that Azure states "Failed" for Prov
```suggestion
		case provisioningState == string(resources.StartingAKSState):
		return apiv2.StartingExternalClusterState
```
lets add `apiv2.StartingExternalClusterState` for both cluster and md

2022-09-06 14:48 UTC, imharshita commented on pkg/api/v2/types.go
>  type ExternalClusterMDPhase struct {
should we rename this ExternalClusterMDPhase => ExternalClusterMDStatus. wdyt? 
If yes, then we can rename 
AKSMDPhase  => AKSMDStatus

2022-09-06 14:48 UTC, imharshita commented on pkg/provider/cloud/aks/provider.go
> +	case provisioningState == string(resources.FailedAKSMDState) && !allNodesRunning:
if will think about this condition:
this basically says, if last operation failed and readyreplicas != replicas, then md state = failed,
suppose if last Upgrade operation fails, and hence readyreplicas != replicas , but still some nodes are ready, should we declare MD as Failed/Unusable

maybe when provisioningState == string(resources.FailedAKSMDState) and ready replicas == 0, then we can declare md as unusable
wdyt?

2022-09-06 18:34 UTC, hbernardo commented on pkg/provider/cloud/aks/provider.go
> +		return apiv2.ErrorExternalClusterState // TODO: think about changing this to "Warning" and add other variables to decide if actual error, because there are cases that Azure states "Failed" for Prov
This case is already being handled by line 231:
```
	case provisioningState == string(resources.StartingAKSState):
		return apiv2.ProvisioningExternalClusterState
```

2022-09-06 18:40 UTC, hbernardo commented on pkg/provider/cloud/aks/provider.go
> +		return apiv2.ErrorExternalClusterState // TODO: think about changing this to "Warning" and add other variables to decide if actual error, because there are cases that Azure states "Failed" for Prov
Anyway, I decided to add a similar one for MD

2022-09-08 12:24 UTC, hbernardo commented
/retest

2022-09-08 16:50 UTC, imharshita commented
/hold

2022-09-08 18:44 UTC, imharshita commented
/hold

2022-09-08 18:57 UTC, imharshita commented
/unhold
/retest

2022-09-08 21:13 UTC, merged