[release/v2.20] Fix vSphere integration and e2e tests
kubermatic/kubermatic pull request #10927
Opened 2022-09-06 10:08 UTC by ahmedwaleedmalik

**What this PR does / why we need it**:
Manual backport of https://github.com/kubermatic/kubermatic/pull/10918

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind bug
/kind failing-test

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

2022-09-06 12:13 UTC, embik requested changes

2022-09-06 12:13 UTC, embik commented on hack/ci/testdata/seed.yaml
> +          ipv6Enabled: true
needs to be removed.

2022-09-06 12:14 UTC, ahmedwaleedmalik commented on hack/ci/testdata/seed.yaml
> +          ipv6Enabled: true
Updated, good catch 😁

2022-09-06 12:19 UTC, embik approved these changes

2022-09-06 12:30 UTC, embik requested changes

2022-09-06 12:30 UTC, embik commented on hack/ci/setup-mla.sh
> +echodate "MLA is ready."
looks like `shfmt` isn't happy about the newline removal here.

2022-09-07 06:48 UTC, ahmedwaleedmalik commented
/retest

2022-09-07 07:13 UTC, ahmedwaleedmalik commented
/retest

Seems like a flake

2022-09-07 07:40 UTC, ahmedwaleedmalik commented
/retest

2022-09-07 15:58 UTC, ahmedwaleedmalik commented
/retest

2022-09-09 07:15 UTC, ahmedwaleedmalik commented
/retest

2022-09-09 09:04 UTC, ahmedwaleedmalik commented
@LittleFox94 Yes I'm investigating and working on fixing those failures. We don't have a 2.20 release planned anytime soon so I hope it's fine that your PR stick arounds for a little longer.

2022-09-09 09:47 UTC, ahmedwaleedmalik commented on pkg/test/e2e/ccm-migration/ccm_migration_test.go
> +	customTestTimeout       = 30 * time.Minute
Tried with 15 minutes, this is what we currently have in master, but it still timeouts although the migration worked fine.

2022-09-12 08:06 UTC, ahmedwaleedmalik commented
/retest

2022-09-12 08:26 UTC, xrstf commented
/override pre-kubermatic-ccm-migration-e2e

2022-09-12 08:39 UTC, xrstf commented
/lgtm

2022-09-12 08:40 UTC, merged