add EtcdLauncherNotEnabled phase to etcd restore
kubermatic/kubermatic pull request #11115
Opened 2022-09-30 14:00 UTC by PratikDeoghare

**What this PR does / why we need it**:
Adds `EtcdLauncherNotEnabled` phase to `EtcdRestore`. 

**Which issue(s) this PR fixes**:

Fixes #9665 

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
EtcdRestores are moved to a 'EtcdLauncherNotEnabled' phase if required etcd-launcher is not enabled
```

**Documentation**:

```documentation
TBD
```

2022-09-30 15:09 UTC, PratikDeoghare commented
/test pre-kubermatic-nodeport-proxy-e2e

2022-10-04 09:50 UTC, embik commented
Might be a stupid question, but why are we adding this? Understanding this phase on a restore object would require knowledge of the dependency on etcd-launcher, no? Otherwise this would - as a user - not really help me understand what's wrong.

2022-10-04 10:07 UTC, PratikDeoghare commented
> Might be a stupid question, but why are we adding this? 

This was considered the best of of all ways (that we considered) of informing user that their etcd-restore might be broken. 

See https://github.com/kubermatic/kubermatic/pull/9633#discussion_r852708342 

> Understanding this phase on a restore object would require knowledge of the dependency on etcd-launcher, no? 

Yes. 
They learn anyway by raising ticket after debugging broken restore for a while. 
This can inform them that something is wrong and they can search with that string to find some docs. 
Saving them some debugging and saving us some ticket would be good, no?

2022-10-04 10:10 UTC, embik commented
Yeah disregard my previous comment, I now remember the discussion after you've linked. My bad!

2022-10-04 10:11 UTC, embik requested changes

2022-10-04 10:11 UTC, embik commented on pkg/apis/kubermatic/v1/etcd_restore.go
>  // +kubebuilder:validation:Enum=Started;StsRebuilding;Completed
This needs to be updated to include the new phase. Will probably require updating the CRD codegen as well.

2022-10-04 11:53 UTC, embik requested changes
As is tradition with my reviews, I don't catch everything on first review. Apologies, but this should be fixed IMO.

2022-10-04 11:53 UTC, embik commented on pkg/apis/kubermatic/v1/etcd_restore.go
> +	EtcdRestorePhaseEtcdLauncherNotEnabled EtcdRestorePhase = "EtcdRestorePhaseEtcdLauncherNotEnabled"
Sorry I should have caught this earlier, but this should remove the `EtcdRestorePhase` prefix. It's not on the other phases either.

```suggestion
	EtcdRestorePhaseEtcdLauncherNotEnabled EtcdRestorePhase = "EtcdLauncherNotEnabled"
```

Same goes for the enum value of course.

2022-10-04 12:07 UTC, embik approved these changes

2022-10-04 12:52 UTC, merged