Fix membernotfound error
kubermatic/kubermatic pull request #11314
Opened 2022-11-07 23:01 UTC by imharshita

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note

```

**Documentation**:

```documentation

```

2022-11-08 08:41 UTC, xrstf requested changes
I don't understand the problem and the solution in this ticket. Please describe both in greater detail. Why do owner refs not work? Why do we suddenly need 2 finalizers? How does this work on shared and on separated master/seed systems?

2022-11-08 09:31 UTC, imharshita commented
> I don't understand the problem and the solution in this ticket. Please describe both in greater detail. Why do owner refs not work? Why do we suddenly need 2 finalizers? How does this work on shared and on separated master/seed systems?



> I don't understand the problem and the solution in this ticket. Please describe both in greater detail. Why do owner refs not work? Why do we suddenly need 2 finalizers? How does this work on shared and on separated master/seed systems?

- Problem: This problem is specific to users who are not owner/service account. 
for ex, I added existing user user@kubermatic.com as a editor member to my project x, then a binding will be created with x set as ownerref.
now if the admin someday decides to delete the user the binding will not be deleted, causing issues mentioned here: #8289 

> Why do we suddenly need 2 finalizers?:
finalizer on binding `finalizers: kubermatic.k8c.io/cleanup-seed-user-project-bindings` and 
ownerref: 
```ownerReferences:
  - apiVersion: kubermatic.k8c.io/v1
    kind: Project
```
finalizer on user:
```finalizers:
  - kubermatic.k8c.io/cleanup-seed-users
  - kubermatic.k8c.io/mla
 ```
 > How does this work on shared and on separated master/seed systems?:  as bindings have finalizer `kubermatic.k8c.io/cleanup-seed-user-project-bindings` once master userbinding is set to delete the seed ones will also get deleted

2022-11-08 14:18 UTC, xrstf commented
ClusterRoleBindings can exist in Kubernetes without either the subject or the ClusterRoles existing. Maybe the same should apply to UserProjectBindings. Maybe it's futile to hope that we will always have 100% referential integrity between resources. Kubernetes is meant to be _eventual_ consistent so maybe our controllers should just deal with objects missing instead of trying to enforce integrity.

The same applied to the Cluster validation webhook, which once tried to ensure that the referenced Project exists and is active. That turned out to be more problem than solution, as due to caching it is very easy to only see "half" of the reality inside the cluster. So we changed our approach and just _deal with it_(tm).

I don't fully understand the sequence of events that need to happen to trigger an issue here. @ahmedwaleedmalik maybe you can, you're more experienced with the API stuff.

2022-11-09 12:27 UTC, ahmedwaleedmalik commented
@imharshita as discussed, IMO adding finalizers is not really a long-term solution for this. And I agree with @xrstf's opinion in general specially `our controllers should just deal with objects missing instead of trying to enforce integrity`

2022-11-10 17:25 UTC, imharshita commented
Will fix this issue on dashboard repo, dealing with error made by api request

2022-11-10 17:25 UTC, closed without merging