WIP - New Machine Builder API
kubermatic/kubermatic pull request #11339
Opened 2022-11-10 13:49 UTC by xrstf

**What this PR does / why we need it**:
The old way we assembled ProviderSpec for MachineDeployments was to rely on API types (like apiv1.NodeSpec). These types were removed and KKP is being refactored to not rely on API types anymore.

To that end, this PR consolidates the remaining places where we assemble Machines and provide a new Go API to make creating machines much easier (hopefully).

**What type of PR is this?**
/kind cleanup

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
NONE
```

**Documentation**:
```documentation
NONE
```

2022-11-11 15:54 UTC, xrstf commented
/retest

2022-11-14 07:28 UTC, pkprzekwas commented on hack/ci/run-conformance-tests.sh
> +elif [[ $provider == "gcp" ]] || [[ $provider == "gcp" ]]; then
Looks like some leftover of replace function
```suggestion
elif [[ $provider == "gcp" ]]; then
```

2022-11-14 07:29 UTC, pkprzekwas commented on hack/run-conformance-tests.sh
> +gcp)
This case is duplicated.

2022-11-14 19:20 UTC, xrstf commented
/test pre-kubermatic-e2e-anexia-flatcar-1.25
/test pre-kubermatic-e2e-azure-ubuntu-1.25
/test pre-kubermatic-e2e-do-centos-1.25
/test pre-kubermatic-e2e-gcp-ubuntu-1.25
/test pre-kubermatic-e2e-hetzner-ubuntu-1.25
/test pre-kubermatic-e2e-kubevirt-centos-1.25
/test pre-kubermatic-e2e-nutanix-centos-1.25
/test pre-kubermatic-e2e-nutanix-ubuntu-1.25
/test pre-kubermatic-e2e-openstack-centos-1.25
/test pre-kubermatic-e2e-openstack-ubuntu-1.25
/test pre-kubermatic-e2e-packet-ubuntu-1.25
/test pre-kubermatic-e2e-vmware-cloud-director-ubuntu-1.25
/test pre-kubermatic-e2e-vsphere-ubuntu-1.25

2022-11-14 19:38 UTC, xrstf commented
/retest

2022-11-14 19:49 UTC, xrstf commented
/retest

2022-11-14 19:56 UTC, xrstf commented
/retest

2022-11-14 20:10 UTC, xrstf commented
/retest

2022-11-15 10:45 UTC, xrstf commented
/retest

2022-11-22 21:26 UTC, xrstf commented
/test pre-kubermatic-e2e-anexia-flatcar-1.25
/test pre-kubermatic-e2e-azure-ubuntu-1.25
/test pre-kubermatic-e2e-do-centos-1.25
/test pre-kubermatic-e2e-gcp-ubuntu-1.25
/test pre-kubermatic-e2e-hetzner-ubuntu-1.25
/test pre-kubermatic-e2e-kubevirt-centos-1.25
/test pre-kubermatic-e2e-nutanix-centos-1.25
/test pre-kubermatic-e2e-nutanix-ubuntu-1.25
/test pre-kubermatic-e2e-openstack-centos-1.25
/test pre-kubermatic-e2e-openstack-ubuntu-1.25
/test pre-kubermatic-e2e-packet-ubuntu-1.25
/test pre-kubermatic-e2e-vmware-cloud-director-ubuntu-1.25
/test pre-kubermatic-e2e-vsphere-ubuntu-1.25

2022-11-24 14:24 UTC, pkprzekwas requested changes

2022-11-24 14:24 UTC, pkprzekwas commented on pkg/machine/builder.go
> +	}
I'm not entirely sure if I understand this part of code. I would expect a different condition in the external `if` statement. Please double check me on that.
```suggestion
	datacenterName := b.datacenterName
	if datacenterName != "" && b.cluster != nil {
		if b.cluster.Spec.Cloud.DatacenterName != b.datacenterName {
			return nil, fmt.Errorf("explicit datacenter %q does not match cluster's datacenter %q", b.datacenterName, b.cluster.Spec.Cloud.DatacenterName)
		}
		datacenterName = b.cluster.Spec.Cloud.DatacenterName
	}
```

2022-11-28 11:02 UTC, xrstf commented on pkg/machine/builder.go
> +	}
Damn you're good. Thaat was indeed broken. I added some unit tests and fixed the function, should now be a bit easier to read.

2022-11-29 09:56 UTC, pkprzekwas commented
/retest

2022-11-29 10:20 UTC, pkprzekwas commented
/lgtm
/approve

2022-11-29 10:21 UTC, pkprzekwas commented
/retest

2022-11-29 12:57 UTC, xrstf commented
/override pre-kubermatic-test-integration

2022-11-29 14:20 UTC, xrstf commented
/retest

2022-11-29 15:09 UTC, merged