New field ClusterName in kubevirt providerconfig
kubermatic/kubermatic pull request #11453
Opened 2022-11-28 13:38 UTC by dermorz

**What this PR does / why we need it**:
This is needed for the machine-controller to set the new cluster labels. (see kubermatic/kubermatic#10923)

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
https://docs.kubermatic.com/kubermatic/main/architecture/supported-providers/kubevirt/kubevirt/
```
We have a draft document including all KubeVirt changes and a migration guide for KKP 2.22. That document will include the documentation for this feature.

2022-11-28 14:11 UTC, hdurand0710 commented
/test pre-kubermatic-e2e-kubevirt-ubuntu-1.25 
/test pre-kubermatic-e2e-kubevirt-centos-1.25

2022-11-28 14:55 UTC, hdurand0710 commented
/test pre-kubermatic-e2e-kubevirt-ubuntu-1.25
/test pre-kubermatic-e2e-kubevirt-centos-1.25

2022-11-28 16:49 UTC, hdurand0710 commented
/lgtm
/approve

2022-11-29 06:39 UTC, hdurand0710 commented
/hold 
Due to  pre-kubermatic-test-integration

2022-11-29 15:22 UTC, mfranczy approved these changes
/approve
/lgtm

2022-11-30 07:41 UTC, hdurand0710 commented
You might have to update now `CompleteKubevirtProviderSpec` to add the clusterName ?

2022-11-30 07:46 UTC, hdurand0710 requested changes
I suspect that the clusterName will not be in the MD on a create cluster flow.

2022-11-30 07:53 UTC, hdurand0710 commented
/test pre-kubermatic-e2e-kubevirt-ubuntu-1.25
/test pre-kubermatic-e2e-kubevirt-centos-1.25

2022-11-30 12:28 UTC, xrstf commented
/override pre-kubermatic-test-integration

2022-11-30 13:08 UTC, hdurand0710 commented
/lgtm

2022-11-30 14:16 UTC, hdurand0710 requested changes

2022-11-30 14:16 UTC, hdurand0710 commented on pkg/machine/provider/kubevirt_test.go
> +				expected: cloneBuilder(goodMachine).WithDNSPolicy("test-dnspolicy").WithClusterName("testcluster"),
s/"testcluster"/goodCluster.Name

2022-11-30 14:16 UTC, hdurand0710 commented on pkg/machine/provider/kubevirt_test.go
> +				expected:  cloneBuilder(goodMachine).WithDNSPolicy("keep-me-kubevirt").WithClusterName("testcluster"),
s/"testcluster"/goodCluster.Name

2022-11-30 14:38 UTC, hdurand0710 commented
/test pre-kubermatic-e2e-kubevirt-ubuntu-1.25
/test pre-kubermatic-e2e-kubevirt-centos-1.25

2022-11-30 14:50 UTC, hdurand0710 approved these changes
/lgtm

2022-11-30 14:50 UTC, hdurand0710 commented
/unhold

2022-11-30 17:05 UTC, merged