Addon controller
kubermatic/kubermatic pull request #1152
Opened 2018-05-30 16:42 UTC by mrIncompetent

**What this PR does / why we need it**:
Adds addon-controller

Whats open:
- [x] Add dockerfile for addons
- [x] Add sidecar container to controller-manager to copy Addons on init

Fixes #418

**Release note**:
```release-note
Introduced addon manager
```

2018-05-31 22:05 UTC, alvaroaleman requested changes

2018-05-31 22:05 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	GetAdminKubeconfig(c *kubermaticv1.Cluster) ([]byte, error)
Why be so low level instead of just leting the interface return a kubernetes clientset (`k8s.io/client-go/kubernetes`)?

2018-05-31 22:05 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +		if addon.Spec.Cluster.UID == obj.GetUID() {
Why not use a `ownerReference` instead of putting that into `Spec`?

2018-05-31 22:05 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	cluster, err := c.clusterLister.Get(addon.Spec.Cluster.Name)
Shouldn't we `.DeepCopy()` that as well?

2018-05-31 22:05 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	if cluster.Labels[kubermaticv1.WorkerNameLabelKey] != c.workerName {
Shouldn't we try to filter for that in the listers already? Like if the `workerName` is not an empty string, use a label selector that filters for `kubermaticv1.WorkerNameLabelKey == workerName`?

2018-05-31 22:05 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.Health == nil || cluster.Status.Health.Apiserver {
Shouldnt this be `|| !cluster.Status.Health.Apiserver`?

2018-05-31 22:05 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	infos, err := ioutil.ReadDir(manifestPath)
Why are these variables named `infos`/`info` instead of `manifests`/`manifest`?

2018-05-31 22:05 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +		reader := kyaml.NewDocumentDecoder(ioutil.NopCloser(bufferAll))
Forgive me if this a stupid question, but why do we need to know anything about yaml at this point?

Wouldn't it be easier to merge the contents of `combineManifests` into `getAddonManifests`, and making the latter just emit a big byte buffer, concatenating the inidvidual files using a `\n---\n` separator and doing the template rendering only once at the end for the concatenated set of files?

2018-05-31 22:05 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +		yamlBytes, err := yaml.JSONToYAML(jsonBuffer.Bytes())
Why go throught the hassle of converting this back to yaml?

2018-05-31 22:05 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	cmd.Stderr = os.Stderr
Why? This will just result in random output cluttering the logs. Better capture it and log if necessary, e.G. on failure

2018-05-31 22:05 UTC, alvaroaleman commented on docs/proposals/addon-controller.md
> +*   1 addon-manager pod per user cluster
Please use the word `One`

2018-05-31 22:05 UTC, alvaroaleman commented on docs/proposals/addon-controller.md
> +With the new addon-controller, we archive that:
`s/archive/achieve/g`

2018-05-31 22:05 UTC, alvaroaleman commented on addon-manager/migrate.sh
> -#!/bin/bash
How are we going to do migrations in the future?

2018-05-31 22:05 UTC, alvaroaleman commented on api/pkg/crd/client/clientset/versioned/typed/kubermatic/v1/fake/fake_addon.go
> +	testing "k8s.io/client-go/testing"
Why use named imports when not changing the name?

2018-06-01 08:14 UTC, metalmatze commented on api/pkg/crd/client/clientset/versioned/typed/kubermatic/v1/fake/fake_addon.go
> +	testing "k8s.io/client-go/testing"
Probably done by GoLand or some generator.

2018-06-01 09:41 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +	GetAdminKubeconfig(c *kubermaticv1.Cluster) ([]byte, error)
We don't need the clientset but we require the kubeconfig for `kubectl` later

2018-06-01 09:42 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +		if addon.Spec.Cluster.UID == obj.GetUID() {
We use owner reference as well.
But using a owner reference to express the target cluster in which the Addon should be installed in is not very explicit.

2018-06-01 09:43 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +		if addon.Spec.Cluster.UID == obj.GetUID() {
Though we set the owner reference too when creating the addon object

2018-06-01 09:44 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +	cluster, err := c.clusterLister.Get(addon.Spec.Cluster.Name)
We don't modify the cluster so not sure if that's useful

2018-06-01 09:45 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +	if cluster.Labels[kubermaticv1.WorkerNameLabelKey] != c.workerName {
Good point. It would make the whole handling of workers safer & we could enforce it at cmd level.
Though this is something for a follow up as this is the current way we do it for all controllers

2018-06-01 09:45 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.Health == nil || cluster.Status.Health.Apiserver {
Good catch!

2018-06-01 09:52 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +	cmd.Stderr = os.Stderr
We could use `cmd.CombinedOutput()` which would returns the output & the err.
We could log it then with `glog.V(6)`
WDYT?

2018-06-01 09:52 UTC, mrIncompetent commented on docs/proposals/addon-controller.md
> +*   1 addon-manager pod per user cluster
1 word to rule them all

2018-06-01 09:54 UTC, mrIncompetent commented on addon-manager/migrate.sh
> -#!/bin/bash
The existing migrations are doable via the `kubectl --prune` feature

2018-06-01 09:54 UTC, mrIncompetent commented on api/pkg/crd/client/clientset/versioned/typed/kubermatic/v1/fake/fake_addon.go
> +	testing "k8s.io/client-go/testing"
codegen via `./hack/update-codegen`
Its the kubernetes client code generation

2018-06-01 12:33 UTC, alvaroaleman requested changes

2018-06-01 12:33 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +		if addon.Spec.Cluster.UID == obj.GetUID() {
> But using a owner reference to express the target cluster in which the Addon should be installed in is not very explicit.

What kind of explicitly are you lacking? I find it rather redundant to do both.

2018-06-01 12:33 UTC, alvaroaleman commented on addons/Dockerfile
> +ADD ./canal /addons/canal
why not just `ADD .`/addons/` and use a `.dockerignore` for what we dont want?

2018-06-01 12:33 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	if cluster.Labels[kubermaticv1.WorkerNameLabelKey] != c.workerName {
Created an issue for that: https://github.com/kubermatic/kubermatic/issues/1166

2018-06-01 12:33 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	cluster, err := c.clusterLister.Get(addon.Spec.Cluster.Name)
What does that have to do with writing or not writing? The `cluster` object can change, afaik the `.DeepCopy()` is used to guarantee a consistent view on the object throughout the sync loop. For writes its actually more likely to fail if you `.DeepCopy()` it because you may not have the newest ressource version anymore

2018-06-01 12:33 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	infos, err := ioutil.ReadDir(manifestPath)
?

2018-06-01 12:33 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +		reader := kyaml.NewDocumentDecoder(ioutil.NopCloser(bufferAll))
?

2018-06-01 12:33 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +		yamlBytes, err := yaml.JSONToYAML(jsonBuffer.Bytes())
?

2018-06-01 13:09 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +		if addon.Spec.Cluster.UID == obj.GetUID() {
> 	// List of objects depended by this object. If ALL objects in the list have
	// been deleted, this object will be garbage collected. If this object is managed by a controller,
	// then an entry in this list will point to this controller, with the controller field set to true.
	// There cannot be more than one managing controller.

The OwnerReference is a slice which is used for garbage collection.
The Addon must point to exactly one Cluster.

We could express it via OwnerReference, but that's simply not the use-case of OwnerReferences in Kubernetes.

2018-06-01 13:10 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +	infos, err := ioutil.ReadDir(manifestPath)
Ah missed that comment.
Because the ReadDir returns FileInfo objects, which only contain infos about the files in the specified directory.

2018-06-01 13:11 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +		reader := kyaml.NewDocumentDecoder(ioutil.NopCloser(bufferAll))
yaml supports multi-document files. json don't afaik.

2018-06-01 13:13 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +		reader := kyaml.NewDocumentDecoder(ioutil.NopCloser(bufferAll))
I want to support multi-document yaml files as input - its a fairly common practice in kubernetes to offer them.
And as we need to modify each single document, we need to split them

2018-06-01 13:13 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +		yamlBytes, err := yaml.JSONToYAML(jsonBuffer.Bytes())
json does not support multi-document files afak

2018-06-02 11:50 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +		if addon.Spec.Cluster.UID == obj.GetUID() {
Hm okay, that is true. It still feels sort-of wrong to have a `cluster` field in the spec, because that is not a property of the addon, its metadata. Was there a reason why we couldn't simply make the addons namespaced and thus derive the cluster from the namespace?

2018-06-04 08:09 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +		if addon.Spec.Cluster.UID == obj.GetUID() {
The namespacing is mainly for organizational purpose not for expressing relationship.
As Clusters are not namespaced in upstream, that should be the way to go for us as well.

Therefore using the namespace would not be enough.

2018-06-04 09:06 UTC, alvaroaleman approved these changes

2018-06-04 09:31 UTC, merged