Reconcile vSphere Tags and Tag Categories
kubermatic/kubermatic pull request #11790
Opened 2023-01-30 16:17 UTC by moadqassem

**What this PR does / why we need it**:
In a previous iteration, a new reconciliation framework has been introduced for the vSphere cloud provider. This PR reconcile all Tags and Tag Categories that are attached to any vSphere user cluster, where we stopped creating those tag categories unconditionally and we demand that, this category is created before hand and passed on to the user cluster.

vSphere cloud provider will make sure that the category exists before moving forward with the reconciliation and make sure that whatever tag is added to this cluster, is gonna be created in that category if it doesn't exist and upon cluster updates or deletion, we make sure that, those delete tags are synced and only delete tags that are attached on the cluster level.    
**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind cleanup
/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Cleanup default tag categories creation and only create tags in the tag category which assigned on the user cluster level
```

**Documentation**:

```documentation
None
```

2023-01-30 17:37 UTC, xrstf approved these changes
/approve

2023-01-30 22:04 UTC, moadqassem commented
/hold

2023-01-31 01:10 UTC, moadqassem commented
/retest

2023-01-31 07:39 UTC, ahmedwaleedmalik requested changes

2023-01-31 07:39 UTC, ahmedwaleedmalik commented on pkg/provider/cloud/vsphere/provider.go
> +	tagCleanupFinilizer = "kubermatic.k8c.io/cleanup-vsphere-tags"
s/tagCleanupFinilizer/tagCleanupFinalizer

2023-01-31 15:27 UTC, ahmedwaleedmalik approved these changes
/approve

2023-01-31 17:54 UTC, merged

2023-02-17 08:30 UTC, embik commented
@moadqassem it seems that this PR changed provider behaviour (i.e., categories need to be created beforehand). Shouldn't this require a documentation change then?

2023-02-17 08:31 UTC, embik commented
It's also unclear if the API changes in this PR require a migration of existing clusters. @WeirdMachine and I are not sure about that.