add Azure support
kubermatic/kubermatic pull request #1200
Opened 2018-06-07 16:51 UTC by kdomanski

**Release note**:
```release-note cloud provider
Added Azure support
```

2018-06-08 06:24 UTC, mrIncompetent commented on api/pkg/provider/cloud/azure/provider.go
> +	if _, err = groupsClient.CreateOrUpdate(context.TODO(), cloud.Azure.ResourceGroup, parameters); err != nil {
Using `CreateOrUpdate` might be a bit confusing if the function is called `createResourceGroup`.

2018-06-08 06:26 UTC, mrIncompetent commented on api/pkg/provider/cloud/azure/provider.go
> +			clusterTagKey: to.StringPtr(clusterName),
Does this override existing tags? Or is it a merge operation?

2018-06-08 06:27 UTC, mrIncompetent commented on api/pkg/provider/cloud/azure/provider.go
> +			clusterTagKey: to.StringPtr(clusterName),
Does this override existing tags? Or is it a merge operation?

Overriding is probably very destructive & might break scenarios where multiple clusters share the same network?

2018-06-08 06:28 UTC, mrIncompetent commented on api/pkg/provider/cloud/azure/provider.go
> +	future, err := networksClient.CreateOrUpdate(context.TODO(), cloud.Azure.ResourceGroup, cloud.Azure.VNetName, parameters)
Using `CreateOrUpdate` might be a bit confusing if the function is called `createVNet`.

2018-06-08 06:30 UTC, mrIncompetent commented on api/pkg/provider/cloud/azure/provider.go
> +	if err := deleteVNet(cloud); err != nil {
I guess, if we always delete the resources, the option that the user can specify some things, is not given with this PR.
That is perfectly fine for now - it's something we can do in a follow-up PR.

2018-06-08 06:31 UTC, mrIncompetent commented on api/pkg/provider/cloud/azure/provider.go
> +			clusterTagKey: to.StringPtr(clusterName),
Not relevant due to https://github.com/kubermatic/kubermatic/pull/1200/files#r193963266

2018-06-08 06:31 UTC, mrIncompetent commented on api/pkg/provider/cloud/azure/provider.go
> +			clusterTagKey: to.StringPtr(clusterName),
Not relevant due to https://github.com/kubermatic/kubermatic/pull/1200/files#r193963266

2018-06-08 06:32 UTC, mrIncompetent commented on api/pkg/provider/cloud/azure/provider.go
> +	future, err := subnetsClient.CreateOrUpdate(context.TODO(), cloud.Azure.ResourceGroup, cloud.Azure.VNetName, cloud.Azure.SubnetName, parameters)
Using `CreateOrUpdate` might be a bit confusing if the function is called `createSubnet`.

2018-06-08 06:32 UTC, mrIncompetent commented on api/pkg/provider/cloud/azure/provider.go
> +	future, err := routeTablesClient.CreateOrUpdate(context.TODO(), cloud.Azure.ResourceGroup, cloud.Azure.RouteTableName, parameters)
Using `CreateOrUpdate` might be a bit confusing if the function is called `createRouteTable`.

2018-06-08 06:34 UTC, mrIncompetent commented on api/pkg/provider/cloud/azure/provider.go
> +	// TODO create security group
?

2018-06-08 06:35 UTC, mrIncompetent commented on api/pkg/provider/cloud/azure/provider.go
> +	// TODO delete security group
?

2018-06-08 06:37 UTC, mrIncompetent requested changes
Just some nits

2018-06-11 11:22 UTC, kdomanski commented on api/pkg/provider/cloud/azure/provider.go
> +	if _, err = groupsClient.CreateOrUpdate(context.TODO(), cloud.Azure.ResourceGroup, parameters); err != nil {
done.

2018-06-11 11:22 UTC, kdomanski commented on api/pkg/provider/cloud/azure/provider.go
> +	future, err := networksClient.CreateOrUpdate(context.TODO(), cloud.Azure.ResourceGroup, cloud.Azure.VNetName, parameters)
done

2018-06-11 11:22 UTC, kdomanski commented on api/pkg/provider/cloud/azure/provider.go
> +	future, err := subnetsClient.CreateOrUpdate(context.TODO(), cloud.Azure.ResourceGroup, cloud.Azure.VNetName, cloud.Azure.SubnetName, parameters)
done.

2018-06-11 11:22 UTC, kdomanski commented on api/pkg/provider/cloud/azure/provider.go
> +	future, err := routeTablesClient.CreateOrUpdate(context.TODO(), cloud.Azure.ResourceGroup, cloud.Azure.RouteTableName, parameters)
done.

2018-06-11 11:22 UTC, kdomanski commented on api/pkg/provider/cloud/azure/provider.go
> +	// TODO create security group
done.

2018-06-11 11:23 UTC, kdomanski commented on api/pkg/provider/cloud/azure/provider.go
> +	// TODO delete security group
done

2018-06-12 08:15 UTC, mrIncompetent approved these changes

2018-06-12 08:22 UTC, merged