WIP - Improve storage class installer
kubermatic/kubermatic pull request #12012
Opened 2023-03-08 12:53 UTC by xrstf

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #11740

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note

```

**Documentation**:

```documentation
NONE
```

2023-03-08 17:22 UTC, xrstf commented
@embik I'm not sure if we should/can set `VolumeBindingMode` to `WaitForFirstCustomer` for all StorageClasses. It currently seems random-ish which provider has the flag.

2023-03-09 07:56 UTC, embik commented
> @embik I'm not sure if we should/can set `VolumeBindingMode` to `WaitForFirstCustomer` for all StorageClasses. It currently seems random-ish which provider has the flag.

I think if the provider supports the binding mode, we should use it.

2023-03-09 09:33 UTC, embik requested changes

2023-03-09 09:33 UTC, embik commented on pkg/install/stack/common/storageclass.go
> +				sc.Parameters["type"] = "gp3"
I wonder if we should make it io1 like we do on the snapshot envs - I mean, we agreed that gp disks on AWS do not work well with etcd, no?

2023-03-09 10:06 UTC, embik requested changes

2023-03-09 10:06 UTC, embik commented on pkg/install/stack/common/storageclass.go
> +			sc.Parameters["type"] = "io1"
also needs iopsPerGB, check out what we have on the latest snapshot (20 is the value we went with).

2023-03-09 14:11 UTC, embik commented
/retest

2023-03-09 15:38 UTC, embik commented
/retest

2023-03-09 18:53 UTC, xrstf commented
/retest

2023-03-10 06:53 UTC, embik approved these changes

2023-03-10 07:51 UTC, merged