WIP - Recover from Grafana data loss
kubermatic/kubermatic pull request #12195
Opened 2023-04-25 13:55 UTC by xrstf

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #12127

**What type of PR is this?**
/kind bug

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
The MLA stack is now able to recover from a lost Grafana volume, properly recreating organizations for KKP projects.
```

**Documentation**:
```documentation
NONE
```

2023-04-26 12:19 UTC, embik requested changes
This looks pretty good as it is, but I do believe that we also need to implement the check for the org name somewhere around https://github.com/kubermatic/kubermatic/blob/09c2ef84901b5b2ad7c50db0ed7af8a58723c60a/pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go#L208
and https://github.com/kubermatic/kubermatic/blob/09c2ef84901b5b2ad7c50db0ed7af8a58723c60a/pkg/controller/seed-controller-manager/mla/dashboard_grafana_controller.go#L211

Otherwise we might end up with datasources and dashboards deployed into the wrong organisation because these controllers were faster than the org-grafana-controller that was fixed here. In my opinion, those controllers should just print a warning and re-queue the reconciling, but refuse to operate on Grafana until the project annotation is fixed.

2023-04-27 15:21 UTC, xrstf commented
> In my opinion, those controllers should just print a warning and re-queue the reconciling, but refuse to operate on Grafana until the project annotation is fixed.

agreed

2023-05-03 06:25 UTC, embik requested changes

2023-05-03 06:25 UTC, embik commented on pkg/controller/seed-controller-manager/mla/dashboard_grafana_controller.go
>  			}
also required in `datasource_grafana_controller.go` :-)

2023-05-03 08:29 UTC, embik commented on pkg/controller/seed-controller-manager/mla/dashboard_grafana_controller.go
>  			}
nvm, my mistake.

2023-05-03 08:29 UTC, embik approved these changes
/approve

2023-05-03 10:45 UTC, merged

2023-05-03 10:49 UTC, embik commented
/cherry-pick release/v2.22

2023-05-03 10:49 UTC, embik commented
/cherry-pick release/v2.21