Set successful job limit for etcd-defragger to 1
kubermatic/kubermatic pull request #12303
Opened 2023-05-23 09:33 UTC by pkprzekwas

**What this PR does / why we need it**:

Our customer noticed many `EtcdDatabaseHighFragmentationRatio` alerts pointing out that one of his etcd clusters should be defragmented. Jobs responsible for running etcd defragmentation are not failing and with `SuccessfulJobsHistoryLimit` set to `0` there is no easy way for checking if defragmentation job doesn't log anything suspicious.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

2023-05-23 09:34 UTC, xmudrii approved these changes

2023-05-23 09:35 UTC, xmudrii commented
@pkprzekwas I think you might need to update fixutres.

2023-05-24 08:13 UTC, xmudrii commented
/test pre-kubermatic-e2e-aws-ubuntu-1.27

2023-05-24 09:19 UTC, xmudrii commented
/test pre-kubermatic-e2e-aws-ubuntu-1.27

2023-05-25 06:35 UTC, embik requested changes

2023-05-25 06:35 UTC, embik commented on pkg/resources/etcd/cronjob.go
> +			job.Spec.SuccessfulJobsHistoryLimit = &successfulHistoryLimit
Let's use `k8s.io/utils/pointer` and `pointer.Int32(1)` here instead?

2023-05-25 08:27 UTC, embik approved these changes
/approve

2023-05-25 10:46 UTC, embik commented
/retest

2023-05-25 11:09 UTC, merged

2023-05-26 06:56 UTC, pkprzekwas commented
/cherrypick release/v2.22