Access to nodes via VPN.
kubermatic/kubermatic pull request #1234
Opened 2018-06-12 08:00 UTC by thz

**What this PR does / why we need it**:

While the openvpn addon currently provides access to services
and pods, it does not provide access to the user cluster 
workers' kubelet ports.

This PR adds another exposed network for the vpn:
This `NodeAccessNetwork` is a private network which is used
to make hosts/nodes from user-cluster accessible from the
apiserver via the openvpn connection. This is achieved by
associating an IP address from that network to each host/node
and doing destination network address translation (DNAT)
to map the virtual IP addresses to the real host IP addresses.

The `NodeAccessNetwork` is specified as a flag to controller-manager
and used as templating data for creation of openvpn client and server
deployments.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
Control plane can now reach the nodes via VPN
```

2018-06-12 14:25 UTC, mrIncompetent requested changes

2018-06-12 14:25 UTC, mrIncompetent commented on addons/openvpn/openvpn-client-dep.yaml
> +          # adding/removing specific DNAT rules.
Please remove the comment and rather create a Issue for it.
As this is going to be visible to customers

2018-06-12 14:25 UTC, mrIncompetent commented on addons/openvpn/openvpn-client-dep.yaml
> +        image: thzpub/vnf-swak-diag:1.2.1
Can't we use the existing Openvpn container?
If it's just missing iptables, i would recommend to simply add it to the image

2018-06-12 14:25 UTC, mrIncompetent commented on api/pkg/resources/openvpn/configmap.go
> +	if len(data.Cluster.Spec.ClusterNetwork.VirtualNodeNetwork) > 0 {
Why optional?

I would prefer always setting in within the controller (`ensureClusterNetworkDefaults`)
A default should be passed in via flag on the controller-manager

2018-06-12 20:10 UTC, thz commented on addons/openvpn/openvpn-client-dep.yaml
> +        image: thzpub/vnf-swak-diag:1.2.1
Yes, this is prepared already and will be replaced tomorrow.

2018-06-12 20:12 UTC, thz commented on api/pkg/resources/openvpn/configmap.go
> +	if len(data.Cluster.Spec.ClusterNetwork.VirtualNodeNetwork) > 0 {
My thoughts were that some customers might not like the fact of exposing their workers by a vpn in this way. Complexity of making it optional seemed reasonable.
But: having it optional is optional too... So we can change it.

2018-06-13 11:59 UTC, thz commented
@mrIncompetent 
Updated as discussed. `NodeAccessNetwork` now going in as a flag to controller-manager.
Templating for vpn-client and vpn-server adds it to the deployments.
PTAL

2018-06-13 12:46 UTC, thz commented
rebased and squashed.

2018-06-13 14:15 UTC, mrIncompetent commented on addons/openvpn/vpn-container/Dockerfile
> +FROM alpine:3.7
I would recomment we create a folder `/containers` on the root of the repository.
As the whole addons directory gets copied into a container later on and then gets used by the addon-controller, this might have unwanted sideeffects

2018-06-13 14:15 UTC, mrIncompetent commented on addons/openvpn/vpn-container/release.sh
> +#!/usr/bin/env bash
I would recomment we create a folder /containers on the root of the repository.
As the whole addons directory gets copied into a container later on and then gets used by the addon-controller, this might have unwanted sideeffects

2018-06-13 14:17 UTC, mrIncompetent commented on api/cmd/kubermatic-controller-manager/main.go
> +	flag.StringVar(&runOp.nodeAccessNetwork, "node-access-network", "", "A network which allows direct access to nodes via VPN. Uses CIDR notation.")
Please set a default value in the deployment

2018-06-21 09:09 UTC, thz commented on api/cmd/kubermatic-controller-manager/main.go
> +	flag.StringVar(&runOp.nodeAccessNetwork, "node-access-network", "", "A network which allows direct access to nodes via VPN. Uses CIDR notation.")
Done in 3e333ff.

2018-06-21 23:43 UTC, thz commented
- Applied node-access-network default in all relevant places (server+client deployment and configmap)
- fixed DNAT generation
- added MASQ for seed->user direction
-  ...and rebased.

2018-06-22 09:06 UTC, mrIncompetent requested changes

2018-06-22 09:06 UTC, mrIncompetent commented on api/pkg/resources/openvpn/configmap.go
> +		IP:   net.IP{10, 254, 0, 0},
This should be a flag as well?

2018-06-22 09:06 UTC, mrIncompetent commented on api/pkg/resources/openvpn/configmap.go
> +			return nil, fmt.Errorf("error creating vpn configmap while parsing node access network: %v", err)
Change to:
```
return nil, fmt.Errorf("failed to parse node access network %s: %v", data.NodeAccessNetwork, err)
```

This has 2 advantages:
- We're not adding the context of the function (`vpn configmap`) - as the caller already knows that this actually failed as it got an error.
- We're adding the value (`NodeAccessNetwork`) which causes the failure

2018-06-22 09:06 UTC, mrIncompetent commented on api/pkg/resources/openvpn/deployment.go
> +		IP:   net.IP{10, 254, 0, 0},
This should be a flag as well?

2018-06-22 09:06 UTC, mrIncompetent commented on api/pkg/resources/openvpn/deployment.go
> +			return nil, fmt.Errorf("error creating vpn deployment while parsing node access network: %v", err)
Change to:
```
return nil, fmt.Errorf("failed to parse node access network %s: %v", data.NodeAccessNetwork, err)
```

This has 2 advantages:
- We're not adding the context of the function (`vpn deployment`) - as the caller already knows that this actually failed as it got an error.
- We're adding the value (`NodeAccessNetwork`) which causes the failure

2018-06-22 09:11 UTC, thz commented on api/pkg/resources/openvpn/configmap.go
> +		IP:   net.IP{10, 254, 0, 0},
That _is_ the node access network. It is one of the places where the default is applied.

2018-06-22 09:14 UTC, thz commented on api/pkg/resources/openvpn/deployment.go
> +		IP:   net.IP{10, 254, 0, 0},
The node access network must have the same value in three places.
How about moving applying the default upwards in the call stack? Maximum would be to set the default after parsing the flag in controller-manager.

2018-06-22 09:30 UTC, mrIncompetent commented on api/pkg/resources/openvpn/deployment.go
> +		IP:   net.IP{10, 254, 0, 0},
sgtm, adding it to `TemplateData`?

2018-06-22 09:47 UTC, thz commented on api/pkg/resources/openvpn/deployment.go
> +			return nil, fmt.Errorf("error creating vpn deployment while parsing node access network: %v", err)
Agreed, fixed.

2018-06-22 09:47 UTC, thz commented on api/pkg/resources/openvpn/configmap.go
> +			return nil, fmt.Errorf("error creating vpn configmap while parsing node access network: %v", err)
Agreed, fixed.

2018-06-22 10:14 UTC, thz commented on api/pkg/resources/openvpn/deployment.go
> +		IP:   net.IP{10, 254, 0, 0},
It is already there. Just the defaulting was not in a central place. This moved now to flag parsing.

2018-06-22 10:51 UTC, mrIncompetent submitted a review, later dismissed

2018-06-22 11:04 UTC, mrIncompetent approved these changes

2018-06-22 11:04 UTC, merged