Add cleanup container
kubermatic/kubermatic pull request #1240
Opened 2018-06-12 10:30 UTC by mrIncompetent

**What this PR does / why we need it**:
Add cleanup container

**Release note**:
```release-note
NONE
```

2018-06-12 13:58 UTC, glower submitted a review, later dismissed

2018-06-12 14:04 UTC, glower commented
We have now 2 Containers from JobTemplate
```
	if len(cronJobs.Items[0].Spec.JobTemplate.Spec.Template.Spec.Containers) != 1 {
		t.Errorf("Expected exactly one container after manipulating cronjob, got %v", len(cronJobs.Items[0].Spec.JobTemplate.Spec.Template.Spec.Containers))
	}
```

2018-06-12 21:37 UTC, alvaroaleman approved these changes

2018-06-12 21:37 UTC, alvaroaleman commented on api/pkg/controller/backup/controller.go
> +							Name: SecretVolumeName,
Why do that instead of just letting the user decide if he or she wants to use a secret by (not-) putting it into the container yaml?

2018-06-12 21:37 UTC, alvaroaleman commented on api/pkg/controller/backup/controller.go
> +							Name: SecretVolumeName,
ah because you can only define a `volumeMount` on the container. Damn, that sucks

2018-06-12 21:37 UTC, alvaroaleman commented on api/pkg/controller/backup/controller.go
> +		if job.Status.Succeeded >= 1 {
This feels a little clunky. Another Controller? :D Not sure what the ideal approach is, maybe just open a ticket so we can revisit this?

2018-06-12 21:37 UTC, alvaroaleman commented on api/pkg/controller/backup/controller.go
> +		if job.Status.Succeeded >= 1 {
Just adding a workque, informers and listers and a minimal `sync()` for Jobs inside this controller could also be an option (Aka writing a controller without writing a controller)

2018-06-12 21:37 UTC, alvaroaleman commented on api/pkg/controller/backup/controller.go
> +	cronJob.Spec.JobTemplate.Spec.Template.Spec.Containers = []corev1.Container{c.storeContainer}
I think we should insert the cluster name into the `storeContainer`

2018-06-12 21:37 UTC, alvaroaleman commented on docs/proposals/etcd-backup.md
> +**Cleanup of backups after cluster deletion**
We absolutely need some documentation here about the backup secrets existence, name and the name of the volume it gets put into.

As a sidenode, maybe we can move proposals to a different dir once they got implemented?

2018-06-12 21:37 UTC, alvaroaleman commented on api/pkg/controller/backup/controller.go
> +							Name: SecretVolumeName,
But still, the user can just use a `secretRef` in the environment... I dislike the `secretVolume` because its complicated to explain and if that secret ever gets deleted, no backup job can run anymore

2018-06-12 21:37 UTC, alvaroaleman commented on api/pkg/controller/backup/controller.go
> +	if clusterFromCache.Labels[kubermaticv1.WorkerNameLabelKey] != c.workerName {
Is the `Spec.WorkerName` deprecated? If yes I think It'd be much easier to use `externalversions.NewFilteredSharedInformerFactory` in `cmd/kubermatic-controller-manager/controllers.go` if `workerName != ""`

2018-06-12 21:40 UTC, alvaroaleman requested changes
I'd much prefer it if we removed the secret volumem, users can use the environments `SecretKeyRef`

2018-06-13 07:49 UTC, mrIncompetent commented on api/pkg/controller/backup/controller.go
> +							Name: SecretVolumeName,
If the user want's to use a secret as volume, there's no chance of doing so without this.
That's why. 
If the user want's to use a different secret via env-vars he/she is free to do so.
The volume mount does not hurt and we're deploying it with the charts anyway

2018-06-13 07:52 UTC, mrIncompetent commented on api/pkg/controller/backup/controller.go
> +		if job.Status.Succeeded >= 1 {
I thought about this as well... 
This seemed like the very cheapest solution which solves our problem.

Adding a second queue is something i would really like to avoid as a controller should only work on a single work-queue otherwise it gets complicated to read and understand the codebase.

2018-06-13 07:53 UTC, mrIncompetent commented on api/pkg/controller/backup/controller.go
> +		if job.Status.Succeeded >= 1 {
created https://github.com/kubermatic/kubermatic/issues/1254 to revisit in the future

2018-06-13 08:03 UTC, mrIncompetent commented on api/pkg/controller/backup/controller.go
> +							Name: SecretVolumeName,
Agreed to remove the volume. Everything is also possible via env-vars

2018-06-13 08:04 UTC, mrIncompetent commented on api/pkg/controller/backup/controller.go
> +							Name: SecretVolumeName,
Reason was the communication & documentation overhead.

2018-06-13 08:11 UTC, mrIncompetent commented on api/pkg/controller/backup/controller.go
> +	cronJob.Spec.JobTemplate.Spec.Template.Spec.Containers = []corev1.Container{c.storeContainer}
That's something we must do dynamically and not here. Otherwise we'll always have the same cluster name.
See https://github.com/kubermatic/kubermatic/pull/1240/files/dbddd98c8e79fb6e063af94979383f405d8e60df#diff-561fd1fece8bf82fdabbcffee300928cR384

2018-06-13 08:16 UTC, alvaroaleman commented on api/pkg/controller/backup/controller.go
> +	cronJob.Spec.JobTemplate.Spec.Template.Spec.Containers = []corev1.Container{c.storeContainer}
the `cronJob` func gets the `cluster` as argument, so you can just take it from there

2018-06-13 08:22 UTC, mrIncompetent commented on api/pkg/controller/backup/controller.go
> +	if clusterFromCache.Labels[kubermaticv1.WorkerNameLabelKey] != c.workerName {
It's not officially deprecated but we're not using it. Therefor it can be deleted.
I'm not entirely sure if using a `FilteredSharedInformerFactory` is a good idea.
It will cause confusion as we won't be able to log the case when we won't process a resource.
But nothing for this PR anyway

2018-06-13 08:23 UTC, mrIncompetent commented on docs/proposals/etcd-backup.md
> +**Cleanup of backups after cluster deletion**
I added more details on the secret injection.
Documentation will go into the docs repository. But it will contain a customer friendly version of this.

2018-06-13 08:26 UTC, mrIncompetent commented on api/pkg/controller/backup/controller.go
> +	cronJob.Spec.JobTemplate.Spec.Template.Spec.Containers = []corev1.Container{c.storeContainer}
Sorry, i read `cleanupContainer`. I'll add the env-var

2018-06-13 08:28 UTC, mrIncompetent commented
@alvaroaleman PTAL

2018-06-13 08:31 UTC, alvaroaleman approved these changes

2018-06-13 09:11 UTC, merged