Fixed several Prometheus record and alert rules
kubermatic/kubermatic pull request #12533
Opened 2023-08-01 17:39 UTC by hc2p

**What this PR does / why we need it**:
This fixes several failing Prometheus record and alert rules:

* The label `label_app` used in query-expressions in kube-state-metrics record-rules is not available anymore. I replaced it with the closest label I could find: `label_name`. This could be improved by pulling in other possible labels with label_replace().
* The KubeCronJobRunning alert should now alert only if the respective schedule time is exceeded.
* KubermaticAddonTakesTooLongToReconcile failed since the metric kubermatic_cluster_deleted exists per seed-controller-manager pod, creating duplicates on the right-hand side. This is fixed by aggregating with max().

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Fixed several Prometheus record and alert rules.
```

**Documentation**:

```documentation
NONE
```

2023-08-07 06:05 UTC, embik commented
@hc2p there is a test failure in `pre-kubermatic-verify` which I believe relates to some of the changed Prometheus rules.

2023-08-08 10:08 UTC, hc2p commented
/retest

2023-08-08 10:14 UTC, hc2p commented
Not sure what fails here. The verification steps all pass locally.

2023-08-09 09:02 UTC, xrstf requested changes
This is partially wrong. label_app is gone because we (accidentally?) changed the labels on the kube-state-metrics Service in #12102. There we changed from `app: kube-state-metrics` to  `app.kubernetes.io/name: kube-state-metrics` and so the more appropriate label selector in Prometheus would not be `label_name`, but related to `__meta_kubernetes_service_label_app_kubernetes_io_name`

2023-08-09 09:12 UTC, xrstf commented
Adjusting the scrape config for KSM like so:

```diff
diff --git a/charts/monitoring/prometheus/config/scraping/kube-state-metrics.yaml b/charts/monitoring/prometheus/config/scraping/kube-state-metrics.yaml
index c2bf54a7d..590ce9d50 100644
--- a/charts/monitoring/prometheus/config/scraping/kube-state-metrics.yaml
+++ b/charts/monitoring/prometheus/config/scraping/kube-state-metrics.yaml
@@ -24,7 +24,7 @@ kubernetes_sd_configs:
     names:
     - '{{ .Release.Namespace }}'
 relabel_configs:
-- source_labels: [__meta_kubernetes_service_label_app]
+- source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
   separator: ;
   regex: kube-state-metrics
   replacement: $1
@@ -58,7 +58,7 @@ relabel_configs:
   target_label: job
   replacement: ${1}
   action: replace
-- source_labels: [__meta_kubernetes_service_label_app]
+- source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
   separator: ;
   regex: (.+)
   target_label: job
```

makes the metrics come back.

2023-08-09 13:56 UTC, hc2p commented
Opened a new PR with only those fixes https://github.com/kubermatic/kubermatic/pull/12551. 
Would rebase this branch and rework it accordingly. Should we add a WIP label until I find the time?

2023-08-14 11:08 UTC, xrstf commented on charts/monitoring/prometheus/rules/src/general/kube-state-metrics.yaml
> +              sum(kube_pod_labels{job="kube-state-metrics", pod="prometheus-0", namespace="monitoring"}) by (namespace, pod, label_app)
Why is this limited to Prometheus? Is this a testing leftover? :)

2023-08-14 11:08 UTC, xrstf requested changes
Questionista

2023-08-23 13:44 UTC, xrstf commented on charts/monitoring/prometheus/rules/src/general/kube-state-metrics.yaml
> +              sum(kube_pod_labels{job="kube-state-metrics", pod="prometheus-0", namespace="monitoring"}) by (namespace, pod, label_app)
@hc2p any news on this? would love to get this PR merged and the bug fixed :))

2023-08-23 13:46 UTC, hc2p commented on charts/monitoring/prometheus/rules/src/general/kube-state-metrics.yaml
> +              sum(kube_pod_labels{job="kube-state-metrics", pod="prometheus-0", namespace="monitoring"}) by (namespace, pod, label_app)
Looks like it 🤦‍♂️ 

~~not in front of a laptop atm. Can this wait until next week? 😵~~

GitHub mobile ftw

2023-08-23 13:51 UTC, hc2p commented
Hope this is fixed now. Sorry for the delay. Should have wrapped before my vacation

2023-08-23 14:02 UTC, xrstf commented
```
diff --git a/charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml b/charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml
index f6cdca80e..208fa77d2 100644
--- a/charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml
+++ b/charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml
@@ -28,7 +28,7 @@ groups:
           sum by (namespace, label_app) (
               sum(rate(container_cpu_usage_seconds_total{job="cadvisor", image!="", container!=""}[5m])) by (namespace, pod)
             * on (namespace, pod) group_left (label_app)
-              sum(kube_pod_labels{job="kube-state-metrics", pod="prometheus-0", namespace="monitoring"}) by (namespace, pod, label_app)
+              sum(kube_pod_labels{job="kube-state-metrics"}) by (namespace, pod, label_app)
           )
       - record: namespace_name:container_memory_usage_bytes:sum
         expr: |
```

I think you forgot to `hack/update-prometheus-rules.sh` :)

2023-08-25 12:09 UTC, xrstf commented
/approve
/lgtm

2023-08-25 12:10 UTC, merged