Templating for ClusterCIDR and IPs in addons
kubermatic/kubermatic pull request #1258
Opened 2018-06-13 09:51 UTC by glower

**What this PR does / why we need it**:

* Check if cluster IP of DNS is within the service range

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1167

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

2018-06-13 14:47 UTC, mrIncompetent commented on api/pkg/controller/addon/controller_test.go
> +	expectedIP := "10.10.10.1"
The first ip of the CIDR is reserved for the Apiserver. As mentioned please use the 10.

2018-06-13 16:17 UTC, glower commented on api/pkg/controller/addon/controller_test.go
> +	expectedIP := "10.10.10.1"
done

2018-06-14 07:29 UTC, mrIncompetent requested changes

2018-06-14 07:29 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +	KubeDNSclusterIP  string
Rename to `DNSClusterIP`

2018-06-14 07:29 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +	ClusterCIDR       string
Why introducing a dedicated field when its already accessable via the `.Cluster` ?

2018-06-14 07:29 UTC, mrIncompetent commented on addons/dns/kube-dns.yaml
> +  clusterIP: {{.KubeDNSclusterIP}}
Rename to `DNSClusterIP`

2018-06-14 07:30 UTC, kron4eg commented on api/pkg/controller/addon/controller.go
> +		ClusterCIDR:       cluster.Spec.ClusterNetwork.Pods.CIDRBlocks[0],
That `CIDRBlocks[0]` is a potential panic (when the slice is empty) waiting to happen.

2018-06-14 07:36 UTC, glower commented on api/pkg/controller/addon/controller.go
> +		ClusterCIDR:       cluster.Spec.ClusterNetwork.Pods.CIDRBlocks[0],
Hmm, OK I can check it, but if Pods.CIDRBlocks is empty, the cluster will probably not run anyway

2018-06-14 07:41 UTC, glower commented on api/pkg/controller/addon/controller.go
> +		ClusterCIDR:       cluster.Spec.ClusterNetwork.Pods.CIDRBlocks[0],
I will move this part now to the template anyway

2018-06-14 07:41 UTC, glower commented on api/pkg/controller/addon/controller.go
> +	ClusterCIDR       string
You right

2018-06-14 08:11 UTC, glower commented on api/pkg/controller/addon/controller.go
> +	KubeDNSclusterIP  string
fixed

2018-06-14 08:11 UTC, glower commented on addons/dns/kube-dns.yaml
> +  clusterIP: {{.KubeDNSclusterIP}}
fixed

2018-06-14 08:52 UTC, mrIncompetent approved these changes

2018-06-14 08:59 UTC, merged