disable CSI drivers installation on cluster where it's already turned on
kubermatic/kubermatic pull request #12621
Opened 2023-09-02 19:10 UTC by akash-gautam

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #12008

**What type of PR is this?**

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Disabled CSI addon on user clusters where it was enabled previously & then disabled using `DisableCSIDriver` option. The controller checks if the CSI driver(s) created by the csi addon is still in use or not and deletes them only if they are not used anywhere otherwise disabling the csi addon fails till the cluster owner ensures that it is not being used.
```

2023-09-04 06:07 UTC, akash-gautam commented
/retest

2023-09-05 11:03 UTC, ahmedwaleedmalik requested changes

2023-09-05 11:03 UTC, ahmedwaleedmalik commented on pkg/controller/seed-controller-manager/addon/addon_controller.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
Please don't introduce new contexts and use the one already propagated.

```suggestion
	ctx, cancel := context.WithTimeout(ctx, 60*time.Second)
```

2023-09-05 11:04 UTC, ahmedwaleedmalik commented
We need to discuss this PR first and then I'll do a proper review. I just want clarity on a few things.

2023-09-13 16:49 UTC, akash-gautam commented
/retest-required

2023-09-15 07:26 UTC, ahmedwaleedmalik approved these changes
/approve

2023-09-15 07:26 UTC, ahmedwaleedmalik commented
@akash-gautam can we please shorten the release note a bit and make it a bit more concise?

2023-09-15 07:34 UTC, akash-gautam commented
@ahmedwaleedmalik Updated the release notes, thanks.

2023-09-15 08:05 UTC, ahmedwaleedmalik commented
Please add description in `What this PR does / why we need it` section for this PR.

2023-09-15 08:05 UTC, ahmedwaleedmalik commented
/kind feature

2023-09-15 08:28 UTC, merged