machine-controller using http-prober with "static" CRD checking
kubermatic/kubermatic pull request #12634
Opened 2023-09-12 17:18 UTC by multi-io

Static CRD checking is a new option on http-prober to support the --crd-to-wait-for option without creating dynamic RESTMapper. The dynamic RESTMapper dynamically discovers all CRDs in the cluster, which can take long enough on a cluster with many CRDs to exceed typical prober timeouts, e.g. the 30s initialDelaySeconds for machine-controller.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

This happened to us in a user cluster with over 900 CRDs(!). Sent machine-controller into a crashloop because http-prober took longer than the container's initialDelaySeconds.

This adds to `--crd-to-wait-for` a 4-tuple option with group,version,resource,namespace that avoids dynamic discovery (e.g. `--crd-to-wait-for cluster.k8s.io,v1alpha1,machines,kube-system`) in addition to the existing 2-tuple option with kind and apiVersion, e.g. `--crd-to-wait-for Machine,cluster.k8s.io/v1alpha1`, which I kept to be compatible with existing (potentially 3rd-party) users of http-prober.

It's a pretty exotic thing, and the first time this particular failure mode has happened to us  in ~5 years of using KKP with (currently) hundreds of user clusters. Maybe you guys still want to merge this.

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note

```

**Documentation**:

```documentation
http-prober --crd-to-wait-for: Ability to avoid dynamic CRD discovery
```

2023-09-13 07:24 UTC, xrstf requested changes
Is the metakube code really meant to be submitted to this repo? Besides that I am very happy for improvements to the prober :)

2023-09-20 13:04 UTC, multi-io commented
> Is the metakube code really meant to be submitted to this repo? Besides that I am very happy for improvements to the prober :)

I asked internally. There is no problem with this. We're working on more general FOSS management policies, but until we have that we'll just proceed as we did in the past, meaning we can offer pieces of the Metakube codebase to upstream if it makes sense for us and for you guys. So there's no legal or policy problem with merging this. 🙂

2023-09-21 11:04 UTC, xrstf commented
Maaybe I wasn't clear enough, I meant these fixtures: https://github.com/multi-io/kubermatic/tree/http-prober-static-crd-checker/metakube-code/pkg/resources/test/fixtures Surely those do not belong here? :)

2023-09-21 12:50 UTC, multi-io commented
> Maaybe I wasn't clear enough, I meant these fixtures: https://github.com/multi-io/kubermatic/tree/http-prober-static-crd-checker/metakube-code/pkg/resources/test/fixtures Surely those do not belong here? :)

Oh crap, you're right. I'll fix that asap 😅

2023-09-21 12:58 UTC, multi-io commented
> Oh crap, you're right. I'll fix that asap 😅

Done. Rebased it to latest main too.

2023-09-21 13:14 UTC, xrstf commented
/ok-to-test

2023-09-21 13:16 UTC, xrstf commented
I expect these tests to fail until we actually release the new http-prober image. But let's see which jobs succeed :)

2023-09-21 14:02 UTC, xrstf commented
@multi-io The lint error is not related to the missing container image.

2023-09-21 14:32 UTC, xrstf commented
/retest

I have released v0.4.0 of the http-prober image.

2023-09-27 16:50 UTC, multi-io commented
Sorry for the late reaction. I fixed the linter problems. Should I also rebase and update the version to v0.4.1? Or rebase without updating the version, and you update the v0.4.0 tag on the image?

2023-09-27 17:51 UTC, multi-io commented
/retest

2023-09-28 08:59 UTC, xrstf commented
Nah, we can leave it on 0.4.0 and I'll re-push the image.

2023-10-02 08:21 UTC, xrstf commented
/lgtm
/approve

2023-10-02 10:19 UTC, merged

2023-10-02 10:43 UTC, xrstf commented
I have now rebuilt & repushed the 0.4.0 version of the image.