Add Minio Console and Ingress Expose Config Option
kubermatic/kubermatic pull request #12683
Opened 2023-10-04 14:21 UTC by toschneck

- add proxy-body-size setting, to ensure stable ingress for minio workload
- Minio: Include configurable Minio Console and Ingress expose strategy to chart

**What this PR does / why we need it**:
Currently the provided minio chart is not allowing to get access to the minio console (the minio management UI). For easier Acccess to minio data or admin information, we can configure the exposement of 

a) the Minio ConSol UI (via Port)
b) Additional Ingress exposement of the s3 API and the Consol

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:
Tested the deployment at the run-2 environment

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Extend Minio Configuration Options to:
- Enable Minio Consol Access
- Expose Minio API and Consol via Ingress
```

**Documentation**:

```documentation
NONE
```

2023-10-04 14:44 UTC, toschneck commented
/assign @wurbanski

2023-10-05 08:55 UTC, wurbanski commented
@toschneck I made some changes to fit better with gneral rules we use for charts and generated tests for you

2023-10-05 10:28 UTC, wurbanski commented
/approve

@xrstf please have another look and lgtm :)

2023-10-05 13:11 UTC, xrstf commented
I think enabling the console by default is already ...mhm. But then we also by default create an Ingress with dummy domains, which will made cert-manager attempt to get certs for those dummy domains. IMHO the Ingress config in the values.yaml needs to be commented out by default or we need to set the default port to 0. Whatever it takes to make an admin actually configure _real_ domains.

2023-10-06 12:36 UTC, xrstf requested changes
I think enabling the console by default is already ...mhm. But then we also by default create an Ingress with dummy domains, which will made cert-manager attempt to get certs for those dummy domains. IMHO the Ingress config in the values.yaml needs to be commented out by default or we need to set the default port to 0. Whatever it takes to make an admin actually configure real domains.

2023-10-09 09:29 UTC, wurbanski commented
> But then we also by default create an Ingress with dummy domains,

I think this is the part that I've removed, there is no ingress by default? https://github.com/kubermatic/kubermatic/pull/12683/files#diff-00aa052af288b2c99310d061e82f15eea9b129ae830c56340ffd9abd9b47e3aeR231

2023-10-10 08:41 UTC, xrstf approved these changes
/approve

2023-10-10 09:10 UTC, merged