[WIP] cinder csi: allow topology support customization
kubermatic/kubermatic pull request #12878
Opened 2023-12-04 16:57 UTC by wozniakjan

**What this PR does / why we need it**:
WIP

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubermatic/kubermatic/issues/12877

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note

```

**Documentation**:

```documentation

```

2023-12-05 16:10 UTC, wozniakjan commented
/retest

2023-12-05 18:31 UTC, wozniakjan commented
/test pre-kubermatic-e2e-openstack-centos-1.28

2023-12-06 08:25 UTC, wozniakjan commented
/test pre-kubermatic-e2e-openstack-centos-1.28

2023-12-06 09:56 UTC, wozniakjan commented on cmd/conformance-tester/pkg/clients/client_kube.go
> +		cluster.Spec.CNIPlugin = &kubermaticv1.CNIPluginSettings{Type: kubermaticv1.CNIPluginTypeCanal}
maybe we should not allow cilium with centos at the moment?

2023-12-06 10:50 UTC, wozniakjan commented
ptal
/cc: @embik @xmudrii

2023-12-06 10:55 UTC, embik requested changes
Please make the release note more specific (which field to set on clusters or datacenters to enable/disable this).

2023-12-06 12:47 UTC, xmudrii commented on pkg/apis/kubermatic/v1/cluster.go
> +	// Flag to configure enablement of CSI Cinder plugin for topology support.
Nit: I think the comment might make more sense the other way
```suggestion
	// Flag to configure enablement of topology support for the Cinder CSI plugin.
```

2023-12-06 12:47 UTC, xmudrii commented on pkg/apis/kubermatic/v1/datacenter.go
> +	// Optional: configures enablement of CSI Cinder plugin for topology support.
```suggestion
	// Optional: configures enablement of topology support for the Cinder CSI Plugin.
```

2023-12-06 14:15 UTC, xmudrii approved these changes
/lgtm
/approve

2023-12-13 10:00 UTC, wurbanski commented
/approve

2023-12-13 10:07 UTC, wozniakjan commented
/cherry-pick release/v2.24

2023-12-13 10:51 UTC, merged