[WIP] Add ClusterBackupStorageLocation and related user Cluster configuration
kubermatic/kubermatic pull request #12929
Opened 2023-12-22 10:16 UTC by moelsayed

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note

```

**Documentation**:

```documentation

```

2023-12-22 10:17 UTC, moelsayed commented
/test all

2024-01-08 10:44 UTC, moelsayed commented
/test all

2024-01-12 09:22 UTC, embik commented
I'll take a look but no release note seems wrong already. Can you please add one?

2024-01-15 10:30 UTC, embik reviewed
I have concerns about the API changes here. Why are we attaching the backup location configuration to the `ClusterSpec` directly? Wouldn't it make more sense to mirror `EtcdBackupConfig` so that we can implement the dashboard changes in an uniform way and allow to associate multiple backup locations with a single cluster (e.g. to run on different schedules; one backups every hour to a nearby S3, and another one back ups once a day to a remote datacenter's S3)?

2024-01-22 09:01 UTC, moelsayed commented
That it is a valid point. It's mostly related to the context of the feature.  Velero, by default, expects an initial default `BackupStorageLocation` to work properly. Velero also allows users to specify additional storage locations when creating `Backups` or `Schedules`. 

Initially, we are going to start with the default backup location only, to simplify the integration. Later, it would be possible to select specific backup locations when configuration a single Velero backup or schedule. In this workflow, having a dedicated API to associate Cluster and Backup configuration would be redundant since that's already implemented by Velero's Backup and Schedule APIs.

2024-01-22 09:17 UTC, embik requested changes

2024-01-22 09:17 UTC, embik commented on hack/update-codegen.sh
> +  "clusterbackupstoragelocations.kubermatic.k8c.io": "seed",
This is an API that will be accessed by the KKP dashboard, right? Then let's add it to master and seed because we had some issue with seed-only resources in the past and had to revert creating resources only on the seed.

2024-01-22 09:18 UTC, embik commented
> That it is a valid point. It's mostly related to the context of the feature. Velero, by default, expects an initial default `BackupStorageLocation` to work properly. Velero also allows users to specify additional storage locations when creating `Backups` or `Schedules`.
> 
> Initially, we are going to start with the default backup location only, to simplify the integration. Later, it would be possible to select specific backup locations when configuration a single Velero backup or schedule. In this workflow, having a dedicated API to associate Cluster and Backup configuration would be redundant since that's already implemented by Velero's Backup and Schedule APIs.

Ack. Sounds good to me for now, let's see if we can evolve the API in the future (or have to).

2024-01-22 14:21 UTC, embik approved these changes
/approve

2024-01-22 15:13 UTC, merged