Set `floating-network-id` in OpenStack cloud-config to provided floating IP pool
kubermatic/kubermatic pull request #12975
Opened 2024-01-18 14:00 UTC by embik

**What this PR does / why we need it**:
This hopefully addresses #12905 - seems that we have missed setting an explicit floating network in the cloud-config passed to the CCM. That is fine when your OpenStack setup only has a single external network (like the one we are testing against), but becomes problematic if there are multiple.

It seems to be sensible to default to the same external network that is used for node floating IPs because we know that the router connection has to be there. If people want to use other networks, they have the option to set the `loadbalancer.openstack.org/floating-network-id` annotation on their `Service` objects.

**Which issue(s) this PR fixes**:

Fixes #12905

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Explicitly configure OpenStack CCM with floating IP pool configured for user cluster instead of defaulting to first external network available
```

**Documentation**:

```documentation
NONE
```

2024-01-18 14:02 UTC, embik commented
/test pre-kubermatic-e2e-openstack-ubuntu-1.28

2024-01-18 17:58 UTC, xrstf commented
/hold cancel
/test pre-kubermatic-e2e-openstack-ubuntu-1.28

2024-01-19 06:58 UTC, embik commented
Legitimate failure, I think I need to resolve the ID.

2024-01-22 11:28 UTC, xrstf commented
> I0118 19:11:43.759351       1 event.go:307] "Event occurred" object="lb-test-1/test" fieldPath="" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: error creating LB floatingip: Bad request with: [POST https://api.dbl.cloud.syseleven.net:9696/v2.0/floatingips], error message: {\"NeutronError\": {\"message\": \"Invalid input for floating_network_id. Reason: 'ext-net' is not a valid UUID.\", \"type\": \"HTTPBadRequest\", \"detail\": \"\"}}"

In case anyone doesn't want to hunt for the error message.

2024-01-22 11:41 UTC, embik commented
> > I0118 19:11:43.759351       1 event.go:307] "Event occurred" object="lb-test-1/test" fieldPath="" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: error creating LB floatingip: Bad request with: [POST https://api.dbl.cloud.syseleven.net:9696/v2.0/floatingips], error message: {"NeutronError": {"message": "Invalid input for floating_network_id. Reason: 'ext-net' is not a valid UUID.", "type": "HTTPBadRequest", "detail": ""}}"
> 
> In case anyone doesn't want to hunt for the error message.

Yes, I need to translate network name to network ID.

2024-01-23 07:56 UTC, embik commented
This requires the OpenStack provider to be reconciling.

2024-04-09 06:08 UTC, embik commented
/cc @xrstf @mohamed-rafraf

@mohamed-rafraf if you are interested in reviewing a PR!

2024-04-10 11:28 UTC, mohamed-rafraf requested changes
I think it will be a good idea the wrapp the whole externalNetwork logic into function called reconcileExtNetwork()

and call it as we do in network, security groups and subnets ...

like this

	// Reconciling the Network
	if force || cluster.Spec.Cloud.Openstack.Network == "" {
		cluster, err = reconcileNetwork(ctx, netClient, cluster, update)
		if err != nil {
			return nil, err
		}
	}

	// All machines will live in one dedicated security group.
	if force || cluster.Spec.Cloud.Openstack.SecurityGroups == "" {
		cluster, err = reconcileSecurityGroup(ctx, netClient, cluster, update)
		if err != nil {
			return nil, err
		}
	}

2024-04-10 12:17 UTC, embik commented
@mohamed-rafraf fixed, thanks for the suggestion!

2024-04-10 13:55 UTC, mohamed-rafraf approved these changes

2024-04-10 17:26 UTC, xrstf commented
/approve

2024-04-10 17:27 UTC, merged

2024-10-28 07:55 UTC, bassemtadros commented
@embik  unfortunately this didn't fix the issue stated in https://github.com/kubermatic/kubermatic/issues/12905

2024-10-28 08:04 UTC, embik commented
Hi @bassemtadros can you please show us the cloud-config and `Cluster` object (with sensitive information redacted) in #12905 so we understand how your Clusters look like in KKP 2.26 (this PR is only available in 2.26.0 and higher)?

2024-10-28 09:15 UTC, bassemtadros commented
You can see below in the preset the external network is **named external**, while in the cluster object it annotates the floating ip pool id of the the other external network, and in the cluster object floatingIPPool it gets its name **manila-network**, let me know if you need further updates.

```apiVersion: kubermatic.k8c.io/v1
kind: Preset
metadata:
  creationTimestamp: "2024-10-28T07:27:04Z"
  generation: 1
  name: datapro
  resourceVersion: "49451354"
  uid: 48bd8505-cf0a-4fd0-9993-eeb42f77ac0c
spec:
  enabled: true
  openstack:
    datacenter: eum-cf-waw3-1
    domain: xxxxx
    floatingIPPool: external
    network: kkp-k8s-private
    routerID: xxxxx-537dc98e4182
    subnetID: xxxx-10091aab018a
  projects:
  - v10fnv6f2y 
```


```apiVersion: kubermatic.k8c.io/v1
kind: Cluster
metadata:
  annotations:
    kubermatic.k8c.io/openstack-floating-ip-pool-id: xxxxxxx-5deb5813602e
    presetName: datapro
  creationTimestamp: "2024-10-28T07:28:17Z"
  finalizers:
  - kubermatic.k8c.io/cleanup-credentials-secrets
  - kubermatic.k8c.io/cleanup-etcdbackupconfigs
  - kubermatic.k8c.io/cleanup-kubermatic-constraints
  - kubermatic.k8c.io/cleanup-namespace
  - kubermatic.k8c.io/cleanup-openstack-security-group
  - kubermatic.k8c.io/cleanup-usersshkeys-cluster-ids
  - kubermatic.k8c.io/delete-nodes
  generation: 5
  labels:
    argocd.argoproj.io/instance: kubermatic
    env: val
    is-credential-preset: "true"
    project-id: v10fnv6f2y
  name: av6clvgml4
  resourceVersion: "49486609"
  uid: a8a146bb-c5ca-40f0-bf3f-a2b4e4e16329
spec:
  auditLogging: {}
  cloud:
    dc: eum-cf-waw3-1
    openstack:
      credentialsReference:
        name: credential-openstack-av6clvgml4
        namespace: kubermatic
      floatingIPPool: manila-network
      network: kkp-k8s-private
      nodePortsAllowedIPRanges:
        cidrBlocks: []
      routerID: xxxxx-8b96-537dc98e4182
      securityGroups: kubernetes-av6clvgml4
      subnetID: xxxxxxx-10091aab018a
    providerName: openstack 
```

2024-10-28 09:55 UTC, embik commented
Thanks for reporting this @bassemtadros and apologies for the issues caused. #13834 will fix this regression, it will be backported to 2.26 and should be included in an upcoming 2.26.1 patch release.