WIP
kubermatic/kubermatic pull request #12996
Opened 2024-01-24 06:50 UTC by ahmedwaleedmalik

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note

```

**Documentation**:

```documentation

```

2024-01-24 06:50 UTC, ahmedwaleedmalik commented
/test all

2024-01-24 17:22 UTC, xrstf commented on cmd/conformance-tester/pkg/types/secrets.go
> +		OVDCNetworks  []string
I don't think we should keep both the old and the new syntax in the conformance-tester's CLI flags. There is no BC guarantee with the tester anyway. We should just have 1 flag, preferably the new one.

Also, this new flag is never set by our code, so the new code isn't tested. Please adjust the hack/ci/run-conformance-tests.sh accordingly.

2024-01-24 17:24 UTC, xrstf commented on pkg/machine/provider/vmware_cloud_director.go
Unrelated, but in line 106 can you change the "AWS" to "VCD"?

2024-01-24 17:31 UTC, xrstf commented on pkg/provider/cloud/vmwareclouddirector/provider.go
> +		if len(oldSpec.VMwareCloudDirector.OVDCNetworks) != len(newSpec.VMwareCloudDirector.OVDCNetworks) {
Why is this only checking the length? Is changing [a,b] to [c,d] valid? Maybe using a string set's Equal() function would work better here, if not even using a semantic equality. But I'd probably just use a set.

2024-01-24 17:32 UTC, xrstf requested changes
QQ

2024-01-24 19:16 UTC, ahmedwaleedmalik commented
Feedback handled @xrstf

2024-01-25 12:49 UTC, xrstf approved these changes
/approve

2024-01-25 12:50 UTC, merged