WIP: Added documentation link, source code link and logo for all the default applications
kubermatic/kubermatic pull request #13054
Opened 2024-02-07 11:22 UTC by archups

**What this PR does / why we need it**:
It will add documentation link, source code link and logos to all the applications which are part of the default applications catalog.

**Which issue(s) this PR fixes**:

Fixes #12942 

**What type of PR is this?**
/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Add documentation link, source code link and logo to the default applicaitons.
```

**Documentation**:

```documentation
TBD
```

2024-02-07 11:25 UTC, archups commented
/assign @archups

2024-02-07 11:34 UTC, archups commented
/cc @embik @SimonTheLeg @csengerszabo

2024-02-07 18:38 UTC, archups commented
Dependent on https://github.com/kubermatic/dashboard/issues/6444 for verification.

2024-02-14 08:46 UTC, archups commented
> /

@embik yes I think the script fix  is the needed! :D I will do it. Stumbled into this issue twice. Thanks! :)

2024-02-14 13:11 UTC, embik commented
/milestone KKP 2.25

2024-02-14 13:15 UTC, embik approved these changes
LGTM, leaving approval to @SimonTheLeg or @csengerszabo.

2024-02-19 13:04 UTC, xrstf commented on pkg/ee/default-application-catalog/applicationdefinitions/argocd-app.yaml
> +  documentationURL: https://argoproj.github.io/cd/
Why did you make all the YAML files executable?

![2024-02-19T14-03-24](https://github.com/kubermatic/kubermatic/assets/127499/bc808f5a-c7da-4092-9fc3-7880557f632a)

chmod 644 was good, why make it 755?

2024-02-19 13:04 UTC, xrstf requested changes
File system permissions

2024-02-20 09:33 UTC, archups commented
> File system permissions

Fixed the file permissions. Thanks @xrstf

2024-02-20 09:42 UTC, SimonTheLeg commented
/approve

With the filesystem fix done, looks good to me

2024-02-20 10:06 UTC, embik approved these changes

2024-02-20 10:31 UTC, merged