Add changelogs for Feb 2024 patch releases
kubermatic/kubermatic pull request #13086
Opened 2024-02-16 06:28 UTC by archups

**What this PR does / why we need it**:
This adds changelogs for the Feb 2024 patch releases.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind documentation

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

2024-02-16 06:28 UTC, archups commented
/assign @archups @akash-gautam 
/cc @embik

2024-02-16 08:03 UTC, embik requested changes
Some minor changes required, the comments ofc apply to the items in 2.23 and 2.22 as well.

2024-02-16 08:03 UTC, embik commented on docs/changelogs/CHANGELOG-2.24.md
> +- Update operating-system-manager (OSM) to [v1.4.1](https://github.com/kubermatic/operating-system-manager/releases/tag/v1.4.1)  * This includes a fix for Flatcar stable channel (version 3815.2.0) fa
Let's categorize these as "Updates" instead.

2024-02-16 08:03 UTC, embik commented on docs/changelogs/CHANGELOG-2.24.md
> +- Update operating-system-manager (OSM) to [v1.4.1](https://github.com/kubermatic/operating-system-manager/releases/tag/v1.4.1)  * This includes a fix for Flatcar stable channel (version 3815.2.0) fa
Can you please re-format this note? Unfortunately the notes generation tool isn't very good at that.

```suggestion
- Update metering to v1.1.2, fixing an error when a custom CA bundle is used ([#13013](https://github.com/kubermatic/kubermatic/pull/13013))
- Update operating-system-manager (OSM) to [v1.4.1](https://github.com/kubermatic/operating-system-manager/releases/tag/v1.4.1)  ([#13082](https://github.com/kubermatic/kubermatic/pull/13082))
  - This includes a fix for Flatcar stable channel (version 3815.2.0) failing to provision as new nodes
```

2024-02-19 10:37 UTC, xrstf commented on docs/changelogs/CHANGELOG-2.24.md
> +- **ACTION REQUIRED:** If you use `velero.restic.deploy: true`, you will see new daemonset `node-agent` running in `velero` namespace. You might need to remove existing daemonset named `restic` manua
Same here regarding mentioning that it's relating to the velero Helm chart.

2024-02-19 11:28 UTC, xrstf approved these changes
/approve

2024-02-19 13:16 UTC, xrstf commented
/lgtm

2024-02-19 13:18 UTC, merged