Add NVIDIA GPU operator as bundled App
kubermatic/kubermatic pull request #13147
Opened 2024-03-01 16:09 UTC by SimonTheLeg

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #13017 

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Add nvidia-gpu-operator to default apps
```

**Documentation**:

```documentation
TBD
```

2024-03-01 16:10 UTC, SimonTheLeg commented
/cc @archups

2024-03-04 09:20 UTC, ahmedwaleedmalik requested changes

2024-03-04 09:20 UTC, ahmedwaleedmalik commented on pkg/ee/default-application-catalog/applicationdefinitions/nvidia-gpu-operator-app.yaml
> +#                   Copyright © 2023 Kubermatic GmbH
`s/2023/2024`

2024-03-04 09:35 UTC, SimonTheLeg commented on pkg/ee/default-application-catalog/applicationdefinitions/nvidia-gpu-operator-app.yaml
> +#                   Copyright © 2023 Kubermatic GmbH
fixed

2024-03-04 09:39 UTC, ahmedwaleedmalik approved these changes
/approve

2024-03-04 12:08 UTC, SimonTheLeg commented
/retest

2024-03-05 13:28 UTC, merged