Use ValuesBlock in Cilium
kubermatic/kubermatic pull request #13276
Opened 2024-04-11 10:51 UTC by SimonTheLeg

**What this PR does / why we need it**:

Uses ValuesBlock instead of Values for Cilium. This is needed because otherwise when you change the values in the UI, the API will convert Values to ValuesBlock, but the controller will still try to populate Values, leading to an issue.

**Which issue(s) this PR fixes**:

Fixes [#6646](https://github.com/kubermatic/dashboard/issues/6646)

**What type of PR is this?**

/kind cleanup

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

2024-04-11 11:34 UTC, cnvergence requested changes
Should we also convert these values?
https://github.com/kubermatic/kubermatic/blob/main/pkg/controller/seed-controller-manager/cni-application-installation-controller/controller.go#L366

2024-06-19 12:19 UTC, embik commented
@SimonTheLeg @cnvergence any chance for this to be picked up again? I believe I got a report about this in support request INC-6976.

2024-06-19 14:43 UTC, SimonTheLeg commented
let me have a look at the merge conflict

2024-07-25 06:56 UTC, SimonTheLeg commented
/test pre-kubermatic-e2e-aws-ubuntu-1.28-ce

2024-07-25 07:14 UTC, SimonTheLeg commented
/restest

2024-07-25 07:14 UTC, SimonTheLeg commented
/retest

2024-07-25 13:42 UTC, SimonTheLeg commented
/test pre-kubermatic-cilium-e2e

2024-07-25 18:09 UTC, SimonTheLeg commented
/retest

2024-07-26 06:52 UTC, embik commented
@xrstf ping, needs override.

2024-07-26 06:53 UTC, embik commented
Note: This is a bug fix, not a cleanup, and should be labeled as such. Which also means it needs a release note.

2024-07-26 07:29 UTC, SimonTheLeg commented
> Note: This is a bug fix, not a cleanup, and should be labeled as such. Which also means it needs a release note.

good point. Fixed

2024-07-26 07:31 UTC, SimonTheLeg commented
@cnvergence This PR should now be ready for review

2024-07-26 08:14 UTC, xrstf commented
/override pre-kubermatic-test-integration

2024-07-26 10:44 UTC, cnvergence approved these changes
/approve

2024-07-26 10:45 UTC, merged

2024-07-29 05:20 UTC, dharapvj commented
Hi @SimonTheLeg - Are we planning to backport this to 2.25?

2024-07-29 08:14 UTC, SimonTheLeg commented
/backport 2.25

good point, yes this should be backportable. One sec.

2024-07-29 09:45 UTC, embik commented
@SimonTheLeg you want `/cherry-pick release/v2.25` 😄

2024-07-29 10:44 UTC, SimonTheLeg commented
/cherry-pick release/v2.25