Allow custom tag & tag-suffix for kubermatic API image
kubermatic/kubermatic pull request #13274
Opened 2024-04-11 10:31 UTC by akash-gautam

**What this PR does / why we need it**:
Currently when we specify a image tag/tag-suffix for dashboard in the KKP configuration, the same is used for KKP API as well, this PR enables admins to set different tag/tag-suffix for KKP UI & KKP API.

**Which issue(s) this PR fixes**:
Fixes #12464

**What type of PR is this?**

/kind feature
/kind api-change

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Separate container image tag/tag-suffix can be set for KKP UI & KKP API.
**ACTION REQUIRED**: If custom image tag/tag-suffix is being used for KKP UI & the admin desires to use the same (or different) custom tag/tag-suffix for the Kubermatic API image as well, then it needs to be explicitly set in the `KubermaticConfiguration.spec.api.dockerTag/dockerTagSuffix` otherwise the default tag for the KKP version will be used.
```

**Documentation**:

```documentation
NONE
```

2024-04-12 08:04 UTC, akash-gautam commented
/cc @embik @ahmedwaleedmalik

2024-04-15 17:48 UTC, xrstf commented
/approve
/lgtm

/hold if you need another review

2024-04-15 18:08 UTC, ahmedwaleedmalik requested changes
Minor nit(s).

We also need to inform the users that this is a breaking change and now they'll have to provide the configuration in both `UI` and `API` block in case they are using custom images. So an `action required` block should be added in the release notes.

2024-04-15 18:08 UTC, ahmedwaleedmalik commented on pkg/apis/kubermatic/v1/configuration.go
> +	// DockerTag is used to overwrite the kubermatic api Docker image tag and is only for development
```suggestion
	// DockerTag is used to overwrite the Kubermatic API Docker image tag and is only for development
```

2024-04-15 18:08 UTC, ahmedwaleedmalik commented on pkg/apis/kubermatic/v1/configuration.go
> +	// DockerTagSuffix is appended to the KKP version used for referring to the custom kubermatic api image.
```suggestion
	// DockerTagSuffix is appended to the KKP version used for referring to the custom Kubermatic API image.
```

2024-04-15 18:08 UTC, ahmedwaleedmalik commented on pkg/apis/kubermatic/v1/configuration.go
> +	// If left empty, either the `DockerTag` if specified or the original kubermatic api Docker image tag will be used.
```suggestion
	// If left empty, either the `DockerTag` if specified or the original Kubermatic API Docker image tag will be used.
```

2024-04-16 06:23 UTC, embik commented
> We also need to inform the users that this is a breaking change and now they'll have to provide the configuration in both UI and API blocks in case they were using the same custom image for both. So an action required block should be added in the release notes.

@ahmedwaleedmalik WDYT, does it maybe make sense to retain the old fallback instead?

2024-04-16 09:11 UTC, ahmedwaleedmalik commented
> > We also need to inform the users that this is a breaking change and now they'll have to provide the configuration in both UI and API blocks in case they were using the same custom image for both. So an action required block should be added in the release notes.
> 
> @ahmedwaleedmalik WDYT, does it maybe make sense to retain the old fallback instead?

So something like using `cfg.Spec.UI.DockerTag` for API if `cfg.Spec.API.DockerTag` is not specified? My personal opinion would be against having a fallback like this since it only adds to the confusion. In most of our cases, users are only interested in updating the UI image and want to use KKP's official image for API.

If otherwise, you were talking about [this](https://github.com/kubermatic/kubermatic/pull/13274/files#diff-5325d511748bcd0b9035af6206947bfc3fed702661685e00e025ca5cfb242e7aR245) fallback. Then although it wouldn't matter much I would have preferred to keep `tag := versions.UI` instead of this change.

2024-04-16 09:17 UTC, embik commented
No, I meant retaining the "old" behaviour for compatibility, but I'm also fine with marking this as a breaking change and be done with it as you suggested. Thanks for the additional input!

2024-04-16 11:23 UTC, akash-gautam commented
@ahmedwaleedmalik Added action required block in the release notes, PTAL.

2024-04-18 10:40 UTC, ahmedwaleedmalik approved these changes
/approve

2024-04-18 10:50 UTC, ahmedwaleedmalik commented
/unhold

2024-04-18 11:47 UTC, merged