bump telemetry to 0.5.2
kubermatic/kubermatic pull request #13289
Opened 2024-04-12 14:16 UTC by xrstf

**What this PR does / why we need it**:
Telemetry 0.5.0 is broken, we need this patch in 2.25.x.

**What type of PR is this?**
/kind bug
/kind regression

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Fix telemetry agent container images not starting up.
```

**Documentation**:
```documentation
NONE
```

2024-04-12 14:19 UTC, xrstf commented
/cherrypick release/v2.25

2024-04-15 07:45 UTC, archups requested changes

2024-04-15 07:45 UTC, archups commented on charts/telemetry/.helmignore
> +test/
Minor fix: End of line is missing.

2024-04-15 12:11 UTC, xrstf commented on charts/telemetry/.helmignore
> +test/
fixed.

2024-04-17 06:12 UTC, archups approved these changes
/lgtm

2024-04-17 06:12 UTC, archups commented
/approve

2024-04-17 06:13 UTC, archups commented
@xrstf your approval is required to merge it. Thanks!

2024-04-17 07:48 UTC, xrstf commented
/approve

2024-04-17 07:54 UTC, merged