Add ManagedByLabel to user ClusterBackup resources
kubermatic/kubermatic pull request #13396
Opened 2024-05-17 21:45 UTC by moelsayed

**What this PR does / why we need it**:
This PR fixes a bug where Velero CRDs are removed from user clusters if it's deployed externally and Cluster Backup is disabled.
**Which issue(s) this PR fixes**:

Fixes #13393

**What type of PR is this?**

/kind bug
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Fixes #13393 where externally deployed Velero CRDs are removed automatically from user user cluster.
```

**Documentation**:

```documentation
NONE
```

2024-05-20 09:04 UTC, embik requested changes

2024-05-20 09:04 UTC, embik commented on pkg/resources/resources.go
> +	ClusterBakcupControllerName       = "cluster-backup-controller"
Typo.

```suggestion
	ClusterBackupControllerName       = "cluster-backup-controller"
```

2024-05-20 09:06 UTC, embik commented on pkg/ee/cluster-backup/controller.go
> +				appskubermaticv1.ApplicationManagedByLabel: resources.ClusterBakcupControllerName,
This should apply to the other resources as well, else we'll still delete Deployments and DaemonSets we never managed.

2024-05-20 14:14 UTC, moelsayed commented
/test pre-kubermatic-etcd-launcher-e2e

2024-05-21 06:53 UTC, xrstf commented
/approve
/lgtrm

Personally I would not have put a controller name constant in the resources package, cause that's not where it belongs, and would have used an objectModifier to apply the labels instead of editing every single reconciler function to do it manually (and therereby getting rid of the new "need" to have the controller name in a completely foreign, remote, far away package), but nwe're in a hurry, so I guess... let's merge it.

2024-05-21 07:03 UTC, xrstf commented
/lgtm
/cherrypick release/v2.25

2024-05-21 07:04 UTC, merged