[On Hold] Add new Kubernetes versions
kubermatic/kubermatic pull request #1348
Opened 2018-06-22 14:07 UTC by mrIncompetent

**What this PR does / why we need it**:
add new versions

**Release note**:
```release-note
Added support for K8S `1.8.14`, `1.9.8`, `1.9.9`, `1.10.4` and `1.10.5`
```

2018-06-22 14:39 UTC, alvaroaleman requested changes

2018-06-22 14:39 UTC, alvaroaleman commented on config/kubermatic/static/master/versions.yaml
> +- version: "1.10.4"
These don't exist on https://quay.io/repository/coreos/hyperkube yet, so this will only work for Ubuntu and CentOS worker nodes

2018-06-22 14:39 UTC, alvaroaleman commented on config/kubermatic/static/master/versions.yaml
> +- version: "1.8.14"
This does not exist on qay yet, so will only work for Ubuntu and CentOS worker nodes

2018-06-22 14:58 UTC, mrIncompetent commented
PR is on Hold until the new versions are in the quay.io/coreos/hyperkube repository

2018-06-28 15:14 UTC, alvaroaleman commented
Will get unblocked by kubermatic/machine-controller#256

2018-07-01 11:08 UTC, alvaroaleman requested changes
We need to update the machine-controller first

2018-07-01 11:47 UTC, alvaroaleman approved these changes

2018-07-01 11:48 UTC, merged