Fix: Update Vsphere Integration Test
kubermatic/kubermatic pull request #13572
Opened 2024-08-06 19:05 UTC by mohamed-rafraf

**What this PR does / why we need it**:
This PR update the Vsphere Integration test config in order to fix the failures in `pre-kubermatic-test-integration` prow job

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

2024-08-06 23:55 UTC, moadqassem requested changes
Please change the datastore name from vSAN to  ```
Datastore0-truenas
```

2024-08-07 09:09 UTC, xrstf commented
/approve
/lgtm

Thanks a bunch :)

2024-08-07 09:10 UTC, mohamed-rafraf commented
/cherrypick release/v2.25

2024-08-07 09:10 UTC, mohamed-rafraf commented
/cherrypick release/v2.24

2024-08-07 09:10 UTC, mohamed-rafraf commented
/cherrypick release/v2.23

2024-08-07 10:09 UTC, moadqassem commented on cmd/conformance-tester/pkg/scenarios/vsphere.go
> +		spec.Cloud.VSphere.DatastoreCluster = "Datastore0-truenas"
I am not sure if this is gonna work as this is not a datastore cluster. Datastore cluster is a collection of ESXi hosts that use the local storage of each of those hosts(VMFS)

2024-08-07 11:00 UTC, moadqassem commented on cmd/conformance-tester/pkg/scenarios/generator.go
> +		// scenario.datastoreCluster = opts.ScenarioOptions.Has("datastore-cluster")
You need tot disable the prow job https://github.com/kubermatic/kubermatic/blob/main/.prow/provider-vsphere.yaml#L153

2024-08-07 12:01 UTC, xrstf approved these changes
/approve

2024-08-07 12:23 UTC, merged

2024-08-07 13:07 UTC, mohamed-rafraf commented
/cherrypick release/v2.23

/cherrypick release/v2.24

/cherrypick release/v2.25