cluster-dns (Part 2/2)
kubermatic/kubermatic pull request #1379
Opened 2018-06-26 14:34 UTC by thz

**What this PR does / why we need it**:

This PR adds openvpn sidecars for `scheduler` and `controllermanager` and configures master components' pods to use the user-cluster's DNS resolver.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #871 

**Special notes for your reviewer**:

Release note:
```release-note
Master components can now talk to cluster DNS
```

2018-06-26 14:42 UTC, thz commented on api/pkg/resources/apiserver/deployment.go
> +			"kube-system.svc.cluster.local",
Not sure if master components should have a search list at all.

2018-06-26 15:06 UTC, thz commented on api/pkg/resources/resources.go
> +// UserClusterDNSResolverIP returns the 9th usable IP address
Just temporary in this PR. This might get obsoleted by the outcome of #1357

2018-06-26 15:06 UTC, thz commented
PTAL @mrIncompetent

2018-06-26 15:13 UTC, mrIncompetent commented on api/pkg/resources/apiserver/deployment.go
> +	openvpnSidecar, err := resources.OpenVPNSidecarContainer(data, "openvpn-client")
:+1:

2018-06-26 15:17 UTC, mrIncompetent commented on api/pkg/resources/apiserver/deployment.go
> +			"kube-system.svc.cluster.local",
Is it required? I would like to omit as much as possible.
Though if kubernetes defaults those fields to `kube-system.svc.cluster.local` & `svc.cluster.local` then we should write those here as well - otherwise our controller detects a difference between desired & actual state -> resulting in an endless loop of updates

2018-06-26 15:19 UTC, mrIncompetent commented on api/pkg/resources/apiserver/deployment.go
> +				Value: &dnsConfigOptionNdots,
Whats this for?

2018-06-26 15:21 UTC, mrIncompetent commented on api/pkg/resources/resources.go
> +// UserClusterDNSResolverIP returns the 9th usable IP address
This actually implements parts of #1357
If this mirrors the same logic like the addon-controller i'm fine with the duplication for now

2018-06-26 16:51 UTC, thz commented on api/pkg/resources/resources.go
> +// UserClusterDNSResolverIP returns the 9th usable IP address
Yes - it is the same logic as in #1357 `getKubeDNSClusterIP()`

2018-06-26 16:54 UTC, thz commented on api/pkg/resources/apiserver/deployment.go
> +			"kube-system.svc.cluster.local",
I prefer an empty search list. Of course this will break uses like "apiserver" without any suffix. But perhaps there is no such use less after Part1/2 of the cluster-dns proposal implementation.

I will check for such a cycle. Originally k8s creates more entries:
```
nameserver 10.47.240.10
search cluster-4b8zj9pvch.svc.cluster.local svc.cluster.local cluster.local c.kubermatic-dev.internal google.internal
options ndots:5
```

This is mixed with what comes from the host/node itself.
But with `DNSPolicy=None` it does not mix in the hosts search list.
I will do some more testing.

2018-06-26 16:56 UTC, thz commented on api/pkg/resources/apiserver/deployment.go
> +				Value: &dnsConfigOptionNdots,
What libc does on resolving is: trying to resolve as a fqdn and then adding all entries from search list and try to resolve that.
`ndots` is the minimum number of dots which is required to check if the given name resolves as a fqdn without any suffix. Default (libc) is 1 IIRC, but because of heavy use of subdomains in k8s that got increased.

2018-06-27 08:10 UTC, mrIncompetent commented
@thz Did you tested this PR according to https://github.com/kubermatic/kubermatic/blob/master/docs/proposals/cluster-dns.md#task--effort ?

2018-07-02 07:47 UTC, mrIncompetent commented
@thz Whats left on this PR?

2018-07-02 07:48 UTC, thz commented
Just the e2e run is left. @mrIncompetent

2018-07-02 07:54 UTC, mrIncompetent commented on api/pkg/resources/resources.go
> +			"cluster.local",
`cluster.Spec.ClusterNetwork.DNSDomain` instead if hardcoded `cluster.local`

2018-07-03 14:00 UTC, alvaroaleman requested changes

2018-07-03 14:00 UTC, alvaroaleman commented on api/pkg/resources/resources.go
> +			cluster.Spec.ClusterNetwork.DNSDomain,
What about `${NS}.svc.${DNSDOMAIN]` and `svc.${DNSDOMAIN}`?

2018-07-03 14:00 UTC, alvaroaleman commented on api/cmd/image-loader/main.go
> +	fakeCluster.Spec.ClusterNetwork.DNSDomain = "cluster.local"
Is this required?

2018-07-03 14:00 UTC, alvaroaleman commented on config/test/admission-webhooks/admissionvalidator-svc.yaml
> +apiVersion: apps/v1
Any chance we can actually deploy and test this with the existing e2e runner? Doesn't have to be in this pull, but maybe just create a ticket for it

2018-07-03 14:11 UTC, thz commented on api/cmd/image-loader/main.go
> +	fakeCluster.Spec.ClusterNetwork.DNSDomain = "cluster.local"
I prefer to return an error in `UserClusterDNSPolicyAndConfig` when the DNSDomain is empty. Unfortunately the image-loader fails then, when fakeCluster has no domain.

2018-07-03 14:14 UTC, thz commented on api/pkg/resources/resources.go
> +			cluster.Spec.ClusterNetwork.DNSDomain,
See discussion in this PR. Current Idea is to go with the shortest possible list. I have no strong opinion here, so perhaps we need to reopen that discussion?

2018-07-03 14:16 UTC, thz commented on config/test/admission-webhooks/admissionvalidator-svc.yaml
> +apiVersion: apps/v1
The problem is that the e2e runner fails even without this change.
Currently this is tested with admission webhook and reachability of an extension apiserver.

2018-07-03 14:17 UTC, alvaroaleman commented on api/pkg/resources/resources.go
> +			cluster.Spec.ClusterNetwork.DNSDomain,
I would prefer to stay with the kube defaults here, just to ensure we don't end up with some weird issues that are ultimatively caused by the apiserver not having the correct search domains

2018-07-03 14:28 UTC, thz commented on api/pkg/resources/resources.go
> +			cluster.Spec.ClusterNetwork.DNSDomain,
@mrIncompetent, opinion?

2018-07-03 15:17 UTC, mrIncompetent commented on api/pkg/resources/resources.go
> +			cluster.Spec.ClusterNetwork.DNSDomain,
Nope

2018-07-05 12:12 UTC, thz commented
```
2018-07-05T14:07:07+0200 Ran 154 of 891 Specs in 392.394 seconds
2018-07-05T14:07:07+0200 SUCCESS! -- 154 Passed | 0 Failed | 0 Pending | 737 Skipped 
```
e2e conformance test passed.

2018-07-05 12:13 UTC, thz commented on api/pkg/resources/resources.go
> +			cluster.Spec.ClusterNetwork.DNSDomain,
@alvaroaleman I added back the `kube-system.svc.${DNSDOMAIN}` and `svc.${DNSDOMAIN}`.

2018-07-05 12:15 UTC, mrIncompetent submitted a review, later dismissed

2018-07-05 12:21 UTC, alvaroaleman submitted a review, later dismissed

2018-07-05 12:28 UTC, thz commented
Meanwhile a new commit landed and I had to rebase...

2018-07-05 12:30 UTC, alvaroaleman approved these changes

2018-07-05 12:35 UTC, mrIncompetent approved these changes

2018-07-05 12:37 UTC, merged