fix: check for cilium system application in default application controller
kubermatic/kubermatic pull request #13870
Opened 2024-11-18 08:59 UTC by cnvergence

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note

```

**Documentation**:

```documentation

```

2024-11-18 09:46 UTC, SimonTheLeg requested changes
I have left some comments. 

In general, I am wondering if we should extract the `if cluster.Spec.CNIPlugin != nil && ...` logic into its own separate function since we are re-using it in the inital-application controller as well

2024-11-18 09:46 UTC, SimonTheLeg commented on pkg/controller/seed-controller-manager/initial-application-installation-controller/controller.go
> +		ciliumApp, err := util.GetCNIApplicationInstallation(ctx, userClusterClient, cluster.Spec.CNIPlugin.Type)
nit: atm we only have cilium, but I think we should call this cniApp, as in the func could return something different in the future.

2024-11-18 09:46 UTC, SimonTheLeg commented on pkg/controller/seed-controller-manager/default-application-controller/controller.go
> +			return &reconcile.Result{RequeueAfter: 10 * time.Second}, nil
Even if we use the same code somewhere else already, I think we should add a test for this as well in here. We do the same in the initial app-controller logic.
https://github.com/kubermatic/kubermatic/blob/0033300c919b3b35da913a23eabb6b394cf49e8e/pkg/controller/seed-controller-manager/initial-application-installation-controller/controller_test.go#L165

2024-11-18 10:02 UTC, cnvergence commented
Thanks @SimonTheLeg, we should do this definitely

2024-11-19 14:57 UTC, cnvergence commented
/retest

2024-11-20 08:38 UTC, SimonTheLeg commented
/lgtm
/approve

2024-11-20 08:53 UTC, embik approved these changes
/approve

2024-11-20 08:54 UTC, cnvergence commented
/cherry-pick release/v2.26

2024-11-20 11:04 UTC, embik commented
/retest

2024-11-20 11:40 UTC, merged