centOS removal
kubermatic/kubermatic pull request #13917
Opened 2024-12-05 09:43 UTC by julioc-p

**What this PR does / why we need it**:
This PR removes CentOS as a supported operating system.

**Which issue(s) this PR fixes**:

Fixes #13580 

**What type of PR is this?**

/kind cleanup

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
CentOS removed as a supported operating system.
```

**Documentation**:

```documentation
https://github.com/kubermatic/docs/pull/1804
```

2024-12-05 09:44 UTC, julioc-p commented
/cc @ahmedwaleedmalik

2024-12-05 10:32 UTC, ahmedwaleedmalik commented
/retitle [release/v2.26] Remove CentOS as supported Operating System

2024-12-05 10:35 UTC, ahmedwaleedmalik commented on .prow/dualstack.yaml
> +
Drop the extra lines

2024-12-05 10:47 UTC, ahmedwaleedmalik requested changes
Although it's benign but i'd recommend not updating anything in the `docs/proposals` directory. Those are historic documents and should represent the state in which they were added to the repo.

2024-12-05 10:47 UTC, ahmedwaleedmalik commented on go.mod
> +	k8c.io/operating-system-manager v1.6.1-0.20241118134103-5db575f65108
Just so you know, you'll need to backport your changes to release branches of MC v1.60 and OSM v1.6. New patch releases will be required for this and those versions should be used here.

We can merge these PRs with the current tags but just make sure that we take care of updating to actual semver tags afterwards.

2024-12-05 13:34 UTC, ahmedwaleedmalik approved these changes
/approve

2024-12-05 13:35 UTC, ahmedwaleedmalik commented
cc @kubermatic/sig-release-managers

2024-12-09 10:47 UTC, xrstf commented
SIG Release is still unsure about this and sadly SIG Cluster last week did not note down the reasons that speak _for_ a backport. We'll bring this up again in the Engineering Management Sync, as we also do not urgently need this backport (next KKP patch releases are planned for 2.26).

2024-12-10 10:04 UTC, xrstf commented
We just talked about this again and now it's clear that CentOS is so dead and broken, there is basically no chance of anyone using it in KKP 2.26.

2024-12-10 11:03 UTC, merged