add default namespace spec to appdef crd
kubermatic/kubermatic pull request #13916
Opened 2024-12-04 13:53 UTC by soer3n

**What this PR does / why we need it**:
This pr adds a field to applicationdefinition crd to be able to configure a default namespace.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note

```

**Documentation**:

```documentation

```

2024-12-04 13:59 UTC, SimonTheLeg requested changes

2024-12-04 13:59 UTC, SimonTheLeg commented on pkg/apis/apps.kubermatic/v1/application_definition.go
> +	// DefaultNamespace specifies default namespace for the UI which are passed to helm templating when creating an application. Comments are preserved.
```suggestion
	// DefaultNamespace specifies the default namespace which is used if a referencing ApplicationInstallation has no target namespace defined. If unset, the name of the ApplicationDefinition is being used instead.
```

2024-12-04 14:10 UTC, SimonTheLeg commented
/approve

2024-12-04 14:16 UTC, SimonTheLeg commented
/lgtm

2024-12-04 15:50 UTC, SimonTheLeg commented
/lgtm

2024-12-04 16:15 UTC, merged

2024-12-05 11:02 UTC, ahmedwaleedmalik commented
Reference: https://github.com/kubermatic/kubermatic/issues/12578