Use calculated DNS-IP
kubermatic/kubermatic pull request #1393
Opened 2018-06-27 11:54 UTC by glower

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1357

**Special notes for your reviewer**:

**Release note**:
```release-note
Non-default IP can now be used for cluster DNS
```

2018-06-27 11:57 UTC, thz commented on api/pkg/controller/addon/controller.go
> +		return nil, fmt.Errorf("failed to get cluster dns ip")
perhaps add the cluster name to the error.

2018-06-27 12:05 UTC, thz commented
LGTM when unused `getKubeDNSClusterIP ()` is removed.
(But I doubt that I am an authorized reviewer...)

2018-06-27 12:27 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
>  	kerrors "k8s.io/apimachinery/pkg/api/errors"
we group imports:
- std-lib
- random
- github.com/kubermatic
- k8s.io

2018-06-27 12:29 UTC, mrIncompetent requested changes
I guess you also want to set the flag on the machine-controller deployment?

2018-06-27 13:39 UTC, glower commented
@mrIncompetent can you please tell me where in machine-controller deployment DNS IP will be set? Slack is not working today :(

2018-06-27 14:27 UTC, mrIncompetent commented
https://github.com/kubermatic/kubermatic/blob/master/api/pkg/resources/machinecontroler/deployment.go

2018-06-27 16:26 UTC, mrIncompetent commented on api/pkg/resources/resources.go
> +func UserClusterDNSResolverIP(cluster *kubermaticv1.Cluster) string {
Please make this function return an error.
Otherwise its a pain to debug.

During addon-templating its fine to have a wrapper function which calls `runtime.HandleErr` whenever a error happens

2018-06-27 16:27 UTC, glower commented on api/pkg/resources/resources.go
> +func UserClusterDNSResolverIP(cluster *kubermaticv1.Cluster) string {
OK, will fix it

2018-06-27 16:39 UTC, glower commented on api/pkg/resources/resources.go
> +func UserClusterDNSResolverIP(cluster *kubermaticv1.Cluster) string {
done

2018-06-28 07:03 UTC, mrIncompetent approved these changes

2018-06-28 07:14 UTC, merged