feat: Configure UserCluster Authorization Webhook via CRD
kubermatic/kubermatic pull request #13930
Opened 2024-12-10 18:35 UTC by 4ch3los

**What this PR does / why we need it**:
I had some spare time and started the Implementation for the issue #13925
We started some basic testing, but will test it more deeply soon(so i would consider it WIP for now) and add some documentation then aswell

**Which issue(s) this PR fixes**:
Fixes #13925

**What type of PR is this?**
Add one of the following kinds:
/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Added support for configuring a Authorization Webhook for UserClusters
```

**Documentation**:

```documentation
TBD
```

2024-12-12 12:16 UTC, csengerszabo commented
/assign @xrstf

2025-01-06 09:22 UTC, xrstf commented on pkg/apis/kubermatic/v1/cluster.go
> +}
The mount path should not be determined in pkg/apis, it's an implementation detail of KKP that has no place being in our stable public API definitions. Or to put it differently, there is no reason for anyone outside of KKP to know where we mount something in the apiserver Deployment.

2025-01-06 09:22 UTC, xrstf commented on pkg/apis/kubermatic/v1/cluster.go
> +	return true
For consistency please add an empty line here.

2025-01-06 09:23 UTC, xrstf commented on pkg/apis/kubermatic/v1/cluster.go
> +}
I would also not make this part of the KKP API, but keep it in the apiserver's package.

2025-01-10 13:44 UTC, 4ch3los commented on pkg/apis/kubermatic/v1/cluster.go
> +}
Sorry for the late response, should i move the default value to the resource package?

For the second approach, the mountpath can definetly be relevant for the user,  as in most cases the secret contains atleast two files, the AuthorizationConfiguration itself and a kubeconfig format file which describes the desired api endpoint. And the first will reference the second one with the absolut path.

Example:
the file passed to the api server:
authz-webhook.yml
```
apiVersion: apiserver.config.k8s.io/v1beta1
kind: AuthorizationConfiguration
authorizers:
  - type: Webhook
    name: webhook
    webhook:
      authorizedTTL: 30s
      unauthorizedTTL: 30s
      timeout: 3s
      subjectAccessReviewVersion: v1
      matchConditionSubjectAccessReviewVersion: v1
      failurePolicy: Deny
      connectionInfo:
        type: KubeConfigFile
        kubeConfigFile: /etc/kubernetes/authorization-configs/opa-endpoint.yaml
  - type: Node
    name: node
  - type: RBAC
    name: rbac
```

the referenced kubeConfigFile ex.:
opa-endpoint.yaml
```
clusters:
  - name: opa
	cluster:
	  insecure-skip-tls-verify: true
	  server: https://opa-authz-webhook.opa.svc.cluster.local:8181/v0/data/k8s/authz/decision
users:
  - name: api-server
	user:
	  token: test-token
current-context: webhook
contexts:
  - context:
	  cluster: opa
	  user: api-server
    name: webhook
```

2025-03-06 08:46 UTC, 4ch3los commented
Hey @xrstf!
Adjusted the things and moved the logic to the apiserver package 👍

2025-04-25 13:30 UTC, embik requested changes
Some minor comments.

2025-04-25 13:30 UTC, embik commented on pkg/apis/kubermatic/v1/cluster.go
> +	AuthorizationConfigurationFile *AuthorizationConfigurationFile `json:"authorizationConfigurationFile,omitempty"`
This should have a comment. What is it?

2025-04-25 13:30 UTC, embik commented on pkg/apis/kubermatic/v1/cluster.go
> +	SecretMountPath string `json:"secretMountPath"`
I guess this should have an `omitempty` tag if it there is a default.

2025-04-25 13:30 UTC, embik commented on pkg/resources/apiserver/deployment.go
> +func getVolumeMounts(data *resources.TemplateData, isKonnectivityEnabled, isEncryptionEnabled bool, isAuditWebhookEnabled bool) []corev1.VolumeMount {
Since `isKonnectivityEnabled` is derived from `data` in the call to `getVolumeMounts`, we should probably remove the superfluous parameter here.

2025-04-25 13:30 UTC, embik commented on pkg/validation/cluster.go
> +	}
This feels wrong, an Authorization config file in fact needs a kubeconfig for the webhook. How would you provide such a kubeconfig if the webhook config cannot be used? In fact, I think we should be checking for custom enabled modes here, because that will be overridden by the config file if I'm not mistaken.

2025-04-30 11:07 UTC, 4ch3los commented on pkg/validation/cluster.go
> +	}
The current implemementation support both ways of configuring the webhook. The old using the --authorization-webhook-config-file parameter and a kubeconfig like file for the endpoint. And the new --authorization-config flag(https://kubernetes.io/docs/reference/access-authn-authz/authorization/#using-configuration-file-for-authorization) which allows a more advanced configuration. But they are not compatible with each other

2025-05-12 09:38 UTC, embik commented on pkg/validation/cluster.go
> +	}
Okay, for my understanding, how do I pass the kubeconfig in a AuthorizationConfig? The one here:

```yaml
connectionInfo:
        # Controls how the webhook should communicate with the server.
        # Valid values:
        # - KubeConfigFile: use the file specified in kubeConfigFile to locate the
        #   server.
        # - InClusterConfig: use the in-cluster configuration to call the
        #   SubjectAccessReview API hosted by kube-apiserver. This mode is not
        #   allowed for kube-apiserver.
        type: KubeConfigFile
        # Path to KubeConfigFile for connection info
        # Required, if connectionInfo.Type is KubeConfigFile
        kubeConfigFile: /kube-system-authz-webhook.yaml
```

Does this mean the authorization-config secret should have multiple files?

2025-05-12 14:38 UTC, 4ch3los commented on pkg/validation/cluster.go
> +	}
Yeah exactly, the secrets will be mounted without a subPath so it can contain the AuthorizationConfig itself, aswell as the KubeConfig

2025-05-22 11:10 UTC, embik requested changes

2025-05-22 11:10 UTC, embik commented on sdk/apis/kubermatic/v1/cluster.go
> +	// Optional: AuthorizationConfig to configure the apiserver authorization modes
This PR looks great, sorry for the slow review on it. Given that we don't have tests for this, can you please add a note here (and regenerate the CRD) that this is an experimental feature for now?

```suggestion
	// Optional: AuthorizationConfig to configure the apiserver authorization modes. This feature is experimental right now
```

2025-05-26 09:48 UTC, 4ch3los commented on sdk/apis/kubermatic/v1/cluster.go
> +	// Optional: AuthorizationConfig to configure the apiserver authorization modes
No Problem :) Added and executed codegen

2025-05-26 09:50 UTC, embik commented
/ok-to-test

2025-05-28 11:55 UTC, xrstf commented
/approve
/lgtm

2025-05-28 13:51 UTC, merged