E2E tests for Default Application Catalog
kubermatic/kubermatic pull request #13942
Opened 2024-12-18 21:39 UTC by iakmc

**What this PR does / why we need it**:
Prow jobs and E2E tests are added. There are prow jobs for each application from the default app catalog, and each job verifies that the ApplicationInstallation object has been installed successfully, its conditions are in a healthy state, a Helm release has been deployed, and the pods of the given application have been deployed successfully.
**NOTE**: The cert-manager pod that is failing in the prow job is also failing in the dev environment, so the issue is not caused by my code.

**Which issue(s) this PR fixes**:

Fixes #13934

**What type of PR is this?**
/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Prow jobs and E2E tests are added. There are prow jobs for each application from the default app catalog, and each job verifies that the ApplicationInstallation object has been installed successfully, its conditions are in a healthy state, a Helm release has been deployed, and the pods of the given application have been deployed successfully. Additionally, end-to-end (E2E) tests are added to verify that the pods for every application in the default application catalog are deployed successfully. These tests help ensure compatibility when updating the version of each application.
```

**Documentation**:

```documentation
NONE
```

2024-12-20 14:06 UTC, embik commented on hack/ci/run-tests-default-application-catalog.sh
> +source hack/ci/setup-kubermatic-in-kind-and-test-default-application-catalog-apps.sh
I would try to re-use `hack/ci/setup-kubermatic-in-kind.sh` here and run the additional steps you added to the script to _this_ script (`hack/ci/run-tests-default-application-catalog.sh`).

2024-12-23 10:50 UTC, iakmc commented on hack/ci/run-tests-default-application-catalog.sh
> +source hack/ci/setup-kubermatic-in-kind-and-test-default-application-catalog-apps.sh
Yes, quite a few steps are repeated, I'll use the other script, I just want to configure it to work and then I'll refactor the code.

2025-01-07 07:42 UTC, embik commented on pkg/test/e2e/default-app-catalog-applications-test/argocd/argocd_test.go
> +		}
This should _probably_ also check if the app is somewhat healthy (e.g. if its Pods are running). I'm not sure if the application-controller publishes such information to the `ApplicationInstallation` status, but if not, we should maybe try to look for the pods created by the app.

2025-01-17 13:55 UTC, embik commented on .prow/applications-catalog.yaml
> +  - name: argocd
Job names should match the usual pattern we use, so e.g. this could/should be `pre-kubermatic-appcatalog-argocd`.

2025-01-23 15:02 UTC, embik requested changes

2025-01-23 15:02 UTC, embik commented on .prow/applications-catalog.yaml
> +    run_if_changed: "(pkg/ee/default-application-catalog/|.prow/)"
Can we make this run only if the YAML file for the app in specific changes? If we update any app, it would trigger _all_ app tests, which seems overkill.

2025-01-23 15:02 UTC, embik commented on .prow/applications-catalog.yaml
> +  - name: pre-kubermatic-appcatalog-sealed-secrets
Just a reminder, this is not in the catalog. We shouldn't test for it.

2025-01-24 07:33 UTC, embik requested changes

2025-01-24 07:33 UTC, embik commented on .prow/applications-catalog.yaml
> +              memory: 18Gi
I don't think we need that many resources for each of those jobs. Can you please try if 4GB memory / 2 CPUs as requests and 6GB as memory limit suffice?

2025-01-24 09:26 UTC, embik commented
/test pre-kubermatic-e2e-aws-ubuntu-1.32

2025-01-24 12:54 UTC, embik requested changes

2025-01-24 12:54 UTC, embik commented on hack/verify-boilerplate.sh
> +  -exclude .prow/applications-catalog.yaml
These things should not be excluded from boilerplate verification.

2025-01-27 08:14 UTC, embik approved these changes
/approve

2025-01-31 11:56 UTC, SimonTheLeg requested changes
Okay I think I already found the nvidia issue. I think it is this line here
https://github.com/kubermatic/kubermatic/pull/13942/files#diff-3a0aa6ce2c59c1329bf29e3fd01f9ab102567de456634b2598f52e99c3a79c49R397

That being said, since I now did a higher-level review of the tests, I think there are some things which need to be changed

1. I think the test should create an appsv1.Application installation (https://github.com/iakubermatic/kubermatic/blob/c64427acfde6639a2633d910590ee0515d5ed239/pkg/apis/apps.kubermatic/v1/application_installation.go#L47) and apply this to the user cluster after it has been created instead of adding annotation on the user cluster. To explain: The annotation feature allows you to create initial applications of a cluster and make them portable for templates. However with this test we mainly want to test what and end-user is doing when adding an application after the cluster has been created. 
2. (I am using Argo as an example, but following bullet applies to all Apps) I think for quicker debugging it is good that the version and application name can be provided inside prow (https://github.com/kubermatic/kubermatic/pull/13942/files#diff-3a0aa6ce2c59c1329bf29e3fd01f9ab102567de456634b2598f52e99c3a79c49R39), however we should definitely set them to the values which are specified in our Appdefs (https://github.com/kubermatic/kubermatic/pull/13942/files#diff-aa5fb43ba7162524d19f9857ee3a013b73b5e623b81236e6875f6545025fb824R48). Ideally directly read them in from that file. Because otherwise when we upgrade we run into a real issue where the test is running a different version than what is in the updated catalog AppDef. It also avoids that we keep names and versions in multiple locations. Furthermore this also applies to the valuesBlock. Here it is paramount that we test the valuesBlock which is inside the AppDef and not override it like here https://github.com/iakubermatic/kubermatic/blob/c64427acfde6639a2633d910590ee0515d5ed239/pkg/test/e2e/default_app_catalog_tests/argocd/argocd.go#L36. Otherwise we are not testing our AppDefs which make up the default app catalog
3. I think the order of testing in testUserCluster() should be
	1. Check if applicationInstallation exists
	2. Check if the release is in a deployed state
	3. check if the pods became ready
My reasoning on this is as follows: AppInstall is always the object that is going to trigger helm deployments and helm deployments are going to lead to the creation of the pods. That being said I would implement it as follows
	* wait for AppInstall to be created
	* wait for helm release to be in deployed. If timeout -> print out the helm error message and still run the wait for pods to get ready. If timeout -> print out pod status. Of course in any of these cases fail the whole test needs to fail.
4. I think we should simplify the tests in the following way:
	[key](https://github.com/iakubermatic/kubermatic/blob/c64427acfde6639a2633d910590ee0515d5ed239/pkg/test/e2e/default_app_catalog_tests/argocd/argocd.go#L78) and names should be specified in the prow.yaml and then be passed to the test. Subsequently the test does not require any switch-case logic anymore or any differentiation between the apps, it just computes the expected namespace (which is metadata.name of the Appdef, but we pass it into the prow job anyways after implementing what I stated in 2)) and then checks for the passed in list of pods if they are ready. I think this is going to simplify the code a lot and makes sure that we do not have a drift between the default catalog and the test

2025-02-11 11:49 UTC, ahmedwaleedmalik commented
/retitle E2E tests for Default Application Catalog

2025-03-11 11:52 UTC, embik commented on pkg/test/e2e/default_app_catalog_tests/application_test.go
> +	time.Sleep(860 * time.Second)
Is this just here for debugging the job? Should probably be removed since you're doing a `wait.PollLog` below already :)

2025-03-12 19:34 UTC, SimonTheLeg requested changes
Left some overall comments.

For me however there are two bigger topics still left:
1. At the moment the test only tests one version of an Application. If the AppDef defines more than one version, then these are not being tested. We definitely want to test all versions inside the catalogue. We can have a look at this issue together
2. In the description it says that the cert-manager is not working, but it's also not working on dev. However for me on dev it seems to be working. Can you give more details what the issue was/is on dev?
![grafik](https://github.com/user-attachments/assets/8e07fbb4-dae9-4afa-96ab-fb824c001fcf)

2025-03-12 19:34 UTC, SimonTheLeg commented on .prow/applications-catalog.yaml
> +    run_if_changed: "(pkg/ee/default-application-catalog/argocd-app.yaml)"
```suggestion
    run_if_changed: "(pkg/ee/default-application-catalog/aikit-app.yaml)"
```

2025-03-12 19:34 UTC, SimonTheLeg commented on pkg/test/e2e/default_app_catalog_tests/application_test.go
> +	}
you can make use of `util.EnsureNamespace` for this
https://github.com/kubermatic/kubermatic/blob/269e8e22a32d5b9aefb15ddbeb491ed7b3babf05/pkg/install/util/kubernetes.go#L29

2025-03-12 19:34 UTC, SimonTheLeg commented on pkg/test/e2e/default_app_catalog_tests/application_test.go
> +		if containsString(secret.Name, appName) && secret.Type == "helm.sh/release.v1" {
```suggestion
		if strings.Contains(secret.Name, appName) && secret.Type == "helm.sh/release.v1" {
```

2025-03-12 19:34 UTC, SimonTheLeg commented on pkg/test/e2e/default_app_catalog_tests/application_test.go
> +			if status, exists := secret.Labels["status"]; exists && status == "deployed" {
since it is a string[string] map, it is safe to directly evaluate it like this: the value will be "" if the map entry does not exist


```suggestion
			if secret.Labels["status"] == "deployed" {
```

2025-03-12 19:34 UTC, SimonTheLeg commented on pkg/test/e2e/default_app_catalog_tests/application_test.go
> +	log.Info("Checking for ApplicationInstallation...")
```suggestion
	log.Info("Check if ApplicationInstallation exists")
```

2025-03-12 19:34 UTC, SimonTheLeg commented on pkg/test/e2e/default_app_catalog_tests/application_test.go
> +	if applicationName == "cluster-autoscaler" {
this is not required, it should be part of the defaultValuesBlock of this app

https://github.com/kubermatic/kubermatic/blob/main/pkg/ee/default-application-catalog/applicationdefinitions/cluster-autoscaler.yaml#L40

2025-03-12 19:34 UTC, SimonTheLeg commented on pkg/test/e2e/default_app_catalog_tests/application_test.go
> +	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
this is in the wrong order. You need to use [gimps](https://github.com/xrstf/gimps) to format all the import statements for verify job to succeed

2025-03-12 19:34 UTC, SimonTheLeg commented on pkg/test/e2e/default_app_catalog_tests/application_test.go
> +	if applicationName == "gpu-operator" {
I think this is not required if you adapt the values in the applications-catalog.yaml file.

2025-03-13 23:11 UTC, iakmc commented on pkg/test/e2e/default_app_catalog_tests/application_test.go
> +	if applicationName == "cluster-autoscaler" {
It doesn't read them and the pods aren't deployed because there are no autoDiscovery values.

2025-03-13 23:13 UTC, iakmc commented on pkg/test/e2e/default_app_catalog_tests/application_test.go
> +	if applicationName == "gpu-operator" {
nvidia-gpu-plane and with the other IDs generated in the name, there was some error that the name was too long and no pods were deployed or something like that

2025-04-22 06:52 UTC, closed without merging

2025-04-22 07:57 UTC, SimonTheLeg commented
superseded by
https://github.com/kubermatic/kubermatic/pull/14312