Prometheus statefulset
kubermatic/kubermatic pull request #1399
Opened 2018-06-27 17:24 UTC by metalmatze

**What this PR does / why we need it**:
We want to move away from the Prometheus Operator an run Prometheus as a Statefulset. See discussions in #1156.

**Special notes for your reviewer**:

- Please ignore the gigantic `config/monitoring/prometheus/rules/rules.yaml` as it is a file that's generated by jsonnet based on the alerts coming from [kubernetes-monitoring/kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin).
- There are still some alerting rules missing that we added ourselves and they'll return in a following PR.
- The alerts don't have a _summary_ & _description_ anymore, but a _message_ instead. Please not that we need to update the alertmanager templates for correct alerts again. Coming in a next PR.

**Release note**:
```release-note monitoring
Prometheus is now a Statefulset
```

2018-06-27 17:24 UTC, metalmatze commented
It's probably best to merge this tomorrow when I can also start working on bringing the Alertmanager with updated templates as PR.

PTAL @mrIncompetent @alvaroaleman

2018-06-28 09:53 UTC, alvaroaleman requested changes

2018-06-28 09:53 UTC, alvaroaleman commented on config/monitoring/prometheus/config/prometheus.yml
> +  - source_labels: [__meta_kubernetes_endpoint_port_name]
As already mentioned somewhere, this is by default now on the `http-metrics` port under the `/metrics/cadvisor` uri

2018-06-28 09:53 UTC, alvaroaleman commented on config/monitoring/prometheus/config/prometheus.yml
> +  - source_labels: [__meta_kubernetes_pod_annotation_kubermatic_metric_path]
Why do we use our own label instead of the default `prometheus.io/[...]`? Is it to be able to seperate stuff that has to be scraped by the kubermatic prometheus from stuff that has to be scraped from the user cluster prometheus?

If yes: WDYT about moving the user cluster prometheus inside the user cluster as an addon?

2018-06-28 09:53 UTC, alvaroaleman commented on config/monitoring/jsonnetfile.json
> +            "version": "master"
https://github.com/kubernetes-monitoring/kubernetes-mixin is alpha according to its README, can we plase pin this to a specific revision?

2018-06-28 10:04 UTC, metalmatze commented on config/monitoring/jsonnetfile.json
> +            "version": "master"
That should be done in the `jsonnetfile.lock.json`. I think it's a bug that it's not there yet. I'll pin it.

2018-06-28 11:02 UTC, mrIncompetent commented on config/monitoring/kube-state-metrics/templates/deployment.yaml
>        - name: addon-resizer
I don't think the addon-resized will work.
Afaik does this consider the cluster its running it for scaling. And kube-state-metrics depends on the data from the user-cluster.

2018-06-28 11:08 UTC, mrIncompetent commented on config/monitoring/kube-state-metrics/templates/deployment.yaml
>        - name: addon-resizer
Nevermind, i was in the user-cluster context.

2018-06-28 11:12 UTC, mrIncompetent commented on config/monitoring/prometheus/config/prometheus.yml
> +  - source_labels: [__meta_kubernetes_pod_annotation_kubermatic_metric_path]
> WDYT about moving the user cluster Prometheus inside the user cluster as an addon?

Inside? So it runs as a Pod inside the user-cluster? On one of the users worker nodes?

2018-06-28 11:16 UTC, mrIncompetent commented on config/monitoring/prometheus/templates/statefulset.yaml
> +          storage: 100Gi
This should be configurable.
Can you check how much storage we need on cloud (europe) and calculate the storage needed per cluster?

2018-06-28 11:36 UTC, alvaroaleman commented on config/monitoring/prometheus/config/prometheus.yml
> +  - source_labels: [__meta_kubernetes_pod_annotation_kubermatic_metric_path]
Yes

2018-06-28 11:45 UTC, mrIncompetent commented on config/monitoring/prometheus/config/prometheus.yml
> +  - source_labels: [__meta_kubernetes_pod_annotation_kubermatic_metric_path]
Had a offline discussion about this.
We currently do not want to deploy Prometheus inside the user-cluster. Reasons:
- User then want's to use it for own stuff
  - we would nee to make it configurable
- Lots of noise

Reason why we deploy a own Prometheus inside the cluster-namespace:
- So we can aggregate and do not pollute the "main" Prometheus

2018-06-28 13:30 UTC, metalmatze commented on config/monitoring/prometheus/templates/statefulset.yaml
> +          storage: 100Gi
```
cluster-2rxkxrww6p      289.0M
cluster-4qhsgslvb6      293.1M
cluster-5g7zrr4vsn      546.0M
cluster-rwhxp9j5j       321.2M
```
I've checked a few Prometheus running inside the cluster namespaces. So I guess ~500MB per namespace. We only federate very few metrics from these to the Kubermatic Prometheus though. I'd say we won't feel the difference as things like _kube-state-metrics_ have way higher metrics cardinality. 
On GKE we should still keep the size 100Gi+ as IOPS below that decrease and we need them for Prometheus.

I'm making it configurable in the next commit.

2018-06-28 13:56 UTC, metalmatze commented on config/monitoring/prometheus/config/prometheus.yml
> +  - source_labels: [__meta_kubernetes_pod_annotation_kubermatic_metric_path]
Looking at the annotations before changing them again, I remembered why I simply called them `kubermatic/scrape: 'true'` & `kubermatic/scrape_port: '9090'`: The primary reason was to annotate only the pods that we want to scrape explicitly. Using the default annotations for example SysEleven could deploy an application to the seed cluster and start scraping it, even thought they might not explicitly want to do this.

I'm not entirely sure if that's better though. Just wanted to give you a run down of my thought process there.

2018-06-28 14:01 UTC, alvaroaleman commented on config/monitoring/prometheus/config/prometheus.yml
> +  - source_labels: [__meta_kubernetes_pod_annotation_kubermatic_metric_path]
Yes, makes sense :+1:

2018-06-28 14:07 UTC, alvaroaleman approved these changes

2018-06-28 14:13 UTC, merged