Feature/1216 create efk chart
kubermatic/kubermatic pull request #1430
Opened 2018-07-02 14:40 UTC by pkavajin

**What this PR does / why we need it**:
Adds charts for a EFK Stack in the seed clusters.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1216 

**Special notes for your reviewer**:

**Release note**:
```release-note
Added EFK stack in seed clusters
```

2018-07-03 09:47 UTC, guusvw requested changes

2018-07-03 09:47 UTC, guusvw commented on config/logging/elasticsearch/templates/es-data-stateful.yaml
> +        - vm.max_map_count=262144
Please make the value customizable

2018-07-03 09:47 UTC, guusvw commented on config/logging/elasticsearch/templates/es-data-stateful.yaml
> +      initContainers:
Would be nice, if I can disable the `initContainer` - there are cases where I wouldn't update the `max_map_count` (running multiple ES on one node)

2018-07-03 09:47 UTC, guusvw commented on config/logging/elasticsearch/templates/es-ingest-dep.yaml
> +        - vm.max_map_count=262144
Please make the value customizable

2018-07-03 09:47 UTC, guusvw commented on config/logging/elasticsearch/templates/es-master-dep.yaml
> +        - vm.max_map_count=262144
Please make the value customizable

2018-07-03 09:47 UTC, guusvw commented on config/logging/elasticsearch/templates/es-master-dep.yaml
> +      initContainers:
Would be nice, if I can disable the `initContainer` - there are cases where I wouldn't update the `max_map_count` (running multiple ES on one node)

2018-07-03 09:47 UTC, guusvw commented on config/logging/fluentd/Chart.yaml
> +  - https://github.com/kubermatic/kubermatic/config
the repo don't exist anymore

2018-07-03 09:47 UTC, guusvw commented on config/logging/kibana/templates/kibana-deployment.yaml
> +        imagePullPolicy: {{.Values.logging.kibana.image.pullPolicy}}
missing whitespace

2018-07-03 09:47 UTC, guusvw commented on config/logging/kibana/values.yaml
> +    auth: 'YWRtaW46JGFwcjEkUFR0Y3lQc0MkWVZFTk9nZmpiVE52RWtSeVk1ZjJULgo='
Would be nice, if we can also set non-default credentials in the values

2018-07-03 09:52 UTC, mrIncompetent commented on config/logging/up.sh
> +helm $HELMOPTS upgrade -i kibana --namespace logging -f ./kibana/values.yaml ./kibana
I'm not a fan of this.
Please rather document the commands in https://github.com/kubermatic/docs/blob/master/content/installation/install_master/_index.en.md#deploy-all-charts

Also the `--tiller-namespace=kubermatic-installer` is something only we and one customer uses.

2018-07-03 09:52 UTC, mrIncompetent commented on config/logging/kibana/values.yaml
> +    auth: 'YWRtaW46JGFwcjEkUFR0Y3lQc0MkWVZFTk9nZmpiVE52RWtSeVk1ZjJULgo='
explain how this gets generated

2018-07-03 09:54 UTC, mrIncompetent commented on config/logging/kibana/values.yaml
> +    host: "kibana.dev.kubermatic.io"
Please let this empty. Its a required field and the installation must fail when its empty

2018-07-03 09:54 UTC, mrIncompetent commented on config/logging/up.sh
> +helm $HELMOPTS upgrade -i kibana --namespace logging -f ./kibana/values.yaml ./kibana
Please also clearly state that all logging charts must be installed in the same namespace

2018-07-03 09:55 UTC, mrIncompetent commented on config/logging/fluentd/Chart.yaml
> +  - https://github.com/kubermatic/kubermatic/config
It does :) Its https://github.com/kubermatic/kubermatic/config not https://github.com/kubermatic/config

2018-07-03 09:56 UTC, mrIncompetent commented
Please configure your IDE to always append a NewLine at the end of each file

2018-07-03 15:16 UTC, pkavajin commented on config/logging/kibana/values.yaml
> +    auth: 'YWRtaW46JGFwcjEkUFR0Y3lQc0MkWVZFTk9nZmpiVE52RWtSeVk1ZjJULgo='
-> huge PITA since thats base64(username:apr1(password))
As discussed we'll let it this way for now and try to implement apr1 in upstream templating and change when upstream change succeeded

2018-07-03 15:25 UTC, mrIncompetent commented on config/logging/kibana/values.yaml
> +    auth: 'YWRtaW46JGFwcjEkUFR0Y3lQc0MkWVZFTk9nZmpiVE52RWtSeVk1ZjJULgo='
Documenting how they get generated for now?

2018-07-05 07:47 UTC, guusvw approved these changes
LGTM

2018-07-05 11:04 UTC, mrIncompetent approved these changes

2018-07-05 11:12 UTC, merged