Create default addons in addon-manager
kubermatic/kubermatic pull request #1431
Opened 2018-07-02 16:12 UTC by glower

**What this PR does / why we need it**:

* Remove addon creation from kubermatic api
* Added default addons creation to addon controller
* added some test
* fixed helm charts
TODO: fix addon documentation in kubermatic/docs

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1380

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

2018-07-03 08:44 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +			glog.Infof("Create addon %s for the cluster %s\n", addon, cluster.Name)
This is not necesarily a create, you call the `enqueueClusterAddons` for all of CREATE/UPDATE/DELETE; this will emit a lot of noise

2018-07-03 08:45 UTC, alvaroaleman commented on api/pkg/controller/addon/controller_test.go
> +func TestFoo(t *testing.T) {
Please name this in a helpfull way, e.G. `TestCreateAddon`

2018-07-03 08:46 UTC, p0lyn0mial commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
I think that we should move the whole block to its own queue, just like we have the queue for addons we should have a queue for clusters.

2018-07-03 08:46 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/rbac-compliant-cluster.go
>  	return cluster, wait.Poll(10*time.Millisecond, 30*time.Second, existsInLister)
we don't have to `wait.Poll` anymore.

2018-07-03 08:47 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/cluster.go
>  	return cluster, wait.Poll(10*time.Millisecond, 30*time.Second, existsInLister)
same here, we don't have to `wait.Poll` anymore.

2018-07-03 08:50 UTC, mrIncompetent requested changes

2018-07-03 08:50 UTC, mrIncompetent commented on api/hack/run-api.sh
> +  -address=127.0.0.1:8081 \
why changing?

2018-07-03 08:50 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +	addonList      []string
rename to `defaultAddonList`

2018-07-03 08:50 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +			c.enqueueClusterAddons(cluster)
why moving the queueing logic into the handler?

2018-07-03 08:50 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +func (c *Controller) enqueueClusterAddons(cluster *kubermaticv1.Cluster) {
Do not put business logic into `enqueue*` functions.
Either rename it or use a queue+workers

2018-07-03 08:50 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +			glog.Infof("Create addon %s for the cluster %s\n", addon, cluster.Name)
This will actually break on the next resync, right?
The next time the cluster gets processed the addons will be installed again -> resulting in a AlreadyExist error

2018-07-03 08:52 UTC, p0lyn0mial commented on api/pkg/controller/addon/controller_test.go
> +	go controller.Run(1, stopCh)
we could improve this UT, usually there is no need to start the controller or the informers, usually we only test the `sync` method. Here is an example: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/controller/rbac/sync_project_test.go#L54

2018-07-03 08:53 UTC, p0lyn0mial commented on config/kubermatic/templates/kubermatic-controller-manager-dep.yaml
> +          # - -addons=/opt/addons
remove ?

2018-07-03 08:54 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
I don't think we should have two work queues inside one controller, that is the same as secretly building a second controller inside the first one.

WDYT about instead changing the `sync` to not use a `addon` name as key but intead a `cluster` ?

2018-07-03 08:55 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/rbac-compliant-cluster.go
>  	return cluster, wait.Poll(10*time.Millisecond, 30*time.Second, existsInLister)
@mrIncompetent can we move this to the client/dashboard ?  can the dashboard "poll" the API ?

2018-07-03 08:57 UTC, glower commented on api/pkg/controller/addon/controller_test.go
> +func TestFoo(t *testing.T) {
ohh, shame on me

2018-07-03 09:02 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
@p0lyn0mial

2018-07-03 09:03 UTC, glower commented on api/hack/run-api.sh
> +  -address=127.0.0.1:8081 \
was not necessary, will change back

2018-07-03 09:06 UTC, p0lyn0mial commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
oh, wait so addons can only be taken/installed from the "default list" ?

2018-07-03 09:11 UTC, p0lyn0mial commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
because for me there are two things:

the first one - once the cluster is added to the system, we need to read the list of addons from the spec and install each of them.

the second one - we need to monitor addons so that we are sure they are in healthy condition.

2018-07-03 09:14 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
No, it would roughly look like this:

* If an `addonInformer` triggers queing, get to the corresponding cluster via an `ownerRef` and put it into the workqeue
* If a `cluster` triggers qeueing, just put it into the `workqeue`

In the sync handler:

* Go over all addons for the cluster
* Ensure `defaultAddons` are among them
* Ensure they are in the desired state

If we can't do that I'd suggest to be honest and write a second controller that just ensures `defaultAddons` are present but doesn't care about their state

CC @mrIncompetent

2018-07-03 09:16 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
> the second one - we need to monitor addons so that we are sure they are in healthy condition.

But its also ensuring they do not get changed, right?

2018-07-03 09:21 UTC, p0lyn0mial commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
right.
not sure if I understand why having more that one queue in the controller is a bad thing ?

2018-07-03 09:27 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
Well, two queues (I am unable to spell this word correctly without googling it) means you have two `syncHandlers` and that is effectively the same as having two controllers, except that you avoid some of the boilerplate code.

The disadvantage IMHO is that its much harder to understand, because there are two completely separate pieces of business logic implemented in one place that have _something_ to do with each other but get reconciled independently

2018-07-03 09:43 UTC, mrIncompetent commented on api/pkg/provider/kubernetes/rbac-compliant-cluster.go
>  	return cluster, wait.Poll(10*time.Millisecond, 30*time.Second, existsInLister)
We actually still need this. The polling here checks if the cluste object exists in the clusterLister.
As the API handles GET requests directly from the Lister, we need to ensure it exists here in the Create endpoint.

Otherwise we create a cluster & the consumer does a GET request directly after resulting in a NotFound

2018-07-03 09:43 UTC, mrIncompetent commented on api/pkg/provider/kubernetes/cluster.go
>  	return cluster, wait.Poll(10*time.Millisecond, 30*time.Second, existsInLister)
See https://github.com/kubermatic/kubermatic/pull/1431#discussion_r199746358

2018-07-03 09:46 UTC, glower commented on api/pkg/provider/kubernetes/rbac-compliant-cluster.go
>  	return cluster, wait.Poll(10*time.Millisecond, 30*time.Second, existsInLister)
I see, so we can just return the cluster obj, don't need to wait for addon creation

2018-07-03 09:59 UTC, glower commented on api/pkg/controller/addon/controller_test.go
> +	go controller.Run(1, stopCh)
cool, will fix it

2018-07-03 10:09 UTC, p0lyn0mial commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
I wrote the controller that makes use of more than one queue :) The controller reconciles projects and project's resources and sets proper RBAC roles for them. I didn't split the controller because my business logic is defined as "assign proper RBAC to projects and its resources".  If this is ugly and not readable then perhaps we should split the controller. 

https://github.com/kubermatic/kubermatic/tree/master/api/pkg/controller/rbac

2018-07-03 10:16 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
As I said, not a huge fan but to stay on topic, is there any reason why we can't have the `sync` act on clusters?

2018-07-03 10:23 UTC, p0lyn0mial commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
not sure why but I assumed that we have more than one source that defines the `addons` to be installed. From what I understand there is only once source the `defaultList`. In that case changing `sync` to act only on clusters makes sense.

2018-07-03 12:42 UTC, glower commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
> If we can't do that I'd suggest to be honest and write a second controller that just ensures defaultAddons are present but doesn't care about their state

This make sense for me. So I will create something like `addon-installer-controller`, and the second one, `addon-controller` can probably stay  as it is now.

2018-07-03 13:04 UTC, glower commented on api/pkg/provider/kubernetes/rbac-compliant-cluster.go
>  	return cluster, wait.Poll(10*time.Millisecond, 30*time.Second, existsInLister)
OK, will put it back :)

2018-07-03 13:09 UTC, glower commented on api/pkg/controller/addon/controller.go
> +			c.enqueueClusterAddons(cluster)
I've seen it like this in cluster controller and found it better this way. We only need to check for `DeletedFinalStateUnknown` in `DeleteFunc` and then call `enqueue`

2018-07-03 13:09 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
I don't think that is necesary, as stated above we can just change the `sync` func to not take a key for an addon but take a key for a cluster, then

* Get all addons from the cluster namespace
* Ensure all addons defined in `defaultAddons` are among them, otherwise create those that are missing
* Execute for all addons `cleanupManifests`/`ensureIsInstall`/`ensureFinalizerIsSet` as approriate

Ping me in Slack if you have questions there

2018-07-03 13:13 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
Then we have to wait up to 5 min if someone decides to delete a addon.
A separate controller sound more reasonable.

2018-07-03 13:13 UTC, mrIncompetent commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
Th 5 minutes come from the force-resync of the cluster-informer

2018-07-03 13:14 UTC, glower commented on api/pkg/controller/addon/controller.go
> +			glog.Infof("Create addon %s for the cluster %s\n", addon, cluster.Name)
Yes, will fix this

2018-07-03 13:17 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
I didn't say we should remove the addon informers ;)

We can just add a middlerware that gets triggered by the addon informers and enqueues the corresponding cluster

2018-07-03 13:20 UTC, glower commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
I will try to write a new controller just to see how it works. Thx a lot for all the commeting. Learned a lot!

2018-07-03 13:35 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
@glower Please do not write a controller just to see how it works, @mrIncompetent and me just discussed this, we don't need a separate controller here, we can just use a `func(addon) { enqueClusterForAddon(addon) }` inside the `addonInformer`

2018-07-03 18:39 UTC, glower commented on api/pkg/controller/addon/controller.go
> +	if cluster.Status.NamespaceName != "" {
@alvaroaleman OK, no problem, I need to read the compleat conversation, somehow I understood the opposite. I will ping you on slack for questions.

2018-07-03 18:54 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/rbac-compliant-cluster.go
>  	return cluster, wait.Poll(10*time.Millisecond, 30*time.Second, existsInLister)
@mrIncompetent I have just created a cluster to test this and the client does GET request but specifies the cluster in the request
`https://dev.kubermatic.io/api/v3/dc/europe-west3-c/cluster/rg4c6t2qdz`  in that case the `rbacCompliantCluster` provider  gets the cluster directly from the API not from the cache.

https://github.com/kubermatic/kubermatic/blob/master/api/pkg/provider/kubernetes/rbac-compliant-cluster.go#L203

@glower I think we can remove `wait.Poll`

2018-07-04 15:50 UTC, glower reviewed
I hope I got everything right this time. Only using one queue for cluster in addon-controller. One thing I'm not liking in this solution is the `sync` method, where if something is wrong with one of the addons, everything will fail. But maybe this is a good thing

2018-07-04 15:50 UTC, glower commented on api/pkg/provider/kubernetes/rbac-compliant-cluster.go
> -	// TODO: Make Addons to be part of the cluster specification
Are this TODOs useful?  Should I put them to somewhere?

2018-07-05 08:07 UTC, alvaroaleman requested changes

2018-07-05 08:07 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	"log"
Please stay consistent and use `glog`

2018-07-05 08:07 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +// If an addonInformer triggers queing, get to the corresponding cluster via an ownerRef and put it into the workqeue
I can not tell you how `queing` is spelled right but I can tell you the current spelling is wrong ;)

2018-07-05 08:07 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +	_, err := c.client.KubermaticV1().Addons(cluster.Status.NamespaceName).Create(&kubermaticv1.Addon{
You can abreviate this:

```

if _, err := c.client.KubermaticV1().Addons(cluster.Status.NamespaceName).Create(&kubermaticv1.Addon{
_stuff
}); err != nil {
 handleError
}
```

2018-07-05 08:07 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +			if addon.DeletionTimestamp != nil {
This does not really make sense: You delete the addon here if it got deleted but you are going to recreate it on the next iteration because it wont be found (L327-329)

2018-07-05 08:07 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +			return fmt.Errorf("failed to get addon %s for cluster %s: %v", defaultAddon, addonFromCache.Spec.Cluster.Name, err)
The point about the return if a single addon fails is a valid one. Ideas about that:

* Use `utilruntime.HandleError`
* Reque the cluster but continue in the current sync loop - Will this cause concurrency issues?

2018-07-05 08:07 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +			if !cluster.Status.Health.Apiserver {
I think this should be in the very beginning of the `sync` func

2018-07-05 08:07 UTC, alvaroaleman commented on api/pkg/controller/addon/controller.go
> +			if err := c.ensureIsInstalled(addon, cluster); err != nil {
I think you basically do the same in line 327-329:

```
		if err != nil && kerrors.IsNotFound(err) {
￼ ￼ 			log.Printf("sync(): defaultAddon %s is not found\n", defaultAddon)
￼			c.createDefaultAddon(defaultAddon, cluster)
}
```

2018-07-05 08:07 UTC, alvaroaleman commented on api/pkg/controller/addon/controller_test.go
> +			controller.processNextItem()
As @p0lyn0mial already noted, please do call the `sync` method in between the steps of your test, e.G. `createTestController(objects)`, `c.Sync(object)`, `checkIfExpectedObjectPresent`

Also please only test on

* States (presense, absence or properties) of the controlling and controlled objects (cluster, addons, respectively)
* The operations being done (e.G. CREATE; UPDATE, DELETE)

There is a very good example here: https://github.com/kubermatic/machine-controller/blob/694cb33243256384a54974b394cb5a636b5e5889/pkg/controller/machine_test.go#L181

2018-07-05 09:59 UTC, glower commented on api/pkg/controller/addon/controller.go
> +			if err := c.ensureIsInstalled(addon, cluster); err != nil {
I think it is different. 327-329 the call to the API is done and the addon resource  is created and here the addon is installed on the cluster. We need to have both checks if I understood it correctly

2018-07-05 10:00 UTC, glower commented on api/pkg/controller/addon/controller.go
> +			if !cluster.Status.Health.Apiserver {
make sense

2018-07-05 11:03 UTC, alvaroaleman commented
So @mrIncompetent and me talked about the topic of workqeues etc again and we settled on having a new controller that ensures the default addons are present as the best solution in terms of complexity and testability.

2018-07-06 09:31 UTC, p0lyn0mial requested changes

2018-07-06 09:31 UTC, p0lyn0mial commented on api/pkg/controller/addoninstaller/controller_test.go
> +			time.Sleep(1 * time.Second)
this is suspicious :(

2018-07-06 09:31 UTC, p0lyn0mial commented on api/pkg/controller/addoninstaller/controller_test.go
> +	kubeInformerFactory.Start(wait.NeverStop)
I'd prefer not to start informers. The example I gave you before demonstrates how you can test the controller without informers. 

In short you can create `addonLister` and `clusterLister` from the `Indexer` and then you can use them to instantiate the controller.

2018-07-06 09:31 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/rbac-compliant-cluster.go
> -	// TODO: Make Addons to be part of the cluster specification
No, it's fine.

2018-07-06 09:31 UTC, p0lyn0mial commented on api/pkg/controller/addoninstaller/controller.go
> +	glog.Infof("Create addon %s for the cluster %s\n", addon, cluster.Name)
this can get quite noisy. I propose to change it to `glog.V(8)` log level ?

2018-07-06 09:31 UTC, p0lyn0mial commented on api/cmd/kubermatic-controller-manager/controllers.go
> +func splitAndTrim(list string) []string {
nit: would be nice if we could inline this function in `startAddonInstallerController` so that the top level functions in this file start with `startXYZController`

2018-07-06 09:39 UTC, alvaroaleman requested changes

2018-07-06 09:39 UTC, alvaroaleman commented on api/pkg/controller/addoninstaller/controller.go
> +	if cluster.Labels[kubermaticv1.WorkerNameLabelKey] != c.workerName {
I think this should be the first thing to do, before checking apiservers health

2018-07-06 09:39 UTC, alvaroaleman commented on api/pkg/controller/addoninstaller/controller.go
> +			c.createDefaultAddon(defaultAddon, cluster)
What do we do if someone changes the addon? I think we should also compare the current spec of the addon if it maches what is inside the `defaultAddon`

2018-07-06 09:39 UTC, alvaroaleman commented on api/pkg/controller/addoninstaller/controller_test.go
> +		log.Fatal(err)
please do not use `log` at all, we use `glog`.

Also if testcases fail, use `*testing.T.Fatalf/Errorf` (which for this case means "newAddonTestController must return an err)

2018-07-06 09:39 UTC, alvaroaleman commented on api/cmd/kubermatic-controller-manager/controllers.go
> +		ctrlCtx.kubeInformerFactory.Core().V1().Secrets(),
What for do you need `Secrets`?

2018-07-06 09:43 UTC, glower commented on api/pkg/controller/addoninstaller/controller_test.go
> +	kubeInformerFactory.Start(wait.NeverStop)
OK, I will rework it. Just copy this test from `cluster-controller`

2018-07-06 09:44 UTC, glower commented on api/pkg/controller/addoninstaller/controller.go
> +	glog.Infof("Create addon %s for the cluster %s\n", addon, cluster.Name)
Make sense, will change this

2018-07-06 09:51 UTC, glower commented on api/cmd/kubermatic-controller-manager/controllers.go
> +func splitAndTrim(list string) []string {
OK, will fix it

2018-07-06 09:53 UTC, glower commented on api/pkg/controller/addoninstaller/controller.go
> +	if cluster.Labels[kubermaticv1.WorkerNameLabelKey] != c.workerName {
make sense

2018-07-06 09:55 UTC, glower commented on api/pkg/controller/addoninstaller/controller_test.go
> +		log.Fatal(err)
fixed

2018-07-06 09:55 UTC, glower commented on api/cmd/kubermatic-controller-manager/controllers.go
> +		ctrlCtx.kubeInformerFactory.Core().V1().Secrets(),
according to @mrIncompetent we need this for syncing

2018-07-06 12:57 UTC, glower commented on api/pkg/controller/addoninstaller/controller_test.go
> +			time.Sleep(1 * time.Second)
I had a problem that without sleep here cache was not in sync with the state :(
Maybe if I use your method with Indexer I dont need it

2018-07-06 17:12 UTC, glower commented on api/pkg/controller/addoninstaller/controller.go
> +			c.createDefaultAddon(defaultAddon, cluster)
I think this is a job of `addon-controller`

2018-07-06 17:32 UTC, glower commented
* Fixed the tests to use indexer, setup is more complicated as with `.Start(wait.NeverStop)` but it anyway :)

2018-07-06 19:59 UTC, alvaroaleman commented on api/cmd/kubermatic-controller-manager/controllers.go
> +		ctrlCtx.kubeInformerFactory.Core().V1().Secrets(),
But its not accessed anywhere in the `adoninstaller` controller except for checking if its synced?

2018-07-06 20:06 UTC, glower commented on api/cmd/kubermatic-controller-manager/controllers.go
> +		ctrlCtx.kubeInformerFactory.Core().V1().Secrets(),
Summon @mrIncompetent: can we remove `Secrets()` sync here and in `addon-controller`

2018-07-09 07:44 UTC, mrIncompetent commented on api/cmd/kubermatic-controller-manager/controllers.go
> +		ctrlCtx.kubeInformerFactory.Core().V1().Secrets(),
Only needed inside the addon-controller. Not the installer.

And only there because the addon-controller gets the cluster-client which depends on it and controllers get started before all informers are synced. Something we need to change in a dedicated PR.

2018-07-09 08:06 UTC, glower commented on api/cmd/kubermatic-controller-manager/controllers.go
> +		ctrlCtx.kubeInformerFactory.Core().V1().Secrets(),
But in the installer same `client kubermaticclientset.Interface` is used as in `addon-controller` for creating an addon

2018-07-09 08:08 UTC, mrIncompetent commented on api/cmd/kubermatic-controller-manager/controllers.go
> +		ctrlCtx.kubeInformerFactory.Core().V1().Secrets(),
Does the installer talks to the user-cluster?
I though it should only create Addon resources? So we do not duplicate the logic

2018-07-09 08:14 UTC, glower commented on api/cmd/kubermatic-controller-manager/controllers.go
> +		ctrlCtx.kubeInformerFactory.Core().V1().Secrets(),
I need kubermatic client to make a call:
```
c.client.KubermaticV1().Addons(cluster.Status.NamespaceName).Create(&kubermaticv1.Addon{
```

2018-07-09 08:15 UTC, mrIncompetent commented on api/cmd/kubermatic-controller-manager/controllers.go
> +		ctrlCtx.kubeInformerFactory.Core().V1().Secrets(),
Sorry for the confusion, i meant a different client: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/cluster/client/client.go

2018-07-09 08:24 UTC, glower commented on api/cmd/kubermatic-controller-manager/controllers.go
> +		ctrlCtx.kubeInformerFactory.Core().V1().Secrets(),
Ah, ok, now I got it, The cluster client is used not direct with `GetAdminKubeconfig` where `Secrets` needs to be there, confusing :)
So I will remove it from installer

2018-07-09 08:54 UTC, glower commented
removed secrets from the addon-installer controller

2018-07-09 10:14 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/cluster.go
> +	return cluster, nil
I think that we need bring `return cluster, wait.Poll(10*time.Millisecond, 30*time.Second, existsInLister)` back as the old API gets the cluster from the cache.

2018-07-09 10:14 UTC, p0lyn0mial commented on api/pkg/controller/addoninstaller/controller.go
> +	addonInformer kubermaticv1informers.AddonInformer,
I would change it to `AddonLister` as this is what we need.

2018-07-09 10:14 UTC, p0lyn0mial commented on api/pkg/controller/addoninstaller/controller.go
> +	ownerRef := *metav1.NewControllerRef(cluster, gv.WithKind("Cluster"))
golang will complain when you move it to line 138 ?

2018-07-09 10:14 UTC, p0lyn0mial commented on api/pkg/controller/addoninstaller/controller.go
> +			c.createDefaultAddon(defaultAddon, cluster)
yeah, the `addon-controller` will ensure that the `addon` is/was installed

2018-07-09 10:14 UTC, p0lyn0mial commented on api/pkg/controller/addoninstaller/controller_test.go
> +			for index, action := range actions {
What do you think about actually checking the `Addon.ObjectMetadata` and `Addon.Spec` ?

2018-07-09 10:31 UTC, glower commented on api/pkg/controller/addoninstaller/controller.go
> +	ownerRef := *metav1.NewControllerRef(cluster, gv.WithKind("Cluster"))
nope, will move this line there

2018-07-09 10:39 UTC, glower commented on api/pkg/controller/addoninstaller/controller.go
> +	addonInformer kubermaticv1informers.AddonInformer,
yes, make sense. Do I need `c.addonSynced` in this case? addons are not installed in this moment, so no need to wait for sync. Is this correct?

2018-07-09 10:49 UTC, p0lyn0mial commented on api/pkg/controller/addoninstaller/controller.go
> +	addonInformer kubermaticv1informers.AddonInformer,
ah, you need both the `Lister` and the `Synced` as the cache will be populated with existing items/addons. So we would have to have two parameters.

I just had a quick look and it seem like all controllers are actually accepting `Informers`. Sorry for the mix up !  

I think it would be better if we stay consistent.

2018-07-09 12:31 UTC, p0lyn0mial commented on api/pkg/controller/addoninstaller/controller_test.go
> +func TestCreateAddon(t *testing.T) {
the test looks really nice :)

2018-07-09 12:32 UTC, p0lyn0mial commented on api/pkg/controller/addoninstaller/controller.go
> +	ownerRef := *metav1.NewControllerRef(cluster, gv.WithKind("Cluster"))
do we want to move this line to L:138 ?

2018-07-09 12:36 UTC, p0lyn0mial commented
this PR look really good, we only need to clean up `kubermatic-api-dep.yaml` file and this is LGTM

@glower thanks for addressing all the comments !

2018-07-09 12:43 UTC, p0lyn0mial commented on config/kubermatic/templates/kubermatic-controller-manager-dep.yaml
> +          - -addons-list={{ join "," .Values.kubermatic.addons.defaultAddons }}
do you mind cleaning up `values.yaml` file - we need to move `kubermatic.addons` to `controller.addons` ?

https://github.com/kubermatic/kubermatic/blob/ec4f65d0afff8cbe3ea41fcf91e01781c9c60dc4/config/kubermatic/values.yaml

2018-07-09 12:45 UTC, p0lyn0mial commented on config/kubermatic/templates/kubermatic-api-dep.yaml
> +      serviceAccountName: kubermatic
nit: remove space at the end.

2018-07-09 12:45 UTC, p0lyn0mial commented on config/kubermatic/templates/kubermatic-controller-manager-dep.yaml
> +          mountPath: /opt/addons
nit: remove space at the end.

2018-07-09 14:28 UTC, p0lyn0mial submitted a review, later dismissed
I'm more than happy that we removed `addon` installation from the API.

@glower many thanks for putting this pull together, it looks really good.

LGTM unless @alvaroaleman @mrIncompetent would like to add something ?

2018-07-09 14:34 UTC, mrIncompetent commented on api/pkg/controller/addoninstaller/controller.go
> +		utilruntime.HandleError(fmt.Errorf("failed to create initial adddon %s for cluster %s: %v", addon, cluster.Name, err))
This function gets called from the sync handler, so we have a cluster context and also have a error handler in place: https://github.com/kubermatic/kubermatic/pull/1431/files#diff-b6caaf6a977e60d21f84c70f79230f29R189

Why not simply return the error?
I think we can directly do a `return err` and enrich the error on https://github.com/kubermatic/kubermatic/pull/1431/files#diff-b6caaf6a977e60d21f84c70f79230f29R240 with the addon name

2018-07-09 14:36 UTC, mrIncompetent commented on api/pkg/controller/addoninstaller/controller.go
> +		glog.V(8).Infof("reconciling: Health.Apiserver of the cluster %s is false", key)
`glog.V(8).Infof("skipping addon sync for cluster %s as the apiserver is not healty yet", key)`

2018-07-09 14:37 UTC, mrIncompetent commented on api/pkg/controller/addoninstaller/controller.go
> +			utilruntime.HandleError(fmt.Errorf("failed to get addon %s for cluster %s: %v", defaultAddon, addonFromCache.Spec.Cluster.Name, err))
Return the error.
As with https://github.com/kubermatic/kubermatic/pull/1431/files#r201024582 we have a error handler in place.


But do not include the cluster name inside the error. I will get added from the error handler

2018-07-09 14:38 UTC, mrIncompetent commented on api/pkg/controller/addoninstaller/controller_test.go
> +	"k8s.io/apimachinery/pkg/runtime"
group alls `k8s.io` imports

2018-07-09 14:48 UTC, p0lyn0mial commented on api/pkg/controller/addoninstaller/controller.go
> +			utilruntime.HandleError(fmt.Errorf("failed to get addon %s for cluster %s: %v", defaultAddon, addonFromCache.Spec.Cluster.Name, err))
we could return an error but what does it give us ? 
perhaps it is better to continue looping and try to install as much `addons` as we can ? Then at the end we could actually return an error indicating that the cluster should be added to the queue.

2018-07-09 14:52 UTC, p0lyn0mial commented
posting here as the file has been changed :)
 
> utilruntime.HandleError(fmt.Errorf("failed to get addon %s for cluster %s: %v", defaultAddon, addonFromCache.Spec.Cluster.Name, err))

mrIncompetent 13 minutes ago
Return the error.
As with https://github.com/kubermatic/kubermatic/pull/1431/files#r201024582 we have a error handler in place.

But do not include the cluster name inside the error. I will get added from the error handler

  @p0lyn0mial
p0lyn0mial 2 minutes ago
we could return an error but what does it give us ?
perhaps it is better to continue looping and try to install as much addons as we can ? Then at the end we could actually return an error indicating that the cluster should be added to the queue.

2018-07-09 14:55 UTC, alvaroaleman commented
@p0lyn0mial That is an intresting discussion, I brought that point up as well. @mrIncompetent argued that all controllers have a sequence of steps that have to be done to get a desired state and all controllers are built in a way that they will return an error if any of those steps fail, which will result in ratelimited requing of that item and proceeding later on - So the equivalent here would be to also return with an err.

I sort of agree, althought it would potentially be nice to emit an event for that (not in this pull). WDYT?

2018-07-09 14:56 UTC, p0lyn0mial commented on api/pkg/controller/addoninstaller/controller_test.go
> +	"k8s.io/apimachinery/pkg/runtime"
this is so common :) 

if only this could be checked by the linter :)

2018-07-09 14:57 UTC, mrIncompetent commented on api/pkg/controller/addoninstaller/controller_test.go
> +	"k8s.io/apimachinery/pkg/runtime"
What else would i be doing the rest of the day? :thinking:

2018-07-09 15:01 UTC, glower commented on api/pkg/controller/addoninstaller/controller.go
> +	ownerRef := *metav1.NewControllerRef(cluster, gv.WithKind("Cluster"))
yes, I forgot it :)

2018-07-09 15:02 UTC, glower commented
I have the feel I will never merge it :)
I fixed the error handling in the creation of the addon
please have a look

2018-07-09 15:02 UTC, glower commented on api/pkg/controller/addoninstaller/controller.go
> +			utilruntime.HandleError(fmt.Errorf("failed to get addon %s for cluster %s: %v", defaultAddon, addonFromCache.Spec.Cluster.Name, err))
done

2018-07-09 15:03 UTC, p0lyn0mial commented
> I sort of agree, although it would potentially be nice to emit an event for that (not in this pull). WDYT?

I see his point, as the chance the next call will actually fail can be quite high. Do you want to measure failed installations ?

2018-07-09 15:03 UTC, p0lyn0mial commented on api/pkg/controller/addoninstaller/controller_test.go
> +	"k8s.io/apimachinery/pkg/runtime"
lol

2018-07-09 15:07 UTC, glower commented on api/pkg/controller/addoninstaller/controller_test.go
> +	"k8s.io/apimachinery/pkg/runtime"
done

2018-07-09 15:18 UTC, mrIncompetent commented
> > I sort of agree, although it would potentially be nice to emit an event for that (not in this pull). WDYT?

> I see his point, as the chance the next call will actually fail can be quite high. Do you want to measure failed installations ?

I would introduce a error metric (Most valuable metric we have): https://github.com/kubermatic/kubermatic/blob/master/api/pkg/controller/cluster/controller.go#L262

But rather do this in a follow up.

2018-07-09 15:21 UTC, p0lyn0mial commented
> I would introduce a error metric (Most valuable metric we have): https://github.com/kubermatic/kubermatic/blob/master/api/pkg/controller/cluster/controller.go#L262
But rather do this in a follow up.

SGTM

2018-07-09 15:26 UTC, mrIncompetent commented on api/pkg/controller/addoninstaller/controller.go
> +			utilruntime.HandleError(fmt.Errorf("failed to get addon %s for cluster %s: %v", defaultAddon, addonFromCache.Spec.Cluster.Name, err))
Why now both?

2018-07-09 15:26 UTC, mrIncompetent commented on api/pkg/controller/addoninstaller/controller.go
> +				utilruntime.HandleError(fmt.Errorf("failed to create initial adddon %s: %v", defaultAddon, err))
Why now both?

2018-07-09 17:17 UTC, glower commented on api/pkg/controller/addoninstaller/controller.go
> +			utilruntime.HandleError(fmt.Errorf("failed to get addon %s for cluster %s: %v", defaultAddon, addonFromCache.Spec.Cluster.Name, err))
fixed

2018-07-09 17:17 UTC, glower commented on api/pkg/controller/addoninstaller/controller.go
> +				utilruntime.HandleError(fmt.Errorf("failed to create initial adddon %s: %v", defaultAddon, err))
fixed

2018-07-09 17:18 UTC, glower commented on api/pkg/controller/addoninstaller/controller_test.go
> +func TestCreateAddon(t *testing.T) {
thx!

2018-07-09 21:25 UTC, alvaroaleman requested changes
Two nits, then we are good to go :)

2018-07-09 21:25 UTC, alvaroaleman commented on api/cmd/kubermatic-controller-manager/main.go
> +	flag.StringVar(&runOp.addonsList, "addons-list", "canal,dashboard,dns,heapster,kube-proxy,openvpn,rbac", "Comma separated list of Addons to install into every user-cluster")
This must also include `kubelet-configmap`, otherwise 1.11 clusters wont work

2018-07-09 21:25 UTC, alvaroaleman commented on api/pkg/controller/addoninstaller/controller.go
> +			Help:      "The number of running addon controller workers",
`addon installer controller workers`

2018-07-09 21:25 UTC, alvaroaleman commented on api/pkg/controller/addoninstaller/controller_test.go
> +				if !equality.Semantic.DeepEqual(createaction.GetObject().(*kubermaticv1.Addon), test.expectedClusterAddons[index]) {
Nice! That one is really cool because it knows e.g. a `nil` and a slice with `len == 0` are semantically equal :)

2018-07-10 06:25 UTC, glower commented on api/pkg/controller/addoninstaller/controller.go
> +			Help:      "The number of running addon controller workers",
fixed

2018-07-10 06:25 UTC, glower commented on api/cmd/kubermatic-controller-manager/main.go
> +	flag.StringVar(&runOp.addonsList, "addons-list", "canal,dashboard,dns,heapster,kube-proxy,openvpn,rbac", "Comma separated list of Addons to install into every user-cluster")
fixed

2018-07-10 06:26 UTC, glower commented on api/pkg/controller/addoninstaller/controller_test.go
> +				if !equality.Semantic.DeepEqual(createaction.GetObject().(*kubermaticv1.Addon), test.expectedClusterAddons[index]) {
Yes, testing with `DeepEqual` is cool

2018-07-10 08:39 UTC, alvaroaleman approved these changes

2018-07-10 08:42 UTC, mrIncompetent approved these changes

2018-07-10 08:55 UTC, p0lyn0mial approved these changes

2018-07-10 08:57 UTC, merged