Add S3 exporter
kubermatic/kubermatic pull request #1482
Opened 2018-07-05 20:54 UTC by alvaroaleman

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1407 

**Special notes for your reviewer**:

**Release note**:
```release-note monitoring
Added an S3 exporter for metrics
```

2018-07-05 20:59 UTC, kron4eg requested changes
is that `api/cmd/s3-exporter/s3-exporter` a compiled binary?

2018-07-05 21:03 UTC, alvaroaleman commented
@kron4eg Yes, `api/cmd/s3-exporter/s3-exporter` is a compiled binary after executing `api/hack/publish-s3-exporter.sh`

2018-07-05 21:07 UTC, kron4eg commented
@alvaroaleman I mean, let's not commit to git compiled executables

2018-07-05 21:18 UTC, alvaroaleman commented
@kron4eg Oups. Fixed

2018-07-06 08:40 UTC, mrIncompetent commented on api/pkg/exporters/s3/exporter.go
> +func MustRun(minioClient *minio.Client, bucket string, listenAddress int) error {
So why return also an error?

2018-07-06 08:43 UTC, mrIncompetent commented on api/cmd/s3-exporter/main.go
> +	stopChannel := make(chan struct{})
what is this channel for?

2018-07-06 08:44 UTC, mrIncompetent commented on api/cmd/s3-exporter/main.go
> +	listenPort := flag.Int("listen-port", 9340, "The port to listen on")
Please adjust to the existing way we define flags:
https://github.com/kubermatic/kubermatic/blob/master/api/cmd/kubermatic-api/main.go#L74

2018-07-06 08:45 UTC, mrIncompetent commented on api/cmd/s3-exporter/main.go
> +		glog.Fatalf(err.Error())
```
glog.Fatal(err)
```
should be enough?

2018-07-06 08:46 UTC, mrIncompetent commented on api/cmd/s3-exporter/README.md
> +```
instruction on building & releasing is missing

2018-07-06 08:49 UTC, mrIncompetent commented on api/hack/publish-s3-exporter.sh
> +export REGISTRY=docker.io/kubermatic/s3-exporter
We are transitioning to quay.io. We should put new images only on quay.

I created docker quay.io/kubermatic/s3-exporter

2018-07-06 08:55 UTC, mrIncompetent commented on api/pkg/exporters/s3/exporter.go
> +		if !exporter.refreshMetrics(w, r) {
I like the idea of refreshing the metrics right before the prom-handler 👍 
Prometheus will alert when this fails

2018-07-06 08:58 UTC, mrIncompetent commented on api/pkg/exporters/s3/exporter.go
> +	prefix := r.URL.Query().Get("prefix")
So we need to have a dedicated scrape config for each cluster?

2018-07-06 09:01 UTC, mrIncompetent commented on api/pkg/exporters/s3/exporter.go
> +	e.ObjectsEmptyCount.With(labels).Set(float64(getEmptyObjectCount(objects)))
Would it be easier if we include the filesize as label on `ObjectsCount` ?

2018-07-06 09:09 UTC, metalmatze commented
Before going any further into the code. How often do we want to scrape the S3 bucket?
It shouldn't be that expensive, right?

So in that case I highly recommend using the collector pattern for this exporter. It has the advantage of all the metrics being stateless, which means that for every time we scrape this exporter it will fetch all the data it needs, return the response and then forget about it again.
This is contrary to what the current approach does which has the prometheus client go state.

Using the collector pattern will improve the situation for objects being deleted. Because it's stateless those old objects won't show up anymore whereas with the current approach they would be still in the internal prometheus client_go cache.

Check the docs:
https://godoc.org/github.com/prometheus/client_golang/prometheus#example-Collector
As an example I can point you to my DigitalOcean exporter: https://github.com/metalmatze/digitalocean_exporter/

2018-07-06 09:41 UTC, alvaroaleman commented on api/cmd/s3-exporter/main.go
> +	stopChannel := make(chan struct{})
Block termination until a SIG is send to the process

2018-07-06 09:42 UTC, alvaroaleman commented on api/pkg/exporters/s3/exporter.go
> +	prefix := r.URL.Query().Get("prefix")
Yes, I actually thought some time about this but I couldn't come up with a better way. Only alternative would be to create an exporter per cluster, but thats IMHO worse

2018-07-06 09:43 UTC, alvaroaleman commented on api/pkg/exporters/s3/exporter.go
> +	e.ObjectsEmptyCount.With(labels).Set(float64(getEmptyObjectCount(objects)))
The filesize of what? The biggest file? the smallest? The average? The std derivation from the avg? :)

2018-07-06 09:44 UTC, alvaroaleman commented
> So in that case I highly recommend using the collector pattern for this exporter. It has the advantage of all the metrics being stateless, which means that for every time we scrape this exporter it will fetch all the data it needs, return the response and then forget about it again.

Makes sense. The exporter already scrapes synchronously but sounds like there are better approaches to implement that behavior than the current one.

2018-07-06 10:13 UTC, alvaroaleman commented
@metalmatze So the only difference I see is that in the example you pointed me at, every metric is a `Collector` which collects metrics via `Collect()` - However that means there is one api call per metric, so basically we would here have three apicalls for the exact same data.

Do I understand that correctly? If yes, I would prefer to keep it the way it is.

2018-07-06 10:47 UTC, metalmatze commented
In the example I just separated the metrics by domain and I need to do separate calls there anyway. I think with this exporter you can easily do all within one collector and then do one API call. Or do I miss something?

2018-07-06 10:48 UTC, alvaroaleman commented
So after talking with @mrIncompetent we decided that if we write an s3 exporter anyways, we can as well put some more business logic into it.

To not require a scrape config per cluster, I will change the exporter to fetch all available clusters and then return metrics for all clusters and not take the `prefix` argument anymore

2018-07-06 15:30 UTC, alvaroaleman commented
@mrIncompetent @metalmatze I think all your comments were addressed, PTAL

2018-07-09 08:04 UTC, mrIncompetent commented on api/cmd/s3-exporter/README.md
> +s3_empty_object_count{prefix="q8z2hgk94f"} 1
Do we need to stick with `prefix`? Why not using `cluster`?

2018-07-09 10:35 UTC, alvaroaleman commented
@mrIncompetent readme still contained outdated list of available metrics, I fixed that

2018-07-09 11:03 UTC, mrIncompetent commented on api/cmd/s3-exporter/main.go
> +	listenPort := flag.Int("listen-port", 9340, "The port to listen on")
Not fixed yet

2018-07-09 11:16 UTC, alvaroaleman commented on api/cmd/s3-exporter/README.md
> +```
Done

2018-07-09 14:04 UTC, mrIncompetent approved these changes

2018-07-09 14:08 UTC, kron4eg approved these changes

2018-07-09 14:12 UTC, merged