Use etcd client cert auth
kubermatic/kubermatic pull request #1496
Opened 2018-07-07 15:43 UTC by mrIncompetent

**What this PR does / why we need it**:
Enables client cert authentication on etcd.

Whats missing:
- [x] Client cert for backup handling

Fixes #1436

**Release note**:
```release-note
Communication between apiserver and etcd is now encrypted
```

2018-07-07 19:09 UTC, alvaroaleman requested changes

2018-07-07 19:09 UTC, alvaroaleman commented on api/pkg/resources/apiserver/etcd-client-certificate.go
> +func EtcdClientCertificate(data *resources.TemplateData, existing *corev1.Secret) (*corev1.Secret, error) {
I think this rather belongs into the `pkg/ressources/etcd` package, especially since the backup job needs it as well

2018-07-07 19:09 UTC, alvaroaleman commented on api/pkg/resources/apiserver/etcd-client-certificate.go
> +func EtcdClientCertificate(data *resources.TemplateData, existing *corev1.Secret) (*corev1.Secret, error) {
Or maybe: Have a func for this in `pkg/ressources/etcd` that takes the desired names/OUs as argument

2018-07-07 19:09 UTC, alvaroaleman commented on api/pkg/resources/apiserver/etcd-client-certificate.go
> +			return nil, fmt.Errorf("faield to certificate (key=%s) from existing secret %s: %v", resources.ApiserverEtcdClientCertificateCertSecretKey, resources.ApiserverEtcdClientCertificateSecretName, err)
typo

2018-07-07 19:09 UTC, alvaroaleman commented on api/pkg/resources/apiserver/etcd-client-certificate.go
> +
Expiration check is missing

2018-07-09 14:03 UTC, alvaroaleman commented
This is also still missing a migration

2018-07-09 14:27 UTC, mrIncompetent commented
Just added the secret revisions to the pod labels.
No migration needed. We might see a downtime of the Apiserver's for the time the etcd gets updated.

2018-07-10 08:38 UTC, alvaroaleman approved these changes

2018-07-10 08:48 UTC, merged