Added new openstack route for subnetwork ids
kubermatic/kubermatic pull request #1516
Opened 2018-07-11 09:19 UTC by glower

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1450

**Special notes for your reviewer**:

2018-07-11 09:49 UTC, p0lyn0mial requested changes

2018-07-11 09:49 UTC, p0lyn0mial commented on api/pkg/provider/cloud/openstack/helper.go
> +type SubnetID struct {
Could we rename it to `Subnet` ? In the future we might want to add more fields that would describe a `subnet` as a resource.

2018-07-11 09:49 UTC, p0lyn0mial commented on api/pkg/provider/cloud/openstack/openstack_test.go
> +	th.SetupHTTP()
I'd like to use the standard library (golang) to test the API. 

for example:
https://github.com/kubermatic/kubermatic/blob/master/api/pkg/handler/datacenter_test.go#L11

Could you update the tests ?

2018-07-11 09:49 UTC, p0lyn0mial commented on api/pkg/handler/routes_v1.go
> +// Lists networks from openstack
this endpoint lists subnets not networks

2018-07-11 09:49 UTC, p0lyn0mial commented on api/pkg/provider/cloud/openstack/helper.go
> +func (os *Provider) GetSubnetIDs(cloud *kubermaticv1.CloudSpec) ([]SubnetID, error) {
@kgroschoff in her previous pull already cleaned up the openstack provider interface. Before, the methods returned `api` objects, for example: `(apiv1.Networks, error)`

Would you be up for continuing the refactoring ? In general the openstack provider doesn't have to accept `CloudSpec` instead it could accept `dc, userName, password ...`.

2018-07-11 09:52 UTC, glower commented on api/pkg/provider/cloud/openstack/helper.go
> +type SubnetID struct {
np

2018-07-11 09:52 UTC, glower commented on api/pkg/provider/cloud/openstack/openstack_test.go
> +	th.SetupHTTP()
yes, np

2018-07-11 12:12 UTC, glower commented on api/pkg/provider/cloud/openstack/helper.go
> +func (os *Provider) GetSubnetIDs(cloud *kubermaticv1.CloudSpec) ([]SubnetID, error) {
Yes, I will love to do this :)

2018-07-12 10:57 UTC, glower commented
I changed call of the methods to have the Openstack client as input, it give me a possibility to inject the client for the tests. Hope it is OK. If this PR is ok, I can write some tests for our handler

2018-07-12 11:25 UTC, p0lyn0mial requested changes

2018-07-12 11:25 UTC, p0lyn0mial commented on api/pkg/handler/openstack.go
> +func openstackSubnetIDsEndpoint(providers provider.CloudRegistry) endpoint.Endpoint {
Although the tests you provided look really impressive they test `openstack.Client`. 

I think that it would be better for us to test our own API. By testing our own API we know that the `path` is correct, we know that the `input` parameters are correct we know that the `output` is not only correct but also properly encoded.   


So I wanted to test the new endpoint we introduce in this PR 

```
func openstackSubnetIDsEndpoint(providers provider.CloudRegistry) endpoint.Endpoint {
		osProviderInterface, ok := providers[provider.OpenstackCloudProvider]
```

Perhaps the easiest way to do this would be to utilize `createTestEndpoint` method ( all the other tests we have use this method) and provide fake implementation of `providers[provider.OpenstackCloudProvider]` - although this part may be tricky because no-one has ever done it, so it may require a small refactoring.

2018-07-12 11:25 UTC, p0lyn0mial commented on api/pkg/api/v1/types.go
> +type OpenstackSubnetID struct {
Can we rename this structure to `OpenstackSubnet` ?

2018-07-12 11:31 UTC, glower commented on api/pkg/handler/openstack.go
> +func openstackSubnetIDsEndpoint(providers provider.CloudRegistry) endpoint.Endpoint {
Yes, make sense, I think I have an idea how to do this

2018-07-12 12:41 UTC, p0lyn0mial commented on api/pkg/handler/openstack.go
> +func openstackSubnetIDsEndpoint(providers provider.CloudRegistry) endpoint.Endpoint {
@glower here is an example: https://github.com/kubermatic/kubermatic/pull/1517/files#diff-e79d4a87b4c18cf2dcd95ba9b4f2dc26R45

the approach only differs in the way we stub/mock the cloud provider.

2018-07-13 07:25 UTC, glower commented
I did a small refactoring of the code and added tests for our /openstack/* routes 
was a bit tricky to mock out openstack API but now we have a small "framework" to mock any calls to Openstack API

2018-07-13 08:09 UTC, p0lyn0mial requested changes

2018-07-13 08:09 UTC, p0lyn0mial commented on api/pkg/handler/openstack_test.go
> +			SetupOpenstackServer(t, tc.OpenstackURL, tc.OpenstackResponse)
we are starting a new http server on each integration, how confident we are that the listening address of the server will not change ?

2018-07-13 08:09 UTC, p0lyn0mial commented on api/pkg/handler/openstack_test.go
> +			ep, err := createTestEndpointForDC(getUser(testUsername, false), buildOpenstackDatacenterMeta(), []runtime.Object{}, []runtime.Object{}, nil, nil)
we could use `createTestEndpointAndGetClients` and ignore some return parameters ?

2018-07-13 08:09 UTC, p0lyn0mial commented on api/pkg/handler/routing_test.go
> +func compareJSON(t *testing.T, res *httptest.ResponseRecorder, s2 string) {
could we change `s2` to `expectedResponseString` ?

2018-07-13 08:09 UTC, p0lyn0mial commented on api/pkg/handler/routing_test.go
> +	var o1 interface{}
could we rename `o1` to `actualResponse` ?

2018-07-13 08:09 UTC, p0lyn0mial commented on api/pkg/handler/routing_test.go
> +	var o2 interface{}
could we rename `o2` to `expectedResponse` ?

2018-07-13 08:09 UTC, p0lyn0mial commented on api/pkg/handler/routing_test.go
> +	if !equality.Semantic.DeepEqual(o1, o2) {
nice use of `DeepEqual` :)

2018-07-13 08:09 UTC, p0lyn0mial commented on api/pkg/handler/openstack_test.go
> +			ExpectedResponse:  ExpectedSubnets,
could we inline expected responses in general ?

2018-07-13 08:09 UTC, p0lyn0mial commented on api/pkg/provider/cloud/openstack/provider.go
> +func (os *Provider) ServiceClient(user, pass, domain, datacenterName string) (*gophercloud.ServiceClient, error) {
shouldn't this be considered as something that is internal to the openstack provider ?

I think that our API is interested in having a conversation with openstack provider not `ServcieClient`.

2018-07-13 08:12 UTC, glower commented on api/pkg/handler/openstack_test.go
> +			SetupOpenstackServer(t, tc.OpenstackURL, tc.OpenstackResponse)
I think I can change it to have one Openstack http server for all needed routes, it is not a big change

2018-07-13 08:15 UTC, glower commented on api/pkg/handler/openstack_test.go
> +			ExpectedResponse:  ExpectedSubnets,
They are not big, so yes, I can do this

2018-07-13 08:23 UTC, glower commented on api/pkg/handler/routing_test.go
> +func compareJSON(t *testing.T, res *httptest.ResponseRecorder, s2 string) {
done

2018-07-13 08:23 UTC, glower commented on api/pkg/handler/routing_test.go
> +	var o1 interface{}
done

2018-07-13 08:23 UTC, glower commented on api/pkg/handler/routing_test.go
> +	var o2 interface{}
done

2018-07-13 08:53 UTC, p0lyn0mial commented on api/pkg/handler/openstack_test.go
> +			SetupOpenstackServer(t, tc.OpenstackURL, tc.OpenstackResponse)
that would be great !

2018-07-13 08:53 UTC, p0lyn0mial commented on api/pkg/handler/routing_test.go
> +	var o2 interface{}
thx

2018-07-13 08:54 UTC, glower commented on api/pkg/handler/openstack_test.go
> +			ExpectedResponse:  ExpectedSubnets,
done

2018-07-13 09:07 UTC, glower commented on api/pkg/handler/openstack_test.go
> +			ep, err := createTestEndpointForDC(getUser(testUsername, false), buildOpenstackDatacenterMeta(), []runtime.Object{}, []runtime.Object{}, nil, nil)
yes, done

2018-07-13 14:21 UTC, closed without merging