Feature/1388 list v sphere networks
kubermatic/kubermatic pull request #1517
Opened 2018-07-11 10:11 UTC by pkavajin

**What this PR does / why we need it**:
Adds a endpoint for listing vsphere networks of a datacenter

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1388 

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

2018-07-11 10:45 UTC, p0lyn0mial requested changes

2018-07-11 10:45 UTC, p0lyn0mial commented on api/pkg/api/v1/types.go
> +type VSphereNetwork struct {
It seems like when working with `OpenStack` we need also an `ID` to uniquely identify the network.
See: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/api/v1/types.go#L232

The `ID` is not required for `VSphere` ?

2018-07-11 10:45 UTC, p0lyn0mial commented on api/pkg/provider/cloud/vsphere/provider.go
> +func (v *Provider) GetNetworks(spec *kubermaticv1.CloudSpec) ([]apiv1.VSphereNetwork, error) {
please don't return `apiv1` objects from the `VSphere` provider - it would be great if you could also change  existing methods.

see: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/handler/openstack.go#L106

To be honest there is no good reason for `VSphere` provider to know about `kubermaticv1.CloudSpec`. Not sure how much time do you have but it would be nice if we could change this as well.

2018-07-11 10:45 UTC, p0lyn0mial commented on api/pkg/handler/vsphere.go
> +func vsphereNetworksEndpoint(providers provider.CloudRegistry) endpoint.Endpoint {
Please add a unit test, happy-path is good enough so that we test encoding, decoding, paths and the output.

2018-07-11 11:00 UTC, p0lyn0mial requested changes

2018-07-11 11:00 UTC, p0lyn0mial commented on api/pkg/handler/vsphere.go
> +	"github.com/go-kit/kit/endpoint"
we group imports, see: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/handler/cluster_test.go#L3

2018-07-11 11:00 UTC, p0lyn0mial commented on api/pkg/api/v1/types.go
> +type AvailableMasterVersions []MasterVersion
why did you add this type ?

2018-07-11 11:18 UTC, pkavajin commented on api/pkg/api/v1/types.go
> +type AvailableMasterVersions []MasterVersion
Wtf, sorry, merge fail, gonna get rid of it.

2018-07-11 11:29 UTC, pkavajin commented on api/pkg/api/v1/types.go
> +type VSphereNetwork struct {
vsphere uses some uuid in internal stuff, everything external works using name/path, so name should be fine as identifier for us (also, current vsphere network related voodoo uses name as well)

2018-07-11 13:05 UTC, p0lyn0mial commented on api/pkg/handler/vsphere.go
> +func vsphereNetworksEndpoint(providers provider.CloudRegistry) endpoint.Endpoint {
it looks like @kgroschoff and @glower will add some unit test as well. Perhaps you can work together since it looks like no-one has ever written a unit test for a cloud provider.

https://github.com/kubermatic/kubermatic/pull/1516
https://github.com/kubermatic/kubermatic/pull/1512

2018-07-11 14:12 UTC, p0lyn0mial commented on api/pkg/provider/cloud/vsphere/provider.go
> +	ctx, cancel := context.WithCancel(context.Background())
move it before `131` and pass `ctx` to `finder.Datacenter`

2018-07-11 14:12 UTC, p0lyn0mial commented on api/pkg/provider/cloud/vsphere/provider.go
> +		netBacking, ok := backing.(*types.VirtualEthernetCardNetworkBackingInfo)
I think that `backing` object implements the following interface

```
type BaseVirtualDeviceBackingInfo interface {
   GetVirtualDeviceBackingInfo() *VirtualDeviceBackingInfo
 }
```

it is not possible to get `DeviceName` from `VirtualDeviceBackingInfo` ?

2018-07-11 14:12 UTC, p0lyn0mial commented on api/pkg/provider/cloud/vsphere/provider.go
> +	netRefs, err := finder.NetworkList(ctx, "*")
we don't have to narrow down the search path ? 
I noticed that some calls use the `rootPath` (`getVsphereRootPath`)

2018-07-12 11:08 UTC, pkavajin commented on api/pkg/provider/cloud/vsphere/provider.go
> +func (v *Provider) GetNetworks(spec *kubermaticv1.CloudSpec) ([]apiv1.VSphereNetwork, error) {
-> as discussed, apiv1 object is changed, kubermaticv1.* would affect all providers + interface, should be an dedicated issue

2018-07-12 11:13 UTC, pkavajin commented on api/pkg/provider/cloud/vsphere/provider.go
> +	netRefs, err := finder.NetworkList(ctx, "*")
thats the root path under which folders should be created for vms, networks are independent from that hierarchy

2018-07-12 11:16 UTC, pkavajin commented on api/pkg/provider/cloud/vsphere/provider.go
> +		netBacking, ok := backing.(*types.VirtualEthernetCardNetworkBackingInfo)
Without explicitly casting? Dont think so, its not part of the interface.

2018-07-12 11:42 UTC, p0lyn0mial commented on api/cmd/kubermatic-api/swagger.json
> +    "AvailableMasterVersions": {
I think that you need to regenerate the swagger spec.

2018-07-12 11:42 UTC, p0lyn0mial commented on api/pkg/handler/vsphere_test.go
> +	compareWithResult(t, res, `[{"name":"VM Network"}]`)
was the response prepared by the `vSpehereMock` ?

is there a way to change/manipulate `vSphereMock` responses ?

2018-07-12 11:42 UTC, p0lyn0mial commented on api/pkg/provider/cloud/vsphere/provider.go
> +			continue
should we log the error message ?

2018-07-12 11:44 UTC, p0lyn0mial commented on api/pkg/handler/routing_test.go
> +		"moon-1": {
why did you add this ?

2018-07-12 11:45 UTC, pkavajin commented on api/pkg/provider/cloud/vsphere/provider.go
> +			continue
dont think so, since else we ll log errors on each api call, because its not "a real" error but a sucky way to filter out distrubuted ports and other virtual net interfaces

2018-07-12 11:46 UTC, pkavajin commented on api/pkg/handler/vsphere_test.go
> +	compareWithResult(t, res, `[{"name":"VM Network"}]`)
its part of the model which tearUp() initializes, .ESX creates a default model with dummy data which contains this network

2018-07-12 11:46 UTC, pkavajin commented on api/cmd/kubermatic-api/swagger.json
> +    "AvailableMasterVersions": {
aw youre absolutly right, my fail

2018-07-12 11:47 UTC, pkavajin commented on api/pkg/handler/routing_test.go
> +		"moon-1": {
Because we need a vsphere datacenter pointing to the local mock server for testing.
(To go a bit more into detail: we setup our endpoints using createTestEndpoint which gets seeded by this data, by having a genuine vsphere entry we dont have to implement any abstractions for injecting a mocked backend)

2018-07-12 11:49 UTC, p0lyn0mial commented on api/pkg/handler/vsphere_test.go
> +	compareWithResult(t, res, `[{"name":"VM Network"}]`)
is there a way to change this model ? for example add some data ? I'm just curious.

2018-07-12 11:57 UTC, pkavajin commented on api/pkg/handler/vsphere_test.go
> +	compareWithResult(t, res, `[{"name":"VM Network"}]`)
Absolutly, the simulator is the cool part of the api, giving you CRUD actions and function hooks for almost all resource types, see https://github.com/vmware/govmomi/tree/master/simulator

2018-07-12 12:00 UTC, p0lyn0mial commented on api/pkg/handler/routing_test.go
> +		"moon-1": {
sgtm.

2018-07-12 12:01 UTC, p0lyn0mial commented on api/pkg/handler/vsphere_test.go
> +	compareWithResult(t, res, `[{"name":"VM Network"}]`)
nice, if there is a need then we could add/modify/remove data from the simulator.

2018-07-12 12:02 UTC, p0lyn0mial commented on api/pkg/provider/cloud/vsphere/provider.go
> +		netBacking, ok := backing.(*types.VirtualEthernetCardNetworkBackingInfo)
yes, okay.

2018-07-12 12:07 UTC, p0lyn0mial approved these changes
this LGTM but I think that we need to get LGTM form other code owners.

2018-07-12 13:15 UTC, mrIncompetent approved these changes

2018-07-12 14:12 UTC, alvaroaleman approved these changes

2018-07-12 14:12 UTC, alvaroaleman commented on api/pkg/handler/request.go
> +func decodeVSphereNetworksReq(c context.Context, r *http.Request) (interface{}, error) {
Why does this return an interface instead of a `*http.Request`?

2018-07-12 14:12 UTC, alvaroaleman commented on api/pkg/handler/request.go
> +func decodeVSphereNetworksReq(c context.Context, r *http.Request) (interface{}, error) {
Nvm, found it myself

2018-07-12 15:36 UTC, merged