feature/load testing script
kubermatic/kubermatic pull request #155
Opened 2016-12-21 11:25 UTC by lbb

Resolves #154

2016-12-28 11:13 UTC, scruplelesswizard requested changes

2016-12-28 11:13 UTC, scruplelesswizard commented on cmd/test-kubermatic-load/main.go
> +	maxNodesFlag    = flag.Int("nodes", 0, "Spcifies the amount of nodes to create in one cluster (nodes*clusters)")
Typo

2016-12-28 11:13 UTC, scruplelesswizard commented on cmd/test-kubermatic-load/main.go
> +	maxClustersFlag = flag.Int("clusters", 0, "Spcifies the amount of clusters to deploy")
Typo

2016-12-28 11:13 UTC, scruplelesswizard commented on cmd/test-kubermatic-load/main.go
> +	dcFlag          = flag.String("datacenter", "master", "use this to specify a datacenter")
Capitalization

2016-12-28 11:13 UTC, scruplelesswizard commented on cmd/test-kubermatic-load/main.go
> +	maxAsyncFlag    = flag.Int("max-async", 10, "Spcifies the amount of request running at the same time")
Typo and Pluralization

2016-12-28 11:13 UTC, scruplelesswizard commented on cmd/test-kubermatic-load/main.go
> +		time.Sleep(time.Second * 10)
Make this configurable

2016-12-28 11:13 UTC, scruplelesswizard commented on cmd/test-kubermatic-load/main.go
> +		log.Printf("Wrong usage usage.\n\n\t %s [up|purge]\n\n", os.Args[0])
Typo

2017-01-04 22:25 UTC, scruplelesswizard requested changes
Please clarify the param descriptions as required

2017-01-04 22:25 UTC, scruplelesswizard commented on cmd/test-kubermatic-load/main.go
> +	maxNodesFlag        = flag.Int("node-count", 0, "The amount of nodes to create in one cluster (node-count*cluster-count)")
`"The number of nodes to create per cluster"`

2017-01-04 22:25 UTC, scruplelesswizard commented on cmd/test-kubermatic-load/main.go
> +	maxClustersFlag     = flag.Int("cluster-count", 0, "The amount of clusters to deploy")
`"The number of clusters to create"`

2017-01-04 22:25 UTC, scruplelesswizard commented on cmd/test-kubermatic-load/main.go
> +	maxAsyncFlag        = flag.Int("max-workers", 10, "The amount of request running at the same time")
`"Maximum concurrent requests"`

2017-01-04 22:25 UTC, scruplelesswizard commented on cmd/test-kubermatic-load/main.go
> +	retryNSIntervalFlag = flag.Int64("ns-retry-interval", 10, "The amout of time until a NS alive request is send again")
`"Duration in seconds to wait between {I really have no idea what we are waiting between}"`

2017-01-04 22:25 UTC, scruplelesswizard commented on cmd/test-kubermatic-load/main.go
> +// setAuth sets the jwt token int a requests Authorization header field
/int/in/

2017-01-05 12:13 UTC, scruplelesswizard commented
We are still missing usage instructions. This will not be merged until we have some docs on how to use it.

2017-01-12 05:37 UTC, scruplelesswizard approved these changes

2017-01-12 08:47 UTC, mrIncompetent approved these changes

2017-01-12 10:00 UTC, merged