Added new openstack route for subnetwork ids
kubermatic/kubermatic pull request #1550
Opened 2018-07-13 14:18 UTC by glower

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1450

**Special notes for your reviewer**:
* Added tests for all /openstack/* routes for our API

**Release note**:
```release-note
NONE
```

2018-07-13 19:22 UTC, alvaroaleman requested changes

2018-07-13 19:22 UTC, alvaroaleman commented on api/pkg/handler/openstack.go
> +		subnets, err := osProvider.GetSubnets(&kubermaticv1.CloudSpec{
While it is obviously possible to just query _all_ subnets it does _imho_ not make sense, because a subnet always belongs to a network. A user should only be allowed to chose a subnet that is inside the network that was chosen already so IMHO this endpoint should have a required `network` parameter.

WDYT?

2018-07-13 19:22 UTC, alvaroaleman commented on api/pkg/handler/openstack.go
> +				Domain:   req.Domain,
This should also contain the `Tenant` field, otherwise the user can only get subnets from his or her `defaultTenant` which may or may not be desired.

2018-07-16 07:14 UTC, glower commented on api/pkg/handler/openstack.go
> +				Domain:   req.Domain,
I will add this to the call and to the request

2018-07-16 07:25 UTC, glower commented on api/pkg/handler/openstack.go
> +		subnets, err := osProvider.GetSubnets(&kubermaticv1.CloudSpec{
So you mean we need an additional filter parameter `network_id` for the call: 
```
allPages, err := ossubnets.List(netClient, {NetworkID: id}).AllPages()
```

2018-07-16 07:56 UTC, p0lyn0mial commented on api/pkg/handler/openstack.go
> +		subnets, err := osProvider.GetSubnets(&kubermaticv1.CloudSpec{
If this sets `network_id` query parameter then yes. 

See also: https://developer.openstack.org/api-ref/network/v2/#list-subnets

2018-07-16 08:04 UTC, p0lyn0mial commented on api/pkg/handler/openstack.go
> +				Domain:   req.Domain,
Good point, and perhaps you can get a list of subnets for more than one tenant if you authenticate as a admin ?

I'll make sure that the other endpoints we have filter by `tenant_id`.

2018-07-16 08:13 UTC, p0lyn0mial commented on api/pkg/api/v1/types.go
> +// OpenstackSubnet is the object representing a openstack subnet id.
change `subnet id` to `subnets` ?

2018-07-16 08:17 UTC, p0lyn0mial commented on api/pkg/provider/cloud/openstack/provider.go
> +func (os *Provider) GetSubnets(cloud *kubermaticv1.CloudSpec) ([]Subnet, error) {
we could just return `[]ossubnets.Subnet, error`, WDYT ?

2018-07-16 09:37 UTC, glower commented on api/pkg/handler/openstack.go
> +		subnets, err := osProvider.GetSubnets(&kubermaticv1.CloudSpec{
Yes, it is. Should I add `network_id` as a url param, `/openstack/subnets?network_id={id}`?

2018-07-16 09:37 UTC, glower commented on api/pkg/provider/cloud/openstack/provider.go
> +func (os *Provider) GetSubnets(cloud *kubermaticv1.CloudSpec) ([]Subnet, error) {
Yes, make sense, will rework it

2018-07-16 09:46 UTC, p0lyn0mial commented on api/pkg/handler/openstack.go
> +		subnets, err := osProvider.GetSubnets(&kubermaticv1.CloudSpec{
sgtm

2018-07-16 12:32 UTC, glower commented
* Updated all OS calls to have TenatID in the request
* Added network_id param to the /subnets call
* Added tests for the query params

2018-07-16 12:38 UTC, glower commented on api/pkg/handler/openstack.go
> +				Domain:   req.Domain,
fixed

2018-07-16 12:38 UTC, glower commented on api/pkg/handler/openstack.go
> +		subnets, err := osProvider.GetSubnets(&kubermaticv1.CloudSpec{
done

2018-07-16 13:12 UTC, glower commented
* Fixed some tests

next step is to refactor our test suit for the handler, because:
```
func createTestEndpointAndGetClients(user apiv1.User, dc map[string]provider.DatacenterMeta, kubeObjects, machineObjects, kubermaticObjects []runtime.Object, versions []*version.MasterVersion, updates []*version.MasterUpdate) (http.Handler, *kubermaticfakeclentset.Clientset, error) {
```

and to call it with
```
	router, _, err := createTestEndpointAndGetClients(user, nil, kubeObjects, nil, kubermaticObjects, versions, updates)
```
is not very sophisticated :)

2018-07-16 16:21 UTC, alvaroaleman requested changes

2018-07-16 16:21 UTC, alvaroaleman commented on api/pkg/handler/request.go
> +// OpenstackReq represent a request for openstack tenants and networks
This does not make sense, because:

When you are requesting the tenants you must not pass in a tenant, because that is what the request is about

In contrast to that, all other requests must have a tenant in them, so they must be seperate

Also IIRC isn't there e.G. a network endpoint for OS as well? I think all of those endpoints should have distinct types or am I missing something?

2018-07-16 16:21 UTC, alvaroaleman commented on api/pkg/handler/request.go
> +	if req.NetworkID == "" {
I am not quite sure here as well, IMHO this should be a `networkID` OR a `networkName` - IIRC the gophercloud bindings have a func that takes something like `nameOrId string` as param

2018-07-16 19:00 UTC, alvaroaleman commented on api/pkg/handler/request.go
> +	if req.NetworkID == "" {
NVM ignore this comment, the API requires it to be the ID

2018-07-16 20:46 UTC, glower commented on api/pkg/handler/request.go
> +// OpenstackReq represent a request for openstack tenants and networks
I see here two possibilities:
* We can implement a separate request object and decode method for each call we have. Even if we have code duplication, it would be consequent and clear.
* We can have 2 different request methods: with and without tenant (we always need user, pass, domain and data centre name).

WDYT?

2018-07-17 08:35 UTC, alvaroaleman commented on api/pkg/handler/request.go
> +// OpenstackReq represent a request for openstack tenants and networks
Ah. Actually I realized after writing this comment that we can just leave the `tenant` field empty for the `tenantRequest` and it should work fine so that means it is fine the way it is :)

2018-07-17 11:26 UTC, alvaroaleman requested changes

2018-07-17 11:26 UTC, alvaroaleman commented on api/pkg/provider/cloud/openstack/helper.go
> +func getSubnetByID(netClient *gophercloud.ServiceClient, networkID string) ([]ossubnets.Subnet, error) {
Please rename to `getSubnetForNetwork`, otherwise pull LGTM

2018-07-17 11:35 UTC, glower commented on api/pkg/provider/cloud/openstack/helper.go
> +func getSubnetByID(netClient *gophercloud.ServiceClient, networkID string) ([]ossubnets.Subnet, error) {
done

2018-07-17 11:37 UTC, alvaroaleman approved these changes

2018-07-17 11:49 UTC, p0lyn0mial approved these changes

2018-07-17 11:53 UTC, mrIncompetent approved these changes

2018-07-17 11:54 UTC, merged