Added bash script for auto-generating changelog and tagging new kubermatic releases
kubermatic/kubermatic pull request #1601
Opened 2018-07-20 16:00 UTC by cbrgm

**What this PR does / why we need it**:
Added bash script for auto-generating changelog and tagging new kubermatic releases.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1400

**Special notes for your reviewer**:

Requirements:
- `gchl` installed
- exported Github personal access token (GCHL_GITHUB_TOKEN)

The script does the following:
```
> Generate a changelog using gchl tool between HEAD and last tagged kubermatic release
> Append changes to existing CHANGELOG.md
> Commit new CHANGELOG.md
> Tag the created commit as a new kubermatic release
```

Usage: 
Execute the script in kubermatic root directory ./api/hack/changelog-gen.sh

```
# Create a changelog since last release, commit and create a new release tag
#
# Usage:
# changelog-gen.sh v2.x.x - create changelog, commit and tag new release, using closed PRs release-note
# changelog-gen.sh v2.x.x github-title - create changelog, commit and tag new release, using closed Githubs PRs title
```
P.S: https://github.com/kubermatic/gchl/pull/1 needs to be merged in order to auto execute `go get `  correctly if `gchl` is not installed.

I also increased the robustness of `gchl` using closed PRs `release-note` field. Now it can deal with all permutation of the word `NONE` e.g. `none`, `None`, `NoNe` and so on.

**Release note**:
```release-note
NONE
```

2018-07-24 08:09 UTC, mrIncompetent commented
@alvaroaleman Can you take care here?

2018-07-24 08:16 UTC, alvaroaleman commented
Will do

2018-07-26 08:40 UTC, alvaroaleman requested changes
So I've tried executing this but it fails, even thought the commit in question definitely is in my branch:

```
$ ./api/hack/changelog-gen.sh v2.10.0
2018/07/26 10:38:48 Failed to find tag or branch name: v2.6.3-110-gd0abea3c
```

Any idea what the reason could be?

2018-07-26 08:40 UTC, alvaroaleman commented on api/hack/changelog-gen.sh
> +#!/bin/bash
This script must be executable (`chmod +x`)

2018-07-26 08:40 UTC, alvaroaleman commented on api/hack/changelog-gen.sh
> +	go get -v https://github.com/kubermatic/gchl
This will fail, go get must not be used in conjunction with a protocol prefix

2018-07-26 08:40 UTC, alvaroaleman commented on api/hack/changelog-gen.sh
> +	echo "Add release-notes flag to use closed PRs `release-notes` annotation content instead of PR title [example: changelog-gen.sh v2.x.x release-notes]"
You can not use backticks here, as this will result in the shell trying to execute the command `release-notes`

2018-07-26 08:40 UTC, alvaroaleman commented on api/hack/changelog-gen.sh
> +	OUTPUT="$(gchl --for-version $1 since $(git tag -l | tail -n 1) $2)"; if [ $? -eq 1 ]; then exit 1; fi
It would be more helpful if this would use the second latest tag on the current branch, not the latest tag overall, e.G. via `git describe --tags $(git rev-list --tags --max-count=2)|tail -1`

2018-07-26 08:51 UTC, cbrgm commented
Thanks for the review! I will do some rework and check the error you mentioned.

2018-07-26 08:52 UTC, alvaroaleman commented on api/hack/changelog-gen.sh
> +	OUTPUT="$(gchl --for-version $1 since $(git tag -l | tail -n 1) $2)"; if [ $? -eq 1 ]; then exit 1; fi
Actually the latest, in my testing I manually created a tag but I just realized the script does this which certainly makes sense

2018-07-31 14:59 UTC, cbrgm commented
To give you a short update on this one: I rewrote the bash script and fixed the points you mentioned @alvaroaleman . I'm still struggling with the tags. I seems like there is no way to display the human-readable names of a commit object like using the `git describe` command with the git library used in `gchl`.

The library only allows to list annotated and lightweight tags found in refs/tags namespace. So the library only allows me to list references like:

```
v1.0.1                            
v1.0 
```

but I'm unable to get a list like

```
v1.0.1                                              
v1.0-2-ga1050a44                                    
v1.0-1-g46b4c026                                    
v1.0 
```
Also the go-git `git describe` compatibility is not yet implemented. [See here](https://github.com/src-d/go-git/blob/master/COMPATIBILITY.md).
I'm still looking for a solution..

2018-07-31 17:44 UTC, alvaroaleman commented
@cbrgm Maybe just use `os/exec.Command("git", "my", "args").CombinedOutput()`? Would be nice to have it in golang but at the end of they day it would still shell out anyways, since many of those git subcommands are Perl scripts ;)

2018-08-01 08:24 UTC, cbrgm commented
Yeah, that was my intention to do. It felt a little bit strange using a library for git in go, but also using `os.Exec`.

might be interesting: [This](https://github.com/kubermatic/gchl/blob/master/pkg/git/git.go#L55) is the function, causing all the troubles. `g.repo.Tags()` behaves equal to `git tag -l`, also tried other approaches yesterday but it seems like using `os.Exec` is the only way to solve this issue here

2018-08-01 13:51 UTC, cbrgm commented
Added the feature to compare hashes with branches/tags and other way around to `gchl`. See [PR](https://github.com/kubermatic/gchl/pull/2).

Also reworked the bash script. It's now using `git rev-list --tags --max-count=2)| tail -1` instead of `git tag -l`.

If you have some time the next days, feel free to try it out @alvaroaleman .

2018-08-03 13:14 UTC, alvaroaleman commented
@cbrgm I took the liberty of finishin this, PTAL

2018-08-03 13:19 UTC, alvaroaleman commented
This needs https://github.com/kubermatic/gchl/pull/2 to be merged, then IMHO its ready

2018-08-03 13:19 UTC, alvaroaleman submitted a review, later dismissed

2018-08-03 13:46 UTC, alvaroaleman approved these changes

2018-08-07 08:18 UTC, cbrgm commented
Thanks @alvaroaleman ! Looks good, well done.

2018-08-07 08:20 UTC, cbrgm commented
kubermatic/gchl#2 has been merged into master.

2018-08-07 11:21 UTC, mrIncompetent approved these changes

2018-08-07 11:27 UTC, merged