Modify cluster metrics
kubermatic/kubermatic pull request #1615
Opened 2018-07-26 11:43 UTC by mrIncompetent

**What this PR does / why we need it**:
- Introduce a cluster collector
- Use var-style metrics declaration

**Release note**:
```release-note
NONE
```

2018-07-27 13:15 UTC, metalmatze requested changes
Overall it's good. I just find the way the collector is created and those objects are passed around quite confusing, but maybe that's just me.

Maybe just a hint on that: You don't really need to create another struct and call it collector. `Collector` is an interface which every struct can implemented by using the exact func signatures.
I'd probably let the controller implement the interface directly.

2018-07-27 13:15 UTC, metalmatze commented on api/cmd/kubermatic-controller-manager/main.go
> +	controller.Register()
Why not do this when creating the controller? The controller is probably instantiated by a func?!

2018-07-27 13:15 UTC, metalmatze commented on api/pkg/collectors/cluster.go
> +	registry.MustRegister(cc)
I thought registering is done outside the collector in the `main.go`?

2018-07-27 13:15 UTC, metalmatze commented on api/pkg/controller/cluster/metrics.go
> +	workersStatisticKey = "workers"
It's not really a key and neither a statistic. I'd simply call it `workers` or `workersGauge` or something like that.

2018-07-27 13:15 UTC, metalmatze commented on config/monitoring/prometheus/jsonnet/alerts/kubermatic.libsonnet
> +              message: 'Cluster {{ $labels.cluster }} is stuck in deletion since more than 30min.',
grammar: `is stuck in deletion for more than 30min.`

2018-07-27 13:23 UTC, metalmatze submitted a review, later dismissed

2018-07-27 13:23 UTC, metalmatze commented on api/pkg/controller/metrics.go
> +	errors = prometheus.NewGauge(
This needs to be a Counter. It has the `_total` suffix and will just `+1` if an error is encountered

2018-07-30 08:02 UTC, mrIncompetent commented on api/pkg/collectors/cluster.go
> +	registry.MustRegister(cc)
`RegisterClusterCollector` gets called from the `main.go` passing in the prometheus registry

2018-07-30 09:08 UTC, mrIncompetent commented on api/pkg/controller/cluster/metrics.go
> +	workersStatisticKey = "workers"
I removed the const, it only gets used in one place, therefore not worth a const

2018-07-30 09:09 UTC, mrIncompetent commented on api/pkg/controller/metrics.go
> +	errors = prometheus.NewGauge(
done in https://github.com/kubermatic/kubermatic/pull/1615/commits/9a63264851f6a99dc2848dfec54f8786f63e02a3

2018-07-30 09:09 UTC, mrIncompetent commented on config/monitoring/prometheus/jsonnet/alerts/kubermatic.libsonnet
> +              message: 'Cluster {{ $labels.cluster }} is stuck in deletion since more than 30min.',
done in https://github.com/kubermatic/kubermatic/pull/1615/commits/9a63264851f6a99dc2848dfec54f8786f63e02a3

2018-07-30 09:11 UTC, mrIncompetent commented on api/cmd/kubermatic-controller-manager/main.go
> +	controller.Register()
I changed it slightly. It was confusing.
It actually attaches a Counter to the global `runtime.HandleErr` function.
That function gets used across all controllers - thus we must only register that metric once.

I moved and renamed it in https://github.com/kubermatic/kubermatic/pull/1615/commits/9a63264851f6a99dc2848dfec54f8786f63e02a3

2018-07-30 09:16 UTC, mrIncompetent commented
> Maybe just a hint on that: You don't really need to create another struct and call it collector. Collector is an interface which every struct can implemented by using the exact func signatures.
I'd probably let the controller implement the interface directly.

Idea is that our controllers only expose the metrics about themself not any data they are processing.

2018-07-30 10:10 UTC, alvaroaleman requested changes

2018-07-30 10:10 UTC, alvaroaleman commented on api/pkg/collectors/cluster.go
> +package collectors
Wouldn't it make more sense to put this package below `pkg/controller/cluster`? At least for me that feels more intuitive

2018-07-30 10:10 UTC, alvaroaleman commented on api/pkg/collectors/cluster.go
> +func RegisterClusterCollector(registry prometheus.Registerer, _ kubeinformers.SharedInformerFactory, kubermaticInformerfactory kubermaticinformers.SharedInformerFactory) {
Maybe put a `Must` in the name to indicate this may panic?

2018-07-30 10:10 UTC, alvaroaleman commented on api/pkg/collectors/collectors.go
> +var AvailableCollectors = map[string]func(registry prometheus.Registerer, informerFactory informers.SharedInformerFactory, kubermaticInformerfactory kubermaticinformers.SharedInformerFactory){
Why is this a var and not a func?

2018-07-30 10:10 UTC, alvaroaleman commented on api/pkg/controller/cluster/metrics.go
> +func init() {
Wont this create issues with parallelized tests?

2018-07-30 10:10 UTC, alvaroaleman commented on api/pkg/metrics/runtime.go
> +func RegisterRuntimErrorMetricCounter(subsystem string, registry prometheus.Registerer) {
Why move this out of the specific controller?

2018-07-30 10:32 UTC, mrIncompetent commented on api/pkg/collectors/cluster.go
> +package collectors
No, because this does not belong to a controller. Its a collector which has nothing in common with the cluster controller

2018-07-30 10:32 UTC, p0lyn0mial requested changes

2018-07-30 10:32 UTC, p0lyn0mial commented on api/cmd/kubermatic-controller-manager/main.go
> +	metrics.RegisterRuntimErrorMetricCounter("kubermatic_controller_manager", prometheus.DefaultRegisterer)
Do you think that having one global error metric is practical ? This might make troubleshooting harder as I would have to find faulty controller, worse if there are two.

2018-07-30 10:33 UTC, mrIncompetent commented on api/pkg/collectors/collectors.go
> +var AvailableCollectors = map[string]func(registry prometheus.Registerer, informerFactory informers.SharedInformerFactory, kubermaticInformerfactory kubermaticinformers.SharedInformerFactory){
Because its a static list which does not have any runtime behavior

2018-07-30 10:35 UTC, mrIncompetent commented on api/pkg/controller/cluster/metrics.go
> +func init() {
It uses sync.Once to prevent issues with parallelized tests

2018-07-30 10:38 UTC, mrIncompetent commented on api/pkg/metrics/runtime.go
> +func RegisterRuntimErrorMetricCounter(subsystem string, registry prometheus.Registerer) {
All controllers call runtime.HandleErr. Its a shared error handler.

In the old code, we only registered it inside the cluster-controller - registering it twice would cause an increment of the metrics by 2 for each error.

`runtime.HandleErr` is a **global** error handler - thus it does not belong into a specific controller.

2018-07-30 10:39 UTC, mrIncompetent commented on api/cmd/kubermatic-controller-manager/main.go
> +	metrics.RegisterRuntimErrorMetricCounter("kubermatic_controller_manager", prometheus.DefaultRegisterer)
See https://github.com/kubermatic/kubermatic/pull/1615#discussion_r206086584

2018-07-30 10:41 UTC, p0lyn0mial commented on api/pkg/collectors/cluster.go
> +
I would add the following to make sure that `ClusterCollector` "implements" `prometheus.Collector` at compile time.

`var _ prometheus.Collector = ClusterCollector{}`

2018-07-30 10:41 UTC, alvaroaleman commented on api/pkg/collectors/collectors.go
> +var AvailableCollectors = map[string]func(registry prometheus.Registerer, informerFactory informers.SharedInformerFactory, kubermaticInformerfactory kubermaticinformers.SharedInformerFactory){
Yeah but a package var always gets allocated independently of the question if its actualy being used, so a `getter` func feels more appropriate

2018-07-30 10:45 UTC, alvaroaleman commented on api/pkg/metrics/runtime.go
> +func RegisterRuntimErrorMetricCounter(subsystem string, registry prometheus.Registerer) {
Okay, then maybe add a label indicating the originating controller?

2018-07-30 10:45 UTC, mrIncompetent commented on api/pkg/collectors/collectors.go
> +var AvailableCollectors = map[string]func(registry prometheus.Registerer, informerFactory informers.SharedInformerFactory, kubermaticInformerfactory kubermaticinformers.SharedInformerFactory){
wont change

2018-07-30 10:45 UTC, alvaroaleman commented on api/pkg/metrics/runtime.go
> +func RegisterRuntimErrorMetricCounter(subsystem string, registry prometheus.Registerer) {
Or is the idea to additionally have a per-controller error metric?

2018-07-30 10:50 UTC, mrIncompetent commented on api/pkg/metrics/runtime.go
> +func RegisterRuntimErrorMetricCounter(subsystem string, registry prometheus.Registerer) {
Quoting myself: 
> `runtime.HandleErr` is a global error handler - thus it does not belong into a specific controller.

2018-07-30 10:53 UTC, mrIncompetent commented on api/pkg/collectors/cluster.go
> +
Doesn't this already get checked via https://github.com/kubermatic/kubermatic/pull/1615/files/ad06ad01a081b990c2ada8f3886c4b7e64f68697#diff-fa63ed4d4f76224f4b46b2d5f1509d3aR46 ?

2018-07-30 10:56 UTC, alvaroaleman commented on api/pkg/metrics/runtime.go
> +func RegisterRuntimErrorMetricCounter(subsystem string, registry prometheus.Registerer) {
Yes I understood that but I don't really see the value: It indicates something is broken but gives no indication about the area _where_ it is broken

2018-07-30 10:59 UTC, mrIncompetent commented on api/pkg/metrics/runtime.go
> +func RegisterRuntimErrorMetricCounter(subsystem string, registry prometheus.Registerer) {
And this discussion is not part of this PR as this PR does not change anything on the logic of that metric.
It just moves it somewhere else as it currently leads to the impression that this metrics is cluster-controller specific

2018-07-30 11:01 UTC, p0lyn0mial commented on api/pkg/metrics/runtime.go
> +func RegisterRuntimErrorMetricCounter(subsystem string, registry prometheus.Registerer) {
I support this see https://github.com/kubermatic/kubermatic/pull/1615#discussion_r206084838

I think that having one global error metric is not practical because you would have to find the faulty controller anyway.

2018-07-30 11:03 UTC, p0lyn0mial commented on api/pkg/collectors/cluster.go
> +
yes it does, but at runtime, not at compile time. In addition is serves also as a documentation :)

2018-07-30 11:08 UTC, alvaroaleman commented on api/pkg/metrics/runtime.go
> +func RegisterRuntimErrorMetricCounter(subsystem string, registry prometheus.Registerer) {
Valid point. I've created #1627 so we keep track of that.

2018-07-30 12:33 UTC, mrIncompetent commented on api/pkg/collectors/cluster.go
> +
I just changed the signature of the Collect function - i was not able to compile anymore due to https://github.com/kubermatic/kubermatic/pull/1615/files/ad06ad01a081b990c2ada8f3886c4b7e64f68697#diff-fa63ed4d4f76224f4b46b2d5f1509d3aR46

2018-07-30 12:56 UTC, mrIncompetent commented
@metalmatze @alvaroaleman @p0lyn0mial everything adressed so PTAL :)

2018-08-01 14:43 UTC, mrIncompetent commented
Ping @alvaroaleman @p0lyn0mial

2018-08-01 15:07 UTC, alvaroaleman approved these changes

2018-08-02 07:52 UTC, p0lyn0mial commented
@mrIncompetent thanks for addressing the comments ;)

2018-08-02 07:52 UTC, p0lyn0mial approved these changes

2018-08-02 08:20 UTC, merged