Feature/1475 ipam controller
kubermatic/kubermatic pull request #1616
Opened 2018-07-26 11:54 UTC by pkavajin

**What this PR does / why we need it**:
Adds a controller for static ip address management.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1475 

**Special notes for your reviewer**:

**Release note**:

```release-note
Added a controller for static ip address management.
```

2018-07-27 14:34 UTC, alvaroaleman requested changes

2018-07-27 14:34 UTC, alvaroaleman commented on api/Makefile
> +CMD=kubermatic-api kubermatic-controller-manager kubermatic-controller-manager-cleanup image-loader rbac-generator s3-storeuploader kubermatic-e2e s3-exporter ipam-controller
Wouldn't it make sense to use this as the first part of a user-cluster-controller-manager? We will be writing more controllers that talk exclusively to the user cluster

2018-07-27 14:34 UTC, alvaroaleman commented on api/cmd/ipam-controller/main.go
> +	flag.StringVar(&gateway, "gateway", "", "Ip of the gateway which should be used.")
Does it make sense like this? Wouldn't it be more useful to have a gateway per CIDR block?

2018-07-27 14:34 UTC, alvaroaleman commented on api/cmd/ipam-controller/main.go
> +	usedIps = make(map[string]struct{})
This is not sufficient, it must survive crashes

2018-07-27 14:34 UTC, alvaroaleman commented on api/cmd/ipam-controller/main.go
> +				err := machineUpdated(mOld, mNew, machineClient)
You should use the same func for both update and create events, as its the same underlying business logic. You can just discard `machineOld`, we don't care about the transition

2018-07-27 14:34 UTC, alvaroaleman commented on api/cmd/ipam-controller/main.go
> +				mOld, ok := oldObj.(*machinev1alpha1.Machine)
This controller is missing a workqeue, the general workflow is:

EventHandlerTriggers => Some generic func that just takes the machine and puts its name into a workqeue => workers take items off the qeue and work onto it in a `Sync(machineName string) error` => The sync handles both the deletion and the initialization case => If there is an error, the item gets reqeued

Check e.G `pkg/controller/backup` for a simple controller or https://github.com/kubernetes/sample-controller/blob/master/controller.go

Just ping me if you have further questions

2018-07-28 11:31 UTC, pkavajin commented on api/cmd/ipam-controller/main.go
> +	flag.StringVar(&gateway, "gateway", "", "Ip of the gateway which should be used.")
thought so aswell, but iirc we discussed that and the point was: "we dont support different gateways/networks, all cidr ranges should go in one network". Nonetheless, asked the customer about their network infrastructure, still waiting for an answer from their side.

2018-07-28 11:40 UTC, pkavajin commented on api/Makefile
> +CMD=kubermatic-api kubermatic-controller-manager kubermatic-controller-manager-cleanup image-loader rbac-generator s3-storeuploader kubermatic-e2e s3-exporter ipam-controller
Maybe, dunno. Should talk about this one.

2018-07-28 11:46 UTC, pkavajin commented on api/cmd/ipam-controller/main.go
> +	usedIps = make(map[string]struct{})
Prolly a stupid question - but why should it? 
This is just a local cache which gets filled when controller gets started and lists the machines. K8S is data leading and the "persistence layer" in here, not the ipam controller.

2018-07-28 11:59 UTC, pkavajin commented on api/cmd/ipam-controller/main.go
> +				mOld, ok := oldObj.(*machinev1alpha1.Machine)
Yeah saw that, had initially used a workerqueue. Stripped it off.
Could you explain to me why I should use a workerqueue here?

I'd see the reason when you want to buffer/batch/distribute over multiple workers, but ipam controller isn't doing any of that.

2018-07-28 19:14 UTC, alvaroaleman requested changes

2018-07-28 19:14 UTC, alvaroaleman commented on api/cmd/ipam-controller/main.go
> +	flag.StringVar(&gateway, "gateway", "", "Ip of the gateway which should be used.")
IMHO (And you were actually the one who intitially brought up that point) this is very, very unlikely to be the case. And if it was the case, we could still enter the same gateway in all CIDR blocks so IMHO it makes much more sense to put it as part of the CIDR block

2018-07-28 19:14 UTC, alvaroaleman commented on api/cmd/ipam-controller/main.go
> +	usedIps = make(map[string]struct{})
Sorry I must be blind then but where exactly does it get filled on startup?

2018-07-28 19:14 UTC, alvaroaleman commented on api/Makefile
> +CMD=kubermatic-api kubermatic-controller-manager kubermatic-controller-manager-cleanup image-loader rbac-generator s3-storeuploader kubermatic-e2e s3-exporter ipam-controller
True. But can we please seperate the actual controllers business logic and stuff like lister/informer creation, argument parsing and leader election and have the former below `pkg/controller/ipam` and just the latter within `cmd/ipam-controller`? This aligns with how we do it everywhere else and IMHO makes the code much easier to read

2018-07-28 19:14 UTC, alvaroaleman commented on api/cmd/ipam-controller/main.go
> +				mOld, ok := oldObj.(*machinev1alpha1.Machine)
No, the main reason is to do proper reconciliation: If the controller cant satisfy a request at a given point in time, e.G. because there is no free IP left it has to retry and this retry has to happen continuously but with an increasing delay because it may be able to satisfy the request later on, e.G. because a machine got deleted or a new CIDR block got added

The workqeue does that for you, thats why the `Add` func is not named `Add` but `AddRateLimited` ;)

2018-07-28 19:14 UTC, alvaroaleman commented on api/cmd/ipam-controller/main.go
> +	glog.V(6).Infof("machine deleted %s", m.Name)
Please use a finalizer here, Kubernetes gives you zero guarantees about catching specific events

2018-07-30 09:04 UTC, pkavajin commented on api/Makefile
> +CMD=kubermatic-api kubermatic-controller-manager kubermatic-controller-manager-cleanup image-loader rbac-generator s3-storeuploader kubermatic-e2e s3-exporter ipam-controller
talked with henrik about user-cluster-controller-manager, will be a future task.

2018-07-31 10:05 UTC, pkavajin commented
@alvaroaleman @mrIncompetent could you guys have another look whether this looks fine to you?

2018-07-31 10:49 UTC, alvaroaleman requested changes
Couple of nits, mostly regarding naming, looks really good overall now!

2018-07-31 10:49 UTC, alvaroaleman commented on api/Makefile
> +KUBERMATICTAG=$(shell git describe --abbrev=0 --tags)
Does this make sense? This will result in always using the last git tag, even if its on a completely different commit which may not even be present in the current branch

2018-07-31 10:49 UTC, alvaroaleman commented on api/cmd/ipam-controller/main.go
> +	flag.Var(&networks, "network", "The networks from which ips should be allocated (format: cidr,gw,dns1,dns2,...)")
Please provide an example on how to specify multiple cidrs, It can be done by just using the flag multiple times, right?

2018-07-31 10:49 UTC, alvaroaleman commented on api/cmd/ipam-controller/main.go
> +		tweakFunc := func(options *metav1.ListOptions) {
Nice, I didn't know this is possible!

2018-07-31 10:49 UTC, alvaroaleman commented on api/pkg/api/v1/types.go
> +	MachineNetworks []kubermaticv1.MachineNetworkingConfig `json:"machineNetworks,omitempty"`
Does this means the `Networks` are immutable?

2018-07-31 10:49 UTC, alvaroaleman commented on api/pkg/controller/cluster/auth.go
> +func (cc *Controller) getDockerCfgSecret(c *kubermaticv1.Cluster, existingSecret *corev1.Secret) (*corev1.Secret, string, error) {
Can we rename this to `getImagePullSecret` because thats what it really is?

2018-07-31 10:49 UTC, alvaroaleman commented on api/pkg/resources/resources.go
> +	IPAMControllerCertUsername = "ipam-controller"
Can we rename this to `kubermatic:ipam-controller` so we stay in our namespace?

2018-07-31 10:49 UTC, alvaroaleman commented on api/pkg/controller/cluster/resources.go
> +		{resources.DockerCfgSecretName, cc.getDockerCfgSecret},
As above, please rename to `ImagePullSecret` as the fact that its a dockercfg is an implementation detail that tells you nothing about its purpose

2018-07-31 10:49 UTC, alvaroaleman commented on api/pkg/controller/cluster/resources.go
> +	if len(c.Spec.MachineNetworks) > 0 {
Can we move this into `GetDeploymentCreators` so this gets picked up by the unittests?

2018-07-31 10:49 UTC, alvaroaleman commented on api/pkg/controller/cluster/resources.go
> +		{resources.DockerCfgSecretName, cc.getDockerCfgSecret},
@mrIncompetent Do we still use `ensureSecrets`? It is marked as `deprecated`

2018-07-31 10:49 UTC, alvaroaleman commented on api/pkg/controller/cluster/userclusterresources.go
> +	if len(c.Spec.MachineNetworks) > 0 {
Please create a `GetUserClusterRoleCreators` func so this can be tested

2018-07-31 10:49 UTC, alvaroaleman commented on api/pkg/controller/cluster/userclusterresources.go
> +	if len(c.Spec.MachineNetworks) > 0 {
Please add a `GetUserClusterRoleBindingCreators` func so this can be tested

2018-07-31 10:49 UTC, alvaroaleman commented on api/pkg/controller/ipam/controller.go
> +	machineInformer.Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{
You need to start the factory and wait for its sync, If I didn't miss it you currently dont do that: https://github.com/kubermatic/kubermatic/blob/36b1fcbadcabfe3553e488c347bc50aed1c9a151/api/cmd/kubermatic-controller-manager/main.go#L269-L274

Please do that within the `cmd/`

2018-07-31 10:49 UTC, alvaroaleman commented on api/pkg/controller/ipam/controller.go
> +	// Remove self from the list of pending Initializers while preserving ordering.
Does the order matter?

2018-07-31 10:49 UTC, alvaroaleman commented on api/pkg/controller/ipam/controller.go
> +func (c *Controller) getNextFreeIP() (net.IP, Network) {
Wouldn'it be easier to let this return an `error` instead of using `ip.IsUnspecified()` checks throughout the code?

2018-07-31 10:49 UTC, alvaroaleman commented on api/pkg/resources/apiserver/deployment_test.go
> +			expectedAdmissionControlFlagValue: "Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,ResourceQuota",
According to the docs[0], this wont work: `Ensure that the Kubernetes cluster is at least as new as v1.9.`, so we have to make this conditional

[0] https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/

2018-07-31 10:49 UTC, alvaroaleman commented on api/pkg/resources/apiserver/deployment_test.go
> +			expectedAdmissionControlFlagValue: "Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,ResourceQuota",
And also let the API return an error if someone attemps to create an 1.8 cluster with networkConfig

2018-07-31 10:49 UTC, alvaroaleman commented on api/pkg/resources/ipamcontroller/deployment.go
> +		"--kubeconfig", fmt.Sprintf("%s/%s", kcDir, resources.IPAMControllerKubeconfigSecretName),
Correct me if I am wrong but this must not be the name of the secret but instead the name of the key inside the secret, or am I missunderstanding something?

2018-07-31 11:26 UTC, pkavajin commented on api/Makefile
> +KUBERMATICTAG=$(shell git describe --abbrev=0 --tags)
Any better idea?
Your local (docker image tag) doesnt have to be available remote. So. Mh.
This way we atleast always get the latest stable deployed, which is imho at least a bit better than how the machine controller does it - by hardcoding it.

2018-07-31 11:31 UTC, pkavajin commented on api/pkg/api/v1/types.go
> +	MachineNetworks []kubermaticv1.MachineNetworkingConfig `json:"machineNetworks,omitempty"`
Ehm, why do you think so?
They are mutable?
Should be frontends job to make sure nobody deletes a used network config.

2018-07-31 11:39 UTC, pkavajin commented on api/pkg/controller/ipam/controller.go
> +	// Remove self from the list of pending Initializers while preserving ordering.
Documentation stated so. Makes sense imho aswell, e.g. you want sth like "CreateResourceGroup" initializer to be executed before "CreateSomethingInThatResourceGroup"

2018-07-31 12:04 UTC, pkavajin commented on api/pkg/resources/apiserver/deployment_test.go
> +			expectedAdmissionControlFlagValue: "Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,ResourceQuota",
Mh. Wondering about that "ensure that the cluster ...." part since initializers were stated alpha in 1.8 Oo Nvm, on it.

2018-07-31 12:05 UTC, pkavajin commented on api/pkg/resources/ipamcontroller/deployment.go
> +		"--kubeconfig", fmt.Sprintf("%s/%s", kcDir, resources.IPAMControllerKubeconfigSecretName),
since both are the same, we're fine.

2018-07-31 13:06 UTC, pkavajin commented on api/pkg/controller/cluster/resources.go
> +	if len(c.Spec.MachineNetworks) > 0 {
huh? What unittests are you talking about? AFAIK no test calls GetDeploymentCreators? Its just resources.go and some undocumented image-loader which doesnt have any cluster related info, therefore moving the code up there seems odd

2018-07-31 13:32 UTC, alvaroaleman approved these changes

2018-07-31 13:32 UTC, alvaroaleman commented on api/pkg/api/v1/types.go
> +	MachineNetworks []kubermaticv1.MachineNetworkingConfig `json:"machineNetworks,omitempty"`
Because the struct is called `NewClusterSpec` but I later saw its also part of the `Cluster` CRD.

2018-07-31 13:32 UTC, alvaroaleman commented on api/Makefile
> +KUBERMATICTAG=$(shell git describe --abbrev=0 --tags)
Maybe just use the git commit sha?

2018-07-31 13:32 UTC, alvaroaleman commented on api/pkg/controller/cluster/resources.go
> +	if len(c.Spec.MachineNetworks) > 0 {
Oups, you are right. Big failure. I will fix the test to do that. It is supposed to get called from `api/pkg/resources/test/load_files_test.go` but we currently manually specifiy all deployments there.

2018-07-31 13:33 UTC, alvaroaleman requested changes
Sorry, approve was a misclick and GH doesnt allow to change it

2018-07-31 14:00 UTC, pkavajin commented on api/Makefile
> +KUBERMATICTAG=$(shell git describe --abbrev=0 --tags)
so running controller locally means you have to push to docker aswell? :-(
What about CI? Will there always be a pushed tag with the git sha?

2018-07-31 17:20 UTC, alvaroaleman commented on api/Makefile
> +KUBERMATICTAG=$(shell git describe --abbrev=0 --tags)
> so running controller locally means you have to push to docker aswell? :-(

What has one to do with the other? The controller creates a deployment so if you want to test that yes, you need to push

> What about CI? Will there always be a pushed tag with the git sha?

Why not? Docker registries are payed per private repo, not per tags

2018-08-01 08:57 UTC, alvaroaleman submitted a review, later dismissed

2018-08-01 09:06 UTC, alvaroaleman submitted a review, later dismissed

2018-08-01 09:08 UTC, pkavajin commented
@mrIncompetent could you have a look? missing some approves for merge.

2018-08-02 07:23 UTC, mrIncompetent commented on api/pkg/resources/apiserver/deployment.go
> +		flags = append(flags, "--feature-gates", "Initializers=true")
This means we no support v1.8 with this feature?
If thats the case, we either need to add validation, to prevent creation of clusters with version 1.8 and IPAM enabled, or remove support for v1.8 completely.

2018-08-02 07:27 UTC, mrIncompetent commented on api/pkg/controller/ipam/controller.go
> +}
You could also do:
```go
type CIDRExhaustedError error
```

to avoid implementing a custom struct which implements the error interface.

2018-08-02 07:42 UTC, mrIncompetent commented on api/pkg/controller/ipam/controller.go
> +	c.usedIps[ip.String()] = struct{}{}
Please remove maintaining this state - it's not reliable at all.

Example:
- Controller dies
- New machine gets created
- Controller starts
- Controller syncs new machine first, before syncing the existing ones
- Already assigned IP gets assigned again - at least that's how the code looks (haven't tested that case)

Better (IMO):
On each sync - calculate the already assigned IP's based from the machines in the Lister.
Additionally - when setting an IP to a machine - wait until that update appears in the Lister

2018-08-02 07:45 UTC, mrIncompetent commented on api/pkg/controller/ipam/controller.go
> +	IPNet      *net.IPNet
Does this need to be a pointer?

2018-08-06 12:49 UTC, mrIncompetent commented on api/pkg/controller/ipam/controller.go
> +	liveSync bool
Is this only being used for testing?

2018-08-06 13:08 UTC, pkavajin commented on api/pkg/controller/ipam/controller.go
> +	liveSync bool
yes, at least for now. Could be needed for azure later tho.

2018-08-06 15:19 UTC, mrIncompetent submitted a review, later dismissed

2018-08-07 12:49 UTC, pkavajin commented
@alvaroaleman @p0lyn0mial PTAL

2018-08-09 14:17 UTC, alvaroaleman commented on api/pkg/resources/apiserver/deployment.go
> +		flags = append(flags, "--feature-gates", "Initializers=true")
This question is unanswered. I personally am in favor of simply removing 1.8 support after it is now broken in the latest patch release anyways. Maybe we can keep it as-is within this PR and create a follow-up to remove the support?

We have to find a solution for what to do with existing 1.8 clusters thought. Force-Upgrade? Ignore by cluster-controller?

2018-08-09 14:21 UTC, alvaroaleman requested changes

2018-08-09 14:21 UTC, alvaroaleman commented on api/pkg/resources/test/load_files_test.go
> +				deps := clustercontroller.GetDeploymentCreators(nil)
Can we pass in a cluster here that has static IPs configured so we actually get fixtures for the IPAM controller deployment?

2018-08-09 15:24 UTC, alvaroaleman submitted a review, later dismissed

2018-08-09 15:32 UTC, mrIncompetent submitted a review, later dismissed

2018-08-13 11:46 UTC, p0lyn0mial commented on api/pkg/controller/ipam/controller.go
> +	return m.ObjectMeta.GetInitializers().Pending[0].Name == initializerName
wouldn't be better the check the exact name match ? Machine objects live inside the user's cluster and the users of the cluster can add their own initialisers.

2018-08-13 12:50 UTC, p0lyn0mial commented on api/pkg/controller/ipam/controller.go
> +		CIDR:    ip.String(),
how about renaming `CIRD` field to `IP` ? From what I have seen we always assign an IP address to it.

2018-08-13 12:57 UTC, p0lyn0mial commented on api/pkg/controller/ipam/controller.go
> +		if ip[len(ip)-1] == 0 || ip.Equal(network.Gateway) {
if the CIDR is "192.168.100.14/24" then I think that 192.168.100.255 is an invalid host address because if I recall correctly 255 is reserved.

2018-08-13 13:25 UTC, p0lyn0mial commented on api/pkg/controller/ipam/controller.go
> +func (c *Controller) initMachineIfNeeded(machine *machinev1alpha1.Machine) (bool, error) {
this method returns two parameters but only one is used. change the signature.

2018-08-13 13:34 UTC, p0lyn0mial commented on api/pkg/controller/ipam/controller.go
> +	go wait.Until(c.runWorker, time.Second, stopCh)
I would add a comment saying that it is very important that this controller is single threaded.

2018-08-13 13:41 UTC, p0lyn0mial commented on api/pkg/controller/ipam/controller.go
> +func (c *Controller) inc(ip net.IP) {
Have you considered to randomise IP assignment ? Perhaps this could minimise duplication in cases the cache doesn't reflect the actual pool of IP addresses.

2018-08-14 09:32 UTC, pkavajin commented on api/pkg/controller/ipam/controller.go
> +	return m.ObjectMeta.GetInitializers().Pending[0].Name == initializerName
Huh? What do you mean by exact name match?

2018-08-14 09:39 UTC, p0lyn0mial commented on api/pkg/controller/ipam/controller.go
> +	return m.ObjectMeta.GetInitializers().Pending[0].Name == initializerName
sorry Mondays :), I think that there can be more than one pending initialiser because the users of the cluster might add them. Wouldn't be better to iterate over the list and find a matching one ? Or we are absolutely sure that ours will always be on the first position ?

2018-08-14 09:46 UTC, pkavajin commented on api/pkg/controller/ipam/controller.go
> +func (c *Controller) inc(ip net.IP) {
If the cache doesnt reflect the actual pool of IP addresses, something went terribly wrong. Either synchronization or leaderelection doesnt work. IMHO relying on randomness to reduce error likeliness doesn't sound good. Since the error still can happen, we just make detection and reproduction worse. We should fix the source of the problem instead.

2018-08-14 10:16 UTC, p0lyn0mial commented on api/pkg/validation/cluster.go
> +	if len(spec.MachineNetworks) > 0 && clusterSemVer.Minor() < 9 {
do we perform any validation of `spec.MachineNetworks` ? I'd check at least if we can parse the addresses (`ParseIP` and `ParseCIDR`)

2018-08-14 11:12 UTC, pkavajin commented on api/pkg/controller/ipam/controller.go
> +	return m.ObjectMeta.GetInitializers().Pending[0].Name == initializerName
A lot of documentation on initializers state that the order matters, (which makes sense in case one initializer depends on another one). So we just handle the resource if its our turn (aka initializer[0] == initializerName)

2018-08-14 11:25 UTC, alvaroaleman commented on api/pkg/controller/ipam/controller.go
> +	return m.ObjectMeta.GetInitializers().Pending[0].Name == initializerName
The iteration has the advantage thought that a) if we ever decide we need an initializer prior to this one the code still works b) if for whatever reason the list of `Pending` initializers has a length of zero, this controller wont crash the whole controller-manager

2018-08-14 12:02 UTC, pkavajin commented on api/pkg/controller/ipam/controller.go
> +	go wait.Until(c.runWorker, time.Second, stopCh)
👍

2018-08-14 12:02 UTC, pkavajin commented on api/pkg/controller/ipam/controller.go
> +func (c *Controller) initMachineIfNeeded(machine *machinev1alpha1.Machine) (bool, error) {
👍

2018-08-14 12:02 UTC, pkavajin commented on api/pkg/controller/ipam/controller.go
> +		if ip[len(ip)-1] == 0 || ip.Equal(network.Gateway) {
👍

2018-08-14 13:18 UTC, pkavajin commented on api/pkg/validation/cluster.go
> +	if len(spec.MachineNetworks) > 0 && clusterSemVer.Minor() < 9 {
👍

2018-08-14 13:18 UTC, pkavajin commented on api/pkg/controller/ipam/controller.go
> +		CIDR:    ip.String(),
Ehm. Im stupid af. We use the cidr now :-)

2018-08-15 12:57 UTC, mrIncompetent approved these changes

2018-08-16 06:08 UTC, p0lyn0mial approved these changes

2018-08-16 08:32 UTC, alvaroaleman approved these changes

2018-08-16 08:33 UTC, merged