remove has synced check
kubermatic/kubermatic pull request #1618
Opened 2018-07-26 13:18 UTC by mrIncompetent

**What this PR does / why we need it**:
Remove has synced check in all controllers

**Release note**:
```release-note
NONE
```

2018-07-26 13:52 UTC, alvaroaleman requested changes
Am I blind or is the sync checking still missing?

2018-07-26 13:52 UTC, alvaroaleman commented on api/cmd/kubermatic-controller-manager/controllers.go
> +	return func() error {
Is the error return for further extension? Because as it stands this func can never return an error

2018-07-26 13:52 UTC, alvaroaleman commented on api/cmd/kubermatic-controller-manager/controllers.go
> +		g.Add(f, func(err error) {})
Shouldn't the second currently empty func be a func that sends something down the `done` channel and hence stops the controllers?

2018-07-26 13:52 UTC, alvaroaleman commented on api/cmd/kubermatic-controller-manager/controllers.go
> +		return nil, fmt.Errorf("failed to parse %s as duratation: %v", ctrlCtx.runOptions.backupInterval, err)
Typo, `s/duratation/duration/g`

2018-07-26 13:52 UTC, alvaroaleman commented on api/pkg/controller/addoninstaller/addoninstaller_controller.go
> -	clusterSynced    cache.InformerSynced
So awesome to see these go

2018-07-26 13:53 UTC, mrIncompetent commented on api/cmd/kubermatic-controller-manager/controllers.go
> +	return func() error {
The run group expects a function which returns an error

2018-07-26 14:22 UTC, mrIncompetent commented on api/cmd/kubermatic-controller-manager/controllers.go
> +		g.Add(f, func(err error) {})
Good catch, i forgot to pass through the Cancel func.
Done in https://github.com/kubermatic/kubermatic/pull/1618/commits/5360942abc0ec9e9e6f82cf0b40f98e5caa51e19

2018-07-26 14:23 UTC, mrIncompetent commented
> Am I blind or is the sync checking still missing?

https://github.com/kubermatic/kubermatic/blob/remove-has-synced-checks/api/cmd/kubermatic-controller-manager/main.go#L149
https://github.com/kubermatic/kubermatic/blob/remove-has-synced-checks/api/cmd/kubermatic-controller-manager/main.go#L270

2018-07-26 14:32 UTC, alvaroaleman submitted a review, later dismissed

2018-07-26 15:11 UTC, alvaroaleman approved these changes

2018-07-27 10:48 UTC, p0lyn0mial commented on api/cmd/kubermatic-controller-manager/controllers.go
> +	return g.Run()
This means that one faulty controller in the group can take all the controllers down. This is quite heavy because for instance backup controller can die for some reason and suddenly the users are not able to create clusters because there is no cluster controller.

Also taking down all the controllers will cause a lot of noise and errors and might make troubleshooting harder.

Is this intentional ?

2018-07-27 10:50 UTC, mrIncompetent commented on api/cmd/kubermatic-controller-manager/controllers.go
> +	return g.Run()
Why else did we ever introduced the run.Group?

Already now, if the http-server which serves the `/metrics` endpoint dies, everything will shutdown.

In my opinion if one of the controller dies, the whole controller-manager must die. Otherwise we run a broken state

2018-07-27 10:52 UTC, alvaroaleman commented on api/cmd/kubermatic-controller-manager/controllers.go
> +	return g.Run()
I think it makes sense that way, because a crashing app is a very obvious error condition, one controller not running while the others still do may not be as obvious.

2018-07-27 11:00 UTC, p0lyn0mial commented on api/pkg/controller/rbac/rbac_controller.go
> -	defer glog.Info("Shutting down RBACGenerator controller")
we don't want to log when the controller starts shutting down anymore ?

2018-07-27 11:01 UTC, mrIncompetent commented on api/pkg/controller/rbac/rbac_controller.go
> -	defer glog.Info("Shutting down RBACGenerator controller")
https://github.com/kubermatic/kubermatic/pull/1618/files#diff-6aa8411af17ce0e6238a3e9625e60ff3R58

2018-07-27 11:02 UTC, p0lyn0mial commented on api/pkg/controller/rbac/rbac_controller.go
> -	defer glog.Info("Shutting down RBACGenerator controller")
ah, okay

2018-07-27 11:03 UTC, p0lyn0mial commented on api/cmd/kubermatic-controller-manager/controllers.go
> +	return g.Run()
alright :)

2018-07-27 11:03 UTC, p0lyn0mial approved these changes

2018-07-27 11:04 UTC, merged

2018-07-27 11:27 UTC, p0lyn0mial commented on api/pkg/controller/rbac/rbac_controller.go
> -	c.userSynced = userInformer.Informer().HasSynced
i have just realised that rbac controller is not controlled by controller-manager :D it is controlled by rbac-generator app :(