add a v3 project-based metrics endpoint
kubermatic/kubermatic pull request #1622
Opened 2018-07-27 10:07 UTC by kdomanski

fixes #1555 

Release note:
```release-note
NONE
```

2018-07-27 12:08 UTC, p0lyn0mial requested changes

2018-07-27 12:08 UTC, p0lyn0mial commented on api/hack/verify-swagger.sh
> +trap "rm -f $TMP_SWAGGER" EXIT SIGINT SIGTERM
wow, not sure how practical this is because in CI storage is ephemeral and on a local machine the next time we try to run the script we might have more luck :)

2018-07-27 12:08 UTC, p0lyn0mial commented on api/pkg/handler/cluster.go
> +	if prometheusURL == nil {
why not to move this block (538:550) of code inside nested function return `func(ctx context.Context, request interface{}) (interface{}, error)` ?

2018-07-27 12:08 UTC, p0lyn0mial commented on api/pkg/handler/cluster.go
> +			if err == provider.ErrNotFound {
it is enough to return `return nil, kubernetesErrorToHTTPError(err)` as `kubernetesErrorToHTTPError` will set proper HTTP Status when the resource was not found.

2018-07-27 12:08 UTC, p0lyn0mial commented on api/pkg/handler/cluster.go
> +		glog.Fatal(err)
please don't use `glog.Fatal` because it calls `os.Exit()`

2018-07-27 12:08 UTC, p0lyn0mial commented on api/pkg/handler/cluster.go
> +	promClient, err := prometheusapi.NewClient(prometheusapi.Config{
I think having only once instance of `promClient` is enough since `prometheusURL` doesn't change between subsequent request ?

2018-07-27 12:08 UTC, p0lyn0mial commented on api/pkg/handler/cluster_test.go
> +	t.Parallel()
why :( ?

2018-07-27 12:27 UTC, kdomanski commented on api/hack/verify-swagger.sh
> +trap "rm -f $TMP_SWAGGER" EXIT SIGINT SIGTERM
This is to prevent the file from being left behind on local dev. Or I could just add it to `.gitignore` to prevent it from polluting `git status`.

2018-07-27 12:30 UTC, kdomanski commented on api/pkg/handler/cluster_test.go
> +	t.Parallel()
Uh, to make testing faster.

2018-07-27 12:47 UTC, kdomanski commented on api/pkg/handler/cluster.go
> +		glog.Fatal(err)
It was that way in the original `getClusterMetricsEndpoint` function, so I just copied it. This can only be called during router initialization anyways.

2018-07-27 12:48 UTC, kdomanski commented on api/pkg/handler/cluster.go
> +	promClient, err := prometheusapi.NewClient(prometheusapi.Config{
Well, it's one per endpoint, unless I move this block lower like you proposed earlier.

2018-07-27 12:49 UTC, kdomanski commented on api/pkg/handler/cluster.go
> +	if prometheusURL == nil {
This sounds contradictory to your later comment.

> I think having only once instance of `promClient` is enough since `prometheusUR` doesn't change between subsequent request ?

2018-07-27 12:51 UTC, kdomanski commented on api/pkg/handler/cluster.go
> +			if err == provider.ErrNotFound {
Fixed.

2018-07-30 09:45 UTC, p0lyn0mial approved these changes

2018-07-30 09:45 UTC, p0lyn0mial commented on api/pkg/handler/cluster_test.go
> +	t.Parallel()
Usually it is not practical because unit tests take fraction of second to complete. But I noticed that the tests under `handler` package take 30 s so I think it might actually help :) Thanks!

2018-07-30 09:45 UTC, p0lyn0mial commented on api/hack/verify-swagger.sh
> +trap "rm -f $TMP_SWAGGER" EXIT SIGINT SIGTERM
no strong opinion here, I think we can leave it as it is.

2018-07-30 09:50 UTC, mrIncompetent approved these changes

2018-07-30 09:55 UTC, merged