Add API endpoints for retrieving and revoking an admin token
kubermatic/kubermatic pull request #1626
Opened 2018-07-30 11:02 UTC by xrstf

**What this PR does / why we need it**:

Previously, revoking an admin token meant that the frontend would generate a new token and update the cluster resource. This new endpoint allows it to generate a new, secure token on the server-side and uncouples the token from the cluster resource (in future versions).

**Which issue(s) this PR fixes**:

Fixes #1534

**Special notes for your reviewer**:

The token generation code was copied from the cluster creation code. I would love to create a `generateAdminToken()` function somewhere and remove the code duplication, but could not find a good spot to do so.

Likewise, I would have liked to verify the token's format in the unit test, but the current validation package for clusters requires a fully, well-defined cluster structure. If possible, I would extract the token check into a dedicated public function and just call that one (like `pkg.validation.IsValidAdminToken()` or something like that).

**Release note**:

```release-note
NONE
```

2018-07-30 15:11 UTC, p0lyn0mial requested changes

2018-07-30 15:11 UTC, p0lyn0mial commented on api/pkg/handler/cluster.go
> +		cluster.Address.AdminToken = fmt.Sprintf("%s.%s", rand.String(6), rand.String(16))
> I would love to create a generateAdminToken() function somewhere and remove the code duplication, but could not find a good spot to do so.

good call, I think it is okay to expose a method in `cluster` controller. This is something we actually already do in a few other places.

2018-07-30 15:11 UTC, p0lyn0mial commented on api/pkg/handler/cluster_test.go
> +	// ep, err := createTestEndpoint(tester, []runtime.Object{}, []runtime.Object{user, project, cluster}, nil, nil)
please remove commented line.

2018-07-30 15:11 UTC, p0lyn0mial commented on api/pkg/handler/cluster_test.go
> +	updatedCluster, err := clientsSets.fakeKubermaticClient.KubermaticV1().Clusters().Get(cluster.Name, metav1.GetOptions{})
we could also issue a `GET` request to check if the token was updated.

2018-07-30 15:11 UTC, p0lyn0mial commented on api/pkg/handler/cluster_test.go
> +	req := httptest.NewRequest("GET", "/api/v1/projects/myProjectInternalName/dc/us-central1/clusters/"+cluster.Name+"/token", nil)
nit: I usually prefer to use `fmt.Sprintf` for formatting.

2018-07-30 15:11 UTC, p0lyn0mial commented on api/pkg/handler/cluster_test.go
> +	response := &apiv1.ClusterAdminToken{}
we could also use `compareWithResult` method for checking the output.

2018-07-30 15:11 UTC, p0lyn0mial commented on api/pkg/handler/cluster.go
> +		req := request.(ClusterAdminTokenReq)
What if the user actually set the token ? Do we want to signal that this is not the correct behaviour ? Just to avoid a situation when the user actually thinks it can control the content of the token.

2018-07-30 15:11 UTC, p0lyn0mial commented on api/pkg/handler/routes_v1.go
> +//     Revokes the current admin tokens and returns a newly generated one.
I think we can change `tokens` to `token`. There is only one token.

2018-07-30 15:16 UTC, p0lyn0mial commented on api/pkg/handler/cluster.go
> +		cluster.Address.AdminToken = fmt.Sprintf("%s.%s", rand.String(6), rand.String(16))
> If possible, I would extract the token check into a dedicated public function and just call that one (like pkg.validation.IsValidAdminToken() or something like that).

If the token generation is controlled by the controller itself then I think we don't have to validate the format of the token in API. We can relay on the test that the controller hopefully has :) Does it make sense ?

2018-07-30 15:31 UTC, xrstf commented on api/pkg/handler/cluster.go
> +		cluster.Address.AdminToken = fmt.Sprintf("%s.%s", rand.String(6), rand.String(16))
> in cluster controller

As a global function in its namespace or as an instance method for the Controller struct? The latter might make it hard to use the function, if the caller needs to build the controller first.

2018-07-30 15:33 UTC, xrstf commented on api/pkg/handler/cluster_test.go
> +	updatedCluster, err := clientsSets.fakeKubermaticClient.KubermaticV1().Clusters().Get(cluster.Name, metav1.GetOptions{})
Yes we could. I wasn't sure which is cleaner and decided for this variant because instrumenting another httptest mock seemed wrong (I don't want to test the cluster API after all). But I can change it if you want to.

2018-07-30 15:33 UTC, p0lyn0mial commented on api/pkg/handler/cluster.go
> +		cluster.Address.AdminToken = fmt.Sprintf("%s.%s", rand.String(6), rand.String(16))
I'd prefer to expose a method (global function). 
@mrIncompetent is that okay with you ?

2018-07-30 15:36 UTC, p0lyn0mial commented on api/pkg/handler/cluster_test.go
> +	updatedCluster, err := clientsSets.fakeKubermaticClient.KubermaticV1().Clusters().Get(cluster.Name, metav1.GetOptions{})
I think we don't have to instrument another mock, we should use an existing one otherwise it doesn't make sense. I think all we have to do is to create a new pair of `res` and `req`.

2018-07-30 15:39 UTC, xrstf commented on api/pkg/handler/cluster.go
> +		req := request.(ClusterAdminTokenReq)
Do we have other places in the API where we forbid extra fields in the request body? If not, I'd like to avoid having it here just in case someone for whatever reason sends a token. If / when we perform stuff like JSON schema checks against request bodies, then sure, let's forbid extra fields.

Just my 2 cents..

2018-07-30 15:41 UTC, xrstf commented on api/pkg/handler/cluster.go
> +		cluster.Address.AdminToken = fmt.Sprintf("%s.%s", rand.String(6), rand.String(16))
> Does it make sense ?

It does.

2018-07-30 15:46 UTC, xrstf commented on api/pkg/handler/cluster_test.go
> +	updatedCluster, err := clientsSets.fakeKubermaticClient.KubermaticV1().Clusters().Get(cluster.Name, metav1.GetOptions{})
But then I'd have to manually unmarshal the JSON, don't I? `compareWithResult` could get tedious, as the response is a complete cluster structure and I don't want to have such a large JSON blob defined inside the test. Plus the blob would have to be dynamic, because I don't know the generated token before revoking it.

Going through the API just seems to get rid of one unneccessary layer of JSON encoding/decoding.

2018-07-30 15:47 UTC, xrstf commented on api/pkg/handler/routes_v1.go
> +//     Revokes the current admin tokens and returns a newly generated one.
That's one of those cases where I wanted to save the file but my Ctrl key didn't register and we were left with a happy little accident ;-)

2018-07-30 19:38 UTC, mrIncompetent commented on api/cmd/kubermatic-api/swagger.json
> +      "put": {
We dont have a request body, right?
Should we rather use the DELETE method?

PUT means replacing a resource, which might be confusing. DELETE though could imply that the resource is gone and should stay deleted?
WDYT @xrstf

2018-07-30 19:38 UTC, mrIncompetent commented on api/cmd/kubermatic-api/swagger.json
> +      "put": {
Sorry for the drive-by :v:

2018-07-30 19:44 UTC, xrstf commented on api/cmd/kubermatic-api/swagger.json
> +      "put": {
I'm torn on this one. Revoking means deleting the old token and creating a new one, so neither PUT nor DELETE seem the best choices. I thought about breaking the REST contract and go with a RPC-style endpoint à la `POST /api/.../cluster/xy/token/revoke`. Another option would be to do a `PATCH /api/.../cluster/xy/token`, but that usually also carries a request payload.

In the end I don't think there's a perfect, non-convoluted solution. A pure REST solution would probably to elevate the revocation to be a resource in itself and perform a `POST /api/.../cluster/xy/token/revocations`, but really, who would benefit from that?

2018-07-31 06:48 UTC, p0lyn0mial commented on api/pkg/handler/cluster_test.go
> +	updatedCluster, err := clientsSets.fakeKubermaticClient.KubermaticV1().Clusters().Get(cluster.Name, metav1.GetOptions{})
yes, you have to parse JSON but I think only `ClusterAdminToken ` not the complete `cluster` structure. By doing so you operate on slightly different level ( HTTP responses), you don't have to you `fakeKubermaticClient`, isn't this something you wanted to avoid ? 

Just to be clear, I'm perfectly fine with what we have know :)

2018-07-31 07:08 UTC, p0lyn0mial commented on api/pkg/handler/cluster.go
> +		cluster.Address.AdminToken = fmt.Sprintf("%s.%s", rand.String(6), rand.String(16))
I spoke with @mrIncompetent  on slack, he suggested to move the function to the following package: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/kubernetes/helper.go

It would be nice if we could also update `cluster` controller. WDYT ?

2018-07-31 07:08 UTC, xrstf commented on api/pkg/handler/cluster_test.go
> +	updatedCluster, err := clientsSets.fakeKubermaticClient.KubermaticV1().Clusters().Get(cluster.Name, metav1.GetOptions{})
>  but I think only ClusterAdminToken not the complete cluster structure

How so? I'm fetching the entire cluster resource and not just the token (I'd like to avoid using one of my new endpoints for checking the token and rather use the existing API).

My original intention was something like "Okay, I've sent the request and got the result back, now do a quick SQL query to see if the database was really updated". That's why I wanted to avoid another HTTP request.

But I think we're just going in circles here :D We need a third opinion. What do you think @mrIncompetent ?

2018-07-31 07:09 UTC, xrstf commented on api/pkg/handler/cluster.go
> +		cluster.Address.AdminToken = fmt.Sprintf("%s.%s", rand.String(6), rand.String(16))
Sure we should update the cluster controller and probably all other spots where we're generating tokens right now. I'll do that.

2018-07-31 07:22 UTC, p0lyn0mial commented on api/pkg/handler/cluster_test.go
> +	updatedCluster, err := clientsSets.fakeKubermaticClient.KubermaticV1().Clusters().Get(cluster.Name, metav1.GetOptions{})
https://github.com/kubermatic/kubermatic/pull/1637 :P

2018-07-31 08:43 UTC, p0lyn0mial commented on api/pkg/handler/cluster.go
> +		req := request.(ClusterAdminTokenReq)
> Do we have other places in the API where we forbid extra fields in the request body?

I don't think so, I don't have strong opinion here just wanted to know yours.

2018-07-31 08:45 UTC, p0lyn0mial commented on api/pkg/controller/cluster/address.go
> +	"github.com/kubermatic/kubermatic/api/pkg/kubernetes"
nit: I would add an alias `kuberneteshelpers` just to highlight it is "utils" package.

2018-07-31 08:50 UTC, p0lyn0mial approved these changes

2018-07-31 12:06 UTC, xrstf commented on api/pkg/controller/cluster/address.go
> +	"github.com/kubermatic/kubermatic/api/pkg/kubernetes"
On the other hand, I would always tend to avoid custom aliases, because they usually force me to look them up when I'm reading a bit of code.

2018-08-01 19:22 UTC, mrIncompetent approved these changes

2018-08-02 06:54 UTC, merged