add a project-enabled cluster upgrade endpoint
kubermatic/kubermatic pull request #1629
Opened 2018-07-30 13:46 UTC by kdomanski

fixes #1554 

Release note:
```release-note
NONE
```

2018-07-30 15:32 UTC, p0lyn0mial requested changes

2018-07-30 15:32 UTC, p0lyn0mial commented on api/pkg/handler/routes_v3.go
> +	mux.Methods(http.MethodGet).
please move this method and the one previously added to `routes_v1.go`

2018-07-30 15:32 UTC, p0lyn0mial commented on api/pkg/handler/upgrade.go
>  	"github.com/go-kit/kit/endpoint"
nit: add an empty line (this is how we group imports)

2018-08-02 10:19 UTC, p0lyn0mial requested changes

2018-08-02 10:19 UTC, p0lyn0mial commented on api/pkg/handler/upgrade.go
> +	"github.com/go-kit/kit/endpoint"
grouping :)

2018-08-02 10:20 UTC, p0lyn0mial commented on api/vendor/github.com/kubermatic/machine-controller/pkg/client/clientset/versioned/typed/machines/v1alpha1/fake/fake_machineset.go
> +Copyright 2017 The Kubernetes Authors.
why this file has been added ?

2018-08-02 10:22 UTC, p0lyn0mial commented on api/vendor/github.com/kubermatic/machine-controller/pkg/client/clientset/versioned/typed/machines/v1alpha1/fake/fake_machineset.go
> +Copyright 2017 The Kubernetes Authors.
because I don't see any new imports.

2018-08-02 11:30 UTC, kdomanski commented on api/pkg/handler/upgrade.go
> +	"github.com/go-kit/kit/endpoint"
What about it now? Order?

2018-08-02 11:35 UTC, kdomanski commented on api/vendor/github.com/kubermatic/machine-controller/pkg/client/clientset/versioned/typed/machines/v1alpha1/fake/fake_machineset.go
> +Copyright 2017 The Kubernetes Authors.
Don't know, don't care. This directory is managed by `dep`

2018-08-02 11:44 UTC, p0lyn0mial commented on api/pkg/handler/upgrade.go
> +	"github.com/go-kit/kit/endpoint"
yes, @kdomanski , we group our imports in all packages not only in those api related 

for the reference see https://github.com/kubermatic/kubermatic/blob/master/api/pkg/provider/kubernetes/rbac-compliant-ssh.go#L3

2018-08-02 14:02 UTC, p0lyn0mial commented on api/pkg/handler/upgrade.go
> +	"github.com/go-kit/kit/endpoint"
we group imports in the following order
```
golang's std pkgs

any others pkgs

kubermatic pkgs

kubernetes pkgs
```

so please update the imports so that they look like this:

```
"context"
"fmt"

"github.com/go-kit/kit/endpoint"

apiv1 "github.com/kubermatic/kubermatic/api/pkg/api/v1"
kubermaticapiv1 "github.com/kubermatic/kubermatic/api/pkg/crd/kubermatic/v1"
"github.com/kubermatic/kubermatic/api/pkg/provider"
"github.com/kubermatic/kubermatic/api/pkg/util/errors"
	
kerrors "k8s.io/apimachinery/pkg/api/errors"
```

2018-08-02 14:17 UTC, p0lyn0mial approved these changes

2018-08-02 14:38 UTC, mrIncompetent approved these changes

2018-08-02 14:39 UTC, merged