user-cluster-controller proposal.
kubermatic/kubermatic pull request #1727
Opened 2018-08-09 12:28 UTC by thz

**What this PR does / why we need it**:

related: #1706 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2018-08-09 13:50 UTC, thz commented
@mrIncompetent ping, please have a look and comment about missing facts and to-think-abouts.

2018-08-10 09:43 UTC, mrIncompetent commented on docs/proposals/user-cluster-resource-controller.md
> +The envisioned improvement is to create a UserClusterResourceController similar to the ClusterController in the seed cluster. CLARIFICATION-NEEDED: The UserClusterResourceController will run in the u
Should be running inside the cluster-namespace.
Otherwise, we have a chicken-egg problem.

It creates relevant RBAC rules needed for the node-bootstrap process. Without, nodes will never come up and never schedule pod

2018-08-10 09:48 UTC, mrIncompetent commented on docs/proposals/user-cluster-resource-controller.md
> +VISION-UNCLEAR: It is possible to make the distinction between optional and mandatory resources and even implement the addon-handling inside the UserClusterResourceController.
I'm not sure here.
I would prefer to let the `UserClusterResourceController` exclusively talk to the user-cluster (Including informers, listers, etc.)
Using it for addons would mean, that it also has to have access to the seed-cluster, as `Addon` resources live inside the cluster-namespace.

cc @alvaroaleman

2018-08-10 12:02 UTC, alvaroaleman commented on docs/proposals/user-cluster-resource-controller.md
> +VISION-UNCLEAR: It is possible to make the distinction between optional and mandatory resources and even implement the addon-handling inside the UserClusterResourceController.
I agree on the let it exclusively talk to the user-cluster part.

Is there a reason thought why we can't have the addons inside the user-cluster?

2018-08-13 13:27 UTC, mrIncompetent commented on docs/proposals/user-cluster-resource-controller.md
> +VISION-UNCLEAR: It is possible to make the distinction between optional and mandatory resources and even implement the addon-handling inside the UserClusterResourceController.
Based on the recent change on the default PropagationPolicy on `kubectl delete` i would instead move in the other direction.
So leaving the Addons on the seed-cluster and move Machines into it as well.

2018-08-13 13:28 UTC, mrIncompetent commented on docs/proposals/user-cluster-resource-controller.md
> +VISION-UNCLEAR: It is possible to make the distinction between optional and mandatory resources and even implement the addon-handling inside the UserClusterResourceController.
We would follow the upstream Cluster-API way of doing it, so storing those CRD's outside the user-cluster.
We could still offer a "proxy" extension API server to enable users to play around with machines. But they will always be stored inside the seed-cluster

2018-08-14 10:19 UTC, mrIncompetent commented on docs/proposals/user-cluster-resource-controller.md
> +	* add to kubermatic-controller-manager
I would rather deploy it into each user-cluster namespace. Then it would not make sense to add it to the controller-manager

2018-08-14 10:20 UTC, mrIncompetent commented on docs/proposals/user-cluster-resource-controller.md
> +	* add to kubermatic-controller-manager
Otherwise we would need to dynamically create Informers/Listers

2018-08-14 10:57 UTC, alvaroaleman requested changes

2018-08-14 10:57 UTC, alvaroaleman commented on docs/proposals/user-cluster-resource-controller.md
> +This is about resources inside the user clusters. Currently resources are created the following places:
Can we not use the term `resources` here, as its ambigious with `pod.spec.containers.resources`? I first thought this proposal was about a controller that dynamically adjusts those

maybe just `user-cluster-controller-manager`?

2018-08-14 10:57 UTC, alvaroaleman commented on docs/proposals/user-cluster-resource-controller.md
> +The following master components are running in a cluster-xyz namespace in the seed cluster:
How is this relevant?

2018-08-14 10:57 UTC, alvaroaleman commented on docs/proposals/user-cluster-resource-controller.md
> +Most user resources are currently created as addons by the AddonManager. The list of addons which are installed by default can be changed on kubermatic level (values.yaml). Also addons can be changed
You are describing a problem here, not a solution. Please describe the solution without going into implementation details. Please also describe the exact scope and the non-scope of the solutions (The latter is I guess e.G. everything thats running in the seed cluster)

2018-08-14 10:57 UTC, alvaroaleman commented on docs/proposals/user-cluster-resource-controller.md
> +Most user resources are currently created as addons by the AddonManager. The list of addons which are installed by default can be changed on kubermatic level (values.yaml). Also addons can be changed
Also, please do not only describe how it is wrong `[...]which is just another abuse`, but instead the desired state

2018-08-14 10:57 UTC, alvaroaleman commented on docs/proposals/user-cluster-resource-controller.md
> +The envisioned improvement is to create a UserClusterResourceController similar to the ClusterController in the seed cluster. The UserClusterResourceController will run in cluster-namespace too.
How is it similiar to the `clusterController`? Just because its a controller and because it creates kube thingys? Thats way too broad of a description

2018-08-14 10:57 UTC, alvaroaleman commented on docs/proposals/user-cluster-resource-controller.md
> +The UserClusterResourceController will do reconciliation like the ClusterController does. This allows for more flexible resource management.
All controllers do, this is a useless information

2018-08-14 10:57 UTC, alvaroaleman commented on docs/proposals/user-cluster-resource-controller.md
> +The UserClusterResourceController will be able to control resources in the user-cluster (example: metrics-server) by talking to the apiserver and it will be controlling resources in the cluster-names
That is also implicit by the fact that it is a controller. Please describe instead on what types it will act and if you write `apiserver` please specify which apiserver

2018-08-14 10:57 UTC, alvaroaleman commented on docs/proposals/user-cluster-resource-controller.md
> +	* add to kubermatic-controller-manager
I would make this the starting point for a user-cluster-controller manager

2018-08-14 10:57 UTC, alvaroaleman commented on docs/proposals/user-cluster-resource-controller.md
> +	* add to kubermatic-controller-manager
We could also add another controller into that controller manager that does the default rbac thingy required, e.G. for machine-controller

2018-08-14 10:59 UTC, alvaroaleman commented
As a sidenote that has nothing to do with the actual proposal: Maybe this is a good example to try out if using [kubebuilder](https://book.kubebuilder.io/) makes writing controllers easier?

2018-08-15 10:55 UTC, thz commented on docs/proposals/user-cluster-resource-controller.md
> +	* add to kubermatic-controller-manager
Agreed on the user-cluster-controller-manager starting point. The user-cluster-controller will be its first controller then.

But I do not see how the rbac resources are different to justify their own controller.

2018-08-15 10:57 UTC, thz commented on docs/proposals/user-cluster-resource-controller.md
> +This is about resources inside the user clusters. Currently resources are created the following places:
You mean `user-cluster-controller` (which is then manged/created by `user-cluster-controller-manager`), right?
Agreed then.

2018-08-15 11:03 UTC, thz commented on docs/proposals/user-cluster-resource-controller.md
> +The following master components are running in a cluster-xyz namespace in the seed cluster:
Indeed too much of a background here as none of them are in question to ever run in user-cluster.

2018-08-15 11:24 UTC, thz commented on docs/proposals/user-cluster-resource-controller.md
> +Most user resources are currently created as addons by the AddonManager. The list of addons which are installed by default can be changed on kubermatic level (values.yaml). Also addons can be changed
I was describing the problem because I see it as the motivation for this proposal. I reworded with a bit more stressing of the desired state.

2018-08-16 08:42 UTC, alvaroaleman submitted a review, later dismissed

2018-08-16 08:42 UTC, alvaroaleman commented on docs/proposals/user-cluster-controller.md
> +The envisioned improvement is started by establishing a user-cluster-controller-manager created within the (seed's) cluster-controller. The manager will create a user-cluster-controller inside the cl
Not `created within` but `created by`

2018-08-16 10:02 UTC, thz commented on docs/proposals/user-cluster-controller.md
> +The envisioned improvement is started by establishing a user-cluster-controller-manager created within the (seed's) cluster-controller. The manager will create a user-cluster-controller inside the cl
True. Fixed.

2018-08-16 10:42 UTC, alvaroaleman approved these changes

2018-08-16 11:53 UTC, merged