combine ca secrets
kubermatic/kubermatic pull request #1732
Opened 2018-08-09 16:54 UTC by mrIncompetent

**What this PR does / why we need it**:
Combine ca secrets

**Release note**:
```release-note
Combine the two existing CA secrets into a single one
```

2018-08-09 18:44 UTC, alvaroaleman requested changes
Please use `/etc/kubernetes/pki` instead of `/etc/kubernetes/ca` as mountPath in the various components, other than that LGTM

2018-08-09 18:44 UTC, alvaroaleman commented on api/pkg/resources/controllermanager/deployment.go
> +			MountPath: "/etc/kubernetes/ca",
What about using `/etc/kubernetes/pki` here like kubeadm does?

2018-08-09 19:03 UTC, thz commented on api/pkg/resources/controllermanager/deployment.go
> +			MountPath: "/etc/kubernetes/ca",
Wouldn't `/etc/kubernetes/pki/ca` be better? Where would we mount other keys like client-certs?

2018-08-09 19:14 UTC, alvaroaleman commented on api/pkg/resources/controllermanager/deployment.go
> +			MountPath: "/etc/kubernetes/ca",
Good point, and good suggestion

2018-08-10 08:27 UTC, mrIncompetent commented on api/pkg/resources/controllermanager/deployment.go
> +			MountPath: "/etc/kubernetes/ca",
Done

2018-08-10 08:27 UTC, mrIncompetent commented
@alvaroaleman PTAL

2018-08-10 08:42 UTC, alvaroaleman requested changes

2018-08-10 08:42 UTC, alvaroaleman commented on api/pkg/resources/etcd/statefulset.go
> -					Name:      resources.CACertSecretName,
This one is not updated, would be nice if we had it consistent

2018-08-10 09:24 UTC, alvaroaleman submitted a review, later dismissed

2018-08-10 09:35 UTC, alvaroaleman approved these changes

2018-08-10 09:37 UTC, merged