adds migration tool to projects
kubermatic/kubermatic pull request #1745
Opened 2018-08-13 10:21 UTC by p0lyn0mial

**What this PR does / why we need it**:

The purpose of this tool is to find all running clusters and group them by the user they belong to.
Similarly with ssh keys that are being used by the clusters.
For each user the tool creates a default project and starts the migration process by updating the existing resources.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
See also #1556 

**Special notes for your reviewer**:
The tool can produce the following output:
```
I0813 11:25:11.668654   18159 main.go:69] Skipping adding europe-west3-c as a seed cluster. It is exactly the same as existing kubernetes master client
I0813 11:25:11.669711   18159 main.go:123] STEP 1: getting the list of clusters that needs to be migrated
I0813 11:25:11.849213   18159 main.go:426] ==================================================================================================
I0813 11:25:11.849758   18159 main.go:427] clusters that will be migrated for user with ID = CggyMTMwNDE1MRIGZ2l0aHVi:
I0813 11:25:11.850020   18159 main.go:428] ==================================================================================================
I0813 11:25:11.850216   18159 main.go:430]   there are 1 clusters resources in "master" cluster (physical location)
I0813 11:25:11.850430   18159 main.go:432]    1. name = 64mfgpr48k
I0813 11:25:11.850587   18159 main.go:132] STEP 2: getting the list of users that own the clusters
I0813 11:25:11.892918   18159 main.go:164] adding the user with ID = user-ncrc7 (CggyMTMwNDE1MRIGZ2l0aHVi) and name = Lukasz Szaszkiewicz to the list 
I0813 11:25:11.893658   18159 main.go:173] STEP 3: creating a default project for each user if not already exists
I0813 11:25:11.922457   18159 main.go:192] the userID = CggyMTMwNDE1MRIGZ2l0aHVi already has a project (ID = ql85r2rw2x, Name = important-project)
I0813 11:25:11.922485   18159 main.go:250] STEP 4: getting the list of ssh keys that are being used by a cluster
I0813 11:25:11.989698   18159 main.go:275] skipping the following ssh keys (ID = key-046bbb224871fb60c5f626025146e5fe-w3yk, Name = guus@guus-XPS-13-9360) as it is not being used by any cluster
I0813 11:25:11.989732   18159 main.go:275] skipping the following ssh keys (ID = key-185cbb46323286801c54cc14851f301e-8z3n, Name = kamil@vanguard) as it is not being used by any cluster
I0813 11:25:11.989739   18159 main.go:275] skipping the following ssh keys (ID = key-1d2e034c9c51457f2f32f3eefc6bf98e-jpd7, Name = pat) as it is not being used by any cluster
I0813 11:25:11.989746   18159 main.go:275] skipping the following ssh keys (ID = key-1f64e0482ec69ea0b209e6ee054afe25-2rqq, Name = igor.komlew@loodse.com) as it is not being used by any cluster
I0813 11:25:11.989752   18159 main.go:275] skipping the following ssh keys (ID = key-1f64e0482ec69ea0b209e6ee054afe25-ez97, Name = igor.komlew@loodse.com) as it is not being used by any cluster
I0813 11:25:11.989758   18159 main.go:275] skipping the following ssh keys (ID = key-1f64e0482ec69ea0b209e6ee054afe25-mi2c, Name = igor.komlew2@loodse.com) as it is not being used by any cluster
I0813 11:25:11.989764   18159 main.go:275] skipping the following ssh keys (ID = key-232ba66f06db4e04fd41ca9998f94130-030v, Name = Alvaro Aleman <alv2412@gmail.com>) as it is not being used by any cluster
I0813 11:25:11.989815   18159 main.go:275] skipping the following ssh keys (ID = key-50e6fae79e2026c488ed2350d96d37cc-pl2q, Name = xrstf2015) as it is not being used by any cluster
I0813 11:25:11.989821   18159 main.go:275] skipping the following ssh keys (ID = key-5542e81fe097ee2368008162795f4eb7-em1o, Name = igor.komlew@gmail.com) as it is not being used by any cluster
I0813 11:25:11.989827   18159 main.go:275] skipping the following ssh keys (ID = key-5f1f92f5c5e9292edc8c637a5a1df83b-km83, Name = simon) as it is not being used by any cluster
W0813 11:25:11.989832   18159 main.go:259] cannot migrate the following ssh key (ID = key-8036218bef587f8230dad6426099da14-c7i4, Name = test), because it doesn't have an owner
W0813 11:25:11.989837   18159 main.go:259] cannot migrate the following ssh key (ID = key-8036218bef587f8230dad6426099da14-wwk5, Name = zest), because it doesn't have an owner
I0813 11:25:11.989846   18159 main.go:275] skipping the following ssh keys (ID = key-80ba7a3b3f89b1b4cdb8b4fb6ca462d0-2rs3, Name = Sebastian) as it is not being used by any cluster
I0813 11:25:11.989851   18159 main.go:275] skipping the following ssh keys (ID = key-941284d9428d6d39c48c3435e101e535-b78x, Name = kron@kron.local) as it is not being used by any cluster
I0813 11:25:11.989857   18159 main.go:275] skipping the following ssh keys (ID = key-9faa50ec30cb2f23a3c68ccda58bb435-eb09, Name = thz@cardno:000604915268) as it is not being used by any cluster
I0813 11:25:11.989862   18159 main.go:275] skipping the following ssh keys (ID = key-9faa50ec30cb2f23a3c68ccda58bb435-rwgl, Name = thz@cardno:000604915268) as it is not being used by any cluster
I0813 11:25:11.989871   18159 main.go:275] skipping the following ssh keys (ID = key-a37b8a6841c7824599b5714280264512-zoo6, Name = tobi-ssh) as it is not being used by any cluster
I0813 11:25:11.989876   18159 main.go:275] skipping the following ssh keys (ID = key-b5eeae012ac9cd22b12740a3ad21bf37-6qj3, Name = webcrypto) as it is not being used by any cluster
W0813 11:25:11.989881   18159 main.go:259] cannot migrate the following ssh key (ID = key-c08aa5c7abf34504f18552846485267d-5bu2, Name = vmOnePubKey), because it doesn't have an owner
I0813 11:25:11.989886   18159 main.go:275] skipping the following ssh keys (ID = key-c08aa5c7abf34504f18552846485267d-9kk6, Name = my_pub_key) as it is not being used by any cluster
I0813 11:25:11.989892   18159 main.go:265] skipping the following ssh keys (ID = key-c08aa5c7abf34504f18552846485267d-sqj1, Name = lukaszvm_id_rsa_temporary_digital) as it already belongs to project = ql85r2rw2x
I0813 11:25:11.989937   18159 main.go:275] skipping the following ssh keys (ID = key-c08aa5c7abf34504f18552846485267d-yafn, Name = pub_key) as it is not being used by any cluster
I0813 11:25:11.989948   18159 main.go:275] skipping the following ssh keys (ID = key-ccad30a4f116904f2b3e8224b4bf39a0-05j6, Name = rsa-key-20180110-3) as it is not being used by any cluster
I0813 11:25:11.989954   18159 main.go:275] skipping the following ssh keys (ID = key-ccad30a4f116904f2b3e8224b4bf39a0-7l01, Name = rsa-key-20180110) as it is not being used by any cluster
I0813 11:25:11.989959   18159 main.go:275] skipping the following ssh keys (ID = key-ccad30a4f116904f2b3e8224b4bf39a0-9r5e, Name = rsa-key-20180110-1) as it is not being used by any cluster
I0813 11:25:11.989964   18159 main.go:275] skipping the following ssh keys (ID = key-ccad30a4f116904f2b3e8224b4bf39a0-k40e, Name = rsa-key-20180110-4) as it is not being used by any cluster
I0813 11:25:11.989969   18159 main.go:275] skipping the following ssh keys (ID = key-ccad30a4f116904f2b3e8224b4bf39a0-s8tc, Name = rsa-key-20180110-2) as it is not being used by any cluster
I0813 11:25:11.989975   18159 main.go:275] skipping the following ssh keys (ID = key-ddc1431afecb9c3f482078c8fecfd5a8-fvk0, Name = henrik@loodse.com) as it is not being used by any cluster
I0813 11:25:11.989980   18159 main.go:275] skipping the following ssh keys (ID = key-e65c136bf74eb30647759658c78f73cf-nqn0, Name = tesdgh) as it is not being used by any cluster
I0813 11:25:11.989987   18159 main.go:284] STEP 5: migrating cluster resources
I0813 11:25:11.989996   18159 main.go:305] the cluster resource (Name = 64mfgpr48k) for userID = CggyMTMwNDE1MRIGZ2l0aHVi was NOT migrated because dry-run option was requested, physical location = master
I0813 11:25:11.990004   18159 main.go:315] STEP 6: migrating ssh keys
```

**Release note**:

```release-note
NONE
```

2018-08-13 10:22 UTC, p0lyn0mial commented on api/cmd/projects-migrator/main.go
> +	//          for example on dev environment: user-lknc7, user-n45j9, user-z9s20j
we have duplicated users in our system :(

2018-08-13 13:19 UTC, mrIncompetent commented on api/cmd/projects-migrator/main.go
> +			// take only the keys that are being used by a cluster
What will happen for all ssh-keys which are not assigned to a cluster?
Are those gone/not-useable then?

2018-08-13 13:21 UTC, mrIncompetent commented on api/cmd/projects-migrator/main.go
> +// Next we create a default project for the users and start the migration process by updating the existing resources.
Do we only create a default project for users which have a cluster?

2018-08-13 13:31 UTC, p0lyn0mial commented on api/cmd/projects-migrator/main.go
> +			// take only the keys that are being used by a cluster
there will be `phase 2` that will migrate the remaining keys but only for the projects owners.  

see:
https://github.com/kubermatic/kubermatic/pull/1745/files#diff-868e0c7534ae5552c6b6cb3fb3e1e1a4R97

2018-08-13 13:32 UTC, p0lyn0mial commented on api/cmd/projects-migrator/main.go
> +// Next we create a default project for the users and start the migration process by updating the existing resources.
yes

2018-08-13 13:46 UTC, p0lyn0mial commented on api/cmd/projects-migrator/main.go
> +	//          for example on dev environment: user-lknc7, user-n45j9, user-z9s20j
This is quite serious because we look up the users by `email` and this means that each time we can work with a different instance of the user resource. But I think this was generated manually, our system will not allow for this.

2018-08-14 07:48 UTC, mrIncompetent commented on api/cmd/projects-migrator/main.go
> +	//          for example on dev environment: user-lknc7, user-n45j9, user-z9s20j
The `userSaverMiddleware` does a lookup by email address. So i think that should be fine.

@p0lyn0mial can you validate after this PR if we have a guarantee that the JWT token always contains the email address? Or does this depends on the provider?

2018-08-14 07:51 UTC, mrIncompetent commented on api/cmd/projects-migrator/main.go
> +	//         this step essentially breaks backward compatibility and prevents the old clients (dashboard) from finding the resources.
Can we postpone that step to the release after the one which contains the user-management?
In case we need to do a rollback

2018-08-14 07:58 UTC, mrIncompetent submitted a review, later dismissed

2018-08-14 08:53 UTC, p0lyn0mial commented on api/cmd/projects-migrator/main.go
> +	//          for example on dev environment: user-lknc7, user-n45j9, user-z9s20j
will do.

2018-08-14 08:54 UTC, p0lyn0mial commented on api/cmd/projects-migrator/main.go
> +	//         this step essentially breaks backward compatibility and prevents the old clients (dashboard) from finding the resources.
sure, good idea.

2018-08-14 08:56 UTC, p0lyn0mial commented
@alvaroaleman PTAL another set of eyes wouldn't hurt.

2018-08-14 10:44 UTC, alvaroaleman requested changes

2018-08-14 10:44 UTC, alvaroaleman commented on api/cmd/projects-migrator/main.go
> +		return nil
This should be `return err`, right?

2018-08-14 10:44 UTC, alvaroaleman commented on api/cmd/projects-migrator/main.go
> +		defaultProjectName := "competent-pike"
Maybe it would make more sense to actually name it `default`? A project is not as ephemeral as a cluster I suppose

2018-08-14 14:06 UTC, p0lyn0mial commented on api/cmd/projects-migrator/main.go
> +		return nil
ups, thx !

2018-08-14 14:07 UTC, p0lyn0mial commented on api/cmd/projects-migrator/main.go
> +		defaultProjectName := "competent-pike"
`default` is boring, but I think you are right, it looks more informative. Will change the name.

2018-08-14 14:46 UTC, p0lyn0mial commented
comments addressed, PTAL

2018-08-14 14:47 UTC, p0lyn0mial commented on api/cmd/projects-migrator/main.go
> +	//          for example on dev environment: user-lknc7, user-n45j9, user-z9s20j
This pull makes sure that the email address will not empty.

https://github.com/kubermatic/kubermatic/pull/1765

2018-08-14 14:48 UTC, mrIncompetent approved these changes

2018-08-14 15:29 UTC, alvaroaleman approved these changes

2018-08-16 06:15 UTC, merged