IAP for system services
kubermatic/kubermatic pull request #1808
Opened 2018-08-17 12:32 UTC by kron4eg

**What this PR does / why we need it**:
Protect system resources during outside access with OIDC

**Special notes for your reviewer**:

**Documentation**:
https://github.com/kubermatic/docs/pull/61

**Release note**:
```release-note
Breaking change: basic auth for kibana/grafana/prometheus/alertmanager replaced with oAuth
```

2018-08-21 10:52 UTC, mrIncompetent commented
Please set the PR description according to the template

2018-08-21 11:02 UTC, mrIncompetent requested changes

2018-08-21 11:02 UTC, mrIncompetent commented on config/iap/templates/deployments.yaml
> +    target: {{ .name }}
Do we need all of this?
Our charts so far have been fairly minimal with focus on simplicity

2018-08-21 11:02 UTC, mrIncompetent commented on config/iap/templates/deployments.yaml
> +  replicas: 1
Should be configurable

2018-08-21 11:02 UTC, mrIncompetent commented on config/iap/templates/_helpers.tpl
> +{{- end -}}
Do we need all of this?
Our charts so far have been fairly minimal with focus on simplicity

2018-08-21 11:02 UTC, mrIncompetent commented on config/iap/templates/ingresses.yaml
> +    target: {{ .name }}
Do we need all of this?
Our charts so far have been fairly minimal with focus on simplicity

2018-08-21 11:02 UTC, mrIncompetent commented on config/iap/templates/services.yaml
> +    target: {{ .name }}
Do we need all of this?
Our charts so far have been fairly minimal with focus on simplicity

2018-08-21 11:02 UTC, mrIncompetent commented on config/monitoring/alertmanager/values.yaml
> +  version: v0.15.2
Should be done in a dedicated PR

2018-08-21 11:03 UTC, mrIncompetent commented
Documentation PR is missing

2018-08-21 11:16 UTC, pkavajin commented on config/iap/templates/deployments.yaml
> +    heritage: {{ $.Release.Service }}
Why do these labels have to specified manually? Shouldnt helm do it on itself?

2018-08-21 12:43 UTC, kron4eg commented on config/iap/templates/deployments.yaml
> +    heritage: {{ $.Release.Service }}
nope, it's helm convention, have to provide them manually

2018-08-21 12:46 UTC, kron4eg commented on config/iap/templates/deployments.yaml
> +  replicas: 1
I'm not sure if it's possible (and have any sense). By default keycloack-proxy maintain it's state (tokens) in-memory boltdb. To have `replicas >1`, we'd need a redis to save tokens there, which I've avoided. Also system services like those wouldn't experience huge loads on them.

2018-08-21 13:58 UTC, kron4eg commented
@mrIncompetent all fixed

2018-08-22 08:18 UTC, mrIncompetent commented
@kron4eg 
PR looks good!
Could you write down the steps needed for us to limit access to our Github org?
So we don't expose all those on cloud.kubermatic.io to everyone

2018-08-22 08:53 UTC, pkavajin submitted a review, later dismissed

2018-08-22 10:08 UTC, kron4eg commented
@mrIncompetent that's very good question :)

By looking at the docs I see that we would need to use combination of dex and keycloak-proxy configs.

on keycloak-proxy side:
* `--scopes=groups+federated:id` (ask dex to supply custom claim to the answer token)
* `--match-claims=federated_claims:connector_id=internal_github`
* `--match-claims=groups=kubermatic:developers` (optional)
* `--resources "uri=/*|groups=kubermatic:developers"` (optional and alternative to previous match-claim)

on dex side:
* add connector type github, but with ID `internal_github`, which will require
```
      orgs:
      - name: kubermatic
```

2018-08-22 10:09 UTC, kron4eg commented
such stunt however will require supporting (via values.yaml) additional flags for keycloack-proxy, and thus require changing this PR

2018-08-23 16:13 UTC, kron4eg commented
@mrIncompetent so here is combination that I've got working

```
scopes:
- "groups"
resources:
- uri: "/*"
  groups:
  - "mygithuborg:dev"
```

And it restricts access to that one organization, even though dex itself can permit everyone from github. But we will need second `internal_github` anyway, since dex is not supplying groups clams if orgs are not specified in dex's connector config

2018-08-24 11:54 UTC, kron4eg commented
@mrIncompetent currently keycloak-proxy is unable to match claims that are hashmaps (like dex issuing). I've opened upstream issue for this: 
https://github.com/gambol99/keycloak-proxy/issues/413

2018-08-31 09:26 UTC, xrstf commented on config/monitoring/grafana/config/grafana.ini
>  [security]
Why do we still need to configure username and password if the login form and basic auth are disabled?

2018-08-31 09:27 UTC, pkavajin commented on config/monitoring/grafana/values.yaml
>    user: YWRtaW4= # admin
isnt that obsolete now by oauth identities?

2018-08-31 10:15 UTC, xrstf commented on config/monitoring/grafana/config/grafana.ini
>  [security]
> for backward compatibility
> I’m going to remove it after full IAP deployment

2018-08-31 10:15 UTC, xrstf submitted a review, later dismissed
LGTM

2018-08-31 10:35 UTC, pkavajin submitted a review, later dismissed

2018-08-31 12:43 UTC, mrIncompetent submitted a review, later dismissed

2018-09-03 12:37 UTC, mrIncompetent approved these changes

2018-09-04 12:19 UTC, merged