Add DNAT sidecar for node-access (seed)
kubermatic/kubermatic pull request #1817
Opened 2018-08-20 12:54 UTC by thz

**What this PR does / why we need it**:

This adds a cmd to be run in a sidecar. It monitors node-addresses and adds destination network address translation (DNAT) rules to the kernel.
This is to be run as a sidecar next to the vpn-client sidecar and enforces connections made to node addresses to go through the VPN.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1691 

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
Add a controller which steers control plane traffic to the kubelets via VPN. 
```

2018-08-20 17:09 UTC, thz commented
@mrIncompetent PTAL

2018-08-21 15:58 UTC, thz commented
updated, PTAL @mrIncompetent

2018-08-21 23:19 UTC, thz commented
ping @mrIncompetent, updated, two new things to look at:
* move to pkg/controller 1a6160fe9ffdfc183a432e77e9c60f3860baba34
* some simplification and fixing of the actual rules after testing 677680d84e2e7367be9d3834f31e4e018ab52af1 (now the rules are even working!)

2018-08-23 12:04 UTC, alvaroaleman requested changes

2018-08-23 12:04 UTC, alvaroaleman commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +	if ctrl.queue.NumRequeues(key) < 5 {
Naive question, I know we have this at other places as well, but why? The `addRatelimited` ensures the delay will get higher, why do we stop after five tries?

2018-08-23 12:04 UTC, alvaroaleman commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +		return 0, string(out), nil
I  must say I do not really find it idiomatic to pass a return code in addition to an error

2018-08-23 12:04 UTC, alvaroaleman commented on api/cmd/kubeletdnat-controller/main.go
> +	networkFlag := flag.String("node-access-network", "", "Node-Access-Network to translate to.")
English has no compound substantives, that's a German thingy. Can you add a `( OpenVPN CiDR range)` or something in the description? I first thought this was the CIDR range that contains the node addresses and was pretty confused

2018-08-23 12:04 UTC, alvaroaleman commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +			[]string{"-t", "nat", "-I", "OUTPUT", "-j",
Why can't this and the masquerade rule not be created via `applyRules`? This would also remove the special case handling we currently have for those

2018-08-23 12:04 UTC, alvaroaleman commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +func (ctrl *Controller) syncDnatRules(key string) error {
I would really like to see some unit testing for this (And I rarely ask for unit tests) that just create `iptables-save` fixtures for node objects, e.G. by adding a `test` boolean into the controller that when set will not execute `iptables-restore` in the apply but instead write the rules to a fixture file

2018-08-23 12:20 UTC, mrIncompetent commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +	if ctrl.queue.NumRequeues(key) < 5 {
good question. @alvaroaleman would you mind creating an issue to fix this accross all controllers?

2018-08-23 12:21 UTC, mrIncompetent commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +func (ctrl *Controller) syncDnatRules(key string) error {
I would prefer separating the logic to generate the rules from the part which applies the rules.
That way we don't have to introduce test-only logic - which always makes me cringe

2018-08-23 12:29 UTC, mrIncompetent commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +	for ctrl.processNextItem() {
We could introduce a sleep of 1 second here.
It would "group" all events of a resync probably & reduce the load.

The queue does deduplication & we always put in the same string into the queue

2018-08-23 17:34 UTC, thz commented on api/cmd/kubeletdnat-controller/main.go
> +	networkFlag := flag.String("node-access-network", "", "Node-Access-Network to translate to.")
Agreed on the language fix. But the `node-access-network` flag is established with that name in controller-manager already. So we can change all occurances after this PR if we want to.

2018-08-23 17:38 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +		return 0, string(out), nil
It is not an exported function, and:
There is the use-case where iptables command is used to check existence of a rule in kernel. The return code is zero when the rule exists and non-zero if it is not. The error is needed to check for real errors (like failure to execute iptables command).

2018-08-23 17:39 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +		return 0, string(out), nil
I must admit I am no longer using that feature and removed the `Check()` function. So without the need I could indeed remove the return code from the function. Still feels valid, though.

2018-08-23 17:59 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +			[]string{"-t", "nat", "-I", "OUTPUT", "-j",
`applyRules` uses the `iptables-restore` command to replace the whole dedicated iptables chain (no previous rules are kept). This is idempotent. We "own" the whole chain. `createRule` adds a rule without touching pre-existing rules. This is  not idempotent and thus the checks are necessary.

2018-08-23 18:07 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +func (ctrl *Controller) syncDnatRules(key string) error {
Except for the jump and masquerade rules (which are static and not generated) the separation of rule generation is easy and actually almost there. The `desiredRules` variable holds the full set of rules and is generated before any apply happens. That could be better encapsulated in a function which is then used by some test.

2018-08-23 18:09 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +	for ctrl.processNextItem() {
Oh, yes. Very good!

2018-08-23 18:16 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +	for ctrl.processNextItem() {
I would even say that waiting for 15 seconds should be fair. Removing rules is not time-critical at all. For adding nodes there is a wait in the area of minutes anyways and the rules are again not critical for cluster bootstrapping. From my log observations: the longer delay would cancel-out an order of magnitude more syncs. Opinion, @mrIncompetent ?

2018-08-23 18:37 UTC, alvaroaleman commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +		return 0, string(out), nil
I heard rumours there are some hipsters that use this thingy called "Boolean" to indicate which of two possible states there is :)

2018-08-23 18:42 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +		return 0, string(out), nil
Same guys run into problems with the 3 possible exit codes iptables has to offer ;-)
I'll remove the return code from the signature.

2018-08-23 18:46 UTC, alvaroaleman commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +	if ctrl.queue.NumRequeues(key) < 5 {
Done: https://github.com/kubermatic/kubermatic/issues/1851

2018-08-24 07:45 UTC, alvaroaleman commented
@thz BTW, please add a release note

2018-08-24 07:49 UTC, alvaroaleman commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +		UpdateFunc: func(_, newObj interface{}) { ctrl.enqueue(newObj.(*corev1.Node)) },
Personally, I'd prefer it if the `UpdateFunc` looked something like this:

`func(old, new interface{}) { if old.status.Addresses != new.status.Addresses { enq(constKey)}` and in addition to that have a goroutine running that does a simple `for { sleep resyncInterval; enq(constKey) }` because we can not use the bultin resync as:

* The five minute interval we have globally in the SharedInformer may not be appropriate
* The Resync from the informer triggers the `UpdateFunc` with two identical objects, meaning the above mentioned func will prevent it from getting enqd

Instead of using a sleep in the `RunWorker`. But I think @mrIncompetent disagrees

2018-08-24 12:22 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +		UpdateFunc: func(_, newObj interface{}) { ctrl.enqueue(newObj.(*corev1.Node)) },
@mrIncompetent ping.

2018-08-24 12:25 UTC, mrIncompetent commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +		UpdateFunc: func(_, newObj interface{}) { ctrl.enqueue(newObj.(*corev1.Node)) },
No strong opinion here - Opting for @alvaroaleman suggestion as it seems a cleaner approach

2018-08-27 10:17 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +		UpdateFunc: func(_, newObj interface{}) { ctrl.enqueue(newObj.(*corev1.Node)) },
Done in 674c26f.

2018-08-27 10:18 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +func (ctrl *Controller) syncDnatRules(key string) error {
Done in 6640636c1408db318f366131f1ee1f336c229012.

2018-08-27 10:19 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +	for ctrl.processNextItem() {
Solved with cleaner Update-func approach, resync timer and no sleep at all.

2018-08-27 10:21 UTC, thz commented
ping @mrIncompetent

2018-08-27 10:35 UTC, alvaroaleman commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +			ctrl.enqueue(newObj.(*corev1.Node))
Shouldn't we use a constant string here to have at least _some_ deduplication since the `sync` syncs the rules for all nodes anyways?

2018-08-27 10:36 UTC, alvaroaleman commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +	if ctrl.queue.NumRequeues(key) < 5 {
Please remove this check, we should retry indefinitely

2018-08-27 10:42 UTC, alvaroaleman commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +	go wait.Until(func() { ctrl.queue.Add("some node") }, time.Second*30, stopCh)
And please make the key used here a constant and use that constant everywhere to ensure we let the qeue deduplicate as much as possible

2018-08-27 10:43 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +	if ctrl.queue.NumRequeues(key) < 5 {
Done in 19a16098d19c0d7a0474045c41a48560ead9fd75

2018-08-27 10:45 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +			ctrl.enqueue(newObj.(*corev1.Node))
This is actually happening in `enqueueAfter`. The object is still passed the way down.

2018-08-27 10:45 UTC, alvaroaleman commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +	_, err := cache.DeletionHandlingMetaNamespaceKeyFunc(n)
I don't think we need any of this, we don't actually enq the node object but just a static key. To simplify this, please change to 

```
func (ctrl *Controller) enqueue(n *corev1.Node) {
 ctrl.queue.AddAfter(enqKeyConstant, 0
}
```

and remove the `enqueueAfter` entirely, unless I've missed something

2018-08-27 10:49 UTC, alvaroaleman commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller_test.go
> +	for i := 0; i < 3; i++ {
nit: You can simply do a 

```
for idx, expectedRule := range expectedRule {
 if rules[idx] != expectedRule {failHard}
```

2018-08-27 10:50 UTC, alvaroaleman commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller_test.go
> +package kubeletdnat
Very nice, this file is better than any doc to understand whats actually going to happen :)

2018-08-27 10:50 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +	go wait.Until(func() { ctrl.queue.Add("some node") }, time.Second*30, stopCh)
Done in fcfa79e4fdf62d2b3dfc7f8bd98365e60aaf14cf

2018-08-27 11:15 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +	_, err := cache.DeletionHandlingMetaNamespaceKeyFunc(n)
Removed enqueue and enqueueAfter now.

2018-08-27 12:15 UTC, alvaroaleman submitted a review, later dismissed

2018-08-27 13:34 UTC, mrIncompetent requested changes

2018-08-27 13:34 UTC, mrIncompetent commented on api/cmd/kubeletdnat-controller/main.go
> +	glog.V(6).Infof("Factory started.")
Whats this log for?
Each Informer does log a `glog.V(4).Infof("caches populated")`

2018-08-27 13:34 UTC, mrIncompetent commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +	QueueKey = "some node"
This does only get used within the package, no need to export it

2018-08-27 13:34 UTC, mrIncompetent commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +}
`DnatRule` does only get used within the package, no need to export it.
Same applies for all properties of the struct

2018-08-27 13:34 UTC, mrIncompetent commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +		rule.TranslatedPort != other.TranslatedPort {
Consider replacing this condition with something more readable like:
```go
if other == nil || equality.Semantic.DeepEqual(*rule, *other) {
	return false
}
return true
```

2018-08-27 13:34 UTC, mrIncompetent commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +			if oldRule.Equals(newRule) {
This is not what we agreed on in https://github.com/kubermatic/kubermatic/pull/1817#discussion_r212547047

This approach here puts business logic into the direct event handler which should be moved into the sync-handler.

2018-08-27 13:34 UTC, mrIncompetent commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +func (ctrl *Controller) syncDnatRules(key string) error {
Why do we pass in the key at all when we don't use it?

2018-08-27 13:34 UTC, mrIncompetent commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +	return -1, []string{}, err
What is the need to return the return code?

2018-08-27 13:34 UTC, mrIncompetent commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +	if rc != 0 || err != nil {
Whats the return-code for if we have an error?

2018-08-27 13:34 UTC, mrIncompetent commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +		if err := execIptables([]string{"-t", "nat", "-I", "POSTROUTING", "-o", "tun0", "-j", "MASQUERADE"}); err != nil {
Interface name should be configurable

2018-08-27 13:34 UTC, mrIncompetent commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +func getPreferredNodeAddress(node *corev1.Node) (string, error) {
Can we rather create a rule all IP's of a node?

2018-08-27 13:34 UTC, mrIncompetent commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +func (ctrl *Controller) getRuleFromNode(node *corev1.Node) (*DnatRule, error) {
Shouldn't it rather be called `getRuleForNode` ?

2018-08-27 13:34 UTC, mrIncompetent commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +	if node == nil {
If we're not smart enough to call a function with correct parameters, we should rethink if calling this function is a good idea.

2018-08-27 13:34 UTC, mrIncompetent commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +func hashLines(lines []string) []byte {
Is it cheaper to calculate & compare hashes of string-lists than directly comparing them?

2018-08-27 13:34 UTC, mrIncompetent commented on api/pkg/resources/vpnsidecar/dnatController.go
> +				corev1.ResourceCPU:    defaultOpenVPNCPURequest,
Does this controller need the same amount of resources like openvpn?
I would expect far less as its only writing iptables rules

2018-08-27 14:10 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +			if oldRule.Equals(newRule) {
That comment is proposing (literally) `func(old, new interface{}) { if old.status.Addresses != new.status.Addresses { enq(constKey)}`.
This is now done with an Equals func, but the comparison was proposed to be directly in the update func.
Also this comparison is there to decide if we add something to the queue or not. I am not getting how that can go to the sync handler.

I see that there is the conversion from obj->node->rule before the comparison. Is that the business logic to prevent?

2018-08-27 14:19 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +	if node == nil {
This is meant for graceful handling of being called like `getRuleFromNode(oldObj.(*corev1.Node))`.
We can push that responsibility to the caller too.

2018-08-27 14:24 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +func hashLines(lines []string) []byte {
Computational, no. Regarding memory, yes. 
But actually the memory footprint would be quite small even with dozens of nodes.
So actually both ways are reasonable.

2018-08-27 14:27 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +func getPreferredNodeAddress(node *corev1.Node) (string, error) {
What is the advantage of adding the extra rules for the addresses which are not used?

2018-08-27 15:30 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +func hashLines(lines []string) []byte {
When in doubt - go for less code...

2018-08-27 20:35 UTC, alvaroaleman commented on api/pkg/resources/apiserver/deployment.go
> +	flags = append(flags, "--kubelet-preferred-address-types", "ExternalIP,InternalIP")
:+1:

2018-08-27 20:43 UTC, alvaroaleman commented on api/pkg/resources/test/fixtures/deployment-aws-1.10.6-apiserver.yaml
> +            cpu: 5m
This is sufficent?

2018-08-27 21:02 UTC, alvaroaleman submitted a review, later dismissed

2018-08-27 21:17 UTC, thz commented
@mrIncompetent ping, all issues addressed.

2018-08-28 07:40 UTC, mrIncompetent commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +		glog.Errorf("failed to get internal node address: %v", err)
Why does the log message say: `failed to ...` but the function returns successfully?
If `getRulesForNode` cannot create the rules for the given input because the given input is not sufficient, `getRulesForNode` should return an error.

The calling function `getDesiredRules` should instead decide if a single failure should make the whole ruleset creation fail

2018-08-28 07:43 UTC, mrIncompetent commented on api/pkg/resources/apiserver/deployment.go
> +	flags = append(flags, "--kubelet-preferred-address-types", "ExternalIP,InternalIP")
Move this to the initialization of the `flags` variable.
No need to append here as its static

2018-08-28 07:44 UTC, mrIncompetent commented on api/pkg/resources/test/fixtures/deployment-aws-1.10.6-apiserver.yaml
> +            cpu: 5m
@thz can you check what usage the controller has in a cluster with 100 Nodes?

2018-08-28 07:45 UTC, mrIncompetent commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +		glog.Errorf("failed to get internal node address: %v", err)
Why does the log message say: `failed to ...` but the function returns successfully?
If `getRulesForNode` cannot create the rules for the given input because the given input is not sufficient, `getRulesForNode` should return an error.

The calling function `getDesiredRules` should instead decide if a single failure should make the whole ruleset creation fail

2018-08-28 08:35 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +		glog.Errorf("failed to get internal node address: %v", err)
When rules for a single node cannot be created an error is logged and rule-creation continues for the other nodes. This is what is happening here. The error is logged and an empty list is returned.

If you say the decision "log but do not fail" should happen more upwards in the call-tree, then I can move it there.

2018-08-28 08:39 UTC, mrIncompetent commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +		glog.Errorf("failed to get internal node address: %v", err)
Yes, i would definitely prefer doing the decision one level above.
Also we should include something like `could not generate rules for node foo: %v - skipping`.
That way a operator knows that logged error is not critical

2018-08-28 11:21 UTC, thz commented on api/pkg/resources/test/fixtures/deployment-aws-1.10.6-apiserver.yaml
> +            cpu: 5m
With 100 Nodes it is peaking into the 10m cpu and 9Mi memory. I will increase cpu to 5m/20m req/limit and reduce memory to 10Mi/20Mi.
Actually the command execution and rule generation part is barely visible in the profile. Most time is spend on the watching part of the controller.

2018-08-28 12:24 UTC, thz commented
@mrIncompetent issues addressed.

2018-08-28 12:24 UTC, thz commented on api/pkg/controller/kubeletdnat/kubeletdnat_controller.go
> +		glog.Errorf("failed to get internal node address: %v", err)
Error handling changed as discussed.

2018-08-28 12:24 UTC, thz commented on api/pkg/resources/apiserver/deployment.go
> +	flags = append(flags, "--kubelet-preferred-address-types", "ExternalIP,InternalIP")
Done.

2018-08-28 14:09 UTC, mrIncompetent submitted a review, later dismissed

2018-08-28 14:29 UTC, mrIncompetent approved these changes

2018-08-28 14:42 UTC, thz commented
ping @alvaroaleman please re-approve (after final image tagging).

2018-08-28 17:01 UTC, alvaroaleman approved these changes

2018-08-28 17:20 UTC, merged