use label selector to filter out clusters to process
kubermatic/kubermatic pull request #1828
Opened 2018-08-21 10:10 UTC by kdomanski

Fixes #1166 

```release-note
NONE
```

2018-08-21 10:24 UTC, p0lyn0mial requested changes

2018-08-21 10:24 UTC, p0lyn0mial commented on api/cmd/kubermatic-controller-manager/main.go
> +	ctrlCtx.kubermaticInformerFactory = externalversions.NewFilteredSharedInformerFactory(ctrlCtx.kubermaticClient, time.Minute*5, metav1.NamespaceAll, labelSelector(runOp.workerName))
`NewFilteredSharedInformerFactory ` is deprecated use `NewSharedInformerFactoryWithOptions` instead.

2018-08-21 10:24 UTC, p0lyn0mial commented on api/pkg/controller/rbac/rbac_controller.go
>  func New(
this controller is run by `rbac-generator` app not `controller-manager`, please change `kubermaticMasterInformerFactory ` in
https://github.com/kubermatic/kubermatic/blob/5eb921a595de6b997a73d21feabfd380dec115e6/api/cmd/rbac-generator/main.go

2018-08-21 10:34 UTC, kdomanski commented on api/cmd/kubermatic-controller-manager/main.go
> +	ctrlCtx.kubermaticInformerFactory = externalversions.NewFilteredSharedInformerFactory(ctrlCtx.kubermaticClient, time.Minute*5, metav1.NamespaceAll, labelSelector(runOp.workerName))
We'd have to bump some deps, e.g. `client-go` and `code-generator` to have it.

2018-08-21 12:03 UTC, alvaroaleman commented on api/cmd/rbac-generator/main.go
> +// return label selector to only process clusters with a matching machine.k8s.io/controller label
Since this has to be identical for every app we have that watches Clusters, wouldn't it make sense to put this into some common package and import?

2018-09-07 12:33 UTC, kdomanski commented
Changed as requested in #1166

2018-09-12 12:37 UTC, alvaroaleman commented on api/cmd/kubermatic-controller-manager-cleanup/main.go
> +	wg.Add(len(clusters.Items))
Is the migration so slow that its worth adding this complexity?

2018-09-12 12:54 UTC, kdomanski commented on api/cmd/kubermatic-controller-manager-cleanup/main.go
> +	wg.Add(len(clusters.Items))
@mrIncompetent WDYT?

2018-09-12 12:56 UTC, kdomanski commented on api/pkg/controller/rbac/rbac_controller.go
>  func New(
Done.

2018-09-12 12:57 UTC, kdomanski commented on api/cmd/rbac-generator/main.go
> +// return label selector to only process clusters with a matching machine.k8s.io/controller label
Done.

2018-09-12 13:04 UTC, kdomanski commented
@p0lyn0mial fix reverted

2018-09-12 15:13 UTC, mrIncompetent commented on api/cmd/kubermatic-controller-manager-cleanup/main.go
> +	wg.Add(len(clusters.Items))
Not worth it. It would be way faster in the long term if we only update the resource if we really touched it

2018-09-13 07:59 UTC, alvaroaleman approved these changes

2018-09-13 12:23 UTC, p0lyn0mial approved these changes

2018-09-14 08:15 UTC, mrIncompetent approved these changes

2018-09-14 09:24 UTC, merged