Move kubeconfigs
kubermatic/kubermatic pull request #1928
Opened 2018-08-31 12:10 UTC by mrIncompetent

**What this PR does / why we need it**:
Move kubeconfig handling into the resources package.
This PR will also add reconciling to the kubeconfig code.

**Release note**:
```release-note
NONE
```

2018-08-31 13:34 UTC, kron4eg submitted a review, later dismissed

2018-08-31 15:01 UTC, alvaroaleman requested changes
Some nits but overall this is soo much better than the annotation approach we had so far :))

2018-08-31 15:01 UTC, alvaroaleman commented on api/pkg/resources/kubeconfig.go
> +		if len(b) == 0 {
Can't we move this check into `isValidKubeconfig` to reduce the amount of branches needed here?

2018-08-31 15:01 UTC, alvaroaleman commented on api/pkg/resources/kubeconfig.go
> +		if err != nil {
Cant we simplify this by doing one branch `if err != nill || !valid` and within that branch another single one to log an error in case `err != nil`?

2018-08-31 15:01 UTC, alvaroaleman commented on api/pkg/resources/resources.go
> +	//TODO: Check why equality.Semantic.DeepEqual returns a different result than deep.Equal
Could you add a (perma-)link here to a code sample where this does not work as expected? Otherwise we will keep this forever because it did not work in some scenario no one knows anything about

2018-08-31 15:01 UTC, alvaroaleman commented on api/pkg/resources/kubeconfig.go
> +func GetInternalKubeconfigCreator(name, commonName string, organizations []string) func(data *TemplateData, existing *corev1.Secret) (*corev1.Secret, error) {
Maybe just name it `GetKubeConfigSecretCreator`?

2018-09-03 11:29 UTC, mrIncompetent commented on api/pkg/resources/kubeconfig.go
> +func GetInternalKubeconfigCreator(name, commonName string, organizations []string) func(data *TemplateData, existing *corev1.Secret) (*corev1.Secret, error) {
The kubeconfig, which will get created here, will use the internal apiserver address.
So the ClusterIP.

I updated the comment to express that

2018-09-03 11:30 UTC, mrIncompetent commented on api/pkg/resources/resources.go
> +	//TODO: Check why equality.Semantic.DeepEqual returns a different result than deep.Equal
I updated the commend

2018-09-03 11:30 UTC, mrIncompetent commented on api/pkg/resources/kubeconfig.go
> +		if err != nil {
done

2018-09-03 11:30 UTC, mrIncompetent commented on api/pkg/resources/kubeconfig.go
> +		if len(b) == 0 {
done

2018-09-03 14:01 UTC, kdomanski approved these changes

2018-09-03 14:01 UTC, merged