WIP: user-cluster-controller part1
kubermatic/kubermatic pull request #1956
Opened 2018-09-05 19:11 UTC by thz

**What this PR does / why we need it**:

See `docs/proposals/user-cluster-controller.md`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
Introduces the user-cluster-controller.
```

2018-09-06 09:03 UTC, mrIncompetent commented on api/pkg/controller/cluster/launching.go
> +			cm.Data["masterVpnAddress"] = vpnAddress
The cluster-info ConfigMap which is defined by the kubeadm project, i would rather avoid using it for our own data.
I would prefer to pass the cluster-name and the vpn-address as flag to the user-cluster-resources-controller-manager

2018-09-06 09:11 UTC, mrIncompetent commented on api/pkg/controller/usercluster/resources.go
> +		if existing, err = ucc.client.RbacV1().ClusterRoles().Get(cRole.Name, metav1.GetOptions{}); err != nil {
Use a lister

2018-09-06 09:13 UTC, mrIncompetent commented on api/pkg/controller/usercluster/resources.go
> +			glog.V(4).Infof("Created ClusterRole %s inside user-cluster %s", cRole.Name, data.ClusterNameOrEmpty())
Remove ` inside user-cluster %s` - as its obvios

2018-09-06 09:13 UTC, mrIncompetent commented on api/pkg/controller/usercluster/resources.go
> +		if existing, err = ucc.client.CoreV1().ConfigMaps(cm.Namespace).Get(cm.Name, metav1.GetOptions{}); err != nil {
Use a lister

2018-09-06 09:13 UTC, mrIncompetent commented on api/pkg/controller/usercluster/resources.go
> +			glog.V(4).Infof("Created ConfigMap %s inside user-cluster %s", cm.Name, data.ClusterNameOrEmpty())
Remove ` inside user-cluster %s` as its obvios

2018-09-06 09:14 UTC, mrIncompetent commented on api/pkg/controller/usercluster/resources.go
> +		glog.V(4).Infof("Updated ClusterRole %s inside user-cluster %s", cRole.Name, data.ClusterNameOrEmpty())
remove ` inside user-cluster %s` as its obvios

2018-09-06 09:18 UTC, mrIncompetent commented on api/pkg/controller/usercluster/resources.go
> +		glog.V(4).Infof("Updated ConfigMap %s inside user-cluster %s", cm.Name, data.ClusterNameOrEmpty())
Remove inside user-cluster %s as its obvios

2018-09-06 09:21 UTC, mrIncompetent commented on api/pkg/controller/usercluster/usercluster_controller.go
> +	}
What is this for?

2018-09-06 09:28 UTC, mrIncompetent commented on api/pkg/resources/openvpn/configmap.go
> +remote %s %s
Why changing to `%s` when we have a port?

2018-09-06 09:31 UTC, mrIncompetent commented on api/pkg/resources/resources.go
> +	UserClusterControllerManagerCertUsername = "kubermatic:user-cluster-controller-manager"
Woulnd't it be easier if we just use the `system:masters` group here?
So we don't run into the chicken-egg problem, where we need to create rbac rules inside the cluster to make the uccm work?

2018-09-06 09:33 UTC, mrIncompetent commented on api/pkg/resources/resources.go
> +type UserConfigMapCreator = func(data *UserClusterData, existing *corev1.ConfigMap) (*corev1.ConfigMap, error)
Shouldn't it be `UserClusterConfigMapCreator` ?

2018-09-06 09:33 UTC, mrIncompetent commented on api/pkg/resources/resources.go
> +type UserClusterRoleCreator = func(data *UserClusterData, existing *rbacv1.ClusterRole) (*rbacv1.ClusterRole, error)
Group all user-cluster interfaces

2018-09-06 09:51 UTC, mrIncompetent commented on api/pkg/resources/userclustercontrollermanager/deployment.go
> +				"--logtostderr", "--v", "6",
Should be turned down to 4 before merging

2018-09-06 09:52 UTC, mrIncompetent commented on api/pkg/resources/userclustercontrollermanager/deployment.go
> +				"--logtostderr", "--v", "6",
```go
"--logtostderr", 
"--v", "6",
```

2018-09-06 09:54 UTC, kdomanski commented on api/pkg/resources/userclustercontrollermanager/deployment.go
> +				"--logtostderr", "--v", "6",
Why do we need to run everything in extra verbose mode?

2018-09-06 09:55 UTC, mrIncompetent commented on api/pkg/resources/userclustercontrollermanager/deployment.go
> +				"--logtostderr", "--v", "6",
See https://github.com/kubermatic/kubermatic/pull/1956#discussion_r215564316

2018-09-06 11:41 UTC, kdomanski commented on api/pkg/resources/userclustercontrollermanager/deployment.go
> +				"--logtostderr", "--v", "6",
My bad.

2018-09-07 16:21 UTC, thz commented on api/pkg/controller/cluster/launching.go
> +			cm.Data["masterVpnAddress"] = vpnAddress
Created a dedicated configmap "cluster-seed" now.

2018-09-11 12:35 UTC, thz commented on api/pkg/controller/usercluster/usercluster_controller.go
> +	}
Ancient relic. It's gone.

2018-09-11 12:42 UTC, thz commented on api/pkg/resources/openvpn/configmap.go
> +remote %s %s
The actual address as a host, port pair is retrieved from the `cluster-seed` configmap. There I used the more common notation of `host:port` for the "address" of the vpn endpoint. I see no added value in separating the two nor do I see value in handing the port as an integer. So in doubt I prefer less code, less fields, less conversion.

Objections?

(Previously in the cluster-controller this was indeed an integer because it was fetched as `openvpnSvc.Spec.Ports[0].NodePort`)

2018-09-11 12:48 UTC, thz commented on api/pkg/resources/resources.go
> +	UserClusterControllerManagerCertUsername = "kubermatic:user-cluster-controller-manager"
This is not the classical chicken-egg problem. It lacks the back-dependency. We need to create a deployment in the cluster-controller, so we can add the RBAC as well.
Isn't your argument here more about removing complexity by sacrificing explicit RBAC?

That said, I do not have a strong opinion, but wouldn't we get a better audit trail in the end if the uccm uses a dedicated (named) role?

2018-09-12 07:44 UTC, mrIncompetent commented on api/cmd/user-cluster-controller-manager/controllers.go
> +}
Rename everything inside this file from `UserClusterController` to `Controller`.

2018-09-12 07:45 UTC, mrIncompetent commented on api/cmd/user-cluster-controller-manager/main.go
> +	if runOp.dockerPullConfigJSONFile == "" {
What for do we need this here?
We don't run any private images inside customer clusters as far as i know

2018-09-12 07:47 UTC, mrIncompetent commented on api/cmd/user-cluster-controller-manager/main.go
> +func newUserClusterControllerContext(runOp controllerRunOptions, done <-chan struct{}, kubeClient kubernetes.Interface) *controllerContext {
Rename to `newControllerContext`

2018-09-12 07:47 UTC, mrIncompetent commented on api/cmd/user-cluster-controller-manager/main.go
> +	controllers, err := createAllUserClusterControllers(ctrlCtx)
rename to `createAllControllers`

2018-09-12 07:52 UTC, mrIncompetent commented on api/pkg/controller/cluster/launching.go
> +			cm.Data["masterVpnAddress"] = vpnAddress
Can we find a more precise name her? Maybe even `cluster-info-extras`
`cluster-seed` seems a bit non-intuitive

2018-09-12 07:55 UTC, mrIncompetent commented on api/pkg/controller/cluster/launching.go
> +			glog.V(2).Infof("NotFound in getOpenVpnAddress is unexpected: %v", err)
Whats the benefit of logging it here if we return the error anyway on https://github.com/kubermatic/kubermatic/pull/1956/files#diff-a87fac085c1ef1d73a261323902c708eR177 ?

All errors are being bubbled up to the controller-error handler & logged there.

2018-09-12 07:57 UTC, mrIncompetent commented on api/pkg/controller/rbac/sync_project.go
> +	_, err = kubeClient.RbacV1().ClusterRoles().Create(generatedClusterRole) // ownerref missing FIXME
What ownerRef are we missing here?

2018-09-12 07:58 UTC, mrIncompetent commented on api/pkg/controller/usercluster/resources.go
> +	}
Move this error handling to `data.GetClusterName()` as it already returns an error

2018-09-12 08:00 UTC, mrIncompetent commented on api/pkg/controller/usercluster/usercluster_controller.go
> +	// "github.com/kubermatic/kubermatic/api/pkg/resources"
Can those be removed?

2018-09-12 08:04 UTC, mrIncompetent commented on api/pkg/resources/data.go
> +func (d *UserClusterData) ClusterNameOrEmpty() string {
Why do we need this function?

2018-09-12 08:04 UTC, mrIncompetent commented on api/pkg/resources/data.go
> +		return ""
At least log the error.

2018-09-12 08:04 UTC, mrIncompetent commented on api/pkg/resources/data.go
> +		return ""
Better: use `runtime.HandleErr`

2018-09-12 08:05 UTC, mrIncompetent commented on api/pkg/resources/data.go
> +	return false
We should not break existing functionality.
Must be fixed before we can merge this

2018-09-12 08:16 UTC, mrIncompetent commented on api/pkg/resources/data.go
> +		vpnPort = cm.Data["masterVpnAddress"][idx+1:]
Add validation for the `vpnPort` by casting it to int.
Otherwise we accept `:` as valid address.

2018-09-12 08:16 UTC, mrIncompetent commented on api/pkg/resources/data.go
> +		vpnPort = cm.Data["masterVpnAddress"][idx+1:]
Also then return the int value, not the string for the port

2018-09-12 08:17 UTC, mrIncompetent commented on api/pkg/resources/openvpn/configmap.go
> +remote %s %s
Yes, see https://github.com/kubermatic/kubermatic/pull/1956/files#r216936449

If we cast to int, we fail early in case we have invalid data instead of silently ignoring it

2018-09-12 08:24 UTC, mrIncompetent commented on api/pkg/resources/resources.go
> +	UserClusterControllerManagerCertUsername = "kubermatic:user-cluster-controller-manager"
You're right, i was assuming we move all user-cluster resource handling into the uccm - which would create a chicken-egg-problem.

We're not loosing anything for the audit trail, if we use a dedicated username + the `system:masters` group.
All actions would be logged with the username + group anyway.
I guess we would give the uccm otherwise permission to create & remove arbitrary RBAC resources anyway?

I would therefore prefer just giving the `system:masters` group to avoid handling RBAC in the cluster-controller

2018-09-12 08:42 UTC, thz commented on api/pkg/controller/cluster/launching.go
> +			cm.Data["masterVpnAddress"] = vpnAddress
It follows the seed metaphor quite exactly. Perhaps a bit too exactly. The seed cluster puts the seed somewhere and the user-cluster grows from it. That seed is called "cluster-seed". But I was guessing that this is slightly non-intuitive.

2018-09-12 08:44 UTC, thz commented on api/pkg/resources/openvpn/configmap.go
> +remote %s %s
I can agree with the validation step, after passing the `host:port` notation. Sounds good.

2018-09-12 09:51 UTC, alvaroaleman commented on api/pkg/controller/cluster/launching.go
> +			cm.Data["masterVpnAddress"] = vpnAddress
`cluster-info-kubermatic`?

2018-09-12 09:53 UTC, alvaroaleman commented on api/pkg/controller/cluster/launching.go
> +			cm.Data["masterVpnAddress"] = vpnAddress
Also, please make all keys an exported constant if you want to re-use them within the user-cluster-controller-manager

2018-09-12 10:01 UTC, alvaroaleman requested changes

2018-09-12 10:01 UTC, alvaroaleman commented on api/pkg/controller/cluster/launching.go
> +	if err != nil {
Nit: I find the code easier to read if the check for `IsNotFound` comes first, because by the time I am at the `else` below I do not know what the condition was anymore:

```
if err != nil {
  if !errors.IsNotFound(err){
    return fmt.Errorf("Error getting configmap: %v", err)
  }
  //CreateConfigMap here
}

2018-09-12 10:01 UTC, alvaroaleman commented on api/pkg/controller/cluster/launching.go
> +	}
Please add a check for `len(s.spec.Ports == 1)` before using it

2018-09-12 10:39 UTC, mrIncompetent commented on api/pkg/controller/cluster/launching.go
> +			cm.Data["masterVpnAddress"] = vpnAddress
As customers offer a managed kubernetes hosting with kubermatic, but under a different name, `cluster-info-kubermatic` might be confusing.
And following the seed metaphor might also be confusing for endusers...

2018-09-12 11:27 UTC, thz commented on api/pkg/controller/cluster/launching.go
> +			cm.Data["masterVpnAddress"] = vpnAddress
Then we are back at `cluster-info-extras`. or:
*  `cluster-bootstrap-data`?
* `master-data` (as it is from the ~seed~master; customer-neutral speak)

2018-09-12 12:20 UTC, alvaroaleman commented on api/pkg/controller/usercluster/usercluster_controller.go
> +package usercluster
Can we please not name this controller `usercluster` as we already have a `user-cluster-controller-manager`? Otherwise this will become the garbace can whenever someone feels something is not worth a dedicated controller and no one knows what it actually does.

Maybe just `ressourcescontroller`?

2018-09-12 12:20 UTC, alvaroaleman commented on api/pkg/controller/usercluster/usercluster_controller.go
> +	client          kubernetes.Interface
Can we rename this to `kubeClient` in case this controller ever manages some crd? Otherwise the name will then become ambigious

2018-09-12 12:20 UTC, alvaroaleman commented on api/pkg/controller/usercluster/usercluster_controller.go
> +	configMapInformer.Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{
Doesn't this also need an informer on all resources it manages, e.G. Roles and clusterroles?

2018-09-12 12:20 UTC, alvaroaleman commented on api/pkg/resources/data.go
> +	panic("GetMasterVpnAddress not implemented for TemplateData")
The panics will all be gone once this is part of a release?

2018-09-12 12:20 UTC, alvaroaleman commented on api/pkg/resources/data.go
> +		vpnPort = cm.Data["masterVpnAddress"][idx+1:]
Nit: I find it easier to read to simply split by `:` then validate the `len(splittedString) == 2`. Also, the current implementation basically checks `len(splittedString) >= 1` but it must be exactly `2`

2018-09-12 12:20 UTC, alvaroaleman commented on api/pkg/resources/resources.go
> +	UserClusterControllerManagerCertUsername = "kubermatic:user-cluster-controller-manager"
I agree, furthermore the audit trail argument is IMHO invalid as the controller must have permissions to create more `Roles` and `RoleBindings` so indirectly it has `system:masters` anyways

2018-09-12 13:54 UTC, thz commented on api/cmd/user-cluster-controller-manager/main.go
> +	if runOp.dockerPullConfigJSONFile == "" {
True.

2018-09-12 19:18 UTC, thz commented on api/pkg/resources/data.go
> +		vpnPort = cm.Data["masterVpnAddress"][idx+1:]
Actually an address `hostname` without the port should be valid and default to standard 1194 port. And then there IPv6 which has `:` in the host part. But yea - using the last `:` would break with IPv6 without port anyways... I'll rethink this.

2018-09-12 19:18 UTC, thz commented on api/pkg/resources/data.go
> +		vpnPort = cm.Data["masterVpnAddress"][idx+1:]
...and then in theory you can use names for ports as well. I doubt that we want to support that though.

2018-09-12 19:20 UTC, thz commented on api/pkg/controller/usercluster/usercluster_controller.go
> +package usercluster
You were the one opposing anything with `resource` in it ;-)
But wouldn't it make sense to have some distinction in the name that the controlled resources are the user/customer resources?

2018-09-12 19:24 UTC, thz commented on api/pkg/resources/data.go
> +	panic("GetMasterVpnAddress not implemented for TemplateData")
That was actually not the plan. Using a `TemplateData` in a usercluster is incorrect and also `UserClusterData` in the clustercontroller is incorrect. Those are mistakes in the code which can only be caused by seriously mixing up userclustercontroller and clustercontroller code paths. In that case I prefer to fail hard and early instead of having a no-op func to satisfy the common interface.

2018-09-12 19:27 UTC, thz commented on api/pkg/resources/resources.go
> +	UserClusterControllerManagerCertUsername = "kubermatic:user-cluster-controller-manager"
My audit trail argument was only about keeping the name. As henrik pointed out that is still the case when using the group. The audit trail is independent of the possibility of privilege elevation by using Roles/RoleBindings rights.

2018-09-14 07:52 UTC, mrIncompetent commented on api/pkg/controller/cluster/launching.go
> +			cm.Data["masterVpnAddress"] = vpnAddress
`cluster-info-extras`

2018-09-14 07:56 UTC, mrIncompetent commented on api/pkg/resources/data.go
> +		vpnPort = cm.Data["masterVpnAddress"][idx+1:]
Lets set `ip:port` as requirement. The IP can be ipv6 though.
We are the ones specifying the data, so no need to cover every edgecase

2018-09-14 08:03 UTC, alvaroaleman commented on api/pkg/controller/usercluster/usercluster_controller.go
> +package usercluster
Touchez. So let me rephrase: I think the current package name is bad because its identintical with the controller managers name but right now I do not have a good suggestion either.

2019-02-15 08:46 UTC, nikhita commented
Closing in favour of https://github.com/kubermatic/kubermatic/pull/2671.

/close

2019-02-15 08:46 UTC, closed without merging