extract ensure ConfigMaps and Secrets
kubermatic/kubermatic pull request #2010
Opened 2018-09-17 13:48 UTC by mrIncompetent

**What this PR does / why we need it**:
Extract ensure ConfigMaps and Secrets

**Release note**:
```release-note
NONE
```

2018-09-18 12:55 UTC, thz requested changes

2018-09-18 12:55 UTC, thz commented on api/pkg/resources/ensure.go
> +
deepcopy for existing secret missing?

2018-09-18 12:55 UTC, thz commented on api/pkg/resources/ensure.go
> +
deepcopy of existing configmap missing?

2018-09-18 13:55 UTC, mrIncompetent commented
@thz I added the missing DeepCopy calls

2018-09-19 08:21 UTC, thz approved these changes

2018-09-19 08:31 UTC, merged