Add monitoring controller
kubermatic/kubermatic pull request #2130
Opened 2018-10-03 11:20 UTC by thetechnick

**What this PR does / why we need it**:
See #2124 
**tl;dr**: Move monitoring stuff into its own controller. The cluster controller should only need to handle cluster live-cycle relevant components.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2124 

**Special notes for your reviewer**:
I duplicated quite a lot of code, but I did not want to waste time on abstractions, before discussing it with someone in person.
I did not yet test if this is actually working, apart from a very basic unittest, because I did not get my hands on a test system yet. 

**Documentation**:

**Release note**:

*internal refactoring*
```release-note
NONE
```

2018-10-03 16:37 UTC, mrIncompetent commented on api/cmd/kubermatic-controller-manager/controllers.go
> +		ctrlCtx.runOptions.inClusterPrometheusScrapingConfigsFile,
Remove those arguments from the cluster controller: https://github.com/kubermatic/kubermatic/blob/monitoring-controller/api/pkg/controller/cluster/cluster_controller.go#L68

2018-10-03 16:38 UTC, mrIncompetent commented on api/cmd/kubermatic-controller-manager/controllers.go
> +		ctrlCtx.runOptions.etcdDiskSize,
Whats the disk size for?

2018-10-03 16:44 UTC, mrIncompetent commented on api/pkg/controller/monitoring/monitoring_controller.go
> +			"monitoring",
`monitoring_cluster`

The name should be the name of the controller + the resource, which gets put into the queue.
Exception here is the cluster controller with just `cluster`.

2018-10-03 18:24 UTC, thetechnick commented on api/cmd/kubermatic-controller-manager/controllers.go
> +		ctrlCtx.runOptions.inClusterPrometheusScrapingConfigsFile,
The prometheus arguments and the `ctrlCtx.runOptions.etcdDiskSize` are used here when instantiating a new TemplateData container:
https://github.com/kubermatic/kubermatic/blob/monitoring-controller/api/pkg/controller/cluster/resources.go#L88-L104
https://github.com/kubermatic/kubermatic/blob/monitoring-controller/api/pkg/controller/monitoring/resources.go#L18-L34

I am also not really happy with this solution, but I also find that `TemplateData` should always have all parameters, whether they are used or not (to make runtime errors less likely). 
Separating these TemplateData objects would make this PR bigger and increases the complexity to a point I am even less happy with.

2018-10-03 18:25 UTC, thetechnick commented on api/cmd/kubermatic-controller-manager/controllers.go
> +		ctrlCtx.runOptions.etcdDiskSize,
see answer above

**tl;dr** `NewTemplateData` needs the `etcdDiskSize`
https://github.com/kubermatic/kubermatic/blob/monitoring-controller/api/pkg/controller/monitoring/resources.go#L18-L34

2018-10-04 11:00 UTC, mrIncompetent commented on api/pkg/controller/cluster/resources.go
> +	creators := []resources.RoleBindingCreator{}
I would prefer if we remove empty ensure functions

2018-10-04 11:01 UTC, mrIncompetent commented on api/pkg/controller/monitoring/monitoring_controller.go
> +	glog.V(0).Infof("Dropping %q out of the backup controller queue after exceeding max retries: %v", key, err)
`backup controller` -> `monitoring controller`

2018-10-04 11:08 UTC, mrIncompetent commented
looks good from my side but @alvaroaleman should have a look as well. 
But reminds me of some cleanups we should do in our controllers (Not this PR):
- Fix adding back to the queue in case of error (Remove dropping)
- Eliminate global `TemplateData`. Maybe: https://github.com/kubermatic/kubermatic/compare/master...alternative-cm-creator

Really good PR :)

2018-10-05 08:55 UTC, mrIncompetent commented
A potential solution(Proposal) to avoid having to handle `TemplateData` everywhere: https://github.com/kubermatic/kubermatic/pull/2145

2018-10-05 10:47 UTC, alvaroaleman requested changes

2018-10-05 10:47 UTC, alvaroaleman commented on api/pkg/controller/monitoring/monitoring_controller.go
> +type UserClusterConnectionProvider interface {
Why not use the existing `UserClusterConnectionProvider` type from the cluster controller?

2018-10-05 10:47 UTC, alvaroaleman commented on api/cmd/kubermatic-controller-manager/controllers.go
> +		ctrlCtx.runOptions.nodePortRange,
Cant we just leave this empty everywhere in the monitoring conroller as its not needed?

2018-10-05 10:47 UTC, alvaroaleman commented on api/pkg/controller/monitoring/resources.go
> +	data, err := c.getClusterTemplateData(cluster)
Wouldn't it be easier to make the `getClusterTemplateData` call inside the main sync loop and passing it into the `ensure...` funcs instead of doing it inside every single one of them?

2018-10-05 10:47 UTC, alvaroaleman commented on api/pkg/controller/monitoring/resources_test.go
> +				if len(controller.kubeClient.(*fake.Clientset).Actions()) != beforeActionCount+1 && controller.kubeClient.(*fake.Clientset).Actions()[beforeActionCount].GetVerb() != "update" {
Wouldn't it make more sense to put the expected actions on the testcase?

2018-10-05 10:47 UTC, alvaroaleman commented on api/pkg/controller/monitoring/userclusterresources.go
> +	client, err := cc.userClusterConnProvider.GetClient(c)
Same as for the templateData, wouldn't it make sense to get the user cluser client in the main sync loop and pass it into the `userCluserEnsure....` instead of getting it in every single one of them?

2018-10-05 11:16 UTC, mrIncompetent commented on api/pkg/controller/monitoring/monitoring_controller.go
> +type UserClusterConnectionProvider interface {
I would live to avoid to import here from the cluster controller. Interfaces should (best case) be defined where they are used

2018-10-05 11:18 UTC, mrIncompetent commented on api/cmd/kubermatic-controller-manager/controllers.go
> +		ctrlCtx.runOptions.nodePortRange,
I would keep the fow now, until we have https://github.com/kubermatic/kubermatic/pull/2145 in

2018-10-05 11:18 UTC, alvaroaleman commented on api/pkg/controller/monitoring/monitoring_controller.go
> +type UserClusterConnectionProvider interface {
Then they shouldn't be exported

2018-10-05 12:42 UTC, alvaroaleman submitted a review, later dismissed

2018-10-05 12:55 UTC, mrIncompetent approved these changes

2018-10-05 13:00 UTC, alvaroaleman approved these changes

2018-10-05 13:01 UTC, merged