Feature/api baremetal
kubermatic/kubermatic pull request #216
Opened 2017-01-18 01:39 UTC by lbb

Resolves #197

2017-01-19 14:06 UTC, mrIncompetent requested changes

2017-01-19 14:06 UTC, mrIncompetent commented on provider/cloud/baremetal/baremetal.go
> +		return nil, errors.New("couldn't find key")
Please return a meaningful error message which also includes the missing key

2017-01-19 14:06 UTC, mrIncompetent commented on provider/cloud/baremetal/baremetal.go
> +	url, ok := annotations["apiserver_url"]
What are we saving this for?

2017-01-19 14:06 UTC, mrIncompetent commented on provider/cloud/baremetal/baremetal.go
> +	kubeconfig, ok := annotations["kubeconfig"]
What are we saving this for?

2017-01-19 14:06 UTC, mrIncompetent commented on provider/cloud/baremetal/baremetal.go
> +		return nil, fmt.Errorf("error creating node got status %d", resp.StatusCode)
Also return the response body in an error case

2017-01-19 14:06 UTC, mrIncompetent commented on types.go
> +	APIServerURL string `json:"apiserver_url"`
What is this needed for?

2017-01-19 14:06 UTC, mrIncompetent commented on types.go
> +	KubeConfig   string `json:"kube_config"`
What is this needed for?

2017-01-19 17:48 UTC, scruplelesswizard commented
Sorry, should have split out the refactor in to its own PR

2017-01-24 10:34 UTC, mrIncompetent commented on provider/cloud/baremetal/baremetal.go
> +	nodes, err := b.Nodes(context.Background(), cl)
Please call
`DELETE /clusters/{name}`

This will delete the registered cluster (from InitializeCloudSpec) & all assigned nodes

2017-01-24 11:05 UTC, mrIncompetent commented on provider/cloud/baremetal/baremetal.go
> +const serviceURL = "baremetal-provider.api.svc.cluster.local"
If we move this to the datacenters.yaml, we have it configurable & we can support multiple bare-metal-DC's

2017-01-24 11:22 UTC, mrIncompetent commented on provider/cloud/baremetal/baremetal.go
> +	name, ok := annotations["name"]
Could we move the key to a constant & make the value a bit more unique?
Just to avoid collisions.

We maybe should in general add a provider-prefix to the annotation keys of the providers.

2017-02-07 11:12 UTC, mrIncompetent approved these changes

2017-02-07 11:25 UTC, merged