Prometheus user cluster access
kubermatic/kubermatic pull request #2177
Opened 2018-10-09 13:23 UTC by thetechnick

**What this PR does / why we need it**:
This PR adds apiserver client certificates that allow prometheus to access the user cluster and configures prometheus to discover and scrape nodes in the user cluster.

What it does not do:
Support for a label selector like "kubermatic.io/scrape=True" to scrape pods/services and it's configuration will be added in another PR.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes a part of #1903 

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
NONE
```

2018-10-09 14:22 UTC, kron4eg requested changes

2018-10-09 14:22 UTC, kron4eg commented on api/pkg/controller/backup/backup_controller.go
> +func (d *secretData) GetOpenVPNCA() (*resources.ECDSAKeyPair, error) {
now when vpn is gone, shouldn't this be gone also?

2018-10-09 14:22 UTC, kron4eg commented on api/pkg/resources/prometheus/configmap.go
> +    api_server: 'apiserver-external.{{ .TemplateData.Cluster.Status.NamespaceName }}.svc.cluster.local:32692'
apiserver-external is a NodePort service, you can't know its port in advance, please use

```
api_server: '{{ .TemplateData.InClusterApiserverURL }}'
```

2018-10-09 14:22 UTC, kron4eg commented on api/pkg/resources/prometheus/configmap.go
> +      key_file: /etc/kubernetes/prometheus-client.key
there is no point to configure `tls_config` two times, (one on scrape_config level, and one here)

2018-10-09 14:22 UTC, kron4eg commented on api/pkg/resources/prometheus/configmap.go
> +    replacement: 'apiserver-external.{{ .TemplateData.Cluster.Status.NamespaceName }}.svc.cluster.local:32692'
apiserver-external is a NodePort service, you can't know its port in advance, please use

```
api_server: '{{ .TemplateData.InClusterApiserverURL }}'
```

2018-10-09 14:45 UTC, thetechnick commented on api/pkg/controller/backup/backup_controller.go
> +func (d *secretData) GetOpenVPNCA() (*resources.ECDSAKeyPair, error) {
This code in the backup controller is needed to make `*secretData` match the `resources.SecretDataProvider` interface.
See https://github.com/kubermatic/kubermatic/blob/master/api/pkg/resources/data.go#L89-L98

2018-10-09 14:49 UTC, thetechnick commented on api/pkg/resources/prometheus/configmap.go
> +      key_file: /etc/kubernetes/prometheus-client.key
The first configuration is used by prometheus for the scrape request.
This second TLS configuration is need to tell prometheus to NOT use the "in cluster" provided secrets to connect to this kubernetes apiserver, but use these ones we have created for the user cluster apiserver.

When removing this config block prometheus cannot connect to the user cluster apiserver anymore:
```
level=error ts=2018-10-09T14:46:41.396697868Z caller=main.go:218 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:359: Failed to list *v1.Node: Get https://apiserver-external.cluster-j8t6q6lqn4.svc.cluster.local.:32692/api/v1/nodes?resourceVersion=0: x509: certificate signed by unknown authority"
```

2018-10-09 14:49 UTC, kron4eg commented on api/pkg/controller/backup/backup_controller.go
> +func (d *secretData) GetOpenVPNCA() (*resources.ECDSAKeyPair, error) {
ohhh... ok then :)

2018-10-09 15:01 UTC, kron4eg commented on api/pkg/resources/prometheus/configmap.go
> +      key_file: /etc/kubernetes/prometheus-client.key
That sounds like a bug in prometheus. why would it assume in-cluster credentials when it was clearly given tls_config just level above... well, ok, let it be two times for now.

2018-10-09 16:35 UTC, mrIncompetent commented on api/pkg/controller/monitoring/resources.go
> +}
Instead of the loop, you could directly handle the single call. Could simplify the code - but then we would have a difference to the cluster controller...
Not a request for change

2018-10-09 16:38 UTC, mrIncompetent commented on api/pkg/resources/resources.go
> +	PrometheusApiserverClientCertificatesSecretName = "prometheus-apiserver-certificates"
Plural ?

2018-10-09 16:39 UTC, mrIncompetent commented on api/pkg/resources/resources.go
> +	PrometheusClusterRoleName = "kubermatic-prometheus"
Please rename this to `external-prometheus` - No need to let the name `kubermatic` appear inside the user cluster.
As the product might get rebranded

2018-10-09 16:39 UTC, mrIncompetent commented on api/pkg/resources/resources.go
> +	PrometheusClusterRoleBindingName = "system:kubermatic-prometheus"
See https://github.com/kubermatic/kubermatic/pull/2177/files#r223777112

2018-10-10 07:27 UTC, thetechnick commented on api/pkg/controller/monitoring/resources.go
> +}
I was thinking about it, but I really like it when the controllers stay as similar as possible as long as the code is not *way* more difficult.

2018-10-10 10:17 UTC, kron4eg submitted a review, later dismissed

2018-10-10 10:28 UTC, mrIncompetent commented on api/pkg/resources/resources.go
> +	PrometheusApiserverClientCertificateSecretName = "prometheus-apiserver-certificates"
The value is still plural for no specific reason. The comment uses singular as well

2018-10-10 10:39 UTC, kron4eg approved these changes

2018-10-10 10:45 UTC, mrIncompetent approved these changes

2018-10-10 13:51 UTC, alvaroaleman approved these changes

2018-10-10 13:59 UTC, merged