New create cluster endpoint for dashboard v2
kubermatic/kubermatic pull request #221
Opened 2017-01-30 16:01 UTC by aklinkert

Depends on kubermatic/config#141 and kubermatic/dashboard#83. The final request looks like:
```json
{
  "cloud": {
    "user": "secret",
    "secret": "even-more-secret-so-you-wont-get-it-you-son-of-your-parents",
    "name": "aws",
    "region": "aws-eu-central-1a"
  },

  "spec": {
    "humanReadableName": "alex-test-1"
  },

  "sshKeys": [
    "alex"
  ]
}
```

2017-01-31 19:59 UTC, mrahbar submitted a review, later dismissed
Suggestion to change REST endpoint to /api/v1/clusters

2017-01-31 19:59 UTC, mrahbar commented on handler/routing.go
> +		Path("/api/v1/cluster").
REST endpoints should be plural: should be /api/v1/clusters

2017-01-31 20:02 UTC, aklinkert commented on handler/routing.go
> +		Path("/api/v1/cluster").
We had that discussion a few hours ago in the office, we will change the API to use plurals, but that will be on v2. So we'll stick with single for now.

BTW, personal note: _should be_ is an opinion here and should be declared as such. The api is using single s at the moment, so that is the _default_ right now.

2017-01-31 20:03 UTC, mrahbar commented
Can you give me an example how the response body will look like? I extracted something from the code put I'm not sure if it is correct: https://github.com/kubermatic/api/issues/165#issuecomment-276028049

2017-01-31 20:08 UTC, aklinkert commented
@mrahbar sure, this is an example response for AWS.

```json
{
  "metadata": {
    "name": "5wbgc8drr",
    "revision": "2699825",
    "uid": "c32680ae-e7f0-11e6-80b8-42010a800fe0"
  },
  "spec": {
    "cloud": {
      "dc": "aws-eu-central-1a",
      "user": "",
      "secret": "",
      "name": "",
      "region": "",
      "aws": {
        "init_mode": "",
        "access_key_id": "secret",
        "secret_access_key": "even more secret",
        "vpc_id": "vpc-819f62e9",
        "ssh_key_name": "alex",
        "subnet_id": "subnet-2bff4f43",
        "internet_gateway_id": "",
        "route_table_id": "",
        "role_name": "kubermatic-role-5wbgc8drr",
        "policy": "arn:aws:iam::733553989067:policy/kubermatic-policy-5wbgc8drr",
        "instance_profile_name": "kubermatic-instance-profile-5wbgc8drr",
        "availability_zone": "eu-central-1a",
        "security_group_id": "sg-9ae3f8f2"
      }
    },
    "humanReadableName": "alex-test-1"
  },
  "address": {
    "url": "",
    "etcdURL": "",
    "token": "",
    "nodePort": 32054
  },
  "status": {
    "lastTransitionTime": "2017-01-31T21:06:30+01:00",
    "phase": "Pending",
    "rootCA": {
      "cert": ""
    },
    "apiserverSSH": ""
  }
}
```

2017-01-31 20:37 UTC, mrahbar commented on handler/routing.go
> +		Path("/api/v1/cluster").
As I entitled my review comment I was _suggesting_ to change it to plural to be more REST conform.  Which makes sense for a new endpoint if it is intended to be a REST endpoint otherwise it can remain singular like the rest of the api which is not a big loss either. Since I do code reviews for my client on a daily basis I tend to provide my opinion as a feedback.

2017-01-31 20:56 UTC, aklinkert commented on handler/routing.go
> +		Path("/api/v1/cluster").
Sure. This more of a comment then a change request then. :)

Does REST specify weather urls have to be singular or plural?

2017-02-01 09:08 UTC, mrIncompetent commented on handler/routing.go
> +		Path("/api/v1/cluster").
As @apinnecke said: http://stackoverflow.com/a/6846057

2017-02-01 09:12 UTC, mrIncompetent commented on handler/fixtures/datacenters.yaml
> +    seed: master
Do we have a ticket to update existing datacenters.yaml files in the config repo?

2017-02-01 09:14 UTC, aklinkert commented on handler/fixtures/datacenters.yaml
> +    seed: master
Oh, that should already be done by the PR in the config repo :)

2017-02-01 09:15 UTC, mrIncompetent approved these changes

2017-02-01 09:18 UTC, mrIncompetent requested changes

2017-02-01 09:18 UTC, mrIncompetent commented on controller/cluster/controller.go
> +	cc.cmStore, cc.cmController = cache.NewIndexerInformer(
This controller needs to be started in `func (cc *clusterController) Run` && been checked in func (cc *clusterController) controllersHaveSynced

2017-02-01 13:26 UTC, aklinkert commented on controller/cluster/controller.go
> +	cc.cmStore, cc.cmController = cache.NewIndexerInformer(
Fixed!

2017-02-01 13:54 UTC, mrahbar commented on handler/routing.go
> +		Path("/api/v1/cluster").
Citing a stackoverflow thread is not reasonable to clarify your standpoint. I haven't read the whole thread but want to express my view at this point.

REST becomes more and more a standard of api design even with its drawbacks. So it is not useful to argue about right and wrong but about what most developer expect and assume when interacting with an api which is declared RESTful. Calling something REST and violating conventions leads to confusion and misinterpretation which can be summed up in anemic-rest [1]. The benefits of a RESTful api among other is that it can build up an api which reflects the current domain it represents. This can lead to a development of a strong domain language also called Domain Specific Language (DSL) which has its roots in Domain Driven Design [2]. For example when talking about features you can use the nouns which  representation your current domain like clusters, nodes, datacenters, ... which is something you normaly do which is good because everybody is on the same page if everyone talks the same DSL also the api. Here brevity in an api is not the key but expressiveness. 
To tackle on the singular/plural argument. REST states that nouns/resources are the elements which builds up an domain. Instances of resources are typically present a number of times. There are commonly no unique resources in an api. This leads to the convention that if declaring an api with GET /resources it returns all resources and identifying a resource by its identifier GET /resources/:id returns a single resource but every interaction happens on the /resources Resource identifier (URI). Using plural is not a rule but a convention. At this point it is a good start to see how other apis which are declared RESTful have coined their design decisions [3, 4]. There is much more so say about this topic but this should clear out my standpoint.

[1] https://www.thoughtworks.com/de/radar/techniques/anemic-rest
[2] http://dddcommunity.flywheelsites.com/learning-ddd/what_is_ddd/
[3.1] https://developer.github.com/v3/ 
[3.2] https://github.com/WhiteHouse/api-standards
[4] https://www.thoughtworks.com/de/insights/blog/rest-api-design-resource-modeling

2017-02-01 14:26 UTC, mrIncompetent commented on handler/routing.go
> +		Path("/api/v1/cluster").
@mrahbar sorry, i was thinking of a different scenario. (Having singular/plural for the resource name when a specific resource (by id) is requested). For this scenario there a different opinions and the comment i linked basically explained why.

But for this case here, we should rename to clusters (plural)

2017-02-01 14:38 UTC, aklinkert commented on handler/routing.go
> +		Path("/api/v1/cluster").
As I said: We will int eh future, but not now. @mrahbar Could you please change the "changes requested"?

2017-02-01 15:43 UTC, mrIncompetent approved these changes

2017-02-01 15:43 UTC, merged