Update cluster API
kubermatic/kubermatic pull request #2254
Opened 2018-10-22 08:11 UTC by maciaszczykm

**What this PR does / why we need it**: It refactors cluster API changing method used to filter sensitive information out of JSON responses and adds new PATCH endpoint. PATCH endpoint will be used to update only specific parts of cluster data and thanks to it sensitive information won't be overwritten during PUT calls.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: Fixes #2121.

**Special notes for your reviewer**: PATCH endpoint uses https://github.com/evanphx/json-patch library that implements https://tools.ietf.org/html/rfc7396. I will also create pull request to the Dashboard that will make it consume new endpoint.

**Documentation**: n/a

**Release note**:

```release-note
NONE
```

2018-10-22 12:39 UTC, maciaszczykm commented
During tests with Dashboard and sending version patch only `resourceVersion` and `version` were updated. There is no impact on read-only fields like `creationTimestamp` etc.

2018-10-22 13:02 UTC, p0lyn0mial requested changes

2018-10-22 13:02 UTC, p0lyn0mial commented on api/pkg/api/v1/types.go
> +	"encoding/json"
we usually group imports, please move it to the top. For example https://github.com/kubermatic/kubermatic/blob/ad6e9b5e5881d91351374fc2b4e4f5220b3eed25/api/pkg/handler/cluster.go#L3

2018-10-22 13:02 UTC, p0lyn0mial commented on api/pkg/api/v1/types.go
> +	External bool `json:"external"`
you remembered :)

2018-10-22 13:02 UTC, p0lyn0mial commented on api/pkg/api/v1/types.go
> +	"encoding/json"
we group the imports, please move it to the top. For example: https://github.com/kubermatic/kubermatic/blob/ad6e9b5e5881d91351374fc2b4e4f5220b3eed25/api/pkg/handler/cluster.go#L3

2018-10-22 13:02 UTC, p0lyn0mial commented on api/pkg/api/v1/types.go
> +	External bool `json:"external"`
you remembered :)

2018-10-22 13:02 UTC, p0lyn0mial commented on api/pkg/api/v1/types.go
> +	TenantID        string `json:"tenantID"`
Do we still (we switched to using PATH) need to return all those fields ?

2018-10-22 13:02 UTC, p0lyn0mial commented on api/pkg/api/v1/types.go
> +	VPCID               string `json:"vpcId"`
as above.

2018-10-22 13:02 UTC, p0lyn0mial commented on api/pkg/handler/cluster.go
> +	"github.com/evanphx/json-patch"
grouping.

2018-10-22 13:02 UTC, p0lyn0mial commented on api/pkg/handler/cluster.go
> +		return filterAndConvertInternalClusterToExternal(updatedCluster), nil
I think we can remove `filter` part of this method and change the name ?

2018-10-22 13:06 UTC, p0lyn0mial commented
do you think we can remove https://github.com/kubermatic/kubermatic/blob/master/api/pkg/crd/kubermatic/v1/cluster.go#L205 ?

2018-10-22 13:07 UTC, p0lyn0mial commented
> During tests with Dashboard and sending version patch only resourceVersion and version were updated. There is no impact on read-only fields like creationTimestamp etc.

please add an issue for unifying date format in API resources.

2018-10-22 13:40 UTC, p0lyn0mial commented on api/pkg/handler/routes_v1.go
> +//     Patches the given cluster.
can we add info about supported patch method ?

2018-10-22 13:41 UTC, p0lyn0mial commented on api/pkg/handler/cluster_test.go
> +			ExistingKubermaticObjects: func() []runtime.Object {
nit: we could change this to
```
ExistingKubermaticObjects: genDefaultKubermaticObjects(
genCluster(),
)
```

2018-10-22 13:43 UTC, maciaszczykm commented
> do you think we can remove https://github.com/kubermatic/kubermatic/blob/master/api/pkg/crd/kubermatic/v1/cluster.go#L205 ?

Unfortunately not until Dashboard will use PATCH endpoint instead of PUT. So in the correct order: getting this PR merged > updating Dashboard to use new PATCH endpoint > removing this method.

2018-10-22 13:48 UTC, maciaszczykm commented on api/pkg/api/v1/types.go
> +	External bool `json:"external"`
Yep :)

2018-10-22 13:48 UTC, maciaszczykm commented on api/pkg/api/v1/types.go
> +	"encoding/json"
Okay.

2018-10-22 15:27 UTC, maciaszczykm commented on api/pkg/handler/cluster_test.go
> +			ExistingKubermaticObjects: func() []runtime.Object {
Done.

2018-10-22 15:31 UTC, maciaszczykm commented on api/pkg/handler/routes_v1.go
> +//     Patches the given cluster.
Done.

2018-10-22 15:31 UTC, maciaszczykm commented on api/pkg/handler/cluster.go
> +		return filterAndConvertInternalClusterToExternal(updatedCluster), nil
Done.

2018-10-22 20:08 UTC, p0lyn0mial commented on api/pkg/api/v1/types.go
> +	TenantID        string `json:"tenantID"`
I guess we cannot remove the additional fields until the dashboard switches to PATCH endpoint ?

2018-10-23 07:12 UTC, maciaszczykm commented on api/pkg/api/v1/types.go
> +	TenantID        string `json:"tenantID"`
Yes, this data is currently used on Dashboard side not only in wizard, so it would be safer to do changes on Dashboard side first and then remove it step by step. I wanted to be careful here :)

2018-10-23 09:02 UTC, p0lyn0mial approved these changes

2018-10-23 09:13 UTC, merged