ensure that the logging stack is deployed
kubermatic/kubermatic pull request #2316
Opened 2018-10-29 14:12 UTC by xrstf

**What this PR does / why we need it**:
For whatever reason the logging stack is only deployed to dev but not to cloud. This PR changes that. Having logs available across pod reschedules makes debugging alerts easier.

**Release note**:
```release-note
NONE
```

2018-10-29 15:37 UTC, kdomanski requested changes
6x `s/monitoring/logging/`

2018-10-29 16:25 UTC, xrstf commented
What an embarrassing brainfart that was...

2018-10-29 17:52 UTC, mrIncompetent approved these changes

2018-10-30 13:39 UTC, kdomanski approved these changes

2018-10-30 13:48 UTC, merged

2018-11-20 18:17 UTC, kdomanski commented
/cherry-pick release/v2.8