prevent CSRF attack using Double Submit Cookies solution
kubermatic/kubermatic pull request #2360
Opened 2018-11-15 08:41 UTC by zreigz

**What this PR does / why we need it**:
The implemented solution protects the `kubeconfig` endpoint against CSRF attack using Double Submit Cookies solution.
In this technique, we send a random value in both a cookie and as a request parameter, with the server verifying if the cookie value and request value match.

**Release note**:
```release-note
NONE
```

2018-11-15 09:24 UTC, mrIncompetent commented on api/pkg/handler/kubeconfig.go
> +var secureCookie = securecookie.New(securecookie.GenerateRandomKey(32), nil)
We run multiple instances of the API.
Does this lead to decode errors as we have a different random key per instance?

2018-11-15 09:34 UTC, zreigz commented on api/pkg/handler/kubeconfig.go
> +var secureCookie = securecookie.New(securecookie.GenerateRandomKey(32), nil)
Good point.
This hash key value should not be also hardcoded, so I will add a new parameter to pass this to API server

2018-11-15 10:47 UTC, bashofmann commented on api/pkg/handler/kubeconfig.go
> +		cookie := &http.Cookie{
For increased security, `SameSite` and `HttpOnly` and `Secure` should be set as well

2018-11-16 08:29 UTC, zreigz commented on api/pkg/handler/kubeconfig.go
> +		cookie := &http.Cookie{
Funny thing golang 1.10 doesn't support `SameSite` field. After updating our linter to version 1.11 the CI have passed.

2018-11-16 08:29 UTC, zreigz commented
@mrIncompetent @bashofmann PTAL

2018-11-20 19:24 UTC, p0lyn0mial requested changes
nice pull, I have a few minor comments and this lgtm.

2018-11-20 19:24 UTC, p0lyn0mial commented on api/pkg/handler/kubeconfig.go
> +	if encoded, err := secureCookie.Encode(csrfCookieName, value); err == nil {
please handle error

2018-11-20 19:24 UTC, p0lyn0mial commented on api/cmd/kubermatic-api/options.go
> +		if len(o.oidcIssuerCookieHashKey) == 0 {
should we validate the key ? are there any constraints other than the recommended length (https://github.com/gorilla/securecookie/blob/master/securecookie.go#L124)?

2018-11-20 19:24 UTC, p0lyn0mial commented on api/pkg/handler/kubeconfig.go
>  func encodeKubeconfigDoINeddAcditional(c context.Context, w http.ResponseWriter, response interface{}) (err error) {
can we change the name ? for example `encodeOIDCKubeconfig` ?

2018-11-20 19:24 UTC, p0lyn0mial commented on api/pkg/handler/kubeconfig.go
> +				value := make(map[string]string)
does it have to be a `map` ?  how about passing just a `string` ?

2018-11-21 07:43 UTC, zreigz commented on api/pkg/handler/kubeconfig.go
> +				value := make(map[string]string)
done

2018-11-21 07:43 UTC, zreigz commented on api/pkg/handler/kubeconfig.go
>  func encodeKubeconfigDoINeddAcditional(c context.Context, w http.ResponseWriter, response interface{}) (err error) {
done

2018-11-21 07:44 UTC, zreigz commented on api/cmd/kubermatic-api/options.go
> +		if len(o.oidcIssuerCookieHashKey) == 0 {
It is up to the operator. We don't have any restriction in the code for secrets. It is rather a recommendation. I added an additional description for options parameter

2018-11-21 07:44 UTC, zreigz commented on api/pkg/handler/kubeconfig.go
> +	if encoded, err := secureCookie.Encode(csrfCookieName, value); err == nil {
done

2018-11-21 07:45 UTC, zreigz commented
@p0lyn0mial thanks for the review, PTAL

2018-11-21 08:39 UTC, p0lyn0mial approved these changes

2018-11-21 08:46 UTC, merged