Evolve kubermatic-e2e to more general purpose tool
kubermatic/kubermatic pull request #2364
Opened 2018-11-16 12:37 UTC by kron4eg

**What this PR does / why we need it**:

**Release note**:
```release-note
NONE
```

2018-11-19 12:02 UTC, glower commented
LGTM, will try it out today.

2018-11-20 09:12 UTC, glower submitted a review, later dismissed
LGTM but let @mrIncompetent to have a look

2018-11-20 21:40 UTC, alvaroaleman commented on api/cmd/kubermatic-e2e/cluster_creator.go
> -	execCtx, execCancel := context.WithTimeout(ctx, ctl.runOpts.GinkgoTimeout)
How would in this scenario Ginkgo be called? Manually after a cluster was created?

2018-11-21 09:29 UTC, kron4eg commented on api/cmd/kubermatic-e2e/cluster_creator.go
> -	execCtx, execCancel := context.WithTimeout(ctx, ctl.runOpts.GinkgoTimeout)
Yes manually, kubermatic-e2e will dump usercluster's admin kubeconfig, that subsequent tools can use to access created cluster.

EDIT:
manually in CI/CD scenario means steps :)

2018-11-21 10:10 UTC, p0lyn0mial commented on api/pkg/resources/cluster/cluster.go
> +func Spec(apiCluster apiv1.Cluster, cloudProviders map[string]provider.CloudProvider) (*kubermaticv1.ClusterSpec, error) {
what's the purpose of `resources` pkg in general ?

2018-11-21 10:10 UTC, p0lyn0mial commented on api/cmd/kubermatic-e2e/README.md
> +Usage of kubermatic-e2e:
should we change the name to `kubermatic-cluster-creator` ?

2018-11-21 10:36 UTC, kron4eg commented on api/cmd/kubermatic-e2e/README.md
> +Usage of kubermatic-e2e:
maybe, I'm open to suggestions

2018-11-21 10:42 UTC, alvaroaleman commented on api/cmd/kubermatic-e2e/cluster_creator.go
> -	execCtx, execCancel := context.WithTimeout(ctx, ctl.runOpts.GinkgoTimeout)
Yeah. Let's maybe have a chat on this next week or Friday, so @mrIncompetent can participate. Right now this breaks the way we run our e2e tests and does not update the docs, so in the current form it can not be merged

2018-11-21 10:43 UTC, kron4eg commented on api/pkg/resources/cluster/cluster.go
> +func Spec(apiCluster apiv1.Cluster, cloudProviders map[string]provider.CloudProvider) (*kubermaticv1.ClusterSpec, error) {
I'm not really sure, but apparently it's a warehouse for generated "resources" (configs, secrets, CRDs)

2018-11-21 10:43 UTC, alvaroaleman requested changes
At least the docs on how to run e2e tests must be updated

2018-11-21 11:25 UTC, kron4eg commented on api/cmd/kubermatic-e2e/cluster_creator.go
> -	execCtx, execCancel := context.WithTimeout(ctx, ctl.runOpts.GinkgoTimeout)
I had impression that kubermatic-e2e is not used anymore by out CI and was replaced by `api/cmd/conformance-tests` o_O

2018-11-21 13:22 UTC, p0lyn0mial commented on api/pkg/resources/cluster/cluster.go
> +func Spec(apiCluster apiv1.Cluster, cloudProviders map[string]provider.CloudProvider) (*kubermaticv1.ClusterSpec, error) {
Just thinking if it is okay if this pkg deals with api (external) types not crds (internal) :) ?

2018-11-21 13:24 UTC, p0lyn0mial commented on api/cmd/kubermatic-e2e/README.md
> +Usage of kubermatic-e2e:
will this tool run any tests ? if not then we could change the name if yes then we don't have to :)

2018-11-21 13:28 UTC, kron4eg commented on api/pkg/resources/cluster/cluster.go
> +func Spec(apiCluster apiv1.Cluster, cloudProviders map[string]provider.CloudProvider) (*kubermaticv1.ClusterSpec, error) {
there is similar package, but to deal with machines CRDs `api/pkg/resources/machine`, and it's used in kubermatic-e2e too.

2018-11-21 13:34 UTC, kron4eg commented on api/cmd/kubermatic-e2e/cluster_creator.go
>  	}
@alvaroaleman BTW, here I've used `github.com/kubermatic/kubermatic/api/pkg/resources/machine.Machine()` directly, should it be replaced with `.MachineDeployment()` instead?

2018-11-21 13:36 UTC, kron4eg commented
@alvaroaleman kubermatic-e2e is not used in our pipeline anymore

2018-11-21 13:48 UTC, kron4eg commented on api/cmd/kubermatic-e2e/README.md
> +Usage of kubermatic-e2e:
It used to run conformance tests, but not anymore. Conformance tests now run by the [new tool](https://github.com/kubermatic/kubermatic/tree/master/api/cmd/conformance-tests).
New purpose of this tool is to provide ability for end-users of kubermatic to create user-clusters  in their pipelines. But I don't have good names at the moment.

2018-11-21 17:18 UTC, alvaroaleman commented on api/cmd/kubermatic-e2e/cluster_creator.go
>  	}
Yeah I think that makes sense

2018-11-21 17:21 UTC, alvaroaleman commented
@kron4eg I see. Generally speaking I am not opposed to this but I would like to have an open discussion first as for what gurantees in terms of compatibility we provide and do not provider. Also, who gets to use this tool in the end.

BTW by now we should probably rename the tool since it doesn't do any testing anymore, maybe just `kubermatic-cli`?

2018-11-21 19:36 UTC, kron4eg commented
> @kron4eg I see. Generally speaking I am not opposed to this but I would like to have an open discussion first as for what gurantees in terms of compatibility we provide and do not provider.

So, currently input specs are just HTTP models (which are supposedly stable). At this stage we don't promise anything, simply because we have to use internal cluster-api objects (even then are hidden behind resources/machines and resources/cluster facades). Once we will have Service Accounts, we will be able to fully utilize API — the we will continue to use same HTTP models but obviously — no direct cluster-api object, and THEN we will be able to promise something.

>Also, who gets to use this tool in the end.

One of our customers with pretty complex setup. For time being, it's enough for them to have what this tool provides. Later (with SAs in place) we will migrate them to actual `kubermatic-cli`.

> BTW by now we should probably rename the tool since it doesn't do any testing anymore, maybe just `kubermatic-cli`?

In absence of Service Accounts I don't think we can call it like this. `kubermatic-cli` should have subcommands for all those manipulations and listings that API allow, that's entirely different story and tool.

EDIT:
Consider this tool as "temporary" stub, that we have to use before we get proper service accounts. Once we have SAs, we should remove it entirely. But the thing is that we don't have SAs even planned.

2018-11-22 14:05 UTC, kron4eg commented
Currently blocked by https://github.com/kubermatic/kubermatic/pull/2389

2018-11-22 16:31 UTC, kron4eg commented
In order to maintain compatibility with 2.8 release, this PR will only do direct manipulations with cluster-api Machine objects.

After merge and cherry-pick to 2.8 release branch, there will be follow-up PR with cluster-api machineDeployment to master.

2018-11-22 16:48 UTC, alvaroaleman commented
@kron4eg Please rename the tool to `kubermatic-cli`, other than that, LGTM :+1:

2018-11-22 16:50 UTC, kron4eg commented
> @kron4eg Please rename the tool to `kubermatic-cli`, other than that, LGTM 👍

That name implies so much responsibility :D but OK.

2018-11-22 17:03 UTC, alvaroaleman commented on api/cmd/kubermatic-cli/cluster_creator.go
>  	"time"
Shouldn't we also move this to `kubermatic-cli`?

2018-11-22 19:58 UTC, kron4eg commented on api/cmd/kubermatic-cli/cluster_creator.go
>  	"time"
Sorry, I didn’t get it. What move? Where?

2018-11-22 22:56 UTC, alvaroaleman commented on api/cmd/kubermatic-cli/cluster_creator.go
>  	"time"
nvm, my github review plugin shows me the file `api/cmd/kubermatic-e2e/e2e_test_runner.go` as still existing but thats not the case, seems to be some bug with that plugin

2018-11-23 10:09 UTC, mrIncompetent commented
Code looks good :)
It would have been great if the Makefile changes would be extracted into a dedicated PR, but i won't block this PR because of it.

I'm fine with pushing this out as a very early experimental tool - It would give us early feedback.
But we should avoid giving any guarantee on this CLI.

2018-11-23 10:10 UTC, mrIncompetent commented
Please state in the Release note that this is an experimental CLI

2018-11-23 11:08 UTC, kron4eg commented
@mrIncompetent done

2018-11-23 12:17 UTC, mrIncompetent approved these changes

2018-11-23 12:22 UTC, alvaroaleman approved these changes

2018-11-23 13:13 UTC, p0lyn0mial approved these changes

2018-11-23 13:14 UTC, merged