kubernetes api deployment can setup openID connect
kubermatic/kubermatic pull request #2370
Opened 2018-11-20 13:13 UTC by zreigz

**What this PR does / why we need it**: configure k8s API server settings in clusters to accept OpenID. The OIDC settings are optional and can be enabled by passing additional command line flags.

```release-note
Kubernetes API servers can now be used with OpenID authentication
[ACTION REQUIRED] to enable the OpenID for kubernetes API server the users must set `-feature-gates=OpenIDConnectTokens=true` and provide `-oidc-issuer-url`, `-oidc-issuer-client-id` when running the controller.
```

2018-11-20 20:55 UTC, p0lyn0mial requested changes

2018-11-20 20:55 UTC, p0lyn0mial commented on api/cmd/kubermatic-controller-manager/options.go
> +			return fmt.Errorf("%s feature is enabled but \"oidc-issuer-client-id\" flag was not specified", OpenIDConnectTokens)
I think that we would like to pass one more flag `--oidc-ca-file` as described in the proposal https://github.com/kubermatic/kubermatic/blob/master/docs/proposals/user-cluster-authentication-via-dex.md

2018-11-20 20:55 UTC, p0lyn0mial commented on api/cmd/kubermatic-controller-manager/options.go
> +		if len(o.oidcURL) == 0 {
should we validate if `oidcURL` holds a valid URL ?  (using https://golang.org/pkg/net/url/#Parse ?)

2018-11-20 20:55 UTC, p0lyn0mial commented on api/cmd/kubermatic-controller-manager/features.go
> +	OpenIDConnectTokens = "OpenIDConnectTokens"
nit: it actually activates the auth plugin, how about changing this field to `OpenIDAuthPlugin` ?

2018-11-20 20:55 UTC, p0lyn0mial commented on api/pkg/resources/data.go
> +func (d *TemplateData) OIDCConnectEnable() bool {
If you decide to change the name of `OpenIDConnectTokens` then I'd change the name of this function as well, `OIDCAuthPluginEnabled` ?

2018-11-20 20:55 UTC, p0lyn0mial commented on api/pkg/resources/data.go
> +	return d.oidcConnectEnable
instead of defining  a new variable we could determine if the functionality was enabled by `return len(d.oidcURL) > 0 && len(d.oidcIssuerClientID) > 0)`

2018-11-20 20:57 UTC, p0lyn0mial commented on api/cmd/kubermatic-controller-manager/options.go
> +			return fmt.Errorf("%s feature is enabled but \"oidc-issuer-client-id\" flag was not specified", OpenIDConnectTokens)
you could test it by passing letsencrypt's CA - https://letsencrypt.org/certificates/
I think that dex's cert is letsencrypt.

2018-11-20 20:58 UTC, p0lyn0mial commented
@alvaroaleman, @mrIncompetent this is important and has a high priority, so please PTAL.

2018-11-20 21:10 UTC, alvaroaleman commented on api/cmd/kubermatic-controller-manager/main.go
> +	if options.featureGates.Enabled(OpenIDConnectTokens) {
IMHO we should treat the `options` as immutable after we validated them, so can we move this before the validation?

2018-11-20 21:13 UTC, alvaroaleman commented on api/cmd/kubermatic-controller-manager/options.go
> +	oidcURL            string
To me it feels more natural to follow the naming of the `kube-apiserver` which names this option `--oidc-issuer-url`, is there a reason not to do that here?

2018-11-20 21:17 UTC, alvaroaleman commented on api/pkg/resources/apiserver/deployment.go
> +		flags = append(flags, "--oidc-issuer-url", "https://dev.kubermatic.io/dex")
We probably do not want to hardcode this to `dev.kubermatic.io` ;)

2018-11-21 13:15 UTC, zreigz commented on api/pkg/resources/apiserver/deployment.go
> +		flags = append(flags, "--oidc-issuer-url", "https://dev.kubermatic.io/dex")
done

2018-11-21 13:15 UTC, zreigz commented on api/cmd/kubermatic-controller-manager/options.go
> +	oidcURL            string
done

2018-11-21 13:16 UTC, zreigz commented on api/cmd/kubermatic-controller-manager/main.go
> +	if options.featureGates.Enabled(OpenIDConnectTokens) {
this part was removed

2018-11-21 13:16 UTC, zreigz commented on api/pkg/resources/data.go
> +	return d.oidcConnectEnable
done

2018-11-21 13:16 UTC, zreigz commented on api/pkg/resources/data.go
> +func (d *TemplateData) OIDCConnectEnable() bool {
done

2018-11-21 13:16 UTC, zreigz commented on api/cmd/kubermatic-controller-manager/features.go
> +	OpenIDConnectTokens = "OpenIDConnectTokens"
done

2018-11-21 13:16 UTC, zreigz commented on api/cmd/kubermatic-controller-manager/options.go
> +		if len(o.oidcURL) == 0 {
done

2018-11-21 13:17 UTC, zreigz commented on api/cmd/kubermatic-controller-manager/options.go
> +			return fmt.Errorf("%s feature is enabled but \"oidc-issuer-client-id\" flag was not specified", OpenIDConnectTokens)
the flag is added

2018-11-21 14:01 UTC, zreigz commented on api/cmd/kubermatic-controller-manager/options.go
> +	oidcCAFile         string
I think it should be a boolean flag because this file will be from a secret?

2018-11-21 14:05 UTC, p0lyn0mial commented on api/cmd/kubermatic-controller-manager/options.go
> +	oidcCAFile         string
I think so, we could rename it to `skip-oidc-tls-verify` or `insecure-skip-oidc-tls-verify` ? It could be `on` by default.

2018-11-21 16:20 UTC, p0lyn0mial approved these changes
/lgtm
@alvaroaleman please PTAL

@alvaroaleman @zreigz I think we could merge this pull and add TLS verification in a separate pull. I think that the changes we made in this pull don't break anything. WDYT ?

2018-11-21 16:21 UTC, p0lyn0mial commented on api/cmd/kubermatic-controller-manager/options.go
> +	oidcCAFile         string
we could add TLS verification in a separate pull.

2018-11-21 16:24 UTC, zreigz commented
Fine for me. I have been working with new PR and I will add TLS verification + new secret with Dex CA

2018-11-21 17:17 UTC, alvaroaleman approved these changes
lgtm, great work. I am afraid thought we have to wait for @mrIncompetent to approve as he is a codeowner here and also the only one with the required permissions to ignore that check.

Looking forward to have Prow and being able to define multiple codeowners

2018-11-21 17:17 UTC, alvaroaleman commented
@p0lyn0mial  doing tls verification in a separate pull sounds good

2018-11-21 17:24 UTC, mrIncompetent approved these changes

2018-11-21 17:42 UTC, merged