Cleanup MachineDeployments when deleting a cluster
kubermatic/kubermatic pull request #2389
Opened 2018-11-22 12:54 UTC by alvaroaleman

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
NONE
```

2018-11-22 13:09 UTC, mrIncompetent requested changes

2018-11-22 13:09 UTC, mrIncompetent commented on api/pkg/controller/cluster/deleting.go
> +			return nil, fmt.Errorf("failed to delete cluster MachineDeployments: %v", err)
Error message => Could not delete MachineDeployments in user cluster

2018-11-22 13:09 UTC, mrIncompetent commented on api/pkg/controller/cluster/deleting.go
> +		return nil, fmt.Errorf("failed to list cluster MachineDeployments: %v", err)
Error message => Could not list MachineDeployments from user cluster

2018-11-22 13:09 UTC, mrIncompetent commented on api/pkg/controller/cluster/deleting.go
> +		return nil, fmt.Errorf("failed to list cluster MachineDeployments: %v", err)
Or: failed to....

To stick to the existing pattern

2018-11-22 13:09 UTC, mrIncompetent commented on api/pkg/controller/cluster/deleting.go
> +			return nil, fmt.Errorf("failed to delete cluster MachineDeployments: %v", err)
Or: failed to....

To stick to the existing pattern

2018-11-22 13:22 UTC, alvaroaleman commented on api/pkg/controller/cluster/deleting.go
> +			return nil, fmt.Errorf("failed to delete cluster MachineDeployments: %v", err)
That is exactly what I did, if you look at the lines below, the error message there is `failed to list cluster machines: %v`

2018-11-22 13:23 UTC, alvaroaleman commented on api/pkg/controller/cluster/deleting.go
> +		return nil, fmt.Errorf("failed to list cluster MachineDeployments: %v", err)
That is exactly what I did, if you look at the lines below, the error message there is `failed to ldelete cluster machines: %v`

2018-11-22 13:29 UTC, mrIncompetent commented on api/pkg/controller/cluster/deleting.go
> +		return nil, fmt.Errorf("failed to list cluster MachineDeployments: %v", err)
I find the "cluster *" a bit confusing. We use "user cluser" everywhere else to express which cluster is affected

2018-11-22 14:43 UTC, alvaroaleman commented on api/pkg/controller/cluster/deleting.go
> +		return nil, fmt.Errorf("failed to list cluster MachineDeployments: %v", err)
Well I am fine with changing it but then we should change it anywhere. So I will just replace the `cluster` everywhere with `user cluster`?

2018-11-23 16:58 UTC, alvaroaleman commented
@mrIncompetent PTAL, I have updated the error messages and changed the code, to wait for for MachineDeployments and MachineSets to be gone after deleting them

2018-11-23 19:19 UTC, mrIncompetent approved these changes

2018-11-23 19:38 UTC, merged