add TLS verification for dex
kubermatic/kubermatic pull request #2403
Opened 2018-11-26 08:16 UTC by zreigz

**What this PR does / why we need it**:
Since Dex is configured with TLS there is a need to add the CA cert to initiate trust.\
Depends on https://github.com/kubermatic/secrets/pull/204

**Documentation**:
https://github.com/kubermatic/kubermatic/blob/master/docs/proposals/user-cluster-authentication-via-dex.md

**Release note**:
```release-note
Kubermatic controller can now use TLS verification
[Action required] to enable the TLS verification for kubermatic-controller-manager the users must set `-feature-gates=OpenIDAuthPlugin=true` and provide `-oidc-issuer-url`, `-oidc-issuer-client-id` and `--oidc-ca-file` when running the controller.
[Action required] user need CA bundle file with a correct chain of certificates
```

2018-11-26 08:33 UTC, alvaroaleman commented on api/pkg/resources/resources.go
> +	caCertSecret, err := lister.Secrets("oauth").Get(DexCASecretName)
I am not sure if its ideal to hardcode the namespace and name of the Secret. IMHO we should make that a config option that can default to `"oauth/"DexCASecretName`

Also I think it may make sense to check on startup if that secret exists and has the correct key and fail if not, to make errors there obvious

2018-11-26 08:38 UTC, zreigz commented on api/pkg/resources/resources.go
> +	caCertSecret, err := lister.Secrets("oauth").Get(DexCASecretName)
Thanks, I like this idea. It can be configurable and we can check if the correct secret/key exists during the validation.

2018-11-26 14:00 UTC, zreigz commented
@alvaroaleman @p0lyn0mial @mrIncompetent PTAL

2018-11-26 14:54 UTC, p0lyn0mial requested changes

2018-11-26 14:54 UTC, p0lyn0mial commented on api/cmd/kubermatic-controller-manager/options.go
> +	metaV1 "k8s.io/apimachinery/pkg/apis/meta/v1"
nit: we usually group imports, for example https://github.com/kubermatic/kubermatic/blob/81ba106b702ddd39baf3ba32e87160bce2ff7336/api/pkg/controller/rbac/sync_project.go

2018-11-26 14:54 UTC, p0lyn0mial commented on api/cmd/kubermatic-controller-manager/options.go
> +const DexCAFileName = "ca.pem"
make it private, also consider changing the name to `caBundle.pem` just to highlight it can contain a certificate chain.

2018-11-26 14:54 UTC, p0lyn0mial commented on api/cmd/kubermatic-controller-manager/options.go
> +	flag.StringVar(&c.oidcDexSecretCAName, "oidc-dex-secret-ca-name", "oauth/dex-ca", "The secret name which contains CA bundle for TLS verification against dex. This flag is optional. The default value
add a note that the secret key must be `ca.pem` (or `caBundle.pem` if you decide to change it)

2018-11-26 14:54 UTC, p0lyn0mial commented on api/pkg/resources/resources.go
> +	DexCASecretName = "dex-ca"
how do we feel about the fact that the secret we would create in the user's cluster will have a different name than the one provided via the flag ?

2018-11-26 14:54 UTC, p0lyn0mial commented on api/pkg/resources/certificates/dex-ca.go
> +		if _, exists := se.Data[resources.DexCAFileName]; exists {
shouldn't we use `dataCAKey` instead ?

2018-11-26 14:54 UTC, p0lyn0mial commented on api/pkg/resources/certificates/dex-ca.go
> +func GetDexCACreator(name, commonName, dataCAKey string, getCA dexCAGetter) func(resources.SecretDataProvider, *corev1.Secret) (*corev1.Secret, error) {
`commonName` arg is not used.

2018-11-26 14:54 UTC, p0lyn0mial commented on api/pkg/resources/apiserver/deployment.go
> +					MountPath: "/etc/kubernetes/dex/ca",
this path is different than the one passed to `--oidc-ca-file` is this intentional ?

2018-11-26 14:54 UTC, p0lyn0mial commented on api/pkg/resources/data.go
> +func (d *TemplateData) OIDCDexSecretCAName() string {
I think that this method is not used anywhere, what's the purpose of having it then ?

2018-11-26 16:13 UTC, zreigz commented on api/cmd/kubermatic-controller-manager/options.go
> +	metaV1 "k8s.io/apimachinery/pkg/apis/meta/v1"
done

2018-11-26 16:13 UTC, zreigz commented on api/cmd/kubermatic-controller-manager/options.go
> +const DexCAFileName = "ca.pem"
done

2018-11-26 16:13 UTC, zreigz commented on api/cmd/kubermatic-controller-manager/options.go
> +	flag.StringVar(&c.oidcDexSecretCAName, "oidc-dex-secret-ca-name", "oauth/dex-ca", "The secret name which contains CA bundle for TLS verification against dex. This flag is optional. The default value
done

2018-11-26 16:16 UTC, zreigz commented on api/pkg/resources/resources.go
> +	DexCASecretName = "dex-ca"
the flag purpose was to hide hardcoded path to the secret. Because this secret name is for the cluster we should use a constant name like for others to keep consistency

2018-11-26 16:16 UTC, zreigz commented on api/pkg/resources/certificates/dex-ca.go
> +		if _, exists := se.Data[resources.DexCAFileName]; exists {
yes, done

2018-11-26 16:16 UTC, zreigz commented on api/pkg/resources/certificates/dex-ca.go
> +func GetDexCACreator(name, commonName, dataCAKey string, getCA dexCAGetter) func(resources.SecretDataProvider, *corev1.Secret) (*corev1.Secret, error) {
yes, removed

2018-11-26 16:19 UTC, zreigz commented on api/pkg/resources/apiserver/deployment.go
> +					MountPath: "/etc/kubernetes/dex/ca",
this path indicates just directory where secret was mounted. The `--oidc-ca-file` indicates the full path for CA bundle file

2018-11-26 16:19 UTC, zreigz commented on api/pkg/resources/data.go
> +func (d *TemplateData) OIDCDexSecretCAName() string {
yes, removed

2018-11-26 16:41 UTC, zreigz commented
PTAL

2018-11-27 06:55 UTC, zreigz commented on api/cmd/kubermatic-controller-manager/options.go
> +		if !o.skipOidcTLSVerify {
I think the dex secret exists independently on this flag, I should skip this check and move outside the TLS verification

2018-11-27 09:14 UTC, mrIncompetent commented
Is there a specific reason why we load the CA from the Kubernetes API instead of just mounting it?

It feels weird having now 2 sources for the controller input:
- Files passed via flag (ConfigMaps or Secrets, which get mounted to the Pod)
- Files which exist as secret and need to be accessed via the Kubernetes API

2018-11-27 15:22 UTC, zreigz commented
@mrIncompetent @alvaroaleman @p0lyn0mial PTAL

2018-11-27 20:20 UTC, alvaroaleman commented on api/cmd/kubermatic-controller-manager/options.go
> +	f, err := os.Open(o.oidcCAFile)
This should be closed in a `defer` statement

2018-11-27 20:20 UTC, alvaroaleman commented on api/pkg/controller/backup/backup_controller.go
> +	return resources.GetDexCAFromFile(d.oidcCABundleFile)
Why was all this code needed? The backup controller does not seem to be using the`DexCA` anywhere or am I missing it?

2018-11-27 20:20 UTC, alvaroaleman commented on api/pkg/controller/backup/backup_controller.go
> +	return resources.GetDexCAFromFile(d.oidcCABundleFile)
Ah, because we need to satisfy the `SecretDataProvider` interface. Wouldn't it be easier to just implement this as a `return nil, errors.New("not implemented)` and not carry around the `CABundleFile` since we don't use it all?

Not quite sure about this one, what do others think?

2018-11-27 20:20 UTC, alvaroaleman commented on api/pkg/controller/cluster/resources_test.go
> +	file, err := ioutil.TempFile("", "caBundle.pem")
Always close file handlers, please

2018-11-27 20:20 UTC, alvaroaleman commented on api/pkg/resources/kubeconfig_test.go
> +	return []*x509.Certificate{{}}, nil
Nit: You can just `return nil, nil` here

2018-11-27 20:20 UTC, alvaroaleman commented on api/pkg/resources/data.go
> +	return GetDexCAFromFile(d.oidcCAFile)
I think it makes more sense to store the whole `CA` in memory instead of reading it from disk every time it is needed

2018-11-28 07:13 UTC, zreigz commented on api/pkg/controller/backup/backup_controller.go
> +	return resources.GetDexCAFromFile(d.oidcCABundleFile)
yes, I agree I will implement your solution and test it but I also didn't notice the usage for this function in backup controller

2018-11-28 08:35 UTC, zreigz commented on api/pkg/resources/data.go
> +	return GetDexCAFromFile(d.oidcCAFile)
I agree I've put the whole cert into memory. I can revert it if others disagree

2018-11-28 08:43 UTC, zreigz commented on api/pkg/resources/kubeconfig_test.go
> +	return []*x509.Certificate{{}}, nil
done

2018-11-28 08:43 UTC, zreigz commented on api/pkg/controller/cluster/resources_test.go
> +	file, err := ioutil.TempFile("", "caBundle.pem")
done

2018-11-28 08:58 UTC, zreigz commented on api/cmd/kubermatic-controller-manager/options.go
> +	f, err := os.Open(o.oidcCAFile)
done

2018-11-28 09:10 UTC, zreigz commented
PTAL

2018-11-28 09:22 UTC, alvaroaleman commented on api/pkg/resources/resources.go
> +	if dexCACerts == nil {
Is this concurrency-safe? Wouldn't it be cleaner to read the file in the `cmd` and pass it as an arg into the Controller when creating the controller?

2018-11-28 09:23 UTC, mrIncompetent commented on api/cmd/kubermatic-controller-manager/options.go
> +func (o controllerRunOptions) validateDexSecretWithCABundle() error {
Is the function name still correct?
As it does not validate a secret anymore

2018-11-28 09:30 UTC, mrIncompetent commented on api/pkg/resources/data.go
> +	return GetDexCAFromFile(d.oidcCAFile)
My 2 cents:
I think its nice to have it read it from filesystem everytime (It will land in the page cache anyway and we won't cause any disk IO). It avoid having to restart the controller on file change.

Though it differs then from our docker-secret handling - where we load it during startup into memory.

2018-11-28 10:10 UTC, zreigz commented on api/cmd/kubermatic-controller-manager/options.go
> +func (o controllerRunOptions) validateDexSecretWithCABundle() error {
done

2018-11-28 10:13 UTC, zreigz commented on api/pkg/resources/resources.go
> +	if dexCACerts == nil {
I have reverted this for reading from filesystem everytime to avoid having to restart the controller on file change.

2018-11-28 10:42 UTC, alvaroaleman approved these changes

2018-11-28 12:28 UTC, p0lyn0mial requested changes
Please also make sure that the release note is correct.

2018-11-28 12:28 UTC, p0lyn0mial commented on api/cmd/kubermatic-controller-manager/options.go
> +	if err := o.validateCABundle(); err != nil {
shouldn't we validate `caBundle` only if the `OpenIDAuthPlugin` feature has been enabled ?

2018-11-28 12:28 UTC, p0lyn0mial commented on api/hack/run-controller.sh
> +  -oidc-ca-file=../../secrets/seed-clusters/dev.kubermatic.io/caBundle.pem \
`OpenIDAuthPlugin` is optional, I'd rather have all (`oidc-issuer-url` and `oidc-issuer-client-id` ) or nothing. I'm fine with having it `disabled` on the local machine. A small comment explaining how to enable it would be appreciated. Does it make sense ?

2018-11-28 12:45 UTC, zreigz commented on api/cmd/kubermatic-controller-manager/options.go
> +	if err := o.validateCABundle(); err != nil {
We create a cluster dex-ca secret and mount it in cluster api deployment independently even if the `OpenIDAuthPlugin` feature is disabled. It makes  `-oidc-ca-file` mandatory right now. In this case validation is OK

2018-11-28 12:49 UTC, zreigz commented on api/hack/run-controller.sh
> +  -oidc-ca-file=../../secrets/seed-clusters/dev.kubermatic.io/caBundle.pem \
Like in the previous comment it is a mandatory flag. Otherwise, we had to make this configurable: https://github.com/kubermatic/kubermatic/pull/2403/files#diff-a4282b98d1211368af8912d690d2794eR203 and depends on the feature `OpenIDAuthPlugin` we would have to create secret and mount it to the cluster API deployment

2018-11-28 12:50 UTC, p0lyn0mial commented on api/cmd/kubermatic-controller-manager/options.go
> +	if err := o.validateCABundle(); err != nil {
we could make it optional in the deployment too, for example https://github.com/kubermatic/kubermatic/blob/master/config/kubermatic/templates/kubermatic-controller-manager-dep.yaml#L60

so what do you think it is not worth it ?

2018-11-28 13:08 UTC, zreigz commented on api/cmd/kubermatic-controller-manager/options.go
> +	if err := o.validateCABundle(); err != nil {
Yes, but creating cluster secrets in the controller it is not configurable in our source code right now. We create all secrets from the list: https://github.com/kubermatic/kubermatic/blob/ac952343cd56f7c0ead6b3f53949959f4d53e888/api/pkg/controller/cluster/resources.go#L196

So secret can exist in the system even if it's not used

2018-11-28 15:56 UTC, zreigz commented on api/cmd/kubermatic-controller-manager/options.go
> +	if err := o.validateCABundle(); err != nil {
Let's do this in the separate PR

2018-11-28 15:56 UTC, p0lyn0mial approved these changes

2018-11-28 16:00 UTC, mrIncompetent commented on api/hack/run-controller.sh
> +  -oidc-ca-file=../../secrets/seed-clusters/dev.kubermatic.io/caBundle.pem \
@zreigz can you do a follow up PR describing how to get that file?

2018-11-28 16:01 UTC, mrIncompetent approved these changes

2018-11-28 16:03 UTC, merged