Add PATCH endpoint for node deployments
kubermatic/kubermatic pull request #2507
Opened 2018-12-11 15:34 UTC by maciaszczykm

**What this PR does / why we need it**: Adds PATCH endpoint for node deployments to allow updating them.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2453

**Special notes for your reviewer**: It was tested with changes for Dashboard: https://github.com/kubermatic/dashboard-v2/commit/95b39c257a9addafaf3cf5dcf76c2a3cf0fef3e0

I will add some tests.

**Documentation**:

**Release note**:

```release-note
NONE
```

2018-12-12 10:35 UTC, maciaszczykm commented
It is ready for a review.

2018-12-12 12:50 UTC, maciaszczykm commented
/assign @alvaroaleman @p0lyn0mial

2018-12-12 15:51 UTC, alvaroaleman commented
/lgtm

2018-12-12 15:52 UTC, alvaroaleman commented
/approve

2018-12-12 15:52 UTC, alvaroaleman commented
/hold

2018-12-12 15:53 UTC, alvaroaleman commented
Why can I approve for `api/cmd/kubermatic-api/OWNERS` and `api/pkg/handler/OWNERS `? :thinking:

2018-12-13 12:26 UTC, alvaroaleman commented
> Why can I approve for api/cmd/kubermatic-api/OWNERS and api/pkg/handler/OWNERS ? ￼

The reason is this: https://github.com/kubermatic/kubermatic/pull/2513

@p0lyn0mial should also approve, after that, feel free to `/hold cancel`

2018-12-13 13:44 UTC, p0lyn0mial requested changes

2018-12-13 13:44 UTC, p0lyn0mial commented on api/pkg/handler/node_v1.go
> +		cluster, err := clusterProvider.Get(userInfo, req.ClusterID, &provider.ClusterGetOptions{})
please bring back checking if a project exists
`_, err := projectProvider.Get(userInfo, req.ProjectID, &provider.ProjectGetOptions{})`

2018-12-13 13:44 UTC, p0lyn0mial commented on api/pkg/handler/node_v1.go
> +	nodeDeploymentID := mux.Vars(r)["nodedeployment_id"]
do you think we could move it to a separate method so that checking is in one place? Just like we do with `decodeDcReq` and `decodeClusterID`. Changing requires updating `decodeDeleteNodeDeployment`, `decodeGetNodeDeployment` and `decodePatchNodeDeployment`

2018-12-13 13:44 UTC, p0lyn0mial commented on api/pkg/handler/node_v1.go
> +		project, err := projectProvider.Get(userInfo, req.ProjectID, &provider.ProjectGetOptions{})
check if the project exits before getting the cluster (line 913)

2018-12-13 13:44 UTC, p0lyn0mial commented on api/pkg/handler/node_v1.go
> +		md, err = machineClient.ClusterV1alpha1().MachineDeployments(md.Namespace).Update(md)
I am afraid that we can not "patch the machine deployment in that way. Because `Update` means replace and the object we are passing to it is created from `patchedNodeDeployment` which doesn't fully mirror already existing object. We overwrite most fields from `ObjectMetadata` and `Status`, is that correct ?

2018-12-13 13:52 UTC, maciaszczykm commented on api/pkg/handler/node_v1.go
> +		cluster, err := clusterProvider.Get(userInfo, req.ClusterID, &provider.ClusterGetOptions{})
Ah, so this is the purpose of these calls. Didn't check that precisely. I will do it.

2018-12-13 13:53 UTC, maciaszczykm commented on api/pkg/handler/node_v1.go
> +	nodeDeploymentID := mux.Vars(r)["nodedeployment_id"]
Of course.

2018-12-13 14:10 UTC, maciaszczykm commented on api/pkg/handler/node_v1.go
> +		md, err = machineClient.ClusterV1alpha1().MachineDeployments(md.Namespace).Update(md)
You are right, this may bring some issues.

Above lines are used to ensure that most important fields like resource version will not be overridden. They will come from GET that is executed before. I agree that this is not the ideal solution, but the status will be fine anyways. Internal logic will keep it up to date. I was not sure how to solve this, because:

- In the perfect world, I would be able to use PATCH method directly from Machine Deployment endpoint, but we are not exposing structures directly (using internal and external ones, and rightly so). So we have our API that exposes `NodeDeployments` PATCH endpoint, and incoming patch request bodies cannot be easily mapped to call PATCH `MachineDeployment` internally.
- Using current solution is also not the best one because we have to ensure that incoming patch object will not change important fiels (i.e. resource version, status etc.). Concurrency will not be an issue, as concurrent edits will be blocked (resource version has to be latest to update an object).

What if we would allow patching only the `spec` of `NodeDeployment` and get all other information from previous GET?

Do you have any suggestions here?

2018-12-14 11:41 UTC, p0lyn0mial commented on api/pkg/handler/node_v1.go
> +		md, err = machineClient.ClusterV1alpha1().MachineDeployments(md.Namespace).Update(md)
for future reference: we had a chat and decided to update only the spec.

2018-12-14 12:54 UTC, maciaszczykm commented
@p0lyn0mial PTAL

2018-12-14 13:34 UTC, p0lyn0mial requested changes

2018-12-14 13:34 UTC, p0lyn0mial commented on api/pkg/handler/node_v1.go
> +		project, err := projectProvider.Get(userInfo, req.ProjectID, &provider.ProjectGetOptions{})
this line can be removed, since we get project in line `928`

2018-12-14 13:34 UTC, p0lyn0mial commented on api/pkg/handler/node_v1.go
> +		machineDeployment.Spec = patchedMachineDeployment.Spec
I think that detecting updates to other fields than `spec` can be difficult ? If so, I would appreciate a comment (swagger spec) that explains which fields can be updated. If not we could return an error.

2018-12-14 13:34 UTC, p0lyn0mial commented on api/pkg/handler/node_v1_test.go
> +					ObjectMeta: metav1.ObjectMeta{
do you think we could wrap it into `genDefaultMachineDeployment(...)` ? If so I would appreciate updating the tests that use `MachineDeployment`

2018-12-14 13:34 UTC, p0lyn0mial commented on api/pkg/handler/node_v1_test.go
> +			for _, existingMachineDeployment := range tc.ExistingMachineDeployments {
can this be simplified to `machineDeploymentObjets = append(machineDeploymentObjets, tc.ExistingMachineDeployment...)` ?

2018-12-14 13:34 UTC, p0lyn0mial commented on api/pkg/handler/routes_v1.go
> +//     Patches a node deployment that is assigned to the given cluster.
that's the place I would add the comment about what can be updated

2018-12-14 14:00 UTC, maciaszczykm commented on api/pkg/handler/node_v1.go
> +		machineDeployment.Spec = patchedMachineDeployment.Spec
Yep, it would be difficult. I will update comments for swagger.

2018-12-14 14:16 UTC, maciaszczykm commented on api/pkg/handler/node_v1_test.go
> +			for _, existingMachineDeployment := range tc.ExistingMachineDeployments {
Seems like it can't. Types won't match if I try to change it.

2018-12-14 14:34 UTC, maciaszczykm commented
@p0lyn0mial PTAL :)

2018-12-17 08:18 UTC, p0lyn0mial commented
/hold cancel
/approve
/lgtm

2018-12-17 08:19 UTC, merged