optional oidc-ca-file flag
kubermatic/kubermatic pull request #2562
Opened 2019-01-02 10:07 UTC by kgroschoff

paired with @zreigz 

**What this PR does / why we need it**:
Right now the CA bundle file is mandatory to start controller-manger. This file should be optional and set only if we want to enable TLS verification.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2467 

**Special notes for your reviewer**:
/

**Release note**:

```release-note
Setting CA bundle with the `oidc-ca-file flag` is now optional
```

2019-01-02 10:50 UTC, p0lyn0mial reviewed
I think we also need to update the deployment, https://github.com/kubermatic/kubermatic/blob/master/config/kubermatic/templates/kubermatic-controller-manager-dep.yaml#L66

`-oidc-ca-file` should be set when `OpenIDAuthPlugin` feature was enabled. (https://github.com/kubermatic/kubermatic/blob/master/config/kubermatic/templates/kubermatic-controller-manager-dep.yaml#L67)

2019-01-02 10:50 UTC, p0lyn0mial commented on api/pkg/controller/cluster/resources_test.go
> +	for _, op := range GetSecretCreatorOperations(cluster, []byte{}, false) {
could we set it to `true` ? To test `DexCASecret`creation.

2019-01-04 12:49 UTC, kgroschoff commented
@p0lyn0mial done 😃

2019-01-07 11:50 UTC, zreigz commented
additionally, those parts should be also optional:
https://github.com/kubermatic/kubermatic/blob/5c2df77c1f3a2d68cfe8e1d0062fa21ad03aa60d/config/kubermatic/templates/kubermatic-controller-manager-dep.yaml#L95

https://github.com/kubermatic/kubermatic/blob/5c2df77c1f3a2d68cfe8e1d0062fa21ad03aa60d/config/kubermatic/templates/kubermatic-controller-manager-dep.yaml#L148

2019-01-07 14:27 UTC, zreigz commented
Besides of those changes the main functionality works fine

2019-01-07 14:27 UTC, zreigz commented
@kgroschoff PTAL

2019-01-07 15:07 UTC, kgroschoff commented
You're absolutely right, @zreigz . Added it, could you PTAL again? 😄

2019-01-07 15:12 UTC, zreigz requested changes

2019-01-07 15:12 UTC, zreigz commented on api/pkg/controller/cluster/resources.go
> +
Please remove the empty line

2019-01-07 15:14 UTC, zreigz commented
Maybe it would be good also try to rebase this code

2019-01-07 15:19 UTC, kgroschoff commented
@zreigz done 👍

2019-01-07 15:23 UTC, zreigz commented
/lgtm
@p0lyn0mial , please, look again, if we have not forgotten something

2019-01-08 08:32 UTC, p0lyn0mial commented
thank you @kgroschoff and @zreigz for implementing and reviewing.

/lgtm
/approve

2019-01-08 09:49 UTC, zreigz commented
/assign @alvaroaleman

2019-01-08 10:09 UTC, alvaroaleman commented
/approve

2019-01-08 10:10 UTC, merged