Add option to enforce floating IP usage for openstack
kubermatic/kubermatic pull request #2585
Opened 2019-01-07 10:14 UTC by floreks

**What this PR does / why we need it**:

I have added an option to enforce floating IP usage on the datacenter level. Additionally, when creating a node it will be possible to specify `useFloatingIP` field. The user will be able to decide if he wants to assign a floating IP to a new node, but only in case, it is not enforced by the datacenter first.

**Which issue(s) this PR fixes**:
Related to #2439 
Fixes #2544 

**Special notes for your reviewer**: 
#### TODO:
 - [x] Fix existing tests
 - [x] Add/adapt some tests

**Release note**:

```release-note
NONE
```

Should I add a note about adding new field to the API struct?

2019-01-08 10:02 UTC, p0lyn0mial requested changes
I don't see validation code for "adding" and "updating" which should check if an `IPPool` has been assigned when required ("EnforceFloatingIP").

2019-01-08 10:02 UTC, p0lyn0mial commented on api/pkg/api/v1/types.go
> +	UseFloatingIP bool `json:"useFloatingIP,omitempty"`
I'm not sure if I understand why we need this filed, is it because we read it in "Add Node" page ? If yes, isn't that field redundant ? The dashboard knows it because it has access to `Datacenters` and `CloudSpec` files

2019-01-08 10:02 UTC, p0lyn0mial commented on api/pkg/api/v1/types.go
> +		FloatingIPPool: internal.FloatingIPPool,
once set all future nodes will have the same `IPPool` assigned ?

2019-01-08 10:30 UTC, mrIncompetent commented on api/pkg/provider/datacenter_test.go
> +        auth_url: https://api.cbk.cloud.syseleven.net:5000/v3
Please do not hardcode customer names/addresses in our codebase :)

2019-01-08 10:31 UTC, mrIncompetent commented on api/pkg/provider/datacenter_test.go
> +        - "37.123.105.117"
Please use the google DNS servers:
- 8.8.8.8
- 8.8.4.4

2019-01-08 10:31 UTC, mrIncompetent commented on api/pkg/provider/datacenter_test.go
> +    location: Syseleven - dbl1
See https://github.com/kubermatic/kubermatic/pull/2585/files#r245946182

2019-01-08 10:31 UTC, mrIncompetent commented on api/pkg/provider/datacenter_test.go
> +					AuthURL:          "https://api.cbk.cloud.syseleven.net:5000/v3",
See https://github.com/kubermatic/kubermatic/pull/2585/files#r245946182

2019-01-08 10:47 UTC, floreks commented on api/pkg/provider/datacenter_test.go
> +        auth_url: https://api.cbk.cloud.syseleven.net:5000/v3
Damn, you are right. Sorry.

Removed.

2019-01-08 10:53 UTC, floreks commented on api/pkg/api/v1/types.go
> +	UseFloatingIP bool `json:"useFloatingIP,omitempty"`
This structure is sent to the backend when creating a new node. In case datacenter does not enforce floating IP usage, this field directly reflects users' choice whether or not newly created nodes should have a floating IP assigned.

2019-01-08 11:01 UTC, floreks commented on api/pkg/api/v1/types.go
> +		FloatingIPPool: internal.FloatingIPPool,
Actually, no. In [here](https://github.com/kubermatic/dashboard-v2/pull/943/files#diff-92ed9bff35147125e4b965386f6efe7cR49) frontend decides if added checkbox should be disabled based on this information.

Basically, if floating ip pool will not be specified at all, then checkbox will be unchecked and disabled when creating a new node. In case it will be specified, but not enforced by datacenter, then user can decide whether or not he wants to assign a floating IP to the created node.

2019-01-08 11:27 UTC, p0lyn0mial commented on api/pkg/api/v1/types.go
> +	UseFloatingIP bool `json:"useFloatingIP,omitempty"`
oh, so the user can decide not only on a cluster level but also on a node level.

2019-01-08 13:50 UTC, floreks commented on api/pkg/validation/cluster.go
> +		if spec.Openstack.FloatingIPPool == "" && dc.Spec.Openstack != nil && dc.Spec.Openstack.EnforceFloatingIP {
It would be nice to introduce some kind of mini validation framework to simplify code and validation process. Right now it is split into multiple places and a bit confusing. In example [here](https://github.com/kubermatic/kubermatic/blob/master/api/pkg/validation/cluster.go#L187) and [here](https://github.com/kubermatic/kubermatic/blob/master/api/pkg/provider/types.go#L51).

2019-01-09 08:33 UTC, floreks commented
PTAL

2019-01-09 15:20 UTC, mrIncompetent commented on api/pkg/validation/cluster.go
> +		if spec.Openstack.FloatingIPPool == "" && dc.Spec.Openstack != nil && dc.Spec.Openstack.EnforceFloatingIP {
Please create an issue for that so we keep track of this technical dept

2019-01-09 15:21 UTC, mrIncompetent commented
/approve

code looks good, but i'll leave the lgtm to @p0lyn0mial

2019-01-10 08:01 UTC, floreks commented on api/pkg/validation/cluster.go
> +		if spec.Openstack.FloatingIPPool == "" && dc.Spec.Openstack != nil && dc.Spec.Openstack.EnforceFloatingIP {
Done https://github.com/kubermatic/kubermatic/issues/2600

2019-01-10 08:38 UTC, p0lyn0mial commented
/lgtm

2019-01-10 08:39 UTC, p0lyn0mial commented
/approve

2019-01-10 09:27 UTC, merged