Add endpoint to list nodes that belong to the node deployment
kubermatic/kubermatic pull request #2587
Opened 2019-01-08 09:31 UTC by maciaszczykm

**What this PR does / why we need it**: Adds endpoint to list nodes that belong to the node deployment, so we will be able to show them in the UI.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: n/a

**Special notes for your reviewer**: n/a

**Documentation**: n/a

**Release note**:

```release-note
NONE
```

2019-01-08 12:31 UTC, maciaszczykm commented on api/pkg/handler/node_v1.go
> +		listOptions := metav1.ListOptions{LabelSelector: strings.Join(selectors, ", ")}
Using label selector to get only needed machines. With owner refs we'd have to get Machine Set first (download all & filter) and then Machines (download all & filter).

2019-01-08 12:36 UTC, p0lyn0mial commented
ready for review ? (or WIP)

2019-01-08 12:51 UTC, maciaszczykm commented
@p0lyn0mial Ready, only tests are missing.

2019-01-08 13:35 UTC, p0lyn0mial requested changes

2019-01-08 13:35 UTC, p0lyn0mial commented on api/pkg/handler/node_v1.go
> +	"github.com/kubermatic/kubermatic/api/pkg/crd/kubermatic/v1"
grouping :)

2019-01-08 13:35 UTC, p0lyn0mial commented on api/pkg/handler/node_v1.go
> +			selectors = append(selectors, fmt.Sprintf("%s=%s", k, v))
this doesn't look correct unless `len(machineDeployment.Spec.Selector.MatchLabels)` is always 0, appending to already initialises slice adds new entries at the end and can be > `len(machineDeployment.Spec.Selector.MatchLabels)`, if this is not clear I can show you a sample code.

2019-01-08 13:35 UTC, p0lyn0mial commented on api/pkg/handler/node_v1.go
> +		selectors := make([]string, 0, len(machineDeployment.Spec.Selector.MatchLabels))
can we use `labels.SelectorFromSet` form `"k8s.io/apimachinery/pkg/labels` instead ?

2019-01-08 13:35 UTC, p0lyn0mial commented on api/pkg/handler/node_v1.go
> +			node := getNodeForMachine(&machines.Items[i], nodeList.Items)
what if the `node` == `nil`?

2019-01-08 13:35 UTC, p0lyn0mial commented on api/pkg/handler/node_v1.go
> +				return nil, fmt.Errorf("failed to output machine %s: %v", machines.Items[i].Name, err)
do you know what HTTP status this error will produce ?

2019-01-08 15:11 UTC, maciaszczykm commented on api/pkg/handler/node_v1.go
> +			node := getNodeForMachine(&machines.Items[i], nodeList.Items)
Status and name will be empty. It is quite common at the moment, that during first call it will be not created yet.

2019-01-08 15:44 UTC, maciaszczykm commented
PTAL @p0lyn0mial

2019-01-09 09:23 UTC, maciaszczykm commented on api/pkg/handler/node_v1.go
> +				return nil, fmt.Errorf("failed to output machine %s: %v", machines.Items[i].Name, err)
`500: {"error":{"code":500,"message":"failed to output machine venus-1: \u003cnil\u003e"}}`

2019-01-09 09:40 UTC, p0lyn0mial commented on api/pkg/handler/node_v1.go
> +	"k8s.io/apimachinery/pkg/labels"
nit: we usually group imports, can you move it down.

2019-01-09 10:05 UTC, maciaszczykm commented
PTAL @p0lyn0mial

2019-01-09 10:12 UTC, p0lyn0mial commented
/lgtm
/approve

2019-01-09 14:18 UTC, p0lyn0mial approved these changes

2019-01-09 15:39 UTC, maciaszczykm commented
/close
/reopen

2019-01-09 15:39 UTC, maciaszczykm commented
/reopen

2019-01-09 16:31 UTC, maciaszczykm commented
/retest

2019-01-09 17:37 UTC, merged