Implementing an endpoint for project update (rename)
kubermatic/kubermatic pull request #2588
Opened 2019-01-08 10:36 UTC by glower

**What this PR does / why we need it**:
With the new HTTP endpoint it is possible to rename the project

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2510

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
Endpoint PUT /api/v1/projects/{project_id} for a renaming of the project is implemented
```

2019-01-08 10:41 UTC, glower commented
/retest

2019-01-08 10:45 UTC, kdomanski commented on api/hack/run-api.sh
> +  -address=127.0.0.1:8081 \
Why?

2019-01-08 10:47 UTC, glower commented on api/hack/run-api.sh
> +  -address=127.0.0.1:8081 \
it was not intended, will revert this

2019-01-08 10:49 UTC, glower commented on api/hack/run-api.sh
> +  -address=127.0.0.1:8081 \
done

2019-01-08 12:05 UTC, p0lyn0mial requested changes

2019-01-08 12:05 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/project.go
> +func (p *ProjectProvider) Rename(user *kubermaticapiv1.User, projectInternalName, newProjectName string) (*kubermaticapiv1.Project, error) {
could we change the name and the signature of this method so that it knows how to update project resource not only the name ? `For example Update(userInfo *UserInfo, newProject *kubermaticv1.Project) (*kubermaticv1.Project, error)`

have a look on these as a reference
https://github.com/kubermatic/kubermatic/blob/master/api/pkg/provider/types.go#L92
https://github.com/kubermatic/kubermatic/blob/master/api/pkg/provider/types.go#L139

2019-01-08 12:05 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/project.go
> +	for _, project := range projects {
could we extract this logic to a separate method `List` and use it in the handler ?
similarly to https://github.com/kubermatic/kubermatic/blob/master/api/pkg/provider/types.go#L127 and https://github.com/kubermatic/kubermatic/blob/master/api/pkg/provider/types.go#L86

2019-01-08 12:49 UTC, glower commented on api/pkg/provider/kubernetes/project.go
> +func (p *ProjectProvider) Rename(user *kubermaticapiv1.User, projectInternalName, newProjectName string) (*kubermaticapiv1.Project, error) {
Yes, I was not sure about this and just implemented the rename functionality. It makes sense to refactor this to the update function. Will do this

2019-01-08 12:52 UTC, glower commented on api/pkg/provider/kubernetes/project.go
> +	for _, project := range projects {
Yes, I will have a look at how we can simplify the logic here

2019-01-09 15:27 UTC, glower commented on api/pkg/provider/kubernetes/project.go
> +func (p *ProjectProvider) Rename(user *kubermaticapiv1.User, projectInternalName, newProjectName string) (*kubermaticapiv1.Project, error) {
done

2019-01-09 15:27 UTC, glower commented on api/pkg/provider/kubernetes/project.go
> +	for _, project := range projects {
done

2019-01-09 15:31 UTC, glower commented
Some tests are not working correctly so I added a skip to fix it later. I think it is because our fake client not checking RBAC rules (not sure about it). I will create a follow-up task for rather fix the tests or remove it.

2019-01-09 16:27 UTC, kdomanski commented
If the tests are not working then the code is not working. Will not approve until this is resolved.

2019-01-09 18:08 UTC, glower commented
After discussion with @p0lyn0mial we decided to remove these tests, because rbac roles are not enforced/checked in unit tests

2019-01-09 22:31 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/project.go
> +func (p *ProjectProvider) List(user *kubermaticapiv1.User, options *provider.UserProjectsListOptions) ([]*kubermaticapiv1.Project, error) {
I'm sorry but i have just realised that it would be better to use `userInfo *provider.UserInfo` instead of `user *kubermaticapiv1.User` because once we have service accounts they could also map to `UserInfo` which holds only an email and the group and no further changes in the code would be required. 

Do you think we could use `ProjectMemberProvider.List` function https://github.com/kubermatic/kubermatic/blob/master/api/pkg/provider/kubernetes/member.go#L66 to get a list of project a user belongs to ? We could extend `provider.ProjectMemberListOptions` to filter only the owners.

2019-01-09 22:31 UTC, p0lyn0mial commented on api/pkg/handler/project.go
> +		if len(req.Name) != 0 {
nit: not needed it has to be `> 0` because of line 104 ?

2019-01-10 09:18 UTC, glower commented on api/pkg/provider/kubernetes/project.go
> +func (p *ProjectProvider) List(user *kubermaticapiv1.User, options *provider.UserProjectsListOptions) ([]*kubermaticapiv1.Project, error) {
Yes, this makes sense. I will rework the code

2019-01-14 13:39 UTC, p0lyn0mial commented on api/pkg/handler/project.go
> +type UserProjectsListOptions struct {
this doesn't have to be exported.

2019-01-14 13:39 UTC, p0lyn0mial commented on api/pkg/handler/project.go
> +func listUserProjects(email string, projectProvider provider.ProjectProvider, memberMapper provider.ProjectMemberMapper, options *UserProjectsListOptions) ([]*kubermaticapiv1.Project, error) {
I think that for `create` and `update` endpoints we need to get (filter) only projects owned by the user.

2019-01-14 13:39 UTC, p0lyn0mial commented on api/pkg/handler/project_test.go
> +			Name:            "scenario 4: rename a project where user is an editor",
we could remove this test scenario because the test framework doesn't check if the user is an editor or an owner only kube-api server. So this is the same  as `scenario 2`

2019-01-14 13:39 UTC, p0lyn0mial commented on api/pkg/handler/user.go
> +				// return nil, k8cerrors.NewBadRequest("you can only use userInfoMiddleware for endpoints that interact with project")
rm not used code.

2019-01-14 14:54 UTC, glower commented on api/pkg/handler/project.go
> +func listUserProjects(email string, projectProvider provider.ProjectProvider, memberMapper provider.ProjectMemberMapper, options *UserProjectsListOptions) ([]*kubermaticapiv1.Project, error) {
make sense, done

2019-01-14 14:54 UTC, glower commented on api/pkg/handler/project.go
> +type UserProjectsListOptions struct {
fixed

2019-01-14 14:54 UTC, glower commented on api/pkg/handler/user.go
> +				// return nil, k8cerrors.NewBadRequest("you can only use userInfoMiddleware for endpoints that interact with project")
fixed

2019-01-15 08:23 UTC, p0lyn0mial commented on api/pkg/handler/project.go
> +		existingProject, err := listUserProjects(userInfo.Email, projectProvider, memberMapper, &userProjectsListOptions{ProjectName: req.Name, Group: "owners"})
please use `rbac.OwnerGroupNamePrefix` instead.

2019-01-15 08:23 UTC, p0lyn0mial commented on api/pkg/handler/project.go
> +		if len(options.Group) > 0 && !strings.HasPrefix(mapping.Spec.Group, options.Group) {
please use `rbac.ExtractGroupPrefix` and compare prefixes.

2019-01-15 08:59 UTC, glower commented on api/pkg/handler/project.go
> +		if len(req.Name) != 0 {
fixed

2019-01-15 09:00 UTC, glower commented on api/pkg/handler/project_test.go
> +			Name:            "scenario 4: rename a project where user is an editor",
fixed

2019-01-15 12:41 UTC, p0lyn0mial commented on api/pkg/handler/project.go
> +		alreadyExistingProjects, err := projectProvider.List(&provider.ProjectListOptions{ProjectName: req.Name, OwnerUID: user.UID})
@glower i changed the endpoint to get the list of projects directly from the cache - as we agreed offline.

2019-01-15 14:41 UTC, glower commented
lgtm

2019-01-15 14:42 UTC, p0lyn0mial commented
/lgtm
/approve

2019-01-15 16:27 UTC, merged