new endpoint for node deployment events
kubermatic/kubermatic pull request #2647
Opened 2019-01-17 14:30 UTC by zreigz

**What this PR does / why we need it* added new endpoint for node deployment events: `/api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/nodedeployments/{nodedeployment_id}/nodes/events`
Lists node deployment events. If the query parameter `type` is set to `warning` then only warning events are retrieved. If the value `normal`  then normal events are returned. If the query parameter is missing method returns all events.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2635 

**Special notes for your reviewer**:

**Release note**:
```release-note
Added new edpoint: `/api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/nodedeployments/{nodedeployment_id}/nodes/events` with query parameter `type`. When `?type=warning` then endpoint returns only warning type events. When `?type=normal` then endpoint returns only normal type events. Without query parameters the endpoint returns all events.
```

2019-01-18 07:57 UTC, zreigz commented
/retest

2019-01-18 08:09 UTC, zreigz commented
PTAL

2019-01-18 09:11 UTC, maciaszczykm commented on api/pkg/handler/event.go
> +func ToEvent(event corev1.Event) v1.Event {
Can be private?

2019-01-18 09:11 UTC, maciaszczykm commented on api/pkg/handler/event.go
> +func CreateEventList(events []corev1.Event) []v1.Event {
As above.

2019-01-18 09:13 UTC, maciaszczykm commented on api/pkg/handler/node_v1.go
> +func listNodeDeploymentNodesEvents() endpoint.Endpoint {
Can we extract the code from there and `listNodeDeploymentNodes`?

2019-01-18 09:14 UTC, maciaszczykm commented on api/pkg/handler/node_v1_test.go
> +func genTestEvent(eventName, eventType, eventReason, eventMessage string) *corev1.Event {
+1

2019-01-18 09:15 UTC, maciaszczykm commented on api/pkg/api/v1/types.go
> +type Event struct {
I was wondering if we need all these fields, but each one of them seems important.

2019-01-18 09:16 UTC, zreigz commented on api/pkg/handler/node_v1.go
> +func listNodeDeploymentNodesEvents() endpoint.Endpoint {
at least I will create some common method because 70% are equal, thanks

2019-01-18 11:04 UTC, mrIncompetent commented
I'm not a big fan of using an optional bool to express 3 states.
- Not set: Show all
- Set but false: Show only normal events
- Set but true: Show only warning events

I would prefer something like `type={warning|normal}` as its more understandable.

But just a personal opinion - feel free to ignore if you have a strong opinion on that one

2019-01-18 11:08 UTC, mrIncompetent commented on api/pkg/handler/event_test.go
> +func equal(a, b []v1.Event) bool {
Can this be replaced with a deep equal?
https://github.com/kubermatic/kubermatic/blob/master/api/pkg/resources/compare.go#L19

2019-01-18 11:51 UTC, zreigz commented on api/pkg/handler/event_test.go
> +func equal(a, b []v1.Event) bool {
it seems like deep equal has a problem with the uint64 comparison
```
panic: an unexported field was encountered, nested like this:  [recovered]
	panic: an unexported field was encountered, nested like this: uint64 [recovered]
	panic: an unexported field was encountered, nested like this: time.Time -> uint64 [recovered]
	panic: an unexported field was encountered, nested like this: v1.Time -> time.Time -> uint64 [recovered]
	panic: an unexported field was encountered, nested like this: v1.Event -> v1.Time -> time.Time -> uint64 [recovered]
	panic: an unexported field was encountered, nested like this: []v1.Event -> v1.Event -> v1.Time -> time.Time -> uint64 [recovered]
	panic: an unexported field was encountered, nested like this: []v1.Event -> v1.Event -> v1.Time -> time.Time -> uint64
```

2019-01-18 12:12 UTC, mrIncompetent commented on api/pkg/handler/event_test.go
> +func equal(a, b []v1.Event) bool {
Thanks for trying!

2019-01-18 12:13 UTC, zreigz commented on api/pkg/handler/event_test.go
> +func equal(a, b []v1.Event) bool {
I am aware of using deep equal but in this case, it was impossible :(

2019-01-18 12:13 UTC, zreigz commented on api/pkg/handler/event.go
> +func CreateEventList(events []corev1.Event) []v1.Event {
done

2019-01-18 12:13 UTC, p0lyn0mial commented on api/pkg/api/v1/types.go
> +type Event struct {
I’d prefer to start as simple as possible, it’s easier to add new fields than removing. It would be nice to see how dashboard could make use of all that fields. 

The endpoint returns events for all nodes that belongs to a deployment perhaps it would be nice if we could group events by machine. Do you think we could start with something like the following ?

```
[
 {
 “name”: “kubermatic-fznjchfpqg-s549d-8478c84f95-2c2zk.157aed7ac5f5e7b4”,
 “events”: [ “Successfully created instance”, “Found instance at cloud provider” , “Requested an instance at cloud provider”]
 },  
 {“name”: “kubermatic-fznjchfpqg-s549d-8478c84f95-mkfpc.157aede5f061f6a4”,
 “events”: [ “Successfully created instance”, “Found instance at cloud provider” , “Requested an instance at cloud provider”]
 },
]
```
or alternatively we could return events as object so that adding new fields doesn’t require changing dashboard 

```
[
 {
 “name”: “kubermatic-fznjchfpqg-s549d-8478c84f95-2c2zk.157aed7ac5f5e7b4”,
 “events”: [ {“msg”: “Successfully created instance”}, {“msg”: “Found instance at cloud provider”}, {“msg”: “Requested an instance at cloud provider”}]
 },  
 {“name”: “kubermatic-fznjchfpqg-s549d-8478c84f95-mkfpc.157aede5f061f6a4”,
 “events”: [ {“msg”: “Successfully created instance”}, {“msg”: “Found instance at cloud provider”}, {“msg”: “Requested an instance at cloud provider”}]
 },
]
```

2019-01-18 12:13 UTC, zreigz commented on api/pkg/handler/event.go
> +func ToEvent(event corev1.Event) v1.Event {
done

2019-01-18 12:14 UTC, zreigz commented on api/pkg/handler/node_v1.go
> +func listNodeDeploymentNodesEvents() endpoint.Endpoint {
done

2019-01-18 12:19 UTC, zreigz commented on api/pkg/api/v1/types.go
> +type Event struct {
make it simple sounds good. I can do like you described but additionally we can also stick with an event type

2019-01-18 13:46 UTC, zreigz commented
@p0lyn0mial  PTAL
I've simplified result for this:
```
[{"involvedObjectName":"venus-1","events":[{"reason":"Started","message":"message started","type":"Normal"},{"reason":"Killed","message":"message killed","type":"Warning"}]}]
```

2019-01-18 13:52 UTC, p0lyn0mial commented
> [{"involvedObjectName":"venus-1","events":[{"reason":"Started","message":"message started","type":"Normal"},{"reason":"Killed","message":"message killed","type":"Warning"}]}]

@zreigz thx, i'm thinking if we could change `involvedObjectName` to something else, since we know from the HTTP path that the events concern nodes thus we could rename it to `node` or `name` or `nodeName`, wdyt ?

2019-01-18 13:54 UTC, zreigz commented
@p0lyn0mial just `name` sounds good

2019-01-18 13:54 UTC, p0lyn0mial commented
also do you think we could remove `reason` field ? It's hard to find a use case for it. The `message` field gives enough info.

2019-01-18 13:58 UTC, zreigz commented
The reason is strong part of the event structure. This is real example for machine
```
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  1h		10m		21	machine-controller			Warning		CreateError		trying to create a VM: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="SkuNotAvailable" Message="The requested size for resource '/subscriptions/528474a9-8cc6-46c8-9b74-1dbc31c4bb7f/resourceGroups/cluster-npm554cwfr/providers/Microsoft.Compute/virtualMachines/kubermatic-npm554cwfr-b572k-fd57c87f7-jr6tn' is currently not available in location 'westeurope' zones '' for subscription '528474a9-8cc6-46c8-9b74-1dbc31c4bb7f'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.". Unable to create a machine.

```

2019-01-18 14:01 UTC, p0lyn0mial commented
> The reason is strong part of the event structure. 

It's seems like it's meant for computers not humans. We started this pull to give operators/humans more information for troubleshooting.

2019-01-18 14:02 UTC, zreigz commented
OK, I will remove it :)

2019-01-18 14:10 UTC, zreigz commented
@p0lyn0mial PTAL

2019-01-18 14:46 UTC, p0lyn0mial requested changes

2019-01-18 14:46 UTC, p0lyn0mial commented on api/pkg/api/v1/types.go
> +	Name string `json:"Name"`
start with a small letter `json:"name"`

2019-01-18 14:46 UTC, p0lyn0mial commented on api/pkg/handler/node_v1.go
> +			eventList, err := GetMachineEvents(customerClusterClient, machine)
check if `len(eventList) > 0` so that we don't return an empty list`

2019-01-18 14:46 UTC, p0lyn0mial commented on api/pkg/handler/node_v1.go
> +	req.Type = r.URL.Query().Get("type")
check if `type` holds  correct "type" `warning/normal` and return an error if not.

2019-01-18 14:46 UTC, p0lyn0mial commented on api/pkg/handler/event.go
> +
rm an empty line.

2019-01-18 14:46 UTC, p0lyn0mial commented on api/pkg/handler/event.go
> +func GetMachineEvents(client kubernetes.Interface, machine clusterv1alpha1.Machine) (v1.EventList, error) {
Could `event.go` file contain generic methods ? So that they could be reused if we decided to add events for another resource. 

If yes could we move machine specific functions `GetMachineEvents` and `createMachineEventList` to `listNodeDeploymentNodesEvents` ?

2019-01-18 14:46 UTC, p0lyn0mial commented on api/pkg/handler/event_test.go
> +			Name:   "scenario 1, filter out normal event types",
rename to `scenario 2`

2019-01-18 14:46 UTC, p0lyn0mial commented on api/pkg/handler/node_v1_test.go
> +func TestListNodeDeploymentNodesEvents(t *testing.T) {
👍

2019-01-18 15:27 UTC, zreigz commented on api/pkg/handler/event_test.go
> +			Name:   "scenario 1, filter out normal event types",
done

2019-01-18 15:27 UTC, zreigz commented on api/pkg/handler/event.go
> +func GetMachineEvents(client kubernetes.Interface, machine clusterv1alpha1.Machine) (v1.EventList, error) {
done

2019-01-18 15:27 UTC, zreigz commented on api/pkg/handler/event.go
> +
done

2019-01-18 15:27 UTC, zreigz commented on api/pkg/handler/node_v1.go
> +	req.Type = r.URL.Query().Get("type")
done

2019-01-18 15:27 UTC, zreigz commented on api/pkg/handler/node_v1.go
> +			eventList, err := GetMachineEvents(customerClusterClient, machine)
done

2019-01-18 15:27 UTC, zreigz commented on api/pkg/api/v1/types.go
> +	Name string `json:"Name"`
done

2019-01-18 15:28 UTC, zreigz commented
@p0lyn0mial PTAL

2019-01-21 08:46 UTC, p0lyn0mial commented
/lgtm

waiting for others before approving
@maciaszczykm @mrIncompetent PTAL

2019-01-21 08:53 UTC, maciaszczykm commented
/lgtm

2019-01-21 15:42 UTC, mrIncompetent commented
/lgtm

2019-01-21 15:58 UTC, p0lyn0mial commented
/approve

2019-01-21 16:01 UTC, merged