RBAC manager for user cluster
kubermatic/kubermatic pull request #2678
Opened 2019-01-23 15:27 UTC by zreigz

**What this PR does / why we need it**: new RBAC manager for user cluster

Fixes #2696

```release-note
new RBAC manager for user cluster
```

2019-02-01 11:11 UTC, p0lyn0mial requested changes

2019-02-01 11:11 UTC, p0lyn0mial commented on api/cmd/rbac-user-cluster/main.go
> +var (
could we move registration to its own file `register.go` to be consistent with k8s, for example 

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/code-generator/_examples/MixedCase/apis/example/v1/register.go

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/apps/v1/register.go

2019-02-01 11:11 UTC, p0lyn0mial commented on api/cmd/rbac-user-cluster/main.go
> +	schemeBuilder.Register(runtimeObjects...)
could be registered in `init` function https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/code-generator/_examples/MixedCase/apis/example/v1/register.go#L35

2019-02-01 11:11 UTC, p0lyn0mial commented on api/cmd/rbac-user-cluster/controllers.go
> +package main
please add `OWNERS` and `README` files.

2019-02-01 11:11 UTC, p0lyn0mial commented on api/cmd/rbac-user-cluster/controllers.go
> +func AddToManager(m manager.Manager) error {
make it private.

2019-02-01 11:11 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/machinedeployment/controller.go
> +		glog.Fatal(err)
please return the error instead.

2019-02-01 11:11 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/machinedeployment/controller.go
> +type ReconcileMachineDeployment struct {
can we just rename it to `reconciler` ? Initially it's going to watch over `machinedeployments` but later on we could add additional CRDs for example `machines` without creating a new controller. I think that filtering the resources we want to reconcile is enough, wdyt ?

2019-02-01 11:11 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/machinedeployment/controller.go
> +type ReconcileMachineDeployment struct {
perhaps `reconciler` doesn't have to be in its own package `machinedeployment` having it in `rbac_user_cluster` is enough.

2019-02-01 11:11 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/machinedeployment/controller.go
> +
I think that it would be prudent to expose at least one metric reporting health status (can be very primitive) to our monitoring system so that we know that the controller is up and running.

https://github.com/kubermatic/kubermatic/blob/master/api/pkg/controller/rbac/rbac_controller.go#L37


can be implement as a follow-up.

2019-02-01 11:11 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/machinedeployment/controller.go
> +	c, err := controller.New("machinedeployment-rbac-controller", mgr, controller.Options{Reconciler: r})
if we decide to rename the reconciler then we need to change the name of the controller too.

2019-02-01 11:11 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/machinedeployment/reconciler.go
> +		glog.Infof("deleting Role %s", name)
I would suggest removing logging it will be too noisy, although they can be useful for debugging, in that case we could add log level.

2019-02-01 11:11 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/machinedeployment/controller.go
> +			return reconcile.Result{}, err
we definitely want to re-enqueue on certain errors.

2019-02-01 11:11 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/machinedeployment/controller.go
> +		return reconcile.Result{}, nil
we should check the error and try to add the object to the queue. For example we don't have re-enqueue if the resource doesn't exist but we have to in case of timeouts.

2019-02-01 11:11 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/machinedeployment/reconciler.go
> +		return err
in case the role already exits we should make sure that it matches the generated one and hasn't been changed manually.

2019-02-01 11:11 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/machinedeployment/reconciler.go
> +			newRole, err := common.GenerateRBACRole(groupName, policyAPIGroup, []string{"machinedeployments", "machines"})
we watch only for one resource namely `machinedeployments` but here we generate a role for two resources `machinedeployment` and `machines`. Additionally the names are hardcoded but could be taken from  from `crd` argument variable.

2019-02-01 11:11 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/common/mapper.go
> +package common
could we move it to `rbac_user_cluster` pkg ?

2019-02-01 11:13 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/common/mapper.go
> +		return []string{"list", "get", "update", "delete"}, nil
I think that `create` is missing - i'll double check the verbs.

2019-02-01 11:13 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/common/mapper.go
> +		return []string{"list", "get", "update"}, nil
editors can `delete` and `create` too.

2019-02-05 09:17 UTC, zreigz commented on api/cmd/rbac-user-cluster/main.go
> +var (
done

2019-02-05 09:17 UTC, zreigz commented on api/cmd/rbac-user-cluster/controllers.go
> +package main
done

2019-02-05 09:17 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/machinedeployment/controller.go
> +		glog.Fatal(err)
done

2019-02-05 09:17 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/machinedeployment/controller.go
> +			return reconcile.Result{}, err
done

2019-02-05 09:18 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/machinedeployment/controller.go
> +		return reconcile.Result{}, nil
done

2019-02-05 09:18 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/common/mapper.go
> +package common
done

2019-02-05 09:18 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/common/mapper.go
> +		return []string{"list", "get", "update", "delete"}, nil
done

2019-02-05 09:18 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/common/mapper.go
> +		return []string{"list", "get", "update"}, nil
done

2019-02-06 07:34 UTC, zreigz commented on api/cmd/rbac-user-cluster/controllers.go
> +func AddToManager(m manager.Manager) error {
done

2019-02-06 07:34 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/machinedeployment/reconciler.go
> +			newRole, err := common.GenerateRBACRole(groupName, policyAPIGroup, []string{"machinedeployments", "machines"})
done

2019-02-06 07:35 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/machinedeployment/reconciler.go
> +		return err
done

2019-02-06 08:46 UTC, zreigz commented
@p0lyn0mial PTAL

2019-02-07 08:06 UTC, p0lyn0mial commented on api/cmd/rbac-user-cluster/controllers.go
> +		glog.V(0).Info("New controller added")
would be nice if we could print the controller name.

2019-02-07 08:06 UTC, p0lyn0mial commented on api/cmd/rbac-user-cluster/controllers.go
> +func addToManager(m manager.Manager) error {
could we rename it to `registerControllers` ?

2019-02-07 08:06 UTC, p0lyn0mial commented on api/cmd/rbac-user-cluster/controllers.go
> +import (
make sure that imports are correctly grouped, usually it is
```
standard library

external libraries

kubermatic

kubernetes
```

for example
```
	"fmt"
	"strings"

	"github.com/golang/glog"

	kubermaticv1 "github.com/kubermatic/kubermatic/api/pkg/crd/kubermatic/v1"

	rbacv1 "k8s.io/api/rbac/v1"
	"k8s.io/apimachinery/pkg/api/equality
```

2019-02-07 08:06 UTC, p0lyn0mial commented on api/cmd/rbac-user-cluster/main.go
> +	glog.V(0).Info("registering components")
i tried to run the app locally but this line wasn't printed
```
./_build/rbac-user-cluster -logtostderr=1 -v=6
I0207 08:19:21.301974   10603 loader.go:359] Config loaded from file /home/lukasz/.kube/config
```

2019-02-07 08:06 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/apis/apiextensions/v1beta1/register.go
> +package v1beta1
move the pkg to ` api/pkg/controller/rbac-user-cluster/`

2019-02-07 08:06 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/crd/controller.go
> +			//  there is no need to set Requeue to true at the same time as RequeueAfter
I'd add a comment that we would like to investigate how to requeue items in an exponential manner.

2019-02-07 08:06 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/crd/controller.go
> +func Add(mgr manager.Manager) error {
this could return a name of the controller.

2019-02-07 08:06 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/apis/apiextensions/v1beta1/register.go
> +var SchemeGroupVersion = schema.GroupVersion{Group: GroupName, Version: "v1beta1"}
replace with `apiextensionv1beta1.SchemeGroupVersion`

2019-02-07 08:06 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/crd/reconciler.go
> +	crdAPIVersion  = "apiextensions.k8s.io/v1beta1"
use `apiextensionv1beta1.SchemeGroupVersion`

2019-02-07 08:06 UTC, p0lyn0mial commented on api/cmd/rbac-user-cluster/main.go
> +	if err := v1beta1.AddToScheme(mgr.GetScheme()); err != nil {
could this be replaced by `apiextensionv1beta1.AddToScheme(mgr.GetScheme())` ?

2019-02-07 08:06 UTC, p0lyn0mial commented on api/cmd/rbac-user-cluster/main.go
> +	if err := v1beta1.AddToScheme(mgr.GetScheme()); err != nil {
if yes are there any drawbacks ?

2019-02-07 08:06 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/crd/reconciler.go
> +	policyAPIGroup = "cluster.k8s.io"
if possible take the name from a public API just like we can with `apiextensionv1beta1.SchemeGroupVersion`, this also applies to line 20 `crdKind`

2019-02-07 08:06 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/crd/reconciler.go
> +			glog.V(3).Infof("creating a new Role %s", rbacName)
this is debug information, I'd increase the log level to `4`, see https://github.com/eBay/Kubernetes/blob/master/docs/devel/logging.md, you might want to check other places too.

2019-02-07 08:06 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/mapper.go
> +		return []string{"delete", "create", "list", "get", "update"}, nil
verbs for editors are exactly the same as for owners we could remove this line.

2019-02-07 09:30 UTC, zreigz commented on api/cmd/rbac-user-cluster/main.go
> +	glog.V(0).Info("registering components")
It will display but propably later:
```
I0207 09:57:06.305947   16982 loader.go:359] Config loaded from file /home/lukasz/Downloads/kubeconfig-admin-wmvg2rkd6c
I0207 09:57:06.470396   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/api?timeout=32s 200 OK in 163 milliseconds
I0207 09:57:06.495738   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis?timeout=32s 200 OK in 25 milliseconds
I0207 09:57:06.538664   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/api/v1?timeout=32s 200 OK in 28 milliseconds
I0207 09:57:06.585364   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/apiregistration.k8s.io/v1?timeout=32s 200 OK in 27 milliseconds
I0207 09:57:06.614012   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/apiregistration.k8s.io/v1beta1?timeout=32s 200 OK in 27 milliseconds
I0207 09:57:06.646274   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/extensions/v1beta1?timeout=32s 200 OK in 30 milliseconds
I0207 09:57:06.689344   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/apps/v1?timeout=32s 200 OK in 39 milliseconds
I0207 09:57:06.717514   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/apps/v1beta2?timeout=32s 200 OK in 25 milliseconds
I0207 09:57:06.749343   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/apps/v1beta1?timeout=32s 200 OK in 25 milliseconds
I0207 09:57:06.782290   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/events.k8s.io/v1beta1?timeout=32s 200 OK in 28 milliseconds
I0207 09:57:06.968395   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/authentication.k8s.io/v1?timeout=32s 200 OK in 185 milliseconds
I0207 09:57:07.000030   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/authentication.k8s.io/v1beta1?timeout=32s 200 OK in 31 milliseconds
I0207 09:57:07.034938   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/authorization.k8s.io/v1?timeout=32s 200 OK in 33 milliseconds
I0207 09:57:07.062792   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/authorization.k8s.io/v1beta1?timeout=32s 200 OK in 25 milliseconds
I0207 09:57:07.092464   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/autoscaling/v1?timeout=32s 200 OK in 27 milliseconds
I0207 09:57:07.119100   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/autoscaling/v2beta1?timeout=32s 200 OK in 26 milliseconds
I0207 09:57:07.152231   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/autoscaling/v2beta2?timeout=32s 200 OK in 30 milliseconds
I0207 09:57:07.177723   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/batch/v1?timeout=32s 200 OK in 25 milliseconds
I0207 09:57:07.205064   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/batch/v1beta1?timeout=32s 200 OK in 25 milliseconds
I0207 09:57:07.235374   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/certificates.k8s.io/v1beta1?timeout=32s 200 OK in 28 milliseconds
I0207 09:57:07.263362   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/networking.k8s.io/v1?timeout=32s 200 OK in 27 milliseconds
I0207 09:57:07.290954   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/policy/v1beta1?timeout=32s 200 OK in 26 milliseconds
I0207 09:57:07.322305   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/rbac.authorization.k8s.io/v1?timeout=32s 200 OK in 28 milliseconds
I0207 09:57:07.351958   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/rbac.authorization.k8s.io/v1beta1?timeout=32s 200 OK in 28 milliseconds
I0207 09:57:07.378791   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/storage.k8s.io/v1?timeout=32s 200 OK in 26 milliseconds
I0207 09:57:07.406238   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/storage.k8s.io/v1beta1?timeout=32s 200 OK in 25 milliseconds
I0207 09:57:07.434903   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/admissionregistration.k8s.io/v1beta1?timeout=32s 200 OK in 26 milliseconds
I0207 09:57:07.464389   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/admissionregistration.k8s.io/v1alpha1?timeout=32s 200 OK in 27 milliseconds
I0207 09:57:07.494503   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/apiextensions.k8s.io/v1beta1?timeout=32s 200 OK in 29 milliseconds
I0207 09:57:07.525003   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/scheduling.k8s.io/v1beta1?timeout=32s 200 OK in 27 milliseconds
I0207 09:57:07.550856   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/coordination.k8s.io/v1beta1?timeout=32s 200 OK in 25 milliseconds
I0207 09:57:07.583560   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/crd.projectcalico.org/v1?timeout=32s 200 OK in 31 milliseconds
I0207 09:57:07.611589   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/cluster.k8s.io/v1alpha1?timeout=32s 200 OK in 27 milliseconds
I0207 09:57:07.646106   16982 round_trippers.go:405] GET https://wmvg2rkd6c.europe-west3-c.dev.kubermatic.io:30413/apis/metrics.k8s.io/v1beta1?timeout=32s 200 OK in 29 milliseconds
I0207 09:57:07.647989   16982 main.go:27] registering components
I0207 09:57:07.648275   16982 main.go:33] setting up controller
I0207 09:57:07.649064   16982 controllers.go:45] New controller crd-rbac-controller added
```

2019-02-07 11:20 UTC, zreigz commented on api/cmd/rbac-user-cluster/controllers.go
> +		glog.V(0).Info("New controller added")
done

2019-02-07 11:20 UTC, zreigz commented on api/cmd/rbac-user-cluster/controllers.go
> +func addToManager(m manager.Manager) error {
done

2019-02-07 11:20 UTC, zreigz commented on api/cmd/rbac-user-cluster/controllers.go
> +import (
done

2019-02-07 11:20 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/apis/apiextensions/v1beta1/register.go
> +package v1beta1
now it is deleted

2019-02-07 11:20 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/crd/controller.go
> +func Add(mgr manager.Manager) error {
done

2019-02-07 11:20 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/apis/apiextensions/v1beta1/register.go
> +var SchemeGroupVersion = schema.GroupVersion{Group: GroupName, Version: "v1beta1"}
done

2019-02-07 11:21 UTC, zreigz commented on api/cmd/rbac-user-cluster/main.go
> +	if err := v1beta1.AddToScheme(mgr.GetScheme()); err != nil {
works fine with `apiextensionv1beta1.AddToScheme(mgr.GetScheme())`

2019-02-07 11:23 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/crd/reconciler.go
> +	policyAPIGroup = "cluster.k8s.io"
for kind is a problem. Even tests for this package use string with CRD name. There is no const with definition for this

2019-02-07 11:23 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/crd/reconciler.go
> +			glog.V(3).Infof("creating a new Role %s", rbacName)
done

2019-02-07 11:23 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/mapper.go
> +		return []string{"delete", "create", "list", "get", "update"}, nil
done

2019-02-07 11:24 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/crd/reconciler.go
> +	crdAPIVersion  = "apiextensions.k8s.io/v1beta1"
done

2019-02-07 11:25 UTC, zreigz commented
@p0lyn0mial PTAL

2019-02-08 07:54 UTC, p0lyn0mial commented on api/cmd/user-cluster-controller/main.go
> +func main() {
@nikhita this will be our share of the pie, PTAL :)

2019-02-08 07:54 UTC, p0lyn0mial commented on api/cmd/user-cluster-controller/controllers.go
> +	addToManagerFuncs := []func(manager.Manager) (string, error){crd.Add}
here you can register new controllers.

2019-02-08 07:54 UTC, nikhita commented on api/cmd/user-cluster-controller/README.md
> +# rbac-user-cluster
I see the stuff in the cmd as the controller-manager instead of just one controller...can we move this part to where the controller resides? :grimacing:

2019-02-08 07:57 UTC, zreigz commented on api/cmd/user-cluster-controller/README.md
> +# rbac-user-cluster
initially, it was intended for RBAC only, the plan has changed so I will change it

2019-02-08 08:01 UTC, p0lyn0mial commented on api/pkg/controller/user-cluster-controller/crd/controller.go
> +package crd
@zreigz I think we should change the directory name to `rbac-user-cluster`.

2019-02-08 08:04 UTC, zreigz commented on api/pkg/controller/user-cluster-controller/crd/controller.go
> +package crd
yes, I like this idea

2019-02-08 14:57 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/reconciler.go
> +	// TODO replace clientset for sigs.k8s.io/controller-runtime/pkg/client.Client
To use `controller-runtime` client we need newer version at least `v0.1.8` where fakeClient list method was fixed:
https://github.com/kubernetes-sigs/controller-runtime/pull/213
It work with k8s v1.12 and we have v1.11

2019-02-08 15:16 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/reconciler.go
> +	// TODO replace clientset for sigs.k8s.io/controller-runtime/pkg/client.Client
also, it requires newer go-client

2019-02-08 16:25 UTC, zreigz commented
/retest

2019-02-08 16:38 UTC, zreigz commented
/retest

2019-02-08 19:52 UTC, zreigz commented
/retest

2019-02-12 10:45 UTC, alvaroaleman commented on api/cmd/user-cluster-controller-manager/OWNERS
> +  - team-ui
Please add the lifecycle team here, as the files here will be shared once #2671 merges

2019-02-12 11:15 UTC, nikhita commented on api/cmd/user-cluster-controller-manager/OWNERS
> +  - team-ui
@zreigz @p0lyn0mial fwiw, I've rebased my PR on top of this, so there shouldn't be too many merge conflicts.

2019-02-12 12:11 UTC, zreigz commented on api/cmd/user-cluster-controller-manager/OWNERS
> +  - team-ui
team-lifecycle added

2019-02-17 17:49 UTC, alvaroaleman commented on api/pkg/controller/rbac-user-cluster/OWNERS
> +  - team-lifecycle
I actually meant to add `team-lifecycle` to _only_ the `cmd/user-cluster-controller` package as that one is shared, the rbac controller itself is something team-lifecycle should not have approve permissions on IMHO

2019-02-18 08:41 UTC, nikhita commented on api/pkg/controller/rbac-user-cluster/reconciler.go
> +	if !RolesMatches(role, defaultRole) {
Out of curiousity, why don't we directly do a `equality.Semantic.DeepEqual(role, defaultRole)` here?

2019-02-18 09:05 UTC, alvaroaleman commented on api/pkg/controller/rbac-user-cluster/controller.go
> +		}, nil
I _believe_ the only thing that has to be done here is to actually return the error instead of swallowing it, the controller will then call `Reconcile` again: https://github.com/kubernetes-sigs/controller-runtime/blob/bd4677326d3a1e201f986bf798638fd38fbe3680/pkg/reconcile/reconcile.go#L82

CC @nikhita because I believe this has to be fixed in the user cluster controller as well

2019-02-18 09:31 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/controller.go
> +		}, nil
good point, thanks

2019-02-18 09:33 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/reconciler.go
> +	if !RolesMatches(role, defaultRole) {
the `role` object is a full object from API but `defaultRole` is a just template with the most important fields so they don't fully match

2019-02-18 09:39 UTC, alvaroaleman commented on api/pkg/controller/rbac-user-cluster/controller.go
> +		}, nil
Yeah it just uses the `AddRateLimited` from the workqueue if there was an error: https://github.com/kubernetes-sigs/controller-runtime/blob/0dd6edb02bf23e3669a3edc50ef00a38719173b0/pkg/internal/controller/controller.go#L216

2019-02-18 09:43 UTC, nikhita commented on api/pkg/controller/rbac-user-cluster/controller.go
> +		}, nil
Re user cluster controller, it returns an error:

https://github.com/kubermatic/kubermatic/blob/3da7568e8aa898eb836f5182611e8dbc115b56d3/api/pkg/controller/usercluster/controller.go#L54-L58

2019-02-18 09:47 UTC, alvaroaleman commented on api/pkg/controller/rbac-user-cluster/controller.go
> +		}, nil
Maybe just remove the `RequeueAfter` then? It is a no-op right now but would make the code easier to understand if it wasn't there

2019-02-18 09:52 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/controller.go
> +		}, nil
we decided to use `RequeueAfter: requeueAfter1sec` in some unexpected cases like a network problem to delay another check

2019-02-18 09:58 UTC, alvaroaleman commented on api/pkg/controller/rbac-user-cluster/controller.go
> +		}, nil
I would argue every error that happens here is unexpected and the normal backoff mechanism of the q should be used instead of trying to be smarter

2019-02-18 10:00 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/controller.go
> +		}, nil
ok, so I will remove it

2019-02-20 21:53 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/role/reconciler.go
> +			if err := r.client.Create(r.ctx, defaultClusterRole); err != nil {
in what namespace is the role created ?

2019-02-20 21:53 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/role/reconciler.go
> +func (r *reconciler) ensureRBACRole(groupName string) error {
nit: consider changing the name to `ensureRBACClusterRole`.

2019-02-20 21:53 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/role/reconciler.go
> +	err = r.client.Get(r.ctx, controllerclient.ObjectKey{Namespace: metav1.NamespaceAll, Name: defaultClusterRole.Name}, clusterRole)
are we searching for the role in all namespaces ? shouldn't we search `kube-system` only ?

2019-02-20 21:53 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/role/reconciler.go
> +func (r *reconciler) Reconcile() error {
update the comment.

2019-02-20 21:53 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/role/reconciler.go
> +		glog.V(debugLevel).Infof("updating the clusterRole %s because it doesn't match the expected one", defaultClusterRole.Name)
change `clusterRole` to `Cluster Role` as in other places.

2019-02-20 21:53 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/role/controller.go
> +	if err != nil {
seems like this could be simplified to 
```
if !errors.IsNotFound(err) {
return err
}

err := rdr.Reconcile()
return reconcile.Result{}, err
```

2019-02-20 21:53 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/role/controller.go
> +	err = r.Get(r.ctx, request.NamespacedName, cr)
can we throw all roles not in `kube-system` namespace out ?

2019-02-20 21:53 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/role/controller.go
> +	if err != nil {
or even 
```
err := rdr.Reconcile()
return reconcile.Result{}, err
```

because the object we reconcile is not necessarily the one we are interested in, since we watch all roles in a namespace.

2019-02-20 21:53 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/matcher.go
> +func RolesMatches(existingRole, requestedRole *rbacv1.ClusterRole) bool {
nit: rename to `ClusterRoleMatches`

2019-02-20 21:53 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/mapper.go
> +	machinedeployments = "machinedeployments"
not needed anymore.

2019-02-20 21:53 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/rolebinding/reconciler.go
> +		glog.Error("getting  cluster role ", defaultClusterBinding.Name, " failed with error: ", err)
consider changing to `unable to create ClusterRoleBinding because the corresponding ClusterRole doesn't exist`

2019-02-20 21:53 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/rolebinding/reconciler.go
> +	if err := r.client.Get(r.ctx, controllerclient.ObjectKey{Namespace: metav1.NamespaceAll, Name: defaultClusterBinding.Name}, clusterRole); err != nil {
consider adding a comment explaining that if the `ClusterRole` does not exit we will return an error and the request will be retried.

2019-02-20 21:53 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/rolebinding/reconciler.go
> +func (r *reconciler) Reconcile() error {
does it have to be public ?

2019-02-20 21:53 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/rolebinding/reconciler.go
> +	defaultClusterBinding := rbacusercluster.GenerateRBACClusterRoleBinding(groupName)
the corresponding `ClusterRole` could be the owner of the corresponding `ClusterRoleBinding`, consider adding `OwnerReference`.

2019-02-20 22:07 UTC, alvaroaleman commented on api/pkg/controller/rbac-user-cluster/role/controller.go
> +	err = c.Watch(&source.Kind{Type: &rbacv1.ClusterRole{}}, &handler.EnqueueRequestForObject{})
As this controller doesn't reconcile individual ClusterRoles but a set of ClusterRoles, wouldn't it make sense to not use `EnqueueRequestForObject` but something like this to deduplicate  multiple events and make sure only one `Reconcile` is running at a time? https://github.com/kubermatic/kubermatic/pull/2822/files#diff-365f1d5947b4b54405fa2ec44a05e7b4R22

Also, wouldn't it make sense to add a `Predicates` func to the watch so this reconciler only runs if a ClusterRole it cares about got changed, not if any clusterrole got changed?

2019-02-20 22:37 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/role/controller.go
> +	err = c.Watch(&source.Kind{Type: &rbacv1.ClusterRole{}}, &handler.EnqueueRequestForObject{})
Alvaro we are interested in individual ClusterRoles but I think we need to see the whole set (all roles in a namespace) to handle "individual ClusterRoles don't exist" scenario. For example our controller starts and the roles were not created, we need to create them for the first time. I think that `Predicate` for a name would rule out all the roles and nothing would be scheduled.

2019-02-21 07:18 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/role/controller.go
> +	err = c.Watch(&source.Kind{Type: &rbacv1.ClusterRole{}}, &handler.EnqueueRequestForObject{})
regarding `EnqueueRequestsFromMapFunc` if i understand it correctly we could return a list of roles (namespace/name) we would like to additionally enqueue for each event.

2019-02-21 07:39 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/role/controller.go
> +	err = c.Watch(&source.Kind{Type: &rbacv1.ClusterRole{}}, &handler.EnqueueRequestForObject{})
so we would have to implement `EnqueueRequestsFromMapFunc` that would return `[]{'kubermatic:viewers", "kubermatic:owners"}`  and `Predicate` that would be interested ony in resources with the following names `'kubermatic:viewers", "kubermatic:owners"`, is that correct ?

2019-02-21 08:14 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/rolebinding/reconciler.go
> +func (r *reconciler) Reconcile() error {
This is a method from the framework interface

2019-02-21 08:41 UTC, alvaroaleman commented on api/pkg/controller/rbac-user-cluster/role/controller.go
> +	err = c.Watch(&source.Kind{Type: &rbacv1.ClusterRole{}}, &handler.EnqueueRequestForObject{})
Oh you are right regarding using predicates, that would create issues for the initial creation.

> so we would have to implement EnqueueRequestsFromMapFunc that would return []{'kubermatic:viewers", "kubermatic:owners"} and Predicate that would be interested ony in resources with the following names 'kubermatic:viewers", "kubermatic:owners", is that correct ?

No. The `EnqueueRequestsFromMapFunc` basically returns a slice of `type.NamespacedName` and each of these will then trigger a run of the `Reconcile`. If you have a `Reconcile` that `reconciles` exactly one thing (For example the cluster controller does this) then it makes sense to have something like `EnqueueRequestForObject`.

But because this controller reconciles _multiple_ ClusterRoles per `Reconcile` run,  the `types.NamespacedName` that is returned should contain a `const` for Name, to make sure that:

* Only one `Reconcile` runs at a time
* If multiple events happen while a `Reconcile` is running, only one item is put in the Workq


The current approach means:

* On startup, `Reconcile` will get triggered for every existing Clusterrole in the cluster (65 times in the sample cluster I have here)
* Every single change to a ClusterRole will trigger another Reconcile (3 here I believe)

Total of 68 `Reconcile` runs

Whereas with the approach of enq a string constant we would:

* Initially trigger one reconcile, then have the key that is currently being worked on be put onto the workq but not trigger the Reconcile, as it already runs for that key
* All changes to ClusterRoles enq the same string const that is already in the workq so nothing happens

=> Total of two `Reconcile` runs

2019-02-21 09:30 UTC, zreigz commented
/retest

2019-02-21 09:39 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/role/controller.go
> +	err = c.Watch(&source.Kind{Type: &rbacv1.ClusterRole{}}, &handler.EnqueueRequestForObject{})
Alvaro thanks for sharing, this is definitely something we should investigate, if you don't mind as a follow up. We would like to merge this pull to unblock API and testing. 

@zreigz is actually going to work on it right after the merge.

2019-02-21 09:50 UTC, p0lyn0mial commented
/lgtm

@alvaroaleman is there anything else we could improve/fix ?

2019-02-21 09:54 UTC, p0lyn0mial commented on api/pkg/controller/rbac-user-cluster/role/reconciler.go
> +			if err := r.client.Create(r.ctx, defaultClusterRole); err != nil {
this comment is not relevant as `ClusteRole` resources are global/cluster-wide.

2019-02-21 10:19 UTC, alvaroaleman reviewed
I must say I find it very confusing that we have two controllers here. The only advantage of using more than one controller is that it parallelizes things, but performance deoesn't seem to be a concern here. You do know that you can make once controller watch different resources, e.G. one controller can watch both ClusterRoles and ClusterRoleBindings?

The drawback is that a lot more code is required because each controllers needs some scaffolding and understanding the "bigger picture" is rather difficult. But thats your teams call.

2019-02-21 10:19 UTC, alvaroaleman commented on api/pkg/controller/rbac-user-cluster/matcher_test.go
> +package rbacusercluster_test
Is it normal to use a different package name for `_test.go` files? Havent seen that before

2019-02-21 10:19 UTC, alvaroaleman commented on api/pkg/controller/rbac-user-cluster/rolebinding/controller.go
> +	err = c.Watch(&source.Kind{Type: &rbacv1.ClusterRoleBinding{}}, &handler.EnqueueRequestForObject{})
Same as above, `EneueueRequestForObjcet` doesn't really make sense here IMHO

2019-02-21 10:19 UTC, alvaroaleman commented on api/pkg/controller/rbac-user-cluster/rolebinding/reconciler.go
> +		glog.Error("unable to create ClusterRoleBinding because the corresponding ClusterRole doesn't exist")
Why does the ClusterRole have to exist to create the ClusterRoleBinding?

2019-02-21 10:33 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/matcher_test.go
> +package rbacusercluster_test
Using a separate _test package means that user can’t access the unexported fields and functions in the package. The test can see only exported API, so it makes the code more usable, safe and complete.

2019-02-21 12:15 UTC, zreigz commented on api/pkg/controller/rbac-user-cluster/rolebinding/reconciler.go
> +		glog.Error("unable to create ClusterRoleBinding because the corresponding ClusterRole doesn't exist")
done

2019-02-21 12:16 UTC, zreigz commented
@alvaroaleman @p0lyn0mial PTAL

2019-02-21 13:45 UTC, zreigz commented
/retest

2019-02-21 14:24 UTC, alvaroaleman commented
/lgtm
/approve

2019-02-21 14:30 UTC, zreigz commented
/retest

2019-02-21 18:09 UTC, zreigz commented
/retest

2019-02-21 18:15 UTC, zreigz commented
/retest

2019-02-21 18:15 UTC, alvaroaleman commented
@zreigz There is currently a race in the cluster-controller/cloud-controller, which is why we hit AWS ratelimits.  https://github.com/kubermatic/kubermatic/pull/2844 fixes this, until that is merged, retesting will likely not help

2019-02-21 18:18 UTC, zreigz commented
@alvaroaleman thanks :)

2019-02-21 20:44 UTC, alvaroaleman commented
/retest

2019-02-21 21:15 UTC, alvaroaleman commented
/retest

2019-02-22 06:39 UTC, p0lyn0mial commented
/lgtm
/approve

2019-02-22 07:15 UTC, merged