extends user cluster provider component
kubermatic/kubermatic pull request #2684
Opened 2019-01-24 09:50 UTC by p0lyn0mial

**What this PR does / why we need it**: simply extends user cluster provider component so that  additional options to the rest config can be added in a generic way.
 
**Special notes for your reviewer**: see #2680 for more info

**Release note**:

```release-note
NONE
```

2019-01-24 10:47 UTC, p0lyn0mial commented
> pkg/cluster/client/client.go:45:6: type name will be used as client.ClientConfigOption by other packages, and that stutters; consider calling this ConfigOption (golint)
type ClientConfigOption func(*restclient.Config) *restclient.Config
     ^

Dear `golint` don't you dare to educate me about naming conventions in our project.

2019-01-24 11:00 UTC, zreigz requested changes
rest looks good

2019-01-24 11:00 UTC, zreigz commented on api/pkg/cluster/client/client.go
> +// ClientConfigOptions defines a function that applies additional configuration to restclient.Config in a generic way.
change to `ConfigOption`

2019-01-24 11:00 UTC, zreigz commented on api/pkg/provider/types.go
> +	GetAdminKubernetesClientForCustomerCluster(cluster *kubermaticv1.Cluster) (kubernetes.Interface, error)
change doc name `GetClientForCustomerCluster` -> `GetAdminKubernetesClientForCustomerCluster`

2019-01-24 11:03 UTC, zreigz approved these changes
/lgtm

2019-01-24 11:05 UTC, zreigz commented
/lgtm

2019-01-24 11:40 UTC, p0lyn0mial commented
/retest

2019-01-25 09:38 UTC, p0lyn0mial commented
@mrIncompetent PTAL

2019-01-25 12:57 UTC, mrIncompetent commented
/approve

2019-01-25 13:33 UTC, kron4eg commented
/approve

2019-01-25 13:49 UTC, zreigz commented
/approve

2019-01-25 21:18 UTC, p0lyn0mial commented
/retest

2019-01-25 22:36 UTC, merged