Do not tolerate authentication-tolerate-lookup-failure
kubermatic/kubermatic pull request #2760
Opened 2019-02-06 22:08 UTC by alvaroaleman

**What this PR does / why we need it**:

Currently if the lookup of the authentication config lookup fails, the scheduler and controller-manager will just continue starting up, but treat all requests as anonymous and thus deny them. This patch makes a lookup of the authentication config a fatal error.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes the sporadic `Kubernetes scheduler has disappeared from Prometheus target discovery.`

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
none
```

2019-02-06 22:09 UTC, alvaroaleman commented
/cherry-pick release/v2.9

2019-02-06 22:19 UTC, alvaroaleman commented
cc @xrstf

2019-02-06 22:20 UTC, alvaroaleman commented
/assign @mrIncompetent

2019-02-07 06:56 UTC, mrIncompetent requested changes

2019-02-07 06:56 UTC, mrIncompetent commented on api/pkg/resources/scheduler/deployment.go
> +		flags = append(flags, "--authentication-tolerate-lookup-failure", "false")
This flag does not exist in v1.13.0.
It got introduced as a Bugfix with https://github.com/kubernetes/kubernetes/pull/71806

But we can simply omit the flag(for v1.13.0) as failing was the default behavior.

2019-02-07 08:37 UTC, alvaroaleman commented on api/pkg/resources/scheduler/deployment.go
> +		flags = append(flags, "--authentication-tolerate-lookup-failure", "false")
Wow, that is a detailled knowledge of the releases. Will fix it up.

2019-02-07 08:41 UTC, alvaroaleman commented on api/pkg/resources/scheduler/deployment.go
> +		flags = append(flags, "--authentication-tolerate-lookup-failure", "false")
Updated, PTAL

2019-02-07 09:12 UTC, mrIncompetent commented
/lgtm
/approve

2019-02-07 09:12 UTC, mrIncompetent approved these changes

2019-02-07 09:25 UTC, merged

2019-02-07 09:43 UTC, alvaroaleman commented
/cherrypick release/v2.9