Add endpoint to upgrade all node deployments within the cluster
kubermatic/kubermatic pull request #2838
Opened 2019-02-20 13:19 UTC by maciaszczykm

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**: Adds endpoint to upgrade all node deployments within the cluster.

**Documentation**: n/a

**Release note**:

```release-note
NONE
```

2019-02-20 16:49 UTC, p0lyn0mial requested changes

2019-02-20 16:49 UTC, p0lyn0mial commented on api/pkg/handler/upgrade.go
> +			_, err = machineClient.ClusterV1alpha1().MachineDeployments(metav1.NamespaceSystem).Update(&machineDeployment)
before updating we must check if the kubelet version is compatible with the cluster version (use `ensureVersionCompatible` method ?) Would be nice if we could cover this scenario with a unit test.

2019-02-20 16:49 UTC, p0lyn0mial commented on api/pkg/handler/upgrade.go
> +			return nil, fmt.Errorf("failed to update some node deployments: %+q", updateErrors)
how does the client parse the response ? wouldn't be better to return human readable message along with a list of additional errors ? e.g. `{"error": "failed to update some node deployments", "details": ["first error", "second error"]"`

2019-02-22 08:31 UTC, maciaszczykm commented on api/pkg/handler/upgrade.go
> +			return nil, fmt.Errorf("failed to update some node deployments: %+q", updateErrors)
It is parsed like every other error message. Sample notification will show `Error 500: failed to update some node deployments: ["err1", "err2"]`.

2019-02-22 08:54 UTC, maciaszczykm commented on api/pkg/handler/upgrade.go
> +			_, err = machineClient.ClusterV1alpha1().MachineDeployments(metav1.NamespaceSystem).Update(&machineDeployment)
Yes, sure it should be done. I will do it.

2019-02-22 10:52 UTC, maciaszczykm commented on api/pkg/handler/upgrade.go
> +			return nil, fmt.Errorf("failed to update some node deployments: %+q", updateErrors)
Done.

2019-02-22 10:52 UTC, maciaszczykm commented on api/pkg/handler/upgrade.go
> +			_, err = machineClient.ClusterV1alpha1().MachineDeployments(metav1.NamespaceSystem).Update(&machineDeployment)
Done.

2019-02-22 10:53 UTC, maciaszczykm commented
@p0lyn0mial PTAL

2019-02-22 12:07 UTC, p0lyn0mial commented
/lgtm
/approve

2019-02-22 12:59 UTC, merged