fix error handling for getting list of the projects
kubermatic/kubermatic pull request #2885
Opened 2019-02-28 13:57 UTC by zreigz

**What this PR does / why we need it**: deleting projects throw HTTP error 403 because of the impersonated client. Now the method for getting the list of projects prepares custom error with details to give a better overview.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2883 

```release-note
NONE
```

2019-03-01 08:35 UTC, p0lyn0mial requested changes

2019-03-01 08:35 UTC, p0lyn0mial commented on api/pkg/handler/v1/project/project.go
> +			projectInternal, err := projectProvider.Get(userInfo, mapping.Spec.ProjectID, &provider.ProjectGetOptions{IncludeUninitialized: false})
I am afraid that showing only initialised project is going to be confusing for the end users. There will be a window in which the recently added projects will not show up on the list.

The defect we were discussing is different, steps to reproduce:
1. Add a cluster
2. Copy the ID of the cluster
3. Remove the cluster
4. Try to get the cluster

The server responds with `403` (access forbidden) but we would like to return `401` (not found) instead.

2019-03-01 08:38 UTC, zreigz commented on api/pkg/handler/v1/project/project.go
> +			projectInternal, err := projectProvider.Get(userInfo, mapping.Spec.ProjectID, &provider.ProjectGetOptions{IncludeUninitialized: false})
OK, I will try this, thanks

2019-03-05 13:28 UTC, zreigz commented
@p0lyn0mial PTAL

2019-03-08 13:12 UTC, p0lyn0mial requested changes

2019-03-08 13:12 UTC, p0lyn0mial commented on api/pkg/handler/v1/project/project.go
> +				projects = append(projects, convertInternalProjectToExternal(projectInternal, projectOwners))
could you add `continue`  add the end and remove `else` below ? It's hard to read the code.

2019-03-08 13:12 UTC, p0lyn0mial commented on api/pkg/handler/v1/project/project.go
> +				if kubernetesError, ok := err.(*kerrors.StatusError); ok {
I would appreciate if we could make this code more readable, maybe it could be moved to a function ?

2019-03-08 13:12 UTC, p0lyn0mial commented on api/pkg/handler/v1/project/project_test.go
> +			Name:       "scenario 2: list John's projects when the binding exist but project not",
can the described scenario happen in our system ? once a project is removed all its resources are removed too.

2019-03-08 13:12 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/project_test.go
> +	"k8s.io/apimachinery/pkg/api/equality"
group imports

2019-03-08 13:12 UTC, p0lyn0mial commented on api/pkg/handler/v1/project/project.go
> +					if http.StatusForbidden == kubernetesError.Status().Code {
it would be nice if we could add a unit test for it.

2019-03-08 13:12 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/project_test.go
> +				// bob's project
please use `test.GenProject` function, for example:

`test.GenProject("my-first-project", kubermaticapiv1.ProjectActive, test.DefaultCreationTimestamp(), oRef(test.GenDefaultUser())),`

2019-03-08 13:12 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/project_test.go
> +			name:          "scenario 1: get only active project",
update the name, this is `scenario 2`

2019-03-08 13:12 UTC, p0lyn0mial commented on api/pkg/provider/types.go
> +	GetUnsecured(projectInternalName string, options *ProjectGetOptions) (*kubermaticv1.Project, error)
We could move it to a different interface maybe event a new one, just to make it more harder to use. Most endpoints accept `ProjectProvider` and have access to that method immediately. 

We could create a new interface `UnsafeProjectProvider`/`PrivilegedProjectProvider` for `GetUnsecured` method and extend `ListEndpoint` to accept it.

2019-03-11 14:29 UTC, zreigz commented on api/pkg/provider/types.go
> +	GetUnsecured(projectInternalName string, options *ProjectGetOptions) (*kubermaticv1.Project, error)
done

2019-03-11 14:29 UTC, zreigz commented on api/pkg/provider/kubernetes/project_test.go
> +			name:          "scenario 1: get only active project",
done

2019-03-11 14:29 UTC, zreigz commented on api/pkg/provider/kubernetes/project_test.go
> +				// bob's project
done

2019-03-11 14:29 UTC, zreigz commented on api/pkg/handler/v1/project/project_test.go
> +			Name:       "scenario 2: list John's projects when the binding exist but project not",
done

2019-03-12 07:42 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/project.go
> +// PrivilegedProjectProvider
please add a description or remove it.

2019-03-12 07:42 UTC, p0lyn0mial commented on api/pkg/provider/types.go
> +// account for it
remove a line break.

2019-03-12 07:42 UTC, p0lyn0mial commented on api/pkg/handler/v1/project/project.go
> +				if !isStatus(err, http.StatusForbidden) {
Please add  a comment explaining why we are doing this.

2019-03-12 07:42 UTC, p0lyn0mial commented on api/pkg/handler/v1/project/project.go
> +			return projects, errors.NewWithDetails(http.StatusInternalServerError, "failed to get some projects", errorList)
not sure if this is more informative but we could update to error msg to "failed to get some projects, please examine details field for more info"

2019-03-12 07:42 UTC, p0lyn0mial commented on api/pkg/handler/v1/project/project.go
> +				if _, errGetUnsecured := privilegedProjectProvider.GetUnsecured(mapping.Spec.ProjectID, &provider.ProjectGetOptions{IncludeUninitialized: true}); errGetUnsecured != nil {
what do you think about writing a unit test for `ListEndpoint` method providing fake implementations for `providers` ?

2019-03-12 13:33 UTC, zreigz commented on api/pkg/handler/v1/project/project.go
> +				if _, errGetUnsecured := privilegedProjectProvider.GetUnsecured(mapping.Spec.ProjectID, &provider.ProjectGetOptions{IncludeUninitialized: true}); errGetUnsecured != nil {
done

2019-03-12 14:06 UTC, zreigz commented
@p0lyn0mial PTAL

2019-03-12 19:19 UTC, p0lyn0mial commented
@zreigz thanks for addressing the comments and fixing the issue. 

/lgtm
/approve

2019-03-12 19:20 UTC, merged