Create initial node deployment with the cluster
kubermatic/kubermatic pull request #2989
Opened 2019-03-12 16:13 UTC by maciaszczykm

**What this PR does / why we need it**: Contains changes that allow creating initial node deployments with the cluster, in the same requests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: Fixes #2928.

**Special notes for your reviewer**: Has to be merged at the same time as https://github.com/kubermatic/dashboard-v2/pull/1125.

**Documentation**: n/a

**Release note**:

```release-note
Initial node deployments are now created with the cluster.
```

2019-03-13 21:41 UTC, p0lyn0mial commented on api/pkg/handler/v1/cluster/cluster.go
> +			// TODO: we could extend the cluster health to report when the controller has finished generating RBAC
Checking `Status.Health.AllHealthy()` is not enough. Since we use an impersonated client, RBAC has to be generated before we open a connection the cluster otherwise we might get occasionally 403. 

@mrIncompetent do you think we could extend cluster health to also include RBAC readiness in the cluster ?

2019-03-14 07:39 UTC, mrIncompetent commented on api/pkg/handler/v1/cluster/cluster.go
> +			// TODO: we could extend the cluster health to report when the controller has finished generating RBAC
I think we need such a "checkpoint" on the cluster.

But:
The necessary RBAC permissions are being applied by a controller which has no access to the actual cluster object?

2019-03-14 08:13 UTC, p0lyn0mial commented on api/pkg/handler/v1/cluster/cluster.go
> +			// TODO: we could extend the cluster health to report when the controller has finished generating RBAC
> The necessary RBAC permissions are being applied by a controller which has no access to the actual cluster object?

I think so, the controller (UCCM) runs in `cluster-abc` namespace and adds RBAC to a cluster created by the user.

> I think we need such a "checkpoint" on the cluster.

Not sure if this is the best solution, all I'm saying is that we need a way to know that UCCM has finished his job before we say that the cluster is ready.

2019-03-14 12:32 UTC, mrIncompetent commented on api/pkg/handler/v1/cluster/cluster.go
> +			// TODO: we could extend the cluster health to report when the controller has finished generating RBAC
> Not sure if this is the best solution, all I'm saying is that we need a way to know that UCCM has finished his job before we say that the cluster is ready.

But how do we know its ready?
The 2 potential solutions which come to my mind here:
- Lets the UCCM write a condition in the cluster object when it successfully completed the sync loop
  - This has the downside that we now need to make the UCC "seed cluster aware" which means we need to talk to 2 clusters now. 
- Let the UCCM write some checkpoint resource in the cluster which gets checked by the cluster controller
  - The cluster controller does a "is reachable" check during each sync anyway

2019-03-15 09:15 UTC, p0lyn0mial commented on api/pkg/handler/v1/cluster/cluster.go
> +			// TODO: we could extend the cluster health to report when the controller has finished generating RBAC
since the CM connects to the clusters anyway the second option seems compelling. It could read a "checkpoint" resource and report the status back all the way up to the method that checks if the cluster is healthy.

2019-03-15 15:13 UTC, maciaszczykm commented
Added metric to report the number of failures. How do we add them to alert manager?

/hold

2019-03-15 15:20 UTC, maciaszczykm commented
/retest

2019-03-18 07:55 UTC, maciaszczykm commented
PTAL @p0lyn0mial

2019-03-18 08:01 UTC, mrIncompetent commented on api/pkg/handler/v1/cluster/cluster.go
> +			// TODO: we could extend the cluster health to report when the controller has finished generating RBAC
Sounds good, would you mind creating an Issue for that?

2019-03-18 11:35 UTC, p0lyn0mial requested changes

2019-03-18 11:35 UTC, p0lyn0mial commented on api/pkg/handler/v1/cluster/cluster.go
> +	sshKeyProvider provider.SSHKeyProvider, dcs map[string]provider.DatacenterMeta, clusterProvider provider.ClusterProvider, userInfo *provider.UserInfo) {
we need to add a guard here - to recover from a panic, for example we could use `utilruntime.HandleCrash()` ("k8s.io/apimachinery/pkg/util/runtime) or create our own function.

2019-03-18 11:35 UTC, p0lyn0mial commented on api/pkg/handler/v1/cluster/cluster.go
> +// TODO: We can add an event to the cluster after successful creation or failure.
rm the comment.

2019-03-18 11:35 UTC, p0lyn0mial commented on api/pkg/handler/v1/cluster/cluster.go
> +		go createInitialNodeDeployment(&req.Body.NodeDeployment, newCluster, project, sshKeyProvider, dcs, clusterProvider, userInfo)
do we want to make a `NodeDeployment` optional ? If not provided we create a cluster only.

2019-03-18 11:35 UTC, p0lyn0mial commented on api/pkg/handler/v1/cluster/cluster.go
> +	interval := 10 * time.Second
we could use `wait.Poll`(`"k8s.io/apimachinery/pkg/util/wait"`) method instead, wdyt ?

2019-03-18 11:35 UTC, p0lyn0mial commented on api/pkg/metrics/middleware.go
> +var InitNodeDeploymentFailures = prometheus.NewCounterVec(prometheus.CounterOpts{
I would prefer to pass the metric as a dependency to  `CreateEndpoint` function. This file `middleware.go` contains metrics that enhance all HTTP request, whereas we want to add a metric to only one endpoint.

2019-03-18 11:35 UTC, p0lyn0mial commented on api/pkg/metrics/middleware.go
> +	Help: "The number of times initial node deployment couldn't be created within the 5m timeout",
not sure if putting a timeout in the comment is good, it can easily get out of sync with the code.

2019-03-18 11:35 UTC, p0lyn0mial commented on api/pkg/metrics/middleware.go
> +	[]string{"cluster"},
should we also add a data center name so that we can locate the faulty cluster quicker?

/cc @mrIncompetent

2019-03-18 11:35 UTC, p0lyn0mial commented on api/pkg/metrics/middleware.go
> +	Name: "init_node_deployment_failures",
@mrIncompetent  do we want to define an alert for that metric ?

2019-03-18 11:35 UTC, p0lyn0mial commented on api/pkg/resources/machine/machinedeployment.go
> +	"github.com/Masterminds/semver"
we usually group imports, add a new line so that they are separated from std imports.

2019-03-18 11:35 UTC, p0lyn0mial commented on api/pkg/resources/machine/machinedeployment.go
> +			return nil, k8cerrors.NewBadRequest("failed to parse kubelet version: %v", err)
as below.

2019-03-18 11:35 UTC, p0lyn0mial commented on api/pkg/resources/machine/machinedeployment.go
> +			return nil, k8cerrors.NewBadRequest(err.Error())
as below.

2019-03-18 11:35 UTC, p0lyn0mial commented on api/pkg/resources/machine/machinedeployment.go
> +		return nil, k8cerrors.NewBadRequest("node deployment needs to have cloud provider data")
it feels weird to return api errors from a function that is not necessarily called from the API server

2019-03-18 11:35 UTC, p0lyn0mial commented on api/pkg/handler/v1/cluster/cluster.go
> +			metrics.InitNodeDeploymentFailures.With(prometheus.Labels{"cluster": cluster.Name}).Add(1)
could we also add an event to the cluster saying that we were unable to add a ND for the cluster? In the future the dashboard will display events for a cluster.

2019-03-18 11:35 UTC, p0lyn0mial commented on api/pkg/handler/v1/cluster/cluster.go
> +	timeout := 5 * time.Minute
In the worst case scenario, the end user will not receive any status/info back from the API. He might start to think that a ND will not be added to the cluster and could send a new request. I'd add an event saying that a ND is going to be added to the cluster.

2019-03-18 11:37 UTC, mrIncompetent commented on api/pkg/metrics/middleware.go
> +	[]string{"cluster"},
Adding the seed-dc name would be great!

2019-03-18 11:37 UTC, mrIncompetent commented on api/pkg/metrics/middleware.go
> +	Name: "init_node_deployment_failures",
Yes! But we can do that in a follow up in case it would block this PR.
cc @xrstf

2019-03-18 11:38 UTC, p0lyn0mial commented on api/pkg/handler/v1/cluster/cluster.go
> +			// TODO: we could extend the cluster health to report when the controller has finished generating RBAC
sure, np.

2019-03-18 11:39 UTC, maciaszczykm commented on api/pkg/handler/v1/cluster/cluster.go
> +	timeout := 5 * time.Minute
Makes sense. I will add an issue to track this soon.

2019-03-18 11:39 UTC, maciaszczykm commented on api/pkg/handler/v1/cluster/cluster.go
> +	timeout := 5 * time.Minute
`this` means adding events related to initial node deployment creation.

2019-03-18 11:40 UTC, maciaszczykm commented on api/pkg/handler/v1/cluster/cluster.go
> +			metrics.InitNodeDeploymentFailures.With(prometheus.Labels{"cluster": cluster.Name}).Add(1)
Yes, that's why there is a `TODO` above. Would you like to have it as a part of this PR?

2019-03-18 11:41 UTC, maciaszczykm commented on api/pkg/resources/machine/machinedeployment.go
> +		return nil, k8cerrors.NewBadRequest("node deployment needs to have cloud provider data")
True, I will change it.

2019-03-18 11:47 UTC, p0lyn0mial commented on api/pkg/handler/v1/cluster/cluster.go
> +			metrics.InitNodeDeploymentFailures.With(prometheus.Labels{"cluster": cluster.Name}).Add(1)
ah :) Your call :) I'm fine with a follow-up.

2019-03-18 12:48 UTC, p0lyn0mial commented on api/pkg/handler/v1/cluster/cluster.go
> +			// TODO: we could extend the cluster health to report when the controller has finished generating RBAC
added an issue https://app.zenhub.com/workspaces/all-kubermatic-58863654794153994b62af76/issues/kubermatic/kubermatic/3019

2019-03-18 15:08 UTC, maciaszczykm commented on api/pkg/handler/v1/cluster/cluster.go
> +			metrics.InitNodeDeploymentFailures.With(prometheus.Labels{"cluster": cluster.Name}).Add(1)
https://github.com/kubermatic/kubermatic/issues/3027

2019-03-18 15:09 UTC, maciaszczykm commented on api/pkg/handler/v1/cluster/cluster.go
> +	timeout := 5 * time.Minute
https://github.com/kubermatic/kubermatic/issues/3027

2019-03-18 16:07 UTC, maciaszczykm commented on api/pkg/handler/v1/cluster/cluster.go
> +		go createInitialNodeDeployment(&req.Body.NodeDeployment, newCluster, project, sshKeyProvider, dcs, clusterProvider, userInfo)
Yep, could be useful for the future.

2019-03-19 10:52 UTC, maciaszczykm commented
/retest

2019-03-19 11:41 UTC, maciaszczykm commented
PTAL @p0lyn0mial

2019-03-19 12:01 UTC, maciaszczykm commented
If it will be approved I will try to merge in the evening and then UI part as soon as e2e will pass.

2019-03-19 17:01 UTC, p0lyn0mial commented on api/pkg/handler/routes_v1.go
> +	"github.com/prometheus/client_golang/prometheus"
grouping :(

2019-03-19 17:01 UTC, p0lyn0mial commented on api/pkg/handler/v1/cluster/cluster.go
> +			go createInitialNodeDeployment(req.Body.NodeDeployment, newCluster, project, sshKeyProvider, dcs,
we could avoid repeating calling `initNodeDeploymentFailures` in `createInitialNodeDeployment` function by doing:
```
go func() {
 defer utilruntime.HandleCrash()
 err := createInitialNodeDeployment(...)
 if err != . il {
   initNodeDeploymentFailures.With(prometheus.Labels{"cluster": cluster.Name, "seed_dc": seedDC}).Add(1)
 }
}()
```

what do you think ?

2019-03-19 17:01 UTC, p0lyn0mial commented on api/cmd/kubermatic-api/metrics.go
> +	InitNodeDeploymentFailures: prometheus.NewCounterVec(
could you add an item for creating an alert for the metric ?

2019-03-20 07:25 UTC, maciaszczykm commented on api/pkg/handler/routes_v1.go
> +	"github.com/prometheus/client_golang/prometheus"
Sorry... Is there any check for GoLand for it?

2019-03-20 07:44 UTC, p0lyn0mial commented on api/pkg/handler/routes_v1.go
> +	"github.com/prometheus/client_golang/prometheus"
I'm afraid there is not, let me know once you find one :)

2019-03-20 08:23 UTC, maciaszczykm commented on api/cmd/kubermatic-api/metrics.go
> +	InitNodeDeploymentFailures: prometheus.NewCounterVec(
https://github.com/kubermatic/kubermatic/issues/3041

2019-03-20 08:35 UTC, maciaszczykm commented on api/pkg/handler/v1/cluster/cluster.go
> +			go createInitialNodeDeployment(req.Body.NodeDeployment, newCluster, project, sshKeyProvider, dcs,
Awesome, it improves a lot :)

2019-03-20 08:38 UTC, maciaszczykm commented
/retest

2019-03-20 08:52 UTC, maciaszczykm commented
PTAL @p0lyn0mial

2019-03-20 12:27 UTC, p0lyn0mial commented
this lgtm waiting for @mrIncompetent before approval

thanks for the pull :)

2019-03-20 14:17 UTC, mrIncompetent commented on api/cmd/kubermatic-api/metrics.go
> +			Name: "init_node_deployment_failures",
Add `kubermatic_api` to all metric names

2019-03-20 14:19 UTC, mrIncompetent commented on api/cmd/kubermatic-api/metrics.go
> +	prometheus.MustRegister(metrics.InitNodeDeploymentFailures)
For gauge & counter metrics: Initialize them with 0 within the register func:
For example: `metrics.HTTPRequestsTotal.Add(0)`

2019-03-20 14:21 UTC, mrIncompetent commented on api/cmd/kubermatic-api/metrics.go
> +package main
Why not just declare them in the package where they actually get used?

2019-03-20 14:22 UTC, mrIncompetent commented on api/pkg/handler/test/hack/hack.go
> +}
Why only partially initializes this ~metric~ struct?

2019-03-20 14:24 UTC, maciaszczykm commented on api/cmd/kubermatic-api/metrics.go
> +package main
We wanted to group API's metrics in one file. Isn't that good?

cc @p0lyn0mial

2019-03-20 14:24 UTC, mrIncompetent commented on api/pkg/handler/v1/cluster/cluster.go
> +	err = wait.Poll(5*time.Second, 5*time.Minute, initClusterCondition(ctx, cluster.Name, clusterProvider, userInfo))
Can we increase the timeout to 30min ?
If you have new worker nodes which need to pull all images, there's a good chance that it will take >5min

2019-03-20 14:27 UTC, maciaszczykm commented on api/pkg/handler/v1/cluster/cluster.go
> +	err = wait.Poll(5*time.Second, 5*time.Minute, initClusterCondition(ctx, cluster.Name, clusterProvider, userInfo))
Of course, I will do it.

2019-03-20 14:27 UTC, maciaszczykm commented on api/pkg/handler/test/hack/hack.go
> +}
So basically having this init inside a function where we also register the metrics and set counters to 0?

2019-03-20 14:31 UTC, mrIncompetent commented on api/cmd/kubermatic-api/metrics.go
> +package main
I prefer to just add the metrics in the packages where they are actually needed & register them in an init func.
Like: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/controller/cluster/metrics.go

Then you don't need to do any pluming - You now have a hard dependency and there's no easy way to unit-test those, but its easier from my point of view.
But that's just my opinion - this don't must be changed

2019-03-20 14:32 UTC, p0lyn0mial commented on api/pkg/handler/v1/cluster/cluster.go
> +	err = wait.Poll(5*time.Second, 5*time.Minute, initClusterCondition(ctx, cluster.Name, clusterProvider, userInfo))
the timeout (5 min) is for waiting for a cluster to become ready, we are not waiting for worker nodes.

2019-03-20 14:34 UTC, mrIncompetent commented on api/pkg/handler/test/hack/hack.go
> +}
Ah wait, i'm an idiot. That's test code. Sorry :man_facepalming:

2019-03-20 14:35 UTC, mrIncompetent commented on api/pkg/handler/v1/cluster/cluster.go
> +	err = wait.Poll(5*time.Second, 5*time.Minute, initClusterCondition(ctx, cluster.Name, clusterProvider, userInfo))
> the timeout (5 min) is for waiting for a cluster to become ready, we are not waiting for worker nodes.

Misunderstanding:
If the worker nodes of the seed cluster are "fresh" and need to pull the images for the control plane pods, this step can take definitely more than 5min.

2019-03-20 14:36 UTC, p0lyn0mial commented on api/cmd/kubermatic-api/metrics.go
> +			Name: "init_node_deployment_failures",
make sure to update alerts when the name changes.

2019-03-20 14:38 UTC, maciaszczykm commented on api/pkg/handler/v1/cluster/cluster.go
> +	err = wait.Poll(5*time.Second, 5*time.Minute, initClusterCondition(ctx, cluster.Name, clusterProvider, userInfo))
> the timeout (5 min) is for waiting for a cluster to become ready, we are not waiting for worker nodes.

True, perhaps 10 minutes will be a compromise here.

2019-03-20 14:39 UTC, p0lyn0mial commented on api/pkg/handler/v1/cluster/cluster.go
> +	err = wait.Poll(5*time.Second, 5*time.Minute, initClusterCondition(ctx, cluster.Name, clusterProvider, userInfo))
oh, I see, they need to download Kubernetes images. Thanks.

2019-03-20 14:39 UTC, maciaszczykm commented on api/cmd/kubermatic-api/metrics.go
> +	prometheus.MustRegister(metrics.InitNodeDeploymentFailures)
Hmm, what to do with labels? Leave them empty? Seems like there is no Add() method directly on the metric object.

2019-03-20 14:40 UTC, maciaszczykm commented on api/pkg/handler/v1/cluster/cluster.go
> +	err = wait.Poll(5*time.Second, 5*time.Minute, initClusterCondition(ctx, cluster.Name, clusterProvider, userInfo))
Okay, then 30m it is 🙂

2019-03-20 14:41 UTC, p0lyn0mial commented on api/cmd/kubermatic-api/metrics.go
> +package main
no strong opinion here, I figured it would be nice to declare them in the main pkg as it improves readability - you immediately know what type of metrics are collected by the API server.

2019-03-20 14:46 UTC, mrIncompetent commented on api/cmd/kubermatic-api/metrics.go
> +	prometheus.MustRegister(metrics.InitNodeDeploymentFailures)
Ah sh*t.
Haven't noticed that. So my comment is useless, sorry!

2019-03-20 14:46 UTC, maciaszczykm commented on api/cmd/kubermatic-api/metrics.go
> +			Name: "init_node_deployment_failures",
Yep, I did.

2019-03-20 14:46 UTC, maciaszczykm commented on api/pkg/handler/v1/cluster/cluster.go
> +	err = wait.Poll(5*time.Second, 5*time.Minute, initClusterCondition(ctx, cluster.Name, clusterProvider, userInfo))
Done.

2019-03-20 14:48 UTC, mrIncompetent commented
/approve

2019-03-20 14:54 UTC, maciaszczykm commented on api/cmd/kubermatic-api/metrics.go
> +	prometheus.MustRegister(metrics.InitNodeDeploymentFailures)
Okay, thanks, no problem 🙂

2019-03-20 14:55 UTC, p0lyn0mial commented
thanks for reviewing 

/lgtm
/approve

2019-03-20 14:55 UTC, maciaszczykm commented on api/cmd/kubermatic-api/metrics.go
> +package main
3 x no strong opinion 😄 

What about keeping it w/o changes and updating if it won't work for us in the long run?

2019-03-20 15:13 UTC, maciaszczykm commented
Thank you both for review and tips :)

2019-03-20 20:26 UTC, p0lyn0mial commented
@kron4eg could you please tag the pull ?

/hold cancel

2019-03-20 20:43 UTC, kron4eg commented on config/monitoring/prometheus/rules/kubermatic-master-kubermatic.yaml
> +    expr: sum(rate(kubermatic_api_http_requests_total{role="kubermatic-api",code=~"5.."}[5m])) >
* this file is generated (there is a notice in the head: "# This file has been generated, do not edit.")
* renaming `http_requests_total` to `kubermatic_api_http_requests_total` is bad idea in general

2019-03-20 20:43 UTC, kron4eg commented on config/monitoring/prometheus/rules/src/kubermatic-master/kubermatic.yaml
> +    expr: sum(rate(kubermatic_api_http_requests_total{role="kubermatic-api",code=~"5.."}[5m])) > 0.1
same applies here

2019-03-20 20:45 UTC, p0lyn0mial commented on config/monitoring/prometheus/rules/kubermatic-master-kubermatic.yaml
> +    expr: sum(rate(kubermatic_api_http_requests_total{role="kubermatic-api",code=~"5.."}[5m])) >
could you say why renaming is a bad idea ?

2019-03-20 20:48 UTC, kron4eg commented on config/monitoring/prometheus/rules/kubermatic-master-kubermatic.yaml
> +    expr: sum(rate(kubermatic_api_http_requests_total{role="kubermatic-api",code=~"5.."}[5m])) >
* metrics names is public API and need to be threaded the same way
* this breaks ability to aggregate across all `http_requests_total` from all the services
* it adds nothing (we were able to filter only to kubermatic `http_requests_total{role="kubermatic-api"}` previously just fine)

2019-03-21 06:29 UTC, maciaszczykm commented on config/monitoring/prometheus/rules/kubermatic-master-kubermatic.yaml
> +    expr: sum(rate(kubermatic_api_http_requests_total{role="kubermatic-api",code=~"5.."}[5m])) >
@mrIncompetent are you okay with reverting this?

2019-03-21 10:50 UTC, mrIncompetent commented on config/monitoring/prometheus/rules/kubermatic-master-kubermatic.yaml
> +    expr: sum(rate(kubermatic_api_http_requests_total{role="kubermatic-api",code=~"5.."}[5m])) >
I'm basically just following https://prometheus.io/docs/practices/naming/#metric-names

> A metric name should have a (single-word) application prefix relevant to the domain the metric belongs to. The prefix is sometimes referred to as namespace by client libraries. For metrics specific to an application, the prefix is usually the application name itself. Sometimes, however, metrics are more generic, like standardized metrics exported by client libraries

2019-03-21 10:57 UTC, mrIncompetent commented on config/monitoring/prometheus/rules/kubermatic-master-kubermatic.yaml
> +    expr: sum(rate(kubermatic_api_http_requests_total{role="kubermatic-api",code=~"5.."}[5m])) >
But apparently i misinterpreted this one: https://groups.google.com/forum/#!topic/prometheus-developers/XjlOnDCK9qc

2019-03-21 11:35 UTC, kron4eg commented on config/monitoring/prometheus/rules/kubermatic-master-kubermatic.yaml
> +    expr: sum(rate(kubermatic_api_http_requests_total{role="kubermatic-api",code=~"5.."}[5m])) >
yeah,
>Sometimes, however, metrics are more generic, like standardized metrics exported by client libraries

`http_requests_total` is one of those standard metrics that a useful when unified across different services.

2019-03-21 15:26 UTC, maciaszczykm commented
Removed the prefix from the metrics names. @kron4eg PTAL.

2019-03-21 15:49 UTC, kron4eg commented on api/cmd/kubermatic-api/metrics.go
> +			Name: "init_node_deployment_failures",
This metric is custom, and probably should get new prefixed name per @mrIncompetent comment.

2019-03-22 08:26 UTC, maciaszczykm commented
@kron4eg PTAL

2019-03-22 08:27 UTC, kron4eg approved these changes
/lgtm

2019-03-22 08:50 UTC, merged