add service account binding controller
kubermatic/kubermatic pull request #2998
Opened 2019-03-13 13:57 UTC by zreigz

**What this PR does / why we need it**: new controller watches SA objects and creates binding to the project.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2932

```release-note
add service account binding controller
```

2019-03-13 15:54 UTC, zreigz commented
/retest

2019-03-14 07:02 UTC, zreigz commented
/retest

2019-03-14 08:50 UTC, zreigz commented
/retest

2019-03-14 10:05 UTC, p0lyn0mial requested changes

2019-03-14 10:05 UTC, p0lyn0mial commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +	glog.V(4).Infof("Reconciling SA binding for %s", saName)
this is redundant and to verbose, we could remove it, wdyt ?

2019-03-14 10:05 UTC, p0lyn0mial commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +			return nil
why don't simply return an error from `Get` ?

2019-03-14 10:05 UTC, p0lyn0mial commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +			Name:   genBindingName(project.Name, user.Spec.ID),
name should be random.

2019-03-14 10:05 UTC, p0lyn0mial commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +	if err := r.Get(r.ctx, client.ObjectKey{Namespace: metav1.NamespaceAll, Name: bindingName}, binding); err != nil {
list all bindings for the given `sa` and `project` from the cache instead.

2019-03-14 10:05 UTC, p0lyn0mial commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +func (r *reconcileServiceAccountProjectBinding) createBinding(user *kubermaticv1.User, project *kubermaticv1.Project) error {
nit: change `user` to `sa`

2019-03-14 10:05 UTC, p0lyn0mial commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +
remove `user.Labels[labelGroup]` if exist

2019-03-14 10:05 UTC, p0lyn0mial commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +	if err := r.Get(r.ctx, client.ObjectKey{Namespace: metav1.NamespaceAll, Name: projectName}, project); err != nil {
why do we have to retrieve the project ? can we simply use `projectName` ?

2019-03-14 10:05 UTC, p0lyn0mial commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +		return fmt.Errorf("label %s not found", labelGroup)
please add the name of the sa to the log msg.

2019-03-14 10:05 UTC, p0lyn0mial commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +			Labels: map[string]string{kubermaticv1.ProjectIDLabelKey: project.Name},
why do we need the label ?

2019-03-14 10:05 UTC, p0lyn0mial commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +	if err := r.Create(r.ctx, binding); err != nil {
change to `return r.Create(r.ctx, binding)`

2019-03-14 10:05 UTC, p0lyn0mial commented on api/pkg/handler/test/helper.go
> +	return &kubermaticapiv1.User{
use `GenUser` method and pass `id, name and email` then add the `group` label

2019-03-14 10:05 UTC, p0lyn0mial commented on api/pkg/controller/rbac/service-account/service_account_binding_test.go
> +				ObjectMeta: metav1.ObjectMeta{
please use `GenBinding` for example https://github.com/kubermatic/kubermatic/blob/master/api/pkg/handler/v1/user/user_test.go#L59

2019-03-14 10:05 UTC, p0lyn0mial commented on api/pkg/controller/rbac/sync_project_binding_controller.go
> +	if err := r.Get(r.ctx, client.ObjectKey{Namespace: metav1.NamespaceAll, Name: projectBinding.Spec.ProjectID}, projectFromCache); err != nil {
nice :)

2019-03-14 11:50 UTC, zreigz commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +	glog.V(4).Infof("Reconciling SA binding for %s", saName)
removed

2019-03-14 11:53 UTC, zreigz commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +			return nil
when SA is deleted then we return nil, otherwise, it will call the Reconcile method again and again

2019-03-14 11:53 UTC, zreigz commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +			Name:   genBindingName(project.Name, user.Spec.ID),
done

2019-03-14 11:53 UTC, zreigz commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +	if err := r.Get(r.ctx, client.ObjectKey{Namespace: metav1.NamespaceAll, Name: bindingName}, binding); err != nil {
done

2019-03-14 11:53 UTC, zreigz commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +func (r *reconcileServiceAccountProjectBinding) createBinding(user *kubermaticv1.User, project *kubermaticv1.Project) error {
done

2019-03-14 11:53 UTC, zreigz commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +
done

2019-03-14 11:55 UTC, zreigz commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +			Labels: map[string]string{kubermaticv1.ProjectIDLabelKey: project.Name},
this code https://github.com/kubermatic/kubermatic/blob/master/api/pkg/controller/rbac/sync_resource.go#L29 expects Project type, we use User for OwnerRef

2019-03-14 11:55 UTC, zreigz commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +	if err := r.Create(r.ctx, binding); err != nil {
done

2019-03-14 11:55 UTC, zreigz commented
@p0lyn0mial PTAL

2019-03-18 09:06 UTC, p0lyn0mial requested changes

2019-03-18 09:06 UTC, p0lyn0mial commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +	delete(sa.Labels, labelGroup)
we need to remove labels after creating a binding otherwise this is not reliable, you can move it to `ensureServiceAccountProjectBinding` function

2019-03-18 10:18 UTC, zreigz commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +	delete(sa.Labels, labelGroup)
done

2019-03-18 10:19 UTC, zreigz commented
@p0lyn0mial PTAL

2019-03-18 10:39 UTC, zreigz commented
/retest

2019-03-18 11:15 UTC, p0lyn0mial commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +		if err := r.Update(r.ctx, sa); err != nil {
what if a binding was created but this call failed for some reason ? In that case we never remove the label. Please move it to line `113`.

2019-03-18 12:35 UTC, zreigz commented on api/pkg/controller/rbac/service-account/service_account_binding_controller.go
> +		if err := r.Update(r.ctx, sa); err != nil {
done

2019-03-18 12:37 UTC, zreigz commented
/retest

2019-03-18 15:17 UTC, p0lyn0mial commented
/lgtm
/approve

2019-03-18 16:33 UTC, merged