add support for SA creation
kubermatic/kubermatic pull request #3037
Opened 2019-03-19 11:55 UTC by zreigz

**What this PR does / why we need it**: new endpoint added for service accounts. It creates a new SA resource.
Fixes: #3034

```release-note
a new endpoint for service account creation: `POST /api/v1/projects/{project_id}/serviceaccounts`
[Action required] user need to set a new parameter `--domain` for a domain name on which the server is deployed
```

2019-03-19 13:08 UTC, p0lyn0mial requested changes

2019-03-19 13:08 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa.go
> +	user.Spec.Email = fmt.Sprintf("%s@kubermatic.io", uniqueName)
the email is going to end up in the tokens, it would be nice to have a subdomain encoded as well, for example,`@dev.kubermatic.io` or `@cloud.kubermatic.io`. The tokens are not encrypted so if a user doesn't remember where it came from looking at the subdomain could be helpful.

2019-03-19 13:08 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa.go
> +	user.Labels = map[string]string{"group": group}
now I have realised that `initialGroup` would be a better name for the label :(, do we want to change that ?

2019-03-19 13:08 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa_test.go
> +			expectedSA: func() *kubermaticv1.User {
could you add a function that generates `SA` ? Similar to `createProject` - although it could have more arguments.

2019-03-19 13:08 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa_test.go
> +			name:     "scenario 1, create service account `test` for owners group",
this test should fail, `sa` cannot belong to the `owners` group. Since the validation is done in the handler we cold change the group name.

2019-03-19 13:08 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa_test.go
> +			if !equality.Semantic.DeepEqual(sa.OwnerReferences, tc.expectedSA.OwnerReferences) {
wouldn't be better to compare everything except a name which is autogenerated ?

2019-03-19 13:08 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/sa.go
> +		sa, err := serviceAccountProvider.CreateServiceAccount(userInfo, project, saFromRequest.Name, saFromRequest.Group)
before creating a `SA` we should check if the name (`saFromRequest`) was not taken.

2019-03-19 13:08 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/sa.go
> +			return nil, err
change to `return nil, common.KubernetesErrorToHTTPError(err)`

2019-03-19 13:08 UTC, p0lyn0mial commented on api/pkg/controller/rbac/mapper.go
> +var ServiceAccountGroupsPrefixes = []string{
please move `ServiceAccountGroupsPrefixes` where it's used - API :)

2019-03-19 13:08 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa_test.go
> +			saGroup:  "owners",
no `owners` group

2019-03-19 13:08 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/sa_test.go
> +	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
grouping :)

2019-03-19 13:08 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/sa.go
> +		sa, err := serviceAccountProvider.CreateServiceAccount(userInfo, project, saFromRequest.Name, saFromRequest.Group)
group name is wrong, should be `owners-projectID`, use `rbac.GenerateActualGroupNameFor(Name, GroupPrefix)`

2019-03-19 15:33 UTC, zreigz commented
/retest

2019-03-20 17:12 UTC, zreigz commented
@p0lyn0mial PTAL

2019-03-22 07:20 UTC, zreigz commented on api/pkg/provider/kubernetes/sa.go
> +	user.Spec.Email = fmt.Sprintf("%s@kubermatic.io", uniqueName)
done

2019-03-25 09:05 UTC, p0lyn0mial requested changes

2019-03-25 09:05 UTC, p0lyn0mial commented on api/pkg/provider/types.go
> +	CreateServiceAccount(userInfo *UserInfo, project *kubermaticv1.Project, name, group string) (*kubermaticv1.User, error)
change to `Create`

2019-03-25 09:05 UTC, p0lyn0mial commented on api/pkg/provider/types.go
> +	GetServiceAccountByNameForProject(userInfo *UserInfo, serviceAccountName, projectName string) (*kubermaticv1.User, error)
change to `List` make it generic and add an additional parameter for filtering, for example https://github.com/kubermatic/kubermatic/blob/master/api/pkg/provider/types.go#L75

we also need to add a guard to validate if only the owners of a project can `List` `SA`s, for example
https://github.com/kubermatic/kubermatic/blob/master/api/pkg/provider/kubernetes/member.go#L92

2019-03-25 09:05 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/sa.go
> +			isRequestedGroupPrefixValid = true
nit: you don't need `isRequestedGroupPrefixValid` variable, you could return `nil` as soon as the code enters here.

```
if existingGroupPrefix == r.Body.Group {
  return nil
}

...
return fmt.Errorf("invalid group name %s", r.Body.Group)
}

2019-03-25 09:05 UTC, p0lyn0mial commented on api/pkg/controller/service-account/service_account_binding_controller.go
> +	label "github.com/kubermatic/kubermatic/api/pkg/provider/kubernetes"
could you change the alias, it reads badly `label.ServiceAccountLabelGroup`

2019-03-25 09:05 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa_test.go
> +			name:        "scenario 2, get existing service account",
nit: update the name to `scenario 1`

2019-03-25 09:05 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa_test.go
> +	sa := &kubermaticv1.User{}
we could use `GenUser(...)` function to emphasise that a `SA` is not really different from a `User`

2019-03-25 09:05 UTC, p0lyn0mial commented on config/kubermatic/templates/kubermatic-api-dep.yaml
> +          - -domain={{ .Values.kubermatic.domain }}
should we announce it in the release note ? So that customers know they have to pass an additional param.

2019-03-25 09:05 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/sa.go
> +			return nil, err
make sure we return a `BadRequest` error.

2019-03-25 09:05 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/sa.go
> +		return k8cerrors.NewBadRequest("invalid group name %s", r.Body.Group)
if the validation is done in the decoding function then the users gets `BadRequest` since this function will not be run there could you return a normal error (`fmt.Errorf`) and wrap it in the endpoint ? This improves readability

2019-03-25 09:05 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/sa.go
> +			return nil, common.KubernetesErrorToHTTPError(fmt.Errorf("the given name: '%s' for service account already exists", saFromRequest.Name))
please return `errors.NewAlreadyExists` instead.

2019-03-25 12:59 UTC, zreigz commented on api/pkg/provider/kubernetes/sa.go
> +	user.Labels = map[string]string{"group": group}
done

2019-03-25 13:00 UTC, zreigz commented on api/pkg/provider/types.go
> +	CreateServiceAccount(userInfo *UserInfo, project *kubermaticv1.Project, name, group string) (*kubermaticv1.User, error)
done

2019-03-25 13:00 UTC, zreigz commented on api/pkg/provider/types.go
> +	GetServiceAccountByNameForProject(userInfo *UserInfo, serviceAccountName, projectName string) (*kubermaticv1.User, error)
done

2019-03-25 13:00 UTC, zreigz commented on api/pkg/handler/v1/serviceaccount/sa.go
> +			isRequestedGroupPrefixValid = true
done

2019-03-25 13:00 UTC, zreigz commented on api/pkg/controller/service-account/service_account_binding_controller.go
> +	label "github.com/kubermatic/kubermatic/api/pkg/provider/kubernetes"
done

2019-03-25 13:00 UTC, zreigz commented on api/pkg/provider/kubernetes/sa_test.go
> +			name:        "scenario 2, get existing service account",
done

2019-03-25 13:00 UTC, zreigz commented on api/pkg/provider/kubernetes/sa_test.go
> +	sa := &kubermaticv1.User{}
done

2019-03-25 13:01 UTC, zreigz commented on config/kubermatic/templates/kubermatic-api-dep.yaml
> +          - -domain={{ .Values.kubermatic.domain }}
I've updated `release notes`

2019-03-25 13:01 UTC, zreigz commented on api/pkg/handler/v1/serviceaccount/sa.go
> +			return nil, err
done

2019-03-25 13:01 UTC, zreigz commented on api/pkg/handler/v1/serviceaccount/sa.go
> +		return k8cerrors.NewBadRequest("invalid group name %s", r.Body.Group)
done

2019-03-25 13:01 UTC, zreigz commented on api/pkg/handler/v1/serviceaccount/sa.go
> +			return nil, common.KubernetesErrorToHTTPError(fmt.Errorf("the given name: '%s' for service account already exists", saFromRequest.Name))
done

2019-03-25 13:02 UTC, zreigz commented
@p0lyn0mial PTAL

2019-03-25 13:09 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/sa.go
> +			return nil, common.KubernetesErrorToHTTPError(err)
this is `errors.BadRequest`, otherwise we will return `500`

2019-03-25 13:13 UTC, zreigz commented on api/pkg/handler/v1/serviceaccount/sa.go
> +			return nil, common.KubernetesErrorToHTTPError(err)
done

2019-03-25 14:04 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa.go
> +			filteredList = append(filteredList, sa)
could we  `break` as soon as we found `sa` :) ?
```
if sa.Spec.Name == options.ServiceAccountName {
			filteredList = append(filteredList, sa)
                         break
}
```

2019-03-25 14:07 UTC, zreigz commented on api/pkg/provider/kubernetes/sa.go
> +			filteredList = append(filteredList, sa)
done

2019-03-25 14:18 UTC, p0lyn0mial commented
/lgtm

2019-03-25 14:19 UTC, p0lyn0mial commented
/approve

2019-03-25 14:21 UTC, p0lyn0mial commented
@zreigz we need an `OWNER` file for `service-account` controller.

2019-03-25 14:43 UTC, p0lyn0mial commented
/lgtm
/approve

2019-03-25 14:48 UTC, zreigz commented
/assign @mrIncompetent

2019-03-25 14:58 UTC, mrIncompetent commented on config/kubermatic/templates/kubermatic-api-dep.yaml
> +          - -domain={{ .Values.kubermatic.domain }}
Please update the docs: https://github.com/kubermatic/docs/tree/master/content/upgrading/2.9_to_2.10

2019-03-25 15:07 UTC, mrIncompetent commented on api/pkg/provider/kubernetes/sa.go
> +			filteredList = append(filteredList, sa)
2 Things:
You're iterating over `[]*kubermaticv1.User` but your variable is called `sa` -> this seems a bit confusing

If you are returning `filteredList` in this func, but `break` as soon as you added the first item - why do you return a slice instead of a pointer?

2019-03-25 15:17 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa.go
> +			filteredList = append(filteredList, sa)
> You're iterating over []*kubermaticv1.User but your variable is called sa -> this seems a bit confusing

ServiceAccounts are a special type of users, they have an email address, belong to a project and a group within that project. They are used to access our API just like regular users.

> If you are returning filteredList in this func, but break as soon as you added the first item - why do you return a slice instead of a pointer?

This is a generic `List` method with options for filtering, it's a common patter for all providers, see: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/provider/types.go#L85

2019-03-25 15:18 UTC, mrIncompetent commented on api/pkg/provider/kubernetes/sa.go
> +		if strings.HasPrefix(sa.Name, "serviceaccount") {
can we use something more expressive like `kubermatic-api-serviceaccount` as prefix?

2019-03-25 15:19 UTC, mrIncompetent commented on api/pkg/provider/kubernetes/sa.go
> +					resultList = append(resultList, sa)
This might be simpler & faster if you use a custom indexer:
Example(UID): https://github.com/kube-node/nodeset/blob/master/pkg/controller/nodeset/node/controller.go#L139

2019-03-25 15:20 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa.go
> +		if strings.HasPrefix(sa.Name, "serviceaccount") {
the name of a service account is `serviceaccount-ID@dev.kubermatic.io` isn't that enough ? Will we have a different type of `SA` in the future ?

2019-03-25 15:27 UTC, mrIncompetent commented on api/pkg/provider/kubernetes/sa.go
> +		if strings.HasPrefix(sa.Name, "serviceaccount") {
Oh wasn't aware, thanks for clarification!

2019-03-25 15:27 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa.go
> +					resultList = append(resultList, sa)
we need to create an indexer first :) Iterating over a list in memory is quite fast - practical for billions of elements :)

2019-03-25 15:28 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa.go
> +					resultList = append(resultList, sa)
but I agree it looks better :)

2019-03-25 15:31 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa.go
> +			filteredList = append(filteredList, sa)
> You're iterating over []*kubermaticv1.User but your variable is called sa -> this seems a bit confusing

Also we didn't want to create a new type and generate code for it, plus we could reuse already existing code for example for mapping a service account to a group.

2019-03-25 15:47 UTC, mrIncompetent commented on api/pkg/provider/kubernetes/sa.go
> +			filteredList = append(filteredList, sa)
> ServiceAccounts are a special type of users, they have an email address, belong to a project and a group within that project. They are used to access our API just like regular users.

:+1: 

> This is a generic List method with options for filtering, it's a common patter for all providers, see: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/provider/types.go#L85

Having a list function which accepts options for filtering :+1: 
Considering the exact `name` as filter during a List operating is a questionable design decision.

2019-03-25 15:49 UTC, mrIncompetent commented
Waiting for the docs approval before approving

2019-03-25 15:52 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa.go
> +			filteredList = append(filteredList, sa)
> Considering the exact name as filter during a List operating is a questionable design decision.

We need to list all resources to check if the name was not taken, we could extend the interface by adding more methods like `GetServiceAccountByName`/`ListServiceAccountByName` or use a single `List` method with options.

2019-03-25 17:38 UTC, zreigz commented
Documentation is ready https://github.com/kubermatic/docs/pull/112
@mrIncompetent PTAL

2019-03-26 08:21 UTC, mrIncompetent commented
/approve

2019-03-26 08:56 UTC, zreigz commented
/retest

2019-03-26 09:26 UTC, merged