new endpoint for editing service account
kubermatic/kubermatic pull request #3080
Opened 2019-03-29 10:25 UTC by zreigz

**What this PR does / why we need it**: new endpoint for editing service account

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3079

```release-note
new endpoint for editing service account for the project: PUT /api/v1/projects/{project_id}/serviceaccounts/{serviceaccount_id}
```

2019-03-29 11:23 UTC, zreigz commented
/retest

2019-04-01 10:20 UTC, zreigz commented
/retest

2019-04-01 10:31 UTC, p0lyn0mial requested changes

2019-04-01 10:31 UTC, p0lyn0mial commented on api/pkg/handler/routes_v1.go
> +		Handler(r.editServiceAccount())
please change the name to `updateServiceAccount`

2019-04-01 10:31 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/sa.go
> +func EditEndpoint(projectProvider provider.ProjectProvider, serviceAccountProvider provider.ServiceAccountProvider) endpoint.Endpoint {
Please change the name to `UpdateEndpoint`, for example https://github.com/kubermatic/kubermatic/blob/master/api/pkg/handler/v1/project/project.go#L130

2019-04-01 10:31 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/sa.go
> +	addReq
should we also change "Update a project" EP to accept `apiv1.Project` in the body ?
https://github.com/kubermatic/kubermatic/blob/master/api/pkg/handler/v1/project/project.go#L230

2019-04-01 10:31 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa.go
> +	serviceAccount, err := p.serviceAccountLister.Get(name)
don't get the resource from the lister, use masterImpersonatedClient instead.

2019-04-01 10:31 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/sa.go
> +		bindings, err := memberMapper.MappingsFor(sa.Spec.Email)
use `MapUserToGroup` instead.

2019-04-01 10:31 UTC, p0lyn0mial commented on api/pkg/handler/routes_v1.go
> +//     Changes membership of the given service account for the given project
please change the description, this EP updates the resource not only changes the membership.

2019-04-01 10:31 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/sa.go
> +func EditEndpoint(projectProvider provider.ProjectProvider, serviceAccountProvider provider.ServiceAccountProvider, memberMapper provider.ProjectMemberMapper) endpoint.Endpoint {
please change to `UpdateEndpoint`, for example https://github.com/kubermatic/kubermatic/blob/master/api/pkg/handler/v1/project/project.go#L130

2019-04-01 11:08 UTC, zreigz commented on api/pkg/handler/routes_v1.go
> +		Handler(r.editServiceAccount())
done

2019-04-01 11:08 UTC, zreigz commented on api/pkg/handler/v1/serviceaccount/sa.go
> +func EditEndpoint(projectProvider provider.ProjectProvider, serviceAccountProvider provider.ServiceAccountProvider) endpoint.Endpoint {
done

2019-04-01 11:08 UTC, zreigz commented on api/pkg/handler/v1/serviceaccount/sa.go
> +	addReq
yes, I've created the issue for it: #3087

2019-04-01 11:08 UTC, zreigz commented on api/pkg/provider/kubernetes/sa.go
> +	serviceAccount, err := p.serviceAccountLister.Get(name)
done

2019-04-01 11:09 UTC, zreigz commented on api/pkg/handler/v1/serviceaccount/sa.go
> +		bindings, err := memberMapper.MappingsFor(sa.Spec.Email)
done

2019-04-01 11:09 UTC, zreigz commented on api/pkg/handler/routes_v1.go
> +//     Changes membership of the given service account for the given project
done

2019-04-01 11:09 UTC, zreigz commented on api/pkg/handler/v1/serviceaccount/sa.go
> +func EditEndpoint(projectProvider provider.ProjectProvider, serviceAccountProvider provider.ServiceAccountProvider, memberMapper provider.ProjectMemberMapper) endpoint.Endpoint {
done

2019-04-01 11:09 UTC, zreigz commented
@p0lyn0mial PTAL

2019-04-01 11:20 UTC, p0lyn0mial commented
/lgtm
/approve

2019-04-01 11:38 UTC, merged