add new edpoint to delete service account
kubermatic/kubermatic pull request #3093
Opened 2019-04-01 14:29 UTC by zreigz

**What this PR does / why we need it**: new endpoint to delete service account

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3092

```release-note
 new endpoint to delete service account: DELETE /api/v1/projects/{project_id}/serviceaccounts/{serviceaccount_id}
```

2019-04-01 14:53 UTC, p0lyn0mial requested changes

2019-04-01 14:53 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/sa.go
> +	Body apiv1.ServiceAccount
to delete a `SA` we only need the `ID`.

2019-04-01 14:53 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/sa.go
> +
check if the project associated with `SA` exist.

2019-04-02 07:13 UTC, zreigz commented on api/pkg/handler/v1/serviceaccount/sa.go
> +	Body apiv1.ServiceAccount
done

2019-04-02 07:13 UTC, zreigz commented on api/pkg/handler/v1/serviceaccount/sa.go
> +
additionally I check if `SA` belongs to the project

2019-04-02 07:44 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/sa.go
> +		project, err := projectProvider.Get(userInfo, req.ProjectID, &provider.ProjectGetOptions{})
shouldn't we check if the project exist before checking/getting the `SA` (line 184) ?

2019-04-02 07:44 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/sa.go
> +		existingSAList, err := serviceAccountProvider.List(userInfo, project, &provider.ServiceAccountListOptions{ServiceAccountName: existingSA.Spec.Name})
we usually don't check if a resource belongs to a project like that. RBAC rules imply that a resource is part of a project.

For example, if a user can retrieve a project then a user belongs to the project. If a user can retrieve a SA then the SA must belong to the project.

However, if you really want to have a check then we could move it to the provider and examine `OwnerRef` / `labels` ?

2019-04-02 08:01 UTC, zreigz commented on api/pkg/handler/v1/serviceaccount/sa.go
> +		project, err := projectProvider.Get(userInfo, req.ProjectID, &provider.ProjectGetOptions{})
yes, done

2019-04-02 08:01 UTC, zreigz commented on api/pkg/handler/v1/serviceaccount/sa.go
> +		existingSAList, err := serviceAccountProvider.List(userInfo, project, &provider.ServiceAccountListOptions{ServiceAccountName: existingSA.Spec.Name})
it's fine, I won't check

2019-04-02 08:26 UTC, zreigz commented
@p0lyn0mial PTAL

2019-04-03 10:16 UTC, p0lyn0mial commented
/lgtm
/approve

2019-04-03 11:50 UTC, zreigz commented
/retest

2019-04-03 12:32 UTC, merged