Set oidc flag in hack script
kubermatic/kubermatic pull request #3109
Opened 2019-04-04 08:03 UTC by mrIncompetent

**What this PR does / why we need it**:
This PR updates our codebase to do certain templating based on the existence of the actual feature flag (`-features=OIDC=true`) and not on the existence of a feature based flag (`-oidc-issuer-url`).
Also this PR updates the hack scripts to contain the OIDC flags.

Fixes #3108

**Release note**:
```release-note
NONE
```

2019-04-04 08:03 UTC, mrIncompetent commented
/assign @alvaroaleman

2019-04-04 08:24 UTC, alvaroaleman commented on api/cmd/kubermatic-api/options.go
> +	// As long as OpenShift support has not reached the testing stage, we only validate those flags when the OIDC feature flag was set
This comment is really confusing and requires to know that:

* OIDC is not optional for Openshift
* We re-use the same feature gate for both Kubernetes and Openshift

2019-04-04 08:24 UTC, alvaroaleman commented on api/cmd/kubermatic-controller-manager/options.go
> -	} else {
Why is this removed? I like it if the thing crashes if a config parameter for a feature that is disabled is passed

2019-04-04 08:24 UTC, alvaroaleman commented on api/hack/run-api.sh
> +  -oidc-issuer-url="$(vault kv get -field=oidc-issuer-url dev/seed-clusters/dev.kubermatic.io)" \
Shouldn't the featuregate be enabled as well or am I missing it?

2019-04-04 08:24 UTC, alvaroaleman commented on api/pkg/controller/cluster/cluster_controller.go
> +	features Features
What "featureGates" map is the comment talking about and is that still a TODO after this pull?

2019-04-04 15:23 UTC, mrIncompetent commented on api/cmd/kubermatic-api/options.go
> +	// As long as OpenShift support has not reached the testing stage, we only validate those flags when the OIDC feature flag was set
The feature flag only targets Kubernetes.

For OpenShift we always use those flags to configure the OpenShift internal OAuth server.
That is the reason why we're not validating them for OpenShift yet.
Otherwise administrators would need to set those flags with v2.10 even they don't use the feature

2019-04-04 15:23 UTC, mrIncompetent commented on api/cmd/kubermatic-controller-manager/options.go
> -	} else {
See https://github.com/kubermatic/kubermatic/pull/3109#discussion_r272234536

2019-04-04 15:23 UTC, mrIncompetent commented on api/hack/run-api.sh
> +  -oidc-issuer-url="$(vault kv get -field=oidc-issuer-url dev/seed-clusters/dev.kubermatic.io)" \
See https://github.com/kubermatic/kubermatic/pull/3109#discussion_r272234536

2019-04-04 15:25 UTC, mrIncompetent commented on api/cmd/kubermatic-api/options.go
> +	// As long as OpenShift support has not reached the testing stage, we only validate those flags when the OIDC feature flag was set
I'll update the comment

2019-04-04 15:29 UTC, mrIncompetent commented on api/cmd/kubermatic-api/options.go
> +	// As long as OpenShift support has not reached the testing stage, we only validate those flags when the OIDC feature flag was set
Done with https://github.com/kubermatic/kubermatic/pull/3109/commits/147e85a270587e40874d4ef524c7d2b1b115c1c3

2019-04-04 15:35 UTC, alvaroaleman commented
/lgtm
/approve

2019-04-04 16:20 UTC, mrIncompetent commented
/retest

2019-04-05 08:19 UTC, zreigz requested changes

2019-04-05 08:19 UTC, zreigz commented on api/hack/run-api.sh
> +  -oidc-issuer-url="$(vault kv get -field=oidc-issuer-url dev/seed-clusters/dev.kubermatic.io)" \
there is no `oidc-issuer-url` in API options. Use 'oidc-url' instead

2019-04-05 08:21 UTC, zreigz commented on api/hack/run-api.sh
> +  -oidc-issuer-url="$(vault kv get -field=oidc-issuer-url dev/seed-clusters/dev.kubermatic.io)" \
generally, this line can be skipped

2019-04-05 12:26 UTC, mrIncompetent commented on api/hack/run-api.sh
> +  -oidc-issuer-url="$(vault kv get -field=oidc-issuer-url dev/seed-clusters/dev.kubermatic.io)" \
Removed with https://github.com/kubermatic/kubermatic/pull/3109/commits/79b3b49568f3326b469715ba8dc5e28cfb1c0963

2019-04-05 12:26 UTC, mrIncompetent commented
@zreigz PTAL

2019-04-05 12:26 UTC, zreigz commented
/lgtm

2019-04-05 12:26 UTC, zreigz commented
/approve

2019-04-05 13:03 UTC, merged