add endpoint for service account token
kubermatic/kubermatic pull request #3111
Opened 2019-04-04 08:27 UTC by zreigz

**What this PR does / why we need it**: add a new endpoint to be able to create a token for the service account

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3107
Depends on: https://github.com/kubermatic/secrets/pull/250

```release-note
[Action required] the users must set `service-account-signing-key` flag when running the kubermatic-api.
It must be a key with 32 bytes or longer. A user can generate this key using command: "openssl rand -hex 32"
[Action required] The value for the `service-account-signing-key flag must be stored in `auth` section for `kubermtic` in values.yaml, for example:

kubermatic:
  auth:
    serviceAccountKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
```

2019-04-04 08:44 UTC, zreigz commented
don't merge before: https://github.com/kubermatic/secrets/pull/250

2019-04-08 10:08 UTC, zreigz commented
/retest

2019-04-08 12:15 UTC, p0lyn0mial requested changes

2019-04-08 12:15 UTC, p0lyn0mial commented on api/cmd/kubermatic-api/main.go
> +	"github.com/kubermatic/kubermatic/api/pkg/serviceaccount"
imports :)

2019-04-08 12:15 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa_token_test.go
> +			expectedOwnerRefs: []metav1.OwnerReference{
wouldn't be better to compare the whole object (`Secret`) ?

2019-04-08 12:15 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa_token_test.go
> +			tokenGenerator, err := serviceaccount.JWTTokenGenerator([]byte(test.TestServiceAccountHashKey))
we could inject a fake token generator and we could easily compare expected and actual objects. 

In this test we would like to know if the provider generates a valid object. We could inspect: namespace, OwnerRef, Name and the token (but we could treat the token as an opaque value)

2019-04-08 12:15 UTC, p0lyn0mial commented on api/pkg/api/v1/types.go
> +	Token string `json:"token"`
this value can be optional, for example it will not be filled on `GET` and `LIST` requests.

2019-04-08 12:15 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa_token.go
> +		return nil, err
I think we need to wrap the err into a kubernetes error so that:
 - we stay consistent - all providers return kubernetes errors
 - we can translate kubernetes error into kubermatic api errror (common.KubernetesErrorToHTTPError(err))

2019-04-08 12:15 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa_token.go
> +	secret.Name = fmt.Sprintf("sa-token-%s", rand.String(10))
so, the users cannot specify a name for tokens ? wouldn't be better to let them specify human readable names ? for example `kubermatic_ci_token`, `ci_e2e_tests`

2019-04-08 12:15 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/token_test.go
> +			if tc.httpStatus == http.StatusCreated {
it always needs to return `StatusCreated`

2019-04-08 12:15 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/token_test.go
> +				tokenAuthenticator := serviceaccount.JWTTokenAuthenticator([]byte(test.TestServiceAccountHashKey))
I'd prefer if we could change `CreateTestEndpointAndGetClients` method to return `tokenAuthenticator` instead. WDYT ?

2019-04-08 12:15 UTC, p0lyn0mial commented on api/pkg/serviceaccount/jwt.go
> +	GenerateToken(claims *jwt.Claims, privateClaims *TokenClaim) (string, error)
since the interface is `TokenGenerator` we could change the method to `Generate`, wdyt ?

2019-04-08 12:15 UTC, p0lyn0mial commented on api/pkg/serviceaccount/jwt.go
> +type TokenAuthenicator interface {
typo in `Authenicator`, should be `Authenticator`

2019-04-08 12:15 UTC, p0lyn0mial commented on api/pkg/serviceaccount/jwt.go
> +	AuthenticateToken(tokenData string) (*TokenClaim, error)
since the interface is `TokenAuthenticator` we could change the method to `Authenticate`, wdyt ?

2019-04-08 12:15 UTC, p0lyn0mial commented on api/pkg/serviceaccount/jwt.go
> +	private := &TokenClaim{}
why do you call it `private` ? `TokenClaim` is not encrypted.
could we call them `customClaims`?

2019-04-08 12:15 UTC, p0lyn0mial commented on api/pkg/api/v1/types.go
> +type ServiceAccountToken struct {
Should we add an `Expiry` field ?

2019-04-08 12:15 UTC, p0lyn0mial commented on api/pkg/serviceaccount/jwt.go
> +	err = public.Validate(jwt.Expected{
shouldn't we use `ValidateWithLeeway` function instead ? what's the difference ?

2019-04-08 12:15 UTC, p0lyn0mial commented on api/pkg/serviceaccount/jwt.go
> +	signer, err := jose.NewSigner(jose.SigningKey{Algorithm: jose.HS256, Key: privateKey}, &jose.SignerOptions{})
what are the requirements for the length of the key ? I think that for `HS256` the key must have `32` bytes in size.

See:
https://tools.ietf.org/html/rfc7518#section-3.2

2019-04-08 12:15 UTC, p0lyn0mial commented on api/cmd/kubermatic-api/options.go
> +	if len(o.serviceAccountHashKey) == 0 {
should we validate the size of they key ?

2019-04-08 12:15 UTC, p0lyn0mial commented on api/cmd/kubermatic-api/options.go
> +	flag.StringVar(&s.serviceAccountHashKey, "service-account-hash-key", "", "Hash key authenticates the service account's token value using HMAC. It is recommended to use a key with 32 or 64 bytes.")
please change the name to `service-account-signing-key`

2019-04-09 13:25 UTC, zreigz commented on api/pkg/serviceaccount/jwt.go
> +	err = public.Validate(jwt.Expected{
This call `ValidateWithLeeway` with default DefaultLeeway:
```
// DefaultLeeway defines the default leeway for matching NotBefore/Expiry claims.
DefaultLeeway = 1.0 * time.Minute

func (c Claims) Validate(e Expected) error {
	return c.ValidateWithLeeway(e, DefaultLeeway)
}
```

2019-04-09 13:26 UTC, zreigz commented on api/cmd/kubermatic-api/options.go
> +	flag.StringVar(&s.serviceAccountHashKey, "service-account-hash-key", "", "Hash key authenticates the service account's token value using HMAC. It is recommended to use a key with 32 or 64 bytes.")
done

2019-04-09 13:26 UTC, zreigz commented on api/pkg/serviceaccount/jwt.go
> +	signer, err := jose.NewSigner(jose.SigningKey{Algorithm: jose.HS256, Key: privateKey}, &jose.SignerOptions{})
it also works when size is different

2019-04-09 13:27 UTC, zreigz commented on api/cmd/kubermatic-api/options.go
> +	if len(o.serviceAccountHashKey) == 0 {
we don't validate other keys

2019-04-09 13:27 UTC, zreigz commented on api/pkg/api/v1/types.go
> +type ServiceAccountToken struct {
done

2019-04-09 13:27 UTC, zreigz commented on api/pkg/provider/kubernetes/sa_token.go
> +		return nil, err
doen

2019-04-09 13:27 UTC, zreigz commented on api/pkg/api/v1/types.go
> +	Token string `json:"token"`
done

2019-04-09 13:27 UTC, zreigz commented on api/pkg/provider/kubernetes/sa_token_test.go
> +			tokenGenerator, err := serviceaccount.JWTTokenGenerator([]byte(test.TestServiceAccountHashKey))
done

2019-04-09 13:53 UTC, zreigz commented
/retest

2019-04-09 14:22 UTC, zreigz commented
/retest

2019-04-09 15:18 UTC, zreigz commented
/retest

2019-04-10 06:02 UTC, zreigz commented
@p0lyn0mial PTAL

2019-04-11 10:18 UTC, p0lyn0mial requested changes

2019-04-11 10:18 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa_token.go
> +func (p *ServiceAccountTokenProvider) List(userInfo *provider.UserInfo, project *kubermaticv1.Project, sa *kubermaticv1.User, options *provider.ServiceAccountTokenListOptions) ([]*apiv1.PublicService
return `[]*v1.Secret` instead `[]*apiv1.PublicServiceAccountToken`

2019-04-11 10:18 UTC, p0lyn0mial commented on api/pkg/provider/kubernetes/sa_token.go
> +// List gets tokens for the project
please, update the comment - this method gets tokens for the given service account and project

2019-04-11 10:18 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/token.go
> +			return nil, errors.New(http.StatusInternalServerError, "can not encode expiration time")
please change the error msg `unable to create a token for %s due to %v", saName, err`

2019-04-11 10:18 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/token.go
> +	if len(r.Body.Name) == 0 || len(r.ProjectID) == 0 || len(r.ServiceAccountID) == 0 {
should we also check the max length of the name ?

2019-04-11 10:18 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/token.go
> +	externalToken.Name = internal.Labels["name"]
what if empty ?

2019-04-11 10:18 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/token.go
> +	externalToken.Token = string(internal.Data["token"])
what if empty ?

2019-04-11 10:18 UTC, p0lyn0mial commented on api/pkg/handler/routes_v1.go
> +//     Adds the given token to the given service account
the EP doesn't add, it generates a token.

2019-04-11 10:18 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/token.go
> +// CreateTokenEndpoint adds the given token to the service account
please update the comment, the EP creates a token for the given service account.

2019-04-11 10:18 UTC, p0lyn0mial commented on api/pkg/serviceaccount/jwt.go
> +type TokenGenerator interface {
should we update the name to `JWTTokenGenerator` ? Also please add a comment to the exported type.

2019-04-11 10:18 UTC, p0lyn0mial commented on api/pkg/serviceaccount/jwt.go
> +type TokenAuthenticator interface {
should we update the name to `JWTTokenAuthenticator` ? Also please add a comment to the exported type.

2019-04-11 10:18 UTC, p0lyn0mial commented on api/pkg/serviceaccount/jwt.go
> +type TokenClaim struct {
could we change the name to `CustomTokenClaim` ? Also please add a comment to the exported type.

2019-04-11 10:18 UTC, p0lyn0mial commented on api/pkg/serviceaccount/jwt.go
> +	Generate(claims *jwt.Claims, privateClaims *TokenClaim) (string, error)
change `privateClaims` to `customClaims` and check other places too.

2019-04-11 10:18 UTC, p0lyn0mial commented on api/pkg/serviceaccount/jwt.go
> +	signer, err := jose.NewSigner(jose.SigningKey{Algorithm: jose.HS256, Key: privateKey}, &jose.SignerOptions{})
Sure it works for different sizes but it doesn't mean it's secure. 

In our case the minimum size of the key is `32` bytes (see the spec) - we need to validate it.

the spec says:
```
 key of the same size as the hash output (for instance, 256 bits for
   "HS256") or larger MUST be used with this algorithm.  (This
   requirement is based on Section 5.3.4 (Security Effect of the HMAC
   Key)
```

2019-04-11 10:18 UTC, p0lyn0mial commented on api/cmd/kubermatic-api/options.go
> +	if len(o.serviceAccountSigningKey) == 0 {
> we don't validate other keys

maybe we should ?

In our case the minimum size of the key is 32 bytes (see the spec) - we need to validate it.

the spec says:

 key of the same size as the hash output (for instance, 256 bits for
   "HS256") or larger MUST be used with this algorithm.  (This
   requirement is based on Section 5.3.4 (Security Effect of the HMAC
   Key)

2019-04-11 10:18 UTC, p0lyn0mial commented on api/pkg/api/v1/types.go
> +	PublicServiceAccountToken
this is not how `PublicCloudSpec` is implemented, could you add a custom `MarshalJSON` method to `ServiceAccountToken`, just like https://github.com/kubermatic/kubermatic/blob/master/api/pkg/api/v1/types.go#L331

2019-04-11 10:18 UTC, p0lyn0mial commented on api/cmd/kubermatic-api/options.go
> +	flag.StringVar(&s.serviceAccountSigningKey, "service-account-signing-key", "", "Hash key authenticates the service account's token value using HMAC. It is recommended to use a key with 32 or 64 byte
please update the description - this is not a `Hash key`, it's a key used for HMAC.

Additionally recommended key size is:
```
key of the same size as the hash output (for instance, 256 bits for
"HS256") or larger MUST be used with this algorithm. (This
requirement is based on Section 5.3.4 (Security Effect of the HMAC
Key)
```

so in our case is `32` or larger.

2019-04-11 10:18 UTC, p0lyn0mial commented on api/hack/run-api.sh
> +  -service-account-signing-key="$(vault kv get -field=service-account-signing-key dev/seed-clusters/dev.kubermatic.io)" \
will you add a key to vault ?

2019-04-11 12:29 UTC, zreigz commented on api/pkg/provider/kubernetes/sa_token.go
> +func (p *ServiceAccountTokenProvider) List(userInfo *provider.UserInfo, project *kubermaticv1.Project, sa *kubermaticv1.User, options *provider.ServiceAccountTokenListOptions) ([]*apiv1.PublicService
done

2019-04-11 12:29 UTC, zreigz commented on api/pkg/provider/kubernetes/sa_token.go
> +// List gets tokens for the project
done

2019-04-11 12:29 UTC, zreigz commented on api/pkg/handler/v1/serviceaccount/token.go
> +			return nil, errors.New(http.StatusInternalServerError, "can not encode expiration time")
done

2019-04-11 12:29 UTC, zreigz commented on api/pkg/handler/v1/serviceaccount/token.go
> +	if len(r.Body.Name) == 0 || len(r.ProjectID) == 0 || len(r.ServiceAccountID) == 0 {
done

2019-04-11 12:29 UTC, zreigz commented on api/pkg/handler/v1/serviceaccount/token.go
> +	externalToken.Name = internal.Labels["name"]
done

2019-04-11 12:29 UTC, zreigz commented on api/pkg/handler/v1/serviceaccount/token.go
> +	externalToken.Token = string(internal.Data["token"])
done

2019-04-11 12:29 UTC, zreigz commented on api/pkg/handler/routes_v1.go
> +//     Adds the given token to the given service account
done

2019-04-11 12:29 UTC, zreigz commented on api/pkg/handler/v1/serviceaccount/token.go
> +// CreateTokenEndpoint adds the given token to the service account
done

2019-04-11 12:29 UTC, zreigz commented on api/pkg/serviceaccount/jwt.go
> +type TokenGenerator interface {
comment added I can't change the name because this name `JWTTokenGenerator` exists in the package for the function

2019-04-11 12:29 UTC, zreigz commented on api/pkg/serviceaccount/jwt.go
> +type TokenAuthenticator interface {
comment added I can't change the name because this name `JWTTokenAuthenticator` exists in the package

2019-04-11 12:30 UTC, zreigz commented on api/pkg/serviceaccount/jwt.go
> +type TokenClaim struct {
done

2019-04-11 12:30 UTC, zreigz commented on api/pkg/serviceaccount/jwt.go
> +	Generate(claims *jwt.Claims, privateClaims *TokenClaim) (string, error)
done

2019-04-11 12:30 UTC, zreigz commented on api/cmd/kubermatic-api/options.go
> +	if len(o.serviceAccountSigningKey) == 0 {
done

2019-04-11 12:30 UTC, zreigz commented on api/cmd/kubermatic-api/options.go
> +	flag.StringVar(&s.serviceAccountSigningKey, "service-account-signing-key", "", "Hash key authenticates the service account's token value using HMAC. It is recommended to use a key with 32 or 64 byte
done

2019-04-11 12:30 UTC, zreigz commented on api/hack/run-api.sh
> +  -service-account-signing-key="$(vault kv get -field=service-account-signing-key dev/seed-clusters/dev.kubermatic.io)" \
yes, waiting for review: https://github.com/kubermatic/secrets/pull/250

2019-04-11 12:35 UTC, zreigz commented
@p0lyn0mial PTAL

2019-04-12 07:06 UTC, p0lyn0mial commented on api/pkg/handler/v1/serviceaccount/token.go
> +	if len(r.Body.Name) > 50 {
the `len` function gives you the number of bytes not individual characters

2019-04-12 08:09 UTC, p0lyn0mial commented
/lgtm

2019-04-12 08:40 UTC, p0lyn0mial commented
/approve

2019-04-12 09:56 UTC, merged