Feature/set port range
kubermatic/kubermatic pull request #334
Opened 2017-04-25 08:14 UTC by lbb

Resolves #331

2017-04-26 10:01 UTC, mrIncompetent submitted a review, later dismissed

2017-04-26 13:21 UTC, scruplelesswizard requested changes

2017-04-26 13:21 UTC, scruplelesswizard commented on cmd/kubermatic-api/cmd/root.go
> +		return 1200, 14767, fmt.Errorf("can't parse %s, plsease enter it in the format of \"12000-14767\"", input)
typo

2017-04-26 13:21 UTC, scruplelesswizard commented on cmd/kubermatic-api/cmd/root.go
> +		return 1200, 14767, err
typo

2017-04-26 13:21 UTC, scruplelesswizard commented on cmd/kubermatic-api/cmd/root.go
> +		return 1200, 14767, err
typo

2017-04-26 13:21 UTC, scruplelesswizard commented on cmd/kubermatic-api/cmd/root.go
> +	RootCmd.PersistentFlags().StringVar(&nodeRange, "node-port-range", "12000-14767", "The range node port will be allocated in, provider in format: \"12000-14767\"")
Must explain what the port is used for. 
Also, this feature is not for a node port, this is the Client API server port. Please change the documentation and variable naming to reflect such

2017-04-26 13:21 UTC, scruplelesswizard commented on cmd/kubermatic-api/cmd/root.go
> +var cfgFile, kubeConfig, dcFile, secretsFile, jwtKey, address, masterKubeconfig, nodeRange string
The variable naming is incorrect. Firstly, this sets the API Server Port Range, and has nothing at all to do with a node. Also, it does not reflect that it references ports at all...

2017-04-27 11:48 UTC, scruplelesswizard requested changes

2017-04-27 11:48 UTC, scruplelesswizard commented on cmd/kubermatic-api/cmd/root.go
> +			log.Fatalf("Error reading node range: %v", err)
Node Range?

2017-04-27 12:36 UTC, scruplelesswizard approved these changes

2017-04-27 12:48 UTC, merged