WIP: Feature/unique dev label
kubermatic/kubermatic pull request #335
Opened 2017-04-25 13:26 UTC by lbb

Resolves #308

2017-04-25 13:47 UTC, scruplelesswizard approved these changes

2017-04-25 14:07 UTC, mrIncompetent requested changes

2017-04-25 14:07 UTC, mrIncompetent commented on controller/cluster/controller_test.go
> +	cc, err := NewController("", clientSet, tprClient, etcdClient, cps, versions, updates, "./../../master-resources/", "localhost", "true", "./../../addon-charts/")
Replace with a proper key

2017-04-25 14:07 UTC, mrIncompetent commented on handler/routing_test.go
> +	kps, err := kubernetes.Providers("./fixtures/kubecfg.yaml", dcs, cps, "./fixtures/secrets.yaml", "true")
Replace with a proper key

2017-04-28 07:43 UTC, mrIncompetent requested changes

2017-04-28 07:43 UTC, mrIncompetent commented on README.md
> +--dev="unique-label-abcdef123" \
Outdated

2017-04-28 07:43 UTC, mrIncompetent commented on README.md
> +--dev="unique-label-abcdef123" \
Outdated

2017-04-28 07:43 UTC, mrIncompetent commented on README.md
> +Valid dev label value must be 63 characters or less and must be empty or begin and end with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics betwe
Outdated

2017-04-28 07:43 UTC, mrIncompetent commented on provider/kubernetes/kubernetes.go
> +	dev string,
Outdated

2017-04-28 07:43 UTC, mrIncompetent commented on provider/kubernetes/kubernetes.go
> +		workerName:       dev,
Outdated

2017-04-28 08:57 UTC, mrIncompetent approved these changes

2017-04-28 08:57 UTC, merged