Feature/delete node with invalid credentials
kubermatic/kubermatic pull request #336
Opened 2017-04-26 08:53 UTC by lbb

Resolves #286

2017-04-26 14:10 UTC, scruplelesswizard requested changes
Please provide a more clear error message

2017-04-26 14:10 UTC, scruplelesswizard commented on provider/types.go
> +var ErrInvalidToken = fmt.Errorf("invalid token")
Please provide a more descriptive error:
Which token is invalid? 
What are the effects of the token being invalid?
Does the user have to take any response?

2017-04-28 13:24 UTC, lbb commented on provider/types.go
> +var ErrInvalidToken = fmt.Errorf("invalid token")
Please consider https://github.com/kubermatic/api/blob/4e26433d4bc36904043cd5fe72878db25a32c600/handler/cluster.go#L302

2017-04-28 13:35 UTC, scruplelesswizard commented on provider/types.go
> +var ErrInvalidToken = fmt.Errorf("invalid token")
>Which token is invalid?

While there is an error string prepended to this in the calling code, we still need to be clear at all levels what is going on.
You still need to explain which token is invalid at a _bare minimum_. Also, calling it the 'cloud provider' token is insufficient, as the user may not associate 'Cloud Provider' with AWS/DO/etc...

2017-04-28 13:41 UTC, scruplelesswizard requested changes

2017-04-28 13:41 UTC, scruplelesswizard commented on handler/cluster.go
> +			err = fmt.Errorf("Error deleting resources on the cloud provider, please manually care about the cleanup: %v", deleteErrors)
>please manually care about the cleanup

This is not valid English. You should instead use:
> please manually clean up any Storage, Nodes or Load Balancers associated with `<the cluster name>`

2017-05-02 10:01 UTC, mrIncompetent approved these changes

2017-05-02 18:37 UTC, scruplelesswizard approved these changes
Lgtm

2017-05-02 18:38 UTC, merged