Feature/jenkins
kubermatic/kubermatic pull request #338
Opened 2017-04-27 14:06 UTC by mrIncompetent

2017-04-28 08:19 UTC, scruplelesswizard requested changes

2017-04-28 08:19 UTC, scruplelesswizard commented on Dockerfile
>  MAINTAINER Dr. Stefan Schimanski <stefan.schimanski@gmail.com>
[Maintainer is Deprecated](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated).

Please drop or use [Labels](https://docs.docker.com/engine/reference/builder/#label) instead

2017-04-28 08:19 UTC, scruplelesswizard commented on Makefile
> +docker:
please rename to `docker-build`

2017-04-28 08:19 UTC, scruplelesswizard commented on Makefile
>  push: docker
Please rename to `docker-push`

2017-04-28 13:22 UTC, scruplelesswizard requested changes
PR is missing documentation

2017-05-02 07:51 UTC, mrIncompetent commented
@chaosaffe `README.md` has been updated to reflect the current changes

2017-05-02 15:52 UTC, merged