Add Antiaffinity & PDBs to dns-resolver, Kubermatic and the monitoring components
kubermatic/kubermatic pull request #3393
Opened 2019-05-01 16:19 UTC by alvaroaleman

**What this PR does / why we need it**:

Adds Pod Antiaffinity and PDBs to the dns-resolver, the Kubermatic control plane and the monitoring components.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Pod AntiAffinity and PDBs were added to the Kubermatic control plane components and the monitoring stack to spread them out if possible and reduce the chance of unavailability
```

2019-05-01 16:23 UTC, alvaroaleman commented
/cherrypick release/v2.10

2019-05-01 17:38 UTC, alvaroaleman commented
/retest

2019-05-01 18:38 UTC, alvaroaleman commented
/assign @mrIncompetent @xrstf

2019-05-01 18:38 UTC, alvaroaleman commented
/cherrypick release/v2.10

2019-05-01 23:53 UTC, xrstf requested changes

2019-05-01 23:53 UTC, xrstf commented on config/kubermatic/templates/kubermatic-api-dep.yaml
> +  affinity:
Deployment spec's have affinity fields? https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#deploymentspec-v1-apps does not mention them.

Also, affinities are meant to be configured in the chart's values.yaml, same for all other charts and we already have *node*AntiAffinities for `kubernetes.io/hostname` -- are those equivalent to your podAntiAffinity?

2019-05-02 05:42 UTC, alvaroaleman commented
> Deployment spec's have affinity fields? https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#deploymentspec-v1-apps does not mention them.

Ofc not :man_facepalming: Good catch!

> Also, affinities are meant to be configured in the chart's values.yaml, same for all other charts 

Yeah because I was looking for affinities at the wrong place I didn't see that. Fixed it up to be in the `values.yaml` everywhere.

> and we already have nodeAntiAffinities for kubernetes.io/hostname -- are those equivalent to your podAntiAffinity?

I think what you mean is `nodeAffinity` for `kubermatic.io/type`? Thats the only affinity I could find.

But those two are not the same. `nodeAffinity` is used to (not-) co-locate a set of pod on a set of nodes whereas `podAntiAffinity` is used to (not-) co-locate a set of pods with each other. Most of the times the latter is done with the purpose of spreading them out in order to reduce the chance of unavailability when a node fails.

Both of them have a `weight`, I have reduced the `weight` of the `podAntiAffinities` to `10` in all places where there was `nodeAffinity` to make sure the `nodeAffinity` is respected first. Let me know what you think.

2019-05-02 06:55 UTC, xrstf requested changes

2019-05-02 06:55 UTC, xrstf commented on config/kubermatic/templates/kubermatic-controller-manager-dep.yaml
> +  affinity:
Leftover?

2019-05-02 07:05 UTC, alvaroaleman commented
@xrstf Fixed the leftover

2019-05-02 07:13 UTC, xrstf commented
/approve no-issue
/lgtm

2019-05-02 07:14 UTC, xrstf commented
/assign @mrIncompetent

2019-05-02 07:43 UTC, alvaroaleman commented
/retest

2019-05-02 08:10 UTC, xrstf approved these changes

2019-05-02 10:58 UTC, mrIncompetent commented
/approve

2019-05-02 10:59 UTC, merged