Maintain a RESTMapper per cluster to avoid performing a discovery on each API call
kubermatic/kubermatic pull request #3405
Opened 2019-05-02 16:09 UTC by mrIncompetent

**What this PR does / why we need it**:
**tl;dr**
The dynamic client performs 33 API calls during creation - Bad for the Kubermatic API latency (When loading Nodes). This PR avoids those calls.

Everytime we create a dynamic client, it performs a discovery process.
The discovery process looks at all available API groups on a Kubernetes API server & fetches the types for each group. This results in a lot if API calls:
```
2019/05/02 17:49:11 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/api?timeout=32s
2019/05/02 17:49:11 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis?timeout=32s
2019/05/02 17:49:11 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/api/v1?timeout=32s
2019/05/02 17:49:11 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/apiregistration.k8s.io/v1?timeout=32s
2019/05/02 17:49:11 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/apiregistration.k8s.io/v1beta1?timeout=32s
2019/05/02 17:49:11 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/extensions/v1beta1?timeout=32s
2019/05/02 17:49:11 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/apps/v1?timeout=32s
2019/05/02 17:49:11 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/apps/v1beta2?timeout=32s
2019/05/02 17:49:11 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/apps/v1beta1?timeout=32s
2019/05/02 17:49:11 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/events.k8s.io/v1beta1?timeout=32s
2019/05/02 17:49:11 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/authentication.k8s.io/v1?timeout=32s
2019/05/02 17:49:11 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/authentication.k8s.io/v1beta1?timeout=32s
2019/05/02 17:49:11 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/authorization.k8s.io/v1?timeout=32s
2019/05/02 17:49:11 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/authorization.k8s.io/v1beta1?timeout=32s
2019/05/02 17:49:11 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/autoscaling/v1?timeout=32s
2019/05/02 17:49:11 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/autoscaling/v2beta1?timeout=32s
2019/05/02 17:49:11 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/autoscaling/v2beta2?timeout=32s
2019/05/02 17:49:12 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/batch/v1?timeout=32s
2019/05/02 17:49:12 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/batch/v1beta1?timeout=32s
2019/05/02 17:49:12 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/certificates.k8s.io/v1beta1?timeout=32s
2019/05/02 17:49:12 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/networking.k8s.io/v1?timeout=32s
2019/05/02 17:49:12 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/policy/v1beta1?timeout=32s
2019/05/02 17:49:12 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/rbac.authorization.k8s.io/v1?timeout=32s
2019/05/02 17:49:13 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/rbac.authorization.k8s.io/v1beta1?timeout=32s
2019/05/02 17:49:13 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/storage.k8s.io/v1?timeout=32s
2019/05/02 17:49:13 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/storage.k8s.io/v1beta1?timeout=32s
2019/05/02 17:49:13 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/admissionregistration.k8s.io/v1beta1?timeout=32s
2019/05/02 17:49:13 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/apiextensions.k8s.io/v1beta1?timeout=32s
2019/05/02 17:49:13 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/scheduling.k8s.io/v1beta1?timeout=32s
2019/05/02 17:49:13 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/coordination.k8s.io/v1beta1?timeout=32s
2019/05/02 17:49:13 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/crd.projectcalico.org/v1?timeout=32s
2019/05/02 17:49:13 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/cluster.k8s.io/v1alpha1?timeout=32s
2019/05/02 17:49:13 https://wflspwnjkn.europe-west3-c.dev.kubermatic.io:32640/apis/metrics.k8s.io/v1beta1?timeout=32s
```

The Kubermatic API unfortunately creates a new dynamic client during each API call which needs to fetch data from a user cluster.
When a user opens the cluster detail page, the Dashboard performs 2 API calls which fetch data from the user cluster:
```
127.0.0.1 - - [02/May/2019:17:58:19 +0200] "GET /api/v1/projects/gjzf628nsg/dc/europe-west3-c/clusters/wflspwnjkn/nodedeployments HTTP/1.1" 200 517 "http://localhost:8000/projects/gjzf628nsg/dc/europe-west3-c/clusters/wflspwnjkn" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36"
127.0.0.1 - - [02/May/2019:17:58:19 +0200] "GET /api/v1/projects/gjzf628nsg/dc/europe-west3-c/clusters/wflspwnjkn/nodes?hideInitialConditions=true HTTP/1.1" 200 2 "http://localhost:8000/projects/gjzf628nsg/dc/europe-west3-c/clusters/wflspwnjkn" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36"
```

This leads to 2 discoveries, each triggering 33 API calls (For an empty user cluster).

To avoid this, i'm introducing a map of "RESTMappers" - For each cluster 1.

But instead if using the default RESTMapper, i'm introducing a wrapper around it.
This avoids having an outdated mapping, which causes errors.
Example:
If the normal RESTMapper got created before we created the Machine/MachineSet/MachineDeployment CRD's, the RESTMapper would not be able to lookup the type information for those types & it will not try to load them. The default RESTMapper only loads the infos during creation.
Upstream issue: https://github.com/kubernetes-sigs/controller-runtime/issues/321

The introduced wrapper will invalidate the mapping and retry the lookup once when it hits an error.

**Does this PR introduce a user-facing change?**:
```release-note
Reduced API latency for loading Nodes & NodeDeployments
```

2019-05-02 16:09 UTC, mrIncompetent commented
/assign @p0lyn0mial @alvaroaleman

2019-05-02 16:10 UTC, mrIncompetent commented
cc @themue

2019-05-03 05:47 UTC, alvaroaleman reviewed
Two nits, but seems like a great change!

2019-05-03 05:47 UTC, alvaroaleman commented on api/pkg/cluster/client/client.go
>  	config, err := p.GetClientConfig(c, options...)
Can we please just pass in and use this config for `getMapper`? This also spares us one call to `GetConfig` if the mapper is not there

2019-05-03 05:47 UTC, alvaroaleman commented on api/pkg/util/restmapper/invalidate.go
> +	for i := 1; i <= 2; i++ {
This feels a bit overly complicated, what about doing something like:

```
import "k8s.io/apimachinery/pkg/api/meta"
if gvk, err = m.mapper.KindFor(resource); err != nil {
  if _, isNoKindMatchErr := err.(*meta.NoKindMatchError); isNoKindMatchErr {
    m.mapper, err = m.newRESTMapping()
    if err != nil {
      return err
    }
    return m.mapper.KindFor(resource)
  }
  return err
}
```

Used https://github.com/openshift/cluster-network-operator/pull/95/files as inspiration

2019-05-03 05:49 UTC, alvaroaleman commented on api/pkg/util/restmapper/invalidate.go
> +	for i := 1; i <= 2; i++ {
The whole checking for the `NoKindMatchError` and if that is the case updating the mapper should probably moved into a `func (m *invalidationMapper) refreshMapperIfIsNoKindMatchErr(err error) error`

2019-05-03 08:16 UTC, mrIncompetent commented on api/pkg/util/restmapper/invalidate.go
> +	for i := 1; i <= 2; i++ {
Haven't seen the openshift code - i'll copy it

2019-05-03 08:27 UTC, mrIncompetent commented on api/pkg/cluster/client/client.go
>  	config, err := p.GetClientConfig(c, options...)
Done with https://github.com/kubermatic/kubermatic/pull/3405/commits/1671abad1ea36fcab955c2fed05c9772a7d431c8

2019-05-03 08:27 UTC, mrIncompetent commented on api/pkg/util/restmapper/invalidate.go
> +	for i := 1; i <= 2; i++ {
Done with https://github.com/kubermatic/kubermatic/pull/3405/commits/1671abad1ea36fcab955c2fed05c9772a7d431c8

2019-05-03 08:48 UTC, alvaroaleman commented on api/pkg/util/restmapper/dynamic.go
> +func (drm *DynamicRESTMapper) reloadOnError(err error) bool {
This func is a bit weird IMHO, can we change it to

`func (drm *DynamicRESTMapper) reloadOnError(err error) (bool, error)`

?

2019-05-03 09:53 UTC, mrIncompetent commented on api/pkg/util/restmapper/dynamic.go
> +func (drm *DynamicRESTMapper) reloadOnError(err error) bool {
I would leave it as it is - changing the signature as you provided would mean we would now need to introduce a dedicated error handling in each consumer.

Going the way via `utilruntime.HandleError(err)` is a nice compromise here as we already have an error which we would return.

2019-05-03 10:04 UTC, alvaroaleman commented
/lgtm
/approve
/hold

so @p0lyn0mial can have a look

2019-05-03 10:17 UTC, themue reviewed
Some comments.

2019-05-03 10:17 UTC, themue commented on api/pkg/cluster/client/client.go
> +	mapperLock *sync.Mutex
No need to make it a reference and explicitly create a mutex. Typical pattern is 

```go
type provider struct {
    mu sync.Mutex
    ...
}

func (p *provider) mapper(...) (meta.RESTMapper, error) {
    p.mu.Lock()
    defer p.mu.Unlock()

    ...
}
```

See e.g. source code of HTTP server.

2019-05-03 10:17 UTC, themue commented on api/pkg/cluster/client/client.go
> +func (p *provider) getMapper(c *kubermaticv1.Cluster, config *restclient.Config) (meta.RESTMapper, error) {
Are we forced to use get prefixes here and in general? It's not convention, see https://golang.org/doc/effective_go.html#Getters . Sadly it finds its way into Go code by devs coming from other languages. Seen it a lot in Ethereum code too.

2019-05-03 10:17 UTC, themue commented on api/pkg/util/restmapper/dynamic.go
> +func (drm *DynamicRESTMapper) KindFor(resource schema.GroupVersionResource) (schema.GroupVersionKind, error) {
Any reason why public methods of a public type have no godoc comment?

2019-05-03 10:17 UTC, themue commented on api/pkg/util/restmapper/dynamic.go
> +	gvks, err := drm.delegate.KindsFor(resource)
All these repeating patterns look more like a retry pattern to me:

```go
func (drm *DynamicRESTMapper) KindsFor(resource schema.GroupVersionResource) (gvks []schema.GroupVersionKind, err error) {
    drm.retry(func() error {
        gvks, err = drm.delegate.KindsFor(resource)
        return err
    }, 2)
}
```

where `retry()` reloads as often as the error type is matching and the counter (here 2) is not reached.

2019-05-07 06:53 UTC, p0lyn0mial requested changes

2019-05-07 06:53 UTC, p0lyn0mial commented on api/pkg/cluster/client/client.go
> +	glog.Infof("Created a mapper for cluster %s", c.Name)
isn't this a debug msg ?

2019-05-07 06:53 UTC, p0lyn0mial commented on api/pkg/cluster/client/client.go
> +		return nil, fmt.Errorf("failed to get the REST mapper for the client: %v", err)
instead of failing we could create the `ctrlruntimeclient` as before without the `mapper`, the request will likely succeed. If we would like to know how many times we failed to create the mapper we could collect some metric.

2019-05-07 06:53 UTC, p0lyn0mial commented on api/pkg/util/restmapper/dynamic.go
> +	drm.delegate = restmapper.NewDiscoveryRESTMapper(gr)
this is a data race, `meta.RESTMapper` is created once and used by many threads. For example, one thread can call `KindFor` and reach this line (WRITE) and at the same time other thread calling `ResourceFor` can `drm.delegate.ResourceFor(input)` (READ).

I think we could use `sync.RWMutex` to guard the delegate variable.

2019-05-07 06:53 UTC, p0lyn0mial commented on api/pkg/util/restmapper/dynamic.go
> +func NewDynamicRESTMapper(cfg *rest.Config) (meta.RESTMapper, error) {
since we use Impersonation and cache `meta.RESTMapper` we can create the mapper for one user and then reuse for other users. For example, imagine that we store the mapper for `Bob` then for every request that `John` makes the kubeAPI server sees it as if it was `Bob`. 

This is only inconvenient for auditing. We could change this by:
 - creating the mapper for anonymous user, discovery is available for unauthenticated users.
 - always create the mapper as an admin.

2019-05-07 06:56 UTC, p0lyn0mial commented on api/pkg/util/restmapper/dynamic.go
> +	drm.delegate = restmapper.NewDiscoveryRESTMapper(gr)
/cc @zreigz it would be really nice to run the API server for E2E tests with `-race` flag enabled.

2019-05-07 06:56 UTC, alvaroaleman commented on api/pkg/util/restmapper/dynamic.go
> +func NewDynamicRESTMapper(cfg *rest.Config) (meta.RESTMapper, error) {
> creating the mapper for anonymous user, discovery is available for unauthenticated users.

This will change for 1.15: https://github.com/kubernetes/kubernetes/pull/73807

2019-05-08 14:30 UTC, mrIncompetent commented on api/pkg/util/restmapper/dynamic.go
> +func NewDynamicRESTMapper(cfg *rest.Config) (meta.RESTMapper, error) {
We actually reuse the mapping across the different users.
We use the cluster name as key for the map of mappers.

This means that unauthenticated users could have access to the discovery information, given that the kubermatic API actually exposes it.

I don't see any big downside of that though.

2019-05-08 14:42 UTC, mrIncompetent commented on api/pkg/util/restmapper/dynamic.go
> +	drm.delegate = restmapper.NewDiscoveryRESTMapper(gr)
Done with https://github.com/kubermatic/kubermatic/pull/3405/commits/4894d7a5279b66bc6c1a701a95b7bf7c8df65a5a

2019-05-08 14:42 UTC, mrIncompetent commented on api/pkg/cluster/client/client.go
> +		return nil, fmt.Errorf("failed to get the REST mapper for the client: %v", err)
Done with https://github.com/kubermatic/kubermatic/pull/3405/commits/4894d7a5279b66bc6c1a701a95b7bf7c8df65a5a

2019-05-08 14:42 UTC, mrIncompetent commented on api/pkg/cluster/client/client.go
> +	glog.Infof("Created a mapper for cluster %s", c.Name)
Done with https://github.com/kubermatic/kubermatic/pull/3405/commits/4894d7a5279b66bc6c1a701a95b7bf7c8df65a5a

2019-05-08 14:42 UTC, mrIncompetent commented on api/pkg/cluster/client/client.go
> +func (p *provider) getMapper(c *kubermaticv1.Cluster, config *restclient.Config) (meta.RESTMapper, error) {
Done with https://github.com/kubermatic/kubermatic/pull/3405/commits/4894d7a5279b66bc6c1a701a95b7bf7c8df65a5a

2019-05-08 14:43 UTC, mrIncompetent commented on api/pkg/util/restmapper/dynamic.go
> +	gvks, err := drm.delegate.KindsFor(resource)
I thought about it, but we explicitly want to only retry once & perfom a certain action if the first attempt fails. Which is why i would prefer the simplicity of the simple `if` for now

2019-05-08 14:44 UTC, mrIncompetent commented on api/pkg/cluster/client/client.go
> +	mapperLock *sync.Mutex
Done with https://github.com/kubermatic/kubermatic/pull/3405/commits/4894d7a5279b66bc6c1a701a95b7bf7c8df65a5a

2019-05-08 15:43 UTC, mrIncompetent commented on api/pkg/util/restmapper/dynamic.go
> +func (drm *DynamicRESTMapper) KindFor(resource schema.GroupVersionResource) (schema.GroupVersionKind, error) {
Added with https://github.com/kubermatic/kubermatic/pull/3405/commits/522b1d4b8784e8d774653105231fb9da75a287a9

2019-05-08 15:44 UTC, mrIncompetent commented
@alvaroaleman @p0lyn0mial @themue PTAL

2019-05-09 08:12 UTC, mrIncompetent commented
/retest

2019-05-09 08:34 UTC, p0lyn0mial commented on api/pkg/util/restmapper/dynamic.go
> +	// The discovery takes some time
nit: not sure if this comment is informative :P

2019-05-09 08:34 UTC, p0lyn0mial commented on api/pkg/util/restmapper/dynamic.go
> +	gvk, err := drm.mapper().KindFor(resource)
took me some time to convince myself this is safe but it is - nice !

2019-05-09 08:36 UTC, p0lyn0mial commented on api/pkg/cluster/client/client.go
> +	glog.V(4).Infof("Created a mapper for cluster %s", c.Name)
no structured logging yet ?

2019-05-09 08:37 UTC, mrIncompetent commented on api/pkg/cluster/client/client.go
> +	glog.V(4).Infof("Created a mapper for cluster %s", c.Name)
Not yet :/ I'm working on it

2019-05-09 08:37 UTC, p0lyn0mial commented on api/pkg/cluster/client/client.go
> +	glog.V(4).Infof("Created a mapper for cluster %s", c.Name)
oh, the pr not merged yet https://github.com/kubermatic/kubermatic/pull/3296

2019-05-09 08:38 UTC, p0lyn0mial commented
nice pull @mrIncompetent 

/lgtm
/approve

2019-05-09 10:31 UTC, alvaroaleman commented
/approve no-issue

2019-05-09 10:46 UTC, alvaroaleman commented
/hold cancel

2019-05-09 12:44 UTC, merged

2019-05-14 13:19 UTC, mrIncompetent commented
/cherrypick release/v2.10