Return seed with created cluster
kubermatic/kubermatic pull request #345
Opened 2017-05-10 15:21 UTC by lbb

2017-05-10 15:25 UTC, mrIncompetent requested changes

2017-05-10 15:25 UTC, mrIncompetent commented on types.go
> +	Seed     string          `json:"seed,omitempty"`
Marshal & Unmarshal is missing. Otherwise this field will be emtpy across all requests except for the createClusterV2 request

2017-05-10 15:26 UTC, lbb commented on types.go
> +	Seed     string          `json:"seed,omitempty"`
Thats right... we only need use it there. 
Do we need it to be marshalled ?

2017-05-10 15:29 UTC, mrIncompetent commented on types.go
> +	Seed     string          `json:"seed,omitempty"`
Yes, otherwise this will be highly confusing as soon as we access this field somewhere else

2017-05-11 09:53 UTC, mrIncompetent approved these changes

2017-05-11 10:08 UTC, merged