Feature/jenkins e2e
kubermatic/kubermatic pull request #348
Opened 2017-05-18 09:15 UTC by lbb

Closes kubermatic/config#218

2017-05-22 10:23 UTC, lbb commented
Depends #347

2017-06-15 10:20 UTC, mrIncompetent commented on hack/e2e/Dockerfile
> +RUN go run e2e.go -- -v --extract=release/stable-1.6
The version should be somehow configurable. Maybe an env-var?

2017-06-15 10:20 UTC, mrIncompetent commented on hack/e2e/Makefile
> +TAG = 1.6
Should be configurable. Maybe a command line parameter?

2017-06-15 10:20 UTC, mrIncompetent commented on cmd/client/main.go
> +	jwtToken   = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBfbWV0YWRhdGEiOnsicm9sZXMiOlsidXNlciJdfSwiaXNzIjoiaHR0cHM6Ly9rdWJlcm1hdGljLmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJnaXRodWJ8NzM4NzcwMyIsImF1ZCI6InpxYUd
I assume this wont work anymore when using OpenID connect with rsa keys?

2017-06-15 10:22 UTC, mrIncompetent commented on hack/e2e/Dockerfile
> +# This is a huge hacky!!1!1! and shitty Dockerfile!!, 6,28Gb WTF!? o.O
Clearly state what could be improved.

2017-07-02 19:04 UTC, lbb commented on hack/e2e/Dockerfile
> +RUN go run e2e.go -- -v --extract=release/stable-1.6
Do you mean at build time?
I'd rather not execute this during runtime because of the massive time and network traffic this is consuming.

2017-07-02 19:05 UTC, lbb commented on cmd/client/main.go
> +	jwtToken   = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBfbWV0YWRhdGEiOnsicm9sZXMiOlsidXNlciJdfSwiaXNzIjoiaHR0cHM6Ly9rdWJlcm1hdGljLmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJnaXRodWJ8NzM4NzcwMyIsImF1ZCI6InpxYUd
When we are using sex we can use a static account to get a token (with Auth0 we can do the same).
This is a dependency, thus this cannot be merged without a static login/token.

2017-07-03 06:48 UTC, mrIncompetent commented on cmd/client/main.go
> +	jwtToken   = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBfbWV0YWRhdGEiOnsicm9sZXMiOlsidXNlciJdfSwiaXNzIjoiaHR0cHM6Ly9rdWJlcm1hdGljLmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJnaXRodWJ8NzM4NzcwMyIsImF1ZCI6InpxYUd
"sex"

![Image of Yaktocat](https://media.giphy.com/media/3oEjHAUOqG3lSS0f1C/giphy.gif)

2017-08-08 21:41 UTC, lbb commented
Things to be done:
* Jenkins build does not link the templates (wrecker does)
* Jenkins junit import of e2e results
* Define when e2e should run (trigger, on dev-merge?)
* (Go to unit export)

2017-08-09 14:37 UTC, mrIncompetent requested changes

2017-08-09 14:37 UTC, mrIncompetent commented on hack/e2e/Dockerfile
> +# TODO(realfake): Strip this nonsense
Clearly state what could be improved. Avoid words like `nonsense`

2017-08-09 14:37 UTC, mrIncompetent commented on Makefile
> +GOBUILDFLAGS= -i
Why `-i` ?

2017-08-09 14:37 UTC, mrIncompetent commented on Jenkinsfile
> +              sh("make e2e")
According to the readme, `make client-up` is missing.
Why is it not used here?
If its not mandatory, update the readme

2017-08-09 14:37 UTC, mrIncompetent commented on cmd/client/main.go
> +	getToken()
Remove the global token variable and make this function return the token.
It should be passed into the client.
Global variables are bad

2017-08-09 14:37 UTC, mrIncompetent commented on extensions/client.go
> +	// New method!
Instead of making comments about whats new:

Explain why we actually hash the base64 string...

2017-08-09 14:37 UTC, mrIncompetent commented on hack/e2e/Dockerfile
> +MAINTAINER Luk Burchard <luk@loodse.com>
Maintainer is deprecated. Use a label

2017-08-09 14:37 UTC, mrIncompetent commented on provider/kubernetes/marshal.go
>  func LabelUser(user string) string {
Whats the difference to the NormalizeUser function?
Looks pretty much the same

2017-08-09 14:40 UTC, lbb commented on Makefile
> +GOBUILDFLAGS= -i
The -i flag installs the packages that are dependencies of the target.

2017-08-09 14:41 UTC, lbb commented on Makefile
> +GOBUILDFLAGS= -i
This speeds up multiple builds

2017-08-09 14:42 UTC, lbb commented on cmd/client/main.go
> +	getToken()
The jet key is used in many places, this script will be deprecated when we have the client.

2017-08-09 15:29 UTC, lbb commented on Jenkinsfile
> +              sh("make e2e")
Fixed

2017-08-09 15:34 UTC, guusvw requested changes

2017-08-09 15:34 UTC, guusvw commented on cmd/client/main.go
> +	errorString := "Invalid username and password"
Define it as a constant or use it directly in `strings.Contains(...)`

2017-08-09 15:39 UTC, lbb commented on hack/e2e/Makefile
> +TAG = 1.6
Same as above

2017-08-09 15:44 UTC, guusvw approved these changes

2017-08-09 16:21 UTC, mrIncompetent approved these changes

2017-08-09 16:22 UTC, merged