Preparation for node-controller-integration
kubermatic/kubermatic pull request #362
Opened 2017-07-03 07:39 UTC by mrIncompetent

2017-07-03 08:21 UTC, lbb requested changes

2017-07-03 08:21 UTC, lbb commented on glide.yaml
> +  version: 1.*
please use ^1.0.0

2017-07-03 08:21 UTC, lbb commented on cmd/kubermatic-cluster-controller/main.go
> +	if *masterResources == "" {
also check `externalURL `(Required)

2017-07-03 08:21 UTC, lbb commented on cmd/kubermatic-cluster-controller/main.go
> +		glog.Fatal(fmt.Printf("failed to load version yaml %q: %v", *versionsFile, err))
Remove `fmt.Printf` or change it to `fmt.Sprintf`

2017-07-03 08:21 UTC, lbb commented on cmd/kubermatic-cluster-controller/main.go
> +			glog.Fatal(fmt.Printf("failed to load updates yaml %q: %v", *updatesFile, err))
Remove `fmt.Printf` or change it to `fmt.Sprintf`

2017-07-05 10:09 UTC, mrIncompetent commented on cmd/kubermatic-cluster-controller/main.go
> +	if *masterResources == "" {
fixed

2017-07-05 11:43 UTC, scheeles approved these changes
LGTM

2017-07-05 11:43 UTC, scheeles commented on cmd/kubermatic-api/main.go
secretsFile is not required any more or?

2017-07-05 12:16 UTC, mrIncompetent commented on cmd/kubermatic-api/main.go
Nope, i removed the code which required it. We never used or even maintained it

2017-07-05 12:50 UTC, merged