Feature/node controller
kubermatic/kubermatic pull request #368
Opened 2017-07-25 13:31 UTC by mrIncompetent

closes kubermatic/api#355

2017-08-11 15:12 UTC, guusvw requested changes

2017-08-11 15:12 UTC, guusvw commented on handler/cluster.go
> +				time.Sleep(1 * time.Second)
Maybe you should make the delay configurable?

2017-08-11 15:12 UTC, guusvw commented on handler/node.go
> +				time.Sleep(200 * time.Millisecond)
Maybe you should make the delay configurable?

2017-08-11 15:12 UTC, guusvw commented on handler/node.go
> +		dc := req.clusterReq.dcReq.dc
Why don't you use `req.dc`?
In Line 115 it is also used.

2017-08-11 15:12 UTC, guusvw commented on provider/cloud/aws/provider.go
> +		FromPort:   aws.Int64(22),
I think it would be awesome, to have something like a `defaultSSHPort` constant.

2017-08-11 15:12 UTC, guusvw commented on provider/cloud/aws/provider.go
> +		return fmt.Errorf("failed to get ec2 ec2client: %v", err)
A little typo

2017-08-14 06:58 UTC, mrIncompetent commented on handler/cluster.go
> +				time.Sleep(1 * time.Second)
Done with 1d0f23b1a759b12a678f25700f8abbc8ca942a95

2017-08-14 06:58 UTC, mrIncompetent commented on handler/node.go
> +				time.Sleep(200 * time.Millisecond)
done with 1d0f23b1a759b12a678f25700f8abbc8ca942a95

2017-08-14 06:58 UTC, mrIncompetent commented on handler/node.go
> +		dc := req.clusterReq.dcReq.dc
Unintentionally done with 1d0f23b1a759b12a678f25700f8abbc8ca942a95

2017-08-14 06:59 UTC, mrIncompetent commented on provider/cloud/aws/provider.go
> +		FromPort:   aws.Int64(22),
done with ef54af3b3215554e261131c81515425eae3634a0

2017-08-14 06:59 UTC, mrIncompetent commented on provider/cloud/aws/provider.go
> +		return fmt.Errorf("failed to get ec2 ec2client: %v", err)
Unintentionally done with ef54af3b3215554e261131c81515425eae3634a0

2017-08-14 07:55 UTC, guusvw submitted a review, later dismissed

2017-08-14 09:42 UTC, guusvw submitted a review, later dismissed

2017-08-15 06:52 UTC, merged