Allow specifying tokens using secrets
kubermatic/kubermatic pull request #3684
Opened 2019-06-21 06:08 UTC by nikhita

For https://github.com/kubermatic/kubermatic/issues/2336

Work in progress, but would love some initial feedback.

/cc @alvaroaleman 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2019-06-21 08:00 UTC, alvaroaleman commented on api/pkg/resources/data.go
> +	// We need all three of these to fetch and use a secret
As this will most likely be needed in many places, it may make sense to generate the func via a factory and use that everywhere:

```
func ConfigVarStringGetterFactoy(ctx context.Context, client client.Client) func (configVar providerconfig.GlobalSecretKeySelector) (string, error)
```

2019-06-21 08:00 UTC, alvaroaleman commented on api/pkg/crd/kubermatic/v1/cluster.go
> -	APIKey       string `json:"apiKey"`
I do not really feel comfortable changing the existing field. It will make migration code weird as we'd need to build a custom json unmarshaller that can cope with both the field being a string and it being a `GlobalSecretKeySelector`.

I'd prefer it if we instead added new field `OriginalFieldNameReference`, e.G. `APIKeyReference` here and add a comment to the old field that they are deprecated

2019-07-02 06:15 UTC, nikhita commented
One question I had around this was... should secrets be created using the credentials defined in `pkg/presets/manager.go` and then `secretRef` for these secrets be "copied" onto the cluster object?

I'm not entirely sure if this somehow conflicts with the credentials work from the API team? In other words: are the "presets" intended to be copied directly to the cluster object? cc @zreigz

2019-07-02 09:27 UTC, zreigz commented
@nikhita 
Instead of passing credentials or other parameters needed to create a cluster in UI, we prepared presets for this. User can specify presets with credentials and extended parameters and just use the preset name. In this part, we search for the values and inject them to cluster spec: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/handler/v1/cluster/cluster.go#L75
The presets manager converts the preset name to values which must be used to create the cluster object.

According to your question if secrets should be generated from the presets.
Presets are designed to add possibilities to use predefined credentials instead of passing all the time. When the presets are defined than our UI display credential name and use them by default. The custom credential feature was requested by big companies to be able to create clusters for individual employees. The admin will spin up the kubermatic with some provider credential which belongs to the company, not to the individual person.

When you start using presets for generating secrets then you enable this feature. It has some implications. Different users assigned to different projects can use the same credentials.

In my opinion, there are two scenarios for your issue:
First, you should create secrets from credentials passed from the user in UI and they stay until cluster exist.
Second, when presets are defined then you can use them to create secrets. In this case, we need some mechanism to check if the presets still exist or someone didn't change them to be able delete/update secrets

2019-07-03 07:00 UTC, nikhita commented
@zreigz thank you so much for that explanation! :) Updated with some new code for creating/deleting secrets as the cluster is created/deleted but I had some more questions.

> Second, when presets are defined 

- My understanding is that the current state of things (i.e. not the changes in this PR) is like: credentials will _always_ be supplied using presets and then these credential values are injected into the clusterSpec. However, is it possible that presets might not be defined? In this case, how are credentials being supplied - directly through the cluster spec?

- Should we be adding an option to selectively define when secrets should be used for credentials vs directly injecting the values into the cluster object? Without that, I'm confused how we can decide whether to directly copy the values or use a secretKeyRef...

> we need some mechanism to check if the presets still exist

- Would this mean adding something to check if the preset (endpoint) was updated? Or...?

> someone didn't change them to be able delete/update secrets

- If someone deleted them, would we just delete the secret and give an error (because of lack of credentials) or do we also take up follow-up actions (delete anything else?) :thinking:

2019-07-08 07:27 UTC, alvaroaleman commented on api/pkg/api/v1/types.go
> +	CredentialsSecretsCleanupFinalizer = "kubermatic.io/cleanup-credentials-secrets"
Its easier to instead just put an OwnerRef pointing to the cluster CR on the secret and letting the garbage collector take care

2019-07-08 07:27 UTC, alvaroaleman commented on api/pkg/controller/openshift/data.go
> +func (od *openshiftData) GetConfigVarStringValue(configVar providerconfig.GlobalSecretKeySelector) (string, error) {
Is this still needed?

2019-07-08 07:27 UTC, alvaroaleman commented on api/pkg/handler/v1/cluster/credential_secrets.go
> +			Namespace: "kubermatic-secrets",
Lets make this a const

2019-07-08 07:27 UTC, alvaroaleman commented on api/pkg/provider/cloud/packet/provider.go
> +		if apiKey.Name == "" && apiKey.Namespace == "" && apiKey.Key == "" {
This should be ` ||` instead of `&&` as we need all three of them or not?

2019-07-08 07:27 UTC, alvaroaleman commented on api/pkg/provider/cloud/packet/provider.go
> +		if apiKey.Name == "" && apiKey.Namespace == "" && apiKey.Key == "" {
And I guess we will have a lot of these checks, so better DRY it out and put it into a func :)

2019-07-08 07:27 UTC, alvaroaleman commented on api/pkg/resources/data.go
> +func (d *TemplateData) GetConfigVarStringValue(configVar providerconfig.GlobalSecretKeySelector) (string, error) {
Can we rename this to something like "GetGlobalSecretKeySelectorValue`? :grimacing:

2019-07-08 07:27 UTC, alvaroaleman commented on api/pkg/resources/data.go
> +			return "", fmt.Errorf("error retrieving secret '%s' from namespace '%s': '%v'", configVar.Name, configVar.Namespace, err)
Nit: Using `%q` achieves almost the same as `'%s` but takes less space in the code

2019-07-08 07:27 UTC, alvaroaleman commented on api/pkg/resources/data.go
> +// TODO: use this instead, and mostly move this to another file?
We'll need this at least in the openshift and the monitoring controller as well, so yeah, the factory makes sense :)

2019-07-10 08:50 UTC, alvaroaleman commented on api/pkg/controller/cluster/resources.go
> +func GetDeploymentCreators(data *resources.TemplateData, enableAPIserverOIDCAuthentication bool, getGlobalSecretKeySelectorValue resources.GetGlobalSecretKeySelectorValue) []reconciling.NamedDeployme
Whats the reason for not making the `getGlobalSecretKeySelectorValue` part of `data`?

2019-07-10 08:50 UTC, alvaroaleman commented on api/pkg/crd/kubermatic/v1/cluster.go
> +	APIKey string `json:"apiKey"`
Can we haz `omitempty`? :)

2019-07-10 08:50 UTC, alvaroaleman commented on api/pkg/handler/v1/cluster/credential_secrets.go
> +			Namespace: KubermaticSecretsNamespace,
Can you add the creation of the NS to the Kubermatic Helm chart?

2019-07-10 08:50 UTC, alvaroaleman commented on api/pkg/handler/v1/cluster/credential_secrets.go
> +	client, err := clusterProvider.GetClientForCustomerCluster(userInfo, cluster)
This gives you a client for the usercluster but we want to store the secret in the seed cluster :)

2019-07-10 08:50 UTC, alvaroaleman commented on api/pkg/validation/cluster.go
> +	if selector.Name == "" && selector.Namespace == "" && selector.Key == "" {
Can we also check if we can actually get the secret? :grimacing:

2019-07-10 11:40 UTC, alvaroaleman commented on api/pkg/controller/cluster/resources.go
> +func GetDeploymentCreators(data *resources.TemplateData, enableAPIserverOIDCAuthentication bool, getGlobalSecretKeySelectorValue resources.GetGlobalSecretKeySelectorValue) []reconciling.NamedDeployme
?

2019-07-10 11:42 UTC, nikhita commented on api/pkg/controller/cluster/resources.go
> +func GetDeploymentCreators(data *resources.TemplateData, enableAPIserverOIDCAuthentication bool, getGlobalSecretKeySelectorValue resources.GetGlobalSecretKeySelectorValue) []reconciling.NamedDeployme
Doing that now.

2019-07-11 05:19 UTC, nikhita commented on api/pkg/controller/cluster/resources.go
> +func GetDeploymentCreators(data *resources.TemplateData, enableAPIserverOIDCAuthentication bool, getGlobalSecretKeySelectorValue resources.GetGlobalSecretKeySelectorValue) []reconciling.NamedDeployme
> Whats the reason for not making the getGlobalSecretKeySelectorValue part of data?

So I've tried a few things but now I'm confused what you meant :sweat_smile:

Wouldn't making it part of data essentially revert back to the old state i.e. without the `GlobalSecretKeySelectorValueGetterFactory`?

2019-07-11 07:24 UTC, alvaroaleman commented on api/pkg/controller/cluster/resources.go
> +func GetDeploymentCreators(data *resources.TemplateData, enableAPIserverOIDCAuthentication bool, getGlobalSecretKeySelectorValue resources.GetGlobalSecretKeySelectorValue) []reconciling.NamedDeployme
By that I meant extend the `templateData` struct with a `GetGlobalSecretKeySelectorValue` func

2019-07-12 07:58 UTC, alvaroaleman reviewed
Two small comments and can we also have a migration that creates the secret if no ref exists but the cluster has the string values on it? :grimacing: 

Thanks for all your work on this!

2019-07-12 07:58 UTC, alvaroaleman commented on api/pkg/controller/openshift/resources/machinecontroller.go
> +func MachineController(osData openshiftData, getGlobalSecretKeySelectorValue resources.GetGlobalSecretKeySelectorValue) reconciling.NamedDeploymentCreatorGetter {
I think the added argument is not needed anymore, as its part of `osData`

2019-07-12 07:58 UTC, alvaroaleman commented on api/pkg/resources/machinecontroller/deployment.go
> +func DeploymentCreator(data machinecontrollerData, getGlobalSecretKeySelectorValue resources.GetGlobalSecretKeySelectorValue) reconciling.NamedDeploymentCreatorGetter {
Just extend the `machinecontrollerData` interface so the additional arg is not needed

2019-07-12 09:28 UTC, nikhita commented on api/pkg/resources/machinecontroller/deployment.go
> +func DeploymentCreator(data machinecontrollerData, getGlobalSecretKeySelectorValue resources.GetGlobalSecretKeySelectorValue) reconciling.NamedDeploymentCreatorGetter {
> Just extend the machinecontrollerData interface so the additional arg is not needed

This would work here, but then we'll also need to add a new method which would do this for `TemplateData` so that it will then satisfy this interface....unless I'm missing something...

2019-07-12 13:01 UTC, alvaroaleman commented on api/pkg/resources/machinecontroller/deployment.go
> +func DeploymentCreator(data machinecontrollerData, getGlobalSecretKeySelectorValue resources.GetGlobalSecretKeySelectorValue) reconciling.NamedDeploymentCreatorGetter {
Yes. The purpose of the `templateData` struct is exactly that: Carry all Informationen needed by any resource around

2019-07-16 06:00 UTC, nikhita commented
/test pull-kubermatic-e2e-packet-coreos-1.14

2019-07-16 06:19 UTC, nikhita commented
/test pull-kubermatic-e2e-packet-coreos-1.14

2019-07-16 08:45 UTC, nikhita commented
/test pull-kubermatic-e2e-packet-coreos-1.14

2019-07-16 09:54 UTC, nikhita commented
/test pull-kubermatic-e2e-packet-coreos-1.14

2019-07-16 10:09 UTC, nikhita commented
/test pull-kubermatic-e2e-packet-coreos-1.14

2019-07-16 11:06 UTC, nikhita commented
/hold

2019-07-16 11:35 UTC, nikhita commented
/test pull-kubermatic-e2e-packet-coreos-1.14

:crossed_fingers: :pray:

2019-07-16 12:19 UTC, nikhita commented
/test pull-kubermatic-e2e-packet-coreos-1.14

2019-07-16 12:43 UTC, nikhita commented
/test pull-kubermatic-e2e-packet-coreos-1.14

:prayer_beads: :pray:

2019-07-16 13:01 UTC, nikhita commented
/test pull-kubermatic-e2e-packet-coreos-1.14

2019-07-16 13:56 UTC, nikhita commented
/test pull-kubermatic-e2e-packet-coreos-1.14

2019-07-16 14:47 UTC, nikhita commented
The last run almost worked :)

/test pull-kubermatic-e2e-packet-coreos-1.14

2019-07-16 15:44 UTC, nikhita commented
It worked. \o/

PTAL :)

2019-07-16 17:51 UTC, alvaroaleman reviewed
almost there :))

2019-07-16 17:51 UTC, alvaroaleman commented on api/pkg/clusterdeletion/deletion.go
> +	if err := d.seedClient.List(ctx, &controllerruntimeclient.ListOptions{Namespace: "kubermatic-secrets"}, secretList); err != nil {
Why do we delete _all_ secrets? Shouldn't we just delete the one that is named like our cluster?

Also we should tolerate a 404 as non error when we try to get our secret :)

2019-07-16 17:51 UTC, alvaroaleman commented on api/pkg/handler/v1/cluster/cluster.go
> +		partialCluster.Name = rand.String(10)
Can we do a quick `GET` to ensure we get a 404 for that name? :grimacing:

2019-07-16 17:51 UTC, alvaroaleman commented on api/cmd/conformance-tests/runner.go
> +		if handlerv1.ShouldAddSecretsCleanupFinalizer(cluster) {
I think we can add this unconditionally and just tolerate a 404 on deletion

2019-07-16 17:51 UTC, alvaroaleman commented on api/pkg/handler/v1/cluster/credential_secrets.go
> +func createPacketSecret(cluster *v1.Cluster, priviligedClusterProvider provider.PrivilegedClusterProvider) error {
Just add the `context` as first arg and move the `TODO` into the caller if no context is available there?

2019-07-16 17:51 UTC, alvaroaleman commented on api/pkg/controller/openshift/data.go
> +func (od *openshiftData) GetGlobalSecretKeySelectorValue(configVar providerconfig.GlobalSecretKeySelector) (string, error) {
Why not use the `GlobalSecretKeySelectorValueGetterFactory`?

2019-07-16 17:51 UTC, alvaroaleman commented on api/cmd/projects-migrator/main.go
> +			if _, err := client.CoreV1().Secrets("kubermatic-secrets").Create(packetSecret); err != nil {
Use the const :grimacing:

2019-07-17 01:35 UTC, nikhita commented on api/pkg/controller/openshift/data.go
> +func (od *openshiftData) GetGlobalSecretKeySelectorValue(configVar providerconfig.GlobalSecretKeySelector) (string, error) {
Because would require the `GetGlobalSecretKeySelectorValue` to be added as a field to the `osData` struct, which doesn't gel well while using with DeploymentCreators because they expect a method instead of a field. :/

2019-07-17 01:42 UTC, nikhita commented
/test pull-kubermatic-e2e-packet-coreos-1.14

2019-07-17 02:52 UTC, nikhita commented on api/pkg/handler/v1/cluster/cluster.go
> +		partialCluster.Name = rand.String(10)
Did that but tests were failing because of :disappointed: 

```
 [FAIL] - aws-coreos-1.13.5 : failed to create cluster: failed to create cluster via kubermatic api: "{\"Payload\":{\"error\":{\"details\":null,\"code\":500,\"message\":\"unable to generate unique cluster name even after 5 tries, error: clusters.kubermatic.k8s.io \\\"4hfq8jcw54\\\" is forbidden: User \\\"serviceaccount-2zqm6cfghz@ci.kubermatic.io\\\" cannot get resource \\\"clusters\\\" in API group \\\"kubermatic.k8s.io\\\" at the cluster scope\"}}}" 
```

2019-07-17 07:05 UTC, alvaroaleman commented on api/pkg/controller/openshift/data.go
> +func (od *openshiftData) GetGlobalSecretKeySelectorValue(configVar providerconfig.GlobalSecretKeySelector) (string, error) {
hm, I think its possible to do something like:

```
type openshiftData struct {
 globalSecretKeySelector func(args type)
}

func (os *openshiftData) GlobalSecretKeyselector(args type) {
return od.globalSecretKeySelector(args type)
}
```

But can be a follow-up

2019-07-17 07:06 UTC, alvaroaleman commented
/test pull-kubermatic-e2e-packet-coreos-1.14

2019-07-17 07:07 UTC, alvaroaleman commented
Lets merge this if the packet presubmit passes
/approve

2019-07-17 07:07 UTC, alvaroaleman commented
@zreigz Can you have a look?

2019-07-17 07:35 UTC, zreigz commented
> @zreigz Can you have a look?

yes, I will review this today

2019-07-17 09:59 UTC, zreigz requested changes

2019-07-17 09:59 UTC, zreigz commented on api/pkg/resources/resources.go
> +	KubermaticSecretsNamespace = "kubermatic-secrets"
Helm installer supports only one namespace: `kubermatic`. For SA we also create `Secrets` and we store them in `kubermatic` namespace otherwise operator must create the new namespace manually. It also has implications with e2e tests.

2019-07-17 09:59 UTC, zreigz commented on api/pkg/handler/v1/cluster/credential_secrets.go
> +func CreateSecretsForCredentials(ctx context.Context, cluster *v1.Cluster, priviligedClusterProvider provider.PrivilegedClusterProvider) error {
Instead of this part, please introduce CredentialSecretsProvider. The similar provider is here: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/provider/kubernetes/sa_token.go
We also create Secret for SA but using ImpersonatedClient. 
In addition, you need to extend RBAC controller for cluster secrets with your specific prefix: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/controller/rbac/rbac_controller_aggregator.go#L99
I recommend using one prefix for all providers. I can handle the changes for RBAC because it's the hardest part and very difficult to test.
When you create this provider then you will be able to test cluster creation for the Packet.

2019-07-18 09:59 UTC, nikhita commented
Updated. PTAL.

2019-07-18 18:29 UTC, zreigz requested changes

2019-07-18 18:29 UTC, zreigz commented on api/pkg/provider/kubernetes/credentials.go
> +	createdSecret.Name = removeTokenPrefix(createdSecret.Name)
you can remove this line

2019-07-18 18:29 UTC, zreigz commented on api/pkg/provider/kubernetes/credentials.go
> +	name := fmt.Sprintf("%spacket-%s", CredentialPrefix, cluster.Name)
please change the prefix to `credential` and patter to `%s-packet-%s`

2019-07-18 18:29 UTC, zreigz commented on api/pkg/provider/kubernetes/sa_token.go
> +	createdToken, err := kubernetesImpersonatedClient.CoreV1().Secrets(resources.KubermaticNamespace).Create(secret)
thanks for this :)

2019-07-18 18:34 UTC, zreigz commented
From the API perspective small changes. 
I've run it locally and I didn't notice any pod deployment for the cluster and I couldn't delete cluster because of the new finalizer. 
We can discuss it tomorrow

2019-07-19 10:37 UTC, nikhita commented
/test pull-kubermatic-e2e-packet-coreos-1.14

2019-07-22 05:28 UTC, nikhita commented
/test pull-kubermatic-e2e-packet-coreos-1.14

2019-07-22 07:39 UTC, alvaroaleman commented
/retest
/test pull-kubermatic-e2e-packet-coreos-1.14

2019-07-22 07:51 UTC, alvaroaleman commented on api/pkg/clusterdeletion/deletion.go
> +	if err := d.cleanUpCredentialsSecrets(ctx, cluster); err != nil {
Lets do this in the very end, because after this we can not re-create the machine-controller deployment which we need to clean up the nodes which is currently done after cleaning up the `CredentialsSecret`

2019-07-22 07:51 UTC, alvaroaleman commented on api/pkg/clusterdeletion/deletion.go
> +		return fmt.Errorf("failed to get Secret %s/%s: %v", resources.KubermaticNamespace, secretName, err)
I wont suggest this very often, but maybe just nest it? As in:

```
if err != nil {
    if kerrors.IsNotfound(err) {
        return nil
    }
return fmt.Errorf(...)
```

2019-07-22 07:51 UTC, alvaroaleman commented on api/pkg/handler/v1/cluster/cluster.go
> +		partialCluster.Name = rand.String(10)
We don't need this anymore now that the cleanup is done via fa finalizer, right?

We can just create the secret using `generateName` and then use the name we got back. Only drawback is that if we fail creating the cluster, the secret will be kept dangling :grimacing:

2019-07-22 07:51 UTC, alvaroaleman commented on api/pkg/provider/kubernetes/cluster.go
> +	if cluster.Name != "" {
THis isnt needed, is it?

2019-07-22 07:51 UTC, alvaroaleman commented on api/pkg/provider/kubernetes/credentials.go
> +	secretLister kubev1.SecretLister
Can we not use any kind of listers but just the `ctrlruntime` client? Or do we have the problem that we can not get an impersonated version of it?

2019-07-22 09:07 UTC, nikhita commented on api/pkg/clusterdeletion/deletion.go
> +	if err := d.cleanUpCredentialsSecrets(ctx, cluster); err != nil {
Done.

2019-07-22 09:07 UTC, nikhita commented on api/pkg/clusterdeletion/deletion.go
> +		return fmt.Errorf("failed to get Secret %s/%s: %v", resources.KubermaticNamespace, secretName, err)
>     if kerrors.IsNotfound(err) {
>        return nil
>   }

In this case, we won't return nil but instead remove the finalizer in case it exists, right? :thinking:

2019-07-22 09:09 UTC, nikhita commented on api/pkg/handler/v1/cluster/cluster.go
> +		partialCluster.Name = rand.String(10)
> Only drawback is that if we fail creating the cluster, the secret will be kept dangling

If we generate the name here, we can still use the cluster name while creating the secret and then if we aren't able to create the cluster, we can delete the secret. This won't keep the secret dangling. :)

Are there drawbacks to this approach though? :thinking:

2019-07-22 09:09 UTC, nikhita commented on api/pkg/provider/kubernetes/credentials.go
> +	secretLister kubev1.SecretLister
> Or do we have the problem that we can not get an impersonated version of it?

This. :disappointed:

2019-07-22 09:10 UTC, nikhita commented on api/pkg/provider/kubernetes/cluster.go
> +	if cluster.Name != "" {
(wrote above https://github.com/kubermatic/kubermatic/pull/3684#discussion_r305743642)

2019-07-22 09:17 UTC, nikhita commented
/test pull-kubermatic-e2e-packet-coreos-1.14

2019-07-22 09:21 UTC, alvaroaleman commented on api/pkg/provider/kubernetes/credentials.go
> +	secretLister kubev1.SecretLister
And actually fixing the controller-runtime client is not really possible is it? Because the lister-backed version of the client would basically have to replicate the whole RBAC logic of the apiserver

2019-07-22 09:23 UTC, alvaroaleman commented on api/pkg/handler/v1/cluster/cluster.go
> +		partialCluster.Name = rand.String(10)
Well its obviously not transaction safe. I think we will have to write a simplistic controller that cleans up dangling secrets anyways (The delete-secret-after-cluster-creation-failed could fail). And at the point where we have to do that anyways, we can just use generateName and don't risk getting a 409 back on one of the creations. Or am I missing something?

2019-07-22 09:24 UTC, alvaroaleman commented on api/pkg/clusterdeletion/deletion.go
> +		return fmt.Errorf("failed to get Secret %s/%s: %v", resources.KubermaticNamespace, secretName, err)
Oh yeah indeed, good point

2019-07-22 09:24 UTC, alvaroaleman commented on api/pkg/clusterdeletion/deletion.go
> +		return fmt.Errorf("failed to get Secret %s/%s: %v", resources.KubermaticNamespace, secretName, err)
(We shouldn't go into the whole cleanup logic for the secret at all if the finalizer doesn't exist, so at this point we can safely assume that it does exist)

2019-07-22 09:29 UTC, alvaroaleman commented on api/pkg/provider/kubernetes/credentials.go
> +	secretLister kubev1.SecretLister
But wait, the lister itself has the same problem, you can get any object off it, there is no impersonation, right? So using the lister here is basically the same as using a privileged controller-runtime client? Or is the problem that the API doesn't use controller-runtime yet?

2019-07-22 09:38 UTC, nikhita commented
Addressed comments. The last run almost worked.

> failed to create machine at cloudprover, due to failed to create server, due to POST `https://api.packet.net/projects/<redacted-project-id-here>/devices: 503` The facility ams1 has no provisionable t1.small.x86 servers matching your criteria

This is a new error :/

2019-07-22 09:39 UTC, nikhita commented on api/pkg/provider/kubernetes/credentials.go
> +	secretLister kubev1.SecretLister
> And actually fixing the controller-runtime client is not really possible is it?

Hmm, iiuc this will need a field for the impersonated version in the `Client` itself, right? In that case, I'm not sure how we can do it...

2019-07-22 10:11 UTC, nikhita commented
/test pull-kubermatic-e2e-packet-coreos-1.14

The secret postsubmit ran successfully

2019-07-22 10:31 UTC, nikhita commented on api/pkg/handler/v1/cluster/cluster.go
> +		partialCluster.Name = rand.String(10)
So I had to revert some changes here, PTAL.

Removed the deletion logic from here, but kept name generation here because we need to pass the partial cluster object to the credentials provider so that it can remove the secret values from there. and then we use the partial cluster to actually create the cluster object. 

Or else the fields on the cluster object would not be changed at all.

2019-07-22 10:35 UTC, nikhita commented
/test pull-kubermatic-e2e-packet-coreos-1.14

2019-07-22 10:54 UTC, nikhita commented
/test pull-kubermatic-e2e-packet-coreos-1.14

2019-07-22 11:38 UTC, nikhita commented
/test pull-kubermatic-e2e-packet-coreos-1.14

2019-07-22 12:16 UTC, nikhita commented
It's green! PTAL. :)

2019-07-22 12:42 UTC, alvaroaleman reviewed
Some more nits. Migration will be a follow-up?

2019-07-22 12:42 UTC, alvaroaleman commented on api/pkg/handler/v1/cluster/cluster.go
> +func ShouldAddSecretsCleanupFinalizer(cluster *kubermaticv1.Cluster) bool {
Please just dont do this check and add the finalizer unconditionally, this simplifies the code. The cleanup already is a no-op if the provider is not packet.

2019-07-22 12:42 UTC, alvaroaleman commented on api/cmd/projects-migrator/credentials.go
> +	referenceNotDefined := packetSpec.APIKeyReference == nil && packetSpec.ProjectIDReference == nil
please rename to `referenceDefined` and change code accordingly, the cognitive overhead of having to remember that a var describes an unmet condition is a lot higher then the one of negating a variable in an if statement

2019-07-22 12:42 UTC, alvaroaleman commented on api/pkg/clusterdeletion/deletion.go
> +		if kerrors.IsNotFound(err) {
We need to remove the finalizer here

2019-07-22 12:42 UTC, alvaroaleman commented on api/pkg/provider/kubernetes/cluster.go
> +	if cluster.Name != "" {
name is already set below in line 109, there is no need for the `if name not empty then set it` you added

2019-07-22 12:42 UTC, alvaroaleman commented on api/pkg/provider/kubernetes/credentials.go
> +func NewCredentialsProvider(kubernetesImpersonationClient kubernetesImpersonationClient, secretLister kubev1.SecretLister) (*CredentialsProvider, error) {
I don't understand why this doens't just get a `kubernetes.Interface` instead of the `kubernetesImpersonationClient`?

2019-07-22 12:42 UTC, alvaroaleman commented on api/pkg/provider/kubernetes/credentials.go
> +	SecretLister               kubev1.SecretLister
Is there a reason to export the lister and the client?

2019-07-22 12:42 UTC, alvaroaleman commented on api/pkg/provider/kubernetes/credentials.go
> +	secret := &corev1.Secret{}
Can we just directly set all properties?

2019-07-22 12:42 UTC, alvaroaleman commented on api/pkg/provider/types.go
> +type CredentialsProvider interface {
Can we not define interfaces if we have exactly one implementation? This doesn't add any value in such a case

2019-07-22 12:42 UTC, alvaroaleman commented on api/pkg/resources/machinecontroller/credentials.go
> +	if spec.APIKey != "" {
Should probably a follow-up, but this should be part of `Data`. The cloud-controller needs the exact same code on providers that do have need resources to be created

2019-07-22 12:42 UTC, alvaroaleman commented on api/pkg/resources/machinecontroller/credentials.go
> +	if spec.APIKey != "" {
(The interface you built in itself is perfect btw, just defined in the wrong place IMO)

2019-07-22 14:05 UTC, nikhita commented on api/pkg/provider/kubernetes/credentials.go
> +func NewCredentialsProvider(kubernetesImpersonationClient kubernetesImpersonationClient, secretLister kubev1.SecretLister) (*CredentialsProvider, error) {
> I don't understand why this doens't just get a kubernetes.Interface instead of the kubernetesImpersonationClient?

We can do that as well, but most other providers need the `kubernetesImpersonationClient` directly so it becomes easy and consistent to pass the same thing to all providers.

2019-07-22 14:06 UTC, nikhita commented on api/pkg/provider/types.go
> +type CredentialsProvider interface {
> Can we not define interfaces if we have exactly one implementation?

There are some other providers with single-implementations... should I changed them in this PR too? I feel like this is consistent but agree that it doesn't add value...

2019-07-22 14:07 UTC, nikhita reviewed
Addressed most comments, and left replies/questions for others.

2019-07-22 14:07 UTC, nikhita commented on api/pkg/provider/helper.go
> +func ValidateSecretKeySelector(selector *providerconfig.GlobalSecretKeySelector, key string) error {
I don't actually like this here, but I wasn't sure where to place this because it was leading to an import cycle otherwise (after rebasing).

2019-07-22 14:15 UTC, alvaroaleman commented on api/pkg/provider/types.go
> +type CredentialsProvider interface {
No, lets just do that for the new `CredentialsProvider`

2019-07-22 14:21 UTC, alvaroaleman reviewed
Lets remove the CredentialsProvider interface and then merge this

2019-07-22 14:21 UTC, alvaroaleman commented on api/pkg/provider/helper.go
> +func ValidateSecretKeySelector(selector *providerconfig.GlobalSecretKeySelector, key string) error {
Can we place it into the `kuberneteshelper` package (`pkg/kubernetes`)? If not, lets just keep it here

2019-07-22 15:15 UTC, nikhita commented
updated.

2019-07-22 15:17 UTC, alvaroaleman commented
/test test pull-kubermatic-e2e-packet-coreos-1.14

Lets merge it if that passes :)

2019-07-22 16:43 UTC, alvaroaleman commented
/approve
/lgtm

2019-07-23 07:29 UTC, maciaszczykm commented
/approve

2019-07-23 07:35 UTC, alvaroaleman commented
/hold cancel

2019-07-23 08:40 UTC, nikhita commented
/retest

2019-07-23 08:44 UTC, nikhita commented
/retest

2019-07-23 09:23 UTC, nikhita commented
Cleaned up some clusters that didn't get deleted because they were created before the kubermatic-ci postsubmit ran...this should hopefully work

/retest

2019-07-23 09:52 UTC, merged