Updated README.md also remove duplicates in wercker.yml
kubermatic/kubermatic pull request #369
Opened 2017-07-26 14:02 UTC by andriisoldatenko

2017-07-29 11:29 UTC, scheeles approved these changes
LGTM

2017-07-29 11:31 UTC, mrIncompetent requested changes

2017-07-29 11:31 UTC, mrIncompetent commented on wercker.yml
> -          go get -u github.com/Masterminds/glide
Why was this removed?

2017-07-29 11:31 UTC, mrIncompetent commented on README.md
> +$ cd api
Lets avoid using `$` as prefix for bash commands

2017-07-29 11:31 UTC, mrIncompetent commented on README.md
> +$HOME/workspace
What are these lines (26-29) for?

2017-07-31 09:29 UTC, andriisoldatenko commented on wercker.yml
> -          go get -u github.com/Masterminds/glide
because you already have this line L25 (https://github.com/kubermatic/api/blob/develop/wercker.yml#L25)

2017-07-31 09:32 UTC, andriisoldatenko commented on README.md
> +$ cd api
@mrIncompetent should I remove all `$` in README.md related to bash commands?

2017-07-31 09:32 UTC, andriisoldatenko commented on README.md
> +$HOME/workspace
general note, I'll remove.

2017-07-31 09:38 UTC, andriisoldatenko commented
@mrIncompetent please review.

2017-08-01 08:04 UTC, mrIncompetent approved these changes

2017-08-01 08:06 UTC, merged