Add endpoint listing GCP machine and disk types
kubermatic/kubermatic pull request #3708
Opened 2019-07-01 11:11 UTC by maciaszczykm

**What this PR does / why we need it**: Adds an endpoint listing GCP machine sizes. Filters out ones with memory below 2 GBs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: Fixes #3659 

**Special notes for your reviewer**: Example output to `GET http://127.0.0.1:8080/api/v1/providers/gcp/machinetypes`:

```json
[
    {
        "name": "n1-highcpu-16",
        "description": "16 vCPUs, 14.4 GB RAM",
        "memory": 14746
    },
    {
        "name": "n1-highcpu-32",
        "description": "32 vCPUs, 28.8 GB RAM",
        "memory": 29491
    },
    {
        "name": "n1-highcpu-4",
        "description": "4 vCPUs, 3.6 GB RAM",
        "memory": 3686
    },
    {
        "name": "n1-highcpu-64",
        "description": "64 vCPUs, 57.6 GB RAM",
        "memory": 58982
    },
    {
        "name": "n1-highcpu-8",
        "description": "8 vCPUs, 7.2 GB RAM",
        "memory": 7373
    },
    {
        "name": "n1-highcpu-96",
        "description": "96 vCPUs, 86 GB RAM",
        "memory": 88474
    },
    {
        "name": "n1-highmem-16",
        "description": "16 vCPUs, 104 GB RAM",
        "memory": 106496
    },
    {
        "name": "n1-highmem-2",
        "description": "2 vCPUs, 13 GB RAM",
        "memory": 13312
    },
    {
        "name": "n1-highmem-32",
        "description": "32 vCPUs, 208 GB RAM",
        "memory": 212992
    },
    {
        "name": "n1-highmem-4",
        "description": "4 vCPUs, 26 GB RAM",
        "memory": 26624
    },
    {
        "name": "n1-highmem-64",
        "description": "64 vCPUs, 416 GB RAM",
        "memory": 425984
    },
    {
        "name": "n1-highmem-8",
        "description": "8 vCPUs, 52 GB RAM",
        "memory": 53248
    },
    {
        "name": "n1-highmem-96",
        "description": "96 vCPUs, 624 GB RAM",
        "memory": 638976
    },
    {
        "name": "n1-standard-1",
        "description": "1 vCPU, 3.75 GB RAM",
        "memory": 3840
    },
    {
        "name": "n1-standard-16",
        "description": "16 vCPUs, 60 GB RAM",
        "memory": 61440
    },
    {
        "name": "n1-standard-2",
        "description": "2 vCPUs, 7.5 GB RAM",
        "memory": 7680
    },
    {
        "name": "n1-standard-32",
        "description": "32 vCPUs, 120 GB RAM",
        "memory": 122880
    },
    {
        "name": "n1-standard-4",
        "description": "4 vCPUs, 15 GB RAM",
        "memory": 15360
    },
    {
        "name": "n1-standard-64",
        "description": "64 vCPUs, 240 GB RAM",
        "memory": 245760
    },
    {
        "name": "n1-standard-8",
        "description": "8 vCPUs, 30 GB RAM",
        "memory": 30720
    },
    {
        "name": "n1-standard-96",
        "description": "96 vCPUs, 360 GB RAM",
        "memory": 368640
    }
]
```

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2019-07-01 11:27 UTC, maciaszczykm commented
/hold

I will also add fetch for disk types here.

2019-07-01 11:32 UTC, zreigz requested changes
rest looks good

2019-07-01 11:32 UTC, zreigz commented on api/pkg/api/v1/types.go
> +type GCPMachineType struct {
can you change it to GCPMachineSize like for other providers: https://github.com/kubermatic/kubermatic/blob/22b1789d4bd6d0c3129c5c6b8833d96c763e2e15/api/pkg/api/v1/types.go#L169

2019-07-01 11:32 UTC, zreigz commented on api/pkg/api/v1/types.go
> +	Description string `json:"description"`
can you replace description for 
`VCPUs        int      `json:"vcpus"`` 

to have only resources like for other providers

2019-07-01 11:32 UTC, zreigz commented on api/pkg/handler/routes_v1.go
> +func (r Routing) listGCPMachineTypes() http.Handler {
can you change for `listGCPSizes`

2019-07-01 11:32 UTC, zreigz commented on api/pkg/handler/routes_v1.go
> +		)(provider.GetGCPMachineTypesEndpoint(r.credentialManager)),
can you change for `GCPSizeEndpoint`

2019-07-01 11:42 UTC, maciaszczykm commented
Added endpoint for listing disk types.

Example output from `GET http://127.0.0.1:8080/api/v1/providers/gcp/disktypes`:

```json
[
    {
        "name": "pd-ssd",
        "description": "SSD Persistent Disk"
    },
    {
        "name": "pd-standard",
        "description": "Standard Persistent Disk"
    }
]
```

2019-07-01 11:49 UTC, maciaszczykm commented on api/pkg/api/v1/types.go
> +	Description string `json:"description"`
The description is `string` that can be useful for Dashboard. I will add the `vCPUs` raw data too.

2019-07-01 13:06 UTC, zreigz requested changes

2019-07-01 13:06 UTC, zreigz commented on api/pkg/api/v1/types.go
> +// GCPMachineTypeList represents an array of GCP machine types.
incorrect name

2019-07-01 13:06 UTC, zreigz commented on api/pkg/api/v1/types.go
> +// GCPMachineType represents a object of GCP machine type.
incorrect name

2019-07-01 13:06 UTC, zreigz commented on api/pkg/handler/routes_v1.go
> +//       200: GCPMachineTypeList
change type for `GCPMachineSize`

2019-07-01 13:06 UTC, zreigz commented on api/pkg/handler/routes_v1.go
> +		Path("/providers/gcp/machinetypes").
change path for `/providers/gcp/sizes`

2019-07-01 13:06 UTC, zreigz commented on api/pkg/handler/routes_v1.go
> +		Handler(r.listGCPMachineTypes())
change for `listGCPSizes`

2019-07-01 13:06 UTC, zreigz commented on api/pkg/handler/v1/provider/gcp.go
> +func DecodeGCPTypesReqReq(c context.Context, r *http.Request) (interface{}, error) {
`DecodeGCPTypesReqReq` to `DecodeGCPTypesReq`

2019-07-01 13:06 UTC, zreigz commented on api/pkg/handler/routes_v1.go
> +// swagger:route GET /api/v1/providers/gcp/machineTypes gcp listGCPMachineTypes
should be `/api/v1/providers/gcp/machinetypes` but please change for `/api/v1/providers/gcp/sizes`

2019-07-01 13:07 UTC, zreigz commented
the reason for the failures:
- rebuild swagger
- rebase code

Please add unit tests for those endpoints

2019-07-02 09:21 UTC, maciaszczykm commented
I have done some research on the tests. I have two options:

- We can export filtering based on memory (< 2 GB) or name (no `local-ssd`) to separate methods and test them as they will contain actual logic inside. There is no point in testing the connection. The valuable test would be the one testing our `/api/v1/providers/gcp/sizes` route, but I cannot find fake client for it (https://github.com/googleapis/google-api-go-client and https://cloud.google.com/compute/docs/api/libraries don't mention that).
- We can skip testing as most of the logic is connected to GCP API and establishing a connection with it. Testing private methods is not too good anyways.

2019-07-02 09:22 UTC, maciaszczykm commented
/hold cancel

@zreigz PTAL

2019-07-02 09:28 UTC, zreigz commented
@maciaszczykm let's skip tests right now

2019-07-02 09:32 UTC, maciaszczykm commented
@zreigz @nikhita PTAL then.

2019-07-02 09:55 UTC, zreigz requested changes
rest look good

2019-07-02 09:55 UTC, zreigz commented on api/pkg/handler/routes_v1.go
> +// swagger:route GET /api/v1/providers/gcp/diskTypes gcp listGCPDiskTypes
wrong path, should be `/api/v1/providers/gcp/disktypes`

2019-07-02 10:17 UTC, zreigz commented
/lgtm
/approve

2019-07-02 10:19 UTC, zreigz commented
@maciaszczykm thanks for this PR

2019-07-03 06:21 UTC, zreigz approved these changes

2019-07-03 06:52 UTC, merged

2019-07-17 09:20 UTC, kdomanski commented
/cherry-pick release/v2.11