Update README.md
kubermatic/kubermatic pull request #372
Opened 2017-08-01 14:46 UTC by guusvw

add flag `token-issuer` and `client-id` to `kubermatic-api`-start command

2017-08-01 19:34 UTC, scheeles requested changes

2017-08-01 19:34 UTC, scheeles commented on README.md
> +  --addon-resources=$GOPATH/src/github.com/kubermatic/api/addon-charts \
I don't think `--addon-resources` is required anymore

2017-08-02 06:10 UTC, guusvw commented on README.md
> +  --addon-resources=$GOPATH/src/github.com/kubermatic/api/addon-charts \
Correct, fixed it.
I will review the whole README when I'm in office.

2017-08-02 06:11 UTC, scheeles approved these changes

2017-08-02 07:18 UTC, mrIncompetent approved these changes

2017-08-02 08:49 UTC, merged