Added example of generating docs
kubermatic/kubermatic pull request #376
Opened 2017-08-07 08:15 UTC by andriisoldatenko

closes #366

2017-08-18 08:55 UTC, guusvw requested changes

2017-08-18 08:55 UTC, guusvw commented on api/Gopkg.toml
> +[[constraint]]
Why do you add this to the vendors?

2017-08-18 08:55 UTC, guusvw commented on api/Gopkg.toml
> +[[constraint]]
Why do you add this to the vendors?

2017-08-18 08:55 UTC, guusvw commented on api/hack/run-api.sh
> +  -versions=../config/kubermatic/static/master/versions.yaml \
Can you use an absolute path?

2017-08-18 08:55 UTC, guusvw commented on api/handler/handler.go
> +	f, e := ioutil.ReadFile("../api/handler/swagger/api/index.json")
An parameter for the path to the file would be nice.

2017-08-18 08:55 UTC, guusvw commented on api/handler/handler.go
> +	json.NewEncoder(res).Encode(f)
It's fine for me, but the `errcheck` don't like it, because you don't handle the error.

2017-08-18 08:55 UTC, guusvw commented on build_docs.sh
> +    -mainApiFile="/Users/andrii/workspace/src/github.com/kubermatic/api/cmd/kubermatic-api/main.go" \
Please use an enviroment variable like `$GOPATH`

2017-08-18 08:55 UTC, guusvw commented on docs/api-docs.md
> +-mainApiFile="/Users/andrii/workspace/src/github.com/kubermatic/api/cmd/kubermatic-api/main.go" \
Please use an enviroment variable like $GOPATH

2017-08-18 08:55 UTC, guusvw commented on api/cmd/kubermatic-api/main.go
> +// @Contact andrii.soldatenko@gmail.com
You can use `info@loodse.com` as contact mail

2017-08-18 08:55 UTC, guusvw commented on api/cmd/kubermatic-api/main.go
> +// @TermsOfServiceUrl https://github.com/kubermatic/api
You need to update the URL

2017-08-18 09:18 UTC, guusvw requested changes

2017-08-18 09:18 UTC, guusvw commented on api/handler/handler.go
> +	f, e := ioutil.ReadFile("../api/handler/swagger/api/index.json")
That's not the "idiomatic go" naming convention, I would prefer `err`

2017-08-18 09:18 UTC, guusvw commented on api/handler/handler.go
> +func APIDescriptionHandler(res http.ResponseWriter, _ *http.Request) {
That's not the "idiomatic go" naming convention, I would prefer `w`, like in the rest of the handler

2017-08-18 09:18 UTC, guusvw commented on api/handler/routing.go
> +		HandlerFunc(APIDescriptionHandler)
I'm not quite sure, but I think, we should'nt change the behaviour of the root handler.
@mrIncompetent do we use it for checks like an uptime check?

2017-08-18 09:27 UTC, mrIncompetent commented on api/handler/routing.go
> +		HandlerFunc(APIDescriptionHandler)
Yes, please do not override this

2017-08-18 09:31 UTC, andriisoldatenko commented on api/Gopkg.toml
> +[[constraint]]
@guusvw because this tool we use for generate `index.json`.

2017-08-18 09:32 UTC, andriisoldatenko commented on api/cmd/kubermatic-api/main.go
> +// @TermsOfServiceUrl https://github.com/kubermatic/api
@guusvw do we have Terms Of Service Url?

2017-08-18 09:34 UTC, andriisoldatenko commented on api/handler/routing.go
> +		HandlerFunc(APIDescriptionHandler)
what is the differences for `/healthz` or `/api/healthz`?
cc @mrIncompetent @scheeles @realfake

2017-08-18 09:58 UTC, guusvw commented on api/handler/routing.go
> +		HandlerFunc(APIDescriptionHandler)
```
--- FAIL: TestUpRoute (0.00s)
        routing_test.go:99: Expected route to return code 200, got 500
```

if you don't have the generated docu, this test fails

2017-08-18 10:02 UTC, andriisoldatenko commented on api/handler/routing.go
> +		HandlerFunc(APIDescriptionHandler)
okey, I'll fix.

2017-08-18 10:44 UTC, guusvw commented
Can not generate docu, get an error
```
~/g/s/g/k/k/api (feature/open-api-for-the-api-server ⚡↩☡-) ./hack/gen-api-docs.sh                                                                                                         12:43:00
2017/08/18 12:43:06 Start parsing
2017/08/18 12:43:08 Can not find definition of APIError model. Current package github.com/kubermatic/kubermatic/api/handler
```

2017-08-18 10:51 UTC, andriisoldatenko commented on api/handler/handler.go
> +	f, e := ioutil.ReadFile("../api/handler/swagger/api/index.json")
@guusvw fixed.

2017-08-18 13:09 UTC, andriisoldatenko commented
@guusvw try now to generate docs,
```
➜  api git:(feature/open-api-for-the-api-server) ✗ ./hack/gen-api-docs.sh
2017/08/18 15:08:36 Start parsing
2017/08/18 15:08:39 Finish parsing
2017/08/18 15:08:39 Wrote api/index.json
2017/08/18 15:08:39 Swagger UI files generated
```

2017-08-18 13:26 UTC, andriisoldatenko commented on api/Gopkg.toml
> +[[constraint]]
removed

2017-08-18 13:26 UTC, andriisoldatenko commented on docs/api-docs.md
> +-mainApiFile="/Users/andrii/workspace/src/github.com/kubermatic/api/cmd/kubermatic-api/main.go" \
fixed

2017-08-18 13:35 UTC, andriisoldatenko commented on api/hack/run-api.sh
> +  -versions=../config/kubermatic/static/master/versions.yaml \
fixed

2017-08-18 14:23 UTC, guusvw requested changes

2017-08-18 14:23 UTC, guusvw commented on api/handler/handler.go
> +	_, err1 := w.Write(f)
`_, err = w.Write(f)` - works fine too ;)

2017-08-18 14:23 UTC, guusvw commented on api/cmd/kubermatic-api/main.go
> +// @TermsOfServiceUrl https://github.com/kubermatic/api
I don't think so. So, you can remove the TOS tag

2017-08-21 06:54 UTC, guusvw approved these changes

2017-08-21 07:49 UTC, mrIncompetent approved these changes

2017-08-21 07:57 UTC, merged