Feature/381 upgrade cluster
kubermatic/kubermatic pull request #382
Opened 2017-08-09 10:48 UTC by guusvw

Close #381

2017-08-15 15:08 UTC, mrIncompetent requested changes

2017-08-15 15:08 UTC, mrIncompetent commented on api/cmd/kubermatic-api/main.go
> +	updatesFile      = flag.String("updates", "updates.yaml", "The updates.yaml file path")
Deployment file also needs to be updated!

2017-08-15 15:08 UTC, mrIncompetent commented on api/handler/upgrade.go
> +		c.Status.Phase = api.UpdatingMasterClusterStatusPhase
After setting the phase, you also need to persist. 
Also: This should probably be moved into the kubernetes provider

2017-08-17 10:09 UTC, guusvw commented on api/cmd/kubermatic-api/main.go
> +	updatesFile      = flag.String("updates", "updates.yaml", "The updates.yaml file path")
Done in https://github.com/kubermatic/kubermatic/pull/382/commits/2148d257d2233ba458a47bab3cb15862219750a2

2017-08-17 10:11 UTC, guusvw commented on api/provider/kubernetes/kubernetes.go
> +func (p *kubernetesProvider) UpgradeCluster(user provider.User, cluster, version string) error {
@mrIncompetent is this the way to go?

2017-08-17 10:13 UTC, guusvw commented on api/handler/upgrade.go
> +		c.Status.Phase = api.UpdatingMasterClusterStatusPhase
Moved: https://github.com/kubermatic/kubermatic/pull/382/commits/9f9eb31e3d65d6f6f5315a4b7acf43850dfe3652#diff-1701e2bab95c63ac3a77bc5844994042L108

https://github.com/kubermatic/kubermatic/pull/382/commits/9f9eb31e3d65d6f6f5315a4b7acf43850dfe3652#diff-db54f997140cb0ce93fd32e0dbf6826cR397

2017-08-17 12:37 UTC, mrIncompetent requested changes

2017-08-17 12:37 UTC, mrIncompetent commented on api/cmd/kubermatic-api/main.go
> +	}
We should not continue if the versions-file or updates-file is not defined

2017-08-17 12:37 UTC, mrIncompetent commented on api/cmd/kubermatic-api/main.go
> +		versions, err = version.LoadVersions(*updatesFile)
updatesFile & versionsFile?
Why checking versionsFile to load updatesFile?

2017-08-17 12:37 UTC, mrIncompetent commented on api/cmd/kubermatic-cluster-controller/main.go
> +		versions, err = version.LoadVersions(*updatesFile)
updatesFile & versionsFile?
Why checking versionsFile to load updatesFile?

2017-08-17 12:37 UTC, mrIncompetent commented on api/cmd/kubermatic-cluster-controller/main.go
>  	}
We should not continue if the versions-file or updates-file is not defined

2017-08-17 12:37 UTC, mrIncompetent commented on api/handler/upgrade.go
> +		possibleUpdates := make(version.Collection, 0)
I think we should use the updates.yaml so we only show possible

2017-08-17 12:37 UTC, mrIncompetent commented on api/provider/kubernetes/kubernetes.go
> +func (p *kubernetesProvider) UpgradeCluster(user provider.User, cluster, version string) error {
Yes!

2017-08-17 14:46 UTC, mrIncompetent approved these changes

2017-08-17 14:52 UTC, merged