Migrate code to use CRD data structures for DCs
kubermatic/kubermatic pull request #3824
Opened 2019-07-15 15:41 UTC by alvaroaleman

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Moves towards fixing #3740

**Special notes for your reviewer**:

Moves our code over to use the new types for datacenters and explicitly distringuish between seeds and Datacenters
**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

2019-07-17 07:14 UTC, alvaroaleman commented
@zreigz @mrIncompetent Modulo unittests for the new code in `pkg/provider/conversions.go` this is done, can you have a look if this looks fine approachwise?

Semantically, this introduces two changes:
* It is not possible anymore to define one datacenter as both seedDC and nodeDC. This was done in one unittests, I hope no customers has this. IMHO this is not a valid usecase anyways, as those two are different things
* `ListDatacenters` doesn't filter out duplicate DCs. The only guarantee the api can give is that there will not be more than one seedDC with a given name and not more than one nodeDC per seed dc with a given name.

In practise multiple dcs with the same name can not get into the system currently, because we read everything from a file that is a flat map. Once we move to CRDs, this could happen. IMHO we should have validation that disallows setting up such a config.

2019-07-17 07:34 UTC, zreigz commented
I will take a look and test it today

2019-07-17 11:16 UTC, zreigz commented
Works and looks perfectly fine. I appreciate your huge effort :+1: 
Is it still WIP or can I approve it?

2019-07-17 12:36 UTC, alvaroaleman commented
> Is it still WIP or can I approve it?

Unittests are missing, I will ping you once they are done

2019-07-17 13:25 UTC, alvaroaleman commented
@zreigz Added unittests, PR is now done from my POV

2019-07-17 13:34 UTC, mrIncompetent commented on api/cmd/master-controller-manager/main.go
> +	ctrlCtx.datacenters, err = provider.LoadDatacenters(ctrlCtx.runOptions.dcFile)
If we load the DC's during startup we won't be able to manage the datacenters during runtime - which is one of the goals of this whole migration.

2019-07-17 13:37 UTC, alvaroaleman commented on api/cmd/master-controller-manager/main.go
> +	ctrlCtx.datacenters, err = provider.LoadDatacenters(ctrlCtx.runOptions.dcFile)
Yes, this will be changed in a follow-up. This PR already changes 2.2k LOC, I didn't want to make it even bigger

2019-07-17 13:50 UTC, mrIncompetent commented on api/cmd/master-controller-manager/main.go
> +		sugarLog.Fatalw("Failed toparse the datacenters definition", "error", err)
typo

2019-07-17 14:11 UTC, alvaroaleman commented
@mrIncompetent Typo fixed, PTAL

2019-07-17 14:42 UTC, alvaroaleman commented
/retest

2019-07-17 15:02 UTC, alvaroaleman commented
/retest

2019-07-17 15:50 UTC, xrstf commented
/approve

2019-07-17 18:14 UTC, zreigz commented
/lgtm
/approve

2019-07-18 07:42 UTC, zreigz commented
/lgtm
/approve

2019-07-18 08:20 UTC, mrIncompetent requested changes

2019-07-18 08:20 UTC, mrIncompetent commented on api/pkg/provider/conversions.go
> +	if n := len(results); n != 1 {
```go
if len(results) != 1 {
```

2019-07-18 08:20 UTC, mrIncompetent commented on api/cmd/conformance-tests/runner.go
> +	nodeDC, err := provider.NodeLocationFromSeedMap(r.dcs, cluster.Spec.Cloud.DatacenterName)
Why does the function name mention `NodeLocation` but the variable is called `nodeDC` ?
We  should have a consistent name

2019-07-18 08:20 UTC, mrIncompetent commented on api/cmd/kubermatic-cli/README.md
> -# Automate creation of kubermatic managed clusters
This was developed upon customer request & the intention of this PR has nothing todo with this cmd.
Revert please

2019-07-18 08:21 UTC, mrIncompetent commented
IMO
From a code quality standpoint this PR is a step backwards.
It mainly comes from the data model we use(Embedding the `NodeLocations` in the `SeedDatacenter`).
We now require every developer to know to only get the `NodeLocation` using `NodeLocationFromSeedMap`.
On top we now require components to know about `SeedDatacenters`, while the only data they need is the `NodeLocations`([LoD](https://en.wikipedia.org/wiki/Law_of_Demeter) is a good read here).

This is not meant to block this PR as this is just my personal opinion on the code quality & not the functionality itself.

2019-07-18 08:24 UTC, alvaroaleman commented on api/cmd/kubermatic-cli/README.md
> -# Automate creation of kubermatic managed clusters
This is unused and doesn't use our API. It will get replaced with a CLI that actually use our API.

I am not going to fix up something we don't use and shouldn't have developed in the first place.

2019-07-18 08:28 UTC, mrIncompetent commented on api/cmd/kubermatic-cli/README.md
> -# Automate creation of kubermatic managed clusters
This code got used by customers. If you want to delete it, make sure they don't use it anymore.
@kron4eg Can you check if this still gets used?

2019-07-18 08:28 UTC, alvaroaleman commented
>On top we now require components to know about SeedDatacenters, while the only data they need is the NodeLocations(LoD is a good read here).

Yup, this is mainly due to the fact how the code is currently structured. We instantiate the cloud providers once with all data they could ever need. When making the thing actually dynamic, I will change their instantiation to only happen when they are needed and to only get the data they need for that specific invocation.

WRT the controllers, I could change them to have a `map[ string]NodeLocation` instead of the one element `map[string]SeedDatacenter`?

2019-07-18 08:34 UTC, alvaroaleman commented on api/pkg/provider/conversions.go
> +	if n := len(results); n != 1 {
That variable is being used in the error, hence the assignment

2019-07-18 10:37 UTC, kron4eg commented on api/cmd/kubermatic-cli/README.md
> -# Automate creation of kubermatic managed clusters
Yeah, I think it can be removed. Actual usage never happened.

2019-07-18 12:53 UTC, mrIncompetent commented on api/cmd/conformance-tests/main.go
> +	seedName := os.Getenv("SEED_NAME")
If there is a reason why we use an environment variable instead of a flag, a comment should explain it :)

2019-07-18 12:53 UTC, mrIncompetent commented on api/cmd/conformance-tests/runner.go
> +		return nil, fmt.Errorf("NodeLocation %q doesn't exist", cluster.Spec.Cloud.DatacenterName)
`NodeLocation` -> `Datacenter`

2019-07-18 13:26 UTC, mrIncompetent commented
/lgtm
/approve

2019-07-18 13:27 UTC, mrIncompetent approved these changes

2019-07-18 14:07 UTC, merged