[WIP] Kubermatic Operator
kubermatic/kubermatic pull request #3850
Opened 2019-07-19 09:00 UTC by xrstf

**What this PR does / why we need it**:
This implements the first parts of the new Kubermatic Operator, as per proposal (#3767).

**Does this PR introduce a user-facing change?**:
```release-note
created Kubermatic Operator to manage deploying/maintaining Kubermatic
```

2019-07-22 12:22 UTC, alvaroaleman commented on api/cmd/kubermatic-operator/controllers.go
> +type runnerFn func(workerCount int, stopCh <-chan struct{}) error
Generally I am not sure if it makes sense to have something like the `controllerCreator`, because different controllers need diffent info in their initialization. But _if_ we decide to have such a thing, its should contain _all_ info, i.E. include the `workerCount`. That in turn would make the  `runerFN` type obsolete, as you can just use `manager.Runnable` instead (which is implemented by sigs.k8s.io/pkg/controller.Controller`

2019-07-22 12:22 UTC, alvaroaleman commented on api/cmd/kubermatic-operator/controllers.go
> +var allControllers = map[string]controllerCreator{
I should take Henriks role over and mention that this is premature optimization, we only have one controller and shouldn't build infra for a problem we don't have :)

2019-07-22 12:22 UTC, alvaroaleman commented on api/cmd/kubermatic-operator/controllers.go
> +func runAllControllersAndCtrlManager(workerCnt int,
This doesn't make sense. The `manager` starts the controllers (or more specifically all `Runnables` that were passed into it via its `Add`. The reason we have something like this func here in Kubermatic is:
* Legacy cruft
* We cant use the `managers` leader election because we have to execute some migrations after aquiring the leader lease and before running the controllers

Generally speaking, everything that is long-running should implement the `Runnable` interface, be added to the manager and be started and managed by the `Manager`. Thankfully, `Mangager` itself also implements `Runnable` :)

2019-07-22 12:22 UTC, alvaroaleman commented on api/cmd/kubermatic-operator/main.go
> +	kubeMasterClient                kubernetes.Interface
We don't need any of these. Just create a `manager` per seed and use its `GetClient` to get a lister-backed client. There is no reason at all to use the generated clientset or manage informers and listers ourselfes.

It also makes writing tests a lot easier, because you only need to replace one  `client`, instead of multiple clients that are used for different types and informers for them

2019-07-22 12:22 UTC, alvaroaleman commented on api/cmd/kubermatic-operator/main.go
> +	// This group is forever waiting in a goroutine for signals to stop
No need for waitgroup, the managers `Start` is blocking until the channel is closed

2019-07-22 12:22 UTC, alvaroaleman commented on api/pkg/controller/operator-master/reconciler.go
> +/*
Why is all of this commented?

2019-07-22 12:55 UTC, xrstf commented on api/pkg/controller/operator-master/reconciler.go
> +/*
Because the first commit was a braindump to ask Henrik a question.

2019-07-22 21:03 UTC, xrstf commented
I've now implemented the first reconciling parts. The deployment is not yet idempotent and causes and infinite reconcile loop, but the other parts seem to work fine already.

2019-07-22 21:04 UTC, xrstf commented on api/pkg/controller/operator-master/controller.go
> +var namespaceNameRegex = regexp.MustCompile(`^\s*([^/]+)\s*/\s*([^/]+)\s*$`)
Is there a ready-made package for this? I wanted to put the owning configuration name into a single annotation, but can just as well split it into two annotations or labels.

2019-07-22 21:06 UTC, xrstf commented on api/pkg/controller/operator-master/resources.go
> +				// fmt.Sprintf("-feature-gates=%s", cfg.Spec.FeatureGates),
This makes my original attempt to have fixed, static fields for each feature flag inside the CRD, harder to implement. Maybe we should go back to just having a `map[string]=bool` for the feature gates in the CRD?

2019-07-22 21:08 UTC, xrstf commented on api/pkg/controller/operator-master/reconciler.go
> +type configReconciler struct {
I got tired of handing the context, namespace and config object into each reconcile function, so I wrapped the context into this struct. `ns` is a field because I did not want to spread the "what is the effective namespace to work in?" logic into each named creator / reconciler function.

2019-07-23 14:50 UTC, mrIncompetent commented on api/cmd/kubermatic-operator/main.go
> +		sugarLog.Fatalw("Failed to create client", "error", err)
Can we rename `sugarLog` to `log` ?

2019-07-23 14:52 UTC, mrIncompetent commented on api/cmd/kubermatic-operator/main.go
> +		sugarLog.Fatalw("failed to register types in Scheme", "error", err)
`failed` -> `Failed`

2019-07-23 14:52 UTC, xrstf commented on api/cmd/kubermatic-operator/main.go
> +		sugarLog.Fatalw("Failed to create client", "error", err)
We can and did.

2019-07-23 14:52 UTC, mrIncompetent commented on api/cmd/kubermatic-operator/main.go
> +		sugarLog.Fatalw("failed to create Controller Manager instance: %v", err)
`failed` -> `Failed`

2019-07-23 16:24 UTC, mrIncompetent requested changes

2019-07-23 16:24 UTC, mrIncompetent commented on api/pkg/controller/operator-master/controller.go
> +		log:          log,
`log: log.Named(ControllerName)`

2019-07-23 16:24 UTC, mrIncompetent commented on api/pkg/controller/operator-master/controller.go
> +func eventHandler(a handler.MapObject) []reconcile.Request {
**Personal opinion**
I have to admit i'm not a huge fan of this handler as it has an entirely different logic based on the type.

It makes code less clear. I was a bit confused when i saw that the `KubermaticConfiguration` gets treated the same way as all other resources: https://github.com/kubermatic/kubermatic/pull/3850/files#diff-96bb0d5e8a5e69728cc12a27cd04c084R85

2019-07-23 16:24 UTC, mrIncompetent commented on api/pkg/controller/operator-master/controller.go
> +var namespaceNameRegex = regexp.MustCompile(`^\s*([^/]+)\s*/\s*([^/]+)\s*$`)
https://github.com/kubernetes/client-go/blob/master/tools/cache/store.go#L95

2019-07-23 16:24 UTC, mrIncompetent commented on api/pkg/controller/operator-master/controller.go
> +	return fmt.Sprintf("%s/%s", namespace, name)
```go
name := NamespacedName{Name: "foo", Namespace: "bar"}
return name.String()
```

2019-07-23 16:24 UTC, mrIncompetent commented on api/pkg/crd/operator/v1alpha1/configuration.go
> +	ExposeStrategy string `json:"exposeStrategy,omitempty"`
Please define a custom type for `ExposeStrategy` + constants for the available strategies

2019-07-23 16:24 UTC, mrIncompetent commented on api/pkg/resources/kubermatic/api.go
> +package kubermatic
Move all resource packages belonging to the operator below the individual controller package.
Like: `/pkg/controller/operator-master/resources `

2019-07-23 16:24 UTC, mrIncompetent commented on api/pkg/resources/kubermatic/api.go
> +					TerminationMessagePath:   "/dev/termination-log",
https://github.com/kubermatic/kubermatic/blob/master/api/pkg/controller/container-linux/resources/deployment.go#L67

2019-07-23 16:24 UTC, mrIncompetent commented on api/pkg/resources/kubermatic/master-controller-manager.go
> +func MasterControllerManagerServiceCreator(ns string, cfg *operatorv1alpha1.KubermaticConfiguration) reconciling.NamedServiceCreatorGetter {
Please remove that.
We don't need a service for the master controller manager.

2019-07-23 16:24 UTC, mrIncompetent commented on api/pkg/resources/kubermatic/seed-controller-manager.go
> +func SeedControllerManagerServiceCreator(ns string, cfg *operatorv1alpha1.KubermaticConfiguration) reconciling.NamedServiceCreatorGetter {
We don't need this service

2019-07-23 16:24 UTC, mrIncompetent commented on api/pkg/resources/kubermatic/ui.go
> +			s.Spec.Type = corev1.ServiceTypeNodePort
ClusterIP

2019-07-23 16:24 UTC, mrIncompetent commented on api/pkg/resources/kubermatic/master-controller-manager.go
> +					TerminationMessagePath:   "/dev/termination-log",
https://github.com/kubermatic/kubermatic/blob/master/api/pkg/controller/container-linux/resources/deployment.go#L67

2019-07-23 16:24 UTC, mrIncompetent commented on api/pkg/resources/kubermatic/master-controller-manager.go
> +	return corev1.Container{
Is missing default values like `TerminationMessagePolicy` & `TerminationMessagePath`

2019-07-23 16:24 UTC, mrIncompetent commented on api/pkg/resources/kubermatic/seed-controller-manager.go
> +					TerminationMessagePath:   "/dev/termination-log",
https://github.com/kubermatic/kubermatic/blob/master/api/pkg/controller/container-linux/resources/deployment.go#L67

2019-07-23 16:24 UTC, mrIncompetent commented on api/pkg/resources/kubermatic/seed-controller-manager.go
> +	return corev1.Container{
Is missing default values like TerminationMessagePolicy & TerminationMessagePath

2019-07-23 16:24 UTC, mrIncompetent commented on api/pkg/resources/kubermatic/ui.go
> +					TerminationMessagePath:   "/dev/termination-log",
Is missing default values like TerminationMessagePolicy & TerminationMessagePath

2019-07-23 16:24 UTC, mrIncompetent commented on api/pkg/resources/kubermatic/seed-controller-manager.go
> +			s.Spec.Ports = mergeServicePort(s.Spec.Ports, corev1.ServicePort{
Why do we want to merge here anything?
Why not forcefully overwriting?

2019-07-23 17:55 UTC, alvaroaleman commented on api/pkg/resources/kubermatic/master-controller-manager.go
> +	return corev1.Container{
Not needed anymore, those are added when the deployment gets reconciled: https://github.com/kubermatic/kubermatic/blob/d80d2a87916c8e72dae799884bae3d45cf34be15/api/pkg/resources/reconciling/zz_generated_reconcile.go#L214

2019-07-23 18:03 UTC, alvaroaleman commented on api/pkg/resources/kubermatic/master-controller-manager.go
> +	return corev1.Container{
(which means its not needed anywhere so it can be removed again :grimacing: )

2019-07-23 18:30 UTC, alvaroaleman commented on api/pkg/controller/operator-master/reconciler.go
> +type configReconciler struct {
Can we rename it to `configData` or something? This thing doesn't reconcile anything, its being used during reconciliation, which is a completely different thing. Also:
* The context is already part of the reconciler, why put it into a second struct?
* Why dont we take the namespace from the `KubermaticConfiguration`?

2019-07-23 18:30 UTC, alvaroaleman commented on api/pkg/crd/client/clientset/versioned/clientset.go
> +	operatorv1alpha1 "github.com/kubermatic/kubermatic/api/pkg/crd/client/clientset/versioned/typed/operator/v1alpha1"
Can we not generate the clientset? Else ppl will end up using it, we don't want that.

2019-07-23 18:30 UTC, alvaroaleman commented on api/pkg/resources/kubermatic/api.go
> +			d.Spec.Replicas = i32ptr(2)
Please use the funcs in the `utilpointer "k8s.io/utils/pointer"` package for this

2019-07-23 18:30 UTC, alvaroaleman commented on api/pkg/resources/kubermatic/api.go
> +			d.Spec.Template.Labels = specLabels
If you initialize it like that, you can just set `d.Spec.Template.Labels = d.Spec.Selector.MatchLabes`. And at that point there is no reason to have the `specLabels` func anymore.

Also I should mention that I dislike funcs that have exactly one caller, unless there is a good reason, e.G. you want to test that specific codepath. It makes the whole thing hard to read, instead of going sequentally with the code, you have to jump to another location.

2019-07-23 18:30 UTC, alvaroaleman commented on api/pkg/resources/kubermatic/api.go
> +							DefaultMode: i32ptr(420),
Utilpointer

2019-07-23 18:30 UTC, alvaroaleman commented on api/pkg/resources/kubermatic/kubermatic.go
> +			for name, content := range cfg.Spec.MasterFiles {
Makes me think if we should build a secretCreatorFactory that takes just name and and map[string][]byte and returns a creator lol

2019-07-23 18:30 UTC, alvaroaleman commented on api/pkg/resources/kubermatic/master-controller-manager.go
> +			volumes := []corev1.Volume{
Why not directly use `d.Volumes`? Same for args and everything else

2019-07-23 18:30 UTC, alvaroaleman commented on api/pkg/resources/kubermatic/util.go
> +	// nameLabel is the recommended name for an identifying label.
"Recommended"? Either we use them in which case they are part of the desired state or we dont, in which we dont care

2019-07-24 07:52 UTC, xrstf commented on api/pkg/controller/operator-master/resources.go
> +				// fmt.Sprintf("-feature-gates=%s", cfg.Spec.FeatureGates),
I have since writing this comment in fact replaced the FeatureGates with a simple map.

2019-07-24 07:54 UTC, xrstf commented on api/pkg/controller/operator-master/reconciler.go
> +type configReconciler struct {
> Why dont we take the namespace from the KubermaticConfiguration?

We do?

```
func (r *configReconciler) Reconcile() error {
	r.applyDefaults() // sets the spec.Namespace to the object's actual namespace if none was given explicitly
	r.ns = r.config.Spec.Namespace
```

> The context is already part of the reconciler, why put it into a second struct?

Which context do you mean? The `ctx` context?

2019-07-24 07:58 UTC, alvaroaleman commented on api/pkg/controller/operator-master/reconciler.go
> +type configReconciler struct {
Lets please not do that. PPL that want the namespace should just access the `kubermaticConfiguration` object. There is no added value to move it to a different variable but it leads to confusion as to why there are two places where the NS is and how they are different.

Also it introduces the possibility of bugs, because some place in the code modifies the kubermaticConfiguration but not the `configReconciler` or the other way round. We should always have exactly one canonical source of truth which is the object itself.

2019-07-24 07:59 UTC, alvaroaleman commented on api/pkg/controller/operator-master/reconciler.go
> +type configReconciler struct {
Yeah, by context I mean `ctx`. And I must admit I don't see the added value of the `configReconciler` concept.

2019-07-24 08:03 UTC, mrIncompetent commented on api/pkg/resources/kubermatic/master-controller-manager.go
> +	return corev1.Container{
Nice! Then we should issue a PR to remove them everywhere!

2019-07-24 08:17 UTC, alvaroaleman commented on api/pkg/controller/operator-master/controller.go
> +func eventHandler(a handler.MapObject) []reconcile.Request {
Yeah I definitely agree, it also makes the relationship quite clear in the beginning, there is one `controllingObject` that uses `handler.EnqueueRequestForName` and a set of `controlled objects` that get a `enqOwnerViaCustomHandlingFunc`

2019-07-24 08:17 UTC, xrstf commented on api/pkg/controller/operator-master/controller.go
> +func eventHandler(a handler.MapObject) []reconcile.Request {
IMHO splitting the event handler into two will only create more code (two event handler functions, two .Watch() calls, two error handlings, two NamedspacedName struct creations, ...) with little to gain.

2019-07-24 08:19 UTC, alvaroaleman commented on api/pkg/controller/operator-master/controller.go
> +		if _, ok := obj.(*operatorv1alpha1.KubermaticConfiguration); ok {
Can we simplify this by just doing a check in the beginning of the `Reconcile`? As you probably noticed, we can not really use the predicate concept as it checks the object itself, not the owner. But IMHO having a three line `if workerNameLabel != workerName { return nil }` is much simpler than this 12 line func that does type assertion

2019-07-24 08:22 UTC, alvaroaleman commented on api/pkg/controller/operator-master/controller.go
> +		if _, ok := obj.(*operatorv1alpha1.KubermaticConfiguration); ok {
s/12 line func/one type and two funcs that occupy a total of 40 LOC/

2019-07-24 10:13 UTC, xrstf commented on api/pkg/controller/operator-master/reconciler.go
> +type configReconciler struct {
> Also it introduces the possibility of bugs, because some place in the code modifies the kubermaticConfiguration but not the configReconciler or the other way round. We should always have exactly one canonical source of truth which is the object itself.

Agreed. Also, since the namespace does not need to be set in each creator function, this already reduces the repetitive access to the field in the spec anyway.

> Yeah, by context I mean ctx. And I must admit I don't see the added value of the configReconciler concept.

In the `Reconcile()` function we create three things: a context for cancellation, the kubermatic config and a logger with additional metadata for the kubermatic config. These three things would then need to be passed into all `reconcile<Object>` functions. This made my spider sense tingle because obviously these three fields are a common context for all the reconcile functions (in addition to the existing shared state in the `Reconciler` struct itself). I would have liked to spawn a new Reconciler for each incoming reconcile request, but it seemed the architecture of our code is built around the concept of a single reconciler. So I did the next best thing and created a new helper that wraps the original Reconciler and adds the new context. I don't neccessarily like its name either, but I liked the concept of having an obvious shared state for all reconcile functions.

2019-07-24 10:28 UTC, xrstf commented on api/pkg/resources/kubermatic/api.go
> +			d.Spec.Template.Labels = specLabels
> Also I should mention that I dislike funcs that have exactly one caller

The `apiPodLabels()` function is used for defining the PDB and Services as well.

2019-07-24 10:47 UTC, xrstf commented on api/pkg/resources/kubermatic/master-controller-manager.go
> +			volumes := []corev1.Volume{
I found shorter variables names increase readability and separating assembling these values from finally assembling the Deployment also helps my understand. It felt wrong to me to create a Deployment object and then start poking around and adding values here and there.

2019-07-24 10:51 UTC, xrstf commented on api/pkg/resources/kubermatic/seed-controller-manager.go
> +			s.Spec.Ports = mergeServicePort(s.Spec.Ports, corev1.ServicePort{
When I forcefully set the values (`s.Spec.Ports = []....`), I ended up in an endless reconcile loop because the `nodePort` was added. That made me be cautious. The other approaches I found (manually doing `s.Spec.Ports[i].Name= ...`) looks brittle (if someone overwrote a port with theirs, they would lose their port after reconciling -- my code would *add* our port back).

2019-07-24 10:52 UTC, xrstf commented on api/pkg/resources/kubermatic/ui.go
> +			s.Spec.Type = corev1.ServiceTypeNodePort
The UI service in our Helm chart says NodePort: https://github.com/kubermatic/kubermatic/blob/master/config/kubermatic/templates/kubermatic-ui-service.yaml

2019-07-24 10:54 UTC, xrstf commented on api/pkg/resources/kubermatic/util.go
> +	// nameLabel is the recommended name for an identifying label.
It's badly worded, I admit. I meant it's recommended by the Kubernetes docs to be used as a label. The comment was supposed to express that this is the label we use for naming because it is recommended.

2019-07-24 10:56 UTC, xrstf commented on api/pkg/controller/operator-master/controller.go
> +	return fmt.Sprintf("%s/%s", namespace, name)
That would certainly currently do the same, but you have now mixed up our splitting implementation with Kubernetes' joining logic. If either changes, the split+join combo would be broken. That's why I opted (in the now irrelevant code) to have my own join function.

2019-07-24 10:58 UTC, xrstf commented on api/pkg/controller/operator-master/controller.go
> +		if _, ok := obj.(*operatorv1alpha1.KubermaticConfiguration); ok {
The whole event handling stuff has been reworked.

2019-07-24 11:11 UTC, alvaroaleman commented on api/pkg/controller/operator-master/reconciler.go
> +type configReconciler struct {
>  I don't neccessarily like its name either, but I liked the concept of having an obvious shared state for all reconcile functions.

Yeah we do that elsewhere with the `templateData` and `openshiftData`. Re the context, while we have some controllers that do create a context per reconciliation, I must admit that this is a pattern I introduced and which doesn't make any sense. The only case where this context should get canceled is for shutdowns of the whole controller.

2019-07-24 13:21 UTC, xrstf commented on api/pkg/crd/client/clientset/versioned/clientset.go
> +	operatorv1alpha1 "github.com/kubermatic/kubermatic/api/pkg/crd/client/clientset/versioned/typed/operator/v1alpha1"
I think I updated the codegen script accordingly now.

2019-07-24 14:40 UTC, alvaroaleman commented on api/pkg/resources/kubermatic/master-controller-manager.go
> +	return corev1.Container{
It already is used in most places. What should be considered thought is that his is applied on a higher level and currently only implemented for Deployments and Statefulsets, so we should probably add it for DaemonSets as well :grimacing:

2019-07-24 14:49 UTC, alvaroaleman commented on api/pkg/controller/operator-master/resources/kubermatic/util.go
> +func mergeServicePort(dst []corev1.ServicePort, src corev1.ServicePort) []corev1.ServicePort {
Please remove, if such a func exists, ppl will think they are supposed to use it. We have to cases where wo do trickery with ports, both of them are on a per-usercluster level and in the responsibility of the kubermatic-controller-manager.

This operator should just achieve a desired state and not merge desired state together with current state on the vague assumption that current state somehow is part of the desired state just because it exists.

2019-07-24 14:51 UTC, alvaroaleman commented on api/pkg/crd/operator/v1alpha1/configuration.go
> +	PullPolicy corev1.PullPolicy `json:"pullPolicy"`
Why does this type exist and why do we want to make the pullPolicy configurable?

2019-07-24 14:55 UTC, alvaroaleman commented on api/pkg/controller/operator-master/controller.go
> +	predicate = newPredicateFuncs(func(meta metav1.Object) bool {
Can you explain why you don't want at the start of the `Reconcile` a simple check if the worker-name matches and instead use two predicate funcs?

3 LOC vs 6 LOC, also the possibility to add a debug log indicating to someone reading the logs that a given cluster is being ignored because its worker-name label doesn't match.

2019-07-24 14:58 UTC, alvaroaleman commented on api/pkg/controller/operator-master/controller.go
> +	if err := c.Watch(&source.Kind{Type: t}, eventHandler, predicate); err != nil {
Thats obviously personal opinion, but assigning something to a variable that is complely not self-explanatory named makes the code for me pretty hard to read. Instead of just going doing and seeing `a source kind of type operatorv1alpha1.KubermaticConfiguration{` I see `a a source kind of type t is being watched, lets go one line back to see what type t is`

2019-07-24 14:59 UTC, alvaroaleman commented on api/pkg/controller/operator-master/controller.go
> +	eventHandler = newEventHandler(func(a handler.MapObject) []reconcile.Request {
Again personal opinion, but I dislike variables that have a generic name like `eventHandler` and get assigned a complete different value so depending on where I look at `eventHandler` it means complete different things.

something like `eventHandlerChildObject` and `eventHandlerMainObject` make the whole thing IMHO much more readable.

2019-07-24 15:01 UTC, alvaroaleman commented on api/pkg/controller/operator-master/controller.go
> +	eventHandler := newEventHandler(func(a handler.MapObject) []reconcile.Request {
This is a re-implementation of `sigs.k8s.io/controller-runtime/pkg/handler.EnqueueRequestForObject`

2019-07-24 15:01 UTC, alvaroaleman commented on api/pkg/controller/operator-master/controller.go
> +		if err := c.Watch(&source.Kind{Type: t}, eventHandler, predicate); err != nil {
(Here using `t` as a variable name is btw perfectly reasonable because it indicates that its a type that is different in every iteration of the loop)

2019-07-24 15:10 UTC, alvaroaleman commented on api/pkg/controller/operator-master/controller.go
> +	predicate = newPredicateFuncs(func(meta metav1.Object) bool {
sorry correction: 3 LOC vs 30 LOC. And three  LOC that are completely obvious to reason about, the amount of funcs added to the code here just to get a predicate func is quite a lot.

2019-07-24 15:39 UTC, alvaroaleman commented
@xrstf Can we please split this PR up? E.G. into:

* PR 0: Add types
* PR 1: Add a no-op reconciler that watches just the newly-added types
* PR 2: Add a single thing to reconcile to the reconciler and with it what should now be watched on top.

PRs of this size:
* Make your reviewers not want to review it because of the sheer size
* Have a very high probably of introducing bugs because reviewers dont catch them because of the sheer size of the PR
* Have a high chance of doing something wrong in multiple places

Please try to create PRs in a way that they change one thing at a time.

2019-07-24 15:41 UTC, alvaroaleman commented on api/pkg/controller/operator-master/reconciler.go
> +func (r *Reconciler) fetchKubermaticConfiguration(ctx context.Context, identifier types.NamespacedName) (*operatorv1alpha1.KubermaticConfiguration, error) {
Why do we create a function that is being called exactly one and and very unlikely to need a dedicated unittest?

2019-07-24 15:41 UTC, alvaroaleman commented on api/pkg/controller/operator-master/reconciler.go
> +	// TODO: Implement garbage collection to remove orphaned resources.
Please use a dedicated controller for garbage collection, this one is complicated enough as-is.

2019-07-24 15:41 UTC, alvaroaleman commented on api/pkg/controller/operator-master/reconciler.go
> +func (r *configData) applyDefaultFields() reconciling.ObjectModifier {
Can we rename to `defaultMetadataModifier()`? One has to read the comment or the code to understand that this doesn't change `fields`, it always changes metadata. Also it doesnt apply anything, its a factory to get a func which applies something.

2019-07-25 14:23 UTC, xrstf commented on api/pkg/resources/kubermatic/master-controller-manager.go
> +	return corev1.Container{
=> #3891

2019-07-25 14:25 UTC, xrstf commented on api/pkg/crd/operator/v1alpha1/configuration.go
> +	PullPolicy corev1.PullPolicy `json:"pullPolicy"`
It mirrors the exact same struct we have all over the place in our Helm charts. I assumed for offline clusters we still want the ability to overwrite repositories, need to overwrite tags for testing and the pull policy for testing as well. Am I wrong?

2019-07-25 14:26 UTC, xrstf commented on api/pkg/controller/operator-master/controller.go
> +	if err := c.Watch(&source.Kind{Type: t}, eventHandler, predicate); err != nil {
But then you need to replicate the same type into the error message just one line below this one and I have already seen cases in our codebase where the error message mentions a totally different object kind than was actually intended.

2019-07-26 20:46 UTC, xrstf commented on api/pkg/controller/operator-master/controller.go
> +	predicate = newPredicateFuncs(func(meta metav1.Object) bool {
I was under the assumption that if there is a predicate feature, I am supposed to use it to check for relevant objects as soon as possible, most likely in an effort to improve controller performance in general.

2019-07-26 20:53 UTC, xrstf commented
This is being split up in #3896, #3898 and future PRs.

2019-07-26 20:53 UTC, closed without merging