Add Prometheus rule for init node deployment failures
kubermatic/kubermatic pull request #3869
Opened 2019-07-23 14:37 UTC by maciaszczykm

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3041.

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2019-07-24 13:18 UTC, xrstf requested changes
Please rephrase.

2019-07-24 13:18 UTC, xrstf commented on config/monitoring/prometheus/rules/kubermatic-master-kubermatic.yaml
> +      message: Kubermatic API is failing to create too many initial node deployments.
Either the API is failing to do something, or it creates too many node deployments. But failing to create too many sounds .. like a good thing?

2019-07-24 13:18 UTC, xrstf commented
Also please bump the Prometheus chart version in the Chart.yaml.

2019-07-26 07:04 UTC, maciaszczykm commented
@xrstf Done, PTAL

2019-07-26 07:30 UTC, xrstf commented
/lgtm
/approve

2019-07-26 07:31 UTC, merged