Add endpoint listing AWS sizes
kubermatic/kubermatic pull request #4166
Opened 2019-08-23 14:11 UTC by maciaszczykm

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: Related to https://github.com/kubermatic/dashboard-v2/issues/1245.

**Special notes for your reviewer**: Example output from `127.0.0.1:8080/api/v1/providers/aws/sizes`:

```json
[
    {
        "name": "c5d.xlarge",
        "pretty_name": "C5 High-CPU Extra Large",
        "memory": 8,
        "vcpus": 4
    },
    {
        "name": "m5a.2xlarge",
        "pretty_name": "M5A Double Extra Large",
        "memory": 32,
        "vcpus": 8
    },
    {
        "name": "c5.9xlarge",
        "pretty_name": "C5 High-CPU 9xlarge",
        "memory": 72,
        "vcpus": 36
    },
    {
        "name": "r5ad.xlarge",
        "pretty_name": "R5AD Extra Large",
        "memory": 32,
        "vcpus": 4
    },
    {
        "name": "c5.large",
        "pretty_name": "C5 High-CPU Large",
        "memory": 4,
        "vcpus": 2
    },
    {
        "name": "c5n.large",
        "pretty_name": "C5N Large",
        "memory": 5.25,
        "vcpus": 2
    },
    {
        "name": "i2.xlarge",
        "pretty_name": "I2 Extra Large",
        "memory": 30.5,
        "vcpus": 4
    },
    {
        "name": "i3en.3xlarge",
        "pretty_name": "I3EN 3xlarge",
        "memory": 96,
        "vcpus": 12
    },
    {
        "name": "z1d.3xlarge",
        "pretty_name": "Z1D 3xlarge",
        "memory": 96,
        "vcpus": 12
    },
    {
        "name": "m5.2xlarge",
        "pretty_name": "M5 General Purpose Double Extra Large",
        "memory": 32,
        "vcpus": 8
    },
    {
        "name": "i2.2xlarge",
        "pretty_name": "I2 Double Extra Large",
        "memory": 61,
        "vcpus": 8
    },
    {
        "name": "i3en.2xlarge",
        "pretty_name": "I3EN Double Extra Large",
        "memory": 64,
        "vcpus": 8
    },
    {
        "name": "m5a.xlarge",
        "pretty_name": "M5A Extra Large",
        "memory": 16,
        "vcpus": 4
    },
    {
        "name": "t2.2xlarge",
        "pretty_name": "T2 Double Extra Large",
        "memory": 32,
        "vcpus": 8
    },
    {
        "name": "t2.large",
        "pretty_name": "T2 Large",
        "memory": 8,
        "vcpus": 2
    },
    {
        "name": "r5a.large",
        "pretty_name": "R5A Large",
        "memory": 16,
        "vcpus": 2
    },
    {
        "name": "c3.large",
        "pretty_name": "C3 High-CPU Large",
        "memory": 3.75,
        "vcpus": 2
    },
    {
        "name": "a1.2xlarge",
        "pretty_name": "A1 Double Extra Large",
        "memory": 16,
        "vcpus": 8
    },
    {
        "name": "c4.xlarge",
        "pretty_name": "C4 High-CPU Extra Large",
        "memory": 7.5,
        "vcpus": 4
    },
    {
        "name": "m5ad.xlarge",
        "pretty_name": "M5AD Extra Large",
        "memory": 16,
        "vcpus": 4
    },
    {
        "name": "m4.large",
        "pretty_name": "M4 General Purpose Large",
        "memory": 8,
        "vcpus": 2
    },
    {
        "name": "h1.4xlarge",
        "pretty_name": "H1 Quadruple Extra Large",
        "memory": 64,
        "vcpus": 16
    },
    {
        "name": "x1e.xlarge",
        "pretty_name": "X1E Extra Large",
        "memory": 122,
        "vcpus": 4
    },
    {
        "name": "m5.large",
        "pretty_name": "M5 General Purpose Large",
        "memory": 8,
        "vcpus": 2
    },
    {
        "name": "c5.4xlarge",
        "pretty_name": "C5 High-CPU Quadruple Extra Large",
        "memory": 32,
        "vcpus": 16
    },
    {
        "name": "r3.large",
        "pretty_name": "R3 High-Memory Large",
        "memory": 15.25,
        "vcpus": 2
    },
    {
        "name": "c4.large",
        "pretty_name": "C4 High-CPU Large",
        "memory": 3.75,
        "vcpus": 2
    },
    {
        "name": "r5d.xlarge",
        "pretty_name": "R5D Extra Large",
        "memory": 32,
        "vcpus": 4
    },
    {
        "name": "m5d.large",
        "pretty_name": "M5 General Purpose Large",
        "memory": 8,
        "vcpus": 2
    },
    {
        "name": "r5.2xlarge",
        "pretty_name": "R5 Double Extra Large",
        "memory": 64,
        "vcpus": 8
    },
    {
        "name": "m3.2xlarge",
        "pretty_name": "M3 General Purpose Double Extra Large",
        "memory": 30,
        "vcpus": 8
    },
    {
        "name": "m5d.2xlarge",
        "pretty_name": "M5 General Purpose Double Extra Large",
        "memory": 32,
        "vcpus": 8
    },
    {
        "name": "m5ad.large",
        "pretty_name": "M5AD Large",
        "memory": 8,
        "vcpus": 2
    },
    {
        "name": "c5d.large",
        "pretty_name": "C5 High-CPU Large",
        "memory": 4,
        "vcpus": 2
    },
    {
        "name": "c5n.2xlarge",
        "pretty_name": "C5N Double Extra Large",
        "memory": 21,
        "vcpus": 8
    },
    {
        "name": "m5d.xlarge",
        "pretty_name": "M5 General Purpose Extra Large",
        "memory": 16,
        "vcpus": 4
    },
    {
        "name": "m3.large",
        "pretty_name": "M3 General Purpose Large",
        "memory": 7.5,
        "vcpus": 2
    },
    {
        "name": "c5d.4xlarge",
        "pretty_name": "C5 High-CPU Quadruple Extra Large",
        "memory": 32,
        "vcpus": 16
    },
    {
        "name": "r4.large",
        "pretty_name": "R4 High-Memory Large",
        "memory": 15.25,
        "vcpus": 2
    },
    {
        "name": "r3.xlarge",
        "pretty_name": "R3 High-Memory Extra Large",
        "memory": 30.5,
        "vcpus": 4
    },
    {
        "name": "c5n.xlarge",
        "pretty_name": "C5N Extra Large",
        "memory": 10.5,
        "vcpus": 4
    },
    {
        "name": "m5a.4xlarge",
        "pretty_name": "M5A Quadruple Extra Large",
        "memory": 64,
        "vcpus": 16
    },
    {
        "name": "r5ad.2xlarge",
        "pretty_name": "R5AD Double Extra Large",
        "memory": 64,
        "vcpus": 8
    },
    {
        "name": "t2.xlarge",
        "pretty_name": "T2 Extra Large",
        "memory": 16,
        "vcpus": 4
    },
    {
        "name": "c3.8xlarge",
        "pretty_name": "C3 High-CPU Eight Extra Large",
        "memory": 60,
        "vcpus": 32
    },
    {
        "name": "m3.medium",
        "pretty_name": "M3 General Purpose Medium",
        "memory": 3.75,
        "vcpus": 1
    },
    {
        "name": "x1e.2xlarge",
        "pretty_name": "X1E Double Extra Large",
        "memory": 244,
        "vcpus": 8
    },
    {
        "name": "m5a.8xlarge",
        "pretty_name": "M5A Eight Extra Large",
        "memory": 128,
        "vcpus": 32
    },
    {
        "name": "m5ad.2xlarge",
        "pretty_name": "M5AD Double Extra Large",
        "memory": 32,
        "vcpus": 8
    },
    {
        "name": "r5a.2xlarge",
        "pretty_name": "R5A Double Extra Large",
        "memory": 64,
        "vcpus": 8
    },
    {
        "name": "d2.xlarge",
        "pretty_name": "D2 Extra Large",
        "memory": 30.5,
        "vcpus": 4
    },
    {
        "name": "c5.2xlarge",
        "pretty_name": "C5 High-CPU Double Extra Large",
        "memory": 16,
        "vcpus": 8
    },
    {
        "name": "t3.medium",
        "pretty_name": "T3 Medium",
        "memory": 4,
        "vcpus": 2
    },
    {
        "name": "m1.xlarge",
        "pretty_name": "M1 General Purpose Extra Large",
        "memory": 15,
        "vcpus": 4
    },
    {
        "name": "c5d.2xlarge",
        "pretty_name": "C5 High-CPU Double Extra Large",
        "memory": 16,
        "vcpus": 8
    },
    {
        "name": "m3.xlarge",
        "pretty_name": "M3 General Purpose Extra Large",
        "memory": 15,
        "vcpus": 4
    },
    {
        "name": "m1.medium",
        "pretty_name": "M1 General Purpose Medium",
        "memory": 3.75,
        "vcpus": 1
    },
    {
        "name": "t3a.medium",
        "pretty_name": "T3A [...]

2019-08-26 12:42 UTC, maciaszczykm commented on allowed_licensed.yaml
> +  - github.com/cristim/ec2-instances-info # Public domain and MIT. See: https://github.com/cristim/ec2-instances-info/blob/master/LICENSE and https://github.com/powdahound/ec2instances.info/blob/mast
@kdomanski Can we use it? The repo code is "public domain" and the generated data is under MIT from what I can see. Is that okay?

2019-08-26 13:28 UTC, maciaszczykm commented on api/pkg/handler/v1/provider/aws.go
> +				// TODO: Use correct datacenter to get the pricing and enable changing 2$ price limit.
We would need to pass region here, not the name of the seed cluster.

2019-08-26 13:28 UTC, maciaszczykm commented
/retest

2019-08-26 14:43 UTC, kdomanski commented on allowed_licensed.yaml
> +  - github.com/cristim/ec2-instances-info # Public domain and MIT. See: https://github.com/cristim/ec2-instances-info/blob/master/LICENSE and https://github.com/powdahound/ec2instances.info/blob/mast
That's okay.

2019-08-27 07:05 UTC, maciaszczykm commented on allowed_licensed.yaml
> +  - github.com/cristim/ec2-instances-info # Public domain and MIT. See: https://github.com/cristim/ec2-instances-info/blob/master/LICENSE and https://github.com/powdahound/ec2instances.info/blob/mast
Okay, thank you.

2019-08-27 11:07 UTC, zreigz requested changes

2019-08-27 11:07 UTC, zreigz commented on api/pkg/handler/v1/provider/aws.go
> +// AzureSizeReq represent a request for Azure VM sizes
change `Azure` to `AWS`

2019-08-27 11:07 UTC, zreigz commented on api/pkg/handler/v1/provider/aws.go
> +func DecodeAWSSizesReq(c context.Context, r *http.Request) (interface{}, error) {
add documentation comments

2019-08-27 11:56 UTC, zreigz commented
/approve

2019-08-27 12:10 UTC, zreigz commented
/lgtm

2019-08-27 13:20 UTC, merged