chart-sync: automatically plug in the latest dashboard tag from a matching release branch
kubermatic/kubermatic pull request #4230
Opened 2019-09-02 09:45 UTC by kdomanski

```release-note
NONE
```

2019-09-02 09:46 UTC, kdomanski commented
/assign @thz

2019-09-02 10:00 UTC, thz requested changes
Just a minor substitution nit.

2019-09-02 10:00 UTC, thz commented on api/hack/ci/ci-sync-charts.sh
> +MINOR_VERSION="$(sed 's:release/::' <<< "$INSTALLER_BRANCH")"
You are nesting the double quotes here. I propose to use the following instead:
```
MINOR_VERSION="${INSTALLER_BRANCH##release/}"
```

2019-09-02 10:32 UTC, thz approved these changes

2019-09-02 10:32 UTC, thz commented
/lgtm
/approve

2019-09-02 11:20 UTC, thz commented
It just got so much better ;-)
/lgtm

2019-09-02 11:51 UTC, alvaroaleman commented on config/kubermatic/values.yaml
> +      tag: "__DASHBOARD_TAG__"
This breaks the deployment to all of our envs. It must stay consistent on master branch and it must be valid.

The way this works is:

* Helm doesn't do anything about the UI if nothing changes in the helm manifests and values
* There is a postsubmit in the dashboard repo that updates the tag on every push to master

/hold

2019-09-03 12:07 UTC, kdomanski commented on config/kubermatic/values.yaml
> +      tag: "__DASHBOARD_TAG__"
Yes, it's marked as [WIP].

2019-09-04 14:31 UTC, kdomanski commented
/test pull-kubermatic-canary-deployment-ci-kubermatic-io

2019-09-04 14:47 UTC, kdomanski commented
/test pull-kubermatic-e2e-aws-coreos-1.13

2019-09-04 16:34 UTC, alvaroaleman commented on api/hack/lib.sh
> +  if [[ "$FOR_BRANCH" == "master" ]]; then
Rather than introducing some magic exception to not get a tag but a sha in a func named `get_latest_tag`, can we just not use this func in `deploy.sh` and instead do a simple ` git ls-remote "$DASHBOARD_URL" refs/heads/$PULL_BASE_REF | awk '{ print $1 }'` there?

In contrast to the current implementation, that would also work properly when we are in a release branch.

2019-09-04 17:29 UTC, kdomanski commented on api/hack/lib.sh
> +  if [[ "$FOR_BRANCH" == "master" ]]; then
Wouldn't removing the exception break PRs opened against master?

2019-09-05 07:49 UTC, alvaroaleman commented on api/hack/lib.sh
> +  if [[ "$FOR_BRANCH" == "master" ]]; then
The most correct way of doing this would be to have `hack/ci/ci-run-minimal-conformance-tests.sh` also figure out the latest hash of the corresponding base branch rather than the latest tag.

In reality this has very little relevance thought, as the only thing these tests test wrt UI is that it doens't crashloop. So as long as `get_latest_dashboard_tag` returns _any_ tag, that should be fine.

So basically, whatever you prefer, both what is currently done and changing it would work.

2019-09-05 10:51 UTC, kdomanski commented
/test pull-kubermatic-api-e2e

2019-09-05 11:19 UTC, kdomanski commented
/test pull-kubermatic-api-e2e

2019-09-05 14:46 UTC, kdomanski commented
/test pull-kubermatic-api-e2e

2019-09-06 09:08 UTC, kdomanski commented
/override pull-kubermatic-e2e-aws-openshift-4.1.9

2019-09-06 09:11 UTC, alvaroaleman commented
@kdomanski can you not override tests unless you know for sure they are broken? The correct approach is to fix the test, not to override it. The particular test you are overriding here got fixed yesterday in #4259

2019-09-06 09:11 UTC, alvaroaleman commented
/test pull-kubermatic-e2e-aws-openshift-4.1.9

2019-09-06 12:12 UTC, alvaroaleman commented
/lgtm
/approve
/hold cancel

2019-09-06 12:21 UTC, kdomanski commented
/test pull-kubermatic-e2e-aws-coreos-1.14

2019-09-06 13:07 UTC, kdomanski commented
/retest

2019-09-06 13:23 UTC, merged