[WIP] Added 404 if swagger json doesn't exists:
kubermatic/kubermatic pull request #430
Opened 2017-09-04 06:19 UTC by andriisoldatenko

fixed #423 
- create smal unit test;
- updated README;
- updated MAKEfile;

2017-09-04 06:20 UTC, andriisoldatenko commented on api/handler/handler.go
>  	f, err := ioutil.ReadFile("../api/handler/swagger/api/index.json")
@guusvw any ideas how to improve this hardcoded path, or mock it in unit tests?

2017-09-04 07:17 UTC, guusvw commented on api/handler/handler.go
>  	f, err := ioutil.ReadFile("../api/handler/swagger/api/index.json")
I would use [flag.String()](https://godoc.org/flag#String) and use a package global variable, so you can change it at the begin of the test.
There are better ways to do it, but that would cause a bigger refactoring.

2017-09-11 08:58 UTC, andriisoldatenko commented
@guusvw PTAL (I'm not sure are you using this acronym from internal go team, PTAL = Please Take Another Look). thanks

2017-09-11 11:46 UTC, lbb requested changes

2017-09-11 11:46 UTC, lbb commented on api/Makefile
> +run-api:
We don't need this in the makefile, maybe replace it with `hack-%:` and the run the script with `hack/$*.sh` or something equivalent.

2017-09-11 11:46 UTC, lbb commented on api/handler/handler.go
> +	swaggerPath := fmt.Sprint(flag.Lookup("swagger-path").Value)
please don't use lookups it is untyped and we can't easily change flags without refactoring.

2017-09-11 11:46 UTC, lbb commented on api/Makefile
> +.PHONY: build test check cover e2e-build client-build client-down client-up e2e docker-build docker-push bootstrap $(CMD)
Also add the *runnable* steps tho the PHONY files

2017-09-13 07:20 UTC, andriisoldatenko commented on api/handler/handler.go
> +	swaggerPath := fmt.Sprint(flag.Lookup("swagger-path").Value)
@realfake any ideas how to improve it? I checked https://golang.org/src/flag/example_test.go, but I'm not sure what's the best way to share flag between 2 different packages? any suggestions?
cc @guusvw

2017-09-13 07:21 UTC, andriisoldatenko commented on api/Makefile
> +run-api:
@realfake done.

2017-09-14 14:43 UTC, lbb commented on api/handler/handler.go
> +	swaggerPath := fmt.Sprint(flag.Lookup("swagger-path").Value)
Yeah pass it through as parameter, as you can see here https://github.com/kubermatic/kubermatic/blob/cb1e1378c00aa00abf866882162079919529ba0a/api/handler/routing.go#L30

2017-10-17 09:59 UTC, mrIncompetent commented
We're using now master instead of develop.
Please rebase your branch and open the PR against master

2017-10-17 09:59 UTC, closed without merging