Allow specifying AWS AssignPublicIP field
kubermatic/kubermatic pull request #4328
Opened 2019-09-19 13:32 UTC by maciaszczykm

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4149

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Allowed specifying AWS AssignPublicIP field.
```

2019-09-19 13:56 UTC, zreigz commented
/lgtm

2019-09-19 13:56 UTC, zreigz commented
/approve

2019-09-19 14:08 UTC, maciaszczykm commented
/assign @thz

2019-09-19 14:49 UTC, thz requested changes

2019-09-19 14:49 UTC, thz commented on api/cmd/kubermatic-api/swagger.json
> +          "description": "should the machine have a publicly accessible IP address",
I think we can be more clear here about what is happening:
This flag controls a property of the AWS instance. When set the AWS instance will get a public IP address assigned during launch overriding a possible setting in the used AWS subnet.

2019-09-20 07:13 UTC, maciaszczykm commented on api/cmd/kubermatic-api/swagger.json
> +          "description": "should the machine have a publicly accessible IP address",
Okay, that sounds much better.

2019-09-20 08:22 UTC, maciaszczykm commented
@thz PTAL

2019-09-20 08:32 UTC, maciaszczykm commented
/retest

2019-09-20 14:20 UTC, thz commented
/lgtm
/approve

2019-09-20 14:25 UTC, thz approved these changes

2019-09-20 15:45 UTC, merged