Add endpoint to list system labels
kubermatic/kubermatic pull request #4504
Opened 2019-10-17 08:29 UTC by floreks

**What this PR does / why we need it**:
Add endpoint to list restricted system labels and filters them out from Cluster, ND, Project LIST/GET endpoints.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4492

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2019-10-17 08:32 UTC, maciaszczykm commented
LGTM, leaving for @zreigz.

2019-10-17 09:29 UTC, zreigz commented
It would be good to add some unit tests for this new endpoint

2019-10-17 13:00 UTC, floreks commented
/retest

2019-10-17 13:01 UTC, zreigz requested changes

2019-10-17 13:01 UTC, zreigz commented on api/pkg/handler/v1/label/label_test.go
> +			Name:            "scenario 1: list clusters that belong to the given project",
change description

2019-10-17 13:01 UTC, zreigz commented on api/pkg/handler/routes_v1.go
> +		Path("/label/system").
we use the plural for the endpoints. should be `/labels/system`

2019-10-17 13:43 UTC, zreigz commented
/lgtm
/approve

2019-10-17 14:06 UTC, merged

2019-11-04 08:36 UTC, maciaszczykm commented
/cherrypick release/v2.12