Add proposals for edge cluster management
kubermatic/kubermatic pull request #4532
Opened 2019-10-22 14:11 UTC by ManuStoessel

**What this PR does / why we need it**:

This PR adds two new proposals that describe how we can enable the management of Edge clusters running on hardware boxes at a customer site. For this we'll need a new "KubeOne" provider in Kubermatic and a gRPC connector that will allow SSH access to the hardware boxes.

2019-10-22 18:46 UTC, toschneck requested changes
please also add acceptance criterias

2019-10-22 18:46 UTC, toschneck commented on docs/proposals/kubeone-provider.md
> +- Innovo needs the client infrastructure setup to be independently timeable of cluster creation in Kubermatic
@ManuStoessel remove

2019-10-22 20:54 UTC, alvaroaleman commented on docs/proposals/grpc-agent.md
> +# Creating a gRPC agent component for enabling KubeOne cluster management in Kubermatic
How is this different from an ordinary vpn?

2019-10-22 20:54 UTC, alvaroaleman commented on docs/proposals/kubeone-provider.md
> +When the agent successfully establishes connection with the gRPC server (running in the user-cluster namespace) a KubeOne install will be triggered (by watching gRPC agent connection health status in
If an unstable network connection is anticpated, why not execute kubeone on one of the nodes?

2019-10-22 20:54 UTC, alvaroaleman commented on docs/proposals/kubeone-provider.md
> +Add a new provider to Kubermatic that will not deploy a k8s control plane in the seed cluster. The cluster CRD will be used with some sort of specification that it is a KubeOne cluster (e.g. cluster-
The implication here being that everything in our API that talks to the user cluster needs adjustment. How are we planning to cope with the cluster being unreachable btw?

2019-10-23 05:42 UTC, ManuStoessel commented on docs/proposals/kubeone-provider.md
> +When the agent successfully establishes connection with the gRPC server (running in the user-cluster namespace) a KubeOne install will be triggered (by watching gRPC agent connection health status in
We still want to keep all the complexity on the Kubermatic side, so that the agent component on the nodes can be as simple as possible (for maintenance cost reasons). Also KubeOne does not have a "localhost" provisioning functionality. The unstable connection should also pose no great problem to KubeOne since the install itself is a one-off kinda thing and KubeOne will have a repair functionality in the future for reconciling failed install attempts.

2019-10-23 05:46 UTC, ManuStoessel commented on docs/proposals/kubeone-provider.md
> +Add a new provider to Kubermatic that will not deploy a k8s control plane in the seed cluster. The cluster CRD will be used with some sort of specification that it is a KubeOne cluster (e.g. cluster-
The cluster being unreachable should pose no problem in this case since the control plan will run on the hardware nodes on the customer site. The gRPC agent on the node will just keep trying to reconnect until the connection is available again.

> The implication here being that everything in our API that talks to the user cluster needs adjustment.

What parts of the API do directly talk to the user-cluster? We could still tunnel that through the gRPC connection without major adjustment on the Kubermatic side I guess.

2019-10-23 05:47 UTC, ManuStoessel commented on docs/proposals/grpc-agent.md
> +# Creating a gRPC agent component for enabling KubeOne cluster management in Kubermatic
Following @scheeles architecture proposal here.

2019-10-23 06:07 UTC, closed without merging