OpenShift: deploy metrics-server
kubermatic/kubermatic pull request #4671
Opened 2019-11-12 16:44 UTC by kron4eg

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4355

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
openshift: add metrics-server
```

2019-11-13 12:57 UTC, alvaroaleman commented on api/pkg/controller/user-cluster-controller-manager/resources/reconciler.go
> +	creators = append(creators, metricsserver.APIServiceCreator(caCert))
No need for the append, you can just define it in line 114 where the var is initialized

2019-11-13 13:27 UTC, kron4eg commented on api/pkg/controller/user-cluster-controller-manager/resources/reconciler.go
> +	creators = append(creators, metricsserver.APIServiceCreator(caCert))
👍

2019-11-13 13:45 UTC, alvaroaleman commented on api/hack/run-controller.sh
> +export KUBERMATICCOMMIT="${KUBERMATICCOMMIT:-$(git rev-parse HEAD)}"
This needs to stay the way it was, else it will be broken by default as in most cases there won't be an image for HEAD. If you actually need and want that you can override the value by setting the KUBERMATICCOMMIT env var.

2019-11-13 13:51 UTC, kron4eg commented on api/hack/run-controller.sh
> +export KUBERMATICCOMMIT="${KUBERMATICCOMMIT:-$(git rev-parse HEAD)}"
Yeah, after thinking about it a bit more, I realized this is very thin ice. Consider this knee-jerk reaction on multiple WTF/second produced by the fact that pods used unexpected image tag :)

Removed.

2019-11-13 14:11 UTC, kron4eg commented
/retest

2019-11-13 14:29 UTC, kron4eg commented
/retest

2019-11-13 20:33 UTC, kron4eg commented
metrics-server complains:
```
E1113 20:31:55.085672       1 authentication.go:65] Unable to authenticate the request due to an error: [x509: subject with cn=apiserver-aggregator is not in the allowed list, x509: certificate signed by unknown authority]
```

2019-11-14 22:29 UTC, kron4eg commented
/retest

2019-11-18 08:29 UTC, kron4eg commented
/hold

needs additional testing

2019-11-18 14:57 UTC, kron4eg commented
/retest

2019-11-18 15:50 UTC, kron4eg commented
/hold cancel

it works

2019-11-18 15:51 UTC, kron4eg commented
/assign @alvaroaleman 

PTAL

2019-11-18 15:52 UTC, kron4eg commented
/retest

2019-11-18 18:14 UTC, alvaroaleman commented on api/hack/run-api.sh
> +make -C ./.. kubermatic-api
Why did you change this? This change means that the script will stop working of the api folder is not the current working directoy

2019-11-18 18:14 UTC, alvaroaleman commented on api/hack/run-api.sh
> +KUBERMATIC_SECRETS_DIR=${KUBERMATIC_SECRETS_DIR:-"../../secrets"}
Please use `$0` as base for relative paths

2019-11-18 18:14 UTC, alvaroaleman commented on api/hack/run-api.sh
> +  "$@"
Doesn't this break the script when passing more than one extra arg?

2019-11-18 18:14 UTC, alvaroaleman commented on api/hack/run-userclustercontroller.sh
> +OPENVPN_SERVER_SERVICE_RAW="$(kubectl get service openvpn-server -o json)"
Not re-arranging this would make this pull easier to review :grimacing:

2019-11-18 18:14 UTC, alvaroaleman commented on api/hack/run-userclustercontroller.sh
> +OPENVPN_SERVER_SERVICE_RAW="$(kubectl get service openvpn-server -o json)"
And generally it would be nice to create dedicated PRs for this kind of refactoring, as it doesn't really have anything to do with the main purpose of the PR

2019-11-18 18:14 UTC, alvaroaleman commented on api/hack/run-userclustercontroller.sh
> +    -pprof-listen-address="${KUBERMATIC_PPROF_ADDRESS}" \
Same here, if you add new args at the end instead of in the middle, the diff stays way smaller which makes reviewing easier

2019-11-18 18:16 UTC, alvaroaleman commented
@kron4eg the RBAC issues were all fixes by allowing the new client name?

2019-11-19 10:39 UTC, kron4eg commented on api/hack/run-userclustercontroller.sh
> +OPENVPN_SERVER_SERVICE_RAW="$(kubectl get service openvpn-server -o json)"
I had to fix pprof port, so I had to edit this file and then all hell broke loose:
* https://github.com/mvdan/sh reformatted me the document
* shellcheck (shell linter) screamed in pains. How could I not fix linter complaining

¯\\\_(ツ)\_/¯

2019-11-19 10:41 UTC, kron4eg commented on api/hack/run-api.sh
> +make -C ./.. kubermatic-api
Fixed

2019-11-19 10:41 UTC, kron4eg commented on api/hack/run-api.sh
> +KUBERMATIC_SECRETS_DIR=${KUBERMATIC_SECRETS_DIR:-"../../secrets"}
Fixed

2019-11-19 10:42 UTC, kron4eg commented on api/hack/run-api.sh
> +  "$@"
no, it's all good, and even safer: https://github.com/koalaman/shellcheck/wiki/SC2068

2019-11-19 10:44 UTC, kron4eg commented
> @kron4eg the RBAC issues were all fixes by allowing the new client name?

Yup, adding missing `apiserver-aggregator` to the clientName fixed the issue with Unauthorized reply from api, when I tried to access metrics.

2019-11-19 11:07 UTC, kron4eg commented on api/hack/run-userclustercontroller.sh
> +    -pprof-listen-address="${KUBERMATIC_PPROF_ADDRESS}" \
The reason to stick pprof-listen-address= into the place where it is, is to group it with others -listen-address= parameters.

2019-11-19 12:33 UTC, kron4eg commented
/retest

2019-11-19 16:28 UTC, kron4eg commented
/retest

2019-11-19 16:31 UTC, kron4eg commented
/retest

2019-11-19 17:31 UTC, kron4eg commented
/retest

2019-11-19 22:22 UTC, kron4eg commented
/retest

2019-11-20 06:18 UTC, kron4eg commented
/retest

2019-11-20 11:48 UTC, kron4eg commented
/retest

2019-11-20 12:15 UTC, kron4eg commented
/test pull-kubermatic-canary-deployment-ci-kubermatic-io

2019-11-22 16:38 UTC, alvaroaleman commented on api/hack/run-userclustercontroller.sh
> +OPENVPN_SERVER_SERVICE_RAW="$(kubectl get service openvpn-server -o json)"
So learn to not use `git -a`? If you have an editorconfig that automatically changes stuff, that should be very much your problem to solve and not the one of your reviewer.

2019-11-22 17:11 UTC, alvaroaleman requested changes
This still fails to scrape metrics with a `E1122 16:58:48.641179       1 authentication.go:65] Unable to authenticate the request due to an error: [x509: subject with cn=apiserver-aggregator is not in the allowed list, x509: certificate signed by unknown authority]` in the metrics server.

Changing the frontproxy client cert to use `kube-apiserver-proxy` as CN fixes that, indicating something with the aggregration layer is still not set up correctly:

```
diff --git a/api/pkg/resources/apiserver/frontproxy-client-certificate.go b/api/pkg/resources/apiserver/frontproxy-client-certificate.go
index a6aa44f57..dcaecc3ae 100644
--- a/api/pkg/resources/apiserver/frontproxy-client-certificate.go
+++ b/api/pkg/resources/apiserver/frontproxy-client-certificate.go
@@ -15,7 +15,7 @@ type frontProxyClientCertificateCreatorData interface {
 func FrontProxyClientCertificateCreator(data frontProxyClientCertificateCreatorData) reconciling.NamedSecretCreatorGetter {
        return certificates.GetClientCertificateCreator(
                resources.ApiserverFrontProxyClientCertificateSecretName,
-               "apiserver-aggregator",
+               "kube-apiserver-proxy",
                nil,
                resources.ApiserverProxyClientCertificateCertSecretKey,
                resources.ApiserverProxyClientCertificateKeySecretKey,
```

2019-11-22 17:11 UTC, alvaroaleman commented on api/hack/run-controller.sh
> -#!/bin/bash
This script doesn't work anymore and without having tried, I assume the same is true for all the other scripts. Please remove all changes to the scripts out of this PR and if you care, create a new one. Those do not have anything to do with the metrics server. I tested this with the versions in `master` of the scripts.

2019-11-22 17:26 UTC, kron4eg commented
> This still fails to scrape metrics with a `E1122 16:58:48.641179 1 authentication.go:65] Unable to authenticate the request due to an error: [x509: subject with cn=apiserver-aggregator is not in the allowed list, x509: certificate signed by unknown authority]` in the metrics server.

Deployments in user-cluster namespace needs to be restarted to pickup the change.

2019-11-22 17:37 UTC, alvaroaleman commented
> Deployments in user-cluster namespace needs to be restarted to pickup the change.

That should happen automatically, we pick up changes to all mounts by putting a label for each mount with a value that is the resourceVersion of the mounted thing. If this does not happen then that is a bug that needs fixing.

2019-11-25 12:42 UTC, kron4eg commented
latest push is just a push force without commits regarding shell scripts

2019-11-29 12:47 UTC, alvaroaleman approved these changes
/lgtm
/approve

2019-11-29 13:25 UTC, kron4eg commented
/retest

2019-11-29 14:32 UTC, alvaroaleman commented
/retest

2019-11-29 15:16 UTC, kron4eg commented
/retest

2019-11-29 16:34 UTC, merged