Rewrite controller to match best-practices
kubermatic/kubermatic pull request #474
Opened 2017-10-01 13:15 UTC by mrIncompetent

2017-10-01 13:19 UTC, mrIncompetent commented
We should introduce the informer-group also in the api to increase api performance and to reduce master-api-calls

2017-10-02 06:21 UTC, lbb commented on api/pkg/controller/types.go
> +	Run(workerCount int, stopCh chan struct{})
Why do we have to change a method of an interface?
IMHO We should rather specify the worker count when building the controller.

2017-10-02 06:32 UTC, lbb commented
I ❤️ this kind of PR's

2017-10-02 07:00 UTC, mrIncompetent commented on api/pkg/controller/types.go
> +	Run(workerCount int, stopCh chan struct{})
Its common practice to have the number-of-workers be configurable.
Its something you might tune during production. Which you cant if you have it hard-coded

2017-10-02 07:07 UTC, lbb commented on api/pkg/controller/types.go
> +	Run(workerCount int, stopCh chan struct{})
Shouldn't be hardcoded, rather be a Struct variable or an extra method

2017-10-02 07:14 UTC, mrIncompetent commented on api/pkg/controller/types.go
> +	Run(workerCount int, stopCh chan struct{})
So instead of passing an int, you want a struct which only has a int property?
Or do you want an extra method only to specify the number of workers?

Seems i don't fully get the point where you want to go, can you give me some examples?

2017-10-02 13:05 UTC, metalmatze requested changes
Overall it looks pretty nice! :tada: I very much like the fact, that you now do a lot more with the k8s client and less string building. :blush:

2017-10-02 13:05 UTC, metalmatze commented on api/cmd/kubermatic-cluster-controller/main.go
> +	signal.Notify(osc, []os.Signal{os.Interrupt, syscall.SIGTERM}...)
This can be simplified: `signal.Notify(osc, os.Interrupt, syscall.SIGTERM)`

2017-10-02 13:05 UTC, metalmatze commented on api/cmd/kubermatic-cluster-controller/main.go
> +	stop := make(chan struct{})
I think a channel is fine here. I would have used a context with `context.WithCancel` though. But it's nitpicking.

2017-10-02 13:05 UTC, metalmatze commented on api/cmd/kubermatic-cluster-controller/main.go
> +	osc := make(chan os.Signal, 2)
`osc` doesn't really say anything to me. I think it can be simply called `sig` or `signal`.

2017-10-02 13:05 UTC, metalmatze commented on api/cmd/kubermatic-cluster-controller/main.go
> +	for dc := range clientcmdConfig.Contexts {
This is very good as I first thought it was a `context.Context` being passed on. :+1:

2017-10-02 13:05 UTC, metalmatze commented on api/cmd/kubermatic-cluster-controller/main.go
> +		go ctrl.Run(*workerCount, stop)
IMHO it's better to pass a cancellable context to `ctrl.Run`.

2017-10-02 13:05 UTC, metalmatze commented on api/pkg/controller/types.go
> +type Interface interface {
hmm. Do you _really_ want to call this `Interface`? It doesn't say anything and neither does `controller.Interface` say anything. :thinking:

2017-10-02 13:05 UTC, metalmatze commented on api/pkg/controller/types.go
> +type Interface interface {
Maybe something like `controller.Stopper`. After digging around the code I'd propose something like `controller.GroupRunStopper`.

2017-10-02 13:05 UTC, metalmatze commented on api/pkg/controller/types.go
> +	Run(workerCount int, stopCh chan struct{})
Things like this (`workerCount`) which are only used in the Run method are best passed along with the `func`, because it only affects this one func when being executed. This doesn't need to be shared.

2017-10-02 13:08 UTC, metalmatze commented
I think your Gogland imported the wrong path in `api/pkg/handler/upgrade_test.go`.
It should probably be 
```diff
- "github.com/blang/semver"
+ "github.com/Masterminds/semver"
```

2017-10-02 13:10 UTC, mrIncompetent commented on api/cmd/kubermatic-cluster-controller/main.go
> +	stop := make(chan struct{})
Its the way, all kubernetes informers work :(
Context would be nice, but k8s-informers only accept a channel of structs...

2017-10-02 13:12 UTC, metalmatze commented on api/cmd/kubermatic-cluster-controller/main.go
> +	stop := make(chan struct{})
Then let's keep it this way. Probably because it's rather new :blush:

2017-10-02 13:13 UTC, mrIncompetent commented on api/cmd/kubermatic-cluster-controller/main.go
> +		go ctrl.Run(*workerCount, stop)
Its the way, all kubernetes informers work :(
Context would be nice, but k8s-informers only accept a channel of structs...

Than channel is beeing passed through to all k8s informers

2017-10-02 13:19 UTC, mrIncompetent commented on api/pkg/controller/types.go
> +type Interface interface {
So it is meant to be the interface for a controller.
It was called Controller before, but as this is the controller package, it should have a different name.

It seems to be a practice also others use:
https://github.com/kubernetes/helm/blob/c7e2d186a5e10b87d0b1939431017d78ee610f23/pkg/helm/interface.go#L25

It kind of makes sense when you think of the resulting import from another package:
```
type mystruct {
   controller controller.Interface
}
```

In the end, i'm not fully sure what would be the cleanest way of handling this.

2017-10-02 13:34 UTC, metalmatze commented on api/pkg/controller/types.go
> +type Interface interface {
The interface doesn't care if the interface is implemented by a controller, a service, a api or whatever. The interface only cares about its details which is, as described in its comment: `started with Run and terminated by closing the stopCh.` That's all the interface cares about and what its name should describe.

2017-10-02 13:53 UTC, metalmatze approved these changes
LGTM

2017-10-02 14:15 UTC, merged