Cleanup Resources when deleting KubermaticConfigurations/Seeds
kubermatic/kubermatic pull request #4795
Opened 2019-12-02 17:49 UTC by xrstf

**What this PR does / why we need it**:
This PR uses finalizers to ensure that cluster-wide resources are removed and Seeds are cleaned up when a KubermaticConfiguration or Seed is removed.

* `KubermaticConfigurations` inside master clusters have a new finalizer from the operator so that it can delete the webhook and ClusterRoleBinding.
* `Seeds` inside the seed cluster (!) have an identical finalizer so that the seed-operator-controller can cleanup the seed cluster.
* `Seeds` inside the master cluster now also get a finalizer from the `seed-sync` controller. This ensures that this controller can propagate the deletion into the seed cluster.

The workflow for deleting a Seed is simple:

1. Delete the Seed CR inside the master cluster.

(Deleting the Seed CR inside the seed cluster will make the operator clean up the seed cluster, but since the seed-sync controller will immediately re-create the Seed CR, it's pointless unless you want to force-reconcile a seed cluster.)

It works like this for separate master/seed clusters:

1. Master-Seed CR has a seed-sync-cleanup finalizer.
2. This triggers the seed-sync controller to delete the Seed-Seed CR.
3. This triggers the operator to cleanup the seed cluster. Afterwards it removes its finalizer.
4. If this happened quicker than 30s, the Delete operation from step 2 succeeds and the seed-sync controller removes the finalizer on the Master-Seed CR. If this is slower, the controller errors out and retries later to delete again.
5. The Master-Seed is removed by the apiserver.

For shared master/seed clusters this is a bit more complex:

1. Seed CR has a seed-sync-cleanup *and* a operator-seed-cleanup finalizers.
2. Upon deletion, both controllers race to cleanup their finalizers:
   1. The seed-sync controller will fetch the Seed CR and notice that Master=Seed by comparing the UIDs. This makes it not perform an indefinitely blocking Delete op, but instead it will just remove its finalizer.
   2. The operator will simply cleanup as usual and then remove its finalizer.
3. It's not important in which order the two steps above happen. Afterwards, both finalizers are gone.
5. The Master-Seed is removed by the apiserver.

There are some known limitations:

1. Deleting the kubeconfig-secret for a Seed will make the cleanup impossible. In this case the seed-sync controllers errors indefinitely. It's assumed that cluster admins will either fix the missing kubeconfig to allow cleanup or remove the finalizer because they nuked the seed cluster already. This could be tackled by making the kubeconfig Secret *own* the Seed CR, but that seems weird and is out of scope for this PR.
2. Deleting a KubermaticConfiguration or a Kubermatic namespace will obviously kill controllers and the operator and make Seed deletion stuck. But I think the procedure to first delete all Seeds and then the KubermaticConfiguration is fine.

**Which issue(s) this PR fixes**:
Fixes #4755 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

2019-12-03 16:54 UTC, xrstf commented on api/pkg/controller/seed-sync/reconciler.go
> +		return err
I chose to sneakily re-use the common package from the operator. Not sure if we want to move the PatchSeed and PatchKubermaticConfiguration into the `controller/util` package.

2019-12-03 16:54 UTC, xrstf commented
/assign @kron4eg

2019-12-04 08:39 UTC, xrstf commented
/retest

2019-12-04 15:18 UTC, kron4eg requested changes
Aside from small nit, looks good

2019-12-04 15:18 UTC, kron4eg commented on api/pkg/controller/operator/master/reconciler.go
> +	if err := common.PatchKubermaticConfiguration(r, config, func(cfg *operatorv1alpha1.KubermaticConfiguration) error {
functions like PatchKubermaticConfiguration and PatchSeed shouldn't exists for the sole reason to provide concrete type in the callback, especially given that callback you've provided don't take any advantage of the concrete type.

Please converge them to the runtime.Object or metav1.Object interfaces.

2019-12-04 15:51 UTC, kron4eg commented on api/pkg/controller/operator/master/reconciler.go
> +	if sets.NewString(config.Finalizers...).Has(common.CleanupFinalizer) {
btw, we have api/pkg/kubernetes.HasAnyFinalizer() which can be used interchangeably here

2019-12-04 15:59 UTC, xrstf commented on api/pkg/controller/operator/master/reconciler.go
> +	if err := common.PatchKubermaticConfiguration(r, config, func(cfg *operatorv1alpha1.KubermaticConfiguration) error {
Neither runtime Objects nor metav1 Objects were usable because one didn't have a DeepCopy and the other wasn't compatible with the Finalizer helper functions. So I just removed the helpers alltogether.

2019-12-04 16:10 UTC, kron4eg approved these changes
/lgtm
/approve

2019-12-04 17:01 UTC, xrstf commented
/hold

This makes clusters get stuck on CI.

2019-12-04 20:32 UTC, xrstf commented
/retest

2019-12-04 21:26 UTC, xrstf commented
/hold cancel

2019-12-05 13:10 UTC, alvaroaleman approved these changes
/lgtm
/approve

2019-12-05 14:25 UTC, merged