Fix patch requests send from go-kubermatic client
kubermatic/kubermatic pull request #4917
Opened 2019-12-23 11:17 UTC by mfranczy

**What this PR does / why we need it**:
Currently, the generated go-kubermatic client is not able to send an appropriate PATCH request to the API server, it's because of the `Patch` field type which is `[]byte` ([example](https://github.com/kubermatic/kubermatic/pull/4917/files#diff-2ace21458585d6d9d5e1ce87136e0fdcL991)) instead it should be `json.RawMessage`. 

`[]byte` representation in JSON is base64 so the API server returns bad request code when receiving such a payload

Additionally, the go-swagger pkg must be upgraded to handle json.RawMessage type.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2019-12-23 11:43 UTC, mfranczy commented on api/pkg/handler/v1/cluster/kubeconfig.go
> +	cookieNonceValue string    `json:"-"`
the new swagger version adds to spec unexported params it seems I will have to fix it there

2020-01-07 11:17 UTC, mfranczy commented on api/pkg/handler/v1/cluster/kubeconfig.go
> +	cookieNonceValue string    `json:"-"`
I created a new issue with PR, https://github.com/go-swagger/go-swagger/issues/2164, let's wait for their response

2020-01-07 11:17 UTC, mfranczy commented
/hold

2020-01-15 12:34 UTC, mfranczy commented
`pre-kubermatic-verify` job fails because of https://github.com/go-swagger/go-swagger/issues/2066, shortly I will create a PR with fix there.

2020-02-06 11:15 UTC, zreigz requested changes
You need to apply changes (new parameter names) for this file: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/test/e2e/api/runner.go
Then tests should pass

2020-02-06 11:18 UTC, zreigz commented
I don't see any version changes in `Gopkg.toml` only in autogenerated `Gopkg.lock` file. The command `dep ensure` can override the changes in my opinion

2020-02-06 11:23 UTC, mfranczy commented
@zreigz thanks for review

> You need to apply changes (new parameter names) for this file: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/test/e2e/api/runner.go
Then tests should pass

yeah I am fixing this now, I see there are more problems with naming.

2020-02-06 11:36 UTC, mfranczy commented
> I don't see any version changes in Gopkg.toml only in autogenerated Gopkg.lock file. The command dep ensure can override the changes in my opinion

I see we use go-swagger master branch that's why Gokpg.toml didn't change, however, I will lock to v0.22.0 version if go-swagger folks will agree to backport this PR https://github.com/go-swagger/go-swagger/pull/2209

2020-02-06 15:02 UTC, mfranczy commented on api/pkg/api/v1/types.go
> +// swagger:model ClusterResource
This had to be renamed to `ClusterResource` we have a name collision with `cmdv1.Config` (Kubeconfig) it contains `Cluster` field (it comes from vendor pkg so I can do nothing about that).

However from the client usage perspective nothing changes, we can still use `model.Cluster`.

2020-02-06 15:12 UTC, zreigz commented
nice work, you need to run `update-swagger` and `gen-api-client` again

2020-02-06 15:25 UTC, mfranczy commented on api/pkg/api/v1/types.go
> +// swagger:model ClusterResource
damn it, now swagger generator is inconsistent with results (similar as spec in the past).... The above comment is not valid. Sometimes generator produces output for `ClusterResource` and sometimes for `Cluster` from `cmdv1.Config`.

2020-02-06 15:28 UTC, mfranczy commented
@zreigz thanks, `gen-api-client` won't work because of https://github.com/kubermatic/kubermatic/pull/4917#discussion_r375900556, swagger has so many bugs, it doesn't know how to handle embedded models. I will try to find a way how to fix that in our code.

2020-02-06 15:45 UTC, zreigz commented
> @zreigz thanks, `gen-api-client` won't work because of [#4917 (comment)](https://github.com/kubermatic/kubermatic/pull/4917#discussion_r375900556), swagger has so many bugs, it doesn't know how to handle embedded models. I will try to find a way how to fix that in our code.

Ach, OK. Thanks. Tests are passing now :+1:

2020-02-06 16:50 UTC, mfranczy commented
@zreigz I had to change `Kubeconfig` to be swagger `response` not `model` (https://github.com/kubermatic/kubermatic/pull/4917/commits/d61ddecf2a22a0679731d9392b8aa3e4a2f6c50a#diff-7f8b07edb0cdb9a092e601081f5ddc8bR501) I think it's even better because it's used only as a response type for `api/v1/kubeconfig` (https://github.com/kubermatic/kubermatic/blob/master/api/pkg/handler/routes_v1_optional.go#L35) and sadly it cannot be embedded struct.

Let's try to re-run tests a few times just to be sure that go-swagger does not surprise us, locally after a few iterations of `swagger generate` I had consistent results.

2020-02-06 18:38 UTC, mfranczy commented
/retest

2020-02-07 10:48 UTC, mfranczy commented
/retest

2020-02-07 10:49 UTC, mfranczy commented
/test all

2020-02-10 08:18 UTC, zreigz commented
everything works fine, thanks for this PR :+1:

2020-02-10 08:19 UTC, zreigz commented
/lgtm
/approve

2020-02-10 08:45 UTC, mfranczy commented
/assign @xmudrii

2020-02-10 14:24 UTC, kron4eg commented on api/cmd/kubermatic-api/swagger.json
> -              "type": "array",
Isn't such change in API is a breaking change?

2020-02-10 15:06 UTC, mfranczy commented on api/cmd/kubermatic-api/swagger.json
> -              "type": "array",
It's not. Before `Patch` fields were of `[]byte` type, they should be `json.RawMessage` (https://github.com/kubermatic/kubermatic/pull/4917/commits/c36b8aa64cb624e2b0489dd862588433d3340c39#diff-a57f88db269544b698f3e8b0e675c4d2L73) which is basically the `[]byte` type with Marshal and Unmarshal functions. So the type is still the same for `Patch` fields.

However, when it comes to type change in swagger.json, `json.RawMessage` for go-swagger is an `object`, for `[]byte` is `[]uint8`, so after that change, finally, the generated kubermatic client will be able to send an appropriate payload which is not base64 encoded (`[]byte` in json is base64 encoded). 

That change from `[]uint8` to `object` in swagger is very demaned and it's not a breaking change as it didn't work before.

2020-02-12 13:25 UTC, mfranczy commented
I had to rebase the branch against master, so please take a look again after all tests are green

2020-02-12 13:26 UTC, kron4eg commented
/lgtm

2020-02-12 13:55 UTC, zreigz commented
/lgtm
/approve

2020-02-12 14:41 UTC, kron4eg commented
/approve

2020-02-12 14:54 UTC, mfranczy commented
/hold cancel

2020-02-12 15:07 UTC, mfranczy commented
in the meantime, some other PR has been merged into master, I had to rebase and regenerate the client again

2020-02-12 15:11 UTC, kron4eg commented
/lgtm

2020-02-12 16:18 UTC, zreigz commented
/retest

2020-02-12 17:35 UTC, merged