Remove legacy endpoints: `RegisterV1Legacy`
kubermatic/kubermatic pull request #4951
Opened 2020-01-13 06:32 UTC by nikhita

Fixes https://github.com/kubermatic/kubermatic/issues/4575

/kind cleanup
/assign @zreigz 

**Does this PR introduce a user-facing change?**:

```release-note
The legacy endpoint is removed from the Kubermatic API.
```

2020-01-13 06:33 UTC, nikhita commented
/hold

For confirmation regarding the deprecation

2020-01-13 18:57 UTC, zreigz commented
@maciaszczykm If I remember some endpoints are still used by the UI

2020-01-14 08:06 UTC, maciaszczykm commented on api/cmd/kubermatic-api/swagger.json
> -      "delete": {
This endpoint is still used by the UI. I think it will stay for longer time as deleting single node from node deployment can be useful sometimes.

2020-01-14 08:10 UTC, maciaszczykm commented on api/cmd/kubermatic-api/swagger.json
> -      "delete": {
```
  deleteNode(projectID: string, clusterID: string, datacenter: string, nodeID: string): Observable<any> {
    const url = `${this._restRoot}/projects/${projectID}/dc/${datacenter}/clusters/${clusterID}/nodes/${nodeID}`;
    return this._http.delete(url);
  }
```

2020-01-14 08:12 UTC, maciaszczykm commented on api/cmd/kubermatic-api/swagger.json
> -      "get": {
```
  nodes(projectID: string, clusterID: string, datacenter: string): Observable<NodeEntity[]> {
    const url = `${this._restRoot}/projects/${projectID}/dc/${datacenter}/clusters/${
        clusterID}/nodes?hideInitialConditions=true`;
    return this._http.get<NodeEntity[]>(url).pipe(catchError(() => of<NodeEntity[]>()));
  }
```

This is still used to display nodes that do not belong to any of the node deployments. The question is if we want to get rid of that list or not.

2020-01-14 08:15 UTC, maciaszczykm requested changes
Some of the endpoints are still used by UI, please verify it. Also, you can start API and UI locally and do some tests too.

2020-03-24 08:35 UTC, closed without merging