Add error handler + Refactoring 🙃
kubermatic/kubermatic pull request #497
Opened 2017-10-10 14:19 UTC by lbb

2017-10-10 14:21 UTC, metalmatze submitted a review, later dismissed
LGTM

2017-10-11 12:53 UTC, mrIncompetent requested changes

2017-10-11 12:53 UTC, mrIncompetent commented on api/pkg/handler/user.go
> +		return provider.User{}, errors.NewNotAuthorized()
A function called GetUser should not return a NewNotAuthorized error. 
The caller needs to decide if the returned user is sufficient to proceed or not

To make code simple, we should probably only have one return: `provider.User`
If `!ok` really happens, we should panic. As this should not happen AT ALL. We have a auth-middleware which is responsible to set the user. If a handler without the auth-middleware calls this function, something is really fucked.
As this function then becomes very dependent on the authenticator, maybe we should move it into that package?

2017-10-11 13:05 UTC, mrIncompetent commented on api/pkg/handler/authentication.go
> +	Signer() endpoint.Middleware
Why is this called Signer?

2017-10-11 13:20 UTC, guusvw commented on api/pkg/handler/user.go
> +		return provider.User{}, errors.NewNotAuthorized()
I totally agree with @mrIncompetent. 
`errors.NewNotAuthorized()` is the wrong error & and I also would return only one value, if you want to return two values, return in this case as second value a boolean, so you could use `ok`.

2017-10-11 13:20 UTC, guusvw commented on api/pkg/handler/user.go
> +		return provider.User{}, errors.NewNotAuthorized()
BTW why is `UserContextKey` exported?

2017-10-11 13:22 UTC, guusvw submitted a review, later dismissed

2017-10-11 13:22 UTC, guusvw commented on api/pkg/handler/authentication.go
> +func (o openIDAuthenticator) Signer() endpoint.Middleware {
Here is a comment missing ;)

2017-10-11 13:31 UTC, guusvw commented on api/pkg/handler/authentication.go
> +			// This should only be called once!
The go compiler can't compile comments 

https://godoc.org/sync#Once

2017-10-11 13:33 UTC, lbb commented on api/pkg/handler/authentication.go
> +			// This should only be called once!
kek

2017-10-11 13:46 UTC, mrIncompetent requested changes

2017-10-11 13:46 UTC, mrIncompetent commented on api/pkg/handler/auth/user.go
> +		panic("User isn't authenticated!")
Bad message. 
Maybe: `invalid user found in context`
Additionally we should log the case telling:
`GetUser got called with an invalid user in the context. Validate that the authentication Verifier ran before calling this function`
@guusvw

2017-10-11 13:46 UTC, mrIncompetent commented on api/pkg/handler/auth/authentication.go
> +	"github.com/kubermatic/kubermatic/api/pkg/provider"
I think the only reason why we import this package is due to the user struct.
Should we rather move it into this package?

2017-10-11 14:46 UTC, lbb commented on api/pkg/handler/auth/authentication.go
> +	"github.com/kubermatic/kubermatic/api/pkg/provider"
Good point, we should move the user to the auth package

2017-10-11 14:56 UTC, lbb commented on api/pkg/handler/auth/authentication.go
> +	"github.com/kubermatic/kubermatic/api/pkg/provider"
But when we do this we should think about moving the whole package to an other location such as `pkg/{,util}/auth` because importing a package from `pkg/handler/...`, that being said we should also move the handler errors package.

2017-10-11 14:58 UTC, mrIncompetent commented on api/pkg/handler/auth/authentication.go
> +	"github.com/kubermatic/kubermatic/api/pkg/provider"
Why should we move it outside of handler?
Is stuff from there used outside of the handler package?

2017-10-11 15:00 UTC, lbb commented on api/pkg/handler/auth/authentication.go
> +	"github.com/kubermatic/kubermatic/api/pkg/provider"
Yes, inside `pkg/provider/...`

2017-10-11 15:04 UTC, mrIncompetent commented on api/pkg/handler/auth/authentication.go
> +	"github.com/kubermatic/kubermatic/api/pkg/provider"
![giphy-downsized](https://user-images.githubusercontent.com/14090308/31449113-5d3550d4-aea6-11e7-9acf-f6f2c1d644b2.gif)

2017-10-11 15:06 UTC, lbb commented on api/pkg/handler/auth/authentication.go
> +	"github.com/kubermatic/kubermatic/api/pkg/provider"
😂 Interpreting as a yes

2017-10-11 15:08 UTC, lbb commented on api/pkg/handler/auth/authentication.go
> +	"github.com/kubermatic/kubermatic/api/pkg/provider"
FYI it's going to go into `pkg/util/errors` and`pkg/util/auth` in apimachinery style

2017-10-11 16:28 UTC, mrIncompetent approved these changes

2017-10-11 16:28 UTC, mrIncompetent commented
:heart:

2017-10-11 16:29 UTC, lbb commented
@guusvw Okay? Seems outdated

2017-10-11 16:30 UTC, merged