Generate Kubermatic Chart static files
kubermatic/kubermatic pull request #5080
Opened 2020-02-12 13:49 UTC by xrstf

**What this PR does / why we need it**:
Keeping our helper manifests up to date in two places is tedious and easy to fuck up. This PR makes it so that the Operator is the single source of truth and the manifests inside the Kubermatic Helm chart are merely derived from it.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

2020-02-12 17:13 UTC, xrstf commented
/retest

2020-02-12 17:56 UTC, xrstf commented on config/kubermatic/static/master/accessible-addons.yaml
> +- node-exporter
This has to be a map at the top level because Helm's fromYaml expects it.

2020-02-13 15:48 UTC, moadqassem requested changes

2020-02-13 15:48 UTC, moadqassem commented on api/codegen/kubermatic_operator/main.go
> +	"github.com/kubermatic/kubermatic/api/pkg/controller/operator/common"
Maybe a better import regrouping?

2020-02-13 15:48 UTC, moadqassem commented on api/codegen/kubermatic_operator/main.go
> +	markup, err := yaml.Marshal(map[string]interface{}{
Why an interface? `[]string` wouldn't be enough?

2020-02-13 15:48 UTC, moadqassem commented on api/codegen/kubermatic_operator/main.go
> +	container = strings.Join([]string{
What about using a buffer instead of using string joins?  it is more efficient and easier to read to be honest :)

2020-02-13 15:48 UTC, moadqassem commented on api/codegen/kubermatic_operator/main.go
> +// This application generates some manifests in the Kubermatic Helm chart
Can we maybe have a test for this bin functionality?

2020-02-13 15:48 UTC, moadqassem commented on api/codegen/kubermatic_operator/main.go
> +	"log"
Nit: What about using zap here since we already using in all kubermatic?

2020-02-13 15:48 UTC, moadqassem commented on api/codegen/kubermatic_operator/main.go
> +// This application generates some manifests in the Kubermatic Helm chart
Nit: In go package names shouldn't have underscores.

2020-02-13 16:08 UTC, xrstf commented on api/codegen/kubermatic_operator/main.go
> +	markup, err := yaml.Marshal(map[string]interface{}{
Because I need to output a map, see my other Github comment on the generated file.

2020-02-13 16:09 UTC, xrstf commented on api/codegen/kubermatic_operator/main.go
> +// This application generates some manifests in the Kubermatic Helm chart
What should that test, except for what the new verify-kubermatic-chart job already does?

2020-02-13 16:10 UTC, xrstf commented on api/codegen/kubermatic_operator/main.go
> +	"log"
Because it's just a codegen thingy and setting up zap requires more code than it's worth it, IMHO. This thing will never produce logs that are meant to be machine-readable anyway.

2020-02-13 16:10 UTC, xrstf commented on api/codegen/kubermatic_operator/main.go
> +// This application generates some manifests in the Kubermatic Helm chart
I was keeping the convention started with `openshift_versions` ;-)

2020-02-13 19:29 UTC, moadqassem commented on api/codegen/kubermatic_operator/main.go
> +// This application generates some manifests in the Kubermatic Helm chart
How Is it a convention? I mean having underscores in package name is not idiomatic in golang please check this https://blog.golang.org/package-names.

2020-02-13 19:40 UTC, moadqassem commented
/approve
/lgtm

2020-02-13 20:46 UTC, merged