Update Velero to v1.2.0
kubermatic/kubermatic pull request #5126
Opened 2020-02-20 19:29 UTC by youssefazrak

**What this PR does / why we need it**:
Update Velero to v1.2.0.
Minor upgrade. New features and bug fixes.

**Special notes for your reviewer**:
New mandatory flag `--plugins` to execute the `velero install` command that generates the CRDs.

**Documentation**:

Release note: https://github.com/vmware-tanzu/velero/releases/tag/v1.2.0

**Does this PR introduce a user-facing change?**:

```release-note
Update Velero to v1.2.0
```

2020-02-20 19:59 UTC, youssefazrak commented
@xrstf Christoph, I updated the "update.sh" file with the `--plugins` flag as it is now a mandatory flag with Velero 1.2.0. When I launch the script with bash the formating is wrong (same in version 1.1.0) so that might be due to a different output with a newer version of Velero. It seems the update.sh was written for Velero 1.0.0.
Also, do you know if this is a manually triggered file or is it triggered by ci when a cluster is deployed? I can't seem to find any mention of "update.sh".
Cheers!

2020-02-22 21:10 UTC, youssefazrak commented
@xrstf I changed the update.sh script to work with the latest version of yq (v3.1.1). Now I have a proper output.
Regarding the newly generated CRD.yaml file, I guess we can remove the new annotation `controller-gen.kubebuilder.io/version: (unknown)`?
Also I suppose we need to apply those manually? 
Cheers

2020-02-24 09:54 UTC, xrstf commented on config/backup/velero/values.yaml
> +    repository: velero/velero
Please always use a fully-qualified Docker image name, i.e. `docker.io/velero/velero`.

2020-02-24 09:56 UTC, xrstf commented
> Regarding the newly generated CRD.yaml file, I guess we can remove the new annotation controller-gen.kubebuilder.io/version: (unknown)?

Nah, why remove them? They offer no real value, but they also don't hurt.

> Also I suppose we need to apply those manually?

Helm applies the CRDs for us, like with everything in `templates/`.

2020-02-24 09:56 UTC, xrstf requested changes
minor

2020-02-24 12:39 UTC, youssefazrak commented on config/backup/velero/values.yaml
> +    repository: velero/velero
Updated

2020-02-24 14:15 UTC, xrstf commented
/lgtm

2020-02-24 14:22 UTC, merged