Updated alibaba instance types
kubermatic/kubermatic pull request #5169
Opened 2020-03-02 15:06 UTC by kgroschoff

**What this PR does / why we need it**:
Updated Alibaba instance types, as the old method seems not to filter response correctly by region. Therefor a lot of invalid instance types were in the list. 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2020-03-03 09:13 UTC, zreigz commented
/lgmt
/approve

2020-03-04 10:59 UTC, zreigz requested changes

2020-03-04 10:59 UTC, zreigz commented on api/pkg/handler/v1/provider/alibaba.go
> +		fmt.Print(apiv1.AlibabaInstanceTypeList{}, errors.New(http.StatusInternalServerError, fmt.Sprintf("failed to list instance types: %#v", err)))
should be return?

2020-03-04 10:59 UTC, zreigz commented on api/pkg/handler/v1/provider/alibaba.go
> +	recommendedInstanceFamilies := []string{"ecs.g6", "ecs.g5", "ecs.g5se", "ecs.g5ne", "ecs.ic5", "ecs.c6", "ecs.c5", "ecs.r6", "ecs.r5", "ecs.d1ne", "ecs.i2", "ecs.i2g", "ecs.hfc6", "ecs.hfg6", "ecs.h
Please use hash set for this: "k8s.io/apimachinery/pkg/util/sets"
```
recommendedInstanceFamilies := sets.NewString("ecs.g6", "ecs.g5", "ecs.g5se", "ecs.g5ne", "ecs.ic5", "ecs.c6", "ecs.c5", "ecs.r6", "ecs.r5", "ecs.d1ne", "ecs.i2", "ecs.i2g", "ecs.hfc6", "ecs.hfg6", "ecs.hfr6")
```
Then you can remove `isInList` method. `recommendedInstanceFamilies.Has(instType.InstanceTypeFamily)`

2020-03-04 10:59 UTC, zreigz commented on api/pkg/handler/v1/provider/alibaba.go
> +		fmt.Print(apiv1.AlibabaInstanceTypeList{}, errors.New(http.StatusInternalServerError, fmt.Sprintf("failed to list instance type families: %#v", err)))
return ?

2020-03-04 13:41 UTC, kgroschoff commented
/test pre-kubermatic-lint

2020-03-04 14:18 UTC, moadqassem commented on api/pkg/handler/v1/provider/alibaba.go
> +func listAlibabaInstanceTypes(ctx context.Context, seedsGetter provider.SeedsGetter, accessKeyID string, accessKeySecret string, region string) (apiv1.AlibabaInstanceTypeList, error) {
In this function the `seedsGetter` is not used or?

2020-03-04 14:18 UTC, moadqassem commented on api/pkg/handler/v1/provider/alibaba.go
> +	"k8s.io/apimachinery/pkg/util/sets"
can you please have better regrouping for the import paths? `"k8s.io/apimachinery/pkg/util/sets"` comes after `kubermatic` imports.

2020-03-04 14:18 UTC, moadqassem commented on api/pkg/handler/v1/provider/alibaba.go
> +		return nil, errors.New(http.StatusInternalServerError, fmt.Sprintf("failed to list instance type families: %#v", err))
Why formating the error message with `#` ?

2020-03-04 14:18 UTC, moadqassem commented on api/pkg/handler/v1/provider/alibaba.go
> +		return nil, errors.New(http.StatusInternalServerError, fmt.Sprintf("failed to list instance types: %#v", err))
Same goes here, Why formating the error message with `#` ?

2020-03-04 15:42 UTC, kgroschoff commented
Thanks @zreigz & @moadqassem, done.

2020-03-04 16:05 UTC, moadqassem commented
/approve
/lgtm

2020-03-04 18:34 UTC, merged