Add configurable default addon enforce option
kubermatic/kubermatic pull request #5193
Opened 2020-03-06 11:15 UTC by moelsayed

**What this PR does / why we need it**:
Add configurable default addon enforce option.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4979

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Add a configuration flag for seed-controller-manager to enforce default addons on userclusters. Enabled by default.
```

2020-03-06 13:16 UTC, moelsayed commented
/retest

2020-03-20 11:25 UTC, kron4eg requested changes
@moelsayed please see https://github.com/kubermatic/kubermatic/issues/4979#issuecomment-601651108

2020-04-15 08:52 UTC, kron4eg commented
/retest

2020-04-15 09:40 UTC, kron4eg reviewed
Looks good! Albeit left few minor comments.

2020-04-15 09:40 UTC, kron4eg commented on api/pkg/controller/seed-controller-manager/addon/addon_controller.go
> +		}
```suggestion
		// we check for this after the ClusterReconcileWrapper() call because otherwise the cluster would never reconcile since we always requeue
		result = &reconcile.Result{}
		if r.addonEnforceInterval != 0 { // addon enforce is enabled
			// All is well, requeue in addonEnforceInterval minutes. We do this to enforce default addons and prevent cluster admins from disabling them.
			result.RequeueAfter = time.Duration(r.addonEnforceInterval) * time.Minute
		}
```

2020-04-15 09:40 UTC, kron4eg commented on api/pkg/controller/seed-controller-manager/addon/addon_controller.go
> +	// while we enfornce the labeled ones
```suggestion
	// while we enforce the labeled ones
```

2020-04-15 09:40 UTC, kron4eg commented on api/pkg/controller/seed-controller-manager/addon/addon_controller.go
> +}
It's completely legal to read from uninitialized map (in case when it's empty or nil).
```suggestion
func hasEnsureResoucesLabel(addon *kubermaticv1.Addon) bool {
	return addon.Labels[addonEnsureLabelKey] == "true"
}
```

2020-04-15 11:25 UTC, moelsayed commented
/retest

2020-04-15 11:39 UTC, kron4eg approved these changes
/hold

@moadqassem PTAL too

2020-04-15 13:55 UTC, moadqassem commented on api/pkg/controller/seed-controller-manager/addon/addon_controller.go
> +func hasEnsureResoucesLabel(addon *kubermaticv1.Addon) bool {
typo hasEnsureResoucesLabel should be hasEnsureResourcesLabel

2020-04-15 13:55 UTC, moadqassem commented on api/pkg/controller/seed-controller-manager/addon/addon_controller.go
> +func hasEnsureResoucesLabel(addon *kubermaticv1.Addon) bool {
and does it really need to do this check, in a function instead of having it inline? I mean 1) it is an unexported function 2) it is only used one time.

2020-04-15 16:01 UTC, moelsayed commented on api/pkg/controller/seed-controller-manager/addon/addon_controller.go
> +func hasEnsureResoucesLabel(addon *kubermaticv1.Addon) bool {
Fixed the typo. I prefer to wrap it in a function because I do think it's more readable this way..

2020-04-16 07:44 UTC, moadqassem commented
/approve 
/lgtm

2020-04-16 08:24 UTC, kron4eg commented
/hold cancel

2020-04-16 08:25 UTC, merged

2020-05-18 12:15 UTC, multi-io commented
Shouldn't the addon installer controller also honour this setting for existing clusters? Ie. update the default addons in those clusters and update the label on them.

2020-10-02 09:03 UTC, xrstf commented
/cherrypick release/v2.13