migrate the RBAC controller to controller-runtime, part 1
kubermatic/kubermatic pull request #5274
Opened 2020-03-31 12:35 UTC by kdomanski

```release-note
NONE
```

"Part 1", because it is intertwined with some code from the resource controller, which also needs migration. After the resource controller has been migrated as well, the cleanup of legacy cluster providers will be possible.

2020-04-17 01:30 UTC, kdomanski commented
/retest

2020-04-17 11:41 UTC, kdomanski commented
/test pre-kubermatic-verify

2020-04-17 13:40 UTC, kdomanski commented
/retest

2020-04-19 18:18 UTC, kdomanski commented
/assign @zreigz @moadqassem

2020-04-20 06:35 UTC, zreigz requested changes
some small comments. Looks good and seems to work fine. I've tested it locally and I didn't find any problem so far

2020-04-20 06:35 UTC, zreigz commented on api/pkg/controller/master-controller-manager/rbac/sync_project.go
> +					err := ensureClusterRBACRoleBindingForResource(
you can also add `return` statement if err != nil

2020-04-20 06:35 UTC, zreigz commented on api/pkg/controller/master-controller-manager/rbac/sync_project.go
> +				err := ensureClusterRBACRoleForResource(c.ctx, c.client, groupPrefix, projectResource.gvr.Resource, projectResource.kind)
you can also add return statement if err != nil
```
if err := ensureClusterRBACRoleForResource(c.ctx, c.client, groupPrefix, projectResource.gvr.Resource, projectResource.kind); err != nil {
return err
}
```

2020-04-20 06:35 UTC, zreigz commented on api/pkg/controller/master-controller-manager/rbac/sync_project.go
> +					err := ensureRBACRoleForResource(
you can also add return statement if err != nil

2020-04-20 06:35 UTC, zreigz commented on api/pkg/controller/master-controller-manager/rbac/sync_project.go
> +					err := ensureRBACRoleBindingForResource(
you can also add return statement if err != nil

2020-04-20 06:35 UTC, zreigz commented on api/pkg/controller/master-controller-manager/rbac/sync_project.go
> +				err := ensureRBACRoleBindingForResource(
you can also add return statement if err != nil

2020-04-20 06:35 UTC, zreigz commented on api/pkg/controller/master-controller-manager/rbac/sync_project.go
> +				err := cleanUpClusterRBACRoleBindingFor(c.ctx, c.client, groupName, projectResource.gvr.Resource)
you can also add return statement if err != nil

2020-04-20 09:20 UTC, kdomanski commented on api/pkg/controller/master-controller-manager/rbac/sync_project.go
> +					err := ensureClusterRBACRoleBindingForResource(
Then it looks like this:
![image](https://user-images.githubusercontent.com/993296/79735494-aaf67400-82f8-11ea-9c66-b178d0daaa86.png)
And the logic flow is difficult to see. Same with the remaining cases.

One could reformat the `ensureClusterRBACRoleBindingForResource` to have all arguments in one line, but in most other cases that's impractical, because the line would be too long.

2020-04-20 09:40 UTC, zreigz commented
/lgtm
/approve

2020-04-20 12:26 UTC, kdomanski commented
/retest

2020-04-20 18:37 UTC, merged