Add proxy support to the Kubermatic Operator
kubermatic/kubermatic pull request #5304
Opened 2020-04-14 13:58 UTC by xrstf

**What this PR does / why we need it**:
This PR gives the operator the options to configure Kubermatic to use a proxy for HTTP/HTTPS communication. The operator itself naturally does not use the proxy settings (though it would be fun if the operator reconciled itself :D ), but since it does not talk to the outside world, it's okay. Otherwise the proper place to put the proxy settings would be the Kubermatic Installer.

The idea for the default NoProxy value and appending the user-supplied values is taken from KubeOne. These guys usually know what they're doing.

Disclaimer: I have no way to test this.

**Which issue(s) this PR fixes**:
Fixes #4783

**Documentation**:
This is a new feature for the unreleased operator, the generated docs already show how to configure the proxy.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

2020-04-20 11:41 UTC, toschneck requested changes
Improve of some defaults needed

2020-04-20 11:41 UTC, toschneck commented on docs/zz_generated.kubermaticConfiguration.yaml
> +    # "127.0.0.1/8", "localhost", ".local", "kubernetes", ".default", ".svc"
some code in the machinecontroller query `webhook. ....cluster.local.`.  This not match somehow to `.local` so we would need add `.local.` as well

2020-04-20 11:41 UTC, toschneck commented on api/pkg/controller/operator/common/defaults.go
> +	DefaultNoProxy = "127.0.0.1/8,localhost,.local,kubernetes,.default,.svc"
some code in the machinecontroller query `webhook. ....cluster.local.`.  This not match somehow to `.local` so we would need add `.local.` as well

2020-04-21 14:09 UTC, xrstf commented on api/pkg/controller/operator/common/defaults.go
> +	DefaultNoProxy = "127.0.0.1/8,localhost,.local,kubernetes,.default,.svc"
Fixed.

2020-04-21 18:39 UTC, toschneck commented
/lgtm
/assign @xrstf

2020-04-21 18:40 UTC, toschneck approved these changes

2020-04-21 21:06 UTC, merged

2020-05-05 11:53 UTC, kdomanski commented
/cherry-pick release/v2.14