add Flatcar Linux to the API
kubermatic/kubermatic pull request #5368
Opened 2020-05-05 15:47 UTC by kdomanski

```release-note
Added Flatcar Linux
```

2020-05-06 15:08 UTC, kdomanski commented
/assign @moadqassem 
/assign @zreigz

2020-05-07 00:17 UTC, moadqassem requested changes

2020-05-07 00:17 UTC, moadqassem commented on api/cmd/conformance-tests/scenarios_aws.go
> +		// CoreOS
Should be Flatcar instead of `CoreOS`

2020-05-07 00:17 UTC, moadqassem commented on api/cmd/kubermatic-api/swagger.json
> +          "description": "disable container linux auto-update feature",
instead of `container linux` should be `flatcar` ;)

2020-05-07 00:17 UTC, moadqassem commented on api/pkg/api/v1/types.go
> +	// disable container linux auto-update feature
Same goes here `flatcar` instead of `container linux`

2020-05-07 00:17 UTC, moadqassem commented on api/cmd/conformance-tests/runner.go
> +		case osSpec.Flatcar != nil:
Please add the flatcar os to the `getOSNameFromSpec` method:
https://github.com/kubermatic/kubermatic/blob/master/api/cmd/conformance-tests/os.go#L7

2020-05-07 00:17 UTC, moadqassem commented on .prow.yaml
> +        - name: EXCLUDE_DISTRIBUTIONS
Actually this is not needed as we have this env var `EXCLUDE_DISTRIBUTIONS `: https://github.com/kubermatic/kubermatic/blob/master/api/hack/ci/ci-run-conformance-tester.sh#L10

2020-05-07 00:17 UTC, moadqassem commented on .prow.yaml
> +        - name: EXCLUDE_DISTRIBUTIONS
Also would be cool to add those in our offline tests for consistency :) 
https://github.com/kubermatic/kubermatic/blob/master/api/hack/ci/ci-run-offline-test.sh#L256

2020-05-07 00:17 UTC, moadqassem commented on api/pkg/api/v1/types.go
> +type FlatcarSpec struct {
This also should be added to the api for the `node_labeler`: 
https://github.com/kubermatic/kubermatic/blob/master/api/pkg/controller/user-cluster-controller-manager/node-labeler/api/api.go#L20

2020-05-07 00:20 UTC, moadqassem commented
@kdomanski Can you please add the flatcar ssh username for our supported cloud provider: 
https://github.com/kubermatic/kubermatic/blob/master/api/pkg/machine/util.go#L10

2020-05-07 14:13 UTC, kdomanski commented on .prow.yaml
> +        - name: EXCLUDE_DISTRIBUTIONS
Implicit is better than explicit and I don't really understand the logic of skipping the setting in a few particular cases without comment because 2 scripts down there is a default value. If anything, we should remove the default values from the script to avoid surprises.

2020-05-07 14:35 UTC, kdomanski commented
/test pre-kubermatic-e2e-aws-flatcar-1.18

2020-05-08 08:39 UTC, kdomanski commented
/retest

2020-05-08 08:40 UTC, kdomanski commented on api/cmd/conformance-tests/scenarios_aws.go
> +		// CoreOS
Fixed

2020-05-08 08:40 UTC, kdomanski commented on api/cmd/kubermatic-api/swagger.json
> +          "description": "disable container linux auto-update feature",
fixed

2020-05-08 08:40 UTC, kdomanski commented on api/pkg/api/v1/types.go
> +	// disable container linux auto-update feature
fixed

2020-05-08 08:41 UTC, kdomanski commented on api/cmd/conformance-tests/runner.go
> +		case osSpec.Flatcar != nil:
done

2020-05-08 08:41 UTC, kdomanski commented on api/pkg/api/v1/types.go
> +type FlatcarSpec struct {
done

2020-05-08 08:53 UTC, moadqassem commented on api/pkg/controller/user-cluster-controller-manager/node-labeler/api/api.go
> +	// FlatcarLabelValue is the value of the label for RHEL
Should be `FlatcarLabelValue is the value of the label for Flatcar` not `RHEL` ;)

2020-05-08 12:23 UTC, kdomanski commented on api/pkg/controller/user-cluster-controller-manager/node-labeler/api/api.go
> +	// FlatcarLabelValue is the value of the label for RHEL
Fixed

2020-05-08 13:33 UTC, moadqassem commented
/retest

2020-05-11 14:49 UTC, kdomanski commented
/hold
@zreigz could someone from your team take a look as well?

2020-05-11 14:49 UTC, moadqassem commented
/lgtm

2020-05-13 12:45 UTC, kdomanski commented
/hold cancel

2020-05-14 05:59 UTC, zreigz commented
/approve

2020-05-14 09:06 UTC, kdomanski commented
/test pre-kubermatic-e2e-operator

2020-05-14 10:39 UTC, merged

2020-06-03 13:56 UTC, kdomanski commented
/cherry-pick release/v2.14