Switch CoreDNS from addon to a user-cluster-controller-manager resource
kubermatic/kubermatic pull request #5370
Opened 2020-05-06 07:27 UTC by moelsayed

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes-partially #3372

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Kubedns is no longer a manifest addon. 
```

2020-05-06 09:16 UTC, moelsayed commented
/retest

2020-05-06 10:48 UTC, moelsayed commented
/retest

2020-05-06 11:00 UTC, xrstf commented on api/pkg/test/e2e/api/runner.go
> +			time.Sleep(6 * time.Second)
It might have been better to increase the number of attempts rather than the interval.

2020-05-06 11:40 UTC, xrstf commented on api/pkg/controller/seed-controller-manager/addon/addon_controller.go
> +		if strings.Contains(err.Error(), "no such file or directory") { // if the manifest is already deleted, that's ok
Please return a dedicated error instead of asserting the string form on an error.

2020-05-06 11:46 UTC, xrstf commented on api/pkg/controller/user-cluster-controller-manager/resources/resources/core-dns/deployment.go
> +						map[string]string{"k8s-app": "kube-dns", "kubermatic-addon": "dns"}),
Please use the modern recommended labels https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/ and do not use the word "kubermatic" anywhere a user could see it. Nothing inside a user cluster must hint at Kubermatic.

2020-05-06 11:47 UTC, xrstf commented on api/pkg/controller/user-cluster-controller-manager/resources/resources/core-dns/service.go
> +			"kubernetes.io/name":            "KubeDNS",
`app.kubernetes.io/name` is more consistent :)

2020-05-06 11:48 UTC, xrstf commented on api/pkg/controller/user-cluster-controller-manager/resources/resources/core-dns/serviceaccount.go
> +			sa.Namespace = metav1.NamespaceSystem
FYI, both lines are redundant. Name and namespace are always set by the reconciling library.

2020-05-06 11:49 UTC, xrstf commented on api/pkg/resources/resources.go
> +
Why not have these in the new `coredns` package?

2020-05-06 11:49 UTC, moadqassem commented on api/pkg/controller/seed-controller-manager/addon/addon_controller.go
> +		if strings.Contains(err.Error(), "no such file or directory") { // if the manifest is already deleted, that's ok
maybe he can use os.IsNotExist instead if a dedicated error ;)

2020-05-06 11:51 UTC, xrstf requested changes
Some minor things.

2020-05-06 11:54 UTC, moadqassem commented on api/hack/run-userclustercontroller.sh
> +if [ -z "${OWNER_EMAIL:-}" ]
There is already a check for this in the main.go file:
https://github.com/kubermatic/kubermatic/blob/master/api/cmd/user-cluster-controller-manager/main.go#L100-L102

2020-05-07 02:05 UTC, moelsayed commented on api/pkg/controller/user-cluster-controller-manager/resources/resources/core-dns/deployment.go
> +						map[string]string{"k8s-app": "kube-dns", "kubermatic-addon": "dns"}),
We actually ensure that particular "kubermatic" label on all addon resources: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/controller/seed-controller-manager/addon/addon_controller.go#L354, do we want to stop doing that everywhere?

2020-05-07 02:09 UTC, moelsayed commented on api/pkg/resources/resources.go
> +
I would prefer that as well, but all the resources-related const's are in this file. Moved them here for consistency.

2020-05-07 02:16 UTC, moelsayed commented on api/hack/run-userclustercontroller.sh
> +if [ -z "${OWNER_EMAIL:-}" ]
That's true, however. It's not currently possible to pass it to the script through an environment variable, you actually need to edit the script to set the value. So, I added the check to inform the user with the environment variable name.

2020-05-07 11:00 UTC, xrstf commented on api/pkg/controller/user-cluster-controller-manager/resources/resources/core-dns/deployment.go
> +						map[string]string{"k8s-app": "kube-dns", "kubermatic-addon": "dns"}),
That is genuinely surprising me, cause I can remember the talks about whitelabelling. But since you didn't make it worse, 👍  ;-)

2020-05-12 09:07 UTC, moadqassem commented
/lgtm

2020-05-12 09:52 UTC, moelsayed commented
/retest

2020-05-13 05:06 UTC, moelsayed commented
/retest

2020-05-13 08:52 UTC, moadqassem commented
/lgtm

2020-05-13 09:52 UTC, moelsayed commented
/retest

2020-05-13 09:54 UTC, merged