Add node-local-dns-cache to user-cluster-controller-manager
kubermatic/kubermatic pull request #5387
Opened 2020-05-08 13:22 UTC by moelsayed

**What this PR does / why we need it**:
Adds node-local-dns-cache to user-cluster-controller-manager
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3372

**Special notes for your reviewer**:
The labels set are different from the ones on the coredns resources. But, they are the same as the ones currently deployed by the addon template. Once this is merged I will update them both to standard labels. 
**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
local-node-dns-cache is no longer a manifest addon. 
```

2020-05-13 19:17 UTC, xrstf commented on api/pkg/controller/user-cluster-controller-manager/resources/resources/node-local-dns/configmap.go
> +	reconcilModeValue   = "Reconcile"
reconcil**e**ModeValue

2020-05-13 19:19 UTC, xrstf commented on api/pkg/controller/user-cluster-controller-manager/resources/resources/node-local-dns/configmap.go
> +			cm.Labels[addonManagerModeKey] = reconcilModeValue
What do we need this label for? The resource is not managed by the addon controller anymore, is it?

2020-05-13 19:20 UTC, xrstf requested changes
Feedback

2020-05-20 13:17 UTC, moelsayed commented on api/pkg/controller/user-cluster-controller-manager/resources/resources/node-local-dns/configmap.go
> +			cm.Labels[addonManagerModeKey] = reconcilModeValue
it's related to k8s addon manager, not k8c's. It's in the original manifests, so I kept it around. Once this is merged, I will make a separate PR to clean and unify labels for all addons.

2020-05-20 19:17 UTC, moelsayed commented
/retest

2020-06-03 12:06 UTC, moelsayed commented
/assign moadqassem

2020-06-03 20:10 UTC, moadqassem commented
@moelsayed Can you please resolve the conflicts :)

2020-06-04 04:18 UTC, moelsayed commented
/retest

2020-06-04 04:56 UTC, moelsayed commented
/retest

2020-06-04 07:52 UTC, moelsayed commented
/retest

2020-06-04 10:57 UTC, moelsayed commented
/retest

2020-06-05 08:50 UTC, moelsayed commented
/retest

2020-06-09 10:26 UTC, moelsayed commented
/retest

2020-06-09 15:52 UTC, moadqassem commented
/approve
/lgtm
/hold 

The tests are passing now, @xrstf if you agree on the addressed changes please remove the hold command.

2020-06-09 18:40 UTC, xrstf approved these changes
/hold cancel

2020-06-10 08:26 UTC, moelsayed commented
/retest

2020-06-10 08:44 UTC, moadqassem commented
/lgtm

2020-06-10 10:02 UTC, moelsayed commented
/retest

2020-06-10 12:56 UTC, merged