Add Validate method to CloudProvider interface
kubermatic/kubermatic pull request #541
Opened 2017-10-23 10:31 UTC by lbb

Resolves #536

2017-10-23 12:12 UTC, mrIncompetent commented on api/pkg/provider/types.go
> +type CloudProvider interface {
Very good idea!

2017-10-23 13:52 UTC, mrIncompetent commented
- Rename to Validating.
- Move initialization to pending phase
- Remove all panics you introduced
- Define aws validate logic
- Move security-group validation code into separate function

2017-10-23 13:52 UTC, mrIncompetent commented
Also:
If a cluster has no phase, set the pase to `Validating`

2017-10-23 13:54 UTC, lbb commented
👍

2017-10-23 17:12 UTC, metalmatze submitted a review, later dismissed

2017-10-23 17:12 UTC, metalmatze commented
LGTM, now.

2017-10-23 17:27 UTC, metalmatze submitted a review, later dismissed

2017-10-23 17:59 UTC, mrIncompetent requested changes

2017-10-23 17:59 UTC, mrIncompetent commented on api/pkg/controller/cluster/pending.go
> +	_, prov, err := provider.ClusterCloudProvider(cc.cps, c)
Keep to current code structure: Move into separate function. The syncPendingCluster should call sub methods.

2017-10-23 17:59 UTC, mrIncompetent commented on api/pkg/crd/kubermatic/v1/cluster.go
>  	UnknownClusterStatusPhase ClusterPhase = "Unknown"
Why do we now have a NoneClusterStatusPhase & UnknownClusterStatusPhase ?

2017-10-23 17:59 UTC, mrIncompetent commented on api/pkg/crd/kubermatic/v1/cluster.go
> +	// ValidatingClusterStatusPhase means that the cluster will be verified and the cloud resources will be created.
Comment is wrong

2017-10-23 17:59 UTC, mrIncompetent commented on api/pkg/provider/cloud/digitalocean/provider.go
> +	_, _, err := client.Account.Get(context.Background())
nit: can we rather call the regions endpoint?
I would like to avoid having to explain why we fetch account details

2017-10-23 17:59 UTC, mrIncompetent commented on api/pkg/provider/cloud/openstack/provider.go
> +		securityGroups := strings.Split(cloud.Openstack.SecurityGroups, ",")
Duplicated code

2017-10-23 17:59 UTC, mrIncompetent commented on api/pkg/provider/kubernetes/kubernetes.go
> +		return nil, fmt.Errorf("could not validate cloud provider: %v", err)
error message should rather be:
"cloud provider data could not be validated successfully: %v"

2017-10-23 17:59 UTC, mrIncompetent commented on config/kubermatic/templates/kubermatic-api-dep.yaml
> -            - name: node-files
Why was this removed?

2017-10-23 23:11 UTC, lbb commented on api/pkg/crd/kubermatic/v1/cluster.go
>  	UnknownClusterStatusPhase ClusterPhase = "Unknown"
UnknownClusterStatusPhase, have never seen I'll remove it. It is nowhere used. We can add it later.  I'll leave `NoneClusterStatusPhase` to have it as an explicit Phase. I don't like _magic_ string around the code base, (in this case _magic_ because it has a *special* meaning)

2017-10-23 23:13 UTC, lbb commented on config/kubermatic/templates/kubermatic-api-dep.yaml
> -            - name: node-files
We don't need the node-files in the api anymore because we have moved the Initialisation to the cluster-controller. The api does not need to know about the nodeclass template files.

2017-10-23 23:30 UTC, lbb commented on api/pkg/provider/cloud/openstack/provider.go
> +		securityGroups := strings.Split(cloud.Openstack.SecurityGroups, ",")
It not a code duplicate, this code *only* checks wether the specified secgroups are available, this does not modify the CloudSpec you probably mean the lines https://github.com/kubermatic/kubermatic/blob/4c20b9127084c910bd1e57b30182418c8dce5559/api/pkg/provider/cloud/openstack/provider.go#L184-L195 
moving this to a separate function would be more complex than just have a little _almost_ copy.

2017-10-23 23:31 UTC, lbb commented on api/pkg/provider/kubernetes/kubernetes.go
> +		return nil, fmt.Errorf("could not validate cloud provider: %v", err)
👍

2017-10-23 23:31 UTC, lbb commented on api/pkg/provider/cloud/digitalocean/provider.go
> +	_, _, err := client.Account.Get(context.Background())
👍

2017-10-23 23:31 UTC, lbb commented on api/pkg/crd/kubermatic/v1/cluster.go
> +	// ValidatingClusterStatusPhase means that the cluster will be verified and the cloud resources will be created.
👍

2017-10-23 23:31 UTC, lbb commented on api/pkg/controller/cluster/pending.go
> +	_, prov, err := provider.ClusterCloudProvider(cc.cps, c)
👍

2017-10-24 07:22 UTC, mrIncompetent commented on config/kubermatic/templates/kubermatic-api-dep.yaml
> -            - name: node-files
Maybe you should have a look again. The initialization has nothing to do with the node-files.

2017-10-24 15:26 UTC, guusvw requested changes

2017-10-24 15:26 UTC, guusvw commented on api/pkg/controller/cluster/pending.go
> +	if err != nil {
Could be converted to 
`if err := cc.launchingCheckConfigMaps(c); err != nil {`

2017-10-24 15:26 UTC, guusvw commented on api/pkg/controller/cluster/pending.go
> +	if err != nil {
`if err := call(); err != nil {`

2017-10-24 15:26 UTC, guusvw commented on api/pkg/controller/cluster/validating.go
> +	if err != nil {
`if err := call(); err != nil {`

2017-10-24 15:26 UTC, guusvw commented on api/pkg/controller/cluster/validating.go
> +	if err != nil {
`if err := call(); err != nil {`

2017-10-24 15:26 UTC, guusvw commented on api/pkg/controller/cluster/validating.go
> +	if err != nil {
`if err := call(); err != nil {`

2017-10-24 15:26 UTC, guusvw commented on api/pkg/controller/cluster/validating.go
> +	if !ok {
`if _, ok := call(); !ok {`

2017-10-24 15:26 UTC, guusvw commented on api/pkg/provider/cloud/openstack/provider.go
> +	err = os.validateSecurityGroup(client, cloud)
`return os.validateSecurityGroup(client, cloud)`

2017-10-24 15:26 UTC, guusvw commented on api/pkg/provider/kubernetes/kubernetes.go
>  	if err != nil {
`if err := call(); err != nil {`

2017-10-25 08:41 UTC, guusvw approved these changes
LGTM

2017-10-25 09:33 UTC, merged