use controller runtime impersonation client for member provider
kubermatic/kubermatic pull request #5452
Opened 2020-05-27 07:13 UTC by zreigz

**What this PR does / why we need it**: use controller runtime impersonation client for member provider

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

```release-note
NONE
```

2020-05-27 08:01 UTC, zreigz commented
/retest

2020-05-27 08:38 UTC, zreigz commented
/retest

2020-05-27 10:12 UTC, lsviben requested changes
Looks good, just some cleanup remarks for tests

2020-05-27 10:12 UTC, lsviben commented on api/pkg/handler/v1/user/user_test.go
> +			ep, _, err := test.CreateTestEndpointAndGetClients(tc.ExistingAPIUser, nil, []runtime.Object{}, []runtime.Object{}, kubermaticObj, nil, nil, hack.NewTestRouting)
I think you can use `test.CreateTestEndpoint` here

2020-05-27 10:12 UTC, lsviben commented on api/pkg/handler/v1/user/user_test.go
>  			ExpectedBindingIDAfterDelete: test.GenBinding("plan9-ID", "bob@acme.com", "viewers").Name,
you can also remove these `ExpectedBindingIDAfterDelete`

2020-05-27 10:12 UTC, lsviben commented on api/pkg/handler/v1/user/user_test.go
> +			ep, _, err := test.CreateTestEndpointAndGetClients(tc.ExistingAPIUser, nil, []runtime.Object{}, []runtime.Object{}, kubermaticObj, nil, nil, hack.NewTestRouting)
you can also use `test.CreateTestEndPoint` here and remove the `ExpectedBindingAfterUpdate`

2020-05-27 10:12 UTC, lsviben commented on api/pkg/handler/v1/user/user_test.go
> +			ep, _, err := test.CreateTestEndpointAndGetClients(tc.ExistingAPIUser, nil, []runtime.Object{}, []runtime.Object{}, kubermaticObj, nil, nil, hack.NewTestRouting)
here as above, and you can remove `ExpectedBindingAfterInvitation`

2020-05-28 06:01 UTC, zreigz commented
@lsviben thanks for the review :+1: 
PTAL

2020-05-28 06:18 UTC, zreigz commented
/retest

2020-05-28 07:06 UTC, lsviben commented
/lgtm
/approve

2020-05-28 07:22 UTC, zreigz commented
/retest

2020-05-28 07:40 UTC, zreigz commented
/retest

2020-05-28 08:20 UTC, merged