Changelog for v2.14.0
kubermatic/kubermatic pull request #5469
Opened 2020-06-02 13:29 UTC by kdomanski

```release-note
NONE
```

2020-06-02 17:16 UTC, xrstf commented on CHANGELOG.md
> +tf))
bad linebreak

2020-06-02 17:16 UTC, xrstf commented on CHANGELOG.md
> +- Add support for Kubernetes 1.18, drop support for Kubernetes &lt; 1.15. [#5325](https://github.com/kubermatic/kubermatic/issues/5325) ([xrstf](https://github.com/xrstf))
Please merge these two entries.

2020-06-02 17:17 UTC, xrstf commented on CHANGELOG.md
> +- Add SLES as an Operating System option [#5040](https://github.com/kubermatic/kubermatic/issues/5040) ([kgroschoff](https://github.com/kgroschoff))
It's a PITA, but can we normalize to present or past time (added vs. add)?

2020-06-02 17:19 UTC, xrstf requested changes
Reviewed.

2020-06-04 15:36 UTC, kdomanski commented on CHANGELOG.md
> +tf))
done

2020-06-04 15:38 UTC, kdomanski commented on CHANGELOG.md
> +- Add support for Kubernetes 1.18, drop support for Kubernetes &lt; 1.15. [#5325](https://github.com/kubermatic/kubermatic/issues/5325) ([xrstf](https://github.com/xrstf))
I decided it makes more sense to remove the first line entirely and add the missing "supporter versions" section.

2020-06-04 15:38 UTC, kdomanski commented on CHANGELOG.md
> +- Add SLES as an Operating System option [#5040](https://github.com/kubermatic/kubermatic/issues/5040) ([kgroschoff](https://github.com/kgroschoff))
You're totally right, I normally do that but I missed these.

2020-06-05 13:16 UTC, xrstf approved these changes
I like.

2020-06-05 13:22 UTC, maciaszczykm commented on CHANGELOG.md
> +- Added support for system-wide dark/light theme selection. [#2294](https://github.com/kubermatic/dashboard-v2/issues/2294) ([floreks](https://github.com/floreks))
It's a duplicate of the first point in this section.

2020-06-05 13:23 UTC, kdomanski commented
/hold

2020-06-05 13:23 UTC, zreigz commented on CHANGELOG.md
> +- Added metrics for nodes. [#1982](https://github.com/kubermatic/dashboard-v2/issues/1982) ([maciaszczykm](https://github.com/maciaszczykm))
now we lost this feature :(

2020-06-05 13:24 UTC, maciaszczykm commented on CHANGELOG.md
> +- Added support for system-wide dark/light theme selection. [#2294](https://github.com/kubermatic/dashboard-v2/issues/2294) ([floreks](https://github.com/floreks))
This pull request is an enhacement of the first one. Right now we have dark, light and system preffered options in the theme selector.

cc @floreks

2020-06-05 13:24 UTC, maciaszczykm commented on CHANGELOG.md
> +- Added info about End-of-life of Container Linux [#2264](https://github.com/kubermatic/dashboard-v2/issues/2264) ([kgroschoff](https://github.com/kgroschoff))
s/End-of-life/end-of-life?

2020-06-05 13:26 UTC, maciaszczykm commented on CHANGELOG.md
> +- We now set &#39;SameSite=Strict&#39; for all cookies. [#2019](https://github.com/kubermatic/dashboard-v2/issues/2019) ([maciaszczykm](https://github.com/maciaszczykm))
Please remove this one as the next entry has overwritten it.

2020-06-05 13:29 UTC, maciaszczykm commented on CHANGELOG.md
> +- Added Paginators to all tables [#1932](https://github.com/kubermatic/dashboard-v2/issues/1932) ([kgroschoff](https://github.com/kgroschoff))
s/Paginators/paginators

2020-06-08 09:32 UTC, kdomanski commented on CHANGELOG.md
> +- Added support for system-wide dark/light theme selection. [#2294](https://github.com/kubermatic/dashboard-v2/issues/2294) ([floreks](https://github.com/floreks))
fixed

2020-06-08 09:32 UTC, kdomanski commented on CHANGELOG.md
> +- Added metrics for nodes. [#1982](https://github.com/kubermatic/dashboard-v2/issues/1982) ([maciaszczykm](https://github.com/maciaszczykm))
removed

2020-06-08 09:32 UTC, kdomanski commented on CHANGELOG.md
> +- Added info about End-of-life of Container Linux [#2264](https://github.com/kubermatic/dashboard-v2/issues/2264) ([kgroschoff](https://github.com/kgroschoff))
fixed

2020-06-08 09:32 UTC, kdomanski commented on CHANGELOG.md
> +- We now set &#39;SameSite=Strict&#39; for all cookies. [#2019](https://github.com/kubermatic/dashboard-v2/issues/2019) ([maciaszczykm](https://github.com/maciaszczykm))
done

2020-06-08 09:32 UTC, kdomanski commented on CHANGELOG.md
> +- Added Paginators to all tables [#1932](https://github.com/kubermatic/dashboard-v2/issues/1932) ([kgroschoff](https://github.com/kgroschoff))
fixed

2020-06-08 09:50 UTC, maciaszczykm commented
LGTM

2020-06-08 10:00 UTC, kdomanski commented
/hold cancel

2020-06-08 10:08 UTC, maciaszczykm commented
@zreigz Can you take a final look and /lgtm?

2020-06-08 12:25 UTC, zreigz commented
/lgtm

2020-06-08 12:28 UTC, merged