initial installer fix
kubermatic/kubermatic pull request #547
Opened 2017-10-24 13:30 UTC by susman

closes #464

2017-10-24 13:31 UTC, susman commented
@realfake the idea is to to pass to this container values.yaml as a secret for each new deployment.

2017-10-26 06:40 UTC, mrIncompetent submitted a review, later dismissed

2017-10-26 06:40 UTC, mrIncompetent commented on config/Dockerfile
> +COPY drone /kubermatic/drone
No need to have drone in the image.

2017-10-26 06:40 UTC, mrIncompetent commented on config/deploy_helm_charts.sh
> +helm upgrade -i drone -f kubermatic-values.yaml -f config/values.yaml drone/
No need to have drone in the image.

2017-10-26 06:40 UTC, mrIncompetent commented on config/deploy_helm_charts.sh
I can see you're replacing the `prometheus` reference with `monitoring` in the dockerfile.
I assume this need to happen here as well?

2017-10-26 06:40 UTC, mrIncompetent commented on config/deploy_helm_charts.sh
>  if grep -q '\bLogging\b' config/values.yaml; then
Another thing i noticed is that this script does not handle rbac.
We should follow the documentation and create a serviceaccount & clusterrolebinding.
https://github.com/kubernetes/helm/blob/master/docs/service_accounts.md

2017-10-26 06:40 UTC, mrIncompetent commented on config/Dockerfile
>  FROM alpine:3.6
Is alpine a good choice for this case? Due to missing glibc we might run into issues.
Maybe we should switch to debian? (its the base for the hyperkube images. So we'll download it anyway)

2017-10-26 07:11 UTC, susman commented on config/Dockerfile
>  FROM alpine:3.6
If helm is the only binary that'd run in the container - we don't need more that that.

2017-10-26 08:37 UTC, metalmatze submitted a review, later dismissed

2017-10-26 08:37 UTC, metalmatze commented on config/deploy_helm_charts.sh
> +  helm upgrade -i prometheus -f kubermatic-values.yaml -f config/values.yaml monitoring/prometheus/
This will fail deploying, because prometheus needs to have a prometheus operator deploy for all CRDs.

2017-10-26 08:45 UTC, susman commented on config/deploy_helm_charts.sh
> +  helm upgrade -i prometheus -f kubermatic-values.yaml -f config/values.yaml monitoring/prometheus/
Commits on the branch are more than welcome

2017-11-14 16:02 UTC, susman commented on config/deploy_helm_charts.sh
>  if grep -q '\bLogging\b' config/values.yaml; then
fixed

2017-11-15 09:18 UTC, mrIncompetent commented on config/deploy_helm_charts.sh
> +  helm upgrade -i prometheus -f kubermatic-values.yaml -f config/values.yaml monitoring/prometheus/
@metalmatze What is the correct way of deploying the monitoring stack?

2017-11-15 09:21 UTC, metalmatze commented on config/deploy_helm_charts.sh
> +  helm upgrade -i prometheus -f kubermatic-values.yaml -f config/values.yaml monitoring/prometheus/
First the Prometheus Operator needs to be deployed, because it contains all the CRDs needed by the other stacks. Then you can deploy prometheus, alertmanager, kube-state-metrics, node-exporter and grafana in a random order (I think, not tested).

2017-11-15 14:35 UTC, lbb requested changes

2017-11-15 14:35 UTC, lbb commented on config/deploy_helm_charts.sh
> +helm ${HELM_OPTS} upgrade -i --namespace=cert-manager cert-manager -f ${VALUESFILE} cert-manager/
We should either have a consistent namespace pattern existent for all charts or specify it every time.

2017-11-15 15:03 UTC, lbb submitted a review, later dismissed
🎖

2017-11-15 15:33 UTC, lbb approved these changes
Weil ich es kann

2017-11-15 15:34 UTC, merged