custom default etcd replicas number for new clusters
kubermatic/kubermatic pull request #5727
Opened 2020-08-04 15:48 UTC by furkhat

Signed-off-by: furkhat <vailodf@gmail.com>

**What this PR does / why we need it**:

Adds `-etcd-replicas-number` option to the `seed-controller-manager` that will be used as value for`componentsOverride.etcd.clusterSize` for all new clusters.

**Special notes for your reviewer**:

Also fixed some hardcodes (go templates) that assume that there are only 3 etcd replicas.

**Documentation**:

What documentation would you like me to add?

**Does this PR introduce a user-facing change?**:

```release-note
1. Add `-etcd-replicas-number` option to `seed-controller-manager` to customize number of etcd replicas for new clusters using `componentsOverride`
```

2020-08-05 14:33 UTC, xrstf commented on cmd/seed-controller-manager/options.go
> +	flag.IntVar(&c.etcdReplicasNumber, "etcd-replicas-number", 3, "Number of etcd replicas. Only applies to new clusters.")
Can we use `kubermaticv1.DefaultEtcdClusterSize` instead of the hardcoded 3 here?

2020-08-05 14:35 UTC, xrstf commented on pkg/crd/operator/v1alpha1/configuration.go
> +	EtcdReplicasNumber int `json:"etcdReplicasNumber,omitempty"`
Why did you call this `ReplicasNUMBER`, whereas we just call it `Replicas` everywhere else? It feels a bit over-specific and incocsitent w.r.t. e.g. the following line: APIServerReplicas.

2020-08-05 14:35 UTC, xrstf requested changes
Minor questions, otherwise very nice :-)

/ok-to-test
/test all
/approve

2020-08-06 09:54 UTC, furkhat commented
/test pre-kubermatic-api-e2e

2020-08-06 10:59 UTC, furkhat commented
/retest

2020-08-06 14:28 UTC, xrstf commented
/retest

2020-08-06 14:29 UTC, xrstf approved these changes
/approve
/hold

@moelsayed is this conflicting with your changes? Otherwise please `/hold cancel` :)

2020-08-06 15:06 UTC, moelsayed commented
@furkhat Thank you!, looks great :+1: 
/hold cancel

2020-08-06 15:19 UTC, xrstf commented
/retest

2020-08-06 16:11 UTC, xrstf commented
One of our tests is actually failing, it's not a flake.

> {"level":"error","time":"2020-08-06T15:59:06.749Z","caller":"conformance-tests/runner.go:733","msg":"Failed to verify that prometheus metrics are available: function did not succeed after 3 attempts: failed to get all expected metrics: got: [....]

2020-08-06 17:30 UTC, xrstf commented
/lgtm cancel

2020-08-07 13:33 UTC, furkhat commented
/retest

2020-08-10 09:15 UTC, furkhat commented
> One of our tests is actually failing, it's not a flake.
> 
> > {"level":"error","time":"2020-08-06T15:59:06.749Z","caller":"conformance-tests/runner.go:733","msg":"Failed to verify that prometheus metrics are available: function did not succeed after 3 attempts: failed to get all expected metrics: got: [....]

Etcd's seem to come up okay.  I am looking at my changes and can't find what might have caused this failure. Do you know what it might be?

2020-08-12 17:02 UTC, furkhat commented
Closing this in favor of #5756 5756

2020-08-12 17:02 UTC, closed without merging