[WIP] Initial etcd volume recovery
kubermatic/kubermatic pull request #5746
Opened 2020-08-10 11:15 UTC by moelsayed

**What this PR does / why we need it**:
This PR provides support for automatic recovery in cases where one of the PVs for the user etcd cluster is lost.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5544

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2020-08-12 10:40 UTC, multi-io commented
Tested this on a 3-node cluster, deleted the etcd-1 PV, removing the pv-protection finalizer in the process, also deleted the etcd-1 pod then (not sure if that would've been necessary). Eventually the PV deletion went through, the kubermatic_volume_watcher_controller kicked in, recreated the pvc and pv and restarted all the etcd pods, end result was a working 3-node cluster with all pods restarted and the etcd-1 PVC and PV recreated. 👍

2020-08-12 12:24 UTC, moelsayed commented
> Tested this on a 3-node cluster, deleted the etcd-1 PV, removing the pv-protection finalizer in the process, also deleted the etcd-1 pod then (not sure if that would've been necessary). Eventually the PV deletion went through, the kubermatic_volume_watcher_controller kicked in, recreated the pvc and pv and restarted all the etcd pods, end result was a working 3-node cluster with all pods restarted and the etcd-1 PVC and PV recreated. +1

Glad to hear that! You don't actually need to delete anything except the PV (to test). After the PV is removed the recovery process should trigger automatically and handle everything.

2020-08-12 13:37 UTC, moelsayed commented
/test pre-kubermatic-e2e-aws-flatcar-1.18-ce

2020-08-12 16:13 UTC, multi-io commented
Since you removed the [WIP] label -- AFAICS the the code currently would try to fix non-etcd statefulsets as well -- and probably not find the PVC's pod and error-return [here](https://github.com/kubermatic/kubermatic/pull/5746/files#diff-5c2013a72c412b88448723c786ec3326R112). Also, worker-name and cluster paused checks are still missing.

2020-08-13 14:18 UTC, moelsayed commented
/hold

2020-08-14 11:55 UTC, moelsayed commented
/test pre-kubermatic-e2e-aws-coreos-1.18

2020-08-14 12:17 UTC, moelsayed commented
/test pre-kubermatic-e2e-aws-coreos-1.18

2020-08-14 13:14 UTC, moelsayed commented
/test pre-kubermatic-e2e-aws-coreos-1.18

2020-08-14 13:26 UTC, moelsayed commented
/test pre-kubermatic-e2e-aws-coreos-1.16

2020-08-14 13:39 UTC, moelsayed commented
/test pre-kubermatic-e2e-aws-coreos-1.18

2020-08-19 12:56 UTC, moelsayed commented
/retest

2020-08-20 15:28 UTC, moelsayed commented
/test pre-kubermatic-e2e-aws-coreos-1.18

2020-08-24 10:16 UTC, multi-io commented
/lgtm

2020-08-24 15:00 UTC, xrstf commented on pkg/controller/seed-controller-manager/pvwatcher/pvwatcher_controller.go
> +		return fmt.Errorf("failed to create watch fordocker-build PersistentVolumeClaidocker-buildms: %v", err)
I suspect some copy-paste mistakes happened in this line?

2020-08-24 15:01 UTC, xrstf commented on pkg/controller/seed-controller-manager/pvwatcher/pvwatcher_controller.go
> +		log.Errorf("failed to get pvc: %v", err)
Why is this logged explicitly, when the return value of `reconcile()` will be logged in `Reconcile()` anyway?

2020-08-24 15:02 UTC, xrstf commented on pkg/controller/seed-controller-manager/pvwatcher/pvwatcher_controller.go
> +	// When the pod is deleted and recreared it, it will be stuck in PodPending phase
_recreaTed_

2020-08-24 15:02 UTC, xrstf requested changes
Minor things

2020-08-24 15:51 UTC, xrstf approved these changes
/approve

2020-08-25 07:59 UTC, moelsayed commented
/retest

2020-08-25 09:08 UTC, moelsayed commented
/hold cancel

2020-08-25 10:14 UTC, merged