Move status.dc to spec.dc
kubermatic/kubermatic pull request #576
Opened 2017-11-13 17:39 UTC by mrIncompetent

2017-11-13 17:51 UTC, lbb requested changes

2017-11-13 17:51 UTC, lbb commented on api/pkg/crd/kubermatic/v1/cluster.go
> +	SeedDC            string `json:"seedDC"`
Can this be `seedDatacenterName` or `seedDatacenter`

2017-11-15 09:25 UTC, mrIncompetent commented on api/pkg/crd/kubermatic/v1/cluster.go
> +	SeedDC            string `json:"seedDC"`
Fixed

2017-11-15 09:26 UTC, lbb approved these changes
👍

2017-11-15 09:27 UTC, metalmatze approved these changes
LGTM

2017-11-15 10:09 UTC, merged