Make caBundle available to kubermatic-api when it is configured but n…
kubermatic/kubermatic pull request #5968
Opened 2020-09-29 16:55 UTC by erdii

**What this PR does / why we need it**: Make caBundle available to kubermatic-api when it is configured but no OIDCKubeCfgEndpoint feature-flag is set.

This enables users to use a custom root CA for dex.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
```

2020-09-29 18:27 UTC, xrstf requested changes
Please ensure that the `kubermatic` Helm chart behaves the same way.

2020-09-30 15:23 UTC, erdii commented
/retest

2020-09-30 16:20 UTC, erdii commented
git diff HEAD~

```
diff --git a/charts/kubermatic/Chart.yaml b/charts/kubermatic/Chart.yaml
index 2f1e7ee5f..7c97a8aeb 100644
--- a/charts/kubermatic/Chart.yaml
+++ b/charts/kubermatic/Chart.yaml
@@ -14,7 +14,7 @@
 
 apiVersion: v1
 name: kubermatic
-version: 1.1.15
+version: 1.1.16
 appVersion: '__KUBERMATIC_TAG__'
 description: Kubermatic chart for master and/or seed clusters.
 keywords:
diff --git a/charts/kubermatic/templates/kubermatic-api-dep.yaml b/charts/kubermatic/templates/kubermatic-api-dep.yaml
index 0061a3525..11a3f110a 100644
--- a/charts/kubermatic/templates/kubermatic-api-dep.yaml
+++ b/charts/kubermatic/templates/kubermatic-api-dep.yaml
@@ -71,11 +71,11 @@ spec:
         - -accessible-addons={{- (.Files.Get "static/master/accessible-addons.yaml" | fromYaml).addons | join "," }}
         {{- end }}
         - -feature-gates={{ .Values.kubermatic.api.featureGates }}
-        # the following flags enable oidc kubeconfig feature/endpoint
-        {{- if regexMatch ".*OIDCKubeCfgEndpoint=true.*" (default "" .Values.kubermatic.api.featureGates) }}
         {{- if .Values.kubermatic.auth.caBundle }}
         - -oidc-ca-file=/opt/dex-ca/caBundle.pem
         {{- end }}
+        # the following flags enable oidc kubeconfig feature/endpoint
+        {{- if regexMatch ".*OIDCKubeCfgEndpoint=true.*" (default "" .Values.kubermatic.api.featureGates) }}
         - -oidc-issuer-redirect-uri={{ .Values.kubermatic.auth.issuerRedirectURL }}
         - -oidc-issuer-client-id={{ .Values.kubermatic.auth.issuerClientID }}
         - -oidc-issuer-client-secret={{ .Values.kubermatic.auth.issuerClientSecret }}
```

>  [2020-09-30T15:24:04+0000] Chart kubermatic was modified but its version (1.1.16) was not changed. Please adjust charts/kubermatic/Chart.yaml. 

I am confused...

2020-10-01 08:06 UTC, xrstf commented
> > [2020-09-30T15:24:04+0000] Chart kubermatic was modified but its version (1.1.16) was not changed. Please adjust charts/kubermatic/Chart.yaml.
> I am confused...

@erdii Since you opened your PR, another PR got merged that bumped the version in master branch to 1.1.16 already. So you have to bump even harder.

2020-10-08 14:05 UTC, xrstf approved these changes
/approve

2020-10-08 14:45 UTC, merged

2020-10-08 15:25 UTC, xrstf commented
/cherrypick release/v2.15