start as a fresh member if data dir is empty
kubermatic/kubermatic pull request #6221
Opened 2020-11-26 15:13 UTC by furkhat

**What this PR does / why we need it**:

When a member pod starts with empty directory etch crashes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
#6220 

**Special notes for your reviewer**: none

**Documentation**: none

**Does this PR introduce a user-facing change?**:

```release-note
start as a fresh member if data directory is empty
```

2020-11-26 15:14 UTC, furkhat commented
/assign @moelsayed

2020-11-26 15:18 UTC, multi-io commented
Can we remove the etcdrestore - related parts from this, as those are part of PR https://github.com/kubermatic/kubermatic/pull/5668 and current upstream master doesn't contain the CRDs?

2020-11-30 14:50 UTC, xrstf commented on cmd/etcd-launcher/main.go
> +				log.Panicw("can't find cluster client: %v", err)
This needs a `zap.Error()` wrapping.

2020-11-30 14:51 UTC, xrstf commented on cmd/etcd-launcher/main.go
> +				log.Panicw("remove itsely due to data dir loss", zap.Error(err))
itsely? itself?

2020-11-30 14:51 UTC, xrstf reviewed
minor oversights

/ok-to-test
/test-all

2020-12-01 13:02 UTC, moelsayed requested changes
Looks good. Thank you. Just a couple of clarifications and 1 change.

2020-12-01 13:02 UTC, moelsayed commented on cmd/etcd-launcher/main.go
> +		joinCluster(e, log)
Can we please return err here an evaluate it? I know the function will panic on error, it would be more readable if we do that here.

2020-12-01 13:02 UTC, moelsayed commented on cmd/etcd-launcher/main.go
> +		log.Panicw("failed to get in cluster config", zap.Error(err))
Why are we replacing `Fatal` with `Panic`?

2020-12-01 13:02 UTC, moelsayed commented on cmd/etcd-launcher/main.go
> +		"--election-timeout=5000",
Can you please explain why those values are used?

2020-12-01 14:22 UTC, furkhat commented on cmd/etcd-launcher/main.go
> +		log.Panicw("failed to get in cluster config", zap.Error(err))
semantically it is the same. The problem is that fatal does `os.Exit(1)` and ignores defers (if there are any). There are few other places in the code with similar problems, most of which can be identified with golint I think.

2020-12-01 14:23 UTC, furkhat commented on cmd/etcd-launcher/main.go
> +		"--election-timeout=5000",
Oh sorry it shouldn't be there, I deleted.

2020-12-06 18:18 UTC, moelsayed commented
/retest

2020-12-09 16:39 UTC, moelsayed commented
@furkhat can you please update the fixtures?

2020-12-10 13:49 UTC, furkhat commented
@moelsayed I run `./hack/update-fixtures.sh` and no diffs. It seems there is nothing to update.

2020-12-15 11:26 UTC, furkhat commented
/retest

2021-01-22 13:57 UTC, moelsayed commented
/test all

2021-01-22 15:09 UTC, moelsayed commented
/lgtm

2021-01-22 15:10 UTC, moelsayed commented
/approve

2021-01-22 16:17 UTC, merged