Use block and with syntax for Storage chart
kubermatic/kubermatic pull request #648
Opened 2017-12-18 11:32 UTC by scruplelesswizard

2017-12-19 12:11 UTC, mrIncompetent requested changes

2017-12-19 12:11 UTC, mrIncompetent commented on config/storage/templates/_helpers.tpl
> +  zone: {{.Zone}}
This makes it really hard to have a values.yaml for multiple charts.
Maybe we should have the values nested? Like in https://github.com/kubermatic/kubermatic/blob/master/config/nginx-ingress-controller/values.yaml

2017-12-21 11:05 UTC, scruplelesswizard commented on config/storage/templates/_helpers.tpl
> +  zone: {{.Zone}}
These values are nested. The template is being called from within the `with` block, so I am _assuming_ it takes the same context. If not then it will have to be updated to use `.Values.Storage.Type`

2017-12-21 11:21 UTC, mrIncompetent commented on config/storage/templates/_helpers.tpl
> +  zone: {{.Zone}}
Please test first with `helm upgrade --dry-run --debug`

2018-02-01 19:36 UTC, metalmatze approved these changes

2018-02-01 19:37 UTC, mrIncompetent approved these changes

2018-02-01 19:37 UTC, merged