Feature/new usermanagement endopints
kubermatic/kubermatic pull request #653
Opened 2017-12-20 10:09 UTC by lbb

@mrIncompetent Which endpoint do you miss?

2017-12-20 12:02 UTC, lbb commented
I would like add:
* Group list users
* Group remove user
* Group add user

* User list groups
* User leave group

2017-12-20 12:15 UTC, mrIncompetent commented on api/pkg/crd/kubermatic/v1/user.go
> +	Name string `json:"name"`
Should the group have a list of references to a user or vice versa?

2017-12-20 12:21 UTC, mrIncompetent commented
I would add the following routes/endpoints:
`GET  /api/v1/me` -> returns current user
`GET /api/v1/group` -> returns current users groups
`POST /api/v1/group` -> adds a group
`POST /api/v1/group/{name}/user` -> adds a user to a group
`DELETE /api/v1/group/{name}/user` -> adds a user to a group
`GET /api/v1/group/{name}/user/{name}` -> gets user information about a group member

@guusvw some opinion on the rest endpoints?

2017-12-20 12:25 UTC, lbb commented
`GET /api/v1/group/{name}/user/{name}` ->
`GET /api/v1/user/{name}` 
 Or 
`DELETE /api/v1/group/{name}/user` ->
`DELETE /api/v1/group/{name}/user/{name}`

2017-12-20 12:27 UTC, lbb commented
And we need 
`GET /api/v1/group/{name}/user` -> list all Users

2017-12-20 12:27 UTC, lbb commented
+ all paths should be pluralized

2017-12-20 12:34 UTC, lbb commented
`GET /api/v1/me` -> returns current user which also contains all groups of a user
~~`GET /api/v1/group` -> returns current users groups~~

2017-12-20 12:40 UTC, lbb commented on api/pkg/crd/kubermatic/v1/user.go
> +	Name string `json:"name"`
We have the same question in the office ;).

I think we should store the groups in the user struct.
A group can be `orgname:owner`, `orgname:viewer`.
In that case we can have many fast lookups from the user point of view, because we can have many groups. Viewing all users in a group can be a little bit more time consuming but that dosen't happen very often.

2017-12-20 12:46 UTC, lbb commented on api/pkg/crd/kubermatic/v1/user.go
> +	Name string `json:"name"`
Other way around we have the user names in the groups. This gives us the advantage that other users can view an other user without seeing their groups.

2017-12-20 12:51 UTC, mrIncompetent commented on api/pkg/crd/kubermatic/v1/user.go
> +	Name string `json:"name"`
I would prefer the usernames (or better references) in the group. Though no strong opinion

2018-01-02 11:27 UTC, lbb commented
As a recap and for later documentation: We had a technical discussion which can be found here #441

2018-01-03 09:05 UTC, mrIncompetent submitted a review, later dismissed

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +	req.Cluster = mux.Vars(r)["member_id"]
`ClusterReq` ?

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +	var req ClusterReq
`ClusterReq` ?

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +//
What are the empty comment lines for?

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +//
What are the empty comment lines for?

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +//
What are the empty comment lines for?

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +		return nil, errors.NewBadRequest("Bad project body type request")
should be lowercase

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +		return nil, errors.NewBadRequest("Bad project body type request")
should be lowercase

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +		return nil, errors.NewBadRequest("Bad project request")
should be lowercase

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +		return nil, errors.NewBadRequest("Bad project request")
should be lowercase

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +//
What are the empty comment lines for?

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +		return nil, errors.NewBadRequest("Bad member request")
should be lowercase

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +//
What are the empty comment lines for?

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +func deleteProjectMemberEndpoint() endpoint.Endpoint {
New line missing

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +		return nil, errors.NewBadRequest("Bad project request")
should be lowercase

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +		return nil, errors.NewBadRequest("Bad member request")
should be lowercase

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +func addProjectMemberEndpoint() endpoint.Endpoint {
New line missing

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +		return nil, errors.NewBadRequest("Bad project request")
should be lowercase

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +		return nil, errors.NewBadRequest("Bad member request")
should be lowercase

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +		return nil, errors.NewBadRequest("Bad member request")
should be lowercase

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +func updateProjectMemberEndpoint() endpoint.Endpoint {
New line missing

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +//
What are the empty comment lines for?

2018-01-03 09:05 UTC, mrIncompetent commented on api/pkg/util/auth/user.go
> +	Roles map[string]struct{} `json:"roles"`
Instead of exposing this struct, we should have a dedicated api struct which we could enhance for display purpose

2018-01-03 09:24 UTC, lbb commented on api/pkg/handler/project.go
> +	req.Cluster = mux.Vars(r)["member_id"]
Habe mich an das naming schema der letzen endpoints gehalten

2018-01-03 09:28 UTC, mrIncompetent commented on api/pkg/handler/project.go
> +	req.Cluster = mux.Vars(r)["member_id"]
The function is called `decodeMemberPathReq` and it returns a ClusterReq?
Maybe its just me, but this looks like a failed copy&paste

2018-01-03 10:21 UTC, mrIncompetent commented
As already discussed, swagger definitions need to be present for all new endpoints

2018-01-03 10:51 UTC, guusvw requested changes

2018-01-03 10:51 UTC, guusvw commented on api/pkg/crd/kubermatic/v1/user.go
> +// swagger:response User
Shouldn't be `User`

2018-01-04 10:33 UTC, guusvw submitted a review, later dismissed

2018-01-09 14:59 UTC, guusvw approved these changes

2018-01-09 15:00 UTC, merged