User-management proposal
kubermatic/kubermatic pull request #662
Opened 2018-01-04 08:36 UTC by lbb

2018-01-04 08:37 UTC, lbb commented
old issue: #441 
working pr: #653

2018-01-04 10:31 UTC, mrIncompetent requested changes

2018-01-04 10:31 UTC, mrIncompetent commented on proposal/user-management.md
> +* `rule`: _(*Kubernetes*)_ a manifest to specify actions a ServiceAcoount/User/Group is allowed to perform.
Why are we using `rule` instead of role?

2018-01-04 10:31 UTC, mrIncompetent commented on proposal/user-management.md
> +  + If the use is removed from the auth provider he shouldn't be able to login into our product.
typo: `use` -> `user`

2018-01-04 10:31 UTC, mrIncompetent commented on proposal/user-management.md
> +* We use dex/(oauth) as AuthN source.
Please add a link to dex: https://github.com/coreos/dex

2018-01-04 10:31 UTC, mrIncompetent commented on proposal/user-management.md
> +* A `user` is restricted in a project it's `roles`.
Maybe rather:
A `user` is restricted by the `roles` the user is assigned

2018-01-04 10:31 UTC, mrIncompetent commented on proposal/user-management.md
> +* A `user` can add other `users` to an `role` in the `project`.
A `user` can add `roles` to other `users` in the `project` (depending if the user is permitted to do so)

2018-01-04 10:31 UTC, mrIncompetent commented on proposal/user-management.md
> +* We wan't to have 4 different `role`s:
before in the proposal you use `users` and `user`, why no use `roles` here instead of `role`s ?

2018-01-04 10:31 UTC, mrIncompetent commented on proposal/user-management.md
> +  + Admin (can add users...)
Who can modify other users roles?

A admin? Can he set someone else as owner and therefore escalate his own privileges?
Or can only a owner do this?

I still think that we should not distinguish between admin and owner (when speaking about `roles`). IMO we should only have: Admin, Editor & Viewer
 @scheeles @guusvw

2018-01-04 10:31 UTC, mrIncompetent commented on proposal/user-management.md
> +* `role` maps to the internal customer cluser i.e A Viewer-`role` can see every Kubernetes resource in the cluster.
No, the View `role` can see everything except for secrets.
Though this is an example, this might lead to confusion later

2018-01-04 10:31 UTC, mrIncompetent commented on proposal/user-management.md
> +  + Viewer (can view resources...)
can only view resources

2018-01-04 10:31 UTC, mrIncompetent commented on proposal/user-management.md
> +  + Editor (can create/delete resources...)
can create/update/delete resources

2018-01-04 10:31 UTC, mrIncompetent commented on proposal/user-management.md
> +The general idea is to map `project`/`role` to Kubernetes `group` which are bound to `rule`s
Why are we using rule instead of role?

2018-01-04 10:31 UTC, mrIncompetent commented on proposal/user-management.md
> +When a project gets created we generate all of it's rules in Kubernetes. When a `user` joins an `role` the rules get bound to the user. This also happens in all client cluster. The client cluster wil
Propagation of customer-cluster permissions should get a own proposal

2018-01-04 16:10 UTC, lbb commented on proposal/user-management.md
> +* `rule`: _(*Kubernetes*)_ a manifest to specify actions a ServiceAcoount/User/Group is allowed to perform.
we would have role 2*times

2018-01-04 16:15 UTC, lbb commented on proposal/user-management.md
> +* We wan't to have 4 different `role`s:
fixed `users` and `user`s

2018-01-04 16:16 UTC, lbb commented on proposal/user-management.md
> +  + Admin (can add users...)
Obv an Admin can not assign himself or other person the owner role

2018-01-04 16:18 UTC, lbb commented on proposal/user-management.md
> +The general idea is to map `project`/`role` to Kubernetes `group` which are bound to `rule`s
Kubernetes rule

2018-01-04 16:24 UTC, mrIncompetent commented
Except for the admin & owner role i'm fine.
@guusvw @metalmatze @scheeles can anyone of you have a look and also check the roles?

2018-01-04 16:24 UTC, lbb commented
This is just an example, we can redefine it later.

> On 4. Jan 2018, at 17:24, Henrik Schmidt <notifications@github.com> wrote:
> 
> Except for the admin & owner role i'm fine.
> @guusvw <https://github.com/guusvw> @metalmatze <https://github.com/metalmatze> @scheeles <https://github.com/scheeles> can anyone of you have a look and also check the roles?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub <https://github.com/kubermatic/kubermatic/pull/662#issuecomment-355327255>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AHC6NwsTHaeYWm33hsKUsBRGQNBeEqyiks5tHPshgaJpZM4RStaQ>.
>

2018-01-05 08:14 UTC, mrIncompetent commented
Agree, removing my objection. Still, a second reviewer is mandatory

2018-01-10 15:20 UTC, scheeles commented
Didn't we want to write a proposal. Also including the main development tasks and the effort

2018-01-10 15:24 UTC, mrIncompetent commented
@scheeles good point, that's missing.

2018-01-17 16:39 UTC, scheeles commented
Please create Proposal similar describe here #687

2018-01-30 14:54 UTC, mrIncompetent submitted a review, later dismissed

2018-01-30 15:03 UTC, mrIncompetent submitted a review, later dismissed
No time estimations as it is too complex to give a reasonable estimation.
I would guess ~1-2 weeks fulltime

2018-01-30 16:25 UTC, scheeles commented
Can't we approx. estimate each task ?

2018-02-26 15:19 UTC, mrIncompetent commented on proposal/user-management.md
> +We use [User Impersonation](https://kubernetes.io/docs/admin/authentication/#user-impersonation) to perform user actions such as listing/editing `resources`. For that we can't use the K8s indexer whi
This is something we can only use for requests to a specific resource.
Unfortunately you cannot restrict access to specific resources and allow a LIST.
When giving a role permission to `list` a resource - it means all.

2018-03-20 09:53 UTC, mrIncompetent commented on proposal/user-management.md
> +List users: When setting `roles` for a specific path in kubernets it won't be filtered when you list them. As a solution we label each resource with the project id (this also helps dev's to find reso
Can we specify multiple resources via SelfSubjectAccessReview ?
Otherwise we'll have a separate call for each Cluster in a Project

2018-03-20 10:00 UTC, lbb commented on proposal/user-management.md
> +We use [User Impersonation](https://kubernetes.io/docs/admin/authentication/#user-impersonation) to perform user actions such as listing/editing `resources`. For that we can't use the K8s indexer whi
But afterward, we filter the resources. The list can be performed by an admin user.

2018-03-20 10:04 UTC, mrIncompetent commented on proposal/user-management.md
> +We use [User Impersonation](https://kubernetes.io/docs/admin/authentication/#user-impersonation) to perform user actions such as listing/editing `resources`. For that we can't use the K8s indexer whi
@realfake Not sure if i understand. Can you elaborate what you mean?
The Block with the User Impersonation does not work for us.

2018-03-20 10:21 UTC, lbb commented on proposal/user-management.md
> +We use [User Impersonation](https://kubernetes.io/docs/admin/authentication/#user-impersonation) to perform user actions such as listing/editing `resources`. For that we can't use the K8s indexer whi
1. Fetch user List with a label selector (any user as we cannot restrict resources to appear in the list)
2. Filter with user-impersonation + `SubjectAccessReview`

2018-03-20 10:22 UTC, lbb commented on proposal/user-management.md
> +List users: When setting `roles` for a specific path in kubernets it won't be filtered when you list them. As a solution we label each resource with the project id (this also helps dev's to find reso
AFAIK we have single calls

2018-03-20 10:24 UTC, mrIncompetent commented on proposal/user-management.md
> +We use [User Impersonation](https://kubernetes.io/docs/admin/authentication/#user-impersonation) to perform user actions such as listing/editing `resources`. For that we can't use the K8s indexer whi
What do you mean with "any user"?

Why do you want to use user impersonation together with `SubjectAccessReview` ?
Or do you mean `SelfSubjectAccessReview`? If so whats the benefit?

2018-03-20 10:32 UTC, lbb commented on proposal/user-management.md
> +We use [User Impersonation](https://kubernetes.io/docs/admin/authentication/#user-impersonation) to perform user actions such as listing/editing `resources`. For that we can't use the K8s indexer whi
In this case, it would be `SelfSubjectAccessReview`, because we already have the user impersonation client.

2018-03-20 10:33 UTC, lbb commented on proposal/user-management.md
> +We use [User Impersonation](https://kubernetes.io/docs/admin/authentication/#user-impersonation) to perform user actions such as listing/editing `resources`. For that we can't use the K8s indexer whi
I wanted to point out that any user with the permission to list users is able to perform the action of listing the users(It really doesn't matter). This may be done, using a locally cached list.

2018-03-20 10:36 UTC, mrIncompetent commented on proposal/user-management.md
> +We use [User Impersonation](https://kubernetes.io/docs/admin/authentication/#user-impersonation) to perform user actions such as listing/editing `resources`. For that we can't use the K8s indexer whi
> In this case, it would be SelfSubjectAccessReview, because we already have the user impersonation client.

Why do we have a impersonation client?
As far as i can see the only reason for it is because you want to use `SelfSubjectAccessReview`?

2018-03-20 10:40 UTC, lbb commented on proposal/user-management.md
> +We use [User Impersonation](https://kubernetes.io/docs/admin/authentication/#user-impersonation) to perform user actions such as listing/editing `resources`. For that we can't use the K8s indexer whi
We want to use user impersonation because of:
1. (Fully) Rely on RBAC
2. All further actions should go through this client (delete/create/...)

2018-03-20 10:51 UTC, mrIncompetent commented on proposal/user-management.md
> +We use [User Impersonation](https://kubernetes.io/docs/admin/authentication/#user-impersonation) to perform user actions such as listing/editing `resources`. For that we can't use the K8s indexer whi
This should be documented in the proposal. 
It currently says we cannot use the Lister (which you already stated differently in the comments)
Also the proposal says we use a Impersonated client for listing (which you already stated differently in the comments)

2018-03-20 10:52 UTC, mrIncompetent commented
How will this work in a multi seed environment?

2018-03-20 10:54 UTC, lbb commented
We should replicate all of the rules to the seeds.

2018-03-20 10:55 UTC, mrIncompetent commented
I highly recommend rewriting the technical details.
- Add examples on what RBAC manifests will be created.
- Clearly state when (which requests) we use a impersonated client & when we use data from the Lister.
- How are multi-seed environments handled?

2018-03-20 10:56 UTC, mrIncompetent commented
> We would have to replicate all rules to the seed clusters. But most of the resources are saved in the master cluster which makes it a lot easier. The definitions are stored in the master so this shouldn't be a problem.

That is wrong. Clusters are stored in the individual seed clusters.

2018-03-20 15:06 UTC, mrIncompetent requested changes

2018-03-20 15:06 UTC, mrIncompetent commented on proposal/user-management.md
> +Sample code to generate user _login_ config:
What it s a "user _login_ config" ?

2018-03-20 15:06 UTC, mrIncompetent commented on proposal/user-management.md
> +  propergate: true
Whats the benefit for debugging in having this only in one Cluster?

2018-03-20 15:06 UTC, mrIncompetent commented on proposal/user-management.md
> +  userBindings:
Why is this called `userBindings` and not just `users`?

2018-03-20 15:06 UTC, mrIncompetent commented on proposal/user-management.md
> +  roleBindings:
why is this called `roleBindings` and not just `roles`?

2018-03-20 15:06 UTC, mrIncompetent commented on proposal/user-management.md
> +kind: Role
Are we introducing a new CustomResource here?

2018-03-20 15:06 UTC, mrIncompetent commented on proposal/user-management.md
> +```
Is this everything we generate when creating a new Project?
I see no RBAC resources, so why do we use User impersonation?

2018-03-20 15:06 UTC, mrIncompetent commented on proposal/user-management.md
> +    verbs: ["impersonate"]
"impersonation" is no verb

2018-03-20 15:06 UTC, mrIncompetent commented on proposal/user-management.md
> +    resources: ["userextras/{{-.ResourceName-}}"]
`userextras/{{-.ResourceName-}}` Seems like a custom path which is not satisfied by an actual resource in Kubernetes.
Doesn't this get validated by the apiserver?

2018-03-20 15:06 UTC, mrIncompetent commented on proposal/user-management.md
> +    resourceNames: ["view", "development"]
What are those resource names?

2018-03-20 15:07 UTC, mrIncompetent commented
It really looks like the examples are incomplete? RBAC resources are missing completely here @realfake

2018-03-20 15:07 UTC, lbb commented on proposal/user-management.md
> +    verbs: ["impersonate"]
It is

2018-03-20 15:12 UTC, lbb commented on proposal/user-management.md
> +Sample code to generate user _login_ config:
The values that build an impersonated user. e.g username, groups

2018-03-20 15:13 UTC, lbb commented on proposal/user-management.md
> +  propergate: true
We can test it in just one cluster and don't spread it to multiple clusters, which may cause errors.

2018-03-20 15:14 UTC, mrIncompetent commented on proposal/user-management.md
> +    verbs: ["impersonate"]
True, documented in https://kubernetes.io/docs/admin/authorization/#determine-the-request-verb

2018-03-20 15:14 UTC, mrIncompetent commented on proposal/user-management.md
> +Sample code to generate user _login_ config:
Then define it in the proposal

2018-03-20 15:14 UTC, lbb commented on proposal/user-management.md
> +  userBindings:
because those are the references it binds to, we don't generate users out of this. IMHO it is more explicit.

2018-03-20 15:15 UTC, lbb commented on proposal/user-management.md
> +  roleBindings:
As above

2018-03-20 15:15 UTC, lbb commented on proposal/user-management.md
> +kind: Role
yes

2018-03-20 15:15 UTC, mrIncompetent commented on proposal/user-management.md
> +  propergate: true
Why would that cause errors?

2018-03-20 15:16 UTC, lbb commented on proposal/user-management.md
> +```
Those are not the resources we generate, we generate real kubernetes rules/bindings/users out of this.

2018-03-20 15:16 UTC, mrIncompetent commented on proposal/user-management.md
> +  userBindings:
Then stick to kubernetes naming and calll it `userRef`

2018-03-20 15:17 UTC, lbb commented on proposal/user-management.md
> +    resources: ["userextras/{{-.ResourceName-}}"]
We generate kubernetes rules out of this. The template is used to be able to generate rules for the wanted resource

2018-03-20 15:17 UTC, mrIncompetent commented on proposal/user-management.md
> +  roleBindings:
Then stick to kubernetes naming and calll it `roleRef`

2018-03-20 15:18 UTC, mrIncompetent commented on proposal/user-management.md
> +kind: Role
There's no word about a custom resource defined in the Text.

2018-03-20 15:20 UTC, mrIncompetent commented on proposal/user-management.md
> +```
Who takes care about generating?
What would "real" kubernetes rules/bindings/users look like?

2018-03-20 15:44 UTC, lbb commented on proposal/user-management.md
> +  propergate: true
I wanted to give the possibility to reduce complexity

2018-03-20 15:46 UTC, mrIncompetent commented on proposal/user-management.md
> +  propergate: true
Can you explain why you think this reduces complexity?
I see the extra logic of having a separate Field (which defaults to `false`) and the logic to handle it more complex

2018-04-05 11:43 UTC, mrIncompetent commented
@p0lyn0mial Should we close this PR?

2018-04-05 13:14 UTC, p0lyn0mial commented
yes, I think so. 

The first part of the user management proposal has been delivered via this PR #858

2018-04-05 13:24 UTC, closed without merging