Upate machine-controller to v1.27.0
kubermatic/kubermatic pull request #6695
Opened 2021-03-12 14:36 UTC by kron4eg

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Upate machine-controller to v1.27.0
```

2021-03-12 14:40 UTC, kron4eg commented on pkg/resources/machinecontroller/webhook.go
> +				args = append(args, "-node-kubelet-feature-gates", strings.Join(featureGates, ","))
If you think this line is missing `"RotateKubeletServerCertificate=true"` then it's not. `"RotateKubeletServerCertificate=true"` defaulting to true is now part of the machine-controller (even when `-node-kubelet-feature-gates` is defined but without `RotateKubeletServerCertificate`.

2021-03-12 16:53 UTC, kron4eg commented
/retest

2021-03-12 20:44 UTC, kron4eg commented
/retest

2021-03-12 21:14 UTC, kron4eg commented
/retest

2021-03-13 17:27 UTC, kron4eg commented
/retest

2021-03-15 10:25 UTC, kron4eg commented
/retest

2021-03-15 11:25 UTC, xmudrii requested changes
Can you also update the [machine-controller dependency](https://github.com/kubermatic/kubermatic/blob/24376f2209aca78f52be35d7814ca7d7494c3b23/go.mod#L48), so that:

* we're sure everything works fine with the newer version of the dependency
* we can use the newly added types (such as the annotations)

2021-03-15 15:11 UTC, kron4eg commented
> Can you also update the [machine-controller dependency](https://github.com/kubermatic/kubermatic/blob/24376f2209aca78f52be35d7814ca7d7494c3b23/go.mod#L48), so that:
> 
> * we're sure everything works fine with the newer version of the dependency

done

> * we can use the newly added types (such as the annotations)

should be done in the followup PRs done under #6551

2021-03-15 20:30 UTC, kron4eg commented
/test pre-kubermatic-api-e2e

2021-03-16 09:09 UTC, kron4eg commented
/test pre-kubermatic-api-e2e

2021-03-16 12:40 UTC, kron4eg commented
/retest

2021-03-16 14:24 UTC, kron4eg commented
/retest

2021-03-16 14:54 UTC, xmudrii approved these changes
/lgtm

2021-03-16 17:02 UTC, xmudrii commented
/retest

2021-03-16 18:48 UTC, kron4eg commented
/retest

2021-03-16 20:38 UTC, merged