Use the custom ca_bundle for openstack and vsphere cluster validation
kubermatic/kubermatic pull request #6907
Opened 2021-04-20 08:55 UTC by lsviben

**What this PR does / why we need it**:
Fixes the issue where cluster validation was failing on certificate error because the validation provider was not using the provided custom CA Bundle. Openstack and vSphere providers now use the proper CA Bundle.

**Does this PR introduce a user-facing change?**:

```release-note
Fixes issue where cluster validation was failing on certificate error because the validation provider was not using the provided custom CA Bundle. 
```

2021-04-20 11:57 UTC, lsviben commented
/retest

2021-04-20 13:12 UTC, kron4eg commented on pkg/provider/cloud/openstack/provider.go
> +		client.HTTPClient = httpcautil.HTTPClientConfig.New(httpcautil.HTTPClientConfig{})
.New() takes no parameters

2021-04-21 08:29 UTC, kron4eg requested changes
Please use existing facilities 
https://github.com/kubermatic/kubermatic/blob/master/pkg/resources/certificates/ca-bundle.go#L63

2021-04-21 10:33 UTC, lsviben commented
/test pre-kubermatic-test

2021-04-21 11:29 UTC, lsviben commented
/retest

2021-04-21 12:00 UTC, xrstf requested changes
/hold

Please do not introduce global state. #6538 went into a lot of effort to ensure the CA bundle is properly injected where it is needed.

2021-04-22 05:54 UTC, kron4eg commented
/retest

2021-04-22 05:56 UTC, kron4eg approved these changes
/lgtm

2021-04-22 07:05 UTC, lsviben commented
> /hold
> 
> Please do not introduce global state. #6538 went into a lot of effort to ensure the CA bundle is properly injected where it is needed.

Changed it to the solution with injecting. Initially I was following the `machine-controller` example as they use the same clients code, but you and @kron4eg are right, this is better.

2021-04-22 07:25 UTC, xrstf commented
Correct, the machine-controller uses global state, but only super super reluctantly: https://github.com/kubermatic/machine-controller/pull/895 -- we tried the sane way first, but in that particular case, global state was the better choice.

Now I have to go wash my mouth with soap for having said that.

2021-04-22 13:33 UTC, xrstf approved these changes
/approve

2021-04-22 13:35 UTC, lsviben commented
/hold cancel

2021-04-22 14:45 UTC, xrstf commented
/retest

2021-04-22 15:38 UTC, lsviben commented
/retest

2021-04-22 23:05 UTC, merged

2021-04-23 15:48 UTC, irozzo-1A commented
cherry-pick release/v2.17

2021-04-23 15:48 UTC, irozzo-1A commented
/cherry-pick release/v2.17

2021-04-24 06:50 UTC, irozzo-1A commented
/cherry-pick release/v2.17