fix swagger documentation
kubermatic/kubermatic pull request #709
Opened 2018-01-29 09:28 UTC by mrIncompetent

**What this PR does / why we need it**:
Fixes the swagger spec:
- Routes had bad annotations
- Models were missing
- Request bodies were not defined at all
- Request path params were not defined at all

I removed all swagger docs which existed before and annotated them new as this was faster than fixing each existing annotation.
Currently all project related annotation are still missing - i'll add them in a new PR

2018-01-29 13:46 UTC, guusvw commented on api/cmd/kubermatic-api/main.go
> -//go:generate swagger generate spec
Why you removed the `go:generate` line?

2018-01-29 14:23 UTC, mrIncompetent commented on api/cmd/kubermatic-api/main.go
> -//go:generate swagger generate spec
It seems it wasn't needed at all

2018-01-31 09:05 UTC, metalmatze commented on api/cmd/kubermatic-api/main.go
> -//go:generate swagger generate spec
How do you generate then? By simply running `swagger generate spec`?

2018-01-31 09:05 UTC, mrIncompetent commented on api/cmd/kubermatic-api/main.go
> -//go:generate swagger generate spec
With our hack/update-swagger.sh script

2018-01-31 09:06 UTC, metalmatze approved these changes

2018-01-31 09:11 UTC, lbb requested changes

2018-01-31 09:11 UTC, lbb commented on api/pkg/util/auth/user.go
> -func (u *User) IsAdmin() bool {
Can we make this a struct/pointer receiver?

2018-01-31 09:15 UTC, metalmatze commented on api/pkg/util/auth/user.go
> -func (u *User) IsAdmin() bool {
Why? A simple func is totally fine here. Can you elaborate?

2018-01-31 09:19 UTC, mrIncompetent commented on api/pkg/util/auth/user.go
> -func (u *User) IsAdmin() bool {
I wanted to have a clear separation between the API object and the logic of defining what makes this user admin.

2018-01-31 09:19 UTC, mrIncompetent commented on api/pkg/util/auth/user.go
> -func (u *User) IsAdmin() bool {
But i actually don't really mind

2018-01-31 09:20 UTC, lbb commented on api/pkg/util/auth/user.go
> -func (u *User) IsAdmin() bool {
This a quite common function, it can be quite hard to track it in the packages (e.g during refactor) also because it's in another package atm `pkg/util`, it it not obvious to a person if this function exists or where it is.

2018-01-31 10:00 UTC, merged