add route for getting digitalocean sizes
kubermatic/kubermatic pull request #726
Opened 2018-02-07 16:45 UTC by kgroschoff

**What this PR does / why we need it**:
add route for getting digitalocean sizes

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Relating to https://github.com/kubermatic/dashboard-v2/issues/410

**Special notes for your reviewer**:
/

2018-02-08 14:56 UTC, metalmatze requested changes
Generally very good code and well documented.
I see a few things that can be optimized pretty easily, for those I left some comments.

At last, I have a question on the design of that endpoint overall: Do we really need to call the DigitalOcean API for every API call of ours?
Wouldn't it be enough to simply call the DigitalOcean API once, when starting, and then simply return what we have queried before?

2018-02-08 14:56 UTC, metalmatze commented on api/pkg/api/v1/types.go
> +	Vcpus        int      `json:"vcpus"`
I'd call this one, as we're talking about vCPUs `VCPUs` rather then `Vcpus`.

2018-02-08 14:56 UTC, metalmatze commented on api/pkg/handler/digitalocean.go
> +			reStandard := regexp.MustCompile("(^s|S)")
`regexp.MustCompile` shouldn't be done inside the loop, as we're compiling the regex in every iteration. 

I'd move this to the top of the func before returning the handler func, like:

```diff
func digitaloceanSizeEndpoint() endpoint.Endpoint {
+	reStandard := regexp.MustCompile("(^s|S)")
+	reOptimized := regexp.MustCompile("(^c|C)")

	return func(ctx context.Context, request interface{}) (interface{}, error) {
```
That way we only call this once in the whole app lifecycle when instantiating the router. This won't be even called for every handler execution.

2018-02-08 14:56 UTC, metalmatze commented on api/pkg/handler/digitalocean.go
> +			if reStandard.MatchString(sizes[k].Slug) {
In the loop I'd go for early returns. If I'm not wrong this should be possible like:

```go
if reStandard.MatchString(sizes[k].Slug) {
	sizesStandard = append(sizesStandard, apiv1.DigitaloceanSize{
	...
	})
	continue
}
if reOptimized.MatchString(sizes[k].Slug) {
	sizesOptimized = append(sizesOptimized, apiv1.DigitaloceanSize{
	...
	})
}
```
The `else` could be deleted completely, as continuing in the loop in case we don't into the `if`s, is the normal behavior.

2018-02-08 16:31 UTC, kgroschoff commented
Thanks @metalmatze , sounds logic. I already committed the adjustments.

About the design thingy: I'm not sure? To get the sizes, we need the API token from the user input (step 4 while creating a cluster in the dashboard). That's my only information...
Maybe @mrIncompetent could add something?! :v:

2018-02-08 17:09 UTC, metalmatze commented
Yep. The design question was actually more meant for @mrIncompetent :innocent:

2018-02-09 08:45 UTC, mrIncompetent requested changes
Looks pretty nice!
Except for the error-return, the rest is just personal preference.
@metalmatze if you have the time, please validate my feedback :)

Regarding the cachine @metalmatze mentioned, i agree, we should probably cache the result.
Though we cannot fetch the sizes on start as we do not have credentials.
We would need to cache it after it got requested for the first time.

I have no idea whats the best practice here for caching.
Is using a variable in the package fine? @metalmatze @guusvw

2018-02-09 08:45 UTC, mrIncompetent commented on api/pkg/handler/digitalocean.go
> +			glog.Errorf("Sizes.List returned error: %v", err)
return the error directly. Otherwise, you get an empty result in the frontend without knowing why.

```
return fmt.Errorf("failed to list sizes: %v", err)
```

2018-02-09 08:45 UTC, mrIncompetent commented on api/pkg/handler/digitalocean.go
> +			}
Should we add a `else` which catches the rest?
Are there other types?
I think we should at least log in case we run into this

2018-02-09 08:45 UTC, mrIncompetent commented on api/pkg/handler/digitalocean.go
> +		sizesOptimized := []apiv1.DigitaloceanSize{}
As `sizeList.Standard` is not a pointer, we could append directly to it, instead of going the way via e extra variable.
Same with `sizeList.Optimized`

2018-02-09 08:45 UTC, mrIncompetent commented on api/pkg/handler/routing.go
> +		Path("/api/v1/digitaloceansizes/{token}").
can we change to `/api/digitalocean/sizes` ?

2018-02-09 08:45 UTC, mrIncompetent commented on api/pkg/handler/routing.go
> +func (r Routing) getdosizes() http.Handler {
Maybe rather `listDigitaloceanSizes` ?

2018-02-09 08:52 UTC, mrIncompetent commented
Regarding the caching - i would avoid caching. I don't want to run into trouble when a size gets unavailable, but the user is still able to select it. Also i'm not sure if the pricing might be dependent on the user - i dont know if DO has some user dependent magic here.

Lets call the API on every request

2018-02-09 09:06 UTC, kgroschoff commented on api/pkg/handler/digitalocean.go
> +			}
There are currently 3 different types: 1) s-something, 2) c-something and 3) something. Type 3 are the old sizes, which are no longer listed in the pricing and will be available until July 1st, 2018 (https://developers.digitalocean.com/documentation/changelog/api-v2/new-size-slugs-for-droplet-plan-changes/). 
Don't know if we want to log this every time?

2018-02-09 09:09 UTC, mrIncompetent commented on api/pkg/handler/digitalocean.go
> +			}
Good point. Can you add a comment mentioning this?

2018-02-09 09:14 UTC, kgroschoff commented on api/pkg/handler/digitalocean.go
> +			}
sure

2018-02-09 11:01 UTC, metalmatze commented on api/pkg/handler/routing.go
> +func (r Routing) getdosizes() http.Handler {
Yes. Please go with `listDigitaloceanSizes`. Just mentioning here that I'd have called this one `getDOSizes`. :wink:

2018-02-09 11:03 UTC, metalmatze commented
I don't think that DO has magic per-user. Maybe caching the results for a minute or two would be beneficial. But we shouldn't over engineer this part right now, so let's keep it like it is without caching.

2018-02-09 11:03 UTC, metalmatze approved these changes

2018-02-09 11:04 UTC, metalmatze commented
Approving because all my requests are met. Please still fix the once requested by @mrIncompetent. Then I'm fine with merging this one. :relaxed:

2018-02-09 11:10 UTC, mrIncompetent approved these changes
actually all my points are addressed - comment was introduced a few lines above, so github didn't recognized that

2018-02-09 11:40 UTC, merged