Create metrics for cluster phase with alerting rules
kubermatic/kubermatic pull request #756
Opened 2018-02-22 18:53 UTC by metalmatze

2018-02-26 09:17 UTC, mrIncompetent requested changes

2018-02-26 09:17 UTC, mrIncompetent commented on config/monitoring/prometheus/rules/kubermatic.yaml
> +      description: "Cluster {{ $labels.cluster }} is {{ $labels.phase }} for more then 10min."
"Cluster {{ $labels.cluster }} is in phase '{{ $labels.phase }}' for more then 10min."

2018-02-26 09:17 UTC, mrIncompetent commented on config/monitoring/prometheus/rules/kubermatic.yaml
> +      kubermatic_cluster_controller_cluster_status_phase{phase="deleting"} == 0
New rule if a cluster is in deleting since more than 30 min.
AWS deletions take longer but should not exceed 30min

2018-02-26 15:03 UTC, metalmatze commented on config/monitoring/prometheus/rules/kubermatic.yaml
> +      description: "Cluster {{ $labels.cluster }} is {{ $labels.phase }} for more then 10min."
It already reads:
`Cluster asdfasf is launching for more then 10min.`
Your would only add:
`Cluster asdfasf is in phase 'launching' for more then 10min.`

Do you still prefer the more explicit one?

2018-02-26 15:04 UTC, mrIncompetent commented on config/monitoring/prometheus/rules/kubermatic.yaml
> +      description: "Cluster {{ $labels.cluster }} is {{ $labels.phase }} for more then 10min."
Yes :)

2018-02-26 15:05 UTC, metalmatze commented on config/monitoring/prometheus/rules/kubermatic.yaml
> +      kubermatic_cluster_controller_cluster_status_phase{phase="deleting"} == 0
Sadly this is not possible as it is.
Right now a cluster is always in a deleting state, even when its long gone, because the prometheus client is stateful and you can't delete a metric with certain labels...
That's why I added `kubermatic_cluster_controller_cluster_status_phase{phase="deleting"} == 0` to the query above too...

2018-02-28 10:06 UTC, metalmatze commented
Updated the alert description.

2018-02-28 10:57 UTC, mrIncompetent approved these changes

2018-02-28 15:05 UTC, merged