Cluster monitoring
kubermatic/kubermatic pull request #786
Opened 2018-03-07 15:26 UTC by metalmatze

**What this PR does / why we need it**:
We want to deploy Prometheus on a per cluster basis.
This will allow us to use Prometheus' Federation from a single Kubermatic cluster to all customer clusters.

**Which issue(s) this PR fixes** 
Closes #770 

**Special notes for your reviewer**:
I still need to implement the deployment of Prometheus & ServiceMonitor CRDs.

2018-03-07 15:39 UTC, mrIncompetent requested changes

2018-03-07 15:39 UTC, mrIncompetent commented on api/pkg/controller/cluster/pending.go
> +		"prometheus": controllerresources.LoadRoleFile,
should be moved to a const in "github.com/kubermatic/kubermatic/api/pkg/controller/resources"

2018-03-07 15:39 UTC, mrIncompetent commented on api/pkg/controller/cluster/pending.go
> +			return fmt.Errorf("failed to generate Role %s: %v", name, err)
why uppercase `Role`?

2018-03-07 15:39 UTC, mrIncompetent commented on api/pkg/controller/cluster/pending.go
> +		generatedRole.Annotations[lastAppliedConfigAnnotation] = lastApplied
`generatedRole.Name = name` is missing. We should not rely on the names defined in the templates.

2018-03-07 15:39 UTC, mrIncompetent commented on api/pkg/controller/cluster/pending.go
> +		"prometheus": controllerresources.LoadRoleBindingFile,
should be moved to a const in "github.com/kubermatic/kubermatic/api/pkg/controller/resources"

2018-03-07 15:39 UTC, mrIncompetent commented on api/pkg/kubernetes/informer/seed/group.go
> +package seed
This package was deleted in master

2018-03-07 15:39 UTC, mrIncompetent commented on config/kubermatic/static/master/controller-manager-service.yaml
> +  name: controller-manager
Whats the whole file for?
I haven't seen a reference to this file

2018-03-07 15:39 UTC, mrIncompetent commented on config/kubermatic/static/master/kube-state-metrics-service.yaml
> +  name: kube-state-metrics
Whats the whole file for?
I haven't seen a reference to this file

2018-03-07 15:39 UTC, mrIncompetent commented on config/kubermatic/static/master/machine-controller-service.yaml
> +    name: scheduler
Whats the whole file for?
I haven't seen a reference to this file

2018-03-07 15:39 UTC, mrIncompetent commented on config/kubermatic/static/master/prometheus-role.yaml
> +#  verbs: ["get"]
Can we remove this?

2018-03-07 15:39 UTC, mrIncompetent commented on config/kubermatic/static/master/prometheus-service-monitor-apiserver.yaml
> +  name: apiserver
Whats the whole file for?
I haven't seen a reference to this file

2018-03-07 15:39 UTC, mrIncompetent commented on config/kubermatic/static/master/prometheus-service-monitor-controller-manager.yaml
> +  name: controller-manager
Whats the whole file for?
I haven't seen a reference to this file

2018-03-07 15:39 UTC, mrIncompetent commented on config/kubermatic/static/master/prometheus-service-monitor-etcd.yaml
> +  name: etcd
Whats the whole file for?
I haven't seen a reference to this file

2018-03-07 15:39 UTC, mrIncompetent commented on config/kubermatic/static/master/prometheus-service-monitor-kube-state-metrics.yaml
> +  name: kube-state-metrics
Whats the whole file for?
I haven't seen a reference to this file

2018-03-07 15:39 UTC, mrIncompetent commented on config/kubermatic/static/master/prometheus-service-monitor-machine-controller.yaml
> +  name: machine-controller
Whats the whole file for?
I haven't seen a reference to this file

2018-03-07 15:39 UTC, mrIncompetent commented on config/kubermatic/static/master/prometheus-service-monitor-scheduler.yaml
> +  name: scheduler
Whats the whole file for?
I haven't seen a reference to this file

2018-03-07 15:39 UTC, mrIncompetent commented on config/kubermatic/static/master/prometheus-service.yaml
> +  name: prometheus
Whats the whole file for?
I haven't seen a reference to this file

2018-03-07 15:39 UTC, mrIncompetent commented on config/kubermatic/static/master/prometheus.yaml
> +  name: {{ .Cluster.Name }}
Whats the whole file for?
I haven't seen a reference to this file

2018-03-07 15:39 UTC, mrIncompetent commented on config/kubermatic/static/master/scheduler-service.yaml
> +  name: scheduler
Whats the whole file for?
I haven't seen a reference to this file

2018-03-07 15:39 UTC, mrIncompetent commented on config/kubermatic/static/master/versions.yaml
> +    kube-state-metrics-version: latest
Is there no other version than latest?

2018-03-07 15:41 UTC, metalmatze commented on config/kubermatic/static/master/versions.yaml
> +    kube-state-metrics-version: latest
Not until https://github.com/kubernetes/kube-state-metrics/pull/371 is merged.

2018-03-07 15:42 UTC, metalmatze commented on config/kubermatic/static/master/versions.yaml
> +    kube-state-metrics-version: latest
Just saw that there was feedback :innocent:

2018-03-07 15:43 UTC, mrIncompetent commented on config/kubermatic/static/master/versions.yaml
> +    kube-state-metrics-version: latest
Nice to see, that they'll accept the change. Thanks for bringing this upstream :)

2018-03-07 15:48 UTC, metalmatze commented on api/pkg/controller/cluster/pending.go
> +		"prometheus": controllerresources.LoadRoleFile,
fixed

2018-03-07 15:49 UTC, metalmatze commented on api/pkg/controller/cluster/pending.go
> +			return fmt.Errorf("failed to generate Role %s: %v", name, err)
Some other resources, at least in older versions, were named like this. fixed

2018-03-07 15:50 UTC, metalmatze commented on api/pkg/controller/cluster/pending.go
> +		generatedRole.Annotations[lastAppliedConfigAnnotation] = lastApplied
I can't find what you think is missing here. :thinking:

2018-03-07 15:50 UTC, metalmatze commented on api/pkg/controller/cluster/pending.go
> +		"prometheus": controllerresources.LoadRoleBindingFile,
fixed

2018-03-07 15:50 UTC, mrIncompetent commented on api/pkg/controller/cluster/pending.go
> +			return fmt.Errorf("failed to generate Role %s: %v", name, err)
Wasn't aware. :+1:

2018-03-07 15:52 UTC, metalmatze commented on api/pkg/kubernetes/informer/seed/group.go
> +package seed
Good catch. It was probably an artifact of rebasing. Deleted.

2018-03-07 15:52 UTC, mrIncompetent commented on api/pkg/controller/cluster/pending.go
> +		generatedRole.Annotations[lastAppliedConfigAnnotation] = lastApplied
Ah i see, its not implemented everywhere.
At the service handling we do it.
```
generatedService.Name = name
```

2018-03-07 15:53 UTC, metalmatze commented on config/kubermatic/static/master/controller-manager-service.yaml
> +  name: controller-manager
We need this Service, because ServiceMonitors can only scrape via Services and we want to scrape this Service's Pods.

2018-03-07 15:53 UTC, metalmatze commented on config/kubermatic/static/master/kube-state-metrics-service.yaml
> +  name: kube-state-metrics
We need this Service, because ServiceMonitors can only scrape via Services and we want to scrape this Service's Pods.

2018-03-07 15:53 UTC, metalmatze commented on config/kubermatic/static/master/machine-controller-service.yaml
> +    name: scheduler
We need this Service, because ServiceMonitors can only scrape via Services and we want to scrape this Service's Pods.

2018-03-07 15:54 UTC, metalmatze commented on config/kubermatic/static/master/controller-manager-service.yaml
> +  name: controller-manager
Oh, but yes. They need to be added to the function that deploys this service. Artifact due to starting all over.

2018-03-07 15:54 UTC, metalmatze commented on config/kubermatic/static/master/kube-state-metrics-service.yaml
> +  name: kube-state-metrics
Oh, but yes. They need to be added to the function that deploys this service. Artifact due to starting all over.

2018-03-07 15:54 UTC, metalmatze commented on config/kubermatic/static/master/machine-controller-service.yaml
> +    name: scheduler
Oh, but yes. They need to be added to the function that deploys this service. Artifact due to starting all over.

2018-03-07 15:59 UTC, metalmatze commented on config/kubermatic/static/master/prometheus-role.yaml
> +#  verbs: ["get"]
I think so: removed.

2018-03-08 10:21 UTC, mrIncompetent approved these changes

2018-03-08 10:22 UTC, merged