Add devcontainer
kubermatic/kubermatic pull request #7991
Opened 2021-10-13 11:24 UTC by cedi

**What this PR does / why we need it**:

Adding a .devcontainer configuration to kubermatic

  As per a Discussion I had with @kron4eg I decided to submit a
  .devcontainer configuration for kubermatic.

  If you never worked with Devcontainers before, here is a good artical by
  [Aaron Powell](https://www.aaron-powell.com/about) on why you should care about Devcontainers:
  [your open source project needs a devcontainer - here's why](https://www.aaron-powell.com/posts/2021-03-08-your-open-source-project-needs-a-dev-container-heres-why/)

  Tl;Dr:
  Devcontainers are awesome and they help to define an isolated
  development environment which is standardised across all contributors
  setups and leverages the beauty of [GitHub Codespaces](https://github.com/features/codespaces) once, it's GA.

**Special notes for your reviewer**:

  Just try it out once, before dismissing it.
  Setting up your VScode to use the Devcontainer is easy:
  1. Make sure you have the following plugin installed: `ms-vscode-remote.remote-containers`
  2. Open VScode in the root-directory of the Repository
  3. Click "Reopen in Container" once VScode shows you the popup, telling
  you that it detected a devcontainer configuration.

**Documentation**:
https://www.aaron-powell.com/posts/2021-03-08-your-open-source-project-needs-a-dev-container-heres-why/
https://code.visualstudio.com/docs/remote/containers
https://github.com/qdm12/godevcontainer
https://github.com/features/codespaces

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

2021-10-14 09:25 UTC, xmudrii requested changes
Overall, this looks okay and I think this might be useful. I left a bunch of comments and questions, but I think we can merge this after comments are addressed.

2021-10-14 09:25 UTC, xmudrii commented on .devcontainer/Dockerfile
> +FROM qmcgaw/godevcontainer
Is using `godevcontainer` image a requirement or we can use any image here?

2021-10-14 09:25 UTC, xmudrii commented on .devcontainer/Dockerfile
> +RUN export CGO_ENABLED=1
I'm not really sure do we need `CGO_ENABLED` enabled by default. As far as I see, we only use it when running race tests because it's required for those.

2021-10-14 09:25 UTC, xmudrii commented on .devcontainer/Dockerfile
> +RUN go get -u github.com/amitbet/gorename
Can't we depend on the VSCode to download all tools automatically?

2021-10-14 09:25 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +	"name": "Go",
My understanding is that this is a name for the container. Can we call container something more recognize-able, such as `kubermatic-devcontainer` or something like that?

2021-10-14 09:25 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +	],
As far as I understand, this is required for delve to work, right? Maybe it would be useful to leave a comment if that's the case.

2021-10-14 09:25 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		"go.toolsManagement.autoUpdate": false,
Does it make sense and is it possible to enable this? This is related to my earlier comment — if I get it right, VSCode should update the required tools automatically if this is enabled.

2021-10-14 09:25 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		"go.lintOnSave": "package",
By default, `lintOnSave` uses `staticcheck`, however, we use `golangci-lint` in the CI. We should also set `go.lintTool` to `golangci-lint` so that lint recommendations are consistent with the CI.

2021-10-14 09:25 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		"go.formatTool": "goimports",
Is there some specific reason why we don't use the default format tool?

2021-10-14 09:25 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		"go.autocompleteUnimportedPackages": true,
As per [VSCode docs](https://github.com/golang/vscode-go/blob/master/docs/settings.md#goautocompleteunimportedpackages), this is not applicable when using the language server.

> Include unimported packages in auto-complete suggestions. Not applicable when using the language server.

2021-10-14 09:25 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		},
What's the reason for overriding this instead of using default values?

2021-10-14 09:25 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		},
Similar to above, what's the reason for overriding this instead of using default values?

2021-10-14 09:25 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		"davidanson.vscode-markdownlint",
I'm not really sure do we need to lint markdown files, but it might be useful.

2021-10-14 09:25 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		"redhat.vscode-yaml",
We already define this extension on L70.

2021-10-14 09:25 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		"lyyyuna.prow-sink",
TIL this extension exists.

2021-10-18 07:06 UTC, cedi commented on .devcontainer/devcontainer.json
> +		"redhat.vscode-yaml",
fixed

2021-10-18 07:07 UTC, cedi commented on .devcontainer/Dockerfile
> +FROM qmcgaw/godevcontainer
you can use any Docker Container. I just use `qmcgaw/godevcontainer` because it comes with go1.17 out of the box and already has many go tools already pre-installed

2021-10-18 07:40 UTC, cedi commented on .devcontainer/devcontainer.json
> +		"go.formatTool": "goimports",
I like it when I press save (with format on save enabled) and my imports are sorted and automatically imported as well

2021-10-18 07:49 UTC, cedi commented on .devcontainer/devcontainer.json
> +		},
I just like explicit configuration over "default". This is what works for me, but I'm happy to remove this config.

2021-10-18 07:49 UTC, cedi commented on .devcontainer/devcontainer.json
> +		"davidanson.vscode-markdownlint",
there is a Readme.md and some docs are in markdown ;)

2021-10-18 15:47 UTC, xmudrii requested changes

2021-10-18 15:47 UTC, xmudrii commented on .devcontainer/Dockerfile
> +FROM qmcgaw/godevcontainer
I'm wondering does it make sense to use [our build image](https://quay.io/repository/kubermatic/build) here because it contains all the binaries you may need to develop and run KKP. However, a potential problem is that the build image is huge — close to 1 GB. @xrstf Do you have any opinions on this?

2021-10-18 15:47 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +}
Please add a new line.

2021-10-18 15:47 UTC, xmudrii commented on .devcontainer/Dockerfile
> +RUN export GO111MODULE=on
Is there any specific reason why we don't use `ENV GO111MODULE=on` instead?

2021-10-18 15:47 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		"go.gotoSymbol.includeImports": true,
As per the [VSCode Go plugin docs](https://github.com/golang/vscode-go/blob/master/docs/settings.md#gogotosymbolincludeimports), this is not applicable when using the language server:

> If false, the import statements will be excluded while using the Go to Symbol in File feature. Not applicable when using the language server.

2021-10-18 15:47 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		"go.gotoSymbol.includeGoroot": true,
As per the [VSCode Go plugin docs](https://github.com/golang/vscode-go/blob/master/docs/settings.md#gogotosymbolincludegoroot), this is not applicable when using the language server:

> If false, the standard library located at $GOROOT will be excluded while using the Go to Symbol in File feature. Not applicable when using the language server.

2021-10-18 15:47 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		"codeQL.runningQueries.debug": true,
I don't see that we use [codeQL extension](https://marketplace.visualstudio.com/items?itemName=github.vscode-codeql). Does it make sense to set those values if we don't use the extension itself?

2021-10-18 15:47 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		"editor.snippetSuggestions": "none",
Why did you disable snippets? I think snippets can be useful, so I think we should leave them on.

2021-10-18 15:47 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		},
Are those options provided by VSCode or some plugin? I can't find anything about those options in the VSCode docs.

2021-10-18 15:47 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		"davidanson.vscode-markdownlint",
Of course we do have markdown files, but I'm not really fond of idea to lint markdown files, although, folks might have different opinions. :slightly_smiling_face:

2021-10-19 11:11 UTC, cedi commented on .devcontainer/Dockerfile
> +RUN export GO111MODULE=on
none other than me just being lazy ;)

2021-10-19 11:13 UTC, cedi commented on .devcontainer/devcontainer.json
> +		},
I actually don't know it for sure either. I just know I have this enabled in all my Go-Projects and it works :D 
It sorts my imports and I like that a lot actually. But I have no feelings for that

2021-10-21 10:47 UTC, xmudrii requested changes
There are a few variables set explicitly to their default values. I think we shouldn't specify variables if default values are satisfying. This makes the config easier to maintain.

2021-10-21 10:47 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		"go.lintOnSave": "package",
`go.lintOnSave` is `package` by default.

2021-10-21 10:47 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		"go.vetOnSave": "package",
`go.vetOnSave` is `package` by default.

2021-10-21 10:47 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		"go.formatTool": "goimports",
I think we can use the default tool without specifying it.

2021-10-21 10:47 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		"go.useLanguageServer": true,
`go.useLanguageServer` is `true` by default.

2021-10-21 10:47 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		"editor.renderFinalNewline": true,
`editor.renderFinalNewline` is `true` by default.

2021-10-21 10:47 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		"editor.codeLens": true,
`editor.codeLens` is `true` by default.

2021-10-21 10:47 UTC, xmudrii commented on .devcontainer/devcontainer.json
> +		"editor.insertSpaces": true,
`editor.insertSpaces` is `true` by default.

2021-11-17 20:17 UTC, xmudrii commented
@cedi There’s a conflict — we can’t merge the PR unless it’s rebased.

2021-11-24 18:43 UTC, cedi commented
@xmudrii rebased it

2021-11-29 08:33 UTC, xmudrii approved these changes
Thanks for the contribution, @cedi!

/lgtm
/approve
/test all

2021-11-29 08:45 UTC, xmudrii commented
```
[2021-11-29T08:34:51] Checking Kubermatic CE licenses...
time="Mon, 29 Nov 2021 08:34:51 UTC" level=warning msg="File is smaller than its boilerplate." file=.devcontainer/Dockerfile
time="Mon, 29 Nov 2021 08:34:52 UTC" level=error msg="1 out of 1469 checked files is invalid."
```

@cedi This is a legitimate failure. Can you please take a look into this?

2021-11-29 10:00 UTC, xmudrii commented
/lgtm cancel

2021-11-30 16:38 UTC, cedi commented
will have a look

2022-04-30 00:42 UTC, closed without merging