OpenAPI v3 CRD schema generation
kubermatic/kubermatic pull request #8027
Opened 2021-10-18 16:01 UTC by kron4eg

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
ref #7398

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
OpenAPI v3 CRD schema generation
```

2021-10-20 11:07 UTC, xrstf commented on hack/update-codegen.sh
> +  object:headerFile=./hack/boilerplate/ce/boilerplate.go.txt \
Where is the headerFile actually used? I don't see it in the generated YAML files.

2021-10-20 11:12 UTC, xrstf commented on pkg/apis/kubermatic/v1/datacenter.go
>  // Seed is the type representing a SeedDatacenter
`s/Datacenter//`. Otherwise it's super confusing.

2021-10-20 11:13 UTC, kron4eg commented on hack/update-codegen.sh
> +  object:headerFile=./hack/boilerplate/ce/boilerplate.go.txt \
in `pkg/apis/kubermatic/v1/zz_generated.deepcopy.go`, without specifying `headerFile=`, that file is loosing its header

2021-10-20 11:19 UTC, xrstf requested changes
Minor things

2021-10-20 16:01 UTC, kron4eg commented on pkg/apis/kubermatic/v1/datacenter.go
>  // Seed is the type representing a SeedDatacenter
Done

2021-10-21 13:40 UTC, xrstf approved these changes
/approve

:tada: So looking forward to this new world of schemas, specs, decks and ducks. Maybe not ducks.

2021-10-21 17:10 UTC, merged