Use strict TLS cipher suites for kubelet and kube-apiserver
kubermatic/kubermatic pull request #8054
Opened 2021-10-21 10:33 UTC by ahmedwaleedmalik

**What this PR does / why we need it**:

Kubernetes, by default, supports a vast number of TLS cipher suites including some with known security concerns which weakens the protection provided by them.

Hence, we are limiting the allowed cipher suites for `kubelet` and `kube-apiserver` to the recommended and most secure algorithms:

TLS 1.3 cipher suites:
```text
TLS_AES_128_GCM_SHA256
TLS_AES_256_GCM_SHA384
TLS_CHACHA20_POLY1305_SHA256
```

TLS 1.0 - 1.2 cipher suites:
```text
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubermatic/edgematic/issues/65

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2021-10-22 07:48 UTC, embik requested changes

2021-10-22 07:48 UTC, embik commented on pkg/resources/apiserver/deployment.go
> +		"--tls-cipher-suites", "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 ,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 ,TLS_ECDHE_RSA_WI
There's two spaces in here (probably from my ticket, sorry about that), one after `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` and one after `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384`, and I think that's breaking the test fixtures generated (it shouldn't be multiple lines with cipher suites).

2021-10-22 07:52 UTC, ahmedwaleedmalik commented on pkg/resources/apiserver/deployment.go
> +		"--tls-cipher-suites", "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 ,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 ,TLS_ECDHE_RSA_WI
No, I added them mistakenly somehow. It was resolved in my last commit.

2021-10-22 09:46 UTC, embik commented on addons/kubelet-configmap/kubelet-configmap.yaml
> +    tlsCipherSuites:
My understanding is limited, but I think this is only setting the cipher for kubelets that use the dynamic configuration feature/addon, no? And the dynamic configuration feature is deprecated in upstream Kubernetes, so it will go away eventually. I'm not sure where non-dynamic-configuration kubelets would set this, but probably in machine-controller?

2021-10-22 09:48 UTC, ahmedwaleedmalik commented on addons/kubelet-configmap/kubelet-configmap.yaml
> +    tlsCipherSuites:
Let me check, I'm not sure about this one.

2021-10-22 10:01 UTC, ahmedwaleedmalik commented on addons/kubelet-configmap/kubelet-configmap.yaml
> +    tlsCipherSuites:
@embik Just confirmed you are right and we need to modify the default `kubelet` config in `machine-controller`. Created a PR for that as well. 

https://github.com/kubermatic/machine-controller/pull/1077

2021-10-27 08:33 UTC, embik approved these changes
/lgtm

2021-10-27 08:48 UTC, kron4eg commented on pkg/resources/apiserver/deployment.go
> +		"--tls-cipher-suites", "TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WI
Please extract this list to the var []string{}, for visibility

2021-10-27 08:49 UTC, ahmedwaleedmalik commented on pkg/resources/apiserver/deployment.go
> +		"--tls-cipher-suites", "TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WI
Forgot to do that here, I'll fix this :+1:

2021-10-27 09:50 UTC, kron4eg commented on pkg/resources/resources.go
> +	KubeAPIServerTLSCypherSuites = "TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_E
I meant real
```
[]string{
    "TLS_AES_128_GCM_SHA256",
    "TLS_AES_256_GCM_SHA384",
    ...
}
```
It can be also exposed to the addons templates as a function so we can have consistent list.

2021-10-27 12:38 UTC, ahmedwaleedmalik commented on pkg/resources/resources.go
> +	KubeAPIServerTLSCypherSuites = "TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_E
Handled, PTAL.

2021-10-27 15:44 UTC, kron4eg approved these changes
/approve

2021-10-28 22:59 UTC, merged