patch GKE machine deployment version and size
kubermatic/kubermatic pull request #8250
Opened 2021-11-18 13:23 UTC by zreigz

**What this PR does / why we need it**: patch GKE machine deployment version and size

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8249

```release-note
```

2021-11-18 14:03 UTC, zreigz commented
/retest

2021-11-18 14:06 UTC, zreigz commented
/retest

2021-11-22 08:02 UTC, zreigz commented
@imharshita PTAL

2021-11-22 10:04 UTC, imharshita commented
/lgtm
/approve

2021-11-22 10:10 UTC, imharshita requested changes

2021-11-22 10:10 UTC, imharshita commented on pkg/handler/v2/external_cluster/gke.go
> +		}
Can you before returning new here update this as new has both replica and version patch `new.NodeDeployment.Spec.Template.Versions.Kubelet = old.Spec.Template.Versions.Kubelet`

2021-11-22 10:15 UTC, imharshita commented on pkg/handler/v2/external_cluster/gke.go
> +func patchGKEMachineDeployment(ctx context.Context, old, new *apiv2.ExternalClusterMachineDeployment, cluster *kubermaticapiv1.ExternalCluster, secretKeySelector provider.SecretKeySelectorValueFunc,
clusterProvider not used here

2021-11-22 10:20 UTC, zreigz commented on pkg/handler/v2/external_cluster/gke.go
> +func patchGKEMachineDeployment(ctx context.Context, old, new *apiv2.ExternalClusterMachineDeployment, cluster *kubermaticapiv1.ExternalCluster, secretKeySelector provider.SecretKeySelectorValueFunc,
I will fix this in the next PR

2021-11-22 10:21 UTC, zreigz commented
/retest

2021-11-22 10:44 UTC, zreigz commented
/retest

2021-11-22 11:46 UTC, imharshita commented
/lgtm
/approve

2021-11-22 14:01 UTC, zreigz commented
/retest

2021-11-22 14:28 UTC, imharshita commented
/lgtm

2021-11-22 18:12 UTC, zreigz commented
/retest

2021-11-22 19:48 UTC, zreigz commented
/retest

2021-11-22 20:07 UTC, merged