Nutanix cloud provider
kubermatic/kubermatic pull request #8448
Opened 2021-12-10 15:04 UTC by embik

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
```

2022-01-10 09:22 UTC, embik commented
/test pre-kubermatic-e2e-aws-ubuntu-1.21

2022-01-10 10:52 UTC, embik commented
/test pre-kubermatic-e2e-nutanix-ubuntu-1.22

2022-01-10 11:03 UTC, embik commented
/test pre-kubermatic-e2e-nutanix-ubuntu-1.22

2022-01-10 11:22 UTC, embik commented
/test pre-kubermatic-e2e-nutanix-ubuntu-1.22

2022-01-10 11:40 UTC, embik commented
/test pre-kubermatic-e2e-nutanix-ubuntu-1.22

2022-01-10 11:56 UTC, embik commented
/test pre-kubermatic-e2e-nutanix-ubuntu-1.22

2022-01-10 12:39 UTC, embik commented
/test pre-kubermatic-e2e-nutanix-ubuntu-1.22

2022-01-10 12:58 UTC, embik commented
/test pre-kubermatic-e2e-nutanix-ubuntu-1.22

2022-01-10 13:30 UTC, embik commented
/test pre-kubermatic-e2e-nutanix-ubuntu-1.22

2022-01-10 13:59 UTC, embik commented
/test pre-kubermatic-e2e-nutanix-ubuntu-1.22

2022-01-10 14:35 UTC, embik commented
/test pre-kubermatic-e2e-nutanix-ubuntu-1.22

2022-01-10 15:03 UTC, embik commented
/test pre-kubermatic-e2e-nutanix-ubuntu-1.22

2022-01-11 07:21 UTC, embik commented
/test pre-kubermatic-e2e-nutanix-ubuntu-1.22

2022-01-11 07:50 UTC, embik commented
/test pre-kubermatic-e2e-nutanix-ubuntu-1.22

2022-01-11 08:31 UTC, embik commented
/test pre-kubermatic-e2e-nutanix-ubuntu-1.22

2022-01-11 08:53 UTC, embik commented
/test pre-kubermatic-e2e-nutanix-ubuntu-1.22

2022-01-12 11:42 UTC, embik commented
/retest

2022-01-13 10:22 UTC, embik commented
/retest

2022-01-13 11:05 UTC, embik commented
/retest

2022-01-14 10:04 UTC, floreks commented
/approve

2022-01-14 12:43 UTC, xrstf commented on .golangci.yml
> +  - cyclomatic complexity [0-9]+ of func `GetAPIV2NodeCloudSpec` is high
a cute kitten just died

2022-01-14 12:43 UTC, xrstf commented on .prow.yaml
> +  - name: pre-kubermatic-e2e-nutanix-centos-1.22
please keep newlines between jobs

2022-01-14 12:45 UTC, xrstf commented on docs/zz_generated.seed.yaml
> +          port: null
Can we show the default value here?

2022-01-14 12:49 UTC, xrstf commented on pkg/handler/v1/provider/nutanix.go
> +	// "k8c.io/kubermatic/v2/pkg/provider"
leftovers?

2022-01-14 12:49 UTC, xrstf commented on pkg/handler/v1/provider/nutanix.go
> +*/
What's this?

2022-01-14 12:52 UTC, xrstf commented on pkg/provider/cloud/nutanix/client.go
> +		URL:      fmt.Sprintf("%s:%d", dc.Endpoint, port),
`net.JoinHostPort` maybe?

2022-01-14 12:55 UTC, xrstf commented on pkg/provider/cloud/nutanix/client.go
> +	}
Couldn't this be

```go
proxyURL := cloud.ProxyURL
if proxyURL == "" && cloud.CredentialsReference != nil {
   credsProxyURL, _ := secretKeyGetter(cloud.CredentialsReference, resources.NutanixProxyURL)
   if credsProxyURL != "" {
      proxyURL = credsProxyURL
   }
}
```

2022-01-14 12:56 UTC, xrstf commented on pkg/provider/cloud/nutanix/provider.go
> +Copyright 2021 The Kubermatic Kubernetes Platform contributors.
2022

2022-01-14 12:56 UTC, xrstf commented on pkg/provider/cloud/nutanix/provider.go
> +	logger.Infow("removing category values")
no `w` needed

2022-01-14 12:57 UTC, xrstf commented on pkg/provider/cloud/nutanix/provider.go
> +	logger.Infow("reconciling category and value")
no `w` needed

2022-01-14 12:58 UTC, xrstf commented on pkg/provider/kubernetes/credentials.go
> +
this empty line can go

2022-01-14 13:00 UTC, xrstf requested changes
consider yourself nutpicked

2022-01-14 13:01 UTC, embik commented on .golangci.yml
> +  - cyclomatic complexity [0-9]+ of func `GetAPIV2NodeCloudSpec` is high
Even that cute kitten can understand this function as it's dead simple, so I honestly don't feel too bad.

2022-01-14 13:06 UTC, embik commented on docs/zz_generated.seed.yaml
> +          port: null
Done!

2022-01-14 13:06 UTC, embik commented on pkg/handler/v1/provider/nutanix.go
> +*/
Leftover. It's gone now.

2022-01-14 13:06 UTC, embik commented on pkg/provider/cloud/nutanix/client.go
> +		URL:      fmt.Sprintf("%s:%d", dc.Endpoint, port),
Sure!

2022-01-14 13:06 UTC, embik commented on pkg/handler/v1/provider/nutanix.go
> +	// "k8c.io/kubermatic/v2/pkg/provider"
Yes, removed.

2022-01-14 13:06 UTC, embik commented on pkg/provider/cloud/nutanix/client.go
> +	}
Yeah you're right, that's better. Thanks!

2022-01-14 14:39 UTC, xrstf approved these changes
/approve
/hold

pls unhold when docker rate limitting is over

2022-01-14 19:50 UTC, embik commented
/retest

2022-01-15 08:05 UTC, embik commented
/retest

2022-01-15 09:04 UTC, embik commented
/retest

2022-01-15 09:50 UTC, embik commented
/hold cancel

2022-01-15 10:05 UTC, merged