Improve nginx-ingress helm chart upgrade process.
kubermatic/kubermatic pull request #8714
Opened 2022-01-12 16:44 UTC by wurbanski

**What does this PR do / Why do we need it**:
* Show the name of backup file in the logs
* notify user to either redeploy previous deployment or fix the errors before proceeding
* 
**Does this PR close any issues?**:

Fixes #8700

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2022-01-13 16:46 UTC, SimonTheLeg requested changes
Unfortunately I was not able to test this yet, as QA is currently having issues creating new clusters. Will get back on it tomorrow morning.

Apart from that, there was one small thing I noticed, that we can change already I think

2022-01-13 16:46 UTC, SimonTheLeg commented on pkg/install/stack/kubermatic-master/nginxingress.go
>  	} else {
_Unfortunately GH does not let me mark the whole area, but the following comment refers to line 125-131:_

This reminds me of another PR for cert-manager that I reviewed (#8392), and I think the same applies here: We should correctly catch API query issues. Additionally I think we can also simplify the code, by using one less else branch. I had something like this in mind

```go
// can of course also be the "if err..." one liner, no strong preference here
err := kubeClient.List....
if err != nil {
	// I think we always should catch that, as it is like a network error and not a "cannot find deployment"
	return fmt.Errorf("Error querying API for the existing deployment, aborting deployment")
}

switch foundDeployments....
```

2022-01-14 08:51 UTC, wurbanski commented on pkg/install/stack/kubermatic-master/nginxingress.go
>  	} else {
Definitely makes sense, I will change that as well :)

2022-01-14 10:29 UTC, wurbanski commented
/retest-required

2022-01-14 15:24 UTC, xrstf commented
Didn't we talk about purging the chart? Or am I mixing something up here?

2022-01-17 09:21 UTC, wurbanski commented
> Didn't we talk about purging the chart? Or am I mixing something up here?

That was for cert-manager, ingress seemed to be a little more straightforward to upgrade. This PR basically handles the negative path better.

2022-01-17 10:07 UTC, xrstf approved these changes
/approve

2022-01-17 13:45 UTC, SimonTheLeg commented
I have verified this PR by doing the following:

1. Setup a quick KKP 2.18.2 installation using the 2.18.2 installer
2. Add a broken nginx section to the `values.yaml` file
```yaml
nginx:
    controller:
        replicaCount: "thisshouldfail"
        service:
            annotations: "thisshouldfail"
```
3. Install using the installer from this branch (with ./charts dir from 2.19 release)
```
./kubermatic-installer-dev deploy --config kubermatic-configuration.yaml --helm-values values_219.yaml --storageclass aws --migrate-upstream-nginx-ingress --migrate-upstream-cert-manager
...

INFO[14:38:38]    📦 Deploying nginx-ingress-controller…
INFO[14:38:38]       nginx-ingress-controller: 1.2.2 detected, performing upgrade to 1.3.4…
INFO[14:38:38]       Backing up old ingress deployment…
INFO[14:38:38]       Attempting to store the deployment in file: backup_nginx-ingress-controller_2022-01-17T143838.yaml
INFO[14:38:38]       Deleting the deployment from the cluster
INFO[14:38:38]       Deploying Helm chart…
INFO[14:38:38]       Updating release from 1.2.2 to 1.3.4…
ERRO[14:38:42] ❌ Operation failed: failed to deploy nginx-ingress-controller: failed to deploy Helm release: failed to install: 
coalesce.go:199: warning: cannot overwrite table with non table for annotations (map[helm.sh/resource-policy:keep])
coalesce.go:199: warning: cannot overwrite table with non table for annotations (map[])
coalesce.go:199: warning: cannot overwrite table with non table for annotations (map[helm.sh/resource-policy:keep])
coalesce.go:199: warning: cannot overwrite table with non table for annotations (map[])
Error: UPGRADE FAILED: template: nginx-ingress-controller/charts/nginx/templates/controller-service.yaml:6:35: executing "nginx-ingress-controller/charts/nginx/templates/controller-service.yaml" at <.Values.controller.service.annotations>: range can't iterate over thisshouldfail

use backup file to restore the deployment or re-try the installation after fixing any errors..
```

Now the error message will be shown. We could slightly make it nicer by printing out the file location in the "use backup file to restore the deployment or re-try the installation after fixing any errors.." log line, but overall this works now as intended 👍

2022-01-17 13:46 UTC, SimonTheLeg commented
/approve

2022-01-17 13:46 UTC, SimonTheLeg approved these changes

2022-01-17 15:00 UTC, xrstf commented
/override pre-kubermatic-test-integration

vCenter issues.

2022-01-17 18:07 UTC, xrstf commented
/retest

2022-01-17 18:54 UTC, xrstf commented
/override pre-kubermatic-test-integration

vCenter issues.

2022-01-17 19:30 UTC, merged