Remove hostPattern and calculate from externalURL
kubermatic/kubermatic pull request #89
Opened 2016-10-12 23:16 UTC by scruplelesswizard

Remove %s pattern from externalURL

2016-10-12 23:17 UTC, scruplelesswizard commented
Attempting to limit the amount of unique configuration files required for a cluster

2016-10-13 10:28 UTC, lbb requested changes
Change  etcd-%s to a etcdURL var

2016-10-13 10:58 UTC, scruplelesswizard commented
@realfake please provide line comments where you would like changes made. If you are talking about https://github.com/kubermatic/api/pull/89/files#diff-3abb48fcbaeb2fb3f47ae2dbf4edbb83R334 that is where the `EtcdURL` is set... We could have an `EtcdURLFormat` constant somewhere, but I am not sure that is the best solution, especially as we are hoping to remove this etcd from the system

2016-10-13 11:51 UTC, scruplelesswizard commented on controller/cluster/pending.go
> +	c.Address.EtcdURL = fmt.Sprintf("https://etcd.%s.%s.%s", c.Metadata.Name, cc.dc, cc.etcdURL)
We use this `fmt.Sprintf( "%s.%s.%s", c.Metadata.Name, cc.dc, cc.etcdURL)` grouping a lot. It might be worthwhile to add it as a var on the cluster

2016-10-13 11:59 UTC, lbb approved these changes

2016-10-13 14:51 UTC, merged