initially hide node conditions
kubermatic/kubermatic pull request #895
Opened 2018-04-12 14:02 UTC by mrIncompetent

This PR adds a query parameter called `hideInitialConditions` which hides node conditions for nodes which are younger than 5 minutes.

**Release note**:
```release-note
NONE
```

2018-04-12 14:06 UTC, metalmatze requested changes
I like the approach. :joy: 
Only one small comment.

2018-04-12 14:06 UTC, metalmatze commented on api/pkg/handler/node_v2.go
> +	if time.Now().Sub(inputNode.CreationTimestamp.Time).Minutes() > 5 {
I'd go for: `time.Since(inputNode.CreationTimestamp.Time).Minutes()`

2018-04-12 14:06 UTC, mrIncompetent commented on api/pkg/handler/node_v2.go
> +	if time.Now().Sub(inputNode.CreationTimestamp.Time).Minutes() > 5 {
linting complaint was exactly that. Fixed

2018-04-12 14:15 UTC, metalmatze commented on api/pkg/handler/node_v2.go
> +	if time.Now().Sub(inputNode.CreationTimestamp.Time).Minutes() > 5 {
No need for a linter, when you have me as a reviewer. :joy:

2018-04-12 14:16 UTC, alvaroaleman commented on api/pkg/handler/node_v2.go
> +	if time.Since(inputNode.CreationTimestamp.Time).Minutes() > initialConditionParsingDelay {
MMh. I really dislike time-based approaches and I really dislike that is not possible at all anymore to get the info sooner.

What about adding an optional url parameter that when set will circumvent this?

2018-04-16 13:56 UTC, mrIncompetent commented
PTAL @metalmatze @alvaroaleman

2018-04-18 08:29 UTC, mrIncompetent commented
@alvaroaleman @metalmatze PTAL

2018-04-18 14:30 UTC, metalmatze approved these changes

2018-04-18 14:33 UTC, alvaroaleman commented
i like :+1:

2018-04-18 14:34 UTC, alvaroaleman approved these changes

2018-04-18 14:37 UTC, merged