Add Vsphere snapshotter
kubermatic/kubermatic pull request #9113
Opened 2022-02-24 20:33 UTC by WeirdMachine

**What does this PR do / Why do we need it**:

Adds the snapshot controller and validation webhook for vsphere csi

Fixes #9013

**Documentation**:
https://github.com/kubernetes-csi/external-snapshotter
https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/master/manifests/vanilla/deploy-csi-snapshot-components.sh

```release-note
Add vSphere Snapshotter
```

2022-02-25 07:25 UTC, WeirdMachine commented
/test pre-kubermatic-e2e-vsphere-ubuntu-1.21

2022-02-25 08:35 UTC, WeirdMachine commented
/test pre-kubermatic-e2e-vsphere-ubuntu-1.21

2022-02-25 13:11 UTC, WeirdMachine commented
/test pre-kubermatic-e2e-vsphere-ubuntu-1.21

2022-03-02 20:15 UTC, WeirdMachine commented
/retest

2022-03-03 07:22 UTC, WeirdMachine commented
/test pre-kubermatic-e2e-vsphere-ubuntu-1.21

2022-03-03 09:10 UTC, WeirdMachine commented
/test pre-kubermatic-e2e-vsphere-ubuntu-1.21

2022-03-22 12:30 UTC, xrstf commented on pkg/controller/user-cluster-controller-manager/resources/resources/csi-snapshotter/secret.go
> +package csisnaphotter
Typo in package name

2022-03-22 12:30 UTC, xrstf requested changes
Typonista

2022-03-23 07:41 UTC, WeirdMachine commented on pkg/controller/user-cluster-controller-manager/resources/resources/csi-snapshotter/secret.go
> +package csisnaphotter
Its obviously new component, the snap Hotter :fire:

2022-03-23 08:37 UTC, WeirdMachine commented
/retest

2022-03-23 13:50 UTC, xrstf commented
/approve
/retest

2022-03-23 15:14 UTC, xrstf commented
Those errors will be fixed once #9420 is merged. Sorry 'bout that.

2022-03-23 19:41 UTC, xrstf commented
/retest

2022-03-24 07:32 UTC, WeirdMachine commented
/retest

2022-03-28 11:00 UTC, WeirdMachine commented
/test pre-kubermatic-e2e-vsphere-ubuntu-1.21

2022-03-28 11:00 UTC, WeirdMachine commented
/retest

2022-03-29 11:48 UTC, xrstf commented
/lgtm

2022-03-29 13:04 UTC, merged