Glide cleanup
kubermatic/kubermatic pull request #92
Opened 2016-10-16 18:21 UTC by mrIncompetent

What was the issue:
Our glide.yaml manually defined all dependencies of kubernetes.
Since Glide is able to read and process the godep.json of kubernetes when we only define kubernetes alone as dependency our gilde.yaml was bigger than it should be and tried to manage dependencies of other project.
When we updated kubernetes from 1.3 -> 1.4 we did not updated the kubernetes dependencies in our own glide.yaml. This caused conflicts since we overwrite this way the versions of kubernetes dependencies.

With this pr we only define our own dependencies in the glide.yaml. If we have a shared dependency with kubernetes or so, we do specify it in the glide.yaml but we dont specify a version.

Please test if the oauth/jwt stuff still works, since i currently do not have a running local dev-env

2016-10-16 18:44 UTC, scruplelesswizard requested changes
A few nits. 

Also, for future, please make code changes and vendor changes in separate commits (`git add vendor/ && git commit -m "Updated vendoring" && git add . && git commit` )
//cc @realfake

2016-10-16 18:44 UTC, scruplelesswizard commented on glide.yaml
> +- packagUsere: github.com/ghodss/yaml
This doesn't look right?

2016-10-16 18:44 UTC, scruplelesswizard commented on handler/user.go
> +		return nil, fmt.Errorf("Invalid token in JWT in request %v", r)
Redundant statement. 
`"Invalid JWT in request %v"`

2016-10-16 19:19 UTC, mrIncompetent commented on glide.yaml
> +- packagUsere: github.com/ghodss/yaml
You're right. No idea how it came there...
Fixed with 004b1d4

2016-10-16 19:21 UTC, mrIncompetent commented on handler/user.go
> +		return nil, fmt.Errorf("Invalid token in JWT in request %v", r)
Fixed with b2cca25

2016-10-16 19:23 UTC, scruplelesswizard approved these changes
LGTM

2016-10-17 15:36 UTC, scheeles commented
LGTM

2016-10-17 17:09 UTC, merged