Update secret name for S3 credentials
kubermatic/kubermatic pull request #9230
Opened 2022-03-04 11:04 UTC by ahmedwaleedmalik

Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What does this PR do / Why do we need it**:
Currently, there is a conflict between the `s3-credentials` secret created by KKP and KubeOne. Both use the same secret name and deploy it in the same namespace i.e. kube-system. But the keys within the secret are different for both of them.

In a bid to solve this issue completely, we are renaming the secret in KKP first. So that the new secret `aws-s3-credentials` only has a single consumer. Next step is to rename this in KubeOne and add a deterministic prefix `kubeone-` to the secret name.

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Secret name for S3 credentials updated to `aws-s3-credentials`
```

2022-03-04 11:13 UTC, embik commented
Pretty sure some of the etcd backup logic expects this secret at that name, you might need to check that out. Probably also needs an update in our docs and an `Action required` notice if we choose to change the secret name expected by the backup.

2022-03-04 11:14 UTC, xrstf commented
I am not sure calling it "aws-s3-..." makes sense, as it's uber specific and it's not even pointing to AWS, it's by defaulting poiting to our Minio. Calling it "aws-something" is super misleading.

Also, why does KKP have to change it KubeOne just started to use the same name? KKP has a much longer history with this Secret. Why not fix KubeOne instead?

2022-03-04 11:16 UTC, ahmedwaleedmalik commented
> etcd backup logic expects this secret at that name

That's super wrong, why are we creating a secret using `minio` helm chart that is then being consumed by multiple components?

2022-03-04 11:28 UTC, xrstf requested changes
The secret was purposefully named after the _protocol_ (S3) and not the concrete backend. Calling it "aws-s3-..." or "minio-s3-..." is breaking that abstraction layer. That is also why we do not call it "AWS_ACCESS_KEY_ID".

A better name would be "kkp-s3-..." or "kubermatic-s3-..." to make sure it's related to KKP.

2022-03-04 11:29 UTC, ahmedwaleedmalik commented
Ah I forgot that minio would just need the creds for ANY S3 compatible storage.

2022-03-04 11:35 UTC, xrstf commented
The backup stuff isn't tied to Minio or AWS. You can use any S3-compatible object store.

2022-03-04 11:36 UTC, ahmedwaleedmalik commented
Yeah my poor memory didn't comply with me, I remember it now :)

2022-03-04 12:25 UTC, ahmedwaleedmalik commented
@xrstf PTAL

2022-03-04 12:27 UTC, ahmedwaleedmalik commented
> Pretty sure some of the etcd backup logic expects this secret at that name, you might need to check that out. Probably also needs an update in our docs and an Action required notice if we choose to change the secret name expected by the backup.

I'll update the docs. Not sure if this should break ANYTHING since we are updating all the references for the credentials as well.

2022-03-04 12:52 UTC, embik commented
> > Pretty sure some of the etcd backup logic expects this secret at that name, you might need to check that out. Probably also needs an update in our docs and an Action required notice if we choose to change the secret name expected by the backup.
> 
> I'll update the docs. Not sure if this should break ANYTHING since we are updating all the references for the credentials as well. But I can be wrong since I haven't explored the etcd backups part in KKP.

In that case, the release note needs an action required, given that people might create this credential manually when they dont use minio for backup. So they need to create the new Secret manually.

2022-03-04 13:06 UTC, ahmedwaleedmalik commented
@embik Updated, please check. Let me know, if the description is not sufficient.

2022-03-04 15:18 UTC, xrstf approved these changes
/approve

2022-03-04 15:19 UTC, merged

2022-03-07 09:50 UTC, ahmedwaleedmalik commented
/cherry-pick release/v2.20
/cherry-pick release/v2.19

2022-03-07 09:52 UTC, ahmedwaleedmalik commented
/cherry-pick release/v2.19