add preset controller
kubermatic/kubermatic pull request #9545
Opened 2022-04-06 11:32 UTC by zreigz

**What does this PR do / Why do we need it**: add a preset controller. Checks if preset was deleted and changes all affected clusters (set credential preset annotation)

**Does this PR close any issues?**:
Fixes #9464

```release-note
Add preset controller
```

2022-04-06 14:25 UTC, xrstf commented on pkg/controller/seed-controller-manager/preset-controller/controller.go
> +	ControllerName = "kkp_preset_controller"
Please use regular "-" and not underscores.

2022-04-06 14:26 UTC, xrstf commented on pkg/controller/seed-controller-manager/preset-controller/controller.go
> +		log.Debugf("The preset %s was deleted", preset.Name)
The log you're using already has the request as a context, there is no need to include the preset name in the log message again.

2022-04-06 14:26 UTC, xrstf commented on pkg/controller/seed-controller-manager/preset-controller/controller.go
> +			log.Errorw("Failed to get clusters", zap.Error(err))
Why is this error logged effectively twice? (once here, once in Reconcile())

2022-04-06 14:27 UTC, xrstf commented on pkg/controller/seed-controller-manager/preset-controller/controller.go
> +		log.Debugf("Update clusters after preset deletion")
Debug instead of Debugf

2022-04-06 14:27 UTC, xrstf commented on pkg/controller/seed-controller-manager/preset-controller/controller.go
> +				log.Debugf("Update cluster %s", cluster.Name)
Please use structured logging, i.e. `log.Debugw("Update cluster", "cluster", cluster.Name)`

2022-04-06 14:27 UTC, xrstf commented on pkg/controller/seed-controller-manager/preset-controller/controller.go
> +					log.Errorw("Failed to update cluster", zap.Error(err))
Why is this error logged twice?

2022-04-06 14:29 UTC, xrstf commented on pkg/controller/seed-controller-manager/preset-controller/doc.go
> +Package presetcontroller contains a controller that is responsible for managing presets.
To be honest, I read the ticket and the PR and I still don't know what this controller does or why. When a preset is deleted, it sets some annotation? Why? What is this used for? Can you please describe the purpose of this controller more than "The x-controller is a controller that controls X." :)

2022-04-06 14:29 UTC, xrstf commented on pkg/controller/seed-controller-manager/preset-controller/controller_test.go
> +					t.Fatalf("expected annotations for the cluster")
`t.Fatal` is enough here

2022-04-06 14:29 UTC, xrstf requested changes
A few comments

2022-04-07 09:12 UTC, zreigz commented
@xrstf thanks a lot for your review. PTAL

2022-04-07 11:19 UTC, xrstf approved these changes
/approve

2022-04-07 12:43 UTC, merged