Add e2e tests for Anexia
kubermatic/kubermatic pull request #9561
Opened 2022-04-07 16:30 UTC by ahmedwaleedmalik

Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What does this PR do / Why do we need it**:
Setting an Anexia cluster manually is slightly cumbersome. To mitigate that and to be consistent with our overall testing policy for cloud providers. We have added E2E tests for Anexia as well.

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2022-04-07 16:30 UTC, ahmedwaleedmalik commented
/test pre-kubermatic-e2e-anexia-ubuntu-1.23

2022-04-09 09:54 UTC, xrstf commented on cmd/conformance-tester/pkg/scenarios/anexia.go
> +	md, err := createMachineDeployment(num, s.version, getOSNameFromSpec(s.osSpec), s.osSpec, providerconfig.CloudProviderAlibaba, anexiatypes.RawConfig{
This still says Alibaba, slight copy-paste mistake ^^

2022-04-09 09:55 UTC, xrstf approved these changes
One minor typo, otherwise lgtm

2022-04-09 09:55 UTC, xrstf commented
/lgtm cancel

2022-04-09 09:56 UTC, xrstf requested changes
Whoops, clicked the wrong option previously.

2022-04-11 08:31 UTC, xrstf commented
/test pre-kubermatic-e2e-anexia-flatcar-1.23

2022-04-11 08:43 UTC, xrstf commented
So... I don't think we should merge this, if the new tests do not pass?

2022-04-12 08:01 UTC, ahmedwaleedmalik commented
>  So... I don't think we should merge this, if the new tests do not pass?

They won't pass since we don't have working anexia setup. Please read the discussion in `sig-cluster-management`.

2022-05-10 09:39 UTC, ahmedwaleedmalik commented
/test pre-kubermatic-e2e-anexia-flatcar-1.23

2022-05-10 10:00 UTC, ahmedwaleedmalik commented
/test pre-kubermatic-e2e-anexia-flatcar-1.23

2022-05-13 19:54 UTC, ahmedwaleedmalik commented
/test pre-kubermatic-e2e-anexia-flatcar-1.23

2022-05-13 19:58 UTC, ahmedwaleedmalik commented
/test pre-kubermatic-e2e-anexia-flatcar-1.23

2022-05-13 20:04 UTC, ahmedwaleedmalik commented
/test pre-kubermatic-e2e-anexia-flatcar-1.23

2022-05-13 20:29 UTC, ahmedwaleedmalik commented
Update: CCM fails, which should be fixed with https://github.com/kubermatic/kubermatic/pull/9335. Other than that we have a working cluster, nodes, etc.

2022-05-13 20:44 UTC, ahmedwaleedmalik commented
/test pre-kubermatic-e2e-anexia-flatcar-1.23

2022-05-16 03:38 UTC, ahmedwaleedmalik commented
/test pre-kubermatic-e2e-anexia-flatcar-1.23

2022-05-16 04:48 UTC, ahmedwaleedmalik commented
/retest

2022-05-16 07:16 UTC, ahmedwaleedmalik commented
@xrstf ready for review 😁

2022-05-16 09:52 UTC, xrstf approved these changes
Love it!

/approve

2022-05-16 10:49 UTC, merged