create preallocated DataVolume for cloning
kubermatic/kubermatic pull request #9578
Opened 2022-04-11 11:18 UTC by sankalp-r

**What does this PR do / Why do we need it**:
This PR introduces a new field  `AllocatedDataVolume` in `KubevirtCloudSpec` for DataVolume cloning.
**Does this PR close any issues?**:
Fixes #8491 

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:
UI for cluster creation with the KubeVirt provider needs to be updated to add this preallocated DataVolumes.

```release-note
None
```

Signed-off-by: Sankalp Rangare <sankalprangare786@gmail.com>

2022-04-11 12:47 UTC, sankalp-r commented
/retest

2022-04-11 17:41 UTC, sankalp-r commented
/retest

2022-04-15 12:15 UTC, ahmedwaleedmalik approved these changes
LGTM

/hold for @mfranczy to review

2022-04-19 07:46 UTC, mfranczy requested changes
Looks good, but please change the naming

2022-04-19 07:46 UTC, mfranczy commented on pkg/apis/kubermatic/v1/cluster.go
> +	AllocatedDataVolume []AllocatedDataVolume `json:"allocatedDataVolume,omitempty"`
please change to `PreAllocatedDataVolumes` the same for json

2022-04-19 07:46 UTC, mfranczy commented on pkg/provider/cloud/kubevirt/storage.go
> +func reconcileAllocatedDataVolume(ctx context.Context, cluster *kubermaticv1.Cluster, client ctrlruntimeclient.Client) error {
please change as well to reconcilePreAllocatedDataVolume

2022-04-20 13:01 UTC, mfranczy approved these changes
/approve
/lgtm

2022-04-20 13:33 UTC, mfranczy commented
/hold cancel

2022-04-20 14:36 UTC, merged