Alerts: fix CPU and Memory overcommit alerts
kubermatic/kubermatic pull request #9739
Opened 2022-05-04 09:54 UTC by vishnueg

Signed-off-by: vishnuegknr <vishnuegknr@gmail>

**What does this PR do / Why do we need it**:
This PR is created as we received an alert in Wacker PROD NUN location. After investigation, found the alert has been modified in the kubernetes-mixin. hence modifying the alert.

**Does this PR close any issues?**:
Fixes # https://kubermatic.freshservice.com/helpdesk/tickets/3780

**Special notes for your reviewer**:
This PR is created to modify the existing alert as it is already modified in kubernetes-mixin
**Documentation**:

https://github.com/prometheus-operator/prometheus-operator/issues/2406
https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/162
https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/646/files

**Does this PR introduce a user-facing change?**: NO

```release-note
```

2022-05-04 14:46 UTC, wurbanski requested changes

2022-05-04 14:46 UTC, wurbanski commented on charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml
> +        for: 10m
Please make sure to not change the formatting, it makes it harder to read the queries.

Remove parts coming straight from JSONNET (`%(ignoringOverprovisionedWorkloadSelector)s}`) and the like and replace them with correct query.

2022-05-04 17:22 UTC, xrstf commented on charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml
> +        for: 10m
Also, please update the file in `src/` and re-generate the rule files from there :)

2022-05-06 06:07 UTC, vishnueg commented on charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml
> +        for: 10m
> Please make sure to not change the formatting, it makes it harder to read the queries.
>  _Formatting done as per existing_
> Remove parts coming straight from JSONNET (`%(ignoringOverprovisionedWorkloadSelector)s}`) and the like and replace them with correct query.
> Completed , made the query correctly

2022-05-06 06:09 UTC, vishnueg commented on charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml
> +        for: 10m
> Also, please update the file in `src/` and re-generate the rule files from there :)

_Updated the file inside `src/genera/` . Please check and let me know if anything else needs to be done_

2022-05-10 08:12 UTC, wurbanski requested changes

2022-05-10 08:12 UTC, wurbanski commented on charts/monitoring/prometheus/rules/src/general/kube-state-metrics.yaml
>        runbook_url: https://docs.kubermatic.com/kubermatic/master/cheat_sheets/alerting_runbook/#alert-kubecpuovercommit
Please update the runbook_url in rendered alerts so that CI can pass :)

2022-05-10 08:12 UTC, wurbanski commented on charts/monitoring/prometheus/rules/src/general/kube-state-metrics.yaml
>        runbook_url: https://docs.kubermatic.com/kubermatic/master/cheat_sheets/alerting_runbook/#alert-kubememovercommit
Please update the runbook_url in rendered alerts so that CI can pass :)

2022-05-11 13:53 UTC, wurbanski commented
/lgtm

2022-05-11 13:58 UTC, wurbanski approved these changes

2022-05-11 14:57 UTC, merged