WIP update resource handling markdown
kubermatic/kubermatic pull request #9799
Opened 2022-05-11 14:53 UTC by SimonTheLeg

Signed-off-by: Simon Bein <simontheleg@gmail.com>

**What does this PR do / Why do we need it**:

Update documentation on resource handling

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2022-05-11 16:59 UTC, xrstf commented on docs/resource-handling.md
> +			// We don't need to set the object's name, as that's being done by the typed Reconcile function.
name _or namespace_

2022-05-11 17:00 UTC, xrstf requested changes
One minor improvement left

2022-05-16 14:15 UTC, SimonTheLeg commented on docs/resource-handling.md
> +			// We don't need to set the object's name, as that's being done by the typed Reconcile function.
As far as I understand it, "name". Afaik the namespace should not be set in the CreatorGetter, but rather passed directly to the corresponding typed Reconcile function.

That being said, I have now added a sentence to this paragraph to make this more clear. ptal

2022-05-16 15:45 UTC, xrstf approved these changes
/approve

2022-05-16 16:20 UTC, merged