removed buggy log sync
kubermatic/kubermatic pull request #9828
Opened 2022-05-16 15:33 UTC by lsviben

**What does this PR do / Why do we need it**:
Removes the deferred `log.Sync()` which causes:
```
"sync /dev/stderr: invalid argument"
```
on some OS. Its caused by: https://github.com/uber-go/zap/issues/370.%C2%A0, and there are no plans to fix it.
As its not essential, and just causes confusion because it fails on exit, so people think the whole binary failed, lets remove it.

**Does this PR introduce a user-facing change?**:

```release-note
Fixed `image-loader` and other binaries failing with "sync /dev/stderr: invalid argument", by removing the log.Sync() on command exit.
```

2022-05-16 15:37 UTC, xrstf requested changes
We do the same in nearly all binaries, so maybe we should ajdust all of them?

2022-05-16 15:46 UTC, xrstf commented
IIRC @embik had some strong-ish opinions on leaving out the sync last time I touched it, so let's allow them a chance to interject.

I would vote to remove the Sync() everywhere, because if we don't, someone(tm) (like me) will forget in half a year why the image-loader is "special" and bring back the seemingly missing Sync() call.

2022-05-16 15:49 UTC, lsviben commented
> IIRC @embik had some strong-ish opinions on leaving out the sync last time I touched it, so let's allow them a chance to interject.
> 
> I would vote to remove the Sync() everywhere, because if we don't, someone(tm) (like me) will forget in half a year why the image-loader is "special" and bring back the seemingly missing Sync() call.

Ok, will wait for @embik to give his 2 cents, if nothing against ill just remove it everywhere

2022-05-17 06:47 UTC, embik commented
> IIRC @embik had some strong-ish opinions on leaving out the sync last time I touched it, so let's allow them a chance to interject.

I don't remember having an opinion on this to be honest, so it cannot be that strong 🤷🏻‍♂️

2022-05-17 08:29 UTC, xrstf approved these changes
/approve

2022-05-17 12:36 UTC, merged